### ISSUE TITLE
serve:electron fails 

### ISSUE THREAD

**Issue by dspangenberg** [nklayman/vue-cli-plugin-electron-builder#1]
Hi,

unfortunately yarn serve:electron throws an error:
```
Error: spawn /Volumes/eSSD/Projects/twiceware-pro.de/electron\node_modules\.bin\electron-webpack ENOENT
Error: spawn /Volumes/eSSD/Projects/twiceware-pro.de/electron\node_modules\.bin\electron-webpack ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:178:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c vue-cli-service serve:electron
Directory: /Volumes/eSSD/Projects/twiceware-pro.de/electron
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Volumes/eSSD/Projects/twiceware-pro.de/electron/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
[yarn-error.log](https://github.com/nklayman/vue-cli-plugin-electron-builder/files/1901046/yarn-error.log)

**Comment by nklayman** [comment]
It seems that electron-webpack is not properly installed, as it is not in the node_modules/.bin folder. Run yarn install again, and then check the node_modules/.bin folder for electron-webpack and electron-builder. If they are missing, make sure they are listed in your package.json.

Also, if you ran `yarn install --dev vue-cli-plugin-electron-builder`, you must also run `vue invoke electron-builder` to complete setup. If you ran `vue add electron-builder`, then it should have been automatically invoked.

**Comment by dspangenberg** [comment]
Yes, same problem as #2. Thank you!
