### ISSUE TITLE
How to create .deb packages in vue electron-builder

### ISSUE THREAD

**Issue by Hariprabu94** [nklayman/vue-cli-plugin-electron-builder#1003]
Hi,Am tried to create .deb packages using vue electron:build. but, Its create only AppImage and snapd packages.

How to create .deb packages for all linux architectures? 
this is my json file configurations

{
  "name": "new",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "test:unit": "vue-cli-service test:unit",
    "lint": "vue-cli-service lint",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps"
  },
  "main": "background.js",
  "dependencies": {
    "animate.css": "^4.1.0",
    "bootstrap-vue": "^2.1.0",
    "canvas-gauges": "^2.1.7",
    "core-js": "^3.6.5",
    "nedb": "^1.8.0",
    "node-wifi": "^2.0.13",
    "simple-keyboard": "^2.29.102",
    "vue": "^2.6.11",
    "vue-canvas-gauges": "0.0.0",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0",
    "wifi-control": "^2.0.1"
  },
  "devDependencies": {
    "@babel/polyfill": "^7.7.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-unit-jest": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/test-utils": "^1.0.3",
    "babel-eslint": "^10.1.0",
    "bootstrap": "^4.3.1",
    "electron": "^9.0.0",
    "electron-devtools-installer": "^3.1.0",
    "electron-installer-debian": "^3.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "mutationobserver-shim": "^0.3.3",
    "popper.js": "^1.16.0",
    "portal-vue": "^2.1.6",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "vue-cli-plugin-bootstrap-vue": "~0.6.0",
    "vue-cli-plugin-electron-builder": "~2.0.0-rc.4",
    "vue-template-compiler": "^2.6.11"
  }
}

**Comment by nklayman** [comment]
Try `yarn electron:build --linux deb` (or `npm run electron:build -- --linux deb`). This will tell electron-builder to package your app as a `.deb` installer. See the [electron-builder docs](https://www.electron.build/cli#target) for more details.
