### ISSUE TITLE
nested iframe can not work

### ISSUE THREAD

**Issue by yexiaodong** [nklayman/vue-cli-plugin-electron-builder#1004]
**Describe the bug**
nested iframe can not work

**To Reproduce**
iframe1：http://localhost:8080/#/configIndex/westLeave.json
iframe2：http://localhost:8080/#/configView/flow
iframe2 can not work.

if iframe2 src change to http://localhost:8080/index.html/#/configView/flow  it can work in serve,but not work in build.

**Expected behavior**
I hope iframe2 can work

**Screenshots**
![image](https://user-images.githubusercontent.com/13914749/91374793-977d8b80-e84b-11ea-9503-0a40bd698d74.png)
![image](https://user-images.githubusercontent.com/13914749/91374961-ff33d680-e84b-11ea-9e9a-567cf3c939ad.png)

**Environment (please complete the following information):**
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz 
  Binaries:
    Node: 12.18.3 - D:\soft\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - D:\soft\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.12.1
    @vue/babel-preset-jsx:  1.1.1
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.1.1
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  3.12.1
    @vue/cli-plugin-babel: ^3.12.1 => 3.12.1
    @vue/cli-plugin-eslint: ^3.12.1 => 3.12.1
    @vue/cli-service: ^3.12.1 => 3.12.1
    @vue/cli-shared-utils:  3.12.1
    @vue/component-compiler-utils:  3.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.2.3 => 5.2.3 (4.7.1)
    vue: ^2.6.11 => 2.6.11
    vue-cli-plugin-electron-builder: ~2.0.0-rc.4 => 2.0.0-rc.4
    vue-eslint-parser:  5.0.0 (2.0.3)
    vue-hot-reload-api:  2.3.4
    vue-json-component: ^0.4.1 => 0.4.1
    vue-lazyload:  1.2.3
    vue-loader:  15.7.1
    vue-markdown: ^2.2.4 => 2.2.4
    vue-router: ^3.1.6 => 3.1.6
    vue-style-loader:  4.1.2
    vue-tabs-chrome: ^0.6.0 => 0.6.0
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.2.0 => 3.2.0
  npmGlobalPackages:
    @vue/cli: Not Found

**Comment by nklayman** [comment]
It won't work in build because the localhost server isn't available. You will have to point it at the [file loaded](https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/master/generator/templates/base/src/background.js#L32) in `background.js`.

**Comment by yexiaodong** [comment]
how should i modify my code

**Comment by nklayman** [comment]
It looks like your second iframe has `index.html` twice in the url. Try removing the duplicate and see if that helps.

**Comment by yexiaodong** [comment]
![image](https://user-images.githubusercontent.com/13914749/91508749-efc79280-e90a-11ea-8e4a-e73cbda09f3f.png)

**Comment by nklayman** [comment]
If you are loading from your app's code, why use an Iframe? just embed the component directly, it will be easier and more performant.

**Comment by yexiaodong** [comment]
app is visual editor，i hope each view contact far as possible to separate

**Comment by nklayman** [comment]
You should split your app into different [pages](https://cli.vuejs.org/config/#pages) and then load them in the iframe instead of trying to load a special route if you want full separation.

**Comment by yexiaodong** [comment]
I copy public/index.html to public/index2.html,but index2.html can not auto injected app.js.

**Comment by yexiaodong** [comment]
I copy pulbic/index.html to pulbic/index2.html,but can not auto injected app.js. how to change vue.config.js?

**Comment by yexiaodong** [comment]
I add index2.html,but the path is app://./index.htmlindex2.html#/configIndex/westLeave.json in build. (the code is normal in serve,how to remove index.html?)
