### ISSUE TITLE
Cookie cannot be set after electron:build

### ISSUE THREAD

**Issue by Liupeng8** [nklayman/vue-cli-plugin-electron-builder#1005]
**Describe the bug**
Cookie cannot be set after electron:build when I use [js-cookie](https://github.com/js-cookie/js-cookie),but at the develop-env is normal.

**To Reproduce**
1. vue create demo
2. cd demo
3. npm i
4. vue add electron-builder
5. choose electron 9.0 version
6. npm i js-cookie -S
7. at the vue page use js-cookie usage
8. npm run electron:build or npm run electron:serve

**Expected behavior**
at develop and build can be used normally.

**Screenshots**
develop env
![image](https://user-images.githubusercontent.com/23046680/91407878-821d5700-e875-11ea-8397-be3e803ac7a6.png)
build env
![image](https://user-images.githubusercontent.com/23046680/91408086-d6283b80-e875-11ea-9843-e34ae810beb8.png)

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: version=22.8.0 os=win10 x64
 - (if possible) link to your repo: 
 - terminal output from running `vue info`:

**Additional context**
electron7.x can be used normally.

**Comment by nklayman** [comment]
If it works in electron 7 then it most definitely doesn't have anything to do with this plugin. I also tried using js-cookie with the [electron-quick-start](https://github.com/electron/electron-quick-start) repo and it didn't work. I don't have much experience with cookies so I'm not sure what you could do, I'd suggest opening an issue on the electron repo instead..

**Comment by Liupeng8** [comment]
@nklayman many thanks

**Comment by Liupeng8** [comment]
@nklayman The electron team said it was caused by the electron-builder problem;I have posted issues on electron-builder, but I haven’t received any reply so far;I remember the vue-cli-plugin-electron-builder of 1.4.x version is depends on electron-builder version ^21.2.0,this version is normal;This question is very important to me, I hope I can get your help,many thanks.

**Comment by Ishu1998** [comment]
I solved this by adding this package https://github.com/heap/electron-cookies
