### ISSUE TITLE
import ipcRenderer in vue.js :  __dirname is not defined

### ISSUE THREAD

**Issue by raphael10-collab** [nklayman/vue-cli-plugin-electron-builder#1006]
I'm struggling to understand how to correctly import ipcRenderer in a .vue file.

I put in /src/background.js file :  

    webPreferences: {
      nodeIntegration:false,
      contextIsolation: true, // protects against prototype pollution
      preload: path.join(__dirname, "../dist_electron/preload.js"),
    }

And, based on https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration I put in preload.js : 

    window.ipcRenderer = ipcRenderer

webpack.config.js :  

    module.exports = {
      entry: './src/background.js',
      target: 'node',
      output: {
        path: path.join(__dirname, 'build'),
        filename: 'background.js'
      }
    }

In order to facilitate the debugging, I created a github repo.
You can git clone the repo from here: https://github.com/raphael10-collab/ElectronVueTypeScriptScaffolding.git

After executing yarn -> yarn electron:serve
you will get the correct page.

But when activating in /src/views/Home.vue this line:

//import { ipcRenderer } from 'electron'

you will get this error:

[__dirname is not defined][1]
![image](https://user-images.githubusercontent.com/70313067/91442481-31f0c580-e872-11ea-91b2-8d8902293cfb.png)

    Environment Info:

      System:
        OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
        CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
      Binaries:
        Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
        Yarn: 1.22.4 - /usr/bin/yarn
        npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
      Browsers:
        Chrome: 85.0.4183.83
        Firefox: 79.0
      npmPackages:
        @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
        @vue/babel-plugin-transform-vue-jsx:  1.1.2 
        @vue/babel-preset-app:  4.4.6 
        @vue/babel-preset-jsx:  1.1.2 
        @vue/babel-sugar-functional-vue:  1.1.2 
        @vue/babel-sugar-inject-h:  1.1.2 
        @vue/babel-sugar-v-model:  1.1.2 
        @vue/babel-sugar-v-on:  1.1.2 
        @vue/cli-overlay:  4.4.6 
        @vue/cli-plugin-babel: ~4.4.0 => 4.4.6 
        @vue/cli-plugin-e2e-cypress: ~4.4.0 => 4.4.6 
        @vue/cli-plugin-router: ~4.4.0 => 4.4.6 
        @vue/cli-plugin-typescript: ~4.4.0 => 4.4.6 
        @vue/cli-plugin-unit-mocha: ~4.4.0 => 4.4.6 
        @vue/cli-plugin-vuex: ~4.4.0 => 4.4.6 
        @vue/cli-service: ~4.4.0 => 4.4.6 
        @vue/cli-shared-utils:  4.4.6 
        @vue/component-compiler-utils:  3.2.0 
        @vue/preload-webpack-plugin:  1.1.2 
        @vue/test-utils: ^1.0.3 => 1.0.3 
        @vue/web-component-wrapper:  1.2.0 
        babel-helper-vue-jsx-merge-props:  2.0.3 
        typescript: ^3.9.7 => 3.9.7 
        vue: ^2.6.11 => 2.6.11 
        vue-class-component: ^7.2.5 => 7.2.5 
        vue-cli-plugin-electron-builder: ~2.0.0-rc.4 => 2.0.0-rc.4 
        vue-hot-reload-api:  2.3.4 
        vue-i18n: ^8.20.0 => 8.20.0 
        vue-loader:  15.9.3 
        vue-property-decorator: ^9.0.0 => 9.0.0 
        vue-router: ^3.2.0 => 3.3.4 
        vue-style-loader:  4.1.2 
        vue-template-compiler: ^2.6.11 => 2.6.11 
        vue-template-es2015-compiler:  1.9.1 
        vuex: ^3.5.1 => 3.5.1 
        vuex-class: ^0.3.2 => 0.3.2 
      npmGlobalPackages:
        @vue/cli: 4.4.6

    node version: v14.5.0

I tried also to set webPreferences as follows (with nodeIntegration: true) :  

    webPreferences: {
      nodeIntegration: true,
      //contextIsolation: true, // protects against prototype pollution
      //preload: path.join(__dirname, "../dist_electron/preload.js"),
    },

and got this error:

![image](https://user-images.githubusercontent.com/70313067/91442499-3b7a2d80-e872-11ea-98be-67fbaceb5211.png)

Searching around for info about this kind of problem, I found this post:
https://stackoverflow.com/questions/53841364/how-to-resolve-fs-existssync-is-not-a-function
With this link: https://webpack.js.org/concepts/targets/

But I already specified in webpack.config.js the target ‘node’:

in webpack.config.js :

    module.exports = {
      entry: './src/background.js',
      target: 'node',
      output: {
        path: path.join(__dirname, 'build'),
        filename: 'background.js'
      }
    }

So... how to solve this new problem?

By the way,
Why must I put

    webPreferences: {
        nodeIntegration: true,
    } 

if, for security reasons, it is more secure to have:

    webPreferences: {
      nodeIntegration:false,
      contextIsolation: true, // protects against prototype pollution
      preload: path.join(__dirname, "../dist_electron/preload.js"),
    }

dist_electron/preload.js :

    const {
        contextBridge,
        ipcRenderer
    } = require("electron");

    // Expose protected methods that allow the renderer process to use
    // the ipcRenderer without exposing the entire object
    contextBridge.exposeInMainWorld(
        "api", {
            send: (channel, data) => {
                // whitelist channels
                let validChannels = ["toMain"];
                if (validChannels.includes(channel)) {
                    ipcRenderer.send(channel, data);
                }
            },
            receive: (channel, func) => {
                let validChannels = ["fromMain"];
                if (validChannels.includes(channel)) {
                    // Deliberately strip event as it includes `sender` 
                    ipcRenderer.on(channel, (event, ...args) =>   
    func(...args));
                }
            }
        }
    );

    window.ipcRenderer = ipcRenderer

https://www.electronjs.org/docs/tutorial/security#electron-security-warnings

In vue.config.js I've put:

    module.exports = {
      pluginOptions: {
        electronBuilder: {
          preload: 'dist_electron/preload.js',
          // Or, for multiple preload files:
          //preload: { preload: 'src/preload.js', otherPreload: 
          //'src/preload2.js' }
        }
      }
    }

But I get the same error when I do 

    yarn electron:serve

[UncaughtReferenceError: __dirname is not defined][3]

When setting nodeIntegration: true (but I would prefer to set it to false, and use preload.js file), I get this other error (as above):

    Uncaught TypeError: fs.existsSync is not a function

![image](https://user-images.githubusercontent.com/70313067/91450944-2b1b8000-e87d-11ea-8f99-37afa3155c45.png)

How to solve the problem?
Looking forward to your kind help

**Comment by nklayman** [comment]
To enable `nodeIntegration`, you have to set it in `vue.config.js` so that the webpack build can be adjusted properly. See [the docs on nodeIntegration](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration) for details. It also seems like your preload config is a little weird, [see the preload file docs](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#preload-files) for instructions on that.

**Comment by raphael10-collab** [comment]
Hi @nklayman Noah!! Thank you for helping.

I updated vue.config.js with nodeIntegration and now vue.config.js is the following but still get "Uncaught ReferenceError: __dirname is not defined"  
![image](https://user-images.githubusercontent.com/70313067/91527485-264ede80-e906-11ea-989c-1acc25102401.png)
 

  vue.config.js :  

    module.exports = {
      // options...
      publicPath: '',
      pluginOptions: {
        electronBuilder: {
          // Prevent bundling of certain imported packages and instead retrieve these external dependencies at runtime.
          // In order to connect to websocket.
          externals: ['ggc'],
          builderOptions: {
            productName: 'GGC',
            win: {
              icon: './public/app.ico'
            },
            mac: {
              icon: './public/icons/Icon.icns',
              target: [
                'pkg',
                'dmg',
                'zip',
              ],
            },
            linux: {
              icon: './public/app.png'
            }
          }
        }
      }
    }

    // https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#webpack-configuration
    module.exports = {
      configureWebpack: {
        // Configuration applied to all builds
      },
      pluginOptions: {
        electronBuilder: {
          chainWebpackMainProcess: (config) => {
            // Chain webpack config for electron main process only
          },
          chainWebpackRendererProcess: (config) => {
            // Chain webpack config for electron renderer process only
            // The following example will set IS_ELECTRON to true in your app
            config.plugin('define').tap((args) => {
              args[0]['IS_ELECTRON'] = true
              return args
            })
          },
          // Use this to change the entrypoint of your app's main process
          mainProcessFile: 'src/background.js',
          // Provide an array of files that, when changed, will recompile the main process and restart Electron
          // Your main process file will be added by default
          //mainProcessWatch: ['src/myFile1', 'src/myFile2'],
          //mainProcessWatch: ['dist_electron/preload.js'],
          // Provide a list of arguments that Electron will be launched with during "electron:serve",
          // which can be accessed from the main process (src/background.js).
          // Note that it is ignored when --debug flag is used with "electron:serve", as you must launch Electron yourself
          // Command line args (excluding --debug, --dashboard, and --headless) are passed to Electron as well
          //mainProcessArgs: ['--arg-name', 'arg-value']
        }
      }
    }

    // https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#typescript-options
    module.exports = {
      pluginOptions: {
        electronBuilder: {
          // option: default // description
          disableMainProcessTypescript: false, // Manually disable typescript plugin for main process. Enable if you want to use 
    regular js for the main process (src/background.js by default).
          mainProcessTypeChecking: false // Manually enable type checking during webpck bundling for background file.
        }
      }
    }

    // https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#preload-files
    module.exports = {
      pluginOptions: {
        electronBuilder: {
          preload: 'dist_electron/preload.js',
          // Or, for multiple preload files:
          //preload: { preload: 'src/preload.js', otherPreload: 'src/preload2.js' }
        }
      }
    }

    // https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration
    module.exports = {
      pluginOptions: {
        electronBuilder: {
          nodeIntegration: true
        }
      }
    }

    // https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#web-workers
    const WorkerPlugin = require('worker-plugin')

    module.exports = {
      configureWebpack: {
        plugins: [new WorkerPlugin()]
      }
    }


What do you mean as "little weird" about preload config? The only difference I see is the path to the only preload.js file:
instead of preload: 'src/preload.js'  ------------> preload: 'dist_electron/preload.js'
or do I have to modify some other aspects?

webpack.config.js :  

    module.exports = {
      entry: './src/background.js',
      target: 'node',
      output: {
        path: path.join(__dirname, 'build'),
        filename: 'background.js'
      }
    }

    // https://github.com/GoogleChromeLabs/worker-plugin
    module.exports = {
      plugins: [
        new WorkerPlugin()
      ]
    }

**Comment by raphael10-collab** [comment]
@nklayman  Now I'm getting this error : Cannot read property 'match' of undefined

![image](https://user-images.githubusercontent.com/70313067/91643493-fa317b80-ea33-11ea-9c71-15901e1572dd.png)

I do not have any clue about this kind of problem, because it doesn't point to any specific file
Would you be so kind in having a loot at this github repo? https://github.com/raphael10-collab/ElectronVueTypeScriptScaffolding

**Comment by raphael10-collab** [comment]
I do not know  why, but it works now...
