### ISSUE TITLE
Loading local file with `local-resource://` throws CORS error

### ISSUE THREAD

**Issue by Yiddishe-Kop** [nklayman/vue-cli-plugin-electron-builder#1007]
Hi 👋

I'm following the [documentation](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#loading-local-images-resources) and registered a file protocol to load local files without having to set `webSecurity: false`.

But I get this CORS error:
`Access to audio at 'yiddishe-kop-protocol:///Users/.../Library/Application Support/jkaraoke-desktop/blob/9' from origin 'http://localhost:8080' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, https.`

Here is a [link](https://github.com/Yiddishe-Kop/jkaraoke-desktop/blob/master/src/background.js) to my `background.js` file.
And a [link](https://github.com/Yiddishe-Kop/jkaraoke-desktop/blob/17bf44cab870f09f34fd8a26268c5f14a727d42f/src/components/AudioPlayer.vue#L187) to my `<audio>` element that is trying to use the protocol.

For now I'll just be setting `webSecurity: false`, but this is [strongly discouraged](https://www.electronjs.org/docs/tutorial/security#5-do-not-disable-websecurity)...

**Environment:**
  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
  Binaries:
    Node: 12.18.1 - /usr/local/opt/node@12/bin/node
    Yarn: 1.19.2 - ~/.npm/bin/yarn
    npm: 6.14.4 - ~/.npm/bin/npm
  npmPackages:
    @ant-design-vue/babel-helper-vue-transform-on:  1.0.1 
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.5.4 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.5.4 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.4 
    @vue/cli-plugin-pwa: ~4.5.0 => 4.5.4 
    @vue/cli-plugin-router: ~4.5.0 => 4.5.4 
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.4 
    @vue/cli-service: ~4.5.0 => 4.5.4 
    @vue/cli-shared-utils:  4.5.4 
    @vue/component-compiler-utils:  3.1.2 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    portal-vue: ^2.1.7 => 2.1.7 
    vue: ^2.6.11 => 2.6.11 
    vue-class-component:  7.2.3 
    vue-cli-plugin-electron-builder: ~1.4.6 => 1.4.6 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.2 (16.0.0-beta.3)
    vue-property-decorator:  8.5.1 
    vue-router: ^3.2.0 => 3.3.2 
    vue-slider-component: ^3.2.5 => 3.2.5 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.4.0 => 3.5.1 
    vuex-electron: ^1.0.3 => 1.0.3 
  npmGlobalPackages:
    @vue/cli: 4.2.3

**Comment by nklayman** [comment]
I removed the `crossorigin="anonymous"` and it seemed to fix the issue. Try and see if that fixes it for you.

**Comment by Yiddishe-Kop** [comment]
Yes, it works 😎 , but when I remove  `webSecurity: false` it goes back to the CORS error 🤷‍♂️ .

**Comment by D4RKAR117** [comment]
This is kinda related with this https://github.com/electron/electron/issues/23664, to fix it i put in my background.ts this 
```app.commandLine.appendSwitch('disable-features', 'OutOfBlinkCors')``` before create window its called, like they say in the electron issue

**Comment by Yiddishe-Kop** [comment]
@D4RKAR117 It doesn't seem to fix the issue.
I still get the same CORS error.

**Comment by nklayman** [comment]
@Yiddishe-Kop it works for me even without `webSecurity: false`. Try with a new project and see if it works there.
