### ISSUE TITLE
SCSS broke after build

### ISSUE THREAD

**Issue by Proladon** [nklayman/vue-cli-plugin-electron-builder#1009]
## In Develop (yarn electron:serve):
![image](https://user-images.githubusercontent.com/35193493/91549142-101e3e00-e959-11ea-87fb-9bef927656fb.png)
```html
<style scoped lang="scss">
.operate-btn-wrapper{
    position: absolute;
    top: 0;
    width: 100%;
    height: 70px;
    background-color: white;
    opacity: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    transition: ease-in-out 0.3s;
}

.operate-btn-wrapper:hover{
    opacity: 30%;
}
</style>
```

## After Build (yarn electron:serve)
![image](https://user-images.githubusercontent.com/35193493/91549399-77d48900-e959-11ea-85e3-6756bee719e1.png)
![image](https://user-images.githubusercontent.com/35193493/91549414-7d31d380-e959-11ea-9ee0-049f71b4ed60.png)

#### **It change my `.operate-btn-wrapper:hover` style: opacity 30% to 1% ..... dumb.**
and l'v tried change `opacity` to `width` or `height` and... it works...
**actually all hover opacity will auto change to 1% after build**
so... idk what happened with `opacity` ??

## evnInfo:
```
  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 14.7.0 - E:\nodejs\node.EXE
    Yarn: 1.22.4 - E:\Yarn\bin\yarn.CMD
    npm: 6.14.7 - E:\nodejs\npm.CMD
  Browsers:
    Chrome: 85.0.4183.83
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    electron-builder  version=22.8.0

    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.4.6
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.4.6
    @vue/cli-plugin-babel: ~4.4.0 => 4.4.6
    @vue/cli-plugin-eslint: ~4.4.0 => 4.4.6
    @vue/cli-plugin-router:  4.4.6
    @vue/cli-plugin-vuex: ~4.4.0 => 4.4.6
    @vue/cli-service: ~4.4.0 => 4.4.6
    @vue/cli-shared-utils:  4.4.6
    @vue/component-compiler-utils:  3.2.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    vue: ^2.6.12 => 2.6.12
    vue-cli-plugin-electron-builder: ~2.0.0-rc.4 => 2.0.0-rc.4
    vue-color: ^2.7.1 => 2.7.1
    vue-eslint-parser:  7.1.0
    vue-hot-reload-api:  2.3.4
    vue-js-modal: ^2.0.0-rc.6 => 2.0.0-rc.6
    vue-loader:  15.9.3
    vue-notification: ^1.3.20 => 1.3.20
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.12 => 2.6.12
    vue-template-es2015-compiler:  1.9.1
    vuedraggable: ^2.24.1 => 2.24.1
    vuex: ^3.4.0 => 3.5.1
```

**Comment by Proladon** [comment]
I found the problem, cuz `Anime.js` conflict.
but still wired between develop and build why different css display.

**Comment by nklayman** [comment]
The snippet you provided works for me. You said there was a conflict in another file, so I will need that as well to debug this, or preferably the full repo.

**Comment by Proladon** [comment]
> The snippet you provided works for me. You said there was a conflict in another file, so I will need that as well to debug this, or preferably the full repo.

Actually, is not "conflict", this is my use words, sorry 😅

the problem snippet:
```js
mounted(){
    anime({
        targets: [".files-viewer"],
        opacity: ["0", "100"],   // problem here
        duration: 1000,
        easing: "easeInOutQuad",
    });
}
```
this will cause all child under the `.files-viewer` div that opacity style auto change to 1% after build.
(or all elements which has opacity style, idk, cuz i didn't tried anymore testing Lol.)

solved:
```js
mounted(){
    anime({
        targets: [".files-viewer"],
        opacity: ["0", "1"],   // just change 100 to 1
        duration: 1000,
        easing: "easeInOutQuad",
    });
}
```
so seems `Anime.js` cause the issue.
but as my last comment, it will display normally until it build. and i think this is more important issue.

**Comment by nklayman** [comment]
Can you test this in a non-electron build/serve? Seems like it'd be an issue with vue cli rather than this plugin.

**Comment by Proladon** [comment]
> Can you test this in a non-electron build/serve? Seems like it'd be an issue with vue cli rather than this plugin.

Sorry for late reply .
I'v tested today, and yes, as you said, seems like it'd be an issue with vue cli.
fine when `yarn serve` but auto change opacity to 1% when `yarn build`.

**Comment by nklayman** [comment]
You should probably open an issue on the vue-cli repo then, as it appears the issue doesn't relate to this plugin.
