### ISSUE TITLE
Integration with nbind or ffi-napi

### ISSUE THREAD

**Issue by nathansalwen** [nklayman/vue-cli-plugin-electron-builder#101]
Hi,

I don't know if this is a bug, or more likely user error but I am having trouble integrating this with certain node packages, particularly those that allow access to external C++ libraries. Thank you for any help and sorry if this is the wrong forum for this. 

I confirmed fs and path node packages work. However, nbind and ffi-napi do not.  I am running the following versions
> "autogypi": "^0.2.2",
>     "ffi-napi": "^2.4.3",
>     "fs": "^0.0.1-security",
>     "nbind": "^0.3.15",
>     "node-gyp": "^3.8.0",
>     "path": "^0.12.7",
>     "vue": "^2.5.17"
> $ node --version
> v10.10.0
> $ npm --version
> 6.4.1
> $ yarn --version
> 1.10.1
I install vue and electron-builder and go through the steps to run nbind or simply install ffi-napi but when I run I see errors trying to access the file system.
$ vue create electron-vue-nbind
$ cd electron-vue-nbind/
I create hello.cc as follows (for nbind) 
```
#include <string>
#include <iostream>
struct Greeter {
  static void sayHello(
    std::string name
  ) {
    std::cout
      << "Hello, "
      << name << "!\n";
  }
};
#include "nbind/nbind.h"
NBIND_CLASS(Greeter) {
    method(sayHello);
}
```
$ yarn add nbind autogypi node-gyp ffi-napi fs path 
I modify package.json to add the scripts (for nbind) 
```
    "autogypi": "autogypi",
    "build:electron": "vue-cli-service build:electron",
    "copyasm": "copyasm",
    "emcc-path": "emcc-path",
    "ndts": "ndts",
```
The next 2 steps are for nbind and the one after is for the test of fs/path
$ npm run -- autogypi   --init-gyp   -p nbind -s hello.cc
$ npm run -- node-gyp   configure build
$ echo "this is a test" > public/myText.txt
$ vue add electron-builder
Then I modify src/main.js to test fs/path and then nbind (node-ffi is commented out)
```
const fileLocation = path.join(__static, 'myText.txt')
const fileContents = fs.readFileSync(fileLocation, 'utf8')
console.log(fileContents)
//const ffi = require('ffi-napi')
const nbind = require('nbind')
var lib = `nbind.init().lib;`
```
$ yarn serve:electron
The console shows
> this is a test
> 
> /home/ns/tmp/electron-vue-nbind/nbind.node
> /home/ns/tmp/electron-vue-nbind/build/nbind.node
> /home/ns/tmp/electron-vue-nbind/build/Debug/nbind.node
> /home/ns/tmp/electron-vue-nbind/build/Release/nbind.node
> /home/ns/tmp/electron-vue-nbind/out/Debug/nbind.node
> /home/ns/tmp/electron-vue-nbind/Debug/nbind.node
> /home/ns/tmp/electron-vue-nbind/out/Release/nbind.node
> /home/ns/tmp/electron-vue-nbind/Release/nbind.node
> /home/ns/tmp/electron-vue-nbind/build/default/nbind.node
> /home/ns/tmp/electron-vue-nbind/compiled/8.9.3/linux/x64/nbind.node
> /home/ns/tmp/electron-vue-nbind/nbind.js
> /home/ns/tmp/electron-vue-nbind/build/nbind.js
> /home/ns/tmp/electron-vue-nbind/build/Debug/nbind.js
> /home/ns/tmp/electron-vue-nbind/build/Release/nbind.js
> /home/ns/tmp/electron-vue-nbind/out/Debug/nbind.js
> /home/ns/tmp/electron-vue-nbind/Debug/nbind.js
> /home/ns/tmp/electron-vue-nbind/out/Release/nbind.js
> /home/ns/tmp/electron-vue-nbind/Release/nbind.js
> /home/ns/tmp/electron-vue-nbind/build/default/nbind.js
> /home/ns/tmp/electron-vue-nbind/compiled/8.9.3/linux/x64/nbind.js
>     at findCompiledModule (nbind.js?b3db:83)
>     at find (nbind.js?b3db:93)
>     at Object.init (nbind.js?b3db:104)
>     at eval (webpack-internal:///./src/main.js:27)
>     at Module../src/main.js (app.js:2001)
>     at __webpack_require__ (app.js:725)
>     at fn (app.js:102)
>     at Object.0 (app.js:2014)
>     at __webpack_require__ (app.js:725)
>     at app.js:792
> 
I notice that the file /home/ns/tmp/electron-vue-nbind/build/Release/nbind.node does exist so I think it has something to do with the file connection even though the fs,readFileSync call worked.

If I comment out the nbind call in main.js but uncomment the ffi-napi require I get a different error but it may be related.
> this is a test
> 
> Uncaught TypeError: Path must be a string. Received undefined
>     at assertPath (path.js:28)
>     at dirname (path.js:1364)
>     at Function.getRoot (bindings.js?dfc1:151)
>     at bindings (bindings.js?dfc1:60)
>     at eval (webpack-internal:///./node_modules/ref-napi/lib/ref.js:7)
>     at Object../node_modules/ref-napi/lib/ref.js (app.js:1889)
>     at __webpack_require__ (app.js:725)
>     at fn (app.js:102)
>     at eval (webpack-internal:///./node_modules/ffi-napi/lib/ffi.js:7)
>     at Object../node_modules/ffi-napi/lib/ffi.js (app.js:1727)

**Comment by nklayman** [comment]
Try setting them as externals. See docs [here](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#table-of-contents)

**Comment by nathansalwen** [comment]
Thank you! 

I created the file vue.config.js and added the entry below and the error message no longer appears.  I had a suspicion that the issue was with webpack.  As a documentation improvement, I think it would be worthwhile to change the line in the docs to "It should get found automatically, but it might not. To do this, use the externals option [(added) in vue.config.js]:" I wasn't certain whether that was to go in a webpack config or in vue.config.js.

// vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      // List native deps here if they don't work
      externals: ['ffi-napi']
    }
  }
}
