### ISSUE TITLE
Running electron:build returns exit code 0, even if it fails packaging

### ISSUE THREAD

**Issue by rathboma** [nklayman/vue-cli-plugin-electron-builder#1017]
**Describe the bug**
Run a build that passes babel and ts compilation but fails during packaging. It should return exit code > 0, but returns 0.

This breaks our CI release system, which just thinks everything worked fine

**To Reproduce**
Build a Deb on a raspberry pi 4 without installing fpm manually first, it will fail.

Build a MacOS notarized dmg file. Sometimes it times out and fails

**Expected behavior**
Exit code of > 0 should be returned

**Screenshots**

**Environment (please complete the following information):**
- Mac or Linux
 

**Additional context**
Not sure if this is a vue cli plugin issue, or an electron builder issue?

Any help here is appreciated.

**Comment by nklayman** [comment]
Thanks for the report, fix will be in next release!

**Comment by rathboma** [comment]
Thanks! Wasn't sure if this was anything to do with the Vue Cli plugin. As always @nklayman you rock
