### ISSUE TITLE
extraRources configuration does not work.

### ISSUE THREAD

**Issue by devie2020** [nklayman/vue-cli-plugin-electron-builder#1018]
![image](https://user-images.githubusercontent.com/33315229/91935977-83d99580-ed21-11ea-8ba8-63ce4960dc78.png)
![image](https://user-images.githubusercontent.com/33315229/91935998-8d62fd80-ed21-11ea-9bbc-f258f64a4cb9.png)

**Comment by nklayman** [comment]
Works fine for me. Please open a new issue that follow the bug report template, I need more information to debug this.

**Comment by devie2020** [comment]
First of all,  thanks very much of your reply. This problem is caused by the custom path, which has been solved. Thank you again.
________________________________
发件人: Noah Klayman <notifications@github.com>
发送时间: 2020年9月4日 9:13
收件人: nklayman/vue-cli-plugin-electron-builder <vue-cli-plugin-electron-builder@noreply.github.com>
抄送: Devie.Huang <devie.huang@outlook.com>; Author <author@noreply.github.com>
主题: Re: [nklayman/vue-cli-plugin-electron-builder] extraRources configuration does not work. (#1018)


Works fine for me. Please open a new issue that follow the bug report template, I need more information to debug this.

―
