### ISSUE TITLE
Webpack bundling error - Multiple Vue instances / BrowserWindows

### ISSUE THREAD

**Issue by 4eveRS** [nklayman/vue-cli-plugin-electron-builder#102]
**Describe the bug**
I need to bundle multiple vue instances in separated files for different browserWindows.

I duplicated main.js and changed the vue instance renderer and component, to make it a different instance on a new BrowserWindow.

After that I added a button on the main window (App.vue) just to open a new BrowserWindow, that points to public/browser.html, which is where the new vue instance will render.

I though it would work out of the box, but unfortunately, it doesn't. So after a lot of research I fount out a partial solution using vue.config.js.

So I created a vue.config.js file with the following content:

```
const HtmlWebpackPlugin = require('html-webpack-plugin');
const path = require('path');

module.exports = {
  pluginOptions: {
    electronBuilder: {
      chainWebpackRendererProcess: config => {
        // Configuration applied to all builds
        config.entry('browser').add(path.join(__dirname, '/src/browser.js'));

        config.plugin('browser').use(HtmlWebpackPlugin, [{
          filename: 'browser.html',
          template: './public/browser.html',
          templateParameters: {
            'BASE_URL': process.env.NODE_ENV === 'production' ? './' : '',
            'VUE_APP_NODE_MODULES_PATH': process.env.NODE_ENV === 'production' ? 'false' : '',
            '__static': __dirname
          },
          chunks: ['browser', 'chunk-vendors'],
        }]);
      }
    }
  }
}
```

It was showing BASE_URL, VUE_APP_NODE_MODULES_PATH not defined errors once I tried to bundle the app. Until I found about the templateParameters. (**Not sure if my approach/code is correct**)

Everything seems to be working fine, until I inspected the main page, and found out that it's using the browser.js that was bundled by webpack. While the browser.html is working perfectly, only using browser.js and chunk-vendors.js.

I tried to override the app.js plugin adding the following code on vue.config.js:

```
config.plugin('app').use(HtmlWebpackPlugin, [{
          filename: 'index.html',
          template: './public/index.html',
          templateParameters: {
            'BASE_URL': process.env.NODE_ENV === 'production' ? './' : '',
            'VUE_APP_NODE_MODULES_PATH': process.env.NODE_ENV === 'production' ? 'false' : '',
            '__static': __dirname
          },
          chunks: ['app', 'chunk-vendors'],
        }]);
```

It worked perfectly on the npm run serve:electron. But when I try to bundle it for production this errors shows up on my terminal:

![console_error](https://user-images.githubusercontent.com/4212200/46556575-70b3b600-c8bd-11e8-82af-d8563c250654.png)

it seems that it builds the legacy bundle just right, and when it's creating the modern bundle, it fails and get stuck in this forever.

I know it's probably something that I'm doing wrong on my webpack, but I couldn't find any solution to this issue.

Thanks in advance.

**Comment by 4eveRS** [comment]
it seems that once I override the 'app' plugin, all legacy-assets-_var_.html.json aren't created and so it can't generate the modern bundle.

**Comment by nklayman** [comment]
For now, just run `build:electron` with the `--legacy` arg to disable modern mode. Note that this feature was added in 1.0.0-rc.3. I will look into finding a better solution later.

**Comment by 4eveRS** [comment]
just a feedback, using --legacy fixed my problems for the moment. Looking forward to a option to use modern mode.

**Comment by nklayman** [comment]
I think this is related to vue-cli, not this plugin, as it fails while building the renderer process. Try opening an issue there.

**Comment by nklayman** [comment]
I think this is fixed in the latest commit. This will be part of the next release. If you want to use it now, you will need to download this plugin from the github repo, to do so:

1. in `package.json`, set `vue-cli-plugin-electron-builder` to `nklayman/vue-cli-plugin-electron-builder`
2. run `yarn install` or `npm install`
3. now, remove the `<% if (BASE_URL === './') { %><base href="app://./" /><% } %>` from `public/index.html`
4. you should be good to go, build your app and see if it works!

**Comment by stuible** [comment]
Using the --legacy flag did not work in my case (I followed the method from #182)
