### ISSUE TITLE
preload.js with a webview within renderer process

### ISSUE THREAD

**Issue by tukutela** [nklayman/vue-cli-plugin-electron-builder#1020]
Hi,

I'm attempting to run a variable number of ```<webview />``` tags within the renderer process (eg. BrowserWindow). Basically attempting to use IPCRenderer to pass commands to webview pages and receive the asynchronous result. 

To set the communication up between the ```renderer``` to the ```<webview />```, you need to add a ```preload``` attribute like so. 

In ```App.vue```:
```<webview src="xxxxxxxx" preload="file://./enableIPC.js" nodeintegration />```.

I've done this with Electron as standard, however when using Vue CLI Plugin Electron Builder, I can't get it to see and load up the ```enableIPC.js``` file. 

I've placed the file in the ```public/``` folder. 

![image](https://user-images.githubusercontent.com/340768/92296843-50df0e00-ef7c-11ea-8c84-c21e67b82b06.png)

I've tried with and without ```file://```, attempting to include in it within the electronBuilder preload key, with no luck. Had anybody tried this successfully and can point me to a repo? 

Thanks in advance. 

Note: I'm using electron version 10.1.1

**Comment by nklayman** [comment]
Try using the `app` instead of `file` protocol.

**Comment by tukutela** [comment]
Hey Noah, thanks for responding! 

Do you have an example somewhere I can look at? do you mean?

```<webview src="xxxxxxxx" preload="require('./enableIPC.js')" nodeintegration />```

**Comment by nklayman** [comment]
Like this:

```
<webview src="xxxxxxxx" preload="app://./enableIPC.js" nodeintegration />.
```

With enableIPC in the public folder.

**Comment by tukutela** [comment]
Didn't think of that! Gave it a go and got......

![image](https://user-images.githubusercontent.com/340768/92317461-16d93f00-f044-11ea-9fe0-bdde0878268b.png)

**Comment by tukutela** [comment]
I got it! I think a part of the problem was that I wasn't testing the right thing, my bad. 

had to create a data attribute:

```
data() {
    return {
      /* eslint-disable */
      preload: `file://${require('path').join(__static, 'enableIPC.js')}`
      /* eslint-enable */
    }
  },
```

and then reference it in the webview like so. 

```
<webview src="xxxxxxxx" :preload="preload" nodeintegration />.
```

Thanks for your help!

**Comment by nklayman** [comment]
Glad that you figured it out!

**Comment by warwr1ck** [comment]
there is no __static in my project.
what should i do.
and i am using vue-cli-plugin-electron-builder 2.0.0-rc.5

**Comment by gbertoncelli** [comment]
Useful solution: https://dev.to/dani/how-to-use-preload-script-in-electron-webview-with-react-2h2f
