### ISSUE TITLE
Issue when plugin added with electron V 9.0.0

### ISSUE THREAD

**Issue by Kamran95** [nklayman/vue-cli-plugin-electron-builder#1021]
ExtensionLoadWarning: Warnings loading extension at /Users/kamrandurrani/Library/Application Support/latesttimetracker/extensions/nhdogjmejiglipccpnnnanhbledajbpd: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'update_url'. Permission 'contextMenus' is unknown or URL pattern is malformed. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.

**Comment by nklayman** [comment]
That is an issue with Vue Devtools, not this plugin. It also is also safe to ignore the warning as Vue Devtools works fine anyways.
