### ISSUE TITLE
Auto Update

### ISSUE THREAD

**Issue by Kamran95** [nklayman/vue-cli-plugin-electron-builder#1022]
How to add auto update for private repository?
As auto update of git hub provided in documentation works only for private repository

**Comment by nklayman** [comment]
See [the electron builder docs](https://www.electron.build/configuration/publish). They provide multiple ways of publishing so you don't have to use github releases. It should be pretty simple to adapt the existing guide to another release method. You can also use GH releases [with a private repo](https://www.electron.build/auto-update.html#private-github-update-repo), but it requires that the `GH_TOKEN` env var is set on the user's machine, so it will only work if they have access to the source code. You could also create a separate repo just for releases that doesn't have any source code.
