### ISSUE TITLE
Cannot read property 'show' of undefined 

### ISSUE THREAD

**Issue by jan-scorl** [nklayman/vue-cli-plugin-electron-builder#1025]
**Describe the bug**
This error only appears when opening the build version and only on other people's machines.
I can open the build on my own machine using my own user account.
I can open the build on my own machine using a different user account that is freshly created and has no dependencies installed.
Any person that I send the build to can't open it but receives this error message instead.
The app is signed and notarised.

**To Reproduce**
Build, sign and notarise the app. Send it to someone.

**Expected behavior**
Others should be able to open it without receiving an error message.

**Screenshots**
![WhatsApp Image 2020-09-09 at 16 39 57](https://user-images.githubusercontent.com/17554280/92616846-008ae780-f2bf-11ea-9729-f33cb9218c65.jpeg)

**Environment (please complete the following information):**
  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 13.8.0 - ~/.nvm/versions/node/v13.8.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v13.8.0/bin/npm
  Browsers:
    Chrome: 85.0.4183.83
    Firefox: 80.0.1
    Safari: 13.1.2
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.2.3
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.2.3
    @vue/cli-plugin-babel: ~4.2.0 => 4.2.3
    @vue/cli-plugin-eslint: ~4.2.0 => 4.2.3
    @vue/cli-plugin-router:  4.2.3
    @vue/cli-plugin-vuex: ~4.2.0 => 4.2.3
    @vue/cli-service: ~4.2.0 => 4.2.3
    @vue/cli-shared-utils:  4.2.3
    @vue/component-compiler-utils:  3.1.1
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^6.1.2 => 6.2.2
    vue: ^2.6.11 => 2.6.11
    vue-cli-plugin-electron-builder: ~2.0.0-beta.0 => 2.0.0-beta.0
    vue-eslint-parser:  7.0.0
    vue-hot-reload-api:  2.3.4
    vue-input-autowidth: ^1.0.10 => 1.0.10
    vue-loader:  15.9.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.1.2 => 3.1.3
  npmGlobalPackages:
    @vue/cli: 4.3.1

**Additional context**
Since I can't reproduce this issue on my own machine and it's not possible to open the dev tools when this error appears, I am out of clues about how to solve it.

**Comment by nklayman** [comment]
Can you please post your `background.js` as well?

**Comment by jan-scorl** [comment]
```
"use strict";

import {
  app,
  ipcMain,
  protocol,
  BrowserWindow,
  Menu,
  Tray,
  screen,
} from "electron";
import {
  createProtocol,
  installVueDevtools,
} from "vue-cli-plugin-electron-builder/lib";
import { autoUpdater } from "electron-updater";
require("./electron/application-menu");
const isDevelopment = process.env.NODE_ENV !== "production";

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let win;
let tray;

// Scheme must be registered before the app is ready
protocol.registerSchemesAsPrivileged([
  {
    scheme: "app",
    privileges: {
      secure: true,
      standard: true,
    },
  },
]);

function createWindow() {
  const { width, height } = screen.getPrimaryDisplay().workAreaSize;
  // Create the browser window.
  win = new BrowserWindow({
    frame: true,
    titleBarStyle: "hidden",
    transparent: true,
    movable: true,
    resizable: true,
    width: width,
    height: height,
    title: "Awake",
    webPreferences: {
      // Use pluginOptions.nodeIntegration, leave this alone
      // See nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#node-integration for more info
      nodeIntegration: process.env.ELECTRON_NODE_INTEGRATION,
    },
  });

  if (process.env.WEBPACK_DEV_SERVER_URL) {
    // Load the url of the dev server if in development mode
    win.loadURL(process.env.WEBPACK_DEV_SERVER_URL);
    console.log(process.env.npm_package_version);
    if (!process.env.IS_TEST) win.webContents.openDevTools();
  } else {
    createProtocol("app");
    // Load the index.html when not in development
    win.loadURL("app://./index.html");
    autoUpdater.checkForUpdatesAndNotify();
  }

  // Set "focus" as protocol client to handle all focus:// links
  app.setAsDefaultProtocolClient("focus");
  app.allowRendererProcessReuse = true;

  win.on("closed", () => {
    win = null;
  });
}

function createTray() {
  tray = new Tray(
    "/Users/janscorl/apps/focus-app-desktop/src/assets/logo_tray.png"
  );
  tray.setTitle("Focus");
  const contextMenu = Menu.buildFromTemplate([
    {
      label: "Show",
      type: "normal",
      click: showApp,
    },
    {
      label: "Quit",
      type: "normal",
      role: "quit",
    },
  ]);
  tray.setContextMenu(contextMenu);
}

function showApp() {
  win.show();
}

// Quit when all windows are closed.
app.on("window-all-closed", () => {
  // On macOS it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On macOS it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (win === null) {
    createWindow();
  } else {
    win.show();
    autoUpdater.checkForUpdatesAndNotify();
  }
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", async () => {
  if (isDevelopment && !process.env.IS_TEST) {
    // Install Vue Devtools
    // Devtools extensions are broken in Electron 6.0.0 and greater
    // See https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/378 for more info
    // Electron will not launch with Devtools extensions installed on Windows 10 with dark mode
    // If you are not using Windows 10 dark mode, you may uncomment these lines
    // In addition, if the linked issue is closed, you can upgrade electron and uncomment these lines
    try {
      await installVueDevtools();
    } catch (e) {
      console.error("Vue Devtools failed to install:", e.toString());
    }
  }

  // Set Dock Icon
  app.dock.setIcon(
    "/Users/janscorl/apps/focus-app-desktop/src/assets/logo.png"
  );

  setTimeout(() => createWindow(), 600);
  createTray();
});

app.on("open-url", function(event, url) {
  event.preventDefault();
  console.log(url);

  const urlObject = new URL(url);
  const params = urlObject.search;
  const newUrl = "https://firebase-auth-redirect.jms.now.sh/" + params;

  win.webContents.send("magicLinkClicked", newUrl);
});

// IPC EVENTS
ipcMain.on("setMenuBarText", (event, time) => {
  tray.setTitle(time);
});
ipcMain.on("bringWindowToFront", () => win.show());
ipcMain.on("hideWindow", () => win.minimize());
ipcMain.on("quitAndInstall", () => autoUpdater.quitAndInstall());

// AUTO UPDATER EVENTS
autoUpdater.on("update-downloaded", () => {
  win.webContents.send("updateDownloaded");
});

// Exit cleanly on request from parent process in development mode.
if (isDevelopment) {
  if (process.platform === "win32") {
    process.on("message", (data) => {
      if (data === "graceful-exit") {
        app.quit();
      }
    });
  } else {
    process.on("SIGTERM", () => {
      app.quit();
    });
  }
}
```

**Comment by jan-scorl** [comment]
Solution:
Although the error pointed towards `app` being undefined, the real culprit were the absolute paths for the app and tray icons. What's strange though is that I would have expected this to fail for the other user on my machine too, since this user doesn't have access to my personal folder. It did work for the other user on my machine though.
