### ISSUE TITLE
electron:serve command can not sync extraFiles set in builderOptions

### ISSUE THREAD

**Issue by Michael-Lee-CN** [nklayman/vue-cli-plugin-electron-builder#1026]
**Describe the bug**
electron:serve command can not sync extraFiles set in builderOptions

**To Reproduce**
If I set extraFiles as below for electron builderOptions in vue.config.js
"extraFiles": {
                        "from": someOriginalPath,
                        "to": "./Resources"
                    }

the file only gets copied in electron:build, but not in dev when use electron:serve command

**Expected behavior**
expect the file in extraFiles be copied when use  electron:serve

**Screenshots**
![Snip20200909_1](https://user-images.githubusercontent.com/18080140/92619399-05b65980-f2f4-11ea-9d9a-968504e34c95.png)

**Environment (please complete the following information):**
 this bug happens in both mac & windows

**Additional context**
N/A

**Comment by nklayman** [comment]
The files are only synced in build because electron-builder copies the files, and it isn't used for `electron:serve`. You can use `process.env.NODE_ENV === 'production'` to determine if you are in build or serve and change the path you are loading from accordingly.
