### ISSUE TITLE
Dev Server - CORS error

### ISSUE THREAD

**Issue by 4eveRS** [nklayman/vue-cli-plugin-electron-builder#103]
**Describe the bug**
I'm having a issue on developer server, when I try to fetch elements from outside URLS / domains.

> Failed to load https://www.google.com/favicon.ico: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**To Reproduce**
Create a new project and try to make a fetch().
(If you set the mode in fetch to 'no-cors', the error disappears, but the content that you are trying to fetch, is returned as null).

**Expected behavior**
In my opinion, the dev server by default, should set headers to:

```
'Access-Control-Allow-Origin': '*',
'Access-Control-Allow-Headers': '*'
```

**Environment (please complete the following information):**
 - OS and version: Mojave 10.14
 - Node version: 10.8.0
 - npm version: 6.4.1
 - vue-cli-plugin-electron-builder version : 1.0.0-rc.3
 - other vue plugins used: Vuetify

**Additional context**
This issue only happens on development mode, since all requests are made by the localhost. Once bundled and packaged, there's no issue.

**Comment by nklayman** [comment]
This is handled by the built in dev server (Vue CLI), so I think I should leave it alone. You can always launch electron with webSecurity disabled. If you think I should set it regardless, re-open this issue.

**Comment by Fanaperana** [comment]
If you are making a request from another node such as serving an API using Express.
You can solve this issue by installing:
 `npm install --save cors`

And then inside you project:
``` js
const express = request('request')
const app = express()
const cors = request('cors')

app.use(cors())
```
