### ISSUE TITLE
Ability to only bundle app

### ISSUE THREAD

**Issue by Armaldio** [nklayman/vue-cli-plugin-electron-builder#1033]
**Is your feature request related to a problem? Please describe.**
I'm using the plugin since it's well integrated with vue and typescript
But i'd like to use either electron builder and electron packager
Electron builder is able to build unpackaged macos version while electron builder, even win --dir can't

**Describe the solution you'd like**
I'd like to have a script like `vue-cli-service electron:serve` but only `vue-cli-service electron:bundle`
It's a folder I can pass to electron-packager

**Comment by nklayman** [comment]
Electron builder should definitely be able to build an unpackaged app, it should be in `dist_electron/mac-unpacked/APPNAME`. You should also be able to pass the `dist_electron/bundled` dir to electron-packager and that should work fine. Is this the folder you were looking for or do you want something else?

**Comment by Armaldio** [comment]
Electron builder tell me that its unable to build for macos (can't provide the real message currently) on windows whatever argument I pass to it, event unpacked while electron packaged can do it 
It link me to this page https://www.electron.build/multi-platform-build where it clearly say: 
``` 
Don’t expect that you can build app for all platforms on one platform 
```

**Comment by nklayman** [comment]
You will still need to use a mac to sign the app, which is required if you want users to be able to install it without getting a security warning or if you want to publish it to the app store. If you run `yarn electron:build --dir` electron-builder will only create an unpacked version of the app which takes less than a second, is this fast enough for you? I'd rather not add a custom flag to skip it as this is a rare use case and I don't want to support electron-packager in addition to electron-builder.

**Comment by Armaldio** [comment]
As my first message said, I'm unable to build unpackaged MacOS on Windows
Running `yarn electron:build --dir`

![image](https://user-images.githubusercontent.com/3089715/93141395-607cf600-f6e4-11ea-8d68-117eb11850af.png)

**Comment by nklayman** [comment]
What if you build it for windows with electron-builder, then use electron-packager to build for macos? the `dist_electron/bundled` dir is platform-independant.
