### ISSUE TITLE
message passing between background.js and Vue instance

### ISSUE THREAD

**Issue by realrecordzLab** [nklayman/vue-cli-plugin-electron-builder#1041]
Is possible to pass messages between the background.js file and the Vue instance?

**Comment by nklayman** [comment]
See the [electron docs on IPC](https://www.electronjs.org/docs/api/ipc-main). The main process is `src/background.js` and the renderer process is your Vue app. Note that you will have to [use a workaround](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration) to access IPC without enabling `nodeIntegration`.

**Comment by realrecordzLab** [comment]
I've tried using a preload script like is showed into the documentation but
it not worked for me and I've opted for the nodeIntegration

Il giorno mer 16 set 2020 alle ore 19:49 Noah Klayman <
notifications@github.com> ha scritto:
