### ISSUE TITLE
npm package vue-debounce: Failed to resolve directive: debounce

### ISSUE THREAD

**Issue by kendaniels** [nklayman/vue-cli-plugin-electron-builder#1044]
Trying to use the npm package [vue-debounce](https://github.com/dhershman1/vue-debounce) to debounce the input on a search bar. 

I've installed the package, and added this to background.js:

```
import Vue from 'vue'
import Vuex from 'vuex'
import vueDebounce from 'vue-debounce'

Vue.use(Vuex, vueDebounce)
```

I assumed that would work, but I get the following error:

`[Vue warn]: Failed to resolve directive: debounce`

After a bit of Googling, I see that there is an option to import the module directly into the component, which I have tried:

```
import { debounce } from 'vue-debounce'
```

and setting the directive up like this:

```
export default {
  directives: {
      debounce
  },
```

which gets rid of the error. But...

My input contains the appropriate syntax: `<input v-debounce:300ms="myFunc" />` however "myFunc" is never hit. I just have a simple `console.log("test") in there which never fires...

Not sure if there is something special I need to setup in vue.config.js or if I'm including it incorrectly, however I've given up after 3 hours of debugging and searching. Hoping someone here can help...

**Comment by nklayman** [comment]
I don't really see how this plugin would cause the issue, you're probably much better off opening an issue on the vue-debounce repo instead.

However, I think the issue would be fixed by using two `Vue.use` statements, I don't think you can combine them:
```js
Vue.use(Vuex)
Vue.use(vueDebounce)
```

**Comment by kendaniels** [comment]
Thanks for your help. Figured out I needed to import and use vue-debounce in main.js, not background.js. 

.use also needs to be called before `new Vue(`
