### ISSUE TITLE
ipcRenderer.on, this.$router undefined

### ISSUE THREAD

**Issue by lesliechueng1996** [nklayman/vue-cli-plugin-electron-builder#1048]
In ipcRenderer.on('channel', (event, data) => {})  callback function, this.$router is undefined

```js
mounted: function () {
    console.log(this.$router)
    ipcRenderer.removeAllListeners()
    ipcRenderer.on('close-project', (event, data) => {
      console.log(this.$router)
      ipcRenderer.send('win-set-screen-style', {
        maximize: false,
      })
      ipcRenderer.send('menu-enable-menu-item', {
        itemArray: [
          { id: 'closeProject', enabled: false },
          { id: 'openProject', enabled: false },
        ],
      })
    })
}
```

<img width="798" alt="截屏2020-09-18 下午1 41 09" src="https://user-images.githubusercontent.com/43738111/93560383-9f48cf80-f9b4-11ea-8130-7cfe0a50ae38.png">

**Comment by lesliechueng1996** [comment]
```
mounted: function () {
    console.log(this.$router)
    ipcRenderer.removeAllListeners()
    ipcRenderer.on('close-project', (event, data) => {
      console.log(this.$router)
      this.$router.back()
      ipcRenderer.send('win-set-screen-style', {
        maximize: false,
      })
      ipcRenderer.send('menu-enable-menu-item', {
        itemArray: [
          { id: 'closeProject', enabled: false },
          { id: 'openProject', enabled: false },
        ],
      })
    })
}
```

**Comment by nklayman** [comment]
I tried the code snippet you posted and it worked fine for me. Can you please create and share a full repo that demonstrates the issue?

**Comment by lesliechueng1996** [comment]
After I created a new project, the problem disappeared. But there is a new problem.
<img width="1841" alt="截屏2020-09-26 下午9 25 58" src="https://user-images.githubusercontent.com/43738111/94341790-e121e780-003e-11eb-8987-61a48138f7a9.png">

I have to use  `window.require('electron')` can solve this problem.
Is that right？
I'll upload my test code. Maybe I lost some files when I introduced dependency. Can you provide your empty project?
[electron-test.zip](https://github.com/nklayman/vue-cli-plugin-electron-builder/files/5286749/electron-test.zip)

**Comment by nklayman** [comment]
Did you make sure to enable node integration in the new app? See https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration for details.

**Comment by lesliechueng1996** [comment]
You're right. I forgot to add this configuration to the test project. Thank you very much.

**Comment by nklayman** [comment]
Since it works in the fresh project, the error likely isn't coming from this plugin, so I'm going to close this issue. If you have more info on the original project you can post that and I can try and help you figure out what the issue was there.
