### ISSUE TITLE
Any plan to warp electron-builder's release command?

### ISSUE THREAD

**Issue by PaleNeutron** [nklayman/vue-cli-plugin-electron-builder#1052]
**Is your feature request related to a problem? Please describe.**
electron-builder provide a nice `release` command to publish binaries from Travis-ci to releases, but we can not use that.

**Describe the solution you'd like**
Just warp it like build and serve.

**Describe alternatives you've considered**
Maybe providing a simple `.travis.yml` which publish release use Travis-ci built in method is a solution.

**Comment by nklayman** [comment]
I can't seem to find documentation for the `release` command. Can you post a link to it so that I can see more details on it?

**Comment by PaleNeutron** [comment]
Sorry for mistake in real command, the `release` command I used to run is `--publish` option of `electron-builder` in fact.

https://www.electron.build/configuration/publish

**Comment by nklayman** [comment]
All CLI arguments passed to `electron:build` are forwarded to electron-builder, so you should just be able to pass it to that command and it should work. Also, check out the [auto update guide](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#auto-update) for more details on publishing.
