### ISSUE TITLE
How to properly debug using webstorm?

### ISSUE THREAD

**Issue by Nisthar** [nklayman/vue-cli-plugin-electron-builder#1053]
I can see only guide for vs code. it would be nice if there's a guide for webstorm.

I checked the other issues for this. The debugging only works on main.js but the client side doesn't work. Also the breakpoints are on the wrong lines than the ones i choose.

**Comment by xXanth0s** [comment]
run this npm scrit

`"electron:debug": "vue-cli-service electron:serve --inspect-brk=9223"`

And add this debugger configuration.

![image](https://user-images.githubusercontent.com/6882434/94248773-35ce4100-ff1f-11ea-810b-935db8a68719.png)

In the code, write `debugger`

**Comment by Nisthar** [comment]
@xXanth0s i am getting this error `60:13  error  Unexpected 'debugger' statement  no-debugger`
also is there a way to make the breakpoints work?

**Comment by nklayman** [comment]
@Nisthar I think that is an error from eslint. You will have to disable that rule to use `debugger` statements. See [these docs](https://eslint.org/docs/rules/no-debugger) for details on the rule and [these](https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments) for disabling the rule with comments. Let me know if @xXanth0s' config works for you then.

**Comment by Nisthar** [comment]
@nklayman Sorry I thought the main files can be debugged like normal electron apps. so i ran the command `vue-cli-service electron:serve --remote-debugging-port=9223 --inspect=5858` now i created 2 new configs that attach to these ports.
It connects to these ports but the breakpoints are not working in the main files.

**Comment by Nisthar** [comment]
Also for some reason it quits the app when i attach to the 5858 port. 
```
Debugger attached.
✔  Bundling main process...
\  Bundling main process...
Process finished with exit code 0
```

**Comment by Nisthar** [comment]
I finally figured it out myself. I had to run `electron --remote-debugging-port=9222 ./dist_electron` and `vue-cli-service electron:serve --debug`. I have to re run the electron command everytime it is rebuilt. Its not a good solution. But it works.

**Comment by danielroehrig** [comment]
I would like to reopen this bug, as I am unable to get it to work.

Electron 9.3, vue 2.6, vue-cli-service 4.3.1

In the vue config.js I added
`configureWebpack: {
    devtool: 'source-map'
  },`
I start the debugging process by calling
`vue-cli-service electron:serve --debug`
And then run this debug configuration
![image](https://user-images.githubusercontent.com/12596513/106061784-28f07280-60f6-11eb-8e1a-54be4d6481c0.png)
But no break point in any of my vue components is hit. Any ideas what I could try next?

**Comment by danielroehrig** [comment]
Once. Just once I would like to find the answer to a problem that has been plaguing me for half a year now BEFORE I post my issue on github. Here is a very nice and easy way to debug the renderer process with breakpoints in Webstorm that does not require any complicated setup:

1. Change your run config to `vue-cli-service electron:serve --remote-debugging-port=9223`
2. Run the config. It will just start and do nothing special.
3. Create a second config. This time a "Attach to Node.js/Chrome" config with port set to 9223 
4. Now, whenever you want to wait for a breakpoint anywhere in the renderer process, just click the debug button and run that config.
![image](https://user-images.githubusercontent.com/12596513/106064146-a669b200-60f9-11eb-8f81-997dcd924fc9.png)
You can even stop any time you like and restart the debugger as long as the app is still running. This is actually pretty great! Thanks for being awesome rubber ducks!
