### ISSUE TITLE
Customizable entry script for Electron main process

### ISSUE THREAD

**Issue by soletan** [nklayman/vue-cli-plugin-electron-builder#1058]
**Is your feature request related to a problem? Please describe.**
The problem is less of a real problem: I'd like to refactor files in my repo so that all electron code resides in a separate folder (e.g. for separate ESLint configuration as well as to help new developers getting on board much easier). In addition I find the name `background.js` sort of confusing and misleading for Electron doesn't talk about something running in background and using `main.js` just ain't no option for that's claimed by Vue.js already. But having separate folders makes even more sense then. Why use separate Electron folder? I'd like to start with nodeIntegration turned off and so there will be quite some code to run in context of Electron's main process.

**Describe the solution you'd like**
I'd prefer some option (e.g. in vue.config.js) to have custom name addressing the script included by electron-builder to start Electron main process.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by nklayman** [comment]
There is already an option for this, called `mainProcessFile`. See the code snippet on [this page of the docs](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#webpack-configuration) for example usage.

**Comment by subdavis** [comment]
For posterity, there are 2 scripts, and 2 options are needed.  See my PR #1088
