### ISSUE TITLE
How to configure eslint to resolve @ to src?

### ISSUE THREAD

**Issue by NoahCardoza** [nklayman/vue-cli-plugin-electron-builder#1059]
All the normal ways I've been going about this have not been working and I'm wondering if there is a special way I should configure this since I'm using this plugin?

Has anyone had any luck with this? I'm using VS Code.

I've tried adding a webpack.config.js, editing the .eslint.js file and the jsconfig.json file to no avail.

Any help would be much appreciated!

Thanks,
Noah

**Comment by saty9** [comment]
This is for typescript and is for @ resolving to src/renderer but should help. 
Apologies for terrible formatting I'm on mobile.

Jest.config.js: 
`modulePaths: ["<rootDir>/src"],
  moduleNameMapper: {
    "@/(.*)": "<rootDir>/src/renderer/$1"
  },
  resolver: null
`
Tsconfig.js
`
CompilerOptions:
"paths": {
      "@/*": [	      "@/*": [
        "src/*"	        "src/renderer/*"
      ]	      ]
    },	    },
`
Vue.config.js
`
configureWebpack: {
    devtool: "source-map"	    devtool: "source-map",
    resolve: {
      alias: {
        "@": path.resolve(__dirname, "src/renderer")
      }
    }
`

**Comment by nklayman** [comment]
@NoahCardoza vue cli should alias `@` to src automatically, I've used this feature many times and it's always worked fine. What is the specific error you have been getting when you try to import a module using the `@` alias?

**Comment by NoahCardoza** [comment]
@saty9 Thanks for the tip! I might play around and see if that config works as well since it's a little simpler than the one I came up with 💀

Yeah it compiled fine, but eslint would say the the files couldn't be found. I was actually able to fix it an hour or so later, but I forgot to close the issue. Sorry about that.

It took a `path-intellisense` config in `/.vscode/settings.json` of:

```json
{
  "path-intellisense.mappings": {
      "@": "${workspaceRoot}/src",
  },
}
```

As well as a `jsconfig.json` config of:

```json
{
  "compilerOptions": {
    "baseUrl": "./src",
    "paths": {
      "@/*": [
        "./*"
      ],
    },
  },
}
```

And installing `eslint-plugin-import` and adding the following to the `.eslint`:

```js
{
  settings: {
    'import/resolver': {
      alias: {
        map: [['@', './src/']],
        extensions: ['.js', '.vue'],
      },
    },
  },
}
``` 

I've been working in Python the last few months so either this was simple and I just lost a little of my JS mojo or this was actually a confusing issue in which I hope this explanation helps people in the near future.

Anyways, thanks for the great plugin! It made my life so much easier!

**Comment by DrJume** [comment]
> @saty9 Thanks for the tip! I might play around and see if that config works as well since it's a little simpler than the one I came up with 💀
> 
> Yeah it compiled fine, but eslint would say the the files couldn't be found. I was actually able to fix it an hour or so later, but I forgot to close the issue. Sorry about that.
> 
> It took a `path-intellisense` config in `/.vscode/settings.json` of:
> 
> ```json
> {
>   "path-intellisense.mappings": {
>       "@": "${workspaceRoot}/src",
>   },
> }
> ```
> 
> As well as a `jsconfig.json` config of:
> 
> ```json
> {
>   "compilerOptions": {
>     "baseUrl": "./src",
>     "paths": {
>       "@/*": [
>         "./*"
>       ],
>     },
>   },
> }
> ```
> 
> And installing `eslint-plugin-import` and adding the following to the `.eslint`:
> 
> ```js
> {
>   settings: {
>     'import/resolver': {
>       alias: {
>         map: [['@', './src/']],
>         extensions: ['.js', '.vue'],
>       },
>     },
>   },
> }
> ```
> 
> I've been working in Python the last few months so either this was simple and I just lost a little of my JS mojo or this was actually a confusing issue in which I hope this explanation helps people in the near future.
> 
> Anyways, thanks for the great plugin! It made my life so much easier!

You need to have `eslint-import-resolver-alias` installed for the .eslintrc settings to work.

**Comment by trandaison** [comment]
I confirm `eslint-import-resolver-alias` works instead of `eslint-plugin-import`.
