### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by koljada** [nklayman/vue-cli-plugin-electron-builder#1063]
**Is your feature request related to a problem? Please describe.**
It seems like Vue 3 is currently not supported
I've got `Cannot find module '@vue/cli-shared-utils` error when trying to execute `vue add electron-builder` with Vue 3 installed.
Are there any plans to support it?

**Comment by shoeyn** [comment]
I don't seem to have this issue when creating a fresh vue 3 project with the vue cli then adding electron-builder.
Are you having this issue with a fresh project or one you've upgraded to vue 3?

**Comment by koljada** [comment]
I had this issue with brand new project.

**Comment by nklayman** [comment]
I don't think this is caused by vue 3 vs vue 2, but rather because if you don't use babel (or other plugins) then @vue/cli-shared-utils isn't installed. I added @vue/cli-shared-utils to the package.json now so this won't happen again.
