### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by rodrigomata** [nklayman/vue-cli-plugin-electron-builder#1069]
**Describe the bug**
After importing the `electron-deeplink` dependency, I get the following error on app startup:
```javascript
App threw an error during load
TypeError: Cannot read property 'indexOf' of undefined
    at Function.getFileName (webpack:///./node_modules/bindings/bindings.js?:178:16)
    at bindings (webpack:///./node_modules/bindings/bindings.js?:82:48)
    at eval (webpack:///./node_modules/electron-deeplink/dist/index.js?:21:127)
```

**To Reproduce**
1. Create a test app with `vue add electron-builder`
2. Add `electron-deeplink` dependency with `npm i -D electron-deeplink`
3. Require the dependency on the `main.js` file `import { Deeplink } from 'electron-deeplink'` 
4. App will break when trying to start

**Expected behavior**
Saw a couple of closed bugs in this repo that suggested to add dependency as **externals**. So far I've already tried doing this without success:
```javascript
// vue.config.js
pluginOptions: {
    electronBuilder: {
      externals: ['electron-deeplink']
    }
  }
```

**Screenshots**
![Screen Shot 2020-10-06 at 20 56 21](https://user-images.githubusercontent.com/15259836/95278715-6dd65d80-0816-11eb-95b4-a4d59077165a.png)

**Environment (please complete the following information):**
```
Environment Info:

  System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
  Binaries:
    Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v14.8.0/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Edge: Not Found
    Firefox: 77.0.1
    Safari: 13.0.3
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2 
    @vue/babel-plugin-jsx:  1.0.0-rc.3 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.5.6 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.5.6 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.6 
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.6 
    @vue/cli-plugin-router: ~4.5.0 => 4.5.6 
    @vue/cli-plugin-unit-jest: ~4.5.0 => 4.5.6 
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.6 
    @vue/cli-service: ~4.5.0 => 4.5.6 
    @vue/cli-shared-utils:  4.5.6 
    @vue/component-compiler-utils:  3.2.0 
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/test-utils: ^1.0.3 => 1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    jest-serializer-vue:  2.0.2 
    vue: ^2.6.11 => 2.6.12 
    vue-cli-plugin-electron-builder: ~2.0.0-rc.4 => 2.0.0-rc.4 
    vue-cli-plugin-tailwind: ~1.5.0 => 1.5.0 
    vue-eslint-parser:  7.1.0 
    vue-hot-reload-api:  2.3.4 
    vue-jest:  3.0.7 
    vue-loader:  15.9.3 (16.0.0-beta.7)
    vue-router: ^3.2.0 => 3.4.3 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.12 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.4.0 => 3.5.1 
  npmGlobalPackages:
    @vue/cli: Not Found
```

**Additional context**
Add any other context about the problem here

**Comment by lykl** [comment]
I got a similar problem when I use serialport,how can I fix it?

**Comment by aleksey-hoffman** [comment]
As the error says, the file `bindings.js` calls `.indexOf` of undefined which means the value of `fileName` is undefined.

https://github.com/TooTallNate/node-bindings/blob/c8033dcfc04c34397384e23f7399a30e6c13830d/bindings.js#L147-L185

They effectively set `fileName = undefined` in line 151:

https://github.com/TooTallNate/node-bindings/blob/c8033dcfc04c34397384e23f7399a30e6c13830d/bindings.js#L151

Then they update its value in line 157:

https://github.com/TooTallNate/node-bindings/blob/c8033dcfc04c34397384e23f7399a30e6c13830d/bindings.js#L157

Which means, either `getFileName()` returns undefined or the loop's condition is never equal to `true` and the value of `fileName` is never updated:

**Comment by nklayman** [comment]
@rodrigomata electron-deeplink works fine for me. Can you please create a repo that demonstrates the error so I can test it?

**Comment by Pckool** [comment]
I was really hoping this would solve my issue but sadly it went stale. I'm having the same issues with node-midi and electron-builder.

**Comment by nklayman** [comment]
@Pckool please create and share a repo that demonstrates the error.

**Comment by DrunkenMastah** [comment]
This occured to me also with serialport here is a quite minimal example https://gitlab.com/spyrous/electron_vue_test_integration

**Comment by aleksey-hoffman** [comment]
The error points to `bindings` module:

Here's the line that causes the error
https://github.com/TooTallNate/node-bindings/blob/c8033dcfc04c34397384e23f7399a30e6c13830d/bindings.js#L147

You guys might wanna create an issue in their repo, instead.

**Comment by DrunkenMastah** [comment]
Thank you I posted it over [there](https://github.com/TooTallNate/node-bindings/issues/72)

**Comment by ToToSpl** [comment]
> I got a similar problem when I use serialport,how can I fix it?

I sill have the same issue when I am trying to use list function in serialport. The hacky way to solve that is to use getStaticProps (if you are using nextron) and if you want to refresh list on a button (like I wanted to do) onClick redirect to empty page that is redirecting you back (hacky web refresh). I have tried many ways to run async but still got the same error. So I will use this solution (if it works it is ok... right?).

**Comment by ntbosscher** [comment]
I'm not sure if it helps, but I have a monkey patch that's working for me atm.
https://github.com/TooTallNate/node-bindings/issues/50#issuecomment-864171923

**Comment by Hash543** [comment]
I solved this problem by add externals content on vue.config.js
`module.exports = {
	pluginOptions: {
		electronBuilder: {
			preload: 'src/preload.js',
			nodeIntegration: true,
      externals: ['ffi-napi', 'ref-napi', '@nut-tree/nut-js'],`

**Comment by kmq116** [comment]
> I solved this problem by add externals content on vue.config.js `module.exports = { pluginOptions: { electronBuilder: { preload: 'src/preload.js', nodeIntegration: true, externals: ['ffi-napi', 'ref-napi', '@nut-tree/nut-js'],`

when I use @nut-tree/nut-js , this issue occurs but if I do not use it, the issue is disapper
