### ISSUE TITLE
serve:electron freezes on "launching electron" (node 11+windows only)

### ISSUE THREAD

**Issue by jappyjan** [nklayman/vue-cli-plugin-electron-builder#107]
**Describe the bug**
I created a bar eproject (not a single line of code of myself) and run "yarn serve:electron", the project builds, without errors (but some lint warnings), and then says "Launching electron" but nothing happens...

**To Reproduce**
1. vue create {project-name}
2. select plugins
- ts
- tslint
- babel
- router
- vuex
3. run "vue add electron-builder"
4. run "yarn serve:electron"

**Expected behavior**
it should open an app window with the default vue template.
(Works with "yarn serve")

**Environment (please complete the following information):**
 - OS and version: Win7 64Bit
 - Node version: 8.11.3
 - npm version: 5.6.0
 - yarn version (if used): 1.6.0
 - vue-cli-plugin-electron-builder version : ^1.0.0-rc.3
 - other vue plugins used: babel, typescript, vuex, router

**Comment by cbingrui** [comment]
My Windows(win10 64Bit) and Mac OS can run a very simple project with command `yarn serve:electron` but my colleague would have the same issue as described above.
We compared the environment(e.g. OS/node/npm/yarn/electron/vue-cli) but cannot find any help.

**Comment by cbingrui** [comment]
The latest `vue-cli-plugin-electron-builder` is using `Vue.js devtool` which may cannot be accessed in some areas(e.g. China). 
Solution: 
1. Set proxy for devtool installation.
2. Delete the code `await installVueDevtools();`.

**Comment by nklayman** [comment]
Is there a way I could fix this automatically, or should I just put a note in the README?

**Comment by cbingrui** [comment]
> Is there a way I could fix this automatically, or should I just put a note in the README?

I am using another start script `"serve:electron:tool": "VUE_DEV_TOOL=enable yarn serve:electron",`. Whether there should be a way, such as config or start params, to control which chrome dev tool to be started with electron. Finally, may need some comprehensive error output.

**Comment by nklayman** [comment]
Unfortunately, I don't think I can improve the error output as I am not in China, so I cannot test it. Maybe you could open a PR? I will put a note in the docs soon.

**Comment by zxc23** [comment]
I have this issue. However, I am getting it only using node v11.1.0. With v8.9 I do not see this behaviour. I am on Windows 10 with Electron 3 and the bare bones template.

**Comment by tdesmet** [comment]
hitting this as well, on windows 10 with node 11.1.0 

created a new project and selected electron 3, when trying to run I see that the electron process is started but no window is shown.

**Comment by nklayman** [comment]
I don't run into any issues on Linux. Unfortunately, I do not have access to a Windows system right now, so I will have to wait a few days till I can look into this issue further.

**Comment by tdesmet** [comment]
I was able to resolve it.
It seems related to this electron issue: https://github.com/electron/electron/pull/15470

After upgrading electron to the latest 3.0.10 (the version that was installed was 3.0.0) and upgrading node to 11.2.0 it works.

electron 3.0.10 with node 11.1.0 did not seem to work.

**Comment by nklayman** [comment]
The plugin automatically installs the latest 2.x or 3.x version. I will add a note to the docs soon.
