### ISSUE TITLE
Further explaination of blank-page problem involved with Vue3

### ISSUE THREAD

**Issue by wxk6b1203** [nklayman/vue-cli-plugin-electron-builder#1079]
**Describe the bug**
There are some changes when using this plugin upon a Vue 3.0 Electron project.
- history mode does not work for Vue 3 anymore. If you use vue-router-next and setup as history mode corresponding to Vue2.x, that is, `history: createWebHistory(),` you will face a blank page after building as production. Instead, `createWebHashHistory()` solve this problem. This feature test passed with `electron:9.3.2` and `electron:10.1.3`.
- According to the feature above, `vue invoke electron-builder` add `mode: history` to your specific router.(ts | js). You should change it manually.

**To Reproduce**
Example repo link [here](https://github.com/wxk6b1203/kanban-vue3). Uncomment `src/router/index.ts:12` and build it with `yarn electron:build`.

**Expected behavior**
none

**Screenshots**
none

**Environment**
Example repo: https://github.com/wxk6b1203/kanban-vue3 on windows 10 build 19042.546
Node: v12.13.1
OS Windows 10 Pro
版本号(Version?)	20H2
操作系统版本(OS identify version)	19042.546
Feature Windows Feature Experience Pack 120.2212.31.0

**Additional context**
Although the problem solved, I have no idea to explain why such kind of behavior happens. 😅😅

**Comment by nklayman** [comment]
Thanks for the tip, I updated the docs with Vue 3 instrucitons.
