### ISSUE TITLE
Cannot read property 'cover-back' of undefined

### ISSUE THREAD

**Issue by Eeylm** [nklayman/vue-cli-plugin-electron-builder#1085]
**Describe the bug**

after executing "electron: build" and the program is compiled when executing, this problem occurs, I have tried to unpack the program and I have seen that it is in the background.js

**To Reproduce**
Just build the program with "electron:build" and execute ".exe" inside win-unpacked.

**Expected behavior**

I was expecting it to run as in development ("electron: serve")

**Screenshots**
![image](https://user-images.githubusercontent.com/54664610/95853447-baa9bf00-0d55-11eb-8163-9a36801251ee.png)

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: 

module.exports = {
  "transpileDependencies": [
    "vuetify"
  ]
}
 - terminal output from running `vue info`:

![image](https://user-images.githubusercontent.com/54664610/95952098-c9e14900-0df7-11eb-915f-18de9971da2d.png)

**Comment by nklayman** [comment]
Can you please post your `background.js` file? I need more information to debug this.

**Comment by Eeylm** [comment]
Sorry, i found the problem, i'm using this package https://www.npmjs.com/package/@sealsystems/ipp and that's why i'm getting this error when i build.
