### ISSUE TITLE
ant-design-vue-pro 使用 electron 打包后运行时报错

### ISSUE THREAD

**Issue by nuochong** [nklayman/vue-cli-plugin-electron-builder#1089]
**Question （问题描述）**

ant-design-vue-pro打包正常，没有问题。 打包后安装并运行报如下错误。

```
Uncaught TypeError: Cannot assign to read only property 'constructor' of object '#<t>'
```

**具体错误信息有关片段**
```
...
//! moment.js
...
```
```
...
t.prototype.constructor=t,t.
...
```

![image](https://user-images.githubusercontent.com/28994748/95807589-292e5300-0d3d-11eb-932e-3ba33ccc1051.png)

**Describe the solution you'd like （你期待的是什么？）**

执行 `vue-cli-service electron:build` 打包安装后可以正常运行。

**Additional context（附加信息）**

执行 `vue-cli-service electron:build` 在使用 dev 环境的时候可以正常使用

**Comment by nklayman** [comment]
Seems like this is an issue with vue-cli's build process. Can you try a non-electron build (`npm run build`) and see if that works?

**Comment by nuochong** [comment]
> Seems like this is an issue with vue-cli's build process. Can you try a non-electron build (`npm run build`) and see if that works?

使用  `npm run build` 打包后部署到 web 运行正常，但是 `vue-cli-service electron:build`  打包后我将 `dist_electron/bundled` 下的文件部署到 web 同样会出现上述错误。有关运行时的 demo ，可以 `clone` 代码并复现错误场景。

@nklayman 

[demo](https://github.com/nuochong/ant-design-vue-pro-electron)

**Comment by milkcha** [comment]
@nklayman 我们遇到了一模一样的问题,请问这个报错你解决了没有?

**Comment by IMustTo** [comment]
> **Question （问题描述）**
> 
> ant-design-vue-pro打包正常，没有问题。 打包后安装并运行报如下错误。
> 
> ```
> Uncaught TypeError: Cannot assign to read only property 'constructor' of object '#<t>'
> ```
> 
> **具体错误信息有关片段**
> 
> ```
> ...
> //! moment.js
> ...
> ```
> 
> ```
> ...
> t.prototype.constructor=t,t.
> ...
> ```
> 
> ![image](https://user-images.githubusercontent.com/28994748/95807589-292e5300-0d3d-11eb-932e-3ba33ccc1051.png)
> 
> **Describe the solution you'd like （你期待的是什么？）**
> 
> 执行 `vue-cli-service electron:build` 打包安装后可以正常运行。
> 
> **Additional context（附加信息）**
> 
> 执行 `vue-cli-service electron:build` 在使用 dev 环境的时候可以正常使用

请问下这个问题解决了吗

**Comment by qozi** [comment]
我也遇到这个问题了。通过 viser-vue 使用 g2 图表报错。


**开发环境：**
- vcpeb 2.1.1 
- viser-vue 2.4.8
- @antv/data-set 0.11.8

**使用 viser-vue** ：
在 vue 的入口文件 main.js 中引入和使用 viser-vue： 
```js
import  Viser from 'viser-vue';
Vue.use(Viser);
```

vcpeb 开发运行 `npm run electron:serve` 没有问题，但是打包后的程序运行报错。
错误信息如下：
```
Uncaught TypeError: Cannot assign to read only property 'constructor' of object '#<t>'
    at n (g2-plugin-slider.js:502)
    at g2-plugin-slider.js:518
    at Object.<anonymous> (g2-plugin-slider.js:517)
    at n (g2-plugin-slider.js:30)
    at Object.<anonymous> (g2-plugin-slider.js:96)
    at n (g2-plugin-slider.js:30)
    at Object.<anonymous> (g2-plugin-slider.js:80)
    at n (g2-plugin-slider.js:30)
    at g2-plugin-slider.js:73
    at g2-plugin-slider.js:11
```

问题和大家的问题是一样！！！

经过查找资料和排查，确定这个问题是 [vue-cli modren mode](https://cli.vuejs.org/guide/browser-compatibility.html#modern-mode) 编译造成的，因为 vcpeb build 默认使用 [modren](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#bundling-options)。

我尝试使用 vue-cli 不经过vcpeb 直接编译项目，结果如下：

- `vue-cli-service build` 编译结果，可以正常运行
- `vue-cli-service build --modren` 编译结果，报同样的错误

所以，问题出在 modren 编译上。那么为什么不能使用 modren 模式编译 viser-vue ??!

最终问题是 g2 里面 g2-plugin-slider 这个库的问题（可能其他库也有问题），它不支持 strict ?  相应 [issue](https://github.com/antvis/g2-plugin-slider/issues/27)。这个代码不熟悉。希望熟悉的大佬解决一下。

**下面给出另外两种方法：**

1. 不使用 modren 模式打包。 添加参数  ` --legacy` 。 如： `vue-cli-service electron:build --legacy`
   > 这种方式，我试过了，可行。但是打的包比原来大了 1M 多，应该是有相关的兼容代码（electron 中是不需要的）

2. 使用 CDN 把 viser-vue 或 g2 放到外部加载。 
   > 这种方式打包体积更小（viser没有按需加载，也没有ES5的兼容代码）, 但是需要依赖网络。

> 另外，一种极端的就是不使用 g2，换其他图表库

最后，还是希望有人可以在根本上解决问题。

**Comment by liudonghua123** [comment]
> 我也遇到这个问题了。通过 viser-vue 使用 g2 图表报错。
> 
> **开发环境：**
> 
> * vcpeb 2.1.1
> * viser-vue 2.4.8
> * @antv/data-set 0.11.8
> 
> **使用 viser-vue** ： 在 vue 的入口文件 main.js 中引入和使用 viser-vue：
> 
> ```js
> import  Viser from 'viser-vue';
> Vue.use(Viser);
> ```
> 
> vcpeb 开发运行 `npm run electron:serve` 没有问题，但是打包后的程序运行报错。 错误信息如下：
> 
> ```
> Uncaught TypeError: Cannot assign to read only property 'constructor' of object '#<t>'
>     at n (g2-plugin-slider.js:502)
>     at g2-plugin-slider.js:518
>     at Object.<anonymous> (g2-plugin-slider.js:517)
>     at n (g2-plugin-slider.js:30)
>     at Object.<anonymous> (g2-plugin-slider.js:96)
>     at n (g2-plugin-slider.js:30)
>     at Object.<anonymous> (g2-plugin-slider.js:80)
>     at n (g2-plugin-slider.js:30)
>     at g2-plugin-slider.js:73
>     at g2-plugin-slider.js:11
> ```
> 
> 问题和大家的问题是一样！！！
> 
> 经过查找资料和排查，确定这个问题是 [vue-cli modren mode](https://cli.vuejs.org/guide/browser-compatibility.html#modern-mode) 编译造成的，因为 vcpeb build 默认使用 [modren](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#bundling-options)。
> 
> 我尝试使用 vue-cli 不经过vcpeb 直接编译项目，结果如下：
> 
> * `vue-cli-service build` 编译结果，可以正常运行
> * `vue-cli-service build --modren` 编译结果，报同样的错误
> 
> 所以，问题出在 modren 编译上。那么为什么不能使用 modren 模式编译 viser-vue ??!
> 
> 最终问题是 g2 里面 g2-plugin-slider 这个库的问题（可能其他库也有问题），它不支持 strict ? 相应 [issue](https://github.com/antvis/g2-plugin-slider/issues/27)。这个代码不熟悉。希望熟悉的大佬解决一下。
> 
> **下面给出另外两种方法：**
> 
> 1. 不使用 modren 模式打包。 添加参数  ` --legacy` 。 如： `vue-cli-service electron:build --legacy`
>    > 这种方式，我试过了，可行。但是打的包比原来大了 1M 多，应该是有相关的兼容代码（electron 中是不需要的）
> 2. 使用 CDN 把 viser-vue 或 g2 放到外部加载。
>    > 这种方式打包体积更小（viser没有按需加载，也没有ES5的兼容代码）, 但是需要依赖网络。
> 
> > 另外，一种极端的就是不使用 g2，换其他图表库
> 
> 最后，还是希望有人可以在根本上解决问题。
> 
> PR 和相关 issue 链接：
> 
> * vue-cli    [issue](https://github.com/vuejs/vue-cli/issues/7125)
> * [g2-plugin-slider](https://github.com/antvis/g2-plugin-slider) 现在无法提交issue，直接PR吧。g2上有个相关 [issue](https://github.com/antvis/G2/pull/1641)

I have the same issue, and add `--legacy` do not work for me. I have to change it to `--no-module`. It seems the option name changed.

```
> yarn vue-cli-service help build
yarn run v1.22.17
$ ...\node_modules\.bin\vue-cli-service help build

  Usage: vue-cli-service build [options] [entry|pattern]

  Options:

    --mode         specify env mode (default: production)
    --dest         specify output directory (default: dist)
    --no-module    build app without generating <script type="module"> chunks for modern browsers
    --target       app | lib | wc | wc-async (default: app)
    --inline-vue   include the Vue module in the final bundle of library or web component target
    --formats      list of output formats for library builds (default: commonjs,umd,umd-min)
    --name         name for lib or web-component mode (default: "name" in package.json or entry filename)
    --filename     file name for output, only usable for 'lib' target (default: value of --name)
    --no-clean     do not remove the dist directory contents before building the project
    --report       generate report.html to help analyze bundle content
    --report-json  generate report.json to help analyze bundle content
    --skip-plugins comma-separated list of plugin names to skip for this run
    --watch        watch for changes
    --stdin        close when stdin ends

```
