### ISSUE TITLE
build dmg Can not work normally

### ISSUE THREAD

**Issue by Jiiiiiin** [nklayman/vue-cli-plugin-electron-builder#109]
**Describe the bug**
The development mode can run normally, it can't be used normally after construction, and there is no way to debug.

[Minimal recurrence project](https://github.com/Jiiiiiin/d2-admin-electron-vue)

**To Reproduce**
build app

**Expected behavior**
Expect to be able to use normally after construction

**Screenshots**
![](https://ws1.sinaimg.cn/large/006tNbRwgy1fwa44w5ylgj318g0xct9s.jpg)

**Environment (please complete the following information):**
 - OS and version:mac os 10.13.6 (17G65)
 - Node version: v8.12.0
 - npm version:6.4.1
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : latest
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**

**Comment by nklayman** [comment]
The function called on [this line](https://github.com/Jiiiiiin/d2-admin-electron-vue/blob/master/src/store/modules/d2admin/modules/account.js#L43) returns `undefined`, maybe that is your issue? To get devtools in a build instance, open `src/background.js`. Move the line `if (!process.env.IS_TEST) window.webContents.openDevTools()` to outside of the `if (isDevelopment)` block. Then devtools will open in production and development. You can then use it to further debug the issue. See the [electron docs on cookies] for more information.

**Comment by Jiiiiiin** [comment]
thx 👍
