### ISSUE TITLE
Feel that the plug-in is missing a corresponding feature is extraResources!!!

### ISSUE THREAD

**Issue by yyccQQu** [nklayman/vue-cli-plugin-electron-builder#1091]
**Describe the bug**
--  I wanted to build a separate require page, but now I’m at a loss

```
"extraResources": [
      {
        "from": "src/settings",
        "to": "app/dist/settings"
      }
    ],
```

**To Reproduce**
 This kind of structure
 There is only one index file after the real-time compilation：
 
![image](https://user-images.githubusercontent.com/32674176/96217318-6429c400-0f93-11eb-89b5-43a4cc18bf6e.png)
![image](https://user-images.githubusercontent.com/32674176/96218213-59702e80-0f95-11eb-9bdd-0421f3f90bc3.png)

```js

  ipcMain.on('open-settings-window', () => {
      const settingsWindowConfig = {
          width: 500,
          height: 400,
          webPreferences: {
              nodeIntegration: true,
          },
          parent: win
      }
      
      let settingsFilePath;

      const settingsFileLocationz = path.join('file://' + __dirname, '../settings/settings.html')
      settingsFilePath = settingsFileLocationz

      console.log(settingsFileLocationz,'settingsFileLocationz')

      settingsWindow = new newWindow(settingsWindowConfig)
      settingsWindow.loadURL(settingsFilePath)
      settingsWindow.once('ready-to-show', () => {
          this.show()
      })
      settingsWindow.removeMenu()
      settingsWindow.on('closed', () => {
          settingsWindow = null
      })
  })
```

**Expected behavior**
Hope that.（settings file） No changes will be made to the html or other files

**Screenshots**
![image](https://user-images.githubusercontent.com/32674176/96217383-828fbf80-0f93-11eb-9c67-d7d5d1d1fcea.png)

**Environment (electron-build 2.0.0 electron v9)

**Additional context**
The extraResources option is normally compiled in the original electron vue project,
but now I don’t know what to do with it
And I know in the vue.config.js, but It’s not working ~
```
pluginOptions: {
        electronBuilder: {
            "nodeIntegration": true,
            builderOptions: {
            "extraResources": [
                {
                    "from": "src/electron/pages",
                    "to": "app/electron/pages"
                    }
            ],
```
hope to this
![image](https://user-images.githubusercontent.com/32674176/96222208-e23e9880-0f9c-11eb-977f-342bd26dec6c.png)

**Comment by nklayman** [comment]
Have you seen the documentation recipe on [multiple pages](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#multiple-pages)? It uses vue cli's multiple pages feature which allows the other page to be compiled with your webpack config as well. Give it a try and see if it works for you.

**Comment by yyccQQu** [comment]
> Have you seen the documentation recipe on [multiple pages](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#multiple-pages)? It uses vue cli's multiple pages feature which allows the other page to be compiled with your webpack config as well. Give it a try and see if it works for you.

It works good! Thanks. and If I always add pages in there, It’s always weird~~~~~
- Except backgroundd. Js, other electron configurations can not be dynamically updated
Finally~  Thanks, movers and shakers
