### ISSUE TITLE
support for vue env variables

### ISSUE THREAD

**Issue by zzmao** [nklayman/vue-cli-plugin-electron-builder#1094]
**Describe the bug**

env variables in .env.stage and .env.production can be used correctly with this builder. 

The way I use the variables are `process.env.VUE_APP_XXX`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 
 - terminal output from running `vue info`:

**Additional context**

**Comment by nklayman** [comment]
Env variables should be supported by default. Can you create a repo that demonstrates the error and post the link here so that I can debug it?

**Comment by dylanBcp** [comment]
I can't access to my env variables too. I'm using .env file in root folder but when i try to access to process.env.VAR_NAME it's always undefined. Do we need more configuration than just creating an .env file?

**Comment by nklayman** [comment]
The variable name has to be prefixed with `VUE_APP_`, as per the [vue cli documentation](https://cli.vuejs.org/guide/mode-and-env.html#environment-variables).

**Comment by dylanBcp** [comment]
It works well with the prefix `VUE_APP_`. But in the documentation it is stated that this prefix should not be put on sensitive variables. What can I do about sensitive variables?

**Comment by nklayman** [comment]
Sensitive variables should not be shipped. Anyone could easily extract them if they install the app. They should only be used on a server that the app connects to.
