### ISSUE TITLE
Created Basic Project, Won't Run

### ISSUE THREAD

**Issue by jasoncmcg** [nklayman/vue-cli-plugin-electron-builder#11]
I am really excited about this plugin and would be glad to test some different scenarios.

**My environment:**
Nodist, set Nodejs to be 8.11.1
Vue cli3 beta 11
 
**Deps list:**
"dependencies": {
    "source-map-support": "^0.5.4",
    "vue": "^2.5.16",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.0-beta.11",
    "@vue/cli-plugin-eslint": "^3.0.0-beta.11",
    "@vue/cli-service": "^3.0.0-beta.11",
    "@vue/eslint-config-standard": "^3.0.0-beta.11",
    "electron": "^2.0.2",
    "electron-builder": "^20.14.7",
    "electron-webpack": "^2.1.2",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "vue-cli-plugin-electron-builder": "^0.3.1",
    "vue-template-compiler": "^2.5.16"
  }

**Process:**
vue create <project name>
vue add electron-builder
npm run serve:electron

I get the error below, hit ctrl-c, electron launches and shows a cannot /get, everything closes

**Build Error Message:**
┏ Renderer -------------------

  i ｢wds｣: Project is running at http://localhost:9080/

┗ ----------------------------
┏ Renderer -------------------

  i ｢wds｣: webpack output is served from /
  i ｢wds｣: Content not from webpack is served from D:\dev\vue-electron\static, D:\dev\vue-electron\dist\renderer-dll

┗ ----------------------------
┏ Renderer -------------------

  × ｢wdm｣: Hash: 87c65831edb78efcbf7a
  Version: webpack 4.8.3
  Time: 8556ms
  Built at: 2018-05-25 08:24:29
   1 asset
  Entrypoint renderer = renderer.js
  [./node_modules/css-hot-loader/hotModuleReplacement.js] 2.86 KiB {renderer} [built]
  [./node_modules/electron-webpack/vue-renderer-entry.js] 116 bytes {renderer} [built]
  [./node_modules/webpack-dev-server/client/index.js?http://localhost:9080] (webpack)-dev-server/client?http://localhost:9080 7.75 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {renderer} [built]
  [./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {renderer} [built]
  [./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.66 KiB {renderer} [built]
  [./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 77 bytes {renderer} [built]
  [./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.31 KiB {renderer} [built]
  [./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.03 KiB {renderer} [built]
  [./src/main.js] 300 bytes {renderer} [built]
  [./src/router.js] 318 bytes {renderer} [built]
  [0] multi (webpack)-dev-server/client?http://localhost:9080 webpack/hot/dev-server css-hot-loader/hotModuleReplacement ./node_modules/electron-webpack/vue-renderer-entry.js ./src/main.js 76 bytes {renderer} [built]
  [./src/store.js] 142 bytes {renderer} [built]
  [url] external "url" 42 bytes {renderer} [built]
      + 101 hidden modules

  ERROR in ./src/components/HelloWorld.vue?vue&type=style&index=0&id=656039f0&scoped=true&lang=stylus (./node_modules/vue-loader/lib??vue-loader-options!./src/components/HelloWorld.vue?vue&type=style&index=0&id=656039f0&scoped=true&lang=stylus)
  Module parse failed: Identifier directly after number (44:11)
  You may need an appropriate loader to handle this file type.
  |
  | h3
  |   margin 40px 0 0
  |
  | ul
   @ ./src/components/HelloWorld.vue?vue&type=style&index=0&id=656039f0&scoped=true&lang=stylus 1:0-159 1:175-178 1:180-336 1:180-336
   @ ./src/components/HelloWorld.vue
   @ ./node_modules/babel-loader/lib??ref--0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Home.vue?vue&type=script&lang=js
   @ ./src/views/Home.vue?vue&type=script&lang=js
   @ ./src/views/Home.vue
   @ ./src/router.js
   @ ./src/main.js
   @ multi (webpack)-dev-server/client?http://localhost:9080 webpack/hot/dev-server css-hot-loader/hotModuleReplacement ./node_modules/electron-webpack/vue-renderer-entry.js ./src/main.js

  ERROR in ./src/App.vue?vue&type=style&index=0&lang=stylus (./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&lang=stylus)
  Module parse failed: Unexpected character '#' (12:0)
  You may need an appropriate loader to handle this file type.
  |
  |
  | #app
  |   font-family 'Avenir', Helvetica, Arial, sans-serif
  |   -webkit-font-smoothing antialiased
   @ ./src/App.vue?vue&type=style&index=0&lang=stylus 1:0-125 1:141-144 1:146-268 1:146-268
   @ ./src/App.vue
   @ ./src/main.js
   @ multi (webpack)-dev-server/client?http://localhost:9080 webpack/hot/dev-server css-hot-loader/hotModuleReplacement ./node_modules/electron-webpack/vue-renderer-entry.js ./src/main.js
  Child html-webpack-plugin for "index.html":
       1 asset
      Entrypoint undefined = index.html
      [./node_modules/html-loader/dist/cjs.js?minimize=false!./dist/.renderer-index-template.html] 330 bytes {0} [built]

┗ ----------------------------
┏ Renderer -------------------

  i ｢wdm｣: Failed to compile.

┗ ----------------------------

**Comment by nklayman** [comment]
You need to modify the webpack config and add the loader for stylus. See [here](https://github.com/nklayman/vue-cli-plugin-electron-builder#electron-webpack) for more details.

Your vue.config.js should look something like this:
```javascript
module.exports = {
  pluginOptions: {
    electronBuilder: {
      webpackConfig: {
        module: {
          rules: [
            {
              test: /\.styl$/,
              use: [
                { loader: "style-loader" },
                { loader: "css-loader" },
                { loader: "stylus-loader" }
              ]
            }
          ]
        },
        resolve: {
          extensions: [".vue", ".js", ".styl"]
        }
      }
    }
  }
};
```
