### ISSUE TITLE
HELP: App working when serving, but does not work when built.

### ISSUE THREAD

**Issue by conorholgate** [nklayman/vue-cli-plugin-electron-builder#1102]
Creating an app that prints a pdf. I have installed a plugin called pdf-to-printer. When serving the project, it works fine, but when the project is built it doesn't. I am unable to see what the error is due to devtools not working.

I have required the plugin, in the background.js:
const ptp = require("pdf-to-printer")

Then created a function in the same file:
 var passDesign = path.join(__static, 'SamplePass.pdf') 
  ipcMain.on('print', () => {
    ptp.print(passDesign).catch(error => {
      console.log(error);
    })
  })

In App.vue, i have button, with the click event called "print". This method is being sent using:
print() {
      ipcRenderer.send('print',null);
    }

I have created a vue.config.js file with the below included:
module.exports = {
    configureWebpack: {
        devtool: 'source-map'
    },
    pluginOptions: {
      electronBuilder: {
        nodeIntegration: true,
        externals: ["pdf-to-printer"],
        nodeModulesPath: ['node_modules']
      }
    }
  }

package.json:
{
  "name": "printpdf",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps"
  },
  "main": "background.js",
  "dependencies": {
    "pdf-to-printer": "^1.5.0",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-service": "~4.5.0",
    "electron": "^9.0.0",
    "electron-devtools-installer": "^3.1.1",
    "electron-rebuild": "^2.2.0",
    "vue-cli-plugin-electron-builder": "~2.0.0-rc.4",
    "vue-template-compiler": "^2.6.11"
  }
}

I am assuming it is the way the plugin is being complied down during the build?

Any help is appreciated.

**Comment by yooouuri** [comment]
I guess building the app with dev env will give you devtools:

https://stackoverflow.com/questions/45485262/how-to-debug-electron-production-binaries

**Comment by conorholgate** [comment]
Manage to solve this!

Think it was down to electron not having access to certain folders when built?

I now put the PDF in the APPDATA folder of the project and did the below

In my App.vue:


import { remote, ipcRenderer } from 'electron';
const ptp = require("pdf-to-printer")
const path = require('path')

export default {
  name: 'App',
  methods: {
    print() {
      const passDesign = path.join(remote.app.getPath('userData'), '/SamplePass.pdf') 
        ptp.print(passDesign).catch(error => {
        console.log(error);
      })
    },
