### ISSUE TITLE
AutoUpdater.checkForUpdatesAndNotify() does not work~

### ISSUE THREAD

**Issue by yyccQQu** [nklayman/vue-cli-plugin-electron-builder#1103]
**Describe the bug**
Google successfully launched ‘electron’ on Github, using the API,
however, the update alert API `autoUpdater.checkForUpdatesAndNotify()` does not work

**The code**
```
app.on('ready', async () => {
   autoUpdater.checkForUpdatesAndNotify()
  ..... 
```

**Expected behavior**
There will be an update after the release of the new version

git:
https://github.com/cc-electron/chat-os

**Comment by nklayman** [comment]
Are you following the [auto update guide](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#auto-update)?

**Comment by yyccQQu** [comment]
> Are you following the [auto update guide](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#auto-update)?

yeah~~,and I don`t know why it`s not working~.
There is my code address
https://github.com/cc-electron/chat-os/blob/main/vue.config.js
https://github.com/cc-electron/chat-os/blob/main/src/background.js

**Comment by Psycarlo** [comment]
Inside createWindow(), at the end, try:

```
win.once("ready-to-show", () => {
  autoUpdater.checkForUpdatesAndNotify();
});
```

Not sure if this works

**Comment by Psycarlo** [comment]
Auto updater works with private github?
Can't make it work

**Comment by yyccQQu** [comment]
> Inside createWindow(), at the end, try:
> 
> ```
> win.once("ready-to-show", () => {
>   autoUpdater.checkForUpdatesAndNotify();
> });
> ```
> 
> Not sure if this works
> Note: Make sure `win.on("closed", () => { win = null; });` is after

It,s not work too. Maybe the Mac Version~

**Comment by NaturalGao** [comment]
我也遇到了这个问题，请问您解决了吗？

**Comment by NaturalGao** [comment]
I also encountered this problem, have you solved it?

**Comment by Psycarlo** [comment]
I solved it. What's your problem/bug/error, so I can help you.

**Comment by yyccQQu** [comment]
> I solved it. What's your problem/bug/error, so I can help you.

Great! Please tell me how you implemented it in code

**Comment by Psycarlo** [comment]
On app.on "ready" :

`process.env.GH_TOKEN = "mygithubtoken";
  autoUpdater.autoDownload = false;
  autoUpdater.checkForUpdates();`

On vue.config.js :

`pluginOptions: {
    electronBuilder: {
      builderOptions: {
        publish: [
          {
            provider: "github",
            owner: "Psycarlo",
            private: true
          }
        ]
      },
    },`

Be careful. I am exposing the Github Token.

**Comment by yyccQQu** [comment]
> On app.on "ready" :
> 
> `process.env.GH_TOKEN = "mygithubtoken"; autoUpdater.autoDownload = false; autoUpdater.checkForUpdates();`
> 
> On vue.config.js :
> 
> `pluginOptions: { electronBuilder: { builderOptions: { publish: [ { provider: "github", owner: "Psycarlo", private: true } ] }, },`
> 
> Be careful. I am exposing the Github Token.

Thanks. For your codes~~~
