### ISSUE TITLE
Can't access "electron" through the renderer process

### ISSUE THREAD

**Issue by avi12** [nklayman/vue-cli-plugin-electron-builder#1104]
I tried creating a project using:
```
vue create electron-test
cd electron-test
vue add electron-builder
(selecting ^9.0.0)
```
Then, in the `App.vue`:
```js
import HelloWorld from './components/HelloWorld.vue';
import { shell } from "electron";

export default {
  name: 'App',
  components: {
    HelloWorld
  },
  data() {
    return {
      shell
    };
  }
};
```
However, Chrome DevTools is showing:
![electron_2020-10-22_08-25-43](https://user-images.githubusercontent.com/6422804/96828366-34ba0200-1440-11eb-9ef5-e9eb1ab0e9a8.png)

### I know this is a bug in the plugin since I followed the [quick start](https://www.electronjs.org/docs/tutorial/quick-start) tutorial, during which I used Electron 10, and I successfully imported `shell` in the renderer process.

**Comment by yooouuri** [comment]
Add

```
module.exports = {
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true
    }
  }
}
```

to your vue.config.js

**Comment by avi12** [comment]
That surprisingly worked, thanks!
