### ISSUE TITLE
non-JavaScript MIME type of "" and blank window

### ISSUE THREAD

**Issue by pawel-miczka** [nklayman/vue-cli-plugin-electron-builder#111]
**Describe the bug**
After building Vue project to Electron production build I got pure white screen and this weird error in DevTools:

```
Failed to load module script: The server responded with non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**To Reproduce**
I just ran **npm run build:electron**

**Expected behavior**
Working application

**Screenshots**
![zrzut ekranu 2018-10-17 o 08 42 47](https://user-images.githubusercontent.com/5631954/47067160-a8d5c580-d1e8-11e8-94be-0ac323e05cc7.png)

**Environment (please complete the following information):**
 - OS and version: MacOS Mojave
 - Node version: 10.9.0
 - npm version: 6.4.1
 - yarn version (if used): none 
 - vue-cli-plugin-electron-builder version : ^1.0.0-rc.3
 - other vue plugins used: none
 - custom config for vcp-electron-builder: none
 - (if possible) link to your repo: it's private so no

**Additional context**

**Comment by pawel-miczka** [comment]
I just updated Electron to 3.x. On 2.x I had same issue.

**Comment by nklayman** [comment]
Try re-invokeing the generator with `vue invoke electron-builder`.

**Comment by pawel-miczka** [comment]
True. I removed few lines from index.html and that's why It doesn't work properly. My fault, closing. Thanks anyway for answer :).
