### ISSUE TITLE
Using fs, path and child_process only possible in background.ts

### ISSUE THREAD

**Issue by AmmonStretz** [nklayman/vue-cli-plugin-electron-builder#1112]
I instaled vue with latest version of vue-cli and npm, chose typescript and added the builder.
I tried to import child_process from the helloWorld component but on riuntime it is an empty object. In the background.ts it works.
For some reason vscode tells me that ther is no electron-devtools-installer (in background.ts).
But it throws no error.
this is the working import in background.ts
`
import * as child from 'child_process';
console.log(child);
`
Do I have to pass the variable in some way to the vue app?

**Comment by wtjperi2003** [comment]
I have the same question. I created a close button. I need to use "remote" object. But I can not get it within vue component

**Comment by nklayman** [comment]
You will have to [enable nodeIntegration](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration) to use native node modules in the renderer process. Please try that and let me know if it works.

**Comment by AmmonStretz** [comment]
Thank you. Works fine. Is a bit tricky for a beginner like me to know that this is disabled becaouse of security issues.
Maybe it could be commented earlier in the documentation.

**Comment by wtjperi2003** [comment]
> You will have to [enable nodeIntegration](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration) to use native node modules in the renderer process. Please try that and let me know if it works.

Remote is deprecated in future. so I didnt use it. finally, I found this lib [promiseIpc](https://www.npmjs.com/package/electron-promise-ipc). Its good. I use it to send data from render process to main process. Then I can close app using `BrowserWindow.getFocusedWindow().close();`

**Comment by mchkirsch** [comment]
For security reason I created a preload.js in between of the background.js and the renderer (VUE component). While sending messages with IPC ExampleComponent.vue --> Preload.js --> background.js just works fine, I can't get a simple console.log() statement out of the preload.js. It always appears directly in the chromium browser console but should appear in the normal terminal (or VUE UI).
