### ISSUE TITLE
ALT+TAB and ALT+F4 issue

### ISSUE THREAD

**Issue by ericwu-eWorldES** [nklayman/vue-cli-plugin-electron-builder#112]
**Describe the bug**
In Kiosk mode, ALT+F4 on Windows can still close the app and ALT+TAB still works on MAC and Windows.

**To Reproduce**
Run app in Kiosk mode, press ALT+F4 or ALT+TAB

**Expected behavior**
App shouldn't close with ALT+F4 and you can't change windows/desktop with ALT+TAB

**Screenshots**

**Environment (please complete the following information):**
 - OS and version:
 - Node version: 10.11.0
 - npm version: 6.4.1
 - yarn version (if used): 1.10.1
 - vue-cli-plugin-electron-builder version : 1.0.0-RC.3
 - other vue plugins used: vuetify0.2.1
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**
Using electron 3.0.4

**Comment by nklayman** [comment]
This is a problem with Electron, not this plugin. You should open an issue there instead.
