### ISSUE TITLE
Compilation fails after update 

### ISSUE THREAD

**Issue by Stanzilla** [nklayman/vue-cli-plugin-electron-builder#1120]
**Describe the bug**

After an update from rc.4 to rc.5, the compilation fails because of `InvalidConfigurationError: GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"`, not sure what changed but this used to work before.

See https://github.com/WeakAuras/WeakAuras-Companion/pull/851

**To Reproduce**

See https://github.com/WeakAuras/WeakAuras-Companion/pull/851

**Expected behavior**
Working compilation

**Screenshots**

**Environment (please complete the following information):**
See https://github.com/WeakAuras/WeakAuras-Companion/pull/851

**Additional context**

**Comment by cwxyz007** [comment]
I have the same problem. And a ineresting thing is, the github only released `rc.4`, but npm has `rc.5`.

**Comment by cwxyz007** [comment]
I changed `electron:build` command to `vue-cli-service electron:build --publish never`, And the problem goes away.


https://www.electron.build/configuration/publish#how-to-publish

**Comment by Stanzilla** [comment]
@nklayman is that the official solution/workaround?

**Comment by eulertour** [comment]
It seems to be some strange default from electron-builder. https://github.com/electron-userland/electron-builder/issues/5463

**Comment by nklayman** [comment]
@Stanzilla seems like the checks on your repo passed now. What did you end up doing to solve the issue?

**Comment by Stanzilla** [comment]
what @cwxyz007 suggested

**Comment by nklayman** [comment]
Okay, I think that the issue was caused by electron-builder changing the default publish behavior, which isn't really related to this plugin. Glad that you could figure out a solution :+1:.
