### ISSUE TITLE
Can't run "electron:serve"

### ISSUE THREAD

**Issue by avi12** [nklayman/vue-cli-plugin-electron-builder#1121]
**Describe the bug**
Running `yarn electron:serve` or `npm run electron:serve` will throw an error.

**To Reproduce**
```
vue create vue-test
cd vue-test
vue add electron-builder
(Press Enter, Electron version doesn't matter)
yarn electron:serve
```

**Expected behavior**
Opens the window normally.

**Output after running `electron:serve`**
```
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                     12:54:28 PM

This relative module was not found:

* ./nodejs/NodejsStreamInputAdapter in ./node_modules/jszip/lib/object.js
 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1
```

**Comment by nklayman** [comment]
I don't get any issues at all. Can you create a repository that demonstrates the error so that I can debug it?

**Comment by avi12** [comment]
I suspect that the issue may have to do with Yarn, as described [here](https://github.com/yarnpkg/yarn/issues/8430)

**Comment by nklayman** [comment]
I'm going to close this issue for now as it seems like this isn't the plugin's fault. I can reopen it if that linked issue is found to not be yarn's fault.
