### ISSUE TITLE
The app name (title) cannot be changed

### ISSUE THREAD

**Issue by yogarasu** [nklayman/vue-cli-plugin-electron-builder#1125]
**Describe the bug**
The app name (title) cannot be changed

**To Reproduce**
After creating an app with vue2 series
I tried to set the title in background.js

```
const win = new BrowserWindow({
    width: 1080,
    height: 720,
    title: "MyApp",
    webPreferences: {
      nodeIntegration: process.env.ELECTRON_NODE_INTEGRATION
    }
  })
```

However, the title of the app remains "Vue app" and cannot be changed

**Expected behavior**
The title of the app can be changed to any name

**Screenshots**
<img width="147" alt="スクリーンショット 2020-11-04 2 03 52" src="https://user-images.githubusercontent.com/68766032/98017051-11c91e00-1e42-11eb-9e3b-89131a5e1304.png">

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 
 - terminal output from running `vue info`:

**Additional context**

**Comment by yogarasu** [comment]
I found a solution
Add the following content to the vue.config.js file

```js
module.exports = {
  publicPath: '/',
  chainWebpack: config => {
    config
      .plugin("html")
      .tap(args => {
        args[0].template = './src/renderer/index.html'
        args[0].title = require('./package.json').title
        return args
      })
  }
}
```

Until then, I was forced to change the title after creating a vue instance

```Vue
  created() {
    const title = require('../package.json').title
    document.title = title
    document.querySelector("meta[property='og:title']").setAttribute('content', title)
  },
```

I noticed that I may have overlooked webpack custom settings etc.
I will review the document

**Comment by nklayman** [comment]
It uses the title from `public/index.html`. Changing that will change the window title.
