### ISSUE TITLE
createProtocol uses deprecated argument format of protocol.createBufferProtocol()

### ISSUE THREAD

**Issue by fspoettel** [nklayman/vue-cli-plugin-electron-builder#1133]
**Describe the bug**
When using the `createProtocol` with `electron@^10.1.3`, the following warning is printed to the console:
```
(node:8379) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
```
The warning is referring to [this code location](https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/master/lib/createProtocol.js#L35-L38).

**To Reproduce**
import and call `createProtocol`.

**Expected behavior**
According to the [electron docs](https://www.electronjs.org/docs/api/protocol#protocolregisterbufferprotocolscheme-handler), it seems like we need to `try/catch` the error now instead of passing a handler as second argument. We should probably also re-throw the error so that callers can properly handle `createProtocol()` failing.

Happy to contribute a PR with a fix.

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: not relevant
 - terminal output from running `vue info`:
```
$ vue info

Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 2600X Six-Core Processor
  Binaries:
    Node: 14.6.0 - ~/.nvm/versions/node/v14.6.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v14.6.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 82.0.3
  npmGlobalPackages:
    @vue/cli: Not Found

```

**Comment by nklayman** [comment]
This was fixed by #1228.
