### ISSUE TITLE
Uncaught ReferenceError: __dirname is not defined when importing electron app or remote in a Vue 3 component.

### ISSUE THREAD

**Issue by VictorioBerra** [nklayman/vue-cli-plugin-electron-builder#1135]
**Describe the bug**
Same issue can be found here 
https://stackoverflow.com/questions/64796292/unable-to-import-electron-related-files-into-vue-3

**To Reproduce**
vue create hello-world
Select Vue 3
vue add electron-builder

Then in main.js try and use it `import { remote } from 'electron'`

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/2934507/98973770-cb2a9200-24d9-11eb-8efa-85462988d5d3.png)

![image](https://user-images.githubusercontent.com/2934507/98973798-d2ea3680-24d9-11eb-8afa-79bc6a49ef44.png)

**Environment (please complete the following information):**
Windows.

```
  "dependencies": {
    "core-js": "^3.6.5",
    "element-plus": "^1.0.1-alpha.14",
    "vue": "^3.0.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-eslint": "^10.1.0",
    "electron": "^9.0.0",
    "electron-devtools-installer": "^3.1.0",
    "electron-icon-builder": "^1.0.2",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0-0",
    "trianglify": "^4.1.1",
    "vue-cli-plugin-electron-builder": "~2.0.0-rc.5"
  },
```

**Additional context**

**Comment by herbievine** [comment]
Same error here. Made a SO post [here](https://stackoverflow.com/questions/64796292/unable-to-import-electron-related-files-into-vue-3)

**Comment by VictorioBerra** [comment]
@herbievine I think we have to communicate to electron using icp. Most electron modules can not be required in the vue app.

**Comment by VictorioBerra** [comment]
require it in preload like so: https://stackoverflow.com/a/64656306/1777780
