### ISSUE TITLE
router link not working in build "/dashboard" converted to "app://./dashboard"

### ISSUE THREAD

**Issue by yassersharaf** [nklayman/vue-cli-plugin-electron-builder#1137]
I have these routes in **SPA using <router-view></router-view> not using separate html files for components**

export const router = createRouter({
    history: process.env.IS_ELECTRON ? createWebHashHistory() : createWebHistory(),
    routes: [
        { path: '/login', component: Login, name: 'login' },
        { path: '/logout', component: Logout, name: 'logout' },
        { path: '/dashboard', component: Dashboard, name: 'dashboard' },
    ]
});

and .env

IS_ELECTRON=true
IS_TEST=false
NODE_ENV=production

In serve version routes work fine I can login and navigate to the dashboard using .push('/dashboard') or using "window.location = '/dashboard'" but in the built version I inspect the network and I find out that it's looking for this route "app://./dashboard" and sure it returns an error and route doesn't work so all other routes won't work.

Is there a default env file for production and developing?

Am I writing routes incorrectly or missing other env parameters? Please guide. Please note I don't have vue.config.js file for configuration if it's related to this issue.

Thanks

**Comment by alectrocute** [comment]
This sounds like you’re attempting to use a non-hash router mode in Electron.

I don’t know what’s going on in `createWebHashHistory()`, I’d suggest making sure it’s actually true to its name and confirm that you’re indeed using hash mode for the router.

**Comment by yassersharaf** [comment]
Hello @alectrocute 
As you see in router.js I have this according to vue 3

    history: process.env.IS_ELECTRON ? createWebHashHistory() : createWebHistory(),

and in .env

    IS_ELECTRON=true

I alert(process.env.IS_ELECTRON) and I get "true" so it's using "createWebHashHistory". If I set it to false the page loads blank without the error I mentioned above. Here's the full router.js

    import {createRouter, createWebHistory, createWebHashHistory} from 'vue-router';
    import Login from "@/components/Login";
    import Logout from "@/components/Logout";
    import Dashboard from "@/components/Dashboard"
    export const router = createRouter({

      history: process.env.IS_ELECTRON ? createWebHashHistory() : createWebHistory(),
      routes: [
          { path: '/login', component: Login, name: 'login' },
          { path: '/logout', component: Logout, name: 'logout' },
          { path: '/dashboard', component: Dashboard, name: 'dashboard' },
      ]
    });

    router.beforeEach( function(to, from, next) {
      const token = localStorage.getItem('vb5token');
      if (to.name !== 'login' && !token) next({ name: 'login' })
      else next();
    });

**Comment by yassersharaf** [comment]
I found out that the problem is I'm using window.location after signing in to navigate to the dashboard to get the stored token from local storage but if I use router.push it works fine but sure can't load the token from local storage without a page load. Do you have a solution for this using the plugin? To get the local storage token value without a reload just by using router.push

**Comment by alectrocute** [comment]
> I found out that the problem is I'm using window.location after signing in to navigate to the dashboard to get the stored token from local storage but if I use router.push it works fine but sure can't load the token from local storage without a page load. Do you have a solution for this using the plugin? To get the local storage token value without a reload just by using router.push

Perhaps you need `window.localStorage`?

```javascript
import {createRouter, createWebHistory, createWebHashHistory} from 'vue-router';
import Login from "@/components/Login";
import Logout from "@/components/Logout";
import Dashboard from "@/components/Dashboard"
const storage = window.localStorage || null;

export const router = createRouter({
  history: process.env.IS_ELECTRON ? createWebHashHistory() : createWebHistory(),
  routes: [
      { path: '/login', component: Login, name: 'login' },
      { path: '/logout', component: Logout, name: 'logout' },
      { path: '/dashboard', component: Dashboard, name: 'dashboard' },
  ]
});

router.beforeEach( function(to, from, next) {
  const token = storage ? storage.getItem('vb5token') : false;
  if (to.name !== 'login' && !token) next({ name: 'login' })
  else next();
});
```

Also, if you're in hash routing mode, then you should be setting `document.location` to the following schema: `app://./index.html/#/dashboard`, `app://./index.html/#/login`, etc. `app://./dashboard` would not be a valid route.

**Comment by yassersharaf** [comment]
It's working in router yes but not working in FetchClient class as it loads at the beginning and reads token from storage as null but can't get the updated value from storage after signing in.

**Comment by yassersharaf** [comment]
Got it to work by modifying FetchClient.js to read the token inside the get or post function not in the constructor

**Comment by Kenhuey** [comment]
For Vue3+TS
Find @/router/index.ts and change mode
`
const router = createRouter({
  history: process.env.IS_ELECTRON
    ? createWebHashHistory()  // builded package
    : createWebHistory(process.env.BASE_URL), // dev serve
  routes,
});
`
