### ISSUE TITLE
Linux icon not showing up in the taskbar but displayed in apps page

### ISSUE THREAD

**Issue by yassersharaf** [nklayman/vue-cli-plugin-electron-builder#1138]
I set icon for Linux but it's not showing up in the taskbar though it's showing in apps page. 

In `vue.config`

    builderOptions: {
        "appId": "com.example.app",
        "icon": "./src/assets/icons/Icon-512.png",
        "win" : {
          "icon" : "src/assets/images/app_icon.png",
        },
        "linux" : {
          "target" : "deb",
          "maintainer" : "xxxx",
          "vendor" : "xxxx",
          "executableName" : "xxxx version 1",
          "category" : "Utility",
          "icon": "./src/assets/icons/"
        },
        "productName" : "xxxx version 1"
      }

Here's a screenshot https://imgur.com/iTWGGKj the icon not showing though It's set correctly as app icon in the apps page like this https://imgur.com/a/1PQqskB

**Comment by nklayman** [comment]
Did you follow the icon guide, specifically [setting the tray icon](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#set-tray-icon)? I think it should solve your problem.
