### ISSUE TITLE
Blank page in production when the partition option is set in the BrowserWindow constructor

### ISSUE THREAD

**Issue by svebaa** [nklayman/vue-cli-plugin-electron-builder#1150]
**Describe the bug**
The partition option causing a blank page in production when it's set in BrowserWindow constructor.

Works in a development, but not in a production.

Problem is solved when removing the partition option, but I would like to use it.

**To Reproduce**
`win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: process.env.ELECTRON_NODE_INTEGRATION,
      sandbox: true,
      webSecurity: false,
      partition: "persist:test"
    }
  })`

**Expected behavior**
Working app in the production

**Screenshots**
![image](https://user-images.githubusercontent.com/65409353/99962418-6e0fc580-2d90-11eb-83ee-9b32ccb12530.png)

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 
 - terminal output from running `vue info`:

**Additional context**

**Comment by nklayman** [comment]
With the next release, you can use `createProtocol('app', session.fromPartition('persist:test').protocol)` and it will work with a partition.
