### ISSUE TITLE
Can't get node-pty to work in Electron

### ISSUE THREAD

**Issue by michielkempen** [nklayman/vue-cli-plugin-electron-builder#1156]
Hey everyone!

I've spent the last two days trying to get [node-pty](https://github.com/microsoft/node-pty) to work in my Electron app, but without any luck. 😞

My development setup is the following:
- OS: macOS 10.15.6
- node-pty version: 0.9.0
- node version: 14.15.1
- electron version: 11.0.3
- vue-cli-plugin-electron-builder version: 2.0.0-rc.5

My `vue.config.js` file looks like this:

```js
var path = require('path');

module.exports = {
  pages: {
    index: {
      entry: 'src/app/main.js',
    },
  },
  chainWebpack: config => {
    config.resolve.alias.set('@', path.resolve(__dirname, 'src/'));
    config.module.rule("node").test(/\.node$/).use("node-loader").loader("node-loader").end();
  },
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true,
      externals: ['node-pty']
    }
  },
};

```

Whenever I import the `node-pty` module in my `background.js` file and run `npx vue-cli-service electron:serve`, I get the following exception:

```
 error  in ./node_modules/node-pty/build/Release/pty.node

Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

 @ ./node_modules/node-pty/lib/index.js 49:49-85
 @ ./src/background.js
 @ multi ./src/background.js
```

Whenever I import the `node-pty` module in my `renderer.js` file and run `npx vue-cli-service electron:serve`, I get the following exception in my browser:

```
Uncaught Error: node-loader:
Error: Invalid package /node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar
    at Object.eval (webpack-internal:///./node_modules/node-pty/build/Release/pty.node:5)
    at eval (webpack-internal:///./node_modules/node-pty/build/Release/pty.node:8)
    at Object../node_modules/node-pty/build/Release/pty.node (chunk-vendors.js:4251)
    at __webpack_require__ (index.js:849)
    at fn (index.js:151)
    at eval (webpack-internal:///./node_modules/node-pty/lib/unixTerminal.js:26)
    at Object../node_modules/node-pty/lib/unixTerminal.js (chunk-vendors.js:4299)
    at __webpack_require__ (index.js:849)
    at fn (index.js:151)
    at eval (webpack-internal:///./node_modules/node-pty/lib/index.js:13)
```

I've tried every possible solution that I could find online and my entire Google search looks purple. I literally don't have a clue what I could try next, so if anyone could point me in the right direction, that would be very helpful.

**Comment by nklayman** [comment]
Just adding `node-pty` as an external worked for me. Can you create an example repo that demonstrates the error so I can debug it?

**Comment by michielkempen** [comment]
I finally found the solution to my problem: https://github.com/electron/electron-rebuild/issues/75#issuecomment-504637837

[electron-rebuild](https://github.com/electron/electron-rebuild/) does not rebuild the modules that are installed as devDependency. Once I installed the module as a dependency, electron-rebuild did its thing and everything worked as expected.

**Comment by yanerdyr** [comment]
I have the same case for using node-pty in electron，and the module is instaled as dependency，but electron-rebuild no effect.
