### ISSUE TITLE
How to use auto update feature with private repository ?

### ISSUE THREAD

**Issue by reepen** [nklayman/vue-cli-plugin-electron-builder#1157]
Hi, i need to set auto update server to works with private repository. I founded this package https://github.com/vercel/hazel to run auto update server but it seems to be old. As you can see, it use older `now` cli command.

Do you know how can i do that ?

**Comment by deathart** [comment]
read: https://www.electron.build/auto-update.html#private-github-update-repo
```js
autoUpdater.setFeedURL({
  provider: 'github',
  repo: 'xxxxx',
  owner: 'xxxxxx',
  private: true,
  token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx'
});
```

**Comment by nklayman** [comment]
@reepen you do not need to use hazel for auto updates, you can just use github releases directly. See the link posted above for instructions, and also see the [auto update guide](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#auto-update), although it is designed for public repositories and will have to be adapted slightly.

**Comment by kaede-labs-jp** [comment]
The github token issuing function now allows you to only allow content to be read, but can you use this token to secure uploads to release automatically?
