### ISSUE TITLE
use adonis JS in same project with electron Vue

### ISSUE THREAD

**Issue by biloo-dev** [nklayman/vue-cli-plugin-electron-builder#1158]
Tired of using Adonis on my project, I have tried so many methods
All of them haven't worked after I created the project
there are any way to use adonisjs please help me
i try require Adonis server to main.js
![2020-11-28_230656](https://user-images.githubusercontent.com/37638323/100527216-a2401780-31d0-11eb-8d66-2a236f15ee16.png)
I had this problem
![2020-11-28_230455](https://user-images.githubusercontent.com/37638323/100527245-f21ede80-31d0-11eb-9f7b-d346e1563ca7.png)

**Comment by nklayman** [comment]
Can you please open a new issue that follows the bug report template? I need more information to debug this. Also, make sure to include the `./Server/server.js' file.
