### ISSUE TITLE
Logging with Preload.js

### ISSUE THREAD

**Issue by mchkirsch** [nklayman/vue-cli-plugin-electron-builder#1159]
**Describe the bug**
For security reason I created a preload.js in between of the background.js and the renderer (VUE component). While sending messages with IPC ExampleComponent.vue --> Preload.js --> background.js just works fine, I can't get a simple console.log() statement out of the preload.js. It always appears directly in the chromium browser console but should appear in the normal terminal (or VUE UI).

**To Reproduce**

I have inserted a contextBridge with a simple console.log statement.
![Bildschirmfoto 2020-11-30 um 20 23 58](https://user-images.githubusercontent.com/63515524/100654391-fe7a7700-3349-11eb-8f0f-874dce2f1b8c.png)

Contrary to the assumption that the result is output in the VUE UI terminal, the print statement appears in the Chromium Browser.

**Expected behavior**
Contrary to the assumption that the result is output in the VUE UI terminal, the print statement appears in the Chromium Browser.

<img width="402" alt="Bildschirmfoto 2020-11-30 um 20 26 19" src="https://user-images.githubusercontent.com/63515524/100654585-53b68880-334a-11eb-8df1-f0f1f8e7a24c.png">

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: 
vue.config.js:
![Bildschirmfoto 2020-11-30 um 20 27 45](https://user-images.githubusercontent.com/63515524/100654755-96786080-334a-11eb-82cd-df96c2a0723b.png)

background.js:
![Bildschirmfoto 2020-11-30 um 20 28 50](https://user-images.githubusercontent.com/63515524/100654825-b019a800-334a-11eb-94ce-730204e91f53.png)

 - terminal output from running `vue info`:
System:
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /opt/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 87.0.4280.67
    Edge: Not Found
    Firefox: 82.0.2
    Safari: 14.0.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2 
    @vue/babel-plugin-jsx:  1.0.0-rc.3 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.9 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.9 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.9 
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.9 
    @vue/cli-plugin-router:  4.5.9 
    @vue/cli-plugin-vuex:  4.5.9 
    @vue/cli-service: ~4.5.0 => 4.5.9 
    @vue/cli-shared-utils:  4.5.9 
    @vue/compiler-core:  3.0.2 
    @vue/compiler-dom:  3.0.2 
    @vue/compiler-sfc: ^3.0.0 => 3.0.2 
    @vue/compiler-ssr:  3.0.2 
    @vue/component-compiler-utils:  3.2.0 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/reactivity:  3.0.2 
    @vue/runtime-core:  3.0.2 
    @vue/runtime-dom:  3.0.2 
    @vue/shared:  3.0.2 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^7.0.0-0 => 7.1.0 
    vue: ^3.0.0 => 3.0.2 
    vue-cli-plugin-electron-builder: ^2.0.0-rc.5 => 2.0.0-rc.5 
    vue-eslint-parser:  7.1.1 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.5 (16.0.0-rc.2)
    vue-loader-v16: ^16.0.0-beta.5.4 => 16.0.0-beta.5.4 
    vue-style-loader:  4.1.2 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 4.5.9

**Additional context**
iPC messages send from vue components to preload.js and then to background.js work fine and get displayed in the vue ui terminal as expected.

**Comment by nklayman** [comment]
Preload `console.log` statements are supposed to output to the browser terminal. The preload script is run in the context of the browser, not the main process. You will have to use IPC to the main process if you want to log to the console window from the preload file.
