### ISSUE TITLE
Cannot find name __static 

### ISSUE THREAD

**Issue by cobysy** [nklayman/vue-cli-plugin-electron-builder#116]
**Describe the bug**
*Cannot find name '__static' when building*
`yarn electron:build` and `yarn electron:serve` fails with the error `Cannot find name '__static'.`

The offending line(s) in `src/background.ts` are (TypeScript)
```
ipcMain.on('mainWindowLoaded', () => {
  db = new Database(fs.readFileSync(path.join(__static, 'hello.sqlite')));
```

Reproduction steps:
```
vue create projname
cd projname
vue add electron-builder
# edit background.ts
```

What am I missing here?

**Environment (please complete the following information):**
 - OS and version: macOS Mojave 10.14
 - Node version: v8.11.3
 - npm version:
 - yarn version (if used): 1.9.4
 - vue-cli-plugin-electron-builder version : ^1.0.0-rc.4

**Comment by nklayman** [comment]
Just add `declare const __static: string` to your `background.js`.
