### ISSUE TITLE
How does autoupdate works from users pc?

### ISSUE THREAD

**Issue by Nisthar** [nklayman/vue-cli-plugin-electron-builder#1165]
This is not an issue but a question i can't figure out. I was able to successfully release an update using the `-p always` argument. 

I am using a private repo. It worked on my pc because i set GH_TOKEN. 

1. How does this work in users pc? do i need to set GH_TOKEN in their pc too?

2. i see that electron builder is adding "sourcecode.zip" file to the release. Is there a way to only publish exe files?

Thanks

**Comment by nklayman** [comment]
Using auto-update with a private github repo requires the user of the app to have a GH_TOKEN with permission on that repo. If you want anyone to be able to update it without a special token then you should create a separate repo just for the updates.

I'm not sure about the `sourcecode.zip` file, you might want to open an issue on the electron-builder repo. I know github itself adds the source code to each release automatically, is that what you are seeing?
