### ISSUE TITLE
ReferenceError: __dirname is not defined

### ISSUE THREAD

**Issue by realrecordzLab** [nklayman/vue-cli-plugin-electron-builder#1167]
I've read the other issue about the same problem but I'm not able to make my app working.  I have set the `nodeIntegration` in my vue.config.js file on true but it seems not working and I'm unable to use the `ipcRenderer` in my vue components.

```
module.exports = {
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
        nodeIntegration: true
      }
    }
  }
}
```
Is there any fix?

**Comment by wildwind3325** [comment]
Move nodeIntegration: true to electronBuilder.

**Comment by lucaslgr** [comment]
@wildwind3325 @realrecordzLab   I have the same problem and I'm using this versions of packages and I can't find the electronBuilder, where is this?
below are my package versions:

`"dependencies": {
    "core-js": "^3.6.5",
    "vue": "^2.6.11",
    "vue-router": "^3.0.3",
    "vuex": "^3.4.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "^3.0.5",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "electron": "^12.0.0",
    "electron-devtools-installer": "^3.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^6.2.2",
    "prettier": "^2.2.1",
    "vue-cli-plugin-electron-builder": "~2.0.0",
    "vue-template-compiler": "^2.6.11"
  },`

**Comment by nklayman** [comment]
@lucaslgr See [the docs on nodeIntegration](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration) for details.

**Comment by lucaslgr** [comment]
Thanks a lot @nklayman !
