### ISSUE TITLE
infinite npm run electron:serve

### ISSUE THREAD

**Issue by soeroon** [nklayman/vue-cli-plugin-electron-builder#1168]
stuck on
![image](https://user-images.githubusercontent.com/75589933/101400635-3fdacb80-38e2-11eb-8e8f-128bbbc99018.png)
and then nothing happening

and during installation of the plugin i got the error:
![image](https://user-images.githubusercontent.com/75589933/101400537-19b52b80-38e2-11eb-821f-3f3c5202c0a9.png)

**Comment by nklayman** [comment]
Please open a new issue that follows the bug report template.
