### ISSUE TITLE
Use of RC4 release on Linux yields blank app window with Electron 3.*

### ISSUE THREAD

**Issue by pauljon** [nklayman/vue-cli-plugin-electron-builder#117]
**Describe the bug**
In upgrading my app to use RC4, it builds and runs, but the app window is blank when run on Ubuntu Linux when using Electron 3.*. It works great if Electron 2.* is used. Using either Electron version on Windows builds works fine.

**To Reproduce**
The repro can be seen in the simple case of the default Vue CLI app with the RC4 plugin added with Electron 3.* selected when prompted.
- On Ubunu 18.04.1 with Vue CLI 3 globally installed by npm
- vue create my-vue-app
- cd my-vue-app
- vue add electron-builder
- (select electron version 3.* when prompted)
- npm run electron:serve

**Expected behavior**
The default Vue CLI-generated application UI should be shown.

**Screenshots**
Instead, a blank app window is presented. The menu bar appears to be mostly working although the dev tools cannot be activated.

**Environment (please complete the following information):**
 - OS and version: Ubuntu Linux 18.04.1 LTS
 - Node version: 10.12.0
 - npm version: 6.4.1
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 1.0.0-rc.4
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**
The RC4 version works fine on Windows with either electron 2.* or 3.* selected. It also works on Ubuntu if electron 2.* is selected. I have reinvoked the plugin so that the npm commands and main entry have been updated as directed in the release notes. I am currently using the RC3 version successfully.

**Comment by pauljon** [comment]
Thanks Noah for a wonderful response time and pointing out this related issue. I do notice a few differences between my report and the electron issue. The electron issue is reporting a crash and the electron version is 2.*. I am not seeing evidence of a crash and I have an issue only with electron 3.*.  Sounds like you are pretty confident they boil down to the same root problem though.

**Comment by nklayman** [comment]
The reason I am confident is because it works fine if I don't have an IPC channel when launching electron.

**Comment by pauljon** [comment]
Great, so you have experienced the repro. So while use of RC3 doesn't manifest the problem, RC4 does something different that causes it to manifest (using ipc presumably). Hopefully, this repro case will help them fix the root cause.

**Comment by Desuuuu** [comment]
The IPC was added to fix #108 which was pretty much Windows related.

While signals could not be used to kill Electron gracefully on Windows, they could be used instead of the IPC on non-Windows platforms and it would solve this.

**Comment by nklayman** [comment]
I published 1.0.0-rc.5. For some reason, it won't launch electron on my computer now. Could one of you test it on linux to make sure it is only an issue with my computer?

**Comment by tbutcaru** [comment]
hi @nklayman , just upgraded to electron v3 and latest VCP electron-builder rc6 and `electron:serve` command stucks at `Launching Electron...`.
I'm on Manjaro Linux.

**Comment by Desuuuu** [comment]
@nklayman I tried in a Ubuntu 18.04.1 VM and I'm not having any issue. Serve and build commands seems to be working fine with a newly-created vue-cli app.

Node v8.10.0
Electron 3.0.6
VCP Electron Builder 1.0.0-rc.6

**Comment by nklayman** [comment]
@tbutcaru the issue you mentioned is related to #122. I have temporarily set the `background.js` to not `await` installing devtools, which is why it works now.

**Comment by pauljon** [comment]
I tried both rc5 and rc6 on my same Ubuntu 18.04.1 VM. Both hang at the "Launching Electron..." message and no UI is presented.

**Comment by nklayman** [comment]
This was fixed with `1.0.0-rc.7`.

**Comment by pauljon** [comment]
Confirmed, rc7 is now working for me on Ubuntu 18.04.1 and continues working on Windows 10. Thanks!

**Comment by tbutcaru** [comment]
Started working for me too only after I cleared everything under `dist_electron` and regenerated the `background.js` file.

**Comment by erguotou520** [comment]
@nklayman 
After updating to rc7 which removed `<base>` tag, my app not worked.
My custom registed protocol is not the default `app` but `xxxapp` and the resource in output html is hard code to `app://`.

**Comment by nklayman** [comment]
Set `noAppProtocol` to true in `pluginOptions`, then you can re-add your `base` tag.

```javascript
// vue.config.js
module.exports = {
pluginOptions: {
        electronBuilder: {
          noAppProtocol: true
        }
      }
    }
}
