### ISSUE TITLE
vue.config.js file ignore windows build 

### ISSUE THREAD

**Issue by realrecordzLab** [nklayman/vue-cli-plugin-electron-builder#1174]
This is the `vue.config.js` file I'm using at the moment

```
module.exports = {
  pluginOptions: {
    electronBuilder: {
      outputDir: 'build',
      builderOptions: {
        mac: {
          target: ['dmg'],
          icon: 'build/icon.icns',
        },
        win: {
          target: ['portable'],
          icon: 'build/icon.icns',
        },
        asar: true
      },
      preload: 'src/preload.js'
    }
  }
}
```
Anyway when from the vue ui I give the `electron:build` command, only the dmg for macOS will be created, the win param of the config file will be ignored and the expected portable `.exe` file will not be created. Is there any error into configuration?

**Comment by nklayman** [comment]
Use `electron:build --windows`. electron-builder will not use the platform config unless you specifically tell it to build for that platform.

**Comment by realrecordzLab** [comment]
I need to enable the windows platform without selecting the output format (NSIS, ecc...) also I need to select the option to avoid the installer creation otherwise it will not work on macOS 10.13.6
Thanks for the help
