### ISSUE TITLE
Transparent window has background color when using electron:serve

### ISSUE THREAD

**Issue by karaeren** [nklayman/vue-cli-plugin-electron-builder#1176]
When serving the project with "yarn electron:serve", transparent windows have a background color. It's something blackish at first and goes white when you close the DevTools. The effect is achieved perfectly when getting a build with electron:build... Had this problem on Windows 10 10.0.19042.

background.js, related part (does this behaviour in an empty project):

```
const win = new BrowserWindow({
    width: 800,
    height: 600,
    transparent: true,
    frame: false,
    webPreferences: {
      nodeIntegration: process.env.ELECTRON_NODE_INTEGRATION
    }
  });
```

**Comment by karaeren** [comment]
Update on the issue, i think DevTools causes the issue here. When disabling it by
```
webPreferences: {
    devTools: false
}
```
the window becomes transparent once again... A workaround is to use DevTools on an external window.

**Comment by nklayman** [comment]
I think this is an issue with electron rather than this plugin, as it seems devtools will disable transparency for any electron app. If you test it with a plain electron app and it stays transparent with devtools, let me know and I will reopen this issue.

**Comment by jsun969** [comment]
I get this problem too. My operating system is Arch Linux. This is the window when I add `transparent: true`

**Comment by Seblor** [comment]
I also have this issue (on Windows 10). Transparency works fine when cloning this repo : https://github.com/toonvanvr/electron-transparency-demo but does not work with I use a default app with vue-cli-plugin-electron-builder. I managed to have a transparent window when removing all references to the plugin in my background.js and executing directly with the electron binary.

@nklayman I think this issue should be re-opened.
