### ISSUE TITLE
loading native modules from non-default location

### ISSUE THREAD

**Issue by muchanem** [nklayman/vue-cli-plugin-electron-builder#1177]
I'm trying to get my native module working (here's the [repo](https://github.com/muchanem/vue-electron-neon-quickstart) for reference), it's not installed with npm because I am building my own native module with [neon-bindings](https://github.com/neon-bindings/neon) I added the directory to my vue.config.js using `externals: ['native']` and added to my background.js with require but when I run electron:serve I get the error 
```
This dependency was not found:

* native in ./src/background.js

To install it, you can run: npm install --save native
```

Maybe trying to add it as a nodeModulesPath could work, but I think that will cause more issues as the index.node is at the top of the directory not in a subdirectory (unlike a module in node_modules installed with npm) also, there's no package.json. could node-loader or publishing the module seperately work?

Is there any way to get my native module working without any of the workarounds?

**Comment by muchanem** [comment]
follow up, trying to use a seperate npm package won't work because the build command relies on the electron version and that isn't being detected on package install

**Comment by shadowfax92** [comment]
@muchanem Curious, did you find a solution here? I'm looking to solve a similar problem too :)
