### ISSUE TITLE
The library is incomplete after packaging

### ISSUE THREAD

**Issue by worksq** [nklayman/vue-cli-plugin-electron-builder#1179]
**Describe the bug**
hello,I have a question. On the package. Json file,  have "Canvas", "file-type ", "Heic-convert",but after run electron:serve.I found that only "Canvas", "file-type" are used in asAR compressed files. no "Heic-convert". I try run electron:build is ok.Looking forward to your guidance.thank you

**Comment by nklayman** [comment]
I'm not sure what your issue is exactly. Can you please open a new issue that follows the bug report template so that I can help you?
