### ISSUE TITLE
Render process async/await error not output in console

### ISSUE THREAD

**Issue by cbingrui** [nklayman/vue-cli-plugin-electron-builder#118]
**Describe the bug**
The error happened inside the `async/await` cannot be output int he electron console, only can output correctly outside the async/await scope or try/catch the error and console.log manually.

**To Reproduce**
1. After vue create testvuecli3electron & yarn & yarn electron:serve, I can see Electorn app run successfully
2. Add the scripts as below in the `Home.vue`
```javascript
  async mounted() {
    console.log("before");
    await console.log("await");
    const a = b.c;
    console.log("finish");
  }
```
3. There is no any error output in the console.(refer to below screenshot)

**Expected behavior**
Display the same error as in browser console.

**Screenshots**
![image](https://user-images.githubusercontent.com/8628260/47401347-8822e800-d773-11e8-90ef-12bc15ddd0bf.png)

**Environment (please complete the following information):**
 - OS and version: 10.12.6
 - Node version: v8.11.4
 - npm version: 6.4.0
 - yarn version (if used): 1.9.4
 - vue-cli-plugin-electron-builder version : 1.0.0-rc.4
 - other vue plugins used: (no)
 - custom config for vcp-electron-builder: (no)

**Comment by nklayman** [comment]
I see it just fine:
![image](https://user-images.githubusercontent.com/12448243/47514263-c6341080-d834-11e8-929a-a60dbf85cda3.png)

**Comment by nklayman** [comment]
What OS are you on?

**Comment by cbingrui** [comment]
Mentioned in the first post `OS and version: 10.12.6`

**Comment by cbingrui** [comment]
MacOS.

**Comment by nklayman** [comment]
I have no idea what causes this, as I am seeing it too. Try opening an issue on electron's repo as it may be their fault (since it works on electron 2). See what happens if you try this on a project without vue.

**Comment by dspangenberg** [comment]
I have the same problem with Electron 3. But "only" in development mode. In production, the errors will be logged to console.

For the time being use:

```
process.on('unhandledRejection', error => {
  console.error(error)
})
```

**Comment by nklayman** [comment]
In what file does this snippet go in?

**Comment by dspangenberg** [comment]
@nklayman For example in main.js

**Comment by nklayman** [comment]
Should I add that when invoking the generator, or just mention it in the docs?

**Comment by nklayman** [comment]
I added this to the docs. @cbingrui would you mind trying this on a simple electron project to determine if it is electron's fault?

**Comment by nklayman** [comment]
I also mentioned this in the docs.

**Comment by nklayman** [comment]
Async errors work fine for me now. Maybe I fixed it without knowing, or Electron/node fixed the issue with a more recent version. Try again with the latest version of this plugin and electron.

**Comment by mathieutu** [comment]
On my side I have a `Uncaught TypeError: process.on is not a function` error. 

Any thoughts?

Thanks.
