### ISSUE TITLE
Can we use the latest version of electron?

### ISSUE THREAD

**Issue by m4heshd** [nklayman/vue-cli-plugin-electron-builder#1180]
I don't know if it's only allowed to use the versions suggested on installation but those are pretty old. So the electron packed node version is also old which makes a handful of modules not functional. Is it possible to update to a later version like Electron v11.1.0?

**Comment by azeranex** [comment]
You can. I use it with latest electron without any issue.

**Comment by m4heshd** [comment]
@azeranex really? Did you just update the Electron module or took any extra steps?

**Comment by azeranex** [comment]
@m4heshd I update electron dependency and made some change in background.js according to electron changes like contextIsolation.

**Comment by m4heshd** [comment]
@azeranex I really appreciate your response. 

> made some change

Would you be kind enough to point me towards all of those exact changes you made to the config so I won't run into any untraceable random issues in middle of my project. Sorry for the trouble. Returning to Electron after a super long time and I'm really nervous.

**Comment by azeranex** [comment]
I only made change on this
```
  win = new BrowserWindow({
    width: 1920,
    height: 1080,
    frame: isDevelopment,
    resizable: false,
    webPreferences: {
      contextIsolation: false,
      enableRemoteModule: true,
      nodeIntegration: process.env.ELECTRON_NODE_INTEGRATION,
    },
  })
```
Otherwise is my app specific requirement. You don't actually need to change anything if you didn't need any specific electron feature.

**Comment by m4heshd** [comment]
Excellent. Huge favor. Much appreciated. 🙏🏼

**Comment by nklayman** [comment]
This plugin shouldn't have any issues with the latest version of electron. I haven't added it to the generator yet because of testing issues, but it seems like they will never fix that so I might just have to add it anyways. Just been really busy lately and haven't had much time to work on this.

**Comment by m4heshd** [comment]
@nklayman no problem. Your hard work which's given out for free is always appreciated. Thank you.
