### ISSUE TITLE
How to use prisma with this library?

### ISSUE THREAD

**Issue by Nisthar** [nklayman/vue-cli-plugin-electron-builder#1183]
It works perfectly fine in debugging

But in build, i am getting the error 

![image](https://user-images.githubusercontent.com/11994157/102114740-9440f680-3e60-11eb-843e-59b277d4cf1c.png)

**Comment by Nisthar** [comment]
Is this related to this issue? https://github.com/electron-userland/electron-builder/issues/3096

**Comment by nklayman** [comment]
Can you please give me more context as to how you are using Prisma? Prisma is designed to be run in a server, not on an Electron app, so I'm not sure how you are trying to configure it.
