### ISSUE TITLE
Port change not working

### ISSUE THREAD

**Issue by akhilchatur77** [nklayman/vue-cli-plugin-electron-builder#1184]
**Describe the bug**
----
I am currently running a electron vue app in package.json as  _"electron:serve": "vue-cli-service electron:serve",_ and it gets the port 8080.
I have vue.config.js file as 

> module.exports = {
    pluginOptions: {
        electronBuilder: {
            builderOptions: {
                "productName": 'ui',
                "extraResources": [
                    {
                        "from": "some.exe",
                        "to": "some.exe"
                    }
                ],
                "devServer": {
                    port: 3000
                }
            }
        }
    }
}

**To Reproduce**

npm run electron:serve

**Expected behavior**

I have been providing port in vue.config.js and also trying _npm run electron:serve -- --port 3000_

but it keeps running on _port:8080_

_App running at:
  - Local:   http://localhost:8080/_

**Screenshots**

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 
 - terminal output from running `vue info`:

-----------------------------------
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE      
    Yarn: Not Found
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2
    @vue/babel-plugin-jsx:  1.0.0-rc.4
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.9
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.9
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.9
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.9
    @vue/cli-plugin-router: ~4.5.0 => 4.5.9
    @vue/cli-plugin-vuex:  4.5.9
    @vue/cli-service: ~4.5.0 => 4.5.9
    @vue/cli-shared-utils:  4.5.9
    @vue/component-compiler-utils:  3.2.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    vue: ^2.6.11 => 2.6.12
    vue-cli-plugin-electron-builder: ~2.0.0-rc.5 => 2.0.0-rc.5
    vue-electron: ^1.0.6 => 1.0.6
    vue-eslint-parser:  7.2.0
    vue-hot-reload-api:  2.3.4
    vue-loader: ^15.9.5 => 15.9.5 (16.1.1)
    vue-router: ^3.4.9 => 3.4.9
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.12
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found

**Additional context**

I have another program running on port:8080 and want to configure electron.

**Comment by anark1stx** [comment]
This issue is not electron-builder related, see that you are running [electron-serve](https://github.com/sindresorhus/electron-serve).

However if you have something else running on 8080 why can't you change it? to 8081 for example.

And another way around is setting your [electron app as an actual server](https://gist.github.com/bellbind/6ae79ebef25504107650)

**Comment by akhilchatur77** [comment]
@anark1stx I will try the new method you just said and also I did make it work by changing the 8080 in my python flask server changes that was running as backend. Thanks.
