### ISSUE TITLE
ERR_ELECTRON_BUILDER_CANNOT_EXECUTE - macOS 10.13.6

### ISSUE THREAD

**Issue by realrecordzLab** [nklayman/vue-cli-plugin-electron-builder#1189]
With the last version of electron builder create a windows NSIS installer or portable app is impossible from macOS 10.13.6
After some research, the last version that seems working is `21.2.0` but when the `electron:build` command is given from vue ui or from cli, also after a downgrade of electro builder, the used version is the latest.  This will produce this error:
```
 INFO  Building app with electron-builder:
  • electron-builder  version=22.9.1 os=17.7.0

  • 
packaging       platform=win32 arch=x64 electron=11.0.3 appOutDir=build/win-unpacked

  • 
building        target=nsis file=build/test Setup 1.0.0.exe archs=x64 oneClick=true perMachine=false

  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.4.1/nsis-3.0.4.1.7z size=1.3 MB parts=1

  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.4.1/nsis-3.0.4.1.7z duration=2.711s

  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.4.1/nsis-resources-3.4.1.7z size=731 kB parts=1

  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.4.1/nsis-resources-3.4.1.7z duration=2.28s

ExecError: /Users/local/Library/Caches/electron-builder/nsis/nsis-3.0.4.1/mac/makensis exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Error output:

Error output:
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/local/Library/Caches/electron-builder/nsis/nsis-3.0.4.1/mac/makensis (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/local/Library/Caches/electron-builder/nsis/nsis-3.0.4.1/mac/makensis (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib


    at ChildProcess.<anonymous> (/Users/local/Sites/apps/electron-app/node_modules/vue-cli-plugin-electron-builder/node_modules/builder-util/src/util.ts:243:14)
    at Object.onceWrapper (node:events:483:26)
    at ChildProcess.emit (node:events:376:20)
    at ChildProcess.EventEmitter.emit (node:domain:470:12)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Socket.EventEmitter.emit (node:domain:470:12)
    at Pipe.<anonymous> (node:net:666:12) {
  exitCode: null,
  alreadyLogged: false,
  code: 'ERR_ELECTRON_BUILDER_CANNOT_EXECUTE'
}
```
Is possible to fix this problem?

**Comment by nklayman** [comment]
Seems like the error is on electron-builder's side, see https://github.com/electron-userland/electron-builder/issues/5134. Maybe something there can help you fix this.

**Comment by realrecordzLab** [comment]
> Seems like the error is on electron-builder's side, see [electron-userland/electron-builder#5134](https://github.com/electron-userland/electron-builder/issues/5134). Maybe something there can help you fix this.

Unfortunately it's another error that produce the same generic error message, not related with the issue linked.

**Comment by OliviaJennings** [comment]
@realrecordzLab I have the same problem, did you find a solution for it?

**Comment by realrecordzLab** [comment]
> @realrecordzLab I have the same problem, did you find a solution for it?

No, at the moment. I've switched to squirrel windows but I hope that the issue will be fixed soon

**Comment by nklayman** [comment]
You can try using [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) to downgrade electron-builder manually, since it seems as if that might fix it.

**Comment by realrecordzLab** [comment]
> You can try using [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) to downgrade electron-builder manually, since it seems as if that might fix it.

Is this possible also with npm? I've tried to uninstall and install manually the version that is reported as working but vue ui will always use last version

**Comment by hpyer** [comment]
> You can try using [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) to downgrade electron-builder manually, since it seems as if that might fix it.

This solution (downgrade electron-builder to 21.2.0) works for me, thanks to @nklayman 

@realrecordzLab Add this code to your `package.json`, then run `yarn install` or `npm install`

```
"resolutions": {
  "vue-cli-plugin-electron-builder/electron-builder": "^21.2.0"
}
```

**Comment by nklayman** [comment]
Since downgrading electron-builder fixes the issue, it appears to not be related to this plugin, so I will close this issue.

**Comment by sangyoo91** [comment]
Downgrading did not work for me with the same errors.

**Comment by sangyoo91** [comment]
For anyone stumbling with this error, for me on Windows, I fixed the problem by specifying an icon path inside build configs.
