### ISSUE TITLE
Static assets path problems when using second browser window as local server

### ISSUE THREAD

**Issue by arsh09** [nklayman/vue-cli-plugin-electron-builder#1193]
**Describe the bug**

I made a child browserWindow with basic HTML and passed in a javascript file in script tag. I wanted to use this as a background process to replace node child-process forks. I am using DLL which requires node modules that I can not access in renderer process that is why I am not using Pages options.

Everything works in development, when I build the app, the child browser window does not find the path. I used the following code snippet. The JS code for second browser windows  is in the public folder (along with its html file). I use the following code snippet to get the path:

`
// group.js -> JavaScript file attached to the group.html file (that serves as second browser window)

if (process.env.NODE_ENV !== 'development') {
    window.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\')
    console.log(window.__static)
}

else {
    window.__static = __dirname 
}
`
**Expected behavior**
The complete install path would be return with __dirname. It resturns the path with 'app.asar' in the path appended that vanilla javascript is unable to use and find dll file (thus causing Dynamic Linking Error: Win32 error 126 which is wrong path to DLL file error)

**Screenshot**
![Image1](https://user-images.githubusercontent.com/16521157/103015814-06f65400-457c-11eb-8a9c-6c3e46a04783.PNG)

**Environment (please complete the following information):**
 - Electron 5 

Thank you

**Comment by nklayman** [comment]
I'm not quite sure how you are including the DLL in the final build, so I don't know how to help you load it properly. Can you please create a sample repo that demonstrates the error so that I can debug it?
