### ISSUE TITLE
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'on' of undefined"

### ISSUE THREAD

**Issue by realrecordzLab** [nklayman/vue-cli-plugin-electron-builder#1195]
I've created a preload file and it seems to be loaded correctly in dev and production modes. After I've decided to enable `contextIsolation` the console started logging this error

```
 vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'on' of undefined"
```

It seems that the `window.ipcRenderer.on` stop working. I'm using it inside the `mounted()` hook of my vue components to listen to events sended from the main process of my electron app. Is there any fix?

**Comment by nklayman** [comment]
As per the [Electron docs](https://www.electronjs.org/docs/tutorial/context-isolation#what-is-it), this is intended behavior. Enabling Context Isolation will give the preload script a separate `window` object, so `window.ipcRenderer.on` would be undefined in the renderer process.

**Comment by realrecordzLab** [comment]
> As per the [Electron docs](https://www.electronjs.org/docs/tutorial/context-isolation#what-is-it), this is intended behavior. Enabling Context Isolation will give the preload script a separate `window` object, so `window.ipcRenderer.on` would be undefined in the renderer process.

So when the context Isolation will be set on true by default from newer electron versions how we will use `ipcRenderer` safely?

**Comment by nklayman** [comment]
See [this StackOverflow answer for instructions](https://stackoverflow.com/a/59675116/10118610). I should probably update the instructions on the docs as well.
