### ISSUE TITLE
How can I access Vuex store from the main process?

### ISSUE THREAD

**Issue by m4heshd** [nklayman/vue-cli-plugin-electron-builder#1196]
As far as I know, we have to use IPC to interact with the Vuex store at the moment right?

Is there any direct method to manipulate the store via main process that I don't know of?

**Comment by anark1stx** [comment]
You can use [vuex-electron](https://github.com/vue-electron/vuex-electron), it's an old package but it is still working, you can find an example [here](https://github.com/vue-electron/vuex-electron-example)

**Comment by m4heshd** [comment]
@anark1stx Thank you for the suggestion. I did knew about that one and I saw that a lot of people having trouble with it since it seems to maintain 2 copies of the store and values not being matched all the time. That's quite unreliable. 😕 Not being maintained either.

**Comment by anark1stx** [comment]
Yeah keeping data synced across two different processes is quite hard to achieve and the reason why why use stores, perhaps you will want to use a different solution like [electron-store](https://github.com/sindresorhus/electron-store), 

> You can use this module directly in both the main and renderer process.

**Comment by m4heshd** [comment]
That looks stable. Wanna try it. Although using that, I'll be losing Vuex functionality right? (since I can't bother to maintain two data sources). Also since everything is stringified, I'll be losing Intellisense support. It's super frustrating integrating a front-end framework into Electron 😓. It almost feels like this is way more work and time consumed than vanilla JS because my previous Electron projects went super smooth using as less dependencies and frameworks as I can. I hate to give up on Vue + Electron though. It feels so right.

**Comment by anark1stx** [comment]
Indeed, by the way why do you need the main process of electron to know about your store? Just curious. And do you have any problems with using ipcMain and ipcRenderer? The [setup](https://gist.github.com/tatat/5cc7f61a20b453db1057561b57f80ea2) for it looks quite simple and clean actually

**Comment by m4heshd** [comment]
Yes that's exactly what I sketched doing. I don't mind using IPC at all but there have been moments IPC failed me untraceably. I know it may sound weird but I've seen so many similar issues on SO too. IPC messages lost in the way and no errors returned either. Something like that would ruin my life because my clients need to have their transactions reflected to the cent on the program and a tiny miscommunication inside IPC can mess that up. I've developed the currently running program in Java and I never have to worry about any silently failed transactions ever. It's just so iron clad. Very clean code to action.

> why do you need the main process of electron to know about your store

I need a lot of DB manipulations done via the main process that directly connects with Vuex store which should also be very reactive. Also I completely want to avoid doing any DB transactions inside the renderer. I totally get that even while writing this 😁, It's impossible to achieve this apart from IPC because it literally is two separate processes. Guess I'm gonna have to take a chance. Or just do everything inside the renderer with node integration on.

BTW I really appreciate you taking the time to invest in this. I'll close this now. But do send any inputs you have my way. Even the tiniest new insight could change how I'll be shaping my project up.

**Comment by anark1stx** [comment]
Yeah, no doubts that a thing like this ruins the whole hype of developing something with some cool technologies that you discovered and trying to make a serious project with it, 4 days ago I had to move to React Native from Electron-Nuxt because of some issues, I know a lot of people hate React but the state management with useState along with useContext or Redux works perfectly and is always synced with async-storage (as a local db), and again, it works perfectly. Wish you the best with your project, I spent 3 months just to choose the right technologies to use lol.

**Comment by m4heshd** [comment]
OMG I'm in the exact same situation as you were. It's been 20+ days now doing research to find the right toolset for my project. I'm migrating an application with 100,000+ lines of code. Don't wanna be stuck in the middle of writing it hitting my head against the wall. Now since you said Redux would work, I wanna check React out. That means more research and more time. Oh well.

> Wish you the best with your project

Thank you very much.

**Comment by anark1stx** [comment]
When It comes to state management I prefer using the Context API (example with my project [here](https://github.com/anark1stx/sushi-night/blob/main/Contexts/AuthContext.js)), Redux is pretty overkill for most cases, and it is also an external library which in my case I cannot use since my final app cannot exceed certain MB.

**Comment by m4heshd** [comment]
Ohh I see. Do you have any projects done with React + Electron?

**Comment by anark1stx** [comment]
I don't, however you may be interested in these boilerplates:

[electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate)

[nextron](https://github.com/saltyshiomix/nextron)

For my personal recommendation goes React Native with Expo, I only need to code 1 time and the app will run in Android / Windows / Mac / iOs / Linux which is a relief, I'm not sure if electron is 100% cross platform compatible, there are other options like Ionic or native-script as well.

**Comment by m4heshd** [comment]
I'm actually familiar with everything you reference here. But from my past experience, Electron kinda stands over everything else since my sole target is desktop platforms. Microsoft also seemed to have dropped react-native to move forward with Electron. I think I'm gonna try to fast pace with Vue and see if It's viable with the mass amount of native modules I'm planning to use. Fingers crossed. 🤞🏼
