### ISSUE TITLE
configuration.mode should be one of these:    "development" | "production" | "none"

### ISSUE THREAD

**Issue by yogaliu** [nklayman/vue-cli-plugin-electron-builder#1198]
I was created .env.sit on the root;
run 'vue-cli-service electron:build --mode sit' 

ERROR
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.mode should be one of these:
   "development" | "production" | "none"
   -> Enable production optimizations or development hints.

**Comment by nklayman** [comment]
In your `.env.sit` file, you will need to set `NODE_ENV` to `production` or `development`. That will fix the issue.
