### ISSUE TITLE
ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed. 

### ISSUE THREAD

**Issue by realrecordzLab** [nklayman/vue-cli-plugin-electron-builder#1199]
I have this shtange issue in my production build 

```
(node:10285) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
writeOut @ internal/process/warning.js:32
```

I'm unable to inspect the build code and this is the only error that I'm able to track using debugtron. I've build the app with success in past but now stopped working. I saw in my background.js that the `createProtocol` is registered from this library. Is possible that is a bug of it?

**Comment by nklayman** [comment]
Can you please open a new issue that follows the bug report template? I need more information to debug this.
