### ISSUE TITLE
Vue Devtools panel doesn't show up on Devtools

### ISSUE THREAD

**Issue by octoper** [nklayman/vue-cli-plugin-electron-builder#1208]
**Describe the bug**
I have tried to find the Vue DevTools in the DevTools panel but nothing

**To Reproduce**
Steps to reproduce the behavior: Just open Electron DevTools and try to find Vue Devtools

**Expected behavior**
I expected the Vue Devtools Tab to be in Electron Devtools

**Screenshots**
![Screenshot from 2021-01-08 01-21-14](https://user-images.githubusercontent.com/6823226/103956147-94c36900-5150-11eb-8377-8f7e7f909e79.png)

**Environment:**
Environment Info:
  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 AMD A10-9620P RADEON R5, 10 COMPUTE CORES 4C+6G
  Binaries:
    Node: 14.15.4 - /usr/bin/node
    Yarn: Not Found
    npm: 6.14.10 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 84.0.1
  npmPackages:
    @headlessui/vue: ^0.2.0 => 0.2.0 
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.0 
    @vue/babel-plugin-jsx:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.10 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.10 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.10 
    @vue/cli-plugin-router: ~4.5.0 => 4.5.10 
    @vue/cli-plugin-unit-jest: ~4.5.0 => 4.5.10 
    @vue/cli-plugin-vuex:  4.5.10 
    @vue/cli-service: ~4.5.0 => 4.5.10 
    @vue/cli-shared-utils:  4.5.10 
    @vue/compiler-core:  3.0.5 
    @vue/compiler-dom:  3.0.5 
    @vue/compiler-sfc: ^3.0.0-beta.1 => 3.0.5 
    @vue/compiler-ssr:  3.0.5 
    @vue/component-compiler-utils:  3.2.0 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/reactivity:  3.0.5 
    @vue/runtime-core:  3.0.5 
    @vue/runtime-dom:  3.0.5 
    @vue/shared:  3.0.5 
    @vue/test-utils: ^2.0.0-alpha.1 => 2.0.0-beta.14 
    @vue/web-component-wrapper:  1.2.0 
    jest-serializer-vue:  2.0.2 
    vue: ^3.0.0-beta.1 => 3.0.5 
    vue-cli-plugin-electron-builder: ~2.0.0-rc.5 => 2.0.0-rc.5 
    vue-hot-reload-api:  2.3.4 
    vue-jest:  3.0.7 
    vue-loader:  15.9.6 (16.1.2)
    vue-router: ^4.0.0-alpha.6 => 4.0.2 
    vue-style-loader:  4.1.2 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 4.5.10

**Comment by m4heshd** [comment]
That might be because you're using Vue 3 which isn't supported by the stable version of Vue devtools. Use this instead of the predefined VueJS Devtools. It's the beta that supports Vue 3.

```
try {
  await installExtension({
    id: 'ljjemllljcmogpfapbkkighbhhppjdbg', //Vue Devtools beta
    electron: '>=1.2.1'
  })
} catch (e) {
  console.error('Vue Devtools failed to install:', e.toString())
}
```

**Comment by octoper** [comment]
It works! Thank you @m4heshd you saved me!
