### ISSUE TITLE
How to avoid webpacking the main process in development

### ISSUE THREAD

**Issue by wiknew1** [nklayman/vue-cli-plugin-electron-builder#1209]
The source mapping for main process is way too unstable and unpredictable to be used with huge programs.

How can I use the uncompiled `background.js` with Electron after starting the vue dev server? I've noticed that there's a lot of ES6 code in this plugin that might complicate this. But please help me if anybody is already doing this.

**Comment by nklayman** [comment]
Set your `vue.config.js` to:
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      bundleMainProcess: false,
      customFileProtocol: './'
    }
  }
}
```

You will have to do the following in `background.js` as well:
1. Remove all `import` statements and replace them with `require` (`electron-devools-installer` may give you errors in build, so you may have to remove it entirely)
2. Replace `const isDevelopment...` with `const isDevelopment = path.extname(__dirname) !== '.asar'`
3. Remove both the `createProtocol` import and call
4. Replace `await win.loadURL(process.env.WEBPACK_DEV_SERVER_URL)` with `await win.loadURL('http://localhost:8080')`, and change the surrounding if statement condition to `process.env.NODE_ENV === 'development'`
5. Replace `win.loadURL('app://./index.html')` with ``win.loadURL(`file://${__dirname}/index.html`)``


And you will need to run `electron:build` with the `--legacy` arg. Keep in mind that if the dev server goes to a port other than `8080`, it won't work (this will happen if that port is already taken).

I think this is a complete list of everything you need to do, but I didn't double check it. Let me know if something else fails and you can't figure it out.
