### ISSUE TITLE
Connecting Vuex

### ISSUE THREAD

**Issue by Kamran95** [nklayman/vue-cli-plugin-electron-builder#1210]
I am having issue when passing data from main process to vuex store and vise versa.
I haved used vuex electron but still no progress.
Anyone kindly help me out how to use vuex store in electron

Waiting for your response 
Thank you

**Comment by nklayman** [comment]
Can you please post code snippets that show how you configure vuex electron? I need more information to be able to help you.

**Comment by lswl66** [comment]
我遇到了一样的问题 不过我往 vue 里注册了 electron ,  然后使用 vuex 的 dispatch 统一修改state 并且使用 ipcRenderer.send() 向主进程通信. 通过主进程,再往 需要了解state 变化的window传送value , 当然最重要的就是 需要在这些窗口监听主进程的通信，我在 APP.vue 文件里使用 ipcRenderer.on() 监听主进程的通知，接收到消息后 变化这个窗口的vuex

希望对你的问题有帮助

**Comment by lswl66** [comment]
在项目的最后,我意识到:我不是真的需要 vuex .  许多数据存储到 localstorage 就足够了。
