### ISSUE TITLE
--mode is ignored or how to customize the build process for different target environments?

### ISSUE THREAD

**Issue by MBurchard** [nklayman/vue-cli-plugin-electron-builder#1213]
I work on an Vue 3 Electron App.

I've created some files in the public folder called `application.json` and `application-[env].json`.

From the `background.ts` a method is called to load the configurations at runtime.

```typescript
  const properties = {
    auth: {
      clientId: '',
      redirectURI: '',
      tenant: '',
    },
    mockData: false,
  }
  const baseName = 'application'
  const fileExtension = '.json'
  const env = process.env.NODE_ENV
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  const configPath = path.resolve(__static)
  console.debug(`Config Path: ${configPath}`)

  const fileNames = [
    `${baseName}${fileExtension}`,
    `${baseName}.local${fileExtension}`,
    `${baseName}-${env}${fileExtension}`,
    `${baseName}-${env}.local${fileExtension}`,
  ]

  fileNames.forEach((fileName) => {
    try {
      if (fs.existsSync(path.resolve(configPath, fileName))) {
        console.debug(`found config file ${fileName}`)

        const rawData = fs.readFileSync(path.resolve(configPath, fileName))

        console.debug(`raw JSON data: ${rawData}`)

        Object.assign(properties, JSON.parse(rawData.toString('utf-8')))
      }
    } catch (e) {
      console.error(`Error reading configuration from file ${fileName}`, e)
    }
  })

  console.debug(`Configuration: ${JSON.stringify(properties, null, '  ')}`)
```

This works well for the default environments `development` and `production`

Now I tried to start the app with a custom environment like described on some websites

```
  "scripts": {
    "electron:serve": "vue-cli-service electron:serve --mode staging",
  },
```

The result was the mode was still development. `--mode` is simply ignored.

What I really want to achieve is to build different versions. One should work against the services of the development environment, another against the staging environment and then one for production.

They will contain different URLs and other settings that are in the application*.json files.

Ideally, the finished build contains only the application*.json files that are really needed for the target environment.

**Comment by nklayman** [comment]
`process.env.NODE_ENV` should only be `development` or `production`. If you want to have a different value (like `staging`), you should use another env variable. See [Vue CLI's guide on env variables](https://cli.vuejs.org/guide/mode-and-env.html) for instructions on configuring those. Any env variables you set with the prefix `VUE_APP_` will be available in both the main and renderer processes.
