### ISSUE TITLE
help!  Vue3.0 [Vue warn]: Failed to resolve component: webview 

### ISSUE THREAD

**Issue by E2875888382** [nklayman/vue-cli-plugin-electron-builder#1217]
**Describe the bug**
Webview tag can be used normally,but when it initializes,there is a warn by vue.

**Expected behavior**
How can i clear this warn ?

**Screenshots**
![image](https://user-images.githubusercontent.com/42968086/105468175-a6b91600-5cd1-11eb-95d0-e9cf30df8e3e.png)

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 
 - terminal output from running `vue info`:
```
    const win = new BrowserWindow({
        width: 1000,
        height: 650,
        minWidth: 1000,
        minHeight: 650,
        autoHideMenuBar: true,
        frame: false,
        icon: icon,
        webPreferences: {
            enableRemoteModule: true,
            nodeIntegration: true,
            webviewTag: true
        }
    });
```
```
<webview ref="webviewDom" :src="url" class="webview"></webview>
```

**Comment by nklayman** [comment]
You will need to set `webview` as a custom element. To do so, set your `vue.config.js` to the following:
```js
module.exports = {
  chainWebpack: (config) => {
    config.module
      .rule('vue')
      .use('vue-loader')
      .loader('vue-loader')
      .tap((options) => {
        options.compilerOptions = {
          ...(options.compilerOptions || {}),
          isCustomElement: (tag) => /^webview/.test(tag)
        }
        return options
      })
  }
}
```
And install vue-loader v16: `npm i -D vue-loader@^16.0.0-rc.1` or `yarn add -D vue-loader@^16.0.0-rc.1`
