### ISSUE TITLE
installVueDevtools() never returns Promise

### ISSUE THREAD

**Issue by LittleHuba** [nklayman/vue-cli-plugin-electron-builder#122]
**Describe the bug**
The following code snippet in `src/background.ts` results in Electron never creating the BrowserWindow.
```
if (isDevelopment && !process.env.IS_TEST) {
    // Install Vue Devtools
    await installVueDevtools()
}
```

**To Reproduce**
Starting the app after creating it with vue-cli.
No BrowserWindow will show.

**Expected behavior**
A clear and concise description of what you expected to happen:
The BrowserWindow opening with VueDevtools installed.

**Environment (please complete the following information):**
 - OS and version: Windows 10
 - Node version: 11.0.0
 - npm version: 6.4.1
 - yarn version (if used): 1.10.1
 - vue-cli-plugin-electron-builder version : 1.0.0-rc.4
 - other vue plugins used: vuebar, vuetify
 - custom config for vcp-electron-builder: no
 - (if possible) link to your repo: If required I can provide read access to you, but the repo is private and will currently stay so

**Additional context**
Commenting out the line `await installVueDevtools()` fixes the bug.

**Comment by nklayman** [comment]
Are you in a location that blocks access to Vue devtools, such as China?

**Comment by LittleHuba** [comment]
Not that I know of.
Actually I have VueDevtools installed as extension in my Browser and it is working flawlessly. Thus I'm quite shure that this is not the problem.

**Comment by LittleHuba** [comment]
Further VueDevtools are even installed when I do comment out this line of code. Might this be the problem?

**Comment by aprilfall** [comment]
I encountered the same problem above，when I comment the line of `await installVueDevtools()`, it works,and the vue-dev-tool is installed in the electron window.

**Comment by nklayman** [comment]
I am running into it myself, rc-6 doesn't `await` the `installVueDevtools()`, which temporarily fixes the issue. I will have to look into it more tomorrow.

**Comment by Desuuuu** [comment]
I have experienced this since upgrading Node to v11.

AFAICT, the problem is caused by https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/master/lib/installVueDevtools/index.js#L31 ; a new promise is returned here (inside the first one created before).

This might be supposed to chain the promises (not sure at all, I don't know a lot about promises), but it does not for me on Node v11.

Calling the `resolve` callback from the first promise instead of `Promise.resolve` solves the issue for me.

**Comment by nklayman** [comment]
@Desuuuu I noticed that myself earlier, `1.0.0-rc.7` fixes that, so `background.js` will now `await` by default. Once you upgrade, you can update your `background.js` as well
