### ISSUE TITLE
DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by dbeja** [nklayman/vue-cli-plugin-electron-builder#1224]
**Describe the bug**
If I run the app with `electron:serve` it works fine, but when I build it with `electron:build` and run the app, I get a blank page and on the console I have the following warnings:

```
DevTools failed to load SourceMap: Could not load content for app://./js/app.b6131695.js.map: 
DevTools failed to load SourceMap: Could not load content for app://./js/chunk-vendors.4bccf704.js.map: 
```

**Expected behavior**
To run like it's running on `electron:serve`.

**Environment (please complete the following information):**
Using the default config.

**Comment by nklayman** [comment]
The devtools sourcemap error would not cause the page to fail to load. My guess is that you are using history mode, see [this page of the docs](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#blank-screen-on-builds-but-works-fine-on-serve) for more details. The sourcemap error is a problem with electron, not this plugin. See https://github.com/electron/electron/issues/21699 for more details on that.

**Comment by dbeja** [comment]
Ok, great, sorry, missed that page.
Working now!
