### ISSUE TITLE
[Bug]When I run `vue-cli-service electron:serve` in windows 10, Uncaught Error append appear and APP launch failed

### ISSUE THREAD

**Issue by oceanlvr** [nklayman/vue-cli-plugin-electron-builder#1229]
**Describe the bug**

When I run `vue-cli-service electron:serve` , something Error appear, and the electron app load failed. 

Could you plz help me, I don't know how to solve.

**To Reproduce**

here is my `package.json`:

```json
  "scripts": {
    "electron:serve": "vue-cli-service electron:serve",
     ...
   }
```

then run `yarn run electron:serve`. Error appear.
```shell
 INFO  Launching Electron...
Uncaught (in promise) Error: Invalid header: Does not start with Cr24
    at crxToZip (webpack:///./node_modules/unzip-crx/dist/index.js?:32:15)
    at eval (webpack:///./node_modules/unzip-crx/dist/index.js?:57:32)    
    at callHanler (webpack:///./node_modules/yaku/lib/yaku.js?:719:16)    
    at tryCatcher (webpack:///./node_modules/yaku/lib/yaku.js?:436:32)    
    at eval (webpack:///./node_modules/yaku/lib/yaku.js?:575:38)
    at flush (webpack:///./node_modules/yaku/lib/yaku.js?:478:17)
    at processTicksAndRejections (internal/process/task_queues.js:79:9)  
```

**Expected behavior**
Electron APP launch success.

**Screenshots**
![image](https://user-images.githubusercontent.com/36698124/106694919-7c8e1f00-6614-11eb-9423-89be818fc78e.png)

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: none
 - (if possible) link to your repo: [https://github.com/emqx/MQTTX](https://github.com/emqx/MQTTX)
 - terminal output from running `vue info`:  `INFO  Launching Electron...`

**Additional context**

[package.json](https://github.com/emqx/MQTTX/blob/dev/v1.5.2/package.json)
[yarn.lock](https://github.com/emqx/MQTTX/blob/dev/v1.5.2/yarn.lock)

ref:
Same like this issue in other repo:
[electron-react-boilerplate/issues/2577](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2577)

**Comment by baruchiro** [comment]
We also facing this, not for all the developers (I think).

As a workaround, we [commenting out](https://github.com/brafdlog/budget-tracking/discussions/189#discussioncomment-330234) the lines related to the *DevTools* in the `backround.ts` file:

```ts
// if (!process.env.IS_TEST) mainWindow.webContents.openDevTools();
...
// await installVueDevtools(); 
```

**Comment by nklayman** [comment]
@oceanlvr the project you linked is using a really old version of electron (v5). I think it will work if you upgrade to a more recent electron version.

**Comment by oceanlvr** [comment]
> @oceanlvr the project you linked is using a really old version of electron (v5). I think it will work if you upgrade to a more recent electron version.

YES! it works in the latest version. THANKS!

I just follow this change: [vue-cli-plugin-electron-builder/releases/tag/v2.0.0-rc.4](https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-rc.4)

```diff
import {
  createProtocol,
- installVueDevtools
} from 'vue-cli-plugin-electron-builder/lib'
+ import installExtension, { VUEJS_DEVTOOLS } from 'electron-devtools-installer'

... (around line 77)

-await installVueDevtools()
+await installExtension(VUEJS_DEVTOOLS)
```

> We also facing this, not for all the developers (I think).

@baruchiro After performing the above operations, our team's vue-cli-server can work normally, maybe you can have a try.

**Comment by oceanlvr** [comment]
> We also facing this, not for all the developers (I think).
> 
> As a workaround, we [commenting out](https://github.com/brafdlog/budget-tracking/discussions/189#discussioncomment-330234) the lines related to the _DevTools_ in the `backround.ts` file:
> 
> ```ts
> // if (!process.env.IS_TEST) mainWindow.webContents.openDevTools();
> ...
> // await installVueDevtools(); 
> ```

thanks for your suggestion, I'll try, it caused by DevTools.

**Comment by baruchiro** [comment]
> > We also facing this, not for all the developers (I think).
> > As a workaround, we [commenting out](https://github.com/brafdlog/budget-tracking/discussions/189#discussioncomment-330234) the lines related to the _DevTools_ in the `backround.ts` file:
> > ```ts
> > // if (!process.env.IS_TEST) mainWindow.webContents.openDevTools();
> > ...
> > // await installVueDevtools(); 
> > ```
> 
> thanks for your suggestion, I'll try, it caused by DevTools.

So I didn't understand. Is the `electron-devtools-installer` solved your issue or not?

**Comment by oceanlvr** [comment]
@baruchiro 
I think the reason for this error is that we are using the old version of `vue-cli-plugin-electron-builder`.
In the new version, We changed the way VUEJS_DEVTOOLS was introduced, as in the code I posted above.
All of our team’s constructions will not have this problem.

here is my relative PR: [https://github.com/emqx/MQTTX/pull/497](https://github.com/emqx/MQTTX/pull/497)

**Comment by baruchiro** [comment]
I tried to do the same change, but the *Vue DevTools* is not installed. I have no time to check this now, maybe later.

**Comment by mankey-ru** [comment]
Can confirm, commenting out installVueDevtools helped, now it works. However, update should fix the problem at all, because versions are too old:
`"electron": "^3.0.0"`
`"vue-cli-plugin-electron-builder": "^1.3.1",`

**Comment by baruchiro** [comment]
Of course, I'm using an old version. I'm using version `1.4.6`, the latest `v1` version.

Do I have to move to `V2`?

 - It required me to do some migration work.
 - I'm not sure, but all the `V2` versions marked as `beta` or `rc`, so what are my options? To use deprecated or use an extreme version?

**Comment by nklayman** [comment]
@baruchiro See the v2.0.0 [release announcement](https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-rc.1) for the migration guide and major changes. Even though it's marked as RC, it's more stable than v1. TBH I should have published it as `2.0.0` a while ago, I've just been really busy with other work so this has taken a backseat for a little while.

**Comment by yannxaver** [comment]
I receive the error message mentioned here `Uncaught (in promise) Error: Invalid header: Does not start with Cr24` when I change the `name` value in my `package.json`. So with name `x` `vue-cli-service serve` works fine but if I change the name to `y` it throws this error. Any idea how this could happen? I don't use any special characters in the `name` field.

**Comment by Symbolk** [comment]
Same problem here after a long time when I re-picked my project (https://github.com/Symbolk/SmartCommit), and there is another similar issue for another scaffold: https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2577.

However, it seems that upgrading to V2 costs too much and may bring risks, so I decide to just comment the line.
