### ISSUE TITLE
Build fails on macOS with Electron 4.0 beta

### ISSUE THREAD

**Issue by caesar** [nklayman/vue-cli-plugin-electron-builder#123]
**Describe the bug**
Build fails on macOS with Electron 4.0 beta due to an error thrown by electron-builder when attempting to modify the helper app plists, which don't exist anymore.

This bug is fixed in electron-builder@20.29.0, so it would be good to update vue-cli-plugin-electron-builder's dep to that version.

**To Reproduce**
Build any app with Electron 4.0 beta on any version of macOS.

**Expected behavior**
Build should work.

**Environment (please complete the following information):**
 - OS and version: macOS 10.14.1
 - Node version: 11.0.0
 - npm version: 6.4.1
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 1.0.0-rc.7
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**
https://github.com/electron-userland/electron-builder/issues/3385
https://github.com/electron-userland/electron-builder/commit/7fc9a2965358fdeff3d757633695609236d7759d
https://github.com/electron-userland/electron-builder/releases/tag/v20.29.0

**Comment by nklayman** [comment]
fixed with a214804acdd90c286262d631a70dcd9d1fb7cde2
