### ISSUE TITLE
vue-cli-service- Error: Cannot find module 'vue-cli-plugin-electron-builder'

### ISSUE THREAD

**Issue by peepopoggers** [nklayman/vue-cli-plugin-electron-builder#1233]
**Describe the bug**
I try to start `npm run electron-serve` or `vue-cli-service` and in both instances it does not function. Gives me error saying module does not exist. Using Vue2 Project. 

**To Reproduce**
Not Sure. Can Link `package.json` commands.
This happens after an install of the vue builder, using `vue add electron-builder`
Then trying to compile.

Package.json: https://pastecode.io/s/vV10UZu7MK

**Expected behavior**
Command will not run, says cannot find module.

**Screenshots**
![image](https://user-images.githubusercontent.com/72892531/107128682-94390200-68b7-11eb-806b-137fbae69970.png)

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 
 This, With Electron Installed. https://github.com/tvjsx/trading-vue-101
 - terminal output from running `vue info`:
 - 
![image](https://user-images.githubusercontent.com/72892531/107128700-bc286580-68b7-11eb-88ab-e30ba7f3b62d.png)

**Additional context**
-

**Comment by nklayman** [comment]
The project you linked doesn't use vue cli. This plugin will only work in a vue cli v3 or v4 project. See [the vue cli docs](https://cli.vuejs.org/) for instructions on creating a project with vue cli.
