### ISSUE TITLE
Question: Where is my db file after build for mac and windows

### ISSUE THREAD

**Issue by ClementVanPeuter** [nklayman/vue-cli-plugin-electron-builder#1242]
This is not an Issue.
This is probably a Dumb question but I can't wrap my head around.

First, Thank you for this VCP electron Builder, love It.

I followed #275 ( I use Sequelize and Sqlite Database) and everything works great.
I build my app for Mac and Windows and everything works great.

My Question is :
Once my app is build for mac os and windows where is my database file ?
Where I can found my data.db in my production app ? For example: manual backup ?

I can't found anything in dist_electron file neither in the Mac Folder or the win_unpack Folder.

Is that bundled or something ?

Thanks again.

**Comment by nklayman** [comment]
It won't be created till you run your app. Then, it should be in `dist_electron/PLATFORM-unpacked/resources/data.db`.
