### ISSUE TITLE
@vue/cli presets to auto include VCPEB when creating a new project fails during creation

### ISSUE THREAD

**Issue by wattsie** [nklayman/vue-cli-plugin-electron-builder#1249]
Hi, just wondering if anyone has been able to use VCPEB within a @vue/cli preset for automatic project creation? 
Is this supported or do I need to always add it manually once the project is created? (would be nice to do it automatically)

ie. whenever I try to use a vue-cli preset to create a new project, it fails whenever I include VCPEB.

However, if you remove VCPED from the preset, create the new app then manually `vue add electron-builder` and select the options it works.

As per `~/.vuerc` below, I am passing the version config, and I have tried testing both `"electronBuilder.electronVersion": "^11.0.0"` and `"electronVersion": "^11.0.0"` within the `~/.vuerc` but appears somehow the version is not being passed or computed.

Have confirmed the options in the "prompts.js" file verify "name" and "value" for the options.

Have tested both yarn and npm, same result.

**To Reproduce**
Add (or create a new) present in the ~/.vuerc and then create a new project
`vue create -p Vue3_ALL_Plus2 new_project`

**Expected behavior**
New project with all presets installed and configured

**Actual behavior**
```
$ electron-builder install-app-deps
  • electron-builder  version=22.9.1
  ⨯ Cannot compute electron version from installed node modules - none of the possible electron modules are installed.
See https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-504968246
error Command failed with exit code 1.
```

Environment Info:
```
  System:
    OS: macOS 10.15.7
    CPU: (24) x64 Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
  Binaries:
    Node: 15.8.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.150
    Edge: 88.0.705.68
    Firefox: 85.0.2
    Safari: 14.0.3
  npmGlobalPackages:
    @vue/cli: 4.5.11
```

**Additional context**
~/.vuerc                                                                                                                                                                                                 
```
{
  "useTaobaoRegistry": false,
  "packageManager": "yarn",
  "latestVersion": "4.5.11",
  "presets": {
    "Vue3_ALL_Plus2": {
      "useConfigFiles": true,
      "plugins": {
        "@vue/cli-plugin-babel": {},
        "@vue/cli-plugin-typescript": {
          "classComponent": true,
          "useTsWithBabel": true
        },
        "@vue/cli-plugin-router": {
          "historyMode": false
        },
        "@vue/cli-plugin-vuex": {},
        "@vue/cli-plugin-eslint": {
          "config": "base",
          "lintOn": []
        },
        "@vue/cli-plugin-unit-mocha": {},
        "@vue/cli-plugin-e2e-cypress": {},
        "vue-cli-plugin-moment": {
          "locales": "en"
        },
        "vue-cli-plugin-fontawesome": {},
        "vue-cli-plugin-electron-builder": {
          "electronBuilder.electronVersion": "^11.0.0",
          "electronBuilder.addTests": true
        }
      },
      "vueVersion": "3",
      "cssPreprocessor": "dart-sass"
    }
  }
}
```

Many thanks in advance.

**Comment by nklayman** [comment]
Because of the way the prompts are configured, the preset config needs to look like this:
```json
  "presets": {
    "test": {
      "useConfigFiles": true,
      "cssPreprocessor": "sass",
      "plugins": {
        "@vue/cli-plugin-babel": {},
        "@vue/cli-plugin-eslint": {
          "config": "airbnb",
          "lintOn": ["save", "commit"]
        },
        "vue-cli-plugin-electron-builder": {
          "electronBuilder": { "electronVersion": "^11.0.0" }
        }
      }
    }
  }
```
