### ISSUE TITLE
Any plans on using electron-builder v 22.10.4?

### ISSUE THREAD

**Issue by vpoddubny** [nklayman/vue-cli-plugin-electron-builder#1252]
Apple introduced new MACs with AMD processors. _electron-builder_ added support for AMD, but it's still in pre-release state.

Are there any plans on introducing some pre-release version of _vue-cli-plugin-electron-builder_, which uses latest _electron-builder_? Or should we wait for electron-builder release?

Thanks.

**Comment by nklayman** [comment]
This plugin will only ship with the stable version of electron-builder. If you want to use a different version, you can do so through [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/), which will allow you to use a prerelease version without me having to do any special versions of this plugin.
