### ISSUE TITLE
vue-cli@5 support

### ISSUE THREAD

**Issue by SnosMe** [nklayman/vue-cli-plugin-electron-builder#1253]
Hello, I'm trying to use it with v5.0.0-alpha.4

`electron:serve` works without any issues even in complex project (https://github.com/SnosMe/awakened-poe-trade/), unfortunately `electron:build` (tested in clean project) results in 

```
$ vue-cli-service electron:build
 INFO  Bundling render process:

-  Building modern bundle for production... ERROR  Vue CLI build failed. Please resolve any issues with your build and try again.
error Command failed with exit code 1.
```

**Comment by williamweckl** [comment]
Same issue here, it is the only thing preventing me to use webpack 5.

**Comment by nklayman** [comment]
This is a bug with vue cli v5 rather than this plugin. I created an issue on their repo: https://github.com/vuejs/vue-cli/issues/6312
