### ISSUE TITLE
problems with @vue/cli 5.0.0-alpha.4

### ISSUE THREAD

**Issue by jzyismylover** [nklayman/vue-cli-plugin-electron-builder#1258]
**Describe the bug**
when i use electron-builder through 'yarn electron:build', it turns to a problem 'ERROR  Vue CLI build failed. Please resolve any issues with your build and try again.' I don't  know how to fix it.

**Comment by nklayman** [comment]
Duplicate of #1253. I should be able to take a look at it sometime soonish.
