### ISSUE TITLE
question: is main process webpack compilation necessary?

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [nklayman/vue-cli-plugin-electron-builder#126]
**Is your feature request related to a problem? Please describe.**
When developing with some libraries it get incredibly difficult to compile them because they check their environment and then take decisions which protocols and dependencies to use. This makes it necessary to configure webpack a lot which I find cumbersome.

**Describe the solution you'd like**
Having a flag for not using Webpack at all would be helpful.

My question is also in general nature: why compile the main process at all?

**Comment by eljefedelrodeodeljefe** [comment]
I see. However, I do not believe that this solves the problem due to the upstream dep making runtime decisions. Would you take a PR for a CLI option on `vue add`?

**Comment by nklayman** [comment]
Sure, it wouldn't hurt to provide

**Comment by eljefedelrodeodeljefe** [comment]
Note sure, but didn't you do this in https://github.com/nklayman/vue-cli-plugin-electron-builder/commit/96f8b24bb8d5dd622a6090bb0bdac979388d52f3 ? it's just lacking docs, no?

**Comment by nklayman** [comment]
Yes. However, there are many things that need to be fixed by the user for it to work, so I don't document it. See https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/98#issuecomment-426370253 fore more info.

**Comment by nklayman** [comment]
Were you able to get that working? If so, please close this issue.
