### ISSUE TITLE
Null coalescing operator and optional chaining not handled in main build

### ISSUE THREAD

**Issue by mathieutu** [nklayman/vue-cli-plugin-electron-builder#1261]
**Describe the bug**
Hi,

Thanks for this plugin.
"New" syntax like "Null coalescing operator" and "optional chaining" make the main build fail.
``` 
error  in ./src/electron/main.ts

Module parse failed: Unexpected token (14:25)
File was processed with these loaders:
 * ./node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
|         { scheme: 'app', privileges: { secure: true, standard: true } },
|     ]);
>     console.log('false' ?? 'true');
|     await registerAppEventsListeners(app);
|     createMenu();

 @ multi ./src/electron/main.ts
```

```
 error  in ./src/electron/main.ts

Module parse failed: Unexpected token (15:20)
File was processed with these loaders:
 * ./node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
|     ]);
|     const foo = {};
>     console.log(foo?.bar || 'fff');
|     await registerAppEventsListeners(app);
|     createMenu();

 @ multi ./src/electron/main.ts
```

**To Reproduce**
Add any of them in your main file.
```js
console.log('foo' ?? 'bar');
console.log(foo?.bar);
```

**Expected behavior**
Build ok with transpilation needed for the electron version (so none I think). 

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: 
 ```
	mainProcessFile: path.join(__dirname, 'main.ts'),
    mainProcessTypeChecking: true,
    mainProcessWatch: [__dirname],
  ```
 - terminal output from running `vue info`:
```
System:
    OS: macOS 11.1
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
```

vcp-electron-builder version : 2.0.0-rc.6

**Comment by nklayman** [comment]
This is because terser did not support these features (see https://github.com/terser/terser/issues/567). While the latest version of Terser works, I haven't upgraded to it because that would be a breaking change. V3 of this plugin will use it, along with webpack v5. Until then, you can use [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) to override the `terser-webpack-plugin` to v4 (not v5 as that doesn't support webpack 4). This should resolve your issue.

**Comment by mathieutu** [comment]
Ok, thanks. Maybe could we put a note about that on the readme?

**Comment by mathieutu** [comment]
However, I don't understand why parser is used here, and not the vuejs standard build part with webpack and babel. 🤔

**Comment by nklayman** [comment]
The VueJS standard build config is very different as it is designed to target the browser, rather than the Electron main process. There are a lot of config differences between the two targets, so the main process uses a custom configuration.
