### ISSUE TITLE
How to set the path of Tray icon?

### ISSUE THREAD

**Issue by Nexround** [nklayman/vue-cli-plugin-electron-builder#1262]
I am using the latest version of this plugin and now it looks like the dir is different from the online doc.
I looked for the solution from many online information but I didn't find way to solve my problem. I have tried to use many different relative paths in the Tray() and put icon in different dir but it just can't find the icon.
https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#icons
According to this URL that it feels like there should be a `build `dir in my project (and maybe there are more config files need to be created manually), but I can only find the `dist_electron` dir. Is this the new version's result? So what should I do to set the right path?
I have successfully run the Tray in the original Electron without vue with a relative path. 
Thanks for your help

**Comment by nklayman** [comment]
The `build` dir is one you create yourself if you want installer/executable icons through electron-builder. To have a tray icon, it isn't required. Just place a `logo.png` in the `public` folder and then use this to create the tray:
```js
// eslint-disable-next-line no-undef
const tray = new Tray(path.join(__static, 'logo.png'))
```

Also make sure to `import path from 'path'` at the top of your file.
