### ISSUE TITLE
use sqlite3

### ISSUE THREAD

**Issue by amirhossein95b** [nklayman/vue-cli-plugin-electron-builder#1264]
How to use sqlite3 and How to address the database file?

**Comment by nklayman** [comment]
See #76, you may also need to add sqlite3 as an external:
```js
// vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['sqlite3']
    }
  }
}
```

**Comment by amirhossein95b** [comment]
Can you give a complete example? Is it possible to use sqlite3 inside vue itself? Can you provide a complete documentary on this topic?

**Comment by nklayman** [comment]
Issue #76, along with any generic guide on using sqlite3 in Node should be sufficient for you to add sqlite3 to your project. I can't offer too much support for free as I have many other commitments. However, if you [sponsor me](https://github.com/sponsors/nklayman/) for $10/month or more I'll create a repo that demonstrates using sqlite3 inside of Vue and explain how I did it.

**Comment by amirhossein95b** [comment]
I am Iranian, dear. And it is not possible for me to pay the debt. And the more complete the documentary, the better for you, not me
