### ISSUE TITLE
Loading iohook doesn't work

### ISSUE THREAD

**Issue by michelvermeulen** [nklayman/vue-cli-plugin-electron-builder#1268]
**Describe the bug**
Using vue-cli + vue-cli-electron-installer
Added the iohook settings according to my setup 
Edited package.json
```
"iohook": {
    "targets": [
      "node-83",
      "electron-85"
    ],
    "platforms": [
      "win32",
      "darwin"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  },
```
npm i

I can see the correct build .node file in my node_modules, but `npm run electron:serve` throws an error :

```
Error: Cannot find module '/Users/useruser/Projects/project/dist_electron/builds/electron-v85-darwin-x64/build/Release/iohook.node'
    at webpackEmptyContext (webpack:///./node_modules/iohook_sync?:2:10)
    at eval (webpack:///./node_modules/iohook/index.js?:10:80)
    at Object../node_modules/iohook/index.js (/Users/useruser/Projects/project/dist_electron/index.js:1163:1)
    at __webpack_require__ (/Users/useruser/Projects/project/dist_electron/index.js:20:30)
    at eval (webpack:///./src/background.js?:16:16)
    at Module../src/background.js (/Users/useruser/Projects/project/dist_electron/index.js:2451:1)
    at __webpack_require__ (/Users/useruser/Projects/project/dist_electron/index.js:20:30)
    at eval (webpack:///multi_./src/background.js?:1:18)
    at Object.0 (/Users/useruser/Projects/project/dist_electron/index.js:2522:1)
    at __webpack_require__ (/Users/useruser/Projects/project/dist_electron/index.js:20:30)

```

I tried to manually copy the iohook.node file in the expected folder structure (under dist_electron/builds/electron-v85-darwin-x64/build/Release/) but it also does not work (although the file exists).

**To Reproduce**

Create a vue-cli project, add vue-cli-plugin-electron-installer, and add iohook as a dependency.

**Environment (please complete the following information):**
```
System:
    OS: macOS 11.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.15.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Firefox: 84.0.2
    Safari: Not Found
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.0.3
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.11
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.11
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.11
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.11
    @vue/cli-plugin-router: ~4.5.0 => 4.5.11
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.11
    @vue/cli-service: ~4.5.0 => 4.5.11
    @vue/cli-shared-utils:  4.5.11
    @vue/component-compiler-utils:  3.2.0
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    vue: ^2.6.11 => 2.6.12
    vue-cli-plugin-electron-builder: ~2.0.0-rc.6 => 2.0.0-rc.6
    vue-eslint-parser:  7.4.1
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.6 (16.1.2)
    vue-router: ^3.2.0 => 3.5.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.12
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.4.0 => 3.6.2
    vuex-electron: ^1.0.3 => 1.0.3
  npmGlobalPackages:
    @vue/cli: 4.5.11
```

**Comment by nklayman** [comment]
You'll probably need to mark `iohook` as an external:
```
// In vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: 'iohook'
    }
  }
}
```
If you are using it in the renderer process (Vue app), you will need to enable [nodeIntegration](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration) as well. Let me know if that fixes it for you.

**Comment by michelvermeulen** [comment]
Hey @nklayman 

Thanks so much for helping out !

I did both: added 

integrations: ["iohook"]

since it's expecting an array, turned on nodeintegration, same thing.

The only dirty fix I was able to come up with is:

- Change the index.js of iohook to puth a string instead of a variable for the path (it's weird, but it works) : `let NodeHookAddon = require('/Users/xxxxx/Projects/xxxxxx/dist_electron/builds/electron-v85-darwin-x64/build/Release/iohook.node');`
- Copy uiiohook.dylib to dist_electron

I really don't understand why it's loading the file from dist_electron, and why it's not loading when using a variable but loading when using a string path. The original code was:

```
const modulePath = path.join(__dirname, 'builds', essential, 'build', 'Release', 'iohook.node');
let NodeHookAddon = require(modulepath);
```

That doesn't work...

Any help is appreciated, I sratched my head the whole afternoon yesterday and my eyes are still soar today 🔢

**Comment by nklayman** [comment]
Hmm, I added it as an external and it worked fine for me on Linux. Can you post a repo that demonstrates the error so I can debug it further?

**Comment by michelvermeulen** [comment]
Hmmmm. Let me send you as much code as I can (it's not possible to share the repo unfortunately).

Here's my vue.config.js 

```
module.exports = {
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true,
      mainProcessWatch: ["src/background.js", "src/modules/shortcut.js"],
      externals: ["iohook"],
// BELOW IS MY DIRTY FIX, LOADING THE NODE MODULE MANUALLY
      chainWebpackMainProcess: config => {
        config.module
          .rule("node")
          .test(/\.node$/)
          .use("node-loader")
          .loader("node-loader")
          .end()
      },
    },
  },
}

```

package.json
```
{
  "name": "myapp",
  "version": "2.0.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "rebuild": "electron-rebuild -f -w iohook,robotjs",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps"
  },
  "iohook": {
    "targets": [
      "node-83",
      "electron-85"
    ],
    "platforms": [
      "win32",
      "darwin"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  },
  "main": "background.js",
  "dependencies": {
    "core-js": "^3.6.5",
    "electron-promise-ipc": "^2.2.4",
    "robotjs": "^0.6.0",
    "vue": "^2.6.11",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0",
    "vuex-electron": "^1.0.3"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "electron": "^11.0.0",
    "electron-devtools-installer": "^3.1.0",
    "electron-rebuild": "^2.3.5",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-vue": "^6.2.2",
    "iohook": "^0.7.2",
    "node-loader": "^1.0.2",
    "prettier": "^1.19.1",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "vue-cli-plugin-electron-builder": "~2.0.0-rc.6",
    "vue-template-compiler": "^2.6.11"
  }
}

```

And in my background.js

```
"use strict"

import registerShortcuts from "@/modules/shortcut.js"
import { app, protocol, BrowserWindow, ipcMain } from "electron"
import { createProtocol } from "vue-cli-plugin-electron-builder/lib"
import installExtension, { VUEJS_DEVTOOLS } from "electron-devtools-installer"
const robot = require("robotjs")
const ioHook = require("iohook")
```

index.js of iohook looks like (basically their original index.js)

```
const EventEmitter = require('events');
const path = require('path');

const runtime = process.versions['electron'] ? 'electron' : 'node';
const essential = runtime + '-v' + process.versions.modules + '-' + process.platform + '-' + process.arch;
const modulePath = path.join(__dirname, 'builds', essential, 'build', 'Release', 'iohook.node');
if (process.env.DEBUG) {
  console.info('Loading native binary:', modulePath);
}
let NodeHookAddon = require(modulePath);
```

And this is what I have when I run npm run electron:serve


```
 INFO  Launching Electron...
App threw an error during load
Error: Cannot find module '/Users/michelvermeulen/Projects/typedesk_v2_native/dist_electron/builds/electron-v85-darwin-x64/build/Release/iohook.node'
    at webpackEmptyContext (webpack:///./node_modules/iohook_sync?:2:10)
    at eval (webpack:///./node_modules/iohook/index.js?:12:80)
    at Object../node_modules/iohook/index.js (/Users/michelvermeulen/Projects/typedesk_v2_native/dist_electron/index.js:1219:1)
    at __webpack_require__ (/Users/michelvermeulen/Projects/typedesk_v2_native/dist_electron/index.js:20:30)
    at eval (webpack:///./src/background.js?:16:16)
    at Module../src/background.js (/Users/michelvermeulen/Projects/typedesk_v2_native/dist_electron/index.js:2530:1)
    at __webpack_require__ (/Users/michelvermeulen/Projects/typedesk_v2_native/dist_electron/index.js:20:30)
    at eval (webpack:///multi_./src/background.js?:1:18)
    at Object.0 (/Users/michelvermeulen/Projects/typedesk_v2_native/dist_electron/index.js:2981:1)
    at __webpack_require__ (/Users/michelvermeulen/Projects/typedesk_v2_native/dist_electron/index.js:20:30)


```

**Comment by Wurielle** [comment]
> You'll probably need to mark `iohook` as an external:
> 
> ```
> // In vue.config.js
> module.exports = {
>   pluginOptions: {
>     electronBuilder: {
>       externals: 'iohook'
>     }
>   }
> }
> ```

I've been fighting to try to get `iohook` working for a few days now and I have the pleasure to say that this indeed fixed the issue on my end so thank you for that! 😄 

I had to downgrade to `electron@11.2.3` because `iohook` doesn't support v12.0.0 yet but otherwise everything is working as it should in `electron:serve` mode at least.

Here's my `iohook` config in my `package.json`:
```
}
  ...
  "dependencies": {
    ...
    "iohook": "^0.7.2",
    ...
  },
  "devDependencies": {
    ...
    "electron": "^11.2.3",
    ...
  }
  ...
  "iohook": {
    "targets": [
      "electron-85"
    ],
    "platforms": [
      "win32",
      "darwin"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  }
}
```
____
To comment on @michelvermeulen's issue:
> ```
>  INFO  Launching Electron...
> App threw an error during load
> Error: Cannot find module '/Users/michelvermeulen/Projects/xxxx/dist_electron/builds/electron-v85-darwin-x64/build/Release/iohook.node'
>     at webpackEmptyContext (webpack:///./node_modules/iohook_sync?:2:10)
>     at eval (webpack:///./node_modules/iohook/index.js?:12:80)
>     at Object../node_modules/iohook/index.js (/Users/michelvermeulen/Projects/xxxx/dist_electron/index.js:1219:1)
>     at __webpack_require__ (/Users/michelvermeulen/Projects/xxxx/dist_electron/index.js:20:30)
>     at eval (webpack:///./src/background.js?:16:16)
>     at Module../src/background.js (/Users/michelvermeulen/Projects/xxxx/dist_electron/index.js:2530:1)
>     at __webpack_require__ (/Users/michelvermeulen/Projects/xxxx/dist_electron/index.js:20:30)
>     at eval (webpack:///multi_./src/background.js?:1:18)
>     at Object.0 (/Users/michelvermeulen/Projects/xxxx/dist_electron/index.js:2981:1)
>     at __webpack_require__ (/Users/xxxxxx/Projects/xxxx/dist_electron/index.js:20:30)
> ```

Have you tried checking inside your `node_modules` folder in `'/Users/michelvermeulen/Projects/xxxx/dist_electron/builds/` if  `electron-v85-darwin-x64/build/Release/iohook.node` exists?
If not, try to run `npm rebuild` so that `iohook` can generate the files for you.

**Comment by nklayman** [comment]
@michelvermeulen I don't see anything that looks like it would cause an issue. Adding it as an external for me (and for @Wurielle), so I don't think it is an issue with this plugin, so I'll close this. If you can create a demo repo that shows the error and post it here, I'll look into it. Otherwise, I can't really help you as I can't trigger the error myself.

**Comment by michelvermeulen** [comment]
SUCCESS!

So thanks to both your comments, I think I figured it out. iohook was in my devDependencies, and moving it to dependencies + adding to the externals did the trick!

Guys, I can't stress enough how this was a pin in my *** so massive thanks! 💙
