### ISSUE TITLE
electron:build command does not copy project package.json - no node modules installed

### ISSUE THREAD

**Issue by jakerieger** [nklayman/vue-cli-plugin-electron-builder#1269]
When running `electron:build`, the project package.json in the root directory is not copied to the `dist_electron/bundled` folder and no dependencies are installed. Running the built executable results in a lot of `module <name> not found` errors in the console.

1. Create a new Vue 2 project with the Vue CLI -> `vue create <name>`
2. Add this plugin as per the docs -> `vue add electron-builder`
3. Install any node package. For example, `yarn add node-fetch`
4. Use this package in any of the source files.
5. Build the app with `yarn electron:build`
6. Run the built .exe and check the console. You will see a missing module for that package error. To further verify this, extracting the `app.asar` in the `dist_electron/win-unpacked/resources` folder and opening the output folder will show you none of your installed node modules in the dependencies section of your package.json are copied over.

**Expected behavior**
All packages in the `dependencies` section of the project package.json should be copied over when building the project.

**Environment:**
- Windows 10
- Yarn (but same problem with NPM)
- "vue-cli-plugin-electron-builder": "~2.0.0-rc.6"
- "electron": "^11.0.0"

**Additional context**
I original encountered this error in a project I had been working on for months and it appeared within the last couple days. Tried this with just a basic Vue project created with the CLI and only modified the background.js file to use the node-fetch package I had installed. Same problem.

**Comment by nklayman** [comment]
That's odd that your package.json isn't copied. It works fine for me and [the code that copies it](https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/7e6ad86539a5d6cff3be85c2bc9aa44373f4dba1/index.js#L158-L172) doesn't have any conditionals on it (expect for `--skipBundle`, which is intentional). Can you post a link to a repo that demonstrates the error? Thanks!

**Comment by jakerieger** [comment]
https://github.com/jakerieger/test-vue-electron-builder-project

One thing to note is I had a friend create a new project using the same steps above and he had the same problem as well so it doesn't appear to a problem with my computer/project specifically.

**Comment by nklayman** [comment]
`node-fetch` is designed to be run in node, so you will have to enable [nodeIntegration](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration) to use it in the renderer process (Vue app). After enabling it, your repo worked fine. Not sure why you would need to use that however, as you could just use the native fetch api provided by the browser.

**Comment by jakerieger** [comment]
nodeIntegration is enabled in my renderer process and it works just fine when running the `electron:serve` command, I'm aware you can use regular fetch, node-fetch was the first module I thought of as a test. My main project has dozens of modules and none of them are copied.

**Comment by nklayman** [comment]
Try adding a `vue.config.js` file with this in it:
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['node-fetch']
    }
  }
}
```
See the [docs on native modules](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules) for more details on the `externals` property.

**Comment by jakerieger** [comment]
So it turned out be an issue with `require` in Vue files. For some reason in order to import the `remote` module and things like `fs` and `process`, you need to use `window.require`. I was under the impression you needed to do this for any node module which isn't the case. Changing all my `window.require` to `require` solved the issue.

**Comment by nklayman** [comment]
Yeah, you should use es6 `import` statements actually. Webpack automatically bundles all your deps together for you.

**Comment by jakerieger** [comment]
Good to know. Appreciate the advice.
