### ISSUE TITLE
How to run the App like the testWithSpectron run it?

### ISSUE THREAD

**Issue by baruchiro** [nklayman/vue-cli-plugin-electron-builder#1273]
https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/f95dc59fc0260eb63fb0bdf413c798e5e4e8f1ed/docs/guide/testingAndDebugging.md#L33

I have so many problems with `testWithSpectron` for a very long time.

Now, after upgrading this plugin to `V2`, I'm trying to use the e2e tests again, and it is not working.

But I sew the `testWithSpectron` code, and one of the things I learned (more things will come) is that if you run `vue-cli-service electron:serve`, you will not see the same errors as you will see if you run `vue-cli-service electron:serve --headless --mode test`, like the `testWithSpectron` do.

I think we need to add this (`vue-cli-service electron:serve --headless --mode test`) command to the docs, in order to let the developers research more, if they have a problem.

I'm opening an issue because I don't know exactly what is the change. I guess it is because of the `--mode test`, but I'm not sure.

**Comment by nklayman** [comment]
`--headless` just tells the command that it shouldn't launch electron and instead print out some info that spectron will use to launch electron. `--mode test` sets the [mode](https://cli.vuejs.org/guide/mode-and-env.html#modes) to `test`, which is the default for the other test commands. At the bottom of the [testing docs page](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/testingAndDebugging.html#testing) the `testWithSpectron` options are detailed. You can change the `mode` option to `development` or `production` if you don't want to run it in test mode.

**Comment by baruchiro** [comment]
So I don't understand this line:
https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/54b2b19db8d252dc154476422680d3a6e08acdce/lib/testWithSpectron.js#L16

If I'm trying to run it myself, `vue-cli-service electron:serve --mode test`, I getting this:

```
 DONE  Compiled successfully in 28358ms

Type checking in progress...

  App running at:
  - Local:   http://localhost:8080/   
  - Network: http://192.168.1.50:8080/

  Note that the development build is not optimized.
  To create a production build, run yarn build.

 ERROR  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.mode should be one of these:
   "development" | "production" | "none"
   -> Enable production optimizations or development hints.
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.mode should be one of these:
   "development" | "production" | "none"
   -> Enable production optimizations or development hints.
    at webpack (C:\Users\baruchr\source\budget-tracking\node_modules\webpack\lib\webpack.js:31:9)
    at bundleMain (C:\Users\baruchr\source\budget-tracking\node_modules\vue-cli-plugin-electron-builder\index.js:690:17)
    at startElectron (C:\Users\baruchr\source\budget-tracking\node_modules\vue-cli-plugin-electron-builder\index.js:307:49)
    at C:\Users\baruchr\source\budget-tracking\node_modules\vue-cli-plugin-electron-builder\index.js:399:7
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Maybe this is the reason for getting timeout in e2e tests?

```
thrown: "Exceeded timeout of 100000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
```

**Comment by nklayman** [comment]
That's because the `testWithSpectron` function also sets the `NODE_ENVIRONMENT` to `production`. You can do this yourself with: `NODE_ENV=production yarn electron:serve --mode test`. On windows you will have to run `set NODE_ENV=production` and then run `yarn electron:serve --mode test` afterwards.
