### ISSUE TITLE
Dependency bug electron-builder < 22.2.0 prevents building Windows installer on macOS Catalina

### ISSUE THREAD

**Issue by travis5491811** [nklayman/vue-cli-plugin-electron-builder#1275]
**Describe the bug**
This package requires electron builder < 22.2.0. Previous versions did not address [issue with Windows installer issues on macOS Catalina](https://github.com/electron-userland/electron-builder/issues/4305). 

**To Reproduce**

1. Start project on Mac Catalina
2. Create `vue` electron project and use `vue-cli-plugin-electron-builder`
2. Build for windows

**Expected behavior**
Build for Windows should complete successfully like it does on older mac versions such as mojave, etc

**Additional context**
To resolve this issue, `electron-builder` dependency should be updated from version `21.2.0` to `22.2.0`

Ref:
https://github.com/electron-userland/electron-builder/issues/4305#issuecomment-559138959

**Comment by nklayman** [comment]
As you can see [here](https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/148513a3acf7717b4fb0f9d919404039e6115482/package.json#L34), this plugin uses the latest version of electron-builder. You may need to delete your `yarn.lock` or `package-lock.json` and then reinstall deps for it to be updated.
