### ISSUE TITLE
HTML file not load `index.js` when in Multiple Pages mode

### ISSUE THREAD

**Issue by ylc395** [nklayman/vue-cli-plugin-electron-builder#1276]
**version: 2.0.0-rc.6**

After running `yarn electron:serve`, HTML file does not load `index.js` when in Multiple Pages mode. 

Alaways reproduce when checking with browser or electron (browser sreenshot).

<img width="649" alt="图片" src="https://user-images.githubusercontent.com/12264626/109941934-9e132100-7d0e-11eb-9069-315e0906a443.png">

while after running `yarn serve`, everything goes fine (browser sreenshot):

<img width="616" alt="图片" src="https://user-images.githubusercontent.com/12264626/109942068-c9960b80-7d0e-11eb-9e88-910cc5a2bec3.png">

Here is my `vue.config.js` file:
```js
const path = require('path');
const webAppEntry = 'src/drivers/ui/web/main.ts';
const alias = {
  entity: path.resolve(__dirname, 'src/domain/entity'),
  service: path.resolve(__dirname, 'src/domain/service'),
  repository: path.resolve(__dirname, 'src/domain/repository'),
  drivers: path.resolve(__dirname, 'src/drivers'),
};

module.exports = {
  pages: {
    index: {
      entry: webAppEntry,
      template: 'src/drivers/ui/web/public/index.html',
    },
  },
  configureWebpack: {
    resolve: { alias },
  },
  pluginOptions: {
    electronBuilder: {
      chainWebpackMainProcess: config => {
        Object.keys(alias).forEach(key => {
          config.resolve.alias.set(key, alias[key]);
        });
      },
      // @see https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/578#issuecomment-561972824
      externals: ['sequelize'],
      mainProcessFile: 'src/drivers/ui/electron/main.ts',
      rendererProcessFile: webAppEntry,
      mainProcessWatch: ['src/drivers/ui/electron/*'],
      mainProcessArgs: ['--arg-name', 'arg-value'],
    },
  },
};

```

**Comment by nklayman** [comment]
Try removing the `rendererProcessFile` config from your `vue.config.js`. If that doesn't work, I'm going to need a repo that demonstrates the error as I can't replicate it myself. You can see https://github.com/nklayman/electron-multipage-example/ for an example as well.

**Comment by Jack-Barry** [comment]
@nklayman I did this in my project and it worked, but I don't remember seeing anything in the docs about removing it for multi page config vs. single page, maybe a caveat should be added?

It's clear in hindsight why it wouldn't need to be there anymore though

**Comment by ylc395** [comment]
> Try removing the `rendererProcessFile` config from your `vue.config.js`. If that doesn't work, I'm going to need a repo that demonstrates the error as I can't replicate it myself. You can see https://github.com/nklayman/electron-multipage-example/ for an example as well.

It worked, thanks very much. Maybe adding this information into docs would be helpful?

**Comment by nklayman** [comment]
The `mainProcessFile` just passes the value to `vue-cli-service serve [value]`. I'm not sure how it differs from changing the entry from the pages config tbh. The multiple pages documentation doesn't say anything about changing that, so I'm not sure if updating the documentation is necessary. What would I change?

**Comment by nklayman** [comment]
I think I'll just remove it completely in favor of changing it through `pages.index.entry` in v3.
