### ISSUE TITLE
Spectron Option

### ISSUE THREAD

**Issue by Kaffiend** [nklayman/vue-cli-plugin-electron-builder#128]
Would be nice to have the plugin ask for E2E Testing with Spectron and proceed accordingly.

**Comment by nklayman** [comment]
See the docs on [testing and debugging](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/testingAndDebugging.html). I think that is enough, do you?

**Comment by Kaffiend** [comment]
It good I agree. I was just thinking generating an example from a question on the cli would be really convenient. This whole plugin makes electron super simple to setup and felt testing deserved the same :)

**Comment by Kaffiend** [comment]
🤦‍♂️ Sorry screen rotation mis-click 😄

**Comment by nklayman** [comment]
Added support for jest with 57895c78a2f5da39a26f0ab0ad6dbaad6e950e24. Going to add mocha soon.

**Comment by nklayman** [comment]
When using mocha, I get this error when mocha-webpack runs (but works fine w/out mocha-webpack):
```
 WEBPACK  Failed to compile with 2 error(s)

Error in ./node_modules/@vue/cli-service/bin/vue-cli-service.js

  Module parse failed: Unexpected character '#' (1:0)
  You may need an appropriate loader to handle this file type.
  > #!/usr/bin/env node
  |
  | const semver = require('semver')

Error in ./node_modules/electron-chromedriver/chromedriver.js

  Module parse failed: Unexpected character '#' (1:0)
  You may need an appropriate loader to handle this file type.
  > #!/usr/bin/env node
  |
  | var ChildProcess = require('child_process')
```
Any ideas on how to fix?

**Comment by Kaffiend** [comment]
Sorry been down sick for a few days, i'll take a look at this.

**Comment by jyrula** [comment]
did you manage to look into this issue?

**Comment by nklayman** [comment]
Will be part of next release.

**Comment by AndreiSoroka** [comment]
@nklayman Hi! Any updates?

**Comment by AndreiSoroka** [comment]
https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/testingAndDebugging.html
find, thanks
