### ISSUE TITLE
update error: "net::ERR_FAILED"

### ISSUE THREAD

**Issue by starhu521** [nklayman/vue-cli-plugin-electron-builder#1280]
**Describe the bug**
I create a test project.

When I update my app with control, I got this error:
```
"Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6497)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)" 
```

**To Reproduce**
It's a new test app.
```
  vue create electron_update_test

  vue add electron-builder

  yarn add electron-updater

```
I build target AppImage for linux and publish provider: 'generic' with my local http server.

Then ` autoUpdater.checkForUpdates() `, I got "update-available":
```
{"version":"0.1.1","files":[{"url":"electron_update_test-0.1.1.AppImage","sha512":"d+gxf7ZnmgdaElt6fE0f+sG25jOdCEgBAcslSYjaXZEOiBoD/c3D/agzxcA/Z9X/7Xs0qOeiRTeFB8WJ2IebPQ==","size":77632041,"blockMapSize":82493}],"path":"electron_update_test-0.1.1.AppImage","sha512":"d+gxf7ZnmgdaElt6fE0f+sG25jOdCEgBAcslSYjaXZEOiBoD/c3D/agzxcA/Z9X/7Xs0qOeiRTeFB8WJ2IebPQ==","releaseDate":"2021-03-05T02:51:25.056Z"}
```
Then I call, ` autoUpdater.downloadUpdate() ` , I got an error from ` autoUpdater.on('error') `, the error is :
```
"Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6497)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)"
```

**Expected behavior**
I hope I can update my app.

**Screenshots**
![image](https://user-images.githubusercontent.com/23275495/110061593-ca787d00-7da2-11eb-88a7-726e942d43a1.png)

**Environment (please complete the following information):**
node: v12.16.2
yarn: v1.22.4
electron: 11.3.0
vue-cli-plugin-electron-builder: 2.0.0-rc.6
electron-builder: 22.10.5
electron-updater: 4.3.8
@vue/cli: 4.5.9

**Comment by nklayman** [comment]
How did you create the local update server?

**Comment by starhu521** [comment]
http-server,

**Comment by starhu521** [comment]
> How did you create the local update server?

With http-server, you can search it in github. And it  's express static.  I also test build target nsis for windows, no problems.

**Comment by nklayman** [comment]
Can you post a link to your repo, or create one that demonstrates the error? I need to see your app to debug this.

**Comment by starhu521** [comment]
> Can you post a link to your repo, or create one that demonstrates the error? I need to see your app to debug this.

This's my test repo(https://github.com/starhu521/electron-update-test). It's just created by vue-cli and vue-cli-plugin-electron-builder. Nothing else. And their version is like above.

**Comment by nklayman** [comment]
I tested your app and it worked just fine with `http-server` serving the `dist_electron` dir. Can you run `ls` in the `dist_electron` dir and post the output here?

**Comment by starhu521** [comment]
> I tested your app and it worked just fine with `http-server` serving the `dist_electron` dir. Can you run `ls` in the `dist_electron` dir and post the output here?

Hello, This's the result:
![image](https://user-images.githubusercontent.com/23275495/113649064-5cd0b100-96c0-11eb-9490-5d89d84a0796.png)

**Comment by nklayman** [comment]
Can you try deleting the `node_modules` folder and reinstalling deps? I tried your repo again and it worked just fine.

**Comment by starhu521** [comment]
Thanks. And I build the target to deb for linux, I will close it.
