### ISSUE TITLE
Adding externals works fine in development but not in production after build

### ISSUE THREAD

**Issue by dannielibor** [nklayman/vue-cli-plugin-electron-builder#1282]
**Describe the bug**
I am using puppeteer and I have to add the package to `externals` also in `webpack` config. It is working in dev environment however after building the app to production this error occurs `Error: Cannot find module 'puppeteer'`

**To Reproduce**
```
module.exports = {
  transpileDependencies: [
    'vuetify'
  ],
  pluginOptions: {
    electronBuilder: {
      externals: [
        'electron',
        'puppeteer-core',
        'puppeteer',
        'puppeteer-extra',
        'puppeteer-extra-plugin-stealth'
      ],
      nodeModulesPath: ['../../node_modules', './node_modules'],
      nodeIntegration: true
    }
  },
  configureWebpack: {
    externals: {
      puppeteer: "require('puppeteer')",
      'puppeteer-extra': "require('puppeteer-extra')",
      'puppeteer-extra-plugin-stealth': "require('puppeteer-extra-plugin-stealth')"
    }
  }
}
```

**Expected behavior**
`Puppeteer-extra` will also work after build

**Screenshots**
![image](https://user-images.githubusercontent.com/32063464/110204975-f6822400-7eb0-11eb-8188-d8a9bbb2449c.png)

**Comment by dannielibor** [comment]
@nklayman Let me know if I have to change to my `vue.config` thank you in advance!

**Comment by nklayman** [comment]
Is puppeteer installed as a `dependency` or a `devDependency`? It won't work if you have it installed as a `devDependency`.
