### ISSUE TITLE
vue components are not show in vue devtool stand alone electron app

### ISSUE THREAD

**Issue by mgowtham** [nklayman/vue-cli-plugin-electron-builder#1283]
**Describe the bug**
vue devtools remote debugging not working. app is detected but components are not detected. I have added <script src="http://192.168.29.186:8098"></script> in app head also

**To Reproduce**
in mac 10.15 just try to connect vue devtools remote app with vue app 

**Expected behavior**
all comonents should be rendered
**Screenshots**

**Environment (please complete the following information):**
  mac 10.15 
<img width="807" alt="Screen Shot 2021-03-07 at 7 22 05 PM" src="https://user-images.githubusercontent.com/9431630/110242219-0fefa280-7f7b-11eb-8786-7ad2661c8c17.png">

**Comment by nklayman** [comment]
This is caused by https://github.com/vuejs/vue-devtools/issues/1289. You will need to install version 5 of vue-devtools if you are using Vue 2. Run `npm i -g @vue/devtools@^5.0.0` to install the proper version.
