### ISSUE TITLE
How to handle `contextIsolation` for > electron v12?

### ISSUE THREAD

**Issue by undergroundwires** [nklayman/vue-cli-plugin-electron-builder#1285]
First of all thanks for this awesome project. It was super easy to get going and I've been using it to distribute [privacy.sexy](https://github.com/undergroundwires/privacy.sexy) for a while. I follow your release notes and admire how good they are.

I've migrated from from electron v11.x to v12 today. It sets `contextIsolation` as `false`. I see that if I run the application using `npm run electron:serve` I get:

```
external "events"?7a7e:1 Uncaught ReferenceError: require is not defined
    at eval (external "events"?7a7e:1)
    at Object.events (app.js:4735)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at eval (emitter.js?a6bd:1)
    at Object../node_modules/webpack/hot/emitter.js (chunk-vendors.js:8770)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at eval (dev-server.js?6895:50)
    at Object../node_modules/webpack/hot/dev-server.js (chunk-vendors.js:8759)
```

It is caused by webpack where it evaluates `module.exports = require(\"events\");` (probably for hot reloading).

I wonder how should we handle this in a good way. Setting `webPreferences: { contextIsolation: true, ... }` solves the issue however I'm not sure if it is the security best practice here #742. What would be your recommendation here?

**Comment by nklayman** [comment]
As far as I know, there is no point in enabling contextIsolation if you have nodeIntegration enabled. The whole point of contextIsolation is to make sure web contents can't access data from the preload script, which could expose dangerous native functions. With nodeIntegration enabled, these functions are available regardless, so there is no point in separating the context of the preload script and web contents.

**Comment by undergroundwires** [comment]
Hi nklayman, thanks for your fast response.

It did not work though.

I enabled `nodeIntegration` using `pluginOptions.nodeIntegration` but I could not get it working without without explicitly setting `contextIsolation` to false.

So:

- Use `vue-cli-plugin-electron-builder`
- Set `nodeIntegration` to true using `pluginOptions.nodeIntegration`
- Use > electron v12 (works without any issues in v11)
- Do not explicitly set  `contextIsolation` to false.

I get the webpack error 😢 Setting it explicitly fixes it though.

**Comment by nklayman** [comment]
You will have to explicitly set `contextIsolation` to false for it to work, that's intended. The next release of this plugin will update the template to include that automatically. Electron requires `contextIsolation` to be false for `nodeIntegration` to work.

**Comment by undergroundwires** [comment]
Thank for clearing this out . It was my misunderstanding then, I thought we could keep `contextIsolation` as true and still have the `nodeIntegration`. Thank you a lot for maintaining this and also doing a great job at doing that again.
