### ISSUE TITLE
Can't load fonts in production build, vue-cli@5.0.0-alpha.6

### ISSUE THREAD

**Issue by SnosMe** [nklayman/vue-cli-plugin-electron-builder#1286]
**Describe the bug**

![image](https://user-images.githubusercontent.com/4292308/110758525-49fbc580-8255-11eb-97f5-b4c10e53abf4.png)

**Steps to reproduce the behavior:**
https://github.com/SnosMe/font-loading-bug
https://github.com/SnosMe/font-loading-bug/blob/cccb45e3742bac48217b781ffa61e4168ecd175d/src/App.vue#L22-L24

Notes:
It was mentioned that paths must be relative https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/206#issuecomment-469300709

**Comment by nklayman** [comment]
This is a bug with vue cli v5: https://github.com/vuejs/vue-cli/issues/6346. Downgrading to v4 fixes it.

**Comment by Alecyrus** [comment]
It seems that the maintainers of vue-cli are not going to solve this problem anytime soon, so I offer a temporary solution. Use electron-builder's hidden hook function BeforeBuild to modify all the incorrect paths in the css file.

```javascript
// vue.config.js, pluginOptions.electronBuilder.builderOptions
beforeBuild: "scripts/modifyFontFilepath.js",
```

```javascript
// modifyFontFilepath.js
const path = require("path")
const fs = require("fs")
const replace = require("replace");

exports.default = async function (context) {
  const workDir = path.join(context.appDir, "css")
  const files = fs.readdirSync(workDir);
  replace({
    regex: "app:///fonts",
    replacement: "app://./fonts",
    paths: files.map(val => path.join(workDir, val)),
    recursive: false,
    silent: false,
  })
}

```

**Comment by Ovenoboyo** [comment]
> 

I think the ```return true``` should be inside the exported default function. I am not exactly sure why but placing it outside was causing electron-builder to skip some dependencies from the final build. Quoting the [docs](https://www.electron.build/configuration/configuration.html#configuration) 

> Resolving to false will skip dependencies install or rebuild.

I think returning nothing from the exported function was causing the dependency to be skipped

When modified to this, it worked perfectly

``` js
// modifyFontFilepath.js
const path = require("path")
const fs = require("fs")
const replace = require("replace");

exports.default = async function (context) {
  const workDir = path.join(context.appDir, "css")
  const files = fs.readdirSync(workDir);
  replace({
    regex: "app:///fonts",
    replacement: "app://./fonts",
    paths: files.map(val => path.join(workDir, val)),
    recursive: false,
    silent: false,
  })

  return true
}

```

**Comment by Alecyrus** [comment]
> > 
> 
> I think the `return true` should be inside the exported default function. I am not exactly sure why but placing it outside was causing electron-builder to skip some dependencies from the final build. Quoting the [docs](https://www.electron.build/configuration/configuration.html#configuration)
> 
> > Resolving to false will skip dependencies install or rebuild.
> 
> I think returning nothing from the exported function was causing the dependency to be skipped
> 
> When modified to this, it worked perfectly
> 
> ```js
> // modifyFontFilepath.js
> const path = require("path")
> const fs = require("fs")
> const replace = require("replace");
> 
> exports.default = async function (context) {
>   const workDir = path.join(context.appDir, "css")
>   const files = fs.readdirSync(workDir);
>   replace({
>     regex: "app:///fonts",
>     replacement: "app://./fonts",
>     paths: files.map(val => path.join(workDir, val)),
>     recursive: false,
>     silent: false,
>   })
> 
>   return true
> }
> ```

It's a mistake not on purpose, thanks for indicating this
