### ISSUE TITLE
App protocol and CORS

### ISSUE THREAD

**Issue by d0whc3r** [nklayman/vue-cli-plugin-electron-builder#129]
**Describe the bug**
This is not a serious bug but could break some apps usign external server with CORS

**To Reproduce**

I use an autentication system (jwt) in external server configured with CORS.
In production build, when `createProtocol('app')` is active and `win.loadFile('index.html')` is used I have some problems to correctly authenticate with server.

**Expected behavior**

Authorization header need to be catched and propagated

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: debian 9
 - Node version: 10.x
 - npm version: 6.4.1
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 1.0.0-rc.7
 - other vue plugins used: vue-auth
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**

This could be fixed, without any other collateral bugs replacing `win.loadFile('index.html');`for: `win.loadURL('app://./index.html');` in `background.js`

**Comment by nklayman** [comment]
When I follow your suggestion, `__dirname` gets set to `resources/electron.asar/renderer`, instead of `resources/app.asar`. Do you know why this is?

**Comment by nklayman** [comment]
Because of this issue, I won't be able to change it. For now, you can just use the fix yourself until I find a solution.

**Comment by d0whc3r** [comment]
Using `electron:serve` and `win.loadURL(process.env.WEBPACK_DEV_SERVER_URL as string);` 

`console.log(__dirname);` in App.vue shows `.../resources/electron.asar/renderer` the same as `win.loadURL('app://./index.html');`

**Comment by d0whc3r** [comment]
Also, in a new "hello-world" project totaly empty, `electron:serve` shows `resources/electron.asar/renderer` as `__dirname` but in builded project (AppImage and unpacked) it shows `resources/app.asar`...
Then using `app://` it will work like as `electron:serve`

**Comment by nklayman** [comment]
Good point. However, `__dirname` is not important in the serve command.

Normally, `__dirname` is not used directly, instead `__static` or `process.env.BASE_URL` is used. See the [docs on static assets](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#handling-static-assets) for more info. In development, these  are `project_root/public` and `/`, respectively. In production, however, they are set to `__dirname`. This means that reading/writing to files in the `public` folder would fail in production.

**Comment by d0whc3r** [comment]
I use relative path and writing files is working, you couldn't write inside asar file, then `__dirname` is not needed and not recommended to use.
Instead of __static could be used `import from` and `import()` for dynamic import for webpack

**Comment by nklayman** [comment]
IDK I feel like more issues will arise from weird `__dirname/__filename` behavior then the CORS issue. In addition, it is quite easy to fix manually. Would it be enough to just mention it in the docs?

**Comment by nklayman** [comment]
I got this to work by replacing `__dirname` with `require('electron').remote.app.getAppPath()`.

**Comment by Stanzilla** [comment]
I have the exactly opposite problem `Access to XMLHttpRequest at 'https://data.wago.io/api/check/weakauras?ids=r1lqyX32M,NyJFor1Mm,Hk8U8kanm,NkaTBpcPW,EyWf_B5NM,Vy4Hm5iH-,HkUtqi7QQ,Vyx12GkVZ,VJfmtnrkm,r14U746B7,4k2jlNx2G,6YhvXz76q,bfaraid4,7AtCkO6Gu,IPYzjowfj,GrbGKhzKH,_dSqZsrvg,V15AfQ7ym' from origin 'app://.' has been blocked by CORS policy: Request header field identifier is not allowed by Access-Control-Allow-Headers in preflight response.`
