### ISSUE TITLE
Tray icon disappear when package name contain scope

### ISSUE THREAD

**Issue by Armaldio** [nklayman/vue-cli-plugin-electron-builder#1296]
**Describe the bug**
A weird bug where the tray icon disappear if the package name contains a scope (@x/y)

**To Reproduce**
- Clone https://github.com/Armaldio/vue-cli-plugin-electron-builder-icon-bug
- `npm run electron:serve`
- See a log showing tray values but no tray icon
- Exit
- Change in `package.json` > `name` and remove `@x/`
- `npm run electron:serve`
- Icon appear in tray

**Expected behavior**
The tray should also work when package name is scoped

**Environment (please complete the following information):**
 - terminal output from running `vue info`:
<details>
Environment Info:

  System:
    OS: Linux 5.9 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.4/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.0.3 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.12 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.12 
    @vue/cli-plugin-babel: ~4.5.12 => 4.5.12 
    @vue/cli-plugin-eslint: ~4.5.12 => 4.5.12 
    @vue/cli-plugin-router:  4.5.12 
    @vue/cli-plugin-vuex:  4.5.12 
    @vue/cli-service: ~4.5.12 => 4.5.12 
    @vue/cli-shared-utils:  4.5.12 (4.5.10)
    @vue/component-compiler-utils:  3.2.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^7.7.0 => 7.7.0 
    vue: ^2.6.12 => 2.6.12 
    vue-cli-plugin-electron-builder: ~2.0.0-rc.6 => 2.0.0-rc.6 
    vue-eslint-parser:  7.6.0 
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.9.6 (16.1.2)
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.12 => 2.6.12 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: Not Found
</details>

**Additional context**
Windows and MacOs seems to work fine with scoped name, only Linux prevent showing the icon in the tray

**Comment by nklayman** [comment]
This is a bug with electron, not this plugin. If you add a tray to https://github.com/electron/electron-quick-start and change the name to be scoped, it is missing as well.
