### ISSUE TITLE
Import the .node file in the main process and report an error

### ISSUE THREAD

**Issue by zhouC98** [nklayman/vue-cli-plugin-electron-builder#1302]
**Describe the bug**
`
 error  in ./native/index.node

Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

 @ ./src/background.js 15:0-44 16:12-21
 @ multi ./src/background.js
`

**Screenshots**
![image](https://user-images.githubusercontent.com/50039646/112250479-67d51b80-8c94-11eb-9148-80f416bdcc26.png)
![image](https://user-images.githubusercontent.com/50039646/112250439-55f37880-8c94-11eb-9ad0-067681362815.png)

**Environment (please complete the following information):**
 "electron": "^9.0.0",
"electron-build-env": "^0.2.0",
"vue": "^2.6.11",
"native-ext-loader": "^2.3.0",
"neon-cli": "^0.6.0",
"vue-cli-plugin-electron-builder": "~2.0.0-rc.5",

**Comment by nklayman** [comment]
Can you please share the `.node` file you are using?

**Comment by zhouC98** [comment]
> 您能否共享`.node`您正在使用的文件？
I use the template [Vue-Webpack-Electron-Neon-Quickstart](https://github.com/muchanem/vue-electron-neon-quickstart/blob/main/package.json) and the .node file generated by yarn build.
The generated .node file is used normally in main.js, and error is reported when used in background.js, as shown in the screenshot above.
Environment: 
cargo 1.50.0
Python 2.7
xCode
neon 0.8.0
[neon documentation](https://neon-bindings.com/docs/getting-started)

**Comment by d3x0r** [comment]
This is the same issue I'm having with https://www.npmjs.com/package/sack.vfs.
~2.0.0-rc.6

found this related issue:  https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/610

```
Module parse failed: Unexpected character 'ï¿½' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

 @ ./node_modules/sack.vfs/vfs_module.cjs 27:17-59 47:17-59
 @ ./node_modules/sack.vfs/vfs_module.mjs
 @ ./src/background.js
 @ multi ./src/background.js
```

the background.js just has

```
import {sack} from "sack.vfs";
```

It would be nice if .node files could just be used without any extra work... is this just because it's background and not main?

Also - if the .node had additional .DLLs associated with it, don't suppose those would be automatically included?

**Comment by nklayman** [comment]
The template repository you shared has some other issues with it that will cause an error, but to load the .node file in the main process you should add this to your `vue.config.js`:
```js
// this goes inside of module.exports = {
pluginOptions: {
    electronBuilder: {
      nodeIntegration: true,
      chainWebpackMainProcess(config) {
        config.module
          .rule("node")
          .test(/\.node$/)
          .use("native-ext-loader")
          .loader("native-ext-loader")
          .options(
            process.env.NODE_ENV === "development"
              ? {
                  rewritePath: path.resolve(__dirname, "native"),
                }
              : {}
          )
      },
    },
  }
```

Your existing config only effected the renderer process, so it would work if you are importing the module into `background.js`.
