### ISSUE TITLE
Recompile electron get an error.(node-loader)

### ISSUE THREAD

**Issue by HWWWWWT** [nklayman/vue-cli-plugin-electron-builder#1304]
**Describe the bug**

**To Reproduce**
in vue.config.js
```
pluginOptions: {
    electronBuilder: {
      outputDir: './dist',
      webSecurity: false,
      nodeIntegration: true,
      allowRunningInsecureContent: true,
      mainProcessFile: 'src/Main/background.ts',
      mainProcessWatch: ['src/Main/*.ts', 'src/Main/*/*.ts', 'src/Main/*/*/*.ts'],
      builderOptions: builderOptions,
      chainWebpackMainProcess: config => {
        config.module
        .rule('node')
          .test(/\.node$/)
          .use('node-loader')
          .loader('node-loader')
          .options({ 
            name: '[name].[ext]'
          })
          .end()
        return config
      },
      chainWebpackRendererProcess: config => {
        return config
      }
    }
  }
```

The first compilation can be done.
![image](https://user-images.githubusercontent.com/24352260/112426723-62023780-8d73-11eb-9a5d-a917606e44f9.png)
```
import verifyPlugin from './verify.node';
console.log(verifyPlugin)
export {
    verifyPlugin
}
```
However, when compiling for the second time, an error was reported
![image](https://user-images.githubusercontent.com/24352260/112426828-92e26c80-8d73-11eb-990f-b6fd40f4d317.png)

how can i fix it?

the .node file  in a sperate folder
![image](https://user-images.githubusercontent.com/24352260/112430235-d390b480-8d78-11eb-99cb-aa5e51d30922.png)

**Environment (please complete the following information):**
"electron": "10.4.0",
"vue": "^3.0.5",
"node-loader": "^1.0.2",
"vue-cli-plugin-electron-builder": "~2.0.0-rc.5"

**Comment by nklayman** [comment]
Can you create a repo that demonstrates the error so that I can debug it?

**Comment by JsBlueCat** [comment]
> Can you create a repo that demonstrates the error so that I can debug it?

(https://github.com/JsBlueCat/electron-pure-node-addon.git)[https://github.com/JsBlueCat/electron-pure-node-addon.git]  i have meet with the same error please refer to my project

**Comment by HWWWWWT** [comment]
i had fixed!
step1:  remove `node-loader`,
step2:  move `.node` file to `__static` folder,
step3: use `__non_webpack_require__` like:
```
var nodePath = resolve(PUBLIC_PATH, './node/verify.node')
var verifyPlugin = __non_webpack_require__(nodePath)
```

its work for me
