### ISSUE TITLE
Unable to switch to Main debug console

### ISSUE THREAD

**Issue by holyduke** [nklayman/vue-cli-plugin-electron-builder#1306]
**Describe the bug**
Working with VSCode, I can't use debug console for background.js file
use case: I wanted to see what process.env.WEBPACK_DEV_SERVER_URL on line 27, but I can not switch to Main debug console

When I try to switch to this main debug console, render debug task crashes and falls down.

After this, I am able to switch to debug console, but `process.env.WEBPACK_DEV_SERVER_URL` gives `undefined`

**To Reproduce**
I followed https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#debugging-with-vscode

**Expected behavior**
Main debug console works

**Screenshots**
![jMkjKkvhkb](https://user-images.githubusercontent.com/48070343/112615193-781b0100-8e22-11eb-9d1d-530950f6a72b.gif)

Thanks for help

**Comment by nklayman** [comment]
Switching the console works fine for me, it seems like that would be a VSCode issue anyways. `process.env.WEBPACK_DEV_SERVER_URL` should be undefined, as it doesn't really exist. This plugin sets webpack to overwrite that variable at build time and replace it with the value directly. The code that electron runs won't have that, as it will have been replaced by `http://localhost:8080` or similar.

**Comment by holyduke** [comment]
Thanks. Any hint how to fix this VSCode issue of switching debug console?

**Comment by nklayman** [comment]
I have no idea really. It works fine for me, on Ubuntu with the latest vscode-insiders. You could try disabling all your plugins to see if a plugin is causing the issue. As a workaround, you could set the renderer debugging to output to the integrated terminal by adding `"console": "integratedTerminal"` to the electron:renderer debug config. This should prevent you from having to switch debug console contexts.
