### ISSUE TITLE
Handling Static Assets Bad

### ISSUE THREAD

**Issue by zhentonglee** [nklayman/vue-cli-plugin-electron-builder#1307]
**Describe the bug**
code:
![image](https://user-images.githubusercontent.com/15976432/112622701-5b082180-8e66-11eb-9df0-f10444f79ec5.png)

yarn electron:serve
ok!
![image](https://user-images.githubusercontent.com/15976432/112622849-9276ce00-8e66-11eb-9231-01c869c58108.png)

yarn electron:build
bad!
![image](https://user-images.githubusercontent.com/15976432/112623090-dcf84a80-8e66-11eb-8b0d-5eec3219347d.png)
![image](https://user-images.githubusercontent.com/15976432/112623174-f9948280-8e66-11eb-8a0f-67631af0be6a.png)

**Environment (please complete the following information):**

![image](https://user-images.githubusercontent.com/15976432/112623685-9d7e2e00-8e67-11eb-956a-dc13ce2decb7.png)

win 10

**Comment by nklayman** [comment]
In your `background.js`, add `enableRemoteModule: true` under `webPreferences` in the `new BrowserWindow` call:
```diff
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      // Use pluginOptions.nodeIntegration, leave this alone
      // See nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration for more info
      nodeIntegration: process.env.ELECTRON_NODE_INTEGRATION,
+     enableRemoteModule: true
    }
  })
```

This will be fixed in the next release, but you'll have to use this workaround for now.
