### ISSUE TITLE
Electron 12 Upgrade

### ISSUE THREAD

**Issue by MattCCC** [nklayman/vue-cli-plugin-electron-builder#1308]
Hi guys, firstly thank you for a great plugin! It works like a charm! Electron 12 is out since beginning of March. Are there any plans to perform the upgrade from 11?

**Comment by nklayman** [comment]
Yes, I just need to figure out a few things regarding `__dirname`, see #1301 for more details. As soon as that is fixed I will update the prompts to include electron 12.
