### ISSUE TITLE
Cannot find module 'clipboard'

### ISSUE THREAD

**Issue by HWWWWWT** [nklayman/vue-cli-plugin-electron-builder#1313]
**To Reproduce**
step1: `import { clipboard } from "electron";`   import clipboard on render process
step2: use `electron-build` to build app.

then show the error
![image](https://user-images.githubusercontent.com/24352260/112784640-c596a880-9084-11eb-8da8-d37b99b008c7.png)

the `clipboard` works in development.

i try to add clipboard module in externals array, but still not working.
in vue.config.js
![image](https://user-images.githubusercontent.com/24352260/112784830-29b96c80-9085-11eb-9a0e-150003887efd.png)

**Environment (please complete the following information):**
"electron": "10.4.0",
"vue": "^3.0.5",
"node-loader": "^1.0.2",
"vue-cli-plugin-electron-builder": "~2.0.0-rc.5"

**Comment by d-loki** [comment]
Hi @HWWWWWT, I'm encountering the same error, how did you solve the problem?
