### ISSUE TITLE
not install vue-devtools extension in vue 3

### ISSUE THREAD

**Issue by amirhossein95b** [nklayman/vue-cli-plugin-electron-builder#1315]
No error is displayed

**Comment by shoeyn** [comment]
Vue 3 uses different devtools to Vue 2.
Change the function which installs the devtools.
```
app.on('ready', async () => {
  if (isDevelopment && !process.env.IS_TEST) {
    // Install Vue Devtools
    try {
-      await installExtension(VUEJS_DEVTOOLS) // Change this line
+      await installExtension('ljjemllljcmogpfapbkkighbhhppjdbg')
    } catch (e) {
      console.error('Vue Devtools failed to install:', e.toString())
    }
  }
  createWindow()
})
```

The id is taken from the [chrome web store](https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg)

**Comment by amirhossein95b** [comment]
> Vue 3 uses different devtools to Vue 2.
> Change the function which installs the devtools.
> 
> ```
> app.on('ready', async () => {
>   if (isDevelopment && !process.env.IS_TEST) {
>     // Install Vue Devtools
>     try {
> -      await installExtension(VUEJS_DEVTOOLS) // Change this line
> +      await installExtension('ljjemllljcmogpfapbkkighbhhppjdbg')
>     } catch (e) {
>       console.error('Vue Devtools failed to install:', e.toString())
>     }
>   }
>   createWindow()
> })
> ```
> 
> The id is taken from the [chrome web store](https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg)

not worked

**Comment by shoeyn** [comment]
It's the code I'm running in my applications, so it's more likely something wrong in your application.
What version of this plugin are you running?
Is there a public repository of your application?

**Comment by nklayman** [comment]
This plugin installs the default version of Vue Devtools, and will continue to do so. If you want to use the beta version of Vue Devtools, @shoeyn's solution above should work fine. If it doesn't, please post a link to a repo that fails so that I can debug it.
