### ISSUE TITLE
Question: How to include extra files in the app.asar.

### ISSUE THREAD

**Issue by blakjak44** [nklayman/vue-cli-plugin-electron-builder#1319]
I am trying to include a public key file (`key.pub`) that is located in my project root in the final `app.asar`. I have tried every possible `files: []` option to include this file but have been unable to make it work. It looks like the problem is related to the step that creates the two package.json structure where the `key.pub` file is not copied into `dist_electron/bundled`.

If I build the application normally, then manually copy the files into `dist_electron/bundled` and then run a 2nd time with the `--skipBundle` flag, then everything works as expected.

What is the correct config to copy files into `dist_electron/bundled` at build time?

**Comment by nklayman** [comment]
An easy way would be to put it in the `public` folder. Any files there are copied to the `app.asar` when building. You can then use the `__static` var (which is injected at build time automatically). See the [docs on static assets](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#handling-static-assets) for more details.
