### ISSUE TITLE
cannot open addon.node

### ISSUE THREAD

**Issue by eyesmarty** [nklayman/vue-cli-plugin-electron-builder#1322]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 
 - terminal output from running `vue info`:

**Additional context**

**Comment by nklayman** [comment]
Please fill out the issue template next time.
