### ISSUE TITLE
cannot open addon.node. invalid package electron.asar

### ISSUE THREAD

**Issue by eyesmarty** [nklayman/vue-cli-plugin-electron-builder#1323]
**Describe the bug**
 I am trying to integrate c++ addon fixed a lot of issues finally got stuck in one error
 **error**
 **Error**: Cannot open /Users/userName/Electron gyp/electron-final-testing-with-addon/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/addon.node: 
 **Error**: Invalid package /Users/userName/Electron gyp/electron-final-testing-with-addon/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar

**c++ import**
check worker.js for import and vue.config.js for .node loader and c++ code is in addon.cc
**To Reproduce**
npm install
node-gyp configure
node-gyp build
./node_modules/.bin/electron-rebuild
npm run electron:serve #to run locally
npm run electron:build #to generate build file in dost_electron

**Expected behavior**
it should show result in console
console.log('This should be eight:', addon.add(3, 5));
**Attachment**
Project has been attached with issue kindly follow steps mentioned in ** to reproduce** section to run project
[Archive.zip](https://github.com/nklayman/vue-cli-plugin-electron-builder/files/6276724/Archive.zip)
@nklayman   my project is about to be launched but is being delayed due to this issue. kindly take out some time to look into my issue as it might help me a lot looking forward for your response

**Comment by filzahamjad** [comment]
facing the same issue?

**Comment by shoaibkhan7871** [comment]
any solution yet

**Comment by UsmanGul** [comment]
Hy wa  Allah...

**Comment by shoaibkhan7871** [comment]
sta dimag kar naki

**Comment by Mohiz20** [comment]
if anyone solves this issue kindly upload fixed project 
it will help so much 
@nklayman thanks in advance

**Comment by UsmanGul** [comment]
> sta dimag kar naki

tool dimagh kar na kai...

**Comment by hameed-fu** [comment]
I have tried and tried to solve the issue but i am failed. I anyone can solve this issue kindly please upload fixed project.
Thank you .

**Comment by Kamran95** [comment]
kind reply if someone comes with appropriate solution.

**Comment by UsmanGul** [comment]
> kindly reply if someone comes up with appropriate solution.

kindly come to tech room...

**Comment by muhammadaqibawaan** [comment]
> > kindly reply if someone comes up with appropriate solution.
> 
> kindly come to tech room...

yes

**Comment by muhammadaqibawaan** [comment]
> > > kindly reply if someone comes up with appropriate solution.
> > 
> > 
> > kindly come to tech room...

**Comment by shoaibkhan7871** [comment]
> > > kindly reply if someone comes up with appropriate solution.
> > 
> > 
> > kindly come to tech room...
> 
> yes

yes

**Comment by muhammadaqibawaan** [comment]
> > > > kindly reply if someone comes up with appropriate solution.
> > > 
> > > 
> > > kindly come to tech room...

yes

**Comment by eyesmarty** [comment]
if import is changed to 
const addon = require('node-loader!./addon.node');
console.log('This should be eight:', addon.add(3, 5));
error changes to
 in ./addon.node

Syntax Error: TypeError: this.getOptions is not a function


 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./worker.js 1:12-47

**Comment by JsBlueCat** [comment]
> if import is changed to
> const addon = require('node-loader!./addon.node');
> console.log('This should be eight:', addon.add(3, 5));
> error changes to
> in ./addon.node
> 
> Syntax Error: TypeError: this.getOptions is not a function
> 
> @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./worker.js 1:12-47

this seems to be a path resolve by webpackroce. you tell the web pack to process the file by node-loader , while it is hanlde by web. this seem the problem, we need to ped it in native webpack, so the webpack exclude it in runtime. i check it in webpack document, i find if pass it with extern,may be it help.

**Comment by nklayman** [comment]
Here's what you need to do to make it work:
1. Install the `nan` npm package (to fix the addon build)
2. Add `enableRemoteModule: true` after line 23 in `background.js` (not related to the addon but causes another error)
3. Set your `vue.config.js` to:
```js
const path = require('path')

module.exports = {
  chainWebpack: (config) => {
    // GraphQL Loader
    config.module
      .rule('node')
      .test(/\.node$/)
      .use('native-ext-loader')
      .loader('native-ext-loader')
      .options(
        process.env.NODE_ENV === 'development'
          ? {
              rewritePath: path.resolve(__dirname, 'build/Release')
            }
          : {}
      )
      .end()
  },
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true
    }
  }
}
```

You will still get an error due to context awareness in the native module, but that's not related to this plugin. Also, this will cause an error if you try to serve in production mode or build in development mode, as the `vue.config.js` uses NODE_ENV to determine if it's build or serve.
