### ISSUE TITLE
Webpack 5 support?

### ISSUE THREAD

**Issue by lanly-dev** [nklayman/vue-cli-plugin-electron-builder#1326]
**Describe the bug**
If I use stylus-loader@5 in my project, it gives out the error  `Syntax Error: TypeError: this.getOptions is not a function`. From what I found, `https://github.com/webpack-contrib/stylus-loader/issues/307` stylus loader requires webpack@5 so I install webpack@5, and another error shows up:
```
Error: Rule can only have one resource source (provided resource and test + include + exclude) in {
  "exclude": [
    null
  ],
  "use": [...]
}
```
So I'm not sure if this error relates to this plugin or not? since I saw the dependencies of it is webpack@4.
or perhaps I am missing some sort of config?

**To Reproduce**
Using *stylus-loader@5* in the project

**Expected behavior**
No error during run/build

**Environment (please complete the following information):**
Just want to update my project `https://github.com/lanly-dev/template-electron-vue-ts`

Thank you!

**Comment by ferm10n** [comment]
I believe this is related, after experiencing the same issue myself with sass-loader@11.0.1
I think the issue is caused by versions 4 and 5 of webpack being installed
https://github.com/vuejs/vue-cli/issues/5986

**Comment by nklayman** [comment]
Webpack 5 support will be coming with v3 of this plugin, as it would require breaking changes to implement. I hope to have an alpha out sometime in the next week or so.

**Comment by ferm10n** [comment]
That's great news!
It'd be nice to leave this issue open until that alpha is released so we could know when to upgrade.
I know I can set a notification setting for project releases, but this way would allow for a better context trail.

**Comment by lanly-dev** [comment]
Thank you for the reply, feeling excited about the update!

**Comment by lanly-dev** [comment]
Is there any update on this? or the v3-alpha release .etc?

**Comment by nklayman** [comment]
Sorry for the delays, was quite busy over the summer. I just started college so I'll be busy for the next little while, but I hope to have time for this sometime within the next month.

**Comment by AndreiSoroka** [comment]
Hi!

> It'd be nice to leave this issue open until that alpha is released so we could know when to upgrade.

Maybe we will leave the issue open?)

**Comment by lanly-dev** [comment]
Look like I accidentally press the wrong key somehow. Didn't meant to. Reopening this again!

**Comment by Stanzilla** [comment]
Instead of webpack5 maybe use esbuild instead?

**Comment by AndreiSoroka** [comment]
@Stanzilla vue-cli is using webpack

**Comment by Stanzilla** [comment]
> vue-cli

Hm yeah but there is https://www.npmjs.com/package/vue-cli-plugin-esbuild

**Comment by AndreiSoroka** [comment]
> > vue-cli
> 
> Hm yeah but there is https://www.npmjs.com/package/vue-cli-plugin-esbuild

I think it's a little early to make this decision
![image](https://user-images.githubusercontent.com/6079139/132924483-753019ac-a8e8-40b1-a941-f32e062fef31.png)

**Comment by Stanzilla** [comment]
> > > vue-cli
> > 
> > 
> > Hm yeah but there is [npmjs.com/package/vue-cli-plugin-esbuild](https://www.npmjs.com/package/vue-cli-plugin-esbuild)
> 
> I think it's a little early to make this decision
> ![image](https://user-images.githubusercontent.com/6079139/132924483-753019ac-a8e8-40b1-a941-f32e062fef31.png)

For this plugin for sure, for the idea in general, I'd say esbuild is pretty mature by now. Not sure how much work it would be to include support for it in vue-cli-plugin-electron-builder though.

Maybe the whole project should switch over to Vite?

**Comment by lanly-dev** [comment]
Vite definitely a interesting option. Look like esbuild and Vite can be faster.

**Comment by AndreiSoroka** [comment]
P.s. I don't want to face potential problems. The build speed is not critical for me.

**Comment by metal-gabe** [comment]
> Maybe the whole project should switch over to Vite?

Just want to point out/comment that switching this whole project over to Vite and/or esbuild seems like a bad idea from the perspective that I imagine it would break a lot of usages out there. If this Vite and esbuild were to be used, I would recommend creating an entirely new package.

**Comment by nklayman** [comment]
Sorry for the delayed response, had to take a break from open source to focus on school.

I'm gonna make a v3 of this plugin that updates all the dependencies, including vue cli 5/webpack 5. However, that'll be the last version of this plugin, as Vite is officially recommended over Vue CLI projects. If I have time, I'm going to make some sort of electron tool for Vite, but I don't know what that would look like right now. In the meantime, keep an eye on the releases page over the next week for a v3 alpha.

**Comment by nklayman** [comment]
V3 alpha is here with webpack v5/Vue CLI v5 support: https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v3.0.0-alpha.0
