### ISSUE TITLE
Created boilerplate app. Then after build and open it shows "Cannot user import statement outside a module"

### ISSUE THREAD

**Issue by ianoble** [nklayman/vue-cli-plugin-electron-builder#1335]
Only modifications I made was to add Description and Author to package.json and add vue.config.js:

`module.exports = {
    pluginOptions: {
        electronBuilder: {
            builderOptions: {
                asar: true,
                appId: 'com.electron.vue_electron_dist',
                productName: 'TestApplication',
                win: {
                    target: [
                        'nsis'
                    ]
                },
                mac: {
                    category: 'public.app-category.developer-tools'
                }
            }
        }
    }
}`

![image](https://user-images.githubusercontent.com/7987064/115592114-b53eab80-a287-11eb-8168-4e574e685434.png)

**Comment by nklayman** [comment]
Please share a repo that demonstrates the error. This isn't enough information for me to debug it.
