### ISSUE TITLE
may virtualModules not work

### ISSUE THREAD

**Issue by godtoy** [nklayman/vue-cli-plugin-electron-builder#1346]
**Describe the bug**
im using `https://github.com/herberttn/bytenode-webpack-plugin` this guy's lib to encrypt my renderer codes, but it said virtaulmodules not found

![image](https://user-images.githubusercontent.com/13638996/116638988-02411280-a957-11eb-87b1-3b374d290045.png)

but you can see here, this virtualmodules have been defained
![image](https://user-images.githubusercontent.com/13638996/116639029-14bb4c00-a957-11eb-8902-220c4a4fff4a.png)

this error only invoke on renderder process building, it worked on main process

**Comment by nklayman** [comment]
Please create a repo that demonstrates the error. This isn't enough information for me to debug your problem.

**Comment by godtoy** [comment]
> Please create a repo that demonstrates the error. This isn't enough information for me to debug your problem.

thank you for your reply, this repo is ready please see here `https://github.com/godtoy/vue-cli-electron-bytenode-issue-6451`

**Comment by nklayman** [comment]
The error is coming from the vue CLI renderer build, which this plugin doesn't really change in any meaningful way. This is probably an issue with the loader you are using. I'm not sure how to fix it as I've never used bytenode before, and I don't think the issue is caused by this plugin.
