### ISSUE TITLE
Default route ('/') is not loaded by at startup when built

### ISSUE THREAD

**Issue by robodude** [nklayman/vue-cli-plugin-electron-builder#135]
**Describe the bug**
When loading an installed electron app that has vue router installed, the default route is not loaded.

**To Reproduce**

1. `vue create my-app`
2. Add Vue Router to application during setup, history mode off
3. `cd my-app` (change into directory)
4. `vue add electron-builder`
5. `npm run electron:build`
6. Navigate to `dist_electron` folder in your OS and install
7. Run installed application

**Expected behavior**
I would expect the "Home" route to be loaded when the application is loaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/1719221/48784400-76abfd80-ec97-11e8-87b0-0b120c1ad201.png)

**Environment (please complete the following information):**
 - OS and version: Windows 10
 - Node version: 8.11.4
 - npm version: 6.4.1
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 1.0.0-rc.8
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**
Clicking on the `Home` link in the application works as expected and routing is otherwise working except on initial load.

**Comment by robodude** [comment]
I read the docs: https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#blank-screen-on-builds-but-works-fine-on-serve

Although it would be great if recommended fix was added by default when this plugin is loaded and vue router is detected ^_^

**Comment by nklayman** [comment]
Since it would be difficult to add this automatically, I instead log a warning message when this plugin is installed, if the project is also using vue-router. (39125f4bf0d483157ce79a300903b88fe7db3965)
