### ISSUE TITLE
How do I execute a script in node_modules when building the app for prodution build  ?

### ISSUE THREAD

**Issue by mokchend** [nklayman/vue-cli-plugin-electron-builder#1355]
In a development mode, calling a program in node_module works without any issue. However, when building the application (in production mode) as my node_module are package in ASAR file, the refered program cannot be be found and throw "Error: spawn ENOENT". I cannot find in the documentation how i can achieve this.

The below workaround works for, but i'm looking for a cleaner solution
in vue.config.js
```
pluginOptions: {
    electronBuilder: {
      builderOptions: {
        extraResources: ['mydemosfdx.cmd','./node_modules/sfdx-cli']
      },
      asar:true
    }
  }
```

in background.js
```
var child = require('child_process').execFile;
var executablePath = `${processResourcePath}/node_modules/sfdx-cli/bin/run.cmd`;
console.dir(executablePath)
var parameters = ["-v"];
child(executablePath, parameters, function(err, data) {
     console.log(err)
     console.log(data.toString());
});
```

A cleaner solution would to run the script from within an asar file instead of doing thoses extra steps.
But I cannot find a proper way to achieve this.

**Comment by nklayman** [comment]
The workaround you posted is about as clean as it gets for this, unfortunately. Since the path has to be different in build vs dev, there isn't a super pretty solution for this afaik.
