### ISSUE TITLE
How to keep vue-cli-plugin-electron-builder synchronized with electron-builder?

### ISSUE THREAD

**Issue by sujiewen** [nklayman/vue-cli-plugin-electron-builder#1357]
There is a problem with electron 11 using the .node inventory. It needs to be upgraded to electron 12.0.5 and the latest version of electron-builder needs to be updated. What should I do?

-----------------------------------------------------------------------------------------------------------------------------
> electron-builder install-app-deps

  • electron-builder  version=22.10.5
  • cannot check updates  error=TypeError: update_notifier_1.default is not a function
  • rebuilding native dependencies  dependencies=sharp@0.28.1 platform=darwin arch=x64
  • install prebuilt binary  name=sharp version=0.28.1 platform=darwin arch=x64 napi= 
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN html-webpack-plugin@5.3.1 requires a peer of webpack@^5.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN script-ext-html-webpack-plugin@2.1.5 requires a peer of html-webpack-plugin@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by PeterBurner** [comment]
seems related to this: https://github.com/electron-userland/electron-builder/issues/5861
