### ISSUE TITLE
testWithSpectron timeout

### ISSUE THREAD

**Issue by Digitaalne** [nklayman/vue-cli-plugin-electron-builder#1360]
**Describe the bug**
If testWithSpectron is called then test would not go any further and  test timeouts. Tried it with Mocha ja Jest with template tests
([Mocha](https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/master/generator/templates/tests-mocha/tests/unit/electron.spec.js), [Jest](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/testingAndDebugging.html#main-process-background-file)). electron:serve works.

**To Reproduce**
npm run test:unit

**Expected behavior**
Test will continue with spectron

**Screenshots**
![image](https://user-images.githubusercontent.com/9251664/117535535-e7c60380-affe-11eb-81fa-feb9b3fd9c69.png)
![image](https://user-images.githubusercontent.com/9251664/117535564-0926ef80-afff-11eb-9ed6-187f3a2450d7.png)

**Environment (please complete the following information):**
 - (if possible) link to your repo:  https://github.com/Digitaalne/vue-stock/blob/35-tests/vue-electron-app/tests/unit/example.spec.js
 - terminal output from running `vue info`:
 System:
    OS: Windows 10 10.0.18363
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 90.0.4430.93
    Edge: Spartan (44.18362.1474.0)
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.0.3
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.11
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.11
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.11
    @vue/cli-plugin-e2e-webdriverio: ~4.5.0 => 4.5.11
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.11
    @vue/cli-plugin-router: ~4.5.0 => 4.5.11
    @vue/cli-plugin-typescript: ~4.5.0 => 4.5.11
    @vue/cli-plugin-unit-jest: ^4.5.13 => 4.5.13
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.11
    @vue/cli-service: ~4.5.0 => 4.5.11
    @vue/cli-shared-utils:  4.5.11 (4.5.13)
    @vue/component-compiler-utils:  3.2.0
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0
    @vue/eslint-config-typescript: ^5.0.2 => 5.1.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/test-utils: ^1.0.3 => 1.2.0
    @vue/web-component-wrapper:  1.3.0
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    highcharts-vue: ^1.3.5 => 1.3.5
    jest-serializer-vue:  2.0.2
    typescript: ~3.9.3 => 3.9.9 (4.2.3)
    vue: ^2.6.11 => 2.6.12
    vue-cli-plugin-electron-builder: ~2.0.0-rc.6 => 2.0.0-rc.6
    vue-debounce: ^2.6.0 => 2.6.0
    vue-eslint-parser:  7.6.0
    vue-github-button:  1.3.0
    vue-github-buttons:  3.1.0
    vue-jest:  3.0.7
    vue-loader:  15.9.6 (16.1.2)
    vue-material: ^1.0.0-beta-15 => 1.0.0-beta-15
    vue-notification: ^1.3.20 => 1.3.20
    vue-router: ^3.2.0 => 3.5.1
    vue-style-loader:  4.1.3
    vue-template-compiler: ^2.6.11 => 2.6.12
    vue-template-es2015-compiler:  1.9.1
    vue-toc:  0.0.1
    vuex: ^3.4.0 => 3.6.2
  npmGlobalPackages:
    @vue/cli: Not Found

**Comment by nklayman** [comment]
It fails in the test because the tests run with `NODE_ENV` set to `production`. If you run electron:serve in productionmode (`yarn electron:serve --mode production`), it fails as well. Either fix your app so it works in production mode, or run the tests in dev mode (`testWithSpectron(spectron, { forceDev: true })`).
