### ISSUE TITLE
How to select the lower of electron version?

### ISSUE THREAD

**Issue by arnozeng** [nklayman/vue-cli-plugin-electron-builder#1364]
**Describe the bug**

![image](https://user-images.githubusercontent.com/64408767/117599104-c2aacf80-b17b-11eb-8271-def38b6d12d2.png)

i can't select the lower version of electron, when input the command 'vue add electron-builder'.  
and just can choose the heighter of electron version for the prompt of windows .  because i want to use node-sqlite3, but it need to dependent electron version, and the electron version shuld less than 8.x

how to fix this problem?

**Comment by klren0312** [comment]
You can try to change the `package.json` after this init

**Comment by nklayman** [comment]
Yeah, the only way to use a lower electron version is to change it in `package.json`. This plugin only supports the latest 3 versions of electron though, so you may run into some errors.
