### ISSUE TITLE
Hot-Reload not working in background.ts

### ISSUE THREAD

**Issue by MeikelLP** [nklayman/vue-cli-plugin-electron-builder#137]
**Describe the bug**
When doing change to the `background.ts` file a hot reload gets triggered and throws a JSON.parse error. The electron app "crashes" and restarts itself. Then everything is fine but this happens on every change.

This may be ok because other cases I know handle this with a fresh restart like it does anyway without the hot-reload json parse stuff.

**To Reproduce**
* Use vue-cli to create a basic vue typescript app
* Convert it to an electron app via `vue add electron-builder`

**Expected behavior**
No error. Can work fluently like used to in a vue app.

**Screenshots**
![skizze 44](https://user-images.githubusercontent.com/11669846/48870607-c8609f00-ede1-11e8-941b-3667912ebc92.png)

**Environment (please complete the following information):**
 - OS and version: Windows 10 64 Bit
 - Node version: 10.9.0
 - npm version: 6.2.0
 - yarn version (if used): -
 - vue-cli-plugin-electron-builder version: ^1.0.0-rc.8
 - other vue plugins used: none
 - custom config for vcp-electron-builder: none
 - (if possible) link to your repo: -

**Comment by nklayman** [comment]
Is this with electron v2 or v3?

**Comment by MeikelLP** [comment]
V3

**Comment by Desuuuu** [comment]
I was unable to reproduce the issue with this setup:

* OS and version: Windows 10 x64
* Node version: 8.12.0
* npm version: 6.4.1
* vue-cli-plugin-electron-builder version: 1.0.0-rc.8
* Electron version: 3.0.10

I tested using the standard Vue CLI application with these features:

```
? Please pick a preset: Manually select features
? Check the features needed for your project: Babel, TS
? Use class-style component syntax? Yes
? Use Babel alongside TypeScript for auto-detected polyfills? Yes
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? No
```

Can you post the content of your `background.ts` when this happens?

PS: Technically, this is not a _hot_ reload 😄

**Comment by Desuuuu** [comment]
It reloads fine with my setup. Maybe it affects Node v10 but not v8?

**Comment by nklayman** [comment]
@MeikelLP can you try with node 8, and @Desuuuu can you try with node 10? Thanks!

**Comment by nklayman** [comment]
It works fine with node 10/11 on Linux. I can't test windows now, so it may be a little while before I am able to resolve this.

**Comment by nklayman** [comment]
I'm thinking this is an issue with node as json.parse is not called anywhere in the index.js, plus the error message said the error occurs in child_process.js. that would explain why it works with node 8 but not 10.

**Comment by MeikelLP** [comment]
I can confirm this is a bug which exists in 10. No issues in 8 whatsoever. 11 Not even working at all.

**Comment by nklayman** [comment]
Make sure you are running the latest electron with node 11, see [here](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#electron-not-opening-on-node-v11) for more info. Try that with node 10 as well and see if the issue persists.

**Comment by MeikelLP** [comment]
I ran 3.0.10 but node 11 is not my target. I will go with node 8. Maybe I'll try 9.

**Comment by nklayman** [comment]
@MeikelLP Is there any chance the issue is related to your system only? Could you try it in a clean environment, maybe via docker or hyper-v? No one else has reported this issue, and @Desuuuu says it works fine.

**Comment by MeikelLP** [comment]
@nklayman For me the workaround is fine. IMO you can close this issue.

**Comment by nklayman** [comment]
Alright, thanks!
