### ISSUE TITLE
linux .wasm 

### ISSUE THREAD

**Issue by wyzj** [nklayman/vue-cli-plugin-electron-builder#1377]
![image](https://user-images.githubusercontent.com/32730019/118463779-beaa1f00-b732-11eb-9f1f-cf7291bb88cc.png)

![image](https://user-images.githubusercontent.com/32730019/118463861-d2558580-b732-11eb-8408-21af92081280.png)
![image](https://user-images.githubusercontent.com/32730019/118584962-91a94b00-b7ca-11eb-9243-724844de0cfb.png)
In win environment, the compile run and package run are all normal, but in Linux, the compile run and package run can't run, and sql.js can't run. There are related wasm files in the dependency, which can't be found
 There is no file corresponding to wasm in Linux after booting under Linux and win environment

**Comment by nklayman** [comment]
I can't debug this with only the information you provided. Please share a repo that demonstrates the error so I can debug this.

**Comment by wyzj** [comment]
It works on windows platform, but doesn't work on linux system; i expect the problem caused by "sql.js" the link ; [https://github.com/wyzj/demo](url)

**Comment by nklayman** [comment]
sql.js isn't designed to work in electron. The official website says it is better to use a native sqlite binding:
> sql.js can be used like any traditional JavaScript library. If you are building a native application in JavaScript (using Electron for instance), or are working in node.js, you will likely prefer to use a native binding of SQLite to JavaScript

You should use [sqlite3](https://www.npmjs.com/package/sqlite3) instead, which won't give you that error.
