### ISSUE TITLE
Is this plugin not support vuex?

### ISSUE THREAD

**Issue by slime7** [nklayman/vue-cli-plugin-electron-builder#138]
**Describe the bug**
state can not update. i commit a mutation in background.js to push an object to array state, but state not changed.

**Environment (please complete the following information):**
 - OS and version: win10 64bit 1803
 - node version: 8.11.2
 - npm version: 6.4.1
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 1.0.0-rc.8
 - electron version: 2.0.13
 - other vue plugins used: babel, eslint
 - (if possible) link to your repo: https://github.com/slime7/kanmand/tree/vuex

**Comment by nklayman** [comment]
Since the `background.js` runs in a separate process, it doesn't have access to anything in your Vue app. To share data between the two and communicate, you will have to use [ipc channels](https://electronjs.org/docs/api/ipc-main).
