### ISSUE TITLE
iohook installation error : iohook .node is not a valid win32 application

### ISSUE THREAD

**Issue by Kamran95** [nklayman/vue-cli-plugin-electron-builder#1382]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 
 - terminal output from running `vue info`:

**Additional context**

**Comment by nklayman** [comment]
Please fill out the template. I can't help you without that information.
