### ISSUE TITLE
Unexpected token 'export' installVueDevtools - bytenode

### ISSUE THREAD

**Issue by welcome14** [nklayman/vue-cli-plugin-electron-builder#1384]
Hi,
I have this issue, 

> App threw an error during load
> C:\Project\node_modules\vue-cli-plugin-electron-builder\lib\index.js:1
> export { default as installVueDevtools } from './installVueDevtools'
> ^^^^^^
> SyntaxError: Unexpected token 'export'
>     at wrapSafe (internal/modules/cjs/loader.js:986:16)
>     at Module._compile (internal/modules/cjs/loader.js:1034:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
>     at Module.load (internal/modules/cjs/loader.js:935:32)
>     at Module._load (internal/modules/cjs/loader.js:776:14)
>     at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
>     at Module.require (internal/modules/cjs/loader.js:959:19)
>     at require (webpack:///./node_modules/bytenode/dist/index.js?:240:27)
>     at Object.<anonymous> (evalmachine.<anonymous>:1:191)
>     at Object.module_1.default._extensions.<computed> (webpack:///./node_modules/bytenode/dist/index.js?:258:28)
>     

this is the entry file ..background.js

> 
> 'use strict';
> 
> const bytenode = require('bytenode');
> const fs = require('fs');
> const v8 = require('v8');
> const path = require('path');
> v8.setFlagsFromString('--no-lazy');
> 
> if (!fs.existsSync(path.join( __static, 'background-main.jsc'))) {
>     bytenode.compileFile('src/background-main.js', 'public/background-main.jsc');
> }
> 
> __non_webpack_require__(path.join( __static, 'background-main.jsc'));
> 

this is a piece of the code from the file 'background-main.js' ..

> 'use strict'
> const bytenode = require('bytenode');
> const { app, protocol, BrowserWindow } = require('electron');
> import {createProtocol } from 'vue-cli-plugin-electron-builder/lib';
> const isDevelopment = process.env.NODE_ENV !== 'production'
> 
> protocol.registerSchemesAsPrivileged([
>     {scheme: 'app', privileges: {secure: true, standard: true}}
> ])
> let win = null;
> async function createWindow() {
>     win = new BrowserWindow({
>         width: 800,
>         height: 600,
>         webPreferences: {
>             devTools: process.env.NODE_ENV == 'production' ? false : true,
>             nodeIntegration: true,//process.env.ELECTRON_NODE_INTEGRATION,
>             contextIsolation: !process.env.ELECTRON_NODE_INTEGRATION,
>             enableRemoteModule: true
>         }
>     })
>     if (process.env.WEBPACK_DEV_SERVER_URL) {
>         await win.loadURL(process.env.WEBPACK_DEV_SERVER_URL)
>     } else {
>         createProtocol('app')
>         win.loadURL('app://./index.html')
>     }
>     win.maximize()
> 
> }

maybe the vue-cli-plugin-electron-builder package is not compatible with bytenode? how i resolve ?

**Comment by nklayman** [comment]
It seems like bytenode isn't compatible with import/export statements. You'll have to make sure to avoid using that in your background file. For me to be able to help you more, I'll need a repo that demonstrates the error.

**Comment by welcome14** [comment]
I have add you ti my repository ..Il 22 mag 2021 20:12, Noah Klayman ***@***.***> ha scritto:
It seems like bytenode isn't compatible with import/export statements. You'll have to make sure to avoid using that in your background file. For me to be able to help you more, I'll need a repo that demonstrates the error.
