### ISSUE TITLE
Unable to resolve fluent-ffmpeg

### ISSUE THREAD

**Issue by AlexSHoffman** [nklayman/vue-cli-plugin-electron-builder#139]
**Describe the bug**
Using this boilerplate, you cannot install `fluent-ffmpeg` npm module

**To Reproduce**
- `yarn add fluent-ffmpeg`
- `yarn serve:electron`

**Screenshots**
![image](https://user-images.githubusercontent.com/13764106/48958671-c6c5e100-ef71-11e8-9e92-4a034e2337b3.png)

**Environment:**
 - OS and version: Win10x64
 - vue-cli-plugin-electron-builder version : v1.0.0-rc.7

**Additional context**

I think it's a problem with Webpack configuration.

Proposed solution can be found in [this comment](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/573#issuecomment-305408048)

**Comment by nklayman** [comment]
You can apply the fix yourself by modifying the webpack config. See [the docs](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#webpack-configuration) for more details.

**Comment by AlexSHoffman** [comment]
@nklayman could you please elaborate on how to do this? 

I've created `vue.config.js` in the same directory as the `package.json` but I'm having troubles applying the code form the linked comment into that file

**Comment by AlexSHoffman** [comment]
I've created `vue.config.js` in the same directory as the `package.json` and added the following code:

Does that look correct?
```

module.exports = {
  pluginOptions: {
    electronBuilder: {
      chainWebpackRendererProcess: config => {
        config.plugin('define').tap(args => {
          args[0]['process.env.FLUENTFFMPEG_COV'] = false
          return args
        })
      },
    }
  }
}
```

**Comment by nklayman** [comment]
That looks right. It matches the suggested solution in the other issue.
