### ISSUE TITLE
[Monorepo] Error: vue-cli-service electron:build

### ISSUE THREAD

**Issue by TamilselvanPunchh** [nklayman/vue-cli-plugin-electron-builder#1395]
**Node Version:** 16.2.0 | 14.17.0 | 12.22.1

**Yarn Version:** 1.22.5 | 1.18.0

**Electron Version:** ^12.0.0

**Target:** Mac

**Used:** Monorepo + Vue 2 + Electron (vue add electron-builder)

When the command is executed: `"electron:build": "vue-cli-service electron:build"`

**Returns the error:**

`electron-builder  version=22.10.5 os=18.5.0
InvalidConfigurationError: Cannot compute electron version from installed node modules - none of the possible electron modules are installed and version ("^12.0.0") is not fixed in the project.`

**Note:** This issue only coming for Monorepo, not in others.

**Comment by nklayman** [comment]
This appears to be an issue with electron-builder, a dependency of this plugin (https://github.com/electron-userland/electron-builder/issues/5097). As a solution, you can manually specify the electron version in `vue.config.js`:
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
        electronVersion: 'X.X.X'
      }
    }
  }
}
```

**Comment by TamilselvanPunchh** [comment]
It's working. Thanks @nklayman
