### ISSUE TITLE
Set Vue and Electron env variables

### ISSUE THREAD

**Issue by algil** [nklayman/vue-cli-plugin-electron-builder#14]
Hi!

I've created a .env file in order to set some environment variables for electron and Vue. I've read the official documentation https://github.com/vuejs/vue-cli/blob/dev/docs/env.md, but when I print `console.log(process.env.BASE_URL)` in a Vue component `undefined` is shown. The same when I set `ELECTRON_DISABLE_SECURITY_WARNINGS` for Electron. Nothing happens.

How can I set env variables for Vue and Electron?

Thanks!

**Comment by luis-git** [comment]
you need to restart the server  every time you edit the .env file

**Comment by algil** [comment]
Hi @luis-git,

> you need to restart the server every time you edit the .env file, for the changes to take effect.

I do it.

> Only variables that start with VUE_APP_ will be accepted.

Then how do I set Electron variables? Or BASE_URL which is accepted by Vue.

Thanks!

**Comment by luis-git** [comment]
in your .env define it like this and restart the server make sure the .env file is in the root dir.
VUE_APP_BASE_URL = http://yourbaseurl.test/

**Comment by algil** [comment]
Tested but it doesn't work. 😔

It's in the root:
![image](https://user-images.githubusercontent.com/520071/40984788-ff598d7a-68e2-11e8-8304-02850c77eab0.png)

And it only has one line:

`VUE_APP_BASE_URL = http://yourbaseurl.test/`

🤷‍♂️

**Comment by luis-git** [comment]
have you console it like this?
console.log(process.env.VUE_APP_BASE_URLL)

**Comment by algil** [comment]
Yes, I have. but it prints `undefined`

![image](https://user-images.githubusercontent.com/520071/40985402-52604882-68e4-11e8-9f49-e249bd31406e.png)

**Comment by nklayman** [comment]
Try using window.process.env instead. I had a similar issue and this worked for me.

**Comment by algil** [comment]
Same result.

It only prints these variables, but not `VUE_APP_BASE_URL`:

![image](https://user-images.githubusercontent.com/520071/40989981-c06382d0-68ef-11e8-92c9-3fd8cfe911e1.png)

**Comment by luis-git** [comment]
make sure you are using vue cli 3 to create your project, this only works for that version.

**Comment by nklayman** [comment]
try using `ELECTRON_WEBPACK_APP` prefix instead: [electron-webpack environment variables documentation](https://webpack.electron.build/environment-variables).

**Comment by luis-git** [comment]
I'm using Windows OS and it works just fine as per vue docs. no need extra configurations.

**Comment by algil** [comment]
Hi!

It was my bad... when I created the .env file (Maybe by Webstorm). I've create a new app from scratch with same configuration and it's works, then I saw the difference between both files... and...

![image](https://user-images.githubusercontent.com/520071/41115328-722783f2-6a87-11e8-8eda-33ffa76d8dda.png)

Thanks a lot!

**Comment by Garry028** [comment]
Im facing a problem regarding env in deployed version on amplify  in  local env are coming
