### ISSUE TITLE
Electron cannot display local images in dev mode - "Not allowed to load local resource"

### ISSUE THREAD

**Issue by AlexSHoffman** [nklayman/vue-cli-plugin-electron-builder#140]
**Describe the bug**
Electron cannot display local images in dev mode since it doesn't load `file://` urls while it is running a page from a non-file URL.

**Reproduction:**
Try to display an image e.g.:
```
<img src="C:\test\image.png">
```

**Proposed solution:**

Disable `webSecurity` in development mode:

```
// backgound.js

const window = new BrowserWindow({
    webPreferences: { 
      webSecurity: process.env.NODE_ENV !== 'development',
    }
})
```

**Comment by nklayman** [comment]
See the [docs on handling static assets](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#electron-not-opening-on-node-v11). Place the image in the public folder and use the __static variable.

**Comment by AlexSHoffman** [comment]
@nklayman yeah, but I'm not talking about the bundled images the developer puts in the app. What if an Electron app need to display images from the user's disk? 

A lot of apps need to display images from the disk. For example: VScode, any graphics related app, any note taking app that supports images, an image gallery app, a wallpaper downloader, a screen recorder, a screenshot taker app.

**Comment by nklayman** [comment]
Other popular templates such as Electron-Vue, Electron-React-Boilerplate, and the suggested main.js on Electron's docs all have websecurity enabled, even by default.

**Comment by AlexSHoffman** [comment]
@nklayman I'm not sure, but I think the problem exists only in development mode, because of webpack's way of linking paths.

I haven't tried building the app yet. I don't know if that's a good way of doing this. I was hoping you'd already knew a workaround or the "proper" way of doing this since your knowledge in this matter is greater than mine.

I tried googling it and reading issues on GitHub / stackoverflow but I didn't really understand how developers are supposed to link images / videos etc from the disk if `webSecurity: true` is the default for development and production modes.

**Comment by choukui** [comment]
@AlexSHoffman I encountered the same problem in use. I wanted to play the downloaded video of the user, but he could not load the user's files from the disk. Has your problem been solved?

**Comment by nklayman** [comment]
Try preprending the url with `file://`, ie `<img src="file://C:/path_to_image.png />`.

**Comment by choukui** [comment]
@nklayman Thank you very much. My problem has been solved. But webSecurity: false, disable the homology policy to load disk files properly. Thank you

**Comment by abbrechen** [comment]
Additionally: Mac uses `file:///` (three slashes) and if you open an image with special characters in the name in the browser you will see they will be converted. E.g. a **#** will be **%23** and you need to care about it in the image tag source.

**Comment by ndtreviv** [comment]
I have an electron app that users drop their images into and it renders them from the local path. It was all working, but now it's not. 

eg this:
```
<img src="file:///Users/me/Downloads/MyImage.jpg" />
```
used to render the image. Now it doesn't - I get a broken image icon instead. I'm not sure this is a vue issue, though. 

Seems to be something changed with electron (I upgraded recently).
