### ISSUE TITLE
testWithSpectron failing with open handles

### ISSUE THREAD

**Issue by ste163** [nklayman/vue-cli-plugin-electron-builder#1401]
**Describe the bug**
`testWithSpectron` always fails. I tried setting up spectron in an existing project and was getting this same error. So I made a fresh project, installed the the electron-builder, and am getting the same error.

My apologies if I'm missing something really obvious. I really appreciate this project!

**To Reproduce**
- Create a new Vue project
- Install the Vue CLI Plugin Electron Builder
- Install latest Jest
- Install v14 of Spectron (I tried using Electron 12 with Spectron 14 & Electron 13 with Spectron 15 and got same errors)
- Copy & paste jest test example from docs (https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/testingAndDebugging.html#testing)

**Expected behavior**
The test should have completed successfully.

**Screenshots**
![test-fail-01](https://user-images.githubusercontent.com/62910490/120117654-3b3df400-c15c-11eb-9126-ff4e60e8a66e.png)
![test-fail-02](https://user-images.githubusercontent.com/62910490/120117656-3da04e00-c15c-11eb-985b-a74024a1e92e.png)

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: nothing custom
 - (if possible) link to your repo: none as I created a fresh project
 - terminal output from running `vue info`:
 ```
 System:
    OS: Linux 5.4 Linux Mint 20.1 (Ulyssa)
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
  Binaries:
    Node: 16.1.0 - ~/.nvm/versions/node/v16.1.0/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.12.1 - ~/.nvm/versions/node/v16.1.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.77
    Firefox: 88.0.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.0.6 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.13 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.13 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-router:  4.5.13 
    @vue/cli-plugin-vuex:  4.5.13 
    @vue/cli-service: ~4.5.0 => 4.5.13 
    @vue/cli-shared-utils:  4.5.13 
    @vue/component-compiler-utils:  3.2.0 
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/web-component-wrapper:  1.3.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.12 
    vue-cli-plugin-electron-builder: ~2.0.0 => 2.0.0 
    vue-eslint-parser:  7.6.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.7 (16.2.0)
    vue-style-loader:  4.1.3 
    vue-template-compiler: ^2.6.11 => 2.6.12 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: Not Found

 ```

**Comment by ste163** [comment]
Was hoping v2.1.1 would have fixed this, but I created a new project and am getting all the same errors :(

**Comment by nklayman** [comment]
The v3 alpha uses Playwright instead of Spectron which may fix your issue. You can give it a try now or wait for it to be released as stable, but I'll close this issue for now. If it still occurs with Playwright I'll reopen this issue.

https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v3.0.0-alpha.0

**Comment by ShubhamPalriwala** [comment]
@nklayman I still face the same issue even with the v3-alpha

**Comment by nklayman** [comment]
Can you open a full bug report then? It is likely a different error than with spectron as it is a completely different framework.
