### ISSUE TITLE
Vue3 compatible or migration guide

### ISSUE THREAD

**Issue by ajmasia** [nklayman/vue-cli-plugin-electron-builder#1416]
Is this plugin compatible with [Vue3](https://github.com/vuejs/vue-next)? It's possible to make a migration how described [here](https://v3.vuejs.org/guide/migration/introduction.html)

Migrate plugin to Vue3 or write a manual migration guide

It would be nice to be able to use [Vite]([Home | Vite](https://vitejs.dev/)) 😄 

Thanks guys 💪

**Comment by nklayman** [comment]
This plugin works just fine with Vue 3, that migration guide should apply. I can't use Vite unless Vue CLI switches to use it.
