### ISSUE TITLE
WebpackOptionsValidationError

### ISSUE THREAD

**Issue by xygengcn** [nklayman/vue-cli-plugin-electron-builder#1420]
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.mode should be one of these:
   "development" | "production" | "none"
   -> Enable production optimizations or development hints.

run a new project，and  error occurred，how to fix bugs，  thanks

**Comment by nklayman** [comment]
Please open a new issue that follows the bug report template, and ideally include a repo that demonstrates the error. I need more information to debug this.
