### ISSUE TITLE
Set Icon

### ISSUE THREAD

**Issue by fsk** [nklayman/vue-cli-plugin-electron-builder#1421]
Hello.

I could not set icon my electron-vue project.

 module.exports = {
   pluginOptions: {
     electronBuilder: {
       builderOptions: {
         win: {
           icon: '../build/icons/logo2.png'
         }
       }
     }
   }
 }

Here is my vue.config.js

and my createWindow function in background.js file

async function createWindow() {
  // Create the browser window.
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    //icon: path.join(__dirname, '../build/icons/logo2.png'),
    resizable: isDev,
    webPreferences: {
      
      // Use pluginOptions.nodeIntegration, leave this alone
      // See nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration for more info
      //icon: path.join(__dirname, '../logo2.ico'),
      nodeIntegration: process.env.ELECTRON_NODE_INTEGRATION,
      contextIsolation: !process.env.ELECTRON_NODE_INTEGRATION
    }
  })

  win.removeMenu();
  win.setIcon(path.join(__dirname, './build/icons/logo2.png'));

  if (process.env.WEBPACK_DEV_SERVER_URL) {
    // Load the url of the dev server if in development mode
    await win.loadURL(process.env.WEBPACK_DEV_SERVER_URL)
    if (!process.env.IS_TEST) win.webContents.openDevTools()
  } else {
    createProtocol('app')
    // Load the index.html when not in development
    win.loadURL('app://./index.html')
  }
}

The above code works but the icon always stays the same.

How can i fix.?

**Comment by trandaison** [comment]
Please, put your code between ``<b></b>` and ``<b></b>` to make it readable.

**Comment by nklayman** [comment]
Please post a link to a repo that demonstrates the error. I need to be able to reproduce it myself to help debug.

**Comment by Kenhuey** [comment]
meet the similar problem, i reach the document and put 256x256 logo on icons/icon.png
when i build it turns wrong

build log:
  • writing effective config  file=dist_electron\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=12.0.0 appOutDir=dist_electron\win-unpacked
panic: runtime error: index out of range [-1]
...
 exitCode: 2,
  alreadyLogged: true,
  code: 'ERR_ELECTRON_BUILDER_CANNOT_EXECUTE'
