### ISSUE TITLE
how can i use fs in .vue file

### ISSUE THREAD

**Issue by dugudongfangshuo** [nklayman/vue-cli-plugin-electron-builder#1427]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nklayman** [comment]
You need to either enable [node integration](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration) and just import like in a node application (less secure but easy) or use [IPC](https://www.electronjs.org/docs/api/ipc-main) through a preload file to run fs operations in the main process (more secure but not as easy).
