### ISSUE TITLE
How to use the latest Electron

### ISSUE THREAD

**Issue by dugudongfangshuo** [nklayman/vue-cli-plugin-electron-builder#1430]
How to use the latest Electron?  now only support 10.11.12

**Comment by aleksey-hoffman** [comment]
Upgrade the Electron manually:

`npm install electron@latest`

**Comment by aleksey-hoffman** [comment]
You can upgrade Electron manually: `npm install electron@latest`

**Comment by nklayman** [comment]
The above solution should work for you. Just upgrade electron like any other npm dep.
