### ISSUE TITLE
Wrong Devtools requested for Vue 3

### ISSUE THREAD

**Issue by yelonek** [nklayman/vue-cli-plugin-electron-builder#1431]
**Describe the bug**
Wrong dev tools are requested from electron-devtools-installer.
If we have Vue 2, then current behaviour is correct.
For Vue 3 it should be VUEJS3_DEVTOOLS.

It is precisely this line:
https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/master/generator/templates/base/src/background.js#L5

**To Reproduce**
I added electron to my Vue 3 app. I didn't get Vue Devtools running.

**Expected behavior**
Vue 3 Devtools beta should run.

**Environment:**
Environment Info:

  System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.48)
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.0.6
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.13
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.13
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.13
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.13
    @vue/cli-plugin-router: ~4.5.0 => 4.5.13
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.13
    @vue/cli-service: ~4.5.0 => 4.5.13
    @vue/cli-shared-utils:  4.5.13
    @vue/compiler-core:  3.1.1
    @vue/compiler-dom:  3.1.1
    @vue/compiler-sfc: ^3.0.0 => 3.1.1
    @vue/compiler-ssr:  3.1.1
    @vue/component-compiler-utils:  3.2.0
    @vue/devtools-api:  6.0.0-beta.13
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/reactivity:  3.1.1
    @vue/runtime-core:  3.1.1
    @vue/runtime-dom:  3.1.1
    @vue/shared:  3.1.1
    @vue/web-component-wrapper:  1.3.0
    eslint-plugin-vue: ^7.0.0 => 7.10.0
    vue: ^3.0.0 => 3.1.1
    vue-cli-plugin-electron-builder: ~2.0.0 => 2.0.0
    vue-eslint-parser:  7.6.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.7 (16.2.0)
    vue-router: ^4.0.0-0 => 4.0.8
    vue-style-loader:  4.1.3
    vue-template-es2015-compiler:  1.9.1
    vuex: ^4.0.0-0 => 4.0.1
  npmGlobalPackages:
    @vue/cli: Not Found

**Additional contex**
I am a beginner and I don't know how to properly fix it.
Just wanted to let you know, so next person does not waste 3 hours on this just like I did.

**Comment by meedfine** [comment]
![image](https://user-images.githubusercontent.com/35157761/122167759-fb8e4080-cead-11eb-9499-b4e22a0351cb.png)


replace   VUEJS_DEVTOOLS  to VUEJS3_DEVTOOLS

**Comment by nklayman** [comment]
I just pushed an update that makes the generator automatically use vue 3 devtools if the project uses vue 3.
