### ISSUE TITLE
Webpack: how to automatically include imported files into the build directory?

### ISSUE THREAD

**Issue by aleksey-hoffman** [nklayman/vue-cli-plugin-electron-builder#1439]
Hi @nklayman could you please suggest a proper way to configure Webpack so it would include imported from `./src` modules into the production build?

For some reason Webpack is not automatically including referenced with `require()` files into the dist directory (production build).

I'm trying to import a local `../src/utils/sharedUtils.js` module:
https://github.com/aleksey-hoffman/sigma-file-manager/blob/main/src/utils/sharedUtils.js

into a renderer window `public/quickViewWindow.html`:

```html
<body>
  <div id="content-container"></div>
  <script type="module">
    const sharedUtils = require('../src/utils/sharedUtils')
    ...
```

It's working in dev, but not working in the production build:

```
Uncaught Error: Cannot find module '../src/utils/sharedUtils'
Require stack:
- C:\Users\AL\AppData\Local\Programs\sigma-file-manager\resources\app.asar\quickViewWindow.html
```

Running this code in the console (production build):

```
console.log(require('fs').readdirSync(__dirname))
```

Shows that Webpack indeed does not include the `./src/utils/sharedUtils.js` file:

```js
0: "0e7fe195a8e2c74bd1f0.worker.js"
1: "0e7fe195a8e2c74bd1f0.worker.js.map"
2: "253bb5a8f9e801b6d940.worker.js"
3: "253bb5a8f9e801b6d940.worker.js.map"
4: "58082cc4c1c8cb1b52e4.worker.js"
5: "58082cc4c1c8cb1b52e4.worker.js.map"
6: "background.js"
7: "background.js.LICENSE.txt"
8: "configs"
9: "css"
10: "errorWindow.html"
11: "fonts"
12: "game"
13: "icons"
14: "img"
15: "index.bundle.js"
16: "index.bundle.js.map"
17: "index.html"
18: "js"
19: "node_modules"
20: "package.json"
21: "quickViewWindow.html"
22: "resources"
23: "server"
24: "trashManagerWindow.html"
```

Here's the Webpack config file:

https://github.com/aleksey-hoffman/sigma-file-manager/blob/main/vue.config.js

With a few small modifications, I'm pretty much using the default electron-builder config.

**Comment by aleksey-hoffman** [comment]
I fixed it with the following code, but I'm not sure if it's a proper way to do it:

```js
const CopyPlugin = require('copy-webpack-plugin')
...
  configureWebpack: {
    plugins: [
      new CopyPlugin([
        {from: './src', to: 'src'}
      ])
    ]
  }
```

**Comment by nklayman** [comment]
Any files in the `public` folder are copied without being processed by webpack (except for `index.html`). Since `quickViewWindow.html` is in the `public` folder, webpack doesn't see that it is importing a module, so `sharedUtils` isn't included in the final build. Using copy-webpack-plugin like the snippet you posted works fine, but it means that the entire unprocessed source of your application will be included in the build. Since your project is open source, this isn't a huge deal, but it could increase the bundle size of your app. I'd suggest changing the plugin to only copy the specific files you need.

**Comment by aleksey-hoffman** [comment]
@nklayman thanks for the suggestion and the explanation
