### ISSUE TITLE
How to serve application on specified port?

### ISSUE THREAD

**Issue by jakerieger** [nklayman/vue-cli-plugin-electron-builder#1442]
How would I run `electron:serve` on a specific port instead of the default port `8080`? I tried adding `--port XXXX` to the end of the electron serve and vue serve commands in the `package.json` and it didn't change.

**Comment by nklayman** [comment]
This currently isn't possible but I might be able to add it. Why do you need this?

**Comment by jakerieger** [comment]
For my partner to see the UI update live in our VS Code liveshare, he needs to run it on port 8081 instead of 8080: [](https://blog.infernored.com/electron-angular-7-and-vs-code-liveshare/)

**Comment by nklayman** [comment]
Sorry for the delayed response, had to take a break from open source to focus on school.

I think the above solution might work, you can give that a try. Either way, I don't think using VSCode liveshare with electron is a good idea. With the separated main/renderer processes there are so many things that could go wrong.
