### ISSUE TITLE
Electron 13 + Webpack -> require is not defined 

### ISSUE THREAD

**Issue by MigFerreira** [nklayman/vue-cli-plugin-electron-builder#1446]
After updating plugin to 2.1.0 and Electron to 13.1.4 on app startup getting following error visible in console:

`external "events"?7a7e:1 Uncaught ReferenceError: require is not defined
    at eval (external "events"?7a7e:1)
    at Object.events (app.js:3462)
    at __webpack_require__ (app.js:790)
    at fn (app.js:151)
    at eval (emitter.js?a6bd:1)
    at Object../node_modules/webpack/hot/emitter.js (chunk-vendors.js:22893)
    at __webpack_require__ (app.js:790)
    at fn (app.js:151)
    at eval (dev-server.js?6895:50)
    at Object../node_modules/webpack/hot/dev-server.js (chunk-vendors.js:22882)`

Problematic line in node_modules/webpack/hot/dev-server.js
`var hotEmitter = require("./emitter");`

**Comment by webrtcn** [comment]
please check your "vue.config.js" file:

set webpack property "target" to web.


```
module.exports = {
  configureWebpack: {
    target: 'web'
  }
}
```

**Comment by MigFerreira** [comment]
Thanks @webrtcn that got me through that one, now I'm getting:
`index.js?bdb9:4 Uncaught ReferenceError: __dirname is not defined
    at eval (index.js?bdb9:4)
    at Object../node_modules/electron/index.js (chunk-vendors.js:15262)
    at __webpack_require__ (app.js:790)
    at fn (app.js:151)
    at eval (settings.js?9af2:3)
    at Module../src/store/modules/settings.js (app.js:2718)
    at __webpack_require__ (app.js:790)
    at fn (app.js:151)
    at eval (index.js?fb0c:1)
    at Module../src/store/index.js (app.js:2622)`

which is invoked through: 
`const { remote } = require('electron')`

I have confirmed that `nodeIntegration = true`  gonna keep investigating.

**Comment by MigFerreira** [comment]
Ok, got it working.
Had to add in `contextIsolation=false`. Not exactly sure on the repercussions on this flag will have to dive into it a little.
Thanks for the help.

**Comment by webrtcn** [comment]
I just used "preload mode" in my project.

1.  change "vue.config.js " file
```
module.exports = {
  configureWebpack: {
    target: 'web'
  }
  pluginOptions: {
      electronBuilder: {
           preload: 'src/preload.js'
      }
  }
}
```
2. change "BrowserWindow webPreferences"
```
webPreferences: {
     nodeIntegration: false,
     contextIsolation: true,
     preload: path.join(__dirname, 'preload.js')
 }
```
3. create preload.js -> 'src/preload.js'

In my project, only use "ipcRenderer" and "process".  They are 'electron object' or 'main object'  ??  whatever!

```
import path from 'path'
import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('process', {
  platform: process.platform,
  preload: path.join('file://', __dirname, 'preload.js'),
  env: {
    NODE_ENV: process.env.NODE_ENV,
  },
})

contextBridge.exposeInMainWorld('ipcRenderer', {
  addListener: (channel, fn) => {
    ipcRenderer.addListener(channel, fn)
  },

  removeListener: (channel) => {
    ipcRenderer.removeAllListeners(channel)
  },

  send: (channel, ...args) => {
    ipcRenderer.send(channel, ...args)
  },
})

```
4. relpace "ipcRenderer" to "window.ipcRenderer" and "process" to "window.ipcRenderer" in renderer process

5. add "preload" to <webview> label

```
      <webview
        webpreferences="contextIsolation=no"
        :preload="preload"
        class="webview"
        ref="webview"
        :src="src" 
      ></webview>
```

":preload" is window.process.preload

**Comment by nklayman** [comment]
Electron is replacing `nodeIntegration=true` with `contextIsolation=false`. I think that was causing your issue as it would explain why upgrading electron broke it and adding `contextIsolation=false` fixed it.

**Comment by blogwy** [comment]
> Electron is replacing `nodeIntegration=true` with `contextIsolation=false`. I think that was causing your issue as it would explain why upgrading electron broke it and adding `contextIsolation=false` fixed it.

doc not update
