### ISSUE TITLE
Vue add electron-builder  appear some error

### ISSUE THREAD

**Issue by huoher** [nklayman/vue-cli-plugin-electron-builder#1447]
**Describe the bug**
While I use command "Vue add electron-builder" in Vue-cli4，there some erroe in terminal:
```bash
C:\Users\qiuchi\Desktop\demo-vue-master\node_modules\vue-cli-plugin-electron-builder\generator\index.js:18
      vue3: /^(\^?)3/.test(pkg?.dependencies?.vue)
```

**Expected behavior**
We sincerely hope to get your help！

**Screenshots**

**Environment (please complete the following information):**
-  System OS: Windows 10
- VueCli: 2.6.11

**Comment by nklayman** [comment]
I just published an update that fixes the issue. Thanks for the report!
