### ISSUE TITLE
npm ERR! code ERESOLVE npm ERR! ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by loriswave** [nklayman/vue-cli-plugin-electron-builder#1450]
Hi,
I try to start a new project but I meet an issue.
my node is: node-v14.17.1
vue cli is: 4.5.13
SO: windows 10

I create a new project: vue create my_project
go inside: cd my_project
add electron builder: vue add electron-builder

the installer notify some vulnerabilities so i try to fix: npm audit fix

normally it not fix anything and I go ahead but this time I have an error:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: webpack@4.46.0
npm ERR! node_modules/webpack
npm ERR!   peer webpack@"^4.0.0" from @intervolga/optimize-cssnano-plugin@1.0.6
npm ERR!   node_modules/@intervolga/optimize-cssnano-plugin
npm ERR!     @intervolga/optimize-cssnano-plugin@"^1.0.5" from @vue/cli-service@4.5.13
npm ERR!     node_modules/@vue/cli-service
npm ERR!       dev @vue/cli-service@"~4.5.0" from the root project
npm ERR!       4 more (@vue/cli-plugin-babel, @vue/cli-plugin-eslint, ...)
npm ERR!   peer webpack@"^4.0.0 || ^5.0.0" from @soda/friendly-errors-webpack-plugin@1.8.0
npm ERR!   node_modules/@soda/friendly-errors-webpack-plugin
npm ERR!     @soda/friendly-errors-webpack-plugin@"^1.7.1" from @vue/cli-service@4.5.13
npm ERR!     node_modules/@vue/cli-service
npm ERR!       dev @vue/cli-service@"~4.5.0" from the root project
npm ERR!       4 more (@vue/cli-plugin-babel, @vue/cli-plugin-eslint, ...)
npm ERR!   21 more (@vue/cli-plugin-babel, @vue/cli-plugin-eslint, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.0.0 || ^5.0.0" from terser-webpack-plugin@3.1.0
npm ERR! node_modules/vue-cli-plugin-electron-builder/node_modules/terser-webpack-plugin
npm ERR!   terser-webpack-plugin@"^3.0.3" from vue-cli-plugin-electron-builder@2.1.1
npm ERR!   node_modules/vue-cli-plugin-electron-builder
npm ERR!     dev vue-cli-plugin-electron-builder@"~2.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

I have try both Vue 2 or Vue 3 and Electron 11 or 13 and is the same.

**Comment by nklayman** [comment]
It seems that the error is caused by `terser-webpack-plugin`, a dependency of this package. I don't think there is really anything I can do in this package to fix the issue, so I think you'll just have to use the `--legacy-peer-deps` until the issue is fixed in `terser-webpack-plugin`.
