### ISSUE TITLE
Optional Chaining not supported

### ISSUE THREAD

**Issue by johnliveeoroncillo** [nklayman/vue-cli-plugin-electron-builder#1454]
Currently I'm using optional chaining on my objects and It has an error when Im executing electron:build it says "You need additional loaders ..."

ex. this.data?.results?.raw?.length

**Comment by sxzz** [comment]
Webpack 4 doesn't support Optional Chaining, you should use Babel to transform code.

```javascript
// babel.config.js
module.exports = {
  plugins: ['@babel/plugin-proposal-optional-chaining', '@babel/plugin-proposal-nullish-coalescing-operator'],
};
```
