### ISSUE TITLE
Electron powerMonitor not working

### ISSUE THREAD

**Issue by schoolver** [nklayman/vue-cli-plugin-electron-builder#1461]
Electron Version: 13
vue-cli-plugin-electron-builder: 2.1.1
Node: 14.17.1
Npm version: 6.14

**PowerMonitor not working*
I trying to fetch System idle from `powerMonitor.getSystemIdleTime()` but it returns `Cannot read property 'getSystemIdleTime' of undefined`

*App.vue*

```
const { powerMonitor } = require('electron')

methods: {
      systemIdleTime() {
        return powerMonitor.getSystemIdleTime();
      },
}

<template>
    <div>{{systemIdleTime()}}</div>
</template>
```

**Comment by MatthijsBurgh** [comment]
You can't access `powerMonitor` in the renderer. Only in the main. See https://www.electronjs.org/docs/latest/api/power-monitor

This is an electron issue, not related to this project.
