### ISSUE TITLE
Cannot run the .exe file

### ISSUE THREAD

**Issue by inwebdesign** [nklayman/vue-cli-plugin-electron-builder#1463]
Hi, I've created a desktop app with Vue-electron. I'm trying to deploy it for win devices.  I've managed to create .exe file which basically should run the app, but when I launch the app, I'm facing issues. 
First, it was the issue of **'Can't use import statement outside ES module'**, which I resolved (changing vue.config**.js** to **.cjs**, and changing the calls in background.js from import to require), 
Then I hit another one when the builder reach this one _(const { createProtocol } = require('vue-cli-plugin-electron-builder/lib'))_, it couldn't resolved that path. I resolve the issue by moving "vue-cli-plugin-electron-builder": "^2.0.0-rc.6" from dev-dependencies to dependencies. 
Now, I'm facing with another one, when I run the app I got :  **SyntaxError: Unexpected token 'export'** in this line: _export {default as InstallVueDevtools} from './installVueDevtools'._
my package.json:
{
  "name": "", _/* I have entered properly, removed on purpose here */_
  "author": "", _/* I have entered properly, removed on purpose here */_
  "version": "1.0.0", 
  "license": "MIT",
  "scripts": {
    "serve": "vue-cli-service serve",
    "lint": "vue-cli-service lint",
    "build": "vue-cli-service build",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps",
    "dist": "electron-builder"
  },
  "build": {
       "appId": "", _/* I have entered properly, removed on purpose here */_
        "productName": "", _/* I have entered properly, removed on purpose here */_
        "target": "NSIS",
         "directories": {
             "output": "build"
         }
    },
  "nsis": {
       "allowToChangeInstallationDirectory": true,
       "oneClick": false
  },
  "main": "./src/background.js",
  "dependencies": {
    "@babel/preset-env": "^7.14.7",
    "axios": "^0.21.1",
    "copy-webpack-plugin": "^9.0.1",
    "core-js": "^3.6.5",
    "html2pdf.js": "^0.9.2",
    "keytar": "^7.6.0",
    "os": "^0.1.1",
    "systeminformation": "^5.6.10",
    "vue": "^2.6.11",
    "vue-ellipse-progress": "^1.3.0",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0",
    "vue-cli-plugin-electron-builder": "^2.0.0-rc.6"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.5.0",
    "@vue/cli-plugin-eslint": "^4.5.0",
    "@vue/cli-service": "^4.5.0",
    "babel-eslint": "^10.1.0",
    "electron": "^11.0.0",
    "electron-devtools-installer": "^3.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "vue-template-compiler": "^2.6.11"
  }
}

my vue.config.js:
module.exports = {
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true,
      externals: ['keytar', 'vue-cli-plugin-electron-builder'],
      mainProcessFile: './src/background.js',
  }
}
}

Note: my node version is 14.17.1

Any thoughts? Thanks

**Comment by nklayman** [comment]
You need to remove `vue-cli-plugin-electron-builder` from your `externals` array in `vue.config.js`. It has ES6 code that needs to be transpiled by webpack. Adding it as an external skips the webpack transpialation.
