### ISSUE TITLE
After using China image to install, the operation will report an error

### ISSUE THREAD

**Issue by hello-schurmi** [nklayman/vue-cli-plugin-electron-builder#1464]
After using China mirror, execute 'npm run electron: serve' error code：
 
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
- configuration.mode should be one of these:
   "development" | "production" | "none"
   -> Enable production optimizations or development hints.

**Comment by nklayman** [comment]
Please open a new issue that follows the bug report template and ideally includes a sample repo that demonstrates the error. I need more information to debug this.
