### ISSUE TITLE
unable to use __dirname in typescript file even with nodeIntegration true

### ISSUE THREAD

**Issue by amsanket22** [nklayman/vue-cli-plugin-electron-builder#1473]
**Problem**
I am using typescript and express which working perfectly fine with vue, but I want to use the fs module with path and when I use __dirname it resolves to dist_electron but I want to use the current directory where I am writing the code.

I have written migrations in the SQL files which I am trying to access like following - 

`const migrationDirectory = path.join(__dirname);
`
migration directory is the same directory in which this code has been written but it gives the following error - file not found in dist_electron. - `src/server/migrations`
init.sql file location - `src/server/migrations/init.sql` 
**Environment:**
 I am doing this in development mode, haven't built the production build yet. Using preload.js  like following -
 `module.exports = {
    pluginOptions: {
      electronBuilder: {
        nodeIntegration: true,
        externals: ['express','typeorm','sqlite','fs','path'],
        preload: 'src/server/index.ts',
      }
    }
  }`

tsconfig.json - 
`{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "webpack-env",
      "node"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": [
    "node_modules",
  ]
}
`

<img width="912" alt="Screenshot 2021-07-19 at 2 20 56 PM" src="https://user-images.githubusercontent.com/11029171/126132463-6415ad31-ecf6-4b5d-9b14-79135d9432f7.png">

**Comment by amsanket22** [comment]
Should I use public dir in that case? and keep my SQL files there and access them using __static?

**Comment by nklayman** [comment]
Yes, you should use the public dir for this. Files there will just be copied, whereas files in src have to be a part of the webpack dependency tree to be included, which is a lot harder to set up.
