### ISSUE TITLE
electron:serve can't go in main process

### ISSUE THREAD

**Issue by klren0312** [nklayman/vue-cli-plugin-electron-builder#1475]
**Describe the bug**
When I use `npm run electron:serve` and my project has a `yarn.lock` file, it will appear

**To Reproduce**
The project has 'yarn.lock`, but computer didn't install `yarn`, and use `npm run electron:serve` to start project
It will stuck at render process, not go to main process

**Expected behavior**
It don't have this effect

**Screenshots**
![image](https://user-images.githubusercontent.com/10903843/126278023-ef4322be-8344-49c6-9b31-c5daa6fcd080.png)

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder:  `v22.9.1`
 - (if possible) link to your repo: 
 - terminal output from running `vue info`: 
```
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 14.17.0 - D:\nodejs\node.EXE
    Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.15.0 - D:\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.124
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2
    @vue/babel-plugin-jsx:  1.0.0-rc.3
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.9
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.9
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.9
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.9
    @vue/cli-plugin-router: ~4.5.0 => 4.5.9
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.9
    @vue/cli-service: ~4.5.0 => 4.5.9
    @vue/cli-shared-utils:  4.5.9
    @vue/component-compiler-utils:  3.2.0
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    vue: ^2.6.11 => 2.6.12
    vue-cli-plugin-electron-builder: ~2.0.0-rc.5 => 2.0.0-rc.5
    vue-clipboard2: ^0.3.1 => 0.3.1
    vue-eslint-parser:  7.1.1
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.5 (16.2.0)
    vue-router: ^3.2.0 => 3.4.9
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.12
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.4.0 => 3.6.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

**Additional context**

**Comment by nklayman** [comment]
I'm not sure what you mean. Can you elaborate a little bit more so that I can understand the bug?

**Comment by klren0312** [comment]
when my project has `yarn.lock`, but my computer didn't install 'yarn'
I use `npm run electron:serve`, it only serves render process, not run the main process
I think it is`vue cli` problem

**Comment by kurohoan** [comment]
It is not clear if this is a YARN problem.
Anyway, when I run the serve command, I get
"INFO Launching Electron..."
message appears and does not proceed.
I would like to catch the error and have it output. What could be the cause of this symptom?

**Comment by kurohoan** [comment]
I found similar past tickets.

https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/24

**Comment by kurohoan** [comment]
In the end, the referenced article did not solve the problem.
I hope they can at least throw an error.

My environment is as follows

```
windows 10
"vue-cli-plugin-electron-builder":"~2.1.1",
npm 8.5.2
node v16.14.0
```

**Comment by kurohoan** [comment]
In the end, the referenced article did not solve the problem.


My environment is as follows
```
windows 10
"vue-cli-plugin-electron-builder":"~2.1.1",
npm 8.5.2
node v16.14.0
```

**Comment by axetroy** [comment]
I got the same issue with `pnpm.lock.yaml` when I did not install ppm in my computer.

This bug should bring by vue-cli service

Delete `pnpm.lock.yaml` and it resolved.
