### ISSUE TITLE
electron:build after not working the app

### ISSUE THREAD

**Issue by snapxtp** [nklayman/vue-cli-plugin-electron-builder#1476]
using  "vue-cli-plugin-electron-builder": "~2.1.1" "electron": "^9.0.0",

I am running "electron:build". It gets a build with no problem. After installing the .dmg file, the app won't open and "my application name quit unexpectedly." displays the error message

note: does not work in applications compiled for windows.

Thanks.

**Comment by nklayman** [comment]
Please post a repo that demonstrates the error. I can't help you debug unless I have more information.
