### ISSUE TITLE
__dirname is not defined (nodeIntegration: true, contextIsolation: false)

### ISSUE THREAD

**Issue by Proladon** [nklayman/vue-cli-plugin-electron-builder#1483]
same as #1234 ，but no answer there for me
so here I'm present a example repo: [electron_dirname_not_defined_reproduce](https://github.com/Proladon/electron_dirname_not_defined_reproduce)

## Gist
- Electron v13
- `nodeIntegration: true`
- `contextIsolation: false`
- electron-store

## Problem
1. `yarn electron:serve`
2. Got `ReferenceError: __dirname is not defined` Error

## Steps to reproduce the behavior:
1. `vue create <name>`
```
- typescript
- vue 3
```

2. `vue add electron-builder`

3. create `vue.config.ts`
```ts
module.exports = {
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true
    }
  }
}
```

4. modify `src/background.ts`
```ts
webPreferences: {
    contextIsolation: false, // hard code to false
}
```

5. `yarn add electron-store`

6. modify `src/main.ts`
```ts
import Store from 'electron-store'
const settings = new Store()
```
6. `yarn electron:serve`

7. Got `ReferenceError: __dirname is not defined` Error

**Comment by luxuebo** [comment]
webPreferences: {
    nodeIntegration: true,
    contextIsolation: false,
}

**Comment by nklayman** [comment]
Sorry for the delayed response, had to take a break from open source to focus on school. Your issue is that `vue.config.ts` is ignored and nodeIntegration isn't actually enabled. Rename it to `vue.config.js` and your app works.
