### ISSUE TITLE
auto ELECTRON_NODE_INTEGRATION

### ISSUE THREAD

**Issue by MathisTLD** [nklayman/vue-cli-plugin-electron-builder#1484]
why forcing nodeIntegration in headless mode ? (I wan't to disable it and the only solution for me right now is chaining webpack config)
setting nodeIntegration to false should at least force node integration to be disabled

https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/bbb09515b954fcbce7092b477d445fab3bdd6560/index.js#L634

**Comment by nklayman** [comment]
This was done because spectron required `nodeIntegration` to work properly. This will be removed in v3 as that uses Playwright instead of spectron.
