### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by stgzhangzheyi** [nklayman/vue-cli-plugin-electron-builder#1495]
![image](https://user-images.githubusercontent.com/44356902/128857414-972e5e0c-216c-46f0-9f87-95cfd4c21b6f.png)
![image](https://user-images.githubusercontent.com/44356902/128857510-575e170b-f131-478f-b7d7-92e9fd622bbf.png)
项目打包之后，win.loadUrl地址是正确的吗？

**Comment by klren0312** [comment]
Please give a minimal example

**Comment by nklayman** [comment]
Closing as no example/reproduction repo was provided.
