### ISSUE TITLE
打包报错2

### ISSUE THREAD

**Issue by stgzhangzheyi** [nklayman/vue-cli-plugin-electron-builder#1496]
![image](https://user-images.githubusercontent.com/44356902/128857785-5bfae143-4022-4e2e-b595-8ac344757517.png)
![image](https://user-images.githubusercontent.com/44356902/128857899-b9388e1e-2be3-4304-ba2b-1f6187c764bc.png)
![image](https://user-images.githubusercontent.com/44356902/128857964-dadd0397-a6e5-4f22-b2df-0b6cbef02ddf.png)
这样写，静态资源没法加载，是我写错了吗？还是什么原因导致的

**Comment by klren0312** [comment]
Please give a minimal example

**Comment by nklayman** [comment]
Closing as no example/reproduction repo was provided.
