### ISSUE TITLE
Auto update is found but not installed

### ISSUE THREAD

**Issue by arsh09** [nklayman/vue-cli-plugin-electron-builder#1498]
**Describe the bug**
The app seems to update for most of the users but it does not update for a few users (including myself). This is very strange because when I install a very old version (v1.0.7) of the software, it gets updated properly but when I install a recent previous version (let says v1.1.3) and tries to auto update to v.1.1.4, the update is not downloaded with not much logs. It gets stuck at this log:

```
// LOGS
Download block maps (old: "https://api.github.com/repos/arsh09/capnotrainer/releases/assets/42087610.blockmap", new: https://api.github.com/repos/arsh09/capnotrainer/releases/assets/42087610.blockmap)
[25388:0810/153300.854:ERROR:atom_bindings.cc(47)] Fatal error in V8: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```
and then suddenly quits. 

I remember that I changed the NSIS parameters from perMachine and perUser settings and then when it did not work, I had to revert back to the old settings. 

**Expected behavior**
The app gets updated properly for ALL users including me.

**Screenshots**
![Capture1](https://user-images.githubusercontent.com/16521157/128885979-d3ed503f-3038-478e-a68d-779548170a40.PNG)

**Environment (please complete the following information):**
@vue/cli 4.5.9
electron v5.0.0 (Required as I am re-compiling node modules and one of them depends on this version)
node v10.22.0 (32 Bit) as I am using a DLL file that was compiled for 32-bit and hence I can not assign more than 2GB memory to the app using --max-old-space-size argument.

**Comment by stgzhangzheyi** [comment]
![image](https://user-images.githubusercontent.com/44356902/128957907-2a1ae596-d889-4036-a153-e2de04afb4bd.png)
你好，请问你知道怎么解决这个问题吗？生产环境下，win.loadUrl的正确地址是win.loadURL("app://./index.html")？

我尝试在生产环境更改了win.loadUrl为 let wincc = `file://${__dirname}/index.html`

    win.loadURL(wincc)
但还是不行。
如果您有方案，不胜感激

**Comment by stgzhangzheyi** [comment]
![image](https://user-images.githubusercontent.com/44356902/128958295-bd8289fa-e8a3-4845-be73-6d35c3c9347a.png)

你好，请问你知道怎么解决这个问题吗？生产环境下，win.loadUrl的正确地址是win.loadURL("app://./index.html")？

我尝试在生产环境更改了win.loadUrl为 let wincc = `file://${__dirname}/index.html`

    win.loadURL(wincc)
但还是不行。
![image](https://user-images.githubusercontent.com/44356902/128958279-10c37b8d-508a-485d-9baa-e660b6003240.png)

如果您有方案，不胜感激

**Comment by lzdyes** [comment]
> ![形象](https://user-images.githubusercontent.com/44356902/128958295-bd8289fa-e8a3-4845-be73-6d35c3c9347a.png)
> 
> 你好，请问你知道怎么解决这个问题吗？生产环境下，win.loadUrl的正确地址是win.loadURL("app://./index.html")？
> 
> 我尝试在生产环境更改了win.loadUrl 为 let wincc = `file://${__dirname}/index.html`
> 
> ```
> win.loadURL(wincc)
> ```
> 
> 但还是不行。
> ![形象](https://user-images.githubusercontent.com/44356902/128958279-10c37b8d-508a-485d-9baa-e660b6003240.png)
> 
> 如果您有方案，不胜感激

protocol.registerSchemesAsPrivileged([{ scheme: 'app', privileges: { secure: true, standard: true } }])

createProtocol('app')

**Comment by arsh09** [comment]
Any suggestions on this please, @nklayman? 

The app keeps when I use an older version of the app but if I install the latest version  (from the release version, i.e. Github release), it does not crash. This seems to be an auto update issue but I am not sure why. I have been looking for memory leaks but can't find one.

**Comment by nklayman** [comment]
I've never seen that error before so I'm not sure how to help you. You should probably open an issue on the electron-builder repository instead, as that handles all the auto-update functionality. This plugin is likely not responsible for the issue as it doesn't do any special config for electron-builder's auto update, so I'll close this issue. If you find out that this plugin is causing the error rather than electron-builder, let me know and I'll reopen this.

**Comment by arsh09** [comment]
Thank you @nklayman  for your comments. 

I ended up moving the releases to another github repository, hoping that it would work for others as it is working for me. 

It seemed like the issue came from my stupid attempt to delete a release after publishing it and then forgetting to delete its Source Code and other tag files (MAYBE). 

Thanks anyways.
