### ISSUE TITLE
after build only white background window shows up when i run the app.exe

### ISSUE THREAD

**Issue by luis-git** [nklayman/vue-cli-plugin-electron-builder#15]
yarn serve:electron works just fine
yarn build:electron, the build just finishes fine without any errors but when i run the app, it shows a blank window. using buefy and windows os.

**Comment by nklayman** [comment]
Can you include steps for reproduction as I am unable to replicate the error. Make sure you are using the latest version of vue-cli.

**Comment by luis-git** [comment]
vue create app-electron
- manually select features
select 
Babel
Progressive Web App (PWA) support
Router
VueX
CSS Pre-processors
Linter / Formatter
E2E Testing

- then choose
SCSS/SASS

- then choose
Eslint with error prevention only

- thenc choose
lint on save

- then Cypress (Chrome only)

- then choose
In dedicated config files

- vue add electron-builder
- yarn build:electron

those are the steps to reproduce the issue

**Comment by nklayman** [comment]
Follow the instructions [here](https://webpack.electron.build/add-ons#sassscss) to add sass/scss support, it should work then. Please close this issue if it does.

**Comment by luis-git** [comment]
node-sass sass-loader are installed out of the box with vue, that does not solve the issue.
![sass](https://user-images.githubusercontent.com/9680925/41189871-c658dcfc-6bd4-11e8-91a0-253883754a45.jpg)

**Comment by nklayman** [comment]
Not sure why it isn't working. For now, just use regular build/serve until v1.0.0 comes out which will fix this issue. A beta should be released in about 1-2 weeks.

**Comment by luis-git** [comment]
thanks.

**Comment by traversng** [comment]
I'm running into the same issue. I have attached my package.json. Folder structure is identical to the guide. Using > 1.0.0 and the issue remains.

![image](https://user-images.githubusercontent.com/8641085/44801582-4bb97e00-ab6e-11e8-9bbc-c40478de5b33.png)

I am just wondering if this is a known bug and if we should reopen the issue

**Comment by nklayman** [comment]
It works fine for me, can you provide reproduction instructions that work on a fresh project?

**Comment by nklayman** [comment]
Upgrade to 1.0.0-rc.2, I think that would fix the issue.

**Comment by traversng** [comment]
@nklayman , sure run a fresh project and see what happens there. I may find my bug in the process anywho. If the bug remains, I will update you. If not, I will update my comment. Thanks for the diligence.

**Comment by traversng** [comment]
@nklayman Just ran a fresh vue cli 3 project with vue-router. No blank screen and routes fine. Now I am really spinning my wheels. Serves fine in my existing project but blank screen in the build. The only other dependencies I have are buefy, vuex, and vuefire.

**Comment by nklayman** [comment]
Make sure to disable history mode on your router for electron builds. Other than that I have no idea.

**Comment by brokyo** [comment]
Disabling history mode solved this problem for me but I couldn't find this suggestion anywhere in the docs. Leaving this as a signpost for others :)

**Comment by nklayman** [comment]
[It's in there](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#blank-screen-on-builds-but-works-fine-on-serve). It also notifies you when you add the plugin to a project using vue-router.

**Comment by vatsal743** [comment]
I had a similar issue. Please find my solution here.
https://github.com/ficonsulting/RInno/issues/107#issuecomment-494118785
