### ISSUE TITLE
vue-electron-builder / aws-sdk conflict

### ISSUE THREAD

**Issue by Arattian** [nklayman/vue-cli-plugin-electron-builder#150]
**Describe the bug**

Application served with this plugin runs an error on any AWS-SDK usage.
AWS-SDK package shows error when after util.isNode() condition it is trying access to its util.stream.Stream and util.stream is undefined. By going up in aws code, i saw this lines

```
  util.isBrowser: function isBrowser() { return process && process.browser; }
  util.isNode: function isNode() { return !util.isBrowser(); }
```

The main problem is that when electron serves application process.browser is undefined,which forces to util.isNode() return true and error happens. This problem does not exist in when serving vue in browser.
I think this problem more related to how the electron configures itself, and on which environment it runs 
and use packages. The background.ts file was not modified. 

**To Reproduce**
Way 1(preferable)
[https://github.com/Arattian/DynamoDb-Vue-Electron](url) Github repo.
1.git clone https://github.com/Arattian/DynamoDb-Vue-Electron.git
2.cd Dynamodb-Vue-Electron
3.npm i
4.npm run electron:serve
5.Click to Add Database
6.Input fields with any text.
7.Confirm

Way 2 
1.Add plugin.
2.Install aws-sdk.
3.Import AWS-SDK.

4.*In my case
```
       const db =  new AWS-SDK.DynamoDb({configs});
       db.listTables();
```

5.npm run electron:serve

**Expected behavior**
Process.browser to be defined in background.ts file. To force isNode() function to return false.
**Screenshots**
![screenshot from 2018-11-30 13-54-00](https://user-images.githubusercontent.com/36269636/49283732-0168d580-f4ac-11e8-9a3a-df741bac28ce.png)

**Environment (please complete the following information):**
 - OS and version: Ubuntu 18.04
 - node version: 10.10
 - npm version: 6.4.1
 - vue-cli-plugin-electron-builder version : ^1.0.0-rc.7
 - electron version: ^3.0.0
 - other vue plugins used: Vuex
 - custom config for vue-electron-builder: default configuration
 - [https://github.com/Arattian/DynamoDb-Vue-Electron](url)

**Comment by nklayman** [comment]
Try sticking `process.browser = {}` or `process.browser = true` to the beginning of your `background.ts`

**Comment by nklayman** [comment]
added the following to the top of `main.ts` and it worked fine:

```typescript
// @ts-ignore
process.browser = true;
```
