### ISSUE TITLE
An error occurred in Vue add electron builder

### ISSUE THREAD

**Issue by coincoc** [nklayman/vue-cli-plugin-electron-builder#1507]
![image](https://user-images.githubusercontent.com/67940946/130205020-b37f799f-01c0-4e3a-be88-43af9102ef62.png)

**Comment by klren0312** [comment]
node-sass causes this problem

**Comment by nklayman** [comment]
This doesn't seem to be an issue with this plugin, rather with node-sass. Try installing node-sass itself and see if it works.
