### ISSUE TITLE
No  way to inspect main process webpack configuration?

### ISSUE THREAD

**Issue by lingo** [nklayman/vue-cli-plugin-electron-builder#1509]
I can run `vue inspect` (or `vue-cli-service inspect) to see a dump of the webpack configuration for the renderer process, but I cannot work out how to do the same for the main process.

Is there a way to do this?

I'm wanting to use `chainWebpackMainProcess` to alter the main process webpack configuration, but to do this effectively, I need to see how webpack is configured by default for the main process.

**Comment by nklayman** [comment]
I don't think a way to inspect the main process webpack config is necessary as it is quite simple. The entire main process bundle is handled in [this function](https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/master/index.js#L582), which is less than 150 lines and should be pretty simple to understand. Let me know if you have any questions.

**Comment by lingo** [comment]
Reading a 150-line function of one of my build tools is not my definition of user-friendly!  :)

However, I thank you - I think this will serve my purpose.  If I find I have a need more often, I will see if I can implement the feature.

**Comment by axetroy** [comment]
solution:

```json
  "electron:serve": "vue-cli-service electron:serve --inspect=5858"
```

The argument for vue-cli will pass to the plugin and use it in the main process

```
C:\Users\Admin\my_project\node_modules\electron\dist\electron.exe dist_electron --inspect=5858
```
