### ISSUE TITLE
How to use native node library like better-sqlite3

### ISSUE THREAD

**Issue by crossle** [nklayman/vue-cli-plugin-electron-builder#151]
Electron can use native node library like better-sqlite3, how to use on vue? it's need load local native compiled file xxx.node, how to do on vue project?

**Comment by nklayman** [comment]
See the [docs on using native modules](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules).

**Comment by crossle** [comment]
Thanks
