### ISSUE TITLE
can't use with serialport

### ISSUE THREAD

**Issue by Minori-ty** [nklayman/vue-cli-plugin-electron-builder#1512]
**Describe the bug**
I added in vue.config.js, but don't work. 

![image](https://user-images.githubusercontent.com/79521943/131095516-968e6bf9-bd82-4b59-b7d1-515860e4e6ab.png)

![image](https://user-images.githubusercontent.com/79521943/131094838-4e6dd07c-f52b-4fbb-98af-c54ef9d3f287.png)

I also try this way, but it don't work: serialport/node-serialport#2089 (comment)

**To Reproduce**

demo: https://github.com/Minori-ty/electron-error-demo

**Expected behavior**
I wish I can import serialport without error

**Comment by klren0312** [comment]
try it
```js
module.exports = {
  configureWebpack: {
    externals: {
      serialport: 'require("serialport")'
    }
  }
}
```

**Comment by Minori-ty** [comment]
> try it
> 
> ```js
> module.exports = {
>   configureWebpack: {
>     externals: {
>       serialport: 'require("serialport")'
>     }
>   }
> }
> ```

it work，thank you
