### ISSUE TITLE
Env variables are missed after building app

### ISSUE THREAD

**Issue by SuperKirik** [nklayman/vue-cli-plugin-electron-builder#1519]
Hello ! I don't actually know if this is a bug or I'm doing something wrong...

**Describe the bug**
After building the app with `vue-cli-service electron:build`, no extra env variable is available in the app.

**To Reproduce**
After reading the discussions of the existing issues I tried different solutions, but with no success:
1) Setting with cross-env
`cross-env IS_STAGING=true && vue-cli-service electron:build
`

2) Using vue-cli-service option `mode`:
`vue-cli-service electron:build -- --mode staging` 
or
`vue-cli-service --mode staging electron:build`
with a file .env.staging:
`IS_STAGING=true
`

3) Moreover I was waiting that at least variables from `.env` file will be available but they don't
4) Then I tried to use `electron-builder.env` as it was said in electron-builder docs

**Additional context**
I'm logging `process.env` in main process into the file, and thats what I got:
```
{
  USER: 'xxx',
  __CFBundleIdentifier: 'com.test.gom.app',
  COMMAND_MODE: 'unix2003',
  LOGNAME: 'xxx',
  PATH: '/usr/bin:/bin:/usr/sbin:/sbin',
  SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.VUS0gzEOhE/Listeners',
  SHELL: '/bin/bash',
  HOME: '/Users/xxx',
  __CF_USER_TEXT_ENCODING: '0x1F5:0x0:0x0',
  TMPDIR: '/var/folders/pn/xdkvp1p95nddpm394d9qlkvm0000gn/T/',
  XPC_SERVICE_NAME: 'application.com.test.gom.app.100632582.100632802',
  XPC_FLAGS: '0x0',
  ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined'
}
```
When I running electron:serve command, everything is fine:
`vue-cli-service electron:serve` - I got all variables from .env file
`vue-cli-service --mode=staging electron:serve`  - I got all variables from `.env.staging` file, 

**Expected behavior**
It is possible to set env variable for using inside built app.

**Environment:**
 - macOS Big Sur

**Comment by SuperKirik** [comment]
**This is my vue.config.js:**

`// vue.config.js

module.exports = {
  chainWebpack: config => {
    config
      .entry('app')
      .clear()
      .add('./src/renderer/main.js');
  },
  pluginOptions: {
    electronBuilder: {
      mainProcessFile: 'src/main/index.js', // main process entry file
      renderProcessFile: 'src/renderer/main.js', // render process entry file
      preload: { preload: 'src/main/preload.js' },
      // options placed here will be merged with default configuration and passed to electron-builder
      builderOptions: {
        "appId": "com.test.gom.app",
        "productName": "goM",
        "win": {
          "extraResources": [{
            "from": "platform/win/bin/golance-sniffer.exe",
            "to": "extraResources/golance-sniffer.exe"
          }, {
            "from": "platform/win/bin/MiniCap/MiniCap.exe",
            "to": "extraResources/MiniCap.exe"
          }],
          "icon": "platform/win/golance.ico"
        },
        "mac": {
          "extraResources": [{
            "from": "platform/osx/bin/sniffer/gom-action-capturer",
            "to": "extraResources/gom-action-capturer"
          }],
          "icon": "platform/osx/golance.icns"
        },
        "dmg": {
          "backgroundColor": "#435aae",
          "icon": "platform/osx/golance.icns",
          "contents": [
            {
              "x": 410,
              "y": 150,
              "type": "link",
              "path": "/Applications"
            },
            {
              "x": 130,
              "y": 150,
              "type": "file"
            }
          ]
        },
        "publish": {
          "provider": "s3",
          "bucket": "test-electron-gom",
          "acl": "public-read",
          "region": process.env.AWS_REGION
        }
      }
    }
  },
}
`

**Comment by SuperKirik** [comment]
If somebody will be interested in,
my problem was that I didn't know about this: 

> Note that only NODE_ENV, BASE_URL, and variables that start with VUE_APP_ will be statically embedded into the client bundle with webpack.DefinePlugin (from Vue Cli docs)

So when I changed the variable to `VUE_APP_IS_STAGING` - everything works fine.

Also what confused me was that logging `process.env` doesn't show my variables while logging `process.env.VUE_APP_IS_STAGING` shows the value (don't actually know why)

**Comment by megasanjay** [comment]
I believe the answer to your question is right there: `It is to avoid accidentally exposing a private key on the machine that could have the same name.`

It's just one of the things that you have to keep in mind when using Vue as your frontend framework.

**Comment by nklayman** [comment]
The reason it only shows when logging `process.env.VUE_APP_IS_STAGING` is because it isn't really setting an environment variable. Instead, it searches your codebase for `process.env.VUE_APP_IS_STAGING` and replaces it with the actual env var value at build time.
