### ISSUE TITLE
These dependencies were not found

### ISSUE THREAD

**Issue by rakakhrl** [nklayman/vue-cli-plugin-electron-builder#152]
**Describe the bug**
After installing knex and serving the app i got an error saying "These dependencies were not found"

**To Reproduce**

- Create a new project
- Install knex and mysql driver `npm install --save knex mysql`
- Run `npm run electron:serve`

**Expected behavior**
Electron app boot up and work normally

**Screenshots**
![gambar](https://user-images.githubusercontent.com/35162927/49340124-36bd2100-f66e-11e8-881a-bb8926386aac.png)

**Environment (please complete the following information):**
 - OS and version: Windows 10 
 - node version: 8.11.2
 - npm version: 6.4.1
 - vue-cli-plugin-electron-builder version : ^1.0.0-rc.9
 - electron version: ^2.0.0
 - other vue plugins used: [@vue/cli-plugin-babel, @vue/cli-plugin-eslint, @vue/eslint-config-prettier]
 - custom config for vcp-electron-builder: 

**Additional context**

**Comment by nklayman** [comment]
knex is looking for `mssql`, not `mysql` :man_facepalming:. Run `npm i mssql` to resolve this issue :+1:.

**Comment by rakakhrl** [comment]
I already install mssql and other db driver like pg and mysql2 but still got the same error. Before i create an issue here i create one in knex repo but they say its not knex related bug and told me i should ask here.

**Comment by nklayman** [comment]
After installing `mssql`, it works fine for me.

**Comment by nklayman** [comment]
Try with a fresh project.

**Comment by chen-xin** [comment]
I have same issue, tried [this solution](https://github.com/tgriesser/knex/issues/1128#issuecomment-316063450) but no luck. It seems the only solution is to install **all** modules in the *not found* list, though my app use sqlite3 only.

**Comment by nklayman** [comment]
@chen-xin Make sure to mark sqlite3 as an external: ```

**Comment by chen-xin** [comment]
Thank you @nklayman, Now I am luck! And you are so warmhearted mentioning the Yarn part, this really enlightened me.

**Comment by krisism** [comment]
I have recently stumbled upon the same issue, searched and tried everything I can find or think of -- without success.  I'm attempting to use this wonderful plugin, along with knex and sqlite3, the same as above.  I can't seem to get past this error without installing all the modules.

To recreate the exact scenario, here are the steps I've taken:

1. Install cli and add plugin
2. yarn add knex
3. yarn add sqlite3
4. in background.js, added knex with example code:
`var knex = require('knex')({
  client: 'sqlite3',
  connection: { filename: databaseLocation }
});`
5. create a vue.config.js file in the project root (beside package.json), added sqlite3 in externals and tried with (and without) nodeModulesPath.

Then when running 'yarn electron:serve' it still triggers the error.  Is there anything obvious I'm missing?  If anyone has advice, or ideas to try, I'm all ears!

**Comment by nklayman** [comment]
@krisism Have you tried adding `knex` as an external in `vue.config.js`?

**Comment by krisism** [comment]
That did the trick, thank you so much for that tip @nklayman .  You're a gentleman and a scholar.

**Comment by Yurematias** [comment]
i having the same issue trying but trying to using knex with mysql. i already tried to add knex and mysql as an external in vue.config.js but still not works.

![externals](https://user-images.githubusercontent.com/43214648/82136830-1e03e500-97e8-11ea-9335-3fe08d4c18c7.PNG)

**Comment by nklayman** [comment]
@Yurematias try adding `./node_modules` to the `nodeModulesPath` array.

**Comment by Yurematias** [comment]
I tried but still not works 
![print electron-builder](https://user-images.githubusercontent.com/43214648/82155332-84215400-984a-11ea-803f-fbbe5bfe283a.PNG)

**Comment by Yurematias** [comment]
The error was mine, i created the vue.config.js in the wrong place, but i moved for the root and followed your tip and resolved. thank you so much bro.

**Comment by AfterFinal** [comment]
![image](https://user-images.githubusercontent.com/20653456/212034320-bb59c498-c9eb-4a66-ad0a-b2233f63a535.png)
Please referto the issue below:
https://github.com/puppeteer/puppeteer/issues/9467

**Comment by AfterFinal** [comment]
[puppeteer-demo.zip](https://github.com/nklayman/vue-cli-plugin-electron-builder/files/10400254/puppeteer-demo.zip)
It's the project file, electron + vue3
