### ISSUE TITLE
nested node_modules folder disappears after packaging

### ISSUE THREAD

**Issue by gruen1988** [nklayman/vue-cli-plugin-electron-builder#1535]
after building the app, the nested node_modules folder disappears after packaging
most likely its because of the Version of the electron_builder. see this [stackoverflow](https://stackoverflow.com/questions/51573965/nested-node-modules-folder-disappears-after-packaging)

**To Reproduce**
install a dependencie with nested package.json. for example "electron-json-storage"
and then build the app with yarn electron:build

**Expected behavior**
it shouldnd disappear
app should work after building similar to how it works on development

**Environment (please complete the following information):**
win 10

**Comment by nklayman** [comment]
That's intentional, see #1522.
