### ISSUE TITLE
What does nodeIntegration actually do?

### ISSUE THREAD

**Issue by camhart** [nklayman/vue-cli-plugin-electron-builder#1548]
I understand what nodeIntegration within electron's BrowserWindow (renderers) does.  What's confusing me is what vue.config.js's pluginOptions.nodeIntegration actually does.

When I create BrowserWindow's I set nodeIntegration as true/false depending on that renderers use case.  But unfortunately when its set to false I get all sorts of hotreloading errors.  My app has some renderers that should use nodeIntegration, and some that shouldn't.  What should pluginOptions.nodeIntegration be set to?  Does it need to be more dynamic than a single t/f?  Like per entry instead?

**Comment by nklayman** [comment]
The pluginOptions config control's electron's nodeIntegration, but also configures the webpack bundle to work properly in the specified environment.
