### ISSUE TITLE
Changing protocol from app to something else

### ISSUE THREAD

**Issue by JohnRSim** [nklayman/vue-cli-plugin-electron-builder#155]
**Describe the bug**
When changing the protocol from app to something else - the correct index page & protocol load however all other assets attempt to load via app:// 

Here is a quick screenshot of a build with debug mode - win location shows the new protocol however you can see all assets are trying to load on app:// - if I change the protocol to app:// it works fine.
![image](https://user-images.githubusercontent.com/364208/49545032-62d9db80-f8d4-11e8-95ec-57a039a208b3.png)

**To Reproduce**
Change protocol to something else like this 
```
	protocol.registerStandardSchemes(['jsecoin'], { secure: true });

	if ((isDevelopment) || (process.env.IS_TEST)) {
		mainWindow.loadURL(process.env.WEBPACK_DEV_SERVER_URL);
		if (!process.env.IS_TEST) {
			mainWindow.webContents.openDevTools();
		}
	} else {
		createProtocol('jsecoin');
		mainWindow.loadURL('jsecoin://./index.html');
	}
```

**Expected behavior**
app protocol shouldnt be used if another is defined

**Environment (please complete the following information):**
 - OS and version: windows 10
 - node version: v10.6.0
 - npm version: 6.1.0
 - yarn version (if used): x
 - vue-cli-plugin-electron-builder version : "1.0.0-rc.9"
 - electron version: 3.0.10
 - other vue plugins used: n/a
 - custom config for vcp-electron-builder: n/a
 - (if possible) link to your repo: n/a

**Additional context**

**Comment by nklayman** [comment]
Set the `noAppProtocol` to `true` in pluginOptions:

```javascript
// vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      noAppProtocol: true
    }
  }
}
```
