### ISSUE TITLE
Sending commands from main process to the renderer vue process. 

### ISSUE THREAD

**Issue by megasanjay** [nklayman/vue-cli-plugin-electron-builder#1555]
Hi, Love the plugin. Just had a quick question regarding the communication between processes in this application. I couldn't find any info on this in the documentation, unfortunately. 

I want to hook into the auto-updater module and create a custom notification on the Vue side. Right now there is no way (that I see at least) to run push a message into the Vue application from background.js. I'm not sure if this is something the electron remote module can be used for or is there another way to trigger a UI element based on if the update was downloaded.

**Comment by klren0312** [comment]
like this?
https://github.com/klren0312/electronTemplate/blob/master/src/updater.js#L60
