### ISSUE TITLE
Lazy loading pages via router - incorrect path returned /assets/ on build

### ISSUE THREAD

**Issue by JohnRSim** [nklayman/vue-cli-plugin-electron-builder#156]
**Describe the bug**
Lazy loading appears to not work within the router after build?

**To Reproduce**
Within router file
```
//works
import test1 from '@/components/test1';

//fails
const test2= () => import(/* webpackChunkName: "test" */ '@/components/test2');
```

```
const router = new Router({
	mode: 'history',
	base: process.env.BASE_URL,
	routes: [
		{
			path: '/test1',
			name: 'test1 ',
			component: test1 ,
		},
		{
			path: '/test2',
			name: 'test2 ',
			component: test2 ,
		},
```

Standard import returns correct address like this
```
app://./assets/[path to file]
```

Lazy load returns full path to asset and fails
```
app://./C:/Users/... ... .. /app.asar/assets/[path to file]
```

**Expected behavior**
Expected correct path to be returned when accessing pages via lazy load approach
app://./assets/[path to file]

**Screenshots**
![image](https://user-images.githubusercontent.com/364208/49645994-adaf3c80-fa15-11e8-8db8-b4d11d9dea6b.png)

**Environment (please complete the following information):**
- OS and version: windows 10
- node version: v10.6.0
- npm version: 6.1.0
- yarn version (if used): x
- vue-cli-plugin-electron-builder version : "1.0.0-rc.9"
- electron version: 3.0.10
- other vue plugins used: n/a
- custom config for vcp-electron-builder: n/a
(- if possible) link to your repo: n/a

**Additional context**
n/a

**Comment by nklayman** [comment]
I set my `router.js` to look like this, and it works fine. I am on Linux (ubuntu), so that might cause a discrepancy.
```javascript
import Vue from 'vue';
import Router from 'vue-router';
import Home from './views/Home.vue';
const About = () => import(/* webpackChunkName: "about" */ '@/views/About');

Vue.use(Router);

export default new Router({
  mode: 'history',
  base: process.env.BASE_URL,
  routes: [
    {
      path: '/',
      name: 'home',
      component: Home
    },
    {
      path: '/about',
      name: 'about',
      component: About
    }
  ]
});
```

If there is something I need to change with it, let me know and I will try again.

**Comment by JohnRSim** [comment]
If you could try this repo:
https://github.com/JSEcoin/platform/tree/0.5.9-beta

Also I will try a clean base build on windows 10 confirm I can replicate and not something to do with my repo.

Thanks 👍

**Comment by JohnRSim** [comment]
Ok Hello-world base build works.

- But when I update and add my own protocol jsecoin then I'm able to replicate the issue. 
Or maybe something I added in my vue.config.js as I did this at the same time - 

You can see the image fails - with incorrect path
![image](https://user-images.githubusercontent.com/364208/49702407-aba0d580-fbef-11e8-9156-e112484eab5d.png)

**Comment by nklayman** [comment]
try setting the `noAppProtocol` to `true` in the plugin options.

**Comment by JohnRSim** [comment]
I think that's what is causing the problems -
noAppProtocol: true

if  enable that for app:// or jsecoin:// it starts giving me the issues.
if I comment out //noAppProtocol: true then app:// works fine but jsecoin:// starts gives me issues.

**Comment by nklayman** [comment]
try setting `baseUrl: 'jsecoin://./`` in `vue.config.js` (not plugin options).
