### ISSUE TITLE
add button to website

### ISSUE THREAD

**Issue by yehtut-indexzero** [nklayman/vue-cli-plugin-electron-builder#1569]
I have browserview and load a website. 
This is code in vue component.
`export default {`
 `name: "HelloWorld",`
  `props: {`
    `msg: String,`
  `},`
  `created() {`  
    `ipcRenderer.send("load-url","https://github.com/");`
  `},`
`};`
`</script>`

This is the code in background.js

`ipcMain.on("load-url", (event, arg) => {`
	`browserview = new BrowserView();`
	`win.addBrowserView(browserview);`
	`const contentBounds = win.getContentBounds();`
	`browserview.setBounds({`
		`x: 0,`
		`y: 0,`
		`width: contentBounds.width,`
		`height: contentBounds.height,`
	`});`
	`browserview.setAutoResize({ width: true, height: true });`
	`browserview.webContents.loadURL(arg);`
});`

what I want to do is to add a button on github website (example)
![Capture](https://user-images.githubusercontent.com/8586647/138236372-02c703f7-a311-4772-bcb3-dc297cf07d56.JPG)
. 

Can anyone help me to give any suggestion?

**Comment by klren0312** [comment]
why not use iframe in vue page and position a button, then use browserwindow open this vue page

**Comment by nklayman** [comment]
Sorry for the delayed response, had to take a break from open source to focus on school.

Your question doesn't seem to be specific to this plugin, just about electron. I'd suggest asking for help on a forum somewhere if the above suggestion doesn't work. Thanks for trying to help @klren0312.
