### ISSUE TITLE
DeprecationWarning with electron@15.3.0

### ISSUE THREAD

**Issue by WangJM001** [nklayman/vue-cli-plugin-electron-builder#1573]
**Describe the bug**
DeprecationWarning with electron@15.3.0
![image](https://user-images.githubusercontent.com/20501316/138996546-1cce76d8-f871-469b-b2af-c30fcada21b2.png)

**To Reproduce**
`npm run electron:serve`
my settings
![image](https://user-images.githubusercontent.com/20501316/138997280-2421e435-8811-423b-8553-dd70d507732c.png)

**Expected behavior**
no warning

**Screenshots**
![image](https://user-images.githubusercontent.com/20501316/138997419-587c1b1d-6df5-4769-8f93-c1fbb31c87a2.png)

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 
 - terminal output from running `vue info`:

**Additional context**

**Comment by WangJM001** [comment]
> > > try to change this in `package.json` ![image](https://user-images.githubusercontent.com/10903843/139007470-0bfd9602-5dd5-4e1b-b955-9b2f894c8701.png)
> > > run electron:build will be error after change this to index.js
> 
> `main/index.js`?

我看了下，源码里写死了生成入口文件的名称了,换成main/index.js后打包就会报错了

**Comment by nklayman** [comment]
This should be fixed in v3 alpha (see https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v3.0.0-alpha.0). Give it a try and let me know if it takes care of the issue.
