### ISSUE TITLE
localStorage not persisting?

### ISSUE THREAD

**Issue by bbeng89** [nklayman/vue-cli-plugin-electron-builder#1577]
My apologies if this is the wrong place for this question, I'm happy to move it wherever support requests are supposed to go. I'm hoping it's a simple issue though.

In my renderer I'm using localStorage to store a simple key/value and I can see it gets added in the devtools and everything works great. But when I close the app and restart it, the values are all wiped out. Is there something I need to do to allow the data in localStorage to persist?

Thanks in advance!

-Blake

**Comment by knaos** [comment]
You are not alone. I am experiencing this same problem. The only way to save the local storage is by closing the application gracefully.
