### ISSUE TITLE
Module parse failed: Unexpected character '�'    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

### ISSUE THREAD

**Issue by AstorLee-tao** [nklayman/vue-cli-plugin-electron-builder#1582]
I've introduced `ssh2-sftp-client` in `background.js` 
![image](https://user-images.githubusercontent.com/70565665/141044161-9d23e030-80ac-40d0-a82a-1a4fbc05f3b1.png)

Error reported at runtime
![image](https://user-images.githubusercontent.com/70565665/141044301-5bbe21ba-23a0-4aee-87ae-d8e41e340eb3.png)

This seems to be because `node-loader` doesn't work,I then added the following configuration.
![image](https://user-images.githubusercontent.com/70565665/141044493-e7a294fc-077e-423e-8fe2-88900823bf4e.png)
Finally, another error was reported
![image](https://user-images.githubusercontent.com/70565665/141044681-85f975cb-39f9-4a4d-a913-1110c45995e1.png)

And then I don't know what to do

This is my `package.json`
![image](https://user-images.githubusercontent.com/70565665/141044822-4dde6e10-999d-4a5e-aee8-93c28a2a12fb.png)

**Comment by klren0312** [comment]
try it ?
```js
configureWebpack: {
    externals: {
      'ssh2-sftp-client: 'require("ssh2-sftp-client")'
    }
}
```

**Comment by AstorLee-tao** [comment]
> 尝试一下 ？
> 
> ```js
> configureWebpack : { 
>     externals : { 
>       'ssh2-sftp-client: ' require ( "ssh2-sftp-client" ) '
>     }
> }
> ```

**Comment by AstorLee-tao** [comment]
> 尝试一下 ？
> 
> ```js
> configureWebpack : { 
>     externals : { 
>       'ssh2-sftp-client: ' require ( "ssh2-sftp-client" ) '
>     }
> }
> ```

thank you for your help

I gave it a try
![image](https://user-images.githubusercontent.com/70565665/141047285-aff6c289-2cb5-4fcc-bf01-f14d15828a63.png)

But it was still an error
![image](https://user-images.githubusercontent.com/70565665/141047366-b1357a5c-e83d-4ee6-bf27-89d97cf3cd2c.png)

**Comment by AstorLee-tao** [comment]
跪求大佬帮帮忙啊

**Comment by AstorLee-tao** [comment]
Although it can be introduced in vue's `main.js`, it does not solve my problem, after all, introducing `ssh2-sFTP-client` in vue's `main.js` will not work in production. I really hope there is a god can help me, let me solve this problem.

**Comment by klren0312** [comment]
@AstorLee-tao 
It works in `background.js`.  I do not know what is your problem, you can upload your example
![1636601255(1)](https://user-images.githubusercontent.com/10903843/141232094-c8ecb9e5-9dd3-4eba-8be1-1527dafbe90c.png)
![1636601323(1)](https://user-images.githubusercontent.com/10903843/141232165-0106ef84-34e7-4596-b307-a0256ed3c1f4.png)

**Comment by AstorLee-tao** [comment]
@klren0312 
Hello, thank you for continuing to follow my questions.
This is the compressed package of my example, I hope you can help me have a look.
[hello-electron.zip](https://github.com/nklayman/vue-cli-plugin-electron-builder/files/7518084/hello-electron.zip)

This is my version of `NodeJS`.
![image](https://user-images.githubusercontent.com/70565665/141245442-4ac5ea83-b16c-4b89-822f-6a88d1dfccc4.png)

This is my version of `Webpack`.
![image](https://user-images.githubusercontent.com/70565665/141245570-5a5ea0ca-40de-407c-a7f8-a2082d7eaeea.png)

**Comment by klren0312** [comment]
so why you add this ???
![image](https://user-images.githubusercontent.com/10903843/141249622-ce97f451-009d-4a9a-a625-f93c50101c3a.png)
delete this, then will work
![image](https://user-images.githubusercontent.com/10903843/141249734-c8f3d142-7e72-4205-a752-72fc74516f41.png)

# waste our time

**Comment by AstorLee-tao** [comment]
This was originally a comment, I accidentally put it out, I'm now commenting it, but the code still returns an error![image](https://user-images.githubusercontent.com/70565665/141250641-05d4e37c-c166-40de-ab45-19bdbd123ab7.png)
![image](https://user-images.githubusercontent.com/70565665/141250993-aee0e062-cd3b-4089-a3f6-7a768d8d53f5.png)
I don't know why

**Comment by AstorLee-tao** [comment]
I wonder if this has something to do with this?
![image](https://user-images.githubusercontent.com/70565665/141251150-40dfbfea-e442-479b-8cfa-50533ba7b312.png)

**Comment by klren0312** [comment]
delete your node_modules, reinstall

**Comment by AstorLee-tao** [comment]
@klren0312 
I see. Thank you.

**Comment by nklayman** [comment]
Sorry for the delayed response, had to take a break from open source to focus on school.

Have you tried marking `ssh2-sftp-client` as an external through the plugin config? That will likely fix your issue. To do so, add this to your `vue.config.js`:

```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['ssh2-sftp-client']
    }
  }
}
```

**Comment by redstone78** [comment]
We had the same issue with our serverless bundle, but we updated to add the IgnorePackages and then got that sshcrypto.node issue. That was a webpack issue, we just added this to our webpack.config.js

module.exports = {
  target: 'node',
  mode: 'none',
  resolve: {
    plugins: [new TsconfigPathsPlugin()]
  },
  **externals: {'ssh2-sftp-client': 'require("ssh2-sftp-client")'}**
};
