### ISSUE TITLE
Support for electron 14 and 15

### ISSUE THREAD

**Issue by ylieder** [nklayman/vue-cli-plugin-electron-builder#1583]
Is this project still maintained? Current electron major version is 15, but due cli electron builder supports only 13. Is it planned to support newer versions of electron?

**Comment by klren0312** [comment]
Try to change the `electron` version to `^15.0.0` in `package.json`, and reinstall dependencies
![1636594259(1)](https://user-images.githubusercontent.com/10903843/141220838-51713142-8e23-42a2-82f1-6687ee8fdb98.png)

**Comment by nklayman** [comment]
Sorry for the delayed response, had to take a break from open source to focus on school.

You can manually upgrade the electron version and it should work without issue. I'm working on a new version of this plugin that will support the latest electron versions, hoping to get it out over the next week.
