### ISSUE TITLE
Failed to register a ServiceWorker after build

### ISSUE THREAD

**Issue by shadowstriker15** [nklayman/vue-cli-plugin-electron-builder#1584]
**Describe the bug**
Whenever I open up the application after it has been built I am getting an error that it failed to register a ServiceWorker.

**To Reproduce**
The project I am currently in is using Typescript and Vue Router. Here are some relevant code snippets:

index.ts
`
const router = new VueRouter({
  mode: process.env.IS_ELECTRON ? 'hash' : 'history',
  base: process.env.BASE_URL,
  routes,
});
`

background.ts (this has not been modified since the boilerplate project)
`
  if (process.env.WEBPACK_DEV_SERVER_URL) {
    // Load the url of the dev server if in development mode
    await win.loadURL(process.env.WEBPACK_DEV_SERVER_URL as string);
    if (!process.env.IS_TEST) win.webContents.openDevTools();
  } else {
    createProtocol("app");
    // Load the index.html when not in development
    win.loadURL("app://./index.html");
  }
`

**Expected behavior**
The main webpage to load (which it is) but it is associated with this error.

**Screenshots**
![image](https://user-images.githubusercontent.com/1342626/141244065-3582de23-92c3-4625-9c4b-abf8e846da99.png)

**Environment (please complete the following information):**
Output from running vue info
`
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 7.20.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.44)
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.0.6
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.13
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.13
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.13
    @vue/cli-plugin-eslint: ^3.1.1 => 3.12.1
    @vue/cli-plugin-pwa: ~4.5.0 => 4.5.13
    @vue/cli-plugin-router: ~4.5.0 => 4.5.13
    @vue/cli-plugin-typescript: ~4.5.0 => 4.5.13
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.13
    @vue/cli-service: ^4.5.13 => 4.5.13
    @vue/cli-shared-utils:  4.5.13 (3.12.1)
    @vue/component-compiler-utils:  3.2.2
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0
    @vue/eslint-config-typescript: ^7.0.0 => 7.0.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/web-component-wrapper:  1.3.0
    eslint-plugin-vue: ^6.2.2 => 6.2.2 (4.7.1)
    typescript: ~4.1.5 => 4.1.6
    vue: ^2.6.11 => 2.6.14
    vue-async-computed: ^3.9.0 => 3.9.0
    vue-cli-plugin-electron-builder: ~2.0.0 => 2.0.0
    vue-cli-plugin-vuetify: ~2.4.1 => 2.4.1
    vue-loader:  15.9.7 (16.3.1)
    vue-router: ^3.2.0 => 3.5.2
    vue-style-loader:  4.1.3
    vue-template-compiler: ^2.6.11 => 2.6.14
    vue-template-es2015-compiler:  1.9.1
    vuetify: ^2.4.0 => 2.5.6
    vuetify-loader: ^1.7.0 => 1.7.2
    vuex: ^3.4.0 => 3.6.2
  npmGlobalPackages:
    @vue/cli: Not Found
`

**Comment by dariaedicas** [comment]
Hi! I have the same issue @shadowstriker15 have you ever found a solution?

**Comment by shadowstriker15** [comment]
> Hi! I have the same issue @shadowstriker15 have you ever found a solution?

No I did not, though this doesn’t appear to cause any other unexpected outcomes that I have seen.

**Comment by nklayman** [comment]
Sorry for the delayed response, had to take a break from open source to focus on school.

I think you can solve your issue by adding `allowServiceWorkers: true` in the `protocol.registerSchemesAsPrivileged` call in your main process file. See [the Electron docs](https://www.electronjs.org/docs/latest/api/protocol#protocolregisterschemesasprivilegedcustomschemes) for more details.

```js
protocol.registerSchemesAsPrivileged([
  { scheme: 'app', privileges: { allowServiceWorkers: true } }
])
```

**Comment by shadowstriker15** [comment]
@nklayman Great, that worked. Thank you!
