### ISSUE TITLE
window.open  setWindowOpenHandler frameName   Why is frameName equal to empty

### ISSUE THREAD

**Issue by seefl** [nklayman/vue-cli-plugin-electron-builder#1587]
window.open('https://github.com','github')

//  The actual result frameName is equal to github
//  But frameName is equal to empty

win.webContents.setWindowOpenHandler(({ url,frameName }) => {
    if(frameName == 'github'){   //  frameName is equal to empty
      return {
        action: "allow",
        overrideBrowserWindowOptions: {
          module:true,
          width,
          height,
        },
      };
    }else {  
      shell.openExternal(url);
    }
    return { action: 'deny' }
  });

**Comment by nklayman** [comment]
This seems to be an issue with Electron, not this plugin. If it only fails with this plugin, let me know and I'll look into it more.
