### ISSUE TITLE
Spectron is getting deprecated, migrate to playwright

### ISSUE THREAD

**Issue by MatthijsBurgh** [nklayman/vue-cli-plugin-electron-builder#1590]
Spectron is getting deprecated, https://github.com/electron-userland/spectron/issues/896 and https://github.com/electron-userland/spectron/issues/1045. [Playwright](https://github.com/microsoft/playwright) is the most common solution mentioned in these issues.

It would be nice if this would be integrated in here as a replacement for the current spectron tools.

**Comment by nklayman** [comment]
Sorry for the delayed response, had to take a break from open source to focus on school.

I'm working on a v3 for this plugin that will update electron, webpack, and migrate to playwright. Hoping to get an alpha out over the next week, keep an eye out on the releases tab.

**Comment by MatthijsBurgh** [comment]
@nklayman Thanks for the great work. Let me know when you need any help for testing, etc..

**Comment by nklayman** [comment]
V3 alpha is here: https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v3.0.0-alpha.0! Please give it a try and let me know how it goes.
