### ISSUE TITLE
Build process failing (presumably) due to invalid 'main' field

### ISSUE THREAD

**Issue by daan33** [nklayman/vue-cli-plugin-electron-builder#1591]
**Describe the bug**
The build process fails for me using Vue-CLI v5 and Electron v16 without any errors.  When starting the dev environment, there are no errors and the electron app runs fine, other than showing one deprecation warning:

```[DEP0128] DeprecationWarning: Invalid 'main' field in '[path]/package.json' of 'src/background.ts'. Please either fix that or report it to the module author```

This seems to be related to #1573.  Unsure whether the builder incorrectly thinks the deprecation warning is an error, or whether something else is causing the build to fail.  I'm also unable to fix the deprecation warning, it just won't go away regardless of how valid my `'main'` field in `package.json` is.

**To Reproduce**
Use `npm run electron:build` on any app that uses Electron v16 and the build process will fail without warning.  The `npm run electron` command starts the dev server fine, however.

**Expected behavior**
The electron app should build or display what's causing the error.

**Screenshots**
When using `npm run electron`:
![image](https://user-images.githubusercontent.com/47603391/142073065-75f4ac2f-2d2a-44bd-91a4-c000f609e49e.png)

When using `npm run electron:build`:
![image](https://user-images.githubusercontent.com/47603391/142073130-da3aff4f-64b7-4f88-91dd-8596e25238c8.png)

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: -
 - (if possible) link to your repo: -
 - terminal output from running `vue info`:
```
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.1.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 96.0.4664.45
    Edge: Spartan (44.22000.120.0), Chromium (95.0.1020.53)
  npmPackages:
    @vue-leaflet/vue-leaflet: ^0.6.1 => 0.6.1
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.1.1
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  5.0.0-rc.0
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  5.0.0-rc.0
    @vue/cli-plugin-babel: 5.0.0-beta.3 => 5.0.0-beta.3
    @vue/cli-plugin-eslint: 5.0.0-beta.3 => 5.0.0-beta.3
    @vue/cli-plugin-router: 5.0.0-beta.3 => 5.0.0-beta.3
    @vue/cli-plugin-typescript: 5.0.0-beta.3 => 5.0.0-beta.3
    @vue/cli-plugin-vuex: 5.0.0-beta.3 => 5.0.0-beta.3
    @vue/cli-service: 5.0.0-beta.3 => 5.0.0-beta.3
    @vue/cli-shared-utils:  4.5.15 (5.0.0-rc.0)
    @vue/compiler-core:  3.2.22
    @vue/compiler-dom:  3.2.22
    @vue/compiler-sfc: ^3.2.22 => 3.2.22
    @vue/compiler-ssr:  3.2.22
    @vue/component-compiler-utils:  3.3.0
    @vue/devtools-api:  6.0.0-beta.20.1
    @vue/eslint-config-typescript: ^9.1.0 => 9.1.0
    @vue/reactivity:  3.2.22
    @vue/ref-transform:  3.2.22
    @vue/runtime-core:  3.2.22
    @vue/runtime-dom:  3.2.22
    @vue/server-renderer:  3.2.22
    @vue/shared:  3.2.22
    @vue/web-component-wrapper:  1.3.0
    eslint-plugin-vue: ^8.0.3 => 8.0.3
    typescript: ^4.4.4 => 4.4.4
    vue: ^3.2.22 => 3.2.22
    vue-cli-plugin-electron-builder: ^2.1.1 => 2.1.1
    vue-eslint-parser:  8.0.1
    vue-hot-reload-api:  2.3.4
    vue-loader:  16.8.3 (15.9.8)
    vue-router: ^4.0.12 => 4.0.12
    vue-style-loader:  4.1.3
    vue-template-es2015-compiler:  1.9.1
    vuex: ^4.0.2 => 4.0.2
  npmGlobalPackages:
    @vue/cli: Not Found
```

**Comment by nklayman** [comment]
V3 alpha no longer requires the `main` field to be set so it should take care of your issue. Give it a try and let me know if it fixes it.

https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v3.0.0-alpha.0

**Comment by mpwanyi256** [comment]
The other thing I have also noticed is that, if your Vue router baseUrl path is not `/` the build is also screwed. So you would need to adjust the background file to make sure it points to the baseUrl
