### ISSUE TITLE
how to install electron 16

### ISSUE THREAD

**Issue by jiuyuehe** [nklayman/vue-cli-plugin-electron-builder#1595]
**Is your feature request related to a problem? Please describe.**
the electron update to 16,but the only choose 11~13

**Comment by klren0312** [comment]
try to change `package.json`

**Comment by nklayman** [comment]
Sorry for the delayed response, had to take a break from open source to focus on school.

For now, just choose 13 and then upgrade it manually in your package.json. I'm working on a new version of the plugin that will have support for the latest versions by default.

**Comment by ypicard** [comment]
Hi @nklayman , do you have information related to your previous message here?
