### ISSUE TITLE
Not support .mjs

### ISSUE THREAD

**Issue by starhu521** [nklayman/vue-cli-plugin-electron-builder#1596]
**Describe the bug**
When build main process, error
![image](https://user-images.githubusercontent.com/23275495/142584245-09b13ae4-5eb3-427e-bc47-0b948e14cb84.png)

And I did like others，add the config：
chainWebpackMainProcess: (config) => {
          config.module
            .rule('mjs$')
            .test(/\.mjs$/)
            .include
            .add(/node_modules/)
            .end()
            .type('javascript/auto');

to both vue.config.js and builderOptions.

**To Reproduce**
I'm using node-ssh repo.

**Environment (please complete the following information):**
"electron": "^13.0.0",
"vue-cli-plugin-electron-builder": "~2.1.1",

**Comment by nklayman** [comment]
It looks like you are trying to import a class that isn't exported from that module, which isn't an issue with this plugin. It's hard to tell because you provided so little information, please share the code that imports the module if you want more help.
