### ISSUE TITLE
No native build was found for platform=win32, please help!

### ISSUE THREAD

**Issue by shuwenkai** [nklayman/vue-cli-plugin-electron-builder#1597]
In my project, I use vue+electron, but I want to use C++ dll file,so I import ffi-napi;
after run `npm run electron:build`, i got this mistake;
![image](https://user-images.githubusercontent.com/42637806/142591262-869c4a03-548f-4499-9365-60e7daf7df40.png)
now development environment is normal, but product environment this mistake still exist, so i need help.

this is my `vue.config.js`

`
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true,
      // 因为这两个模块中包含原生 C代码，所以要在运行的时候再获取，而不是被webpack打包到bundle中
      // 否则开发环境会出现 No native build was found for platform=win32  , 'ref-napi'
      externals: ['ffi-napi', 'ref-napi'],
      nodeGypRebuild: true,
      asar: true,
      builderOptions: {
        extraResources: {
          // 拷贝静态文件到指定位置,否则打包之后出现找不到资源的问题.将整个resources目录拷贝到 发布的根目录下
          from: 'resources/',
          to: './'
        }
      }
    }
  }
`

**Comment by nklayman** [comment]
I can't tell what your issue is without more information. Please open a new issue that follows the bug report template, and ideally include a repo that demonstrates the error.
