### ISSUE TITLE
Deprecation warning (Buffer) on clean startup

### ISSUE THREAD

**Issue by paulbdavis** [nklayman/vue-cli-plugin-electron-builder#160]
**Describe the bug**
Usage of deprecated feature.

```
(node:18179) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**To Reproduce**
```sh
vue create test-project
cd test-project 
vue add electron-builder
yarn electron:serve 
```

The deprecation warning shows up in the terminal after the application starts.

**Expected behavior**
No warnings or errors on a "clean" startup

**Environment (please complete the following information):**
 - OS and version: Linux
 - node version: 8.12.0
 - npm version: 6.4.1
 - yarn version (if used): 1.12.3 
 - vue-cli-plugin-electron-builder version : 1.0.0-rc.9
 - electron version: 3.0.11
 - other vue plugins used: babel, eslint
 - custom config for vcp-electron-builder: None

**Additional context**

Config used to create the vue project

```json
    "electron-setup": {
      "useConfigFiles": false,
      "plugins": {
        "@vue/cli-plugin-babel": {},
        "@vue/cli-plugin-eslint": {
          "config": "standard",
          "lintOn": [
            "save",
            "commit"
          ]
        }
      },
      "router": true,
      "routerHistoryMode": false,
      "vuex": true
    }
```

**Comment by kl3sk** [comment]
I have the same message except I'm under Windows 10.

**Comment by nklayman** [comment]
If you get the stack trace from the warning, it is from [compress-commons](https://www.npmjs.com/package/compress-commons). Open an issue there instead.
https://github.com/archiverjs/node-compress-commons/blob/f975390bc96d0c789f47d684e491a55e1a672458/lib/archivers/zip/constants.js#L11
