### ISSUE TITLE
Install permission denied

### ISSUE THREAD

**Issue by KaloSora** [nklayman/vue-cli-plugin-electron-builder#1601]
System : Mac Monterey

An error occured while execute command `vue add electron-builder`

![iShot2021-11-23 11 12 27](https://user-images.githubusercontent.com/35422660/142966098-b9ff7b3e-6348-46ff-9cf1-4a4055bd8e81.png)

**Comment by klren0312** [comment]
try to add `sudo` ?

**Comment by KaloSora** [comment]
yep，but it didn't work.

**Comment by nklayman** [comment]
Sorry for the delayed response, had to take a break from open source to focus on school.

Unfortunately, I don't own a Mac and have no idea as to what could cause this or how to solve it. For now, can you try installing another plugin and see if you get the same error?
