### ISSUE TITLE
任务栏右键菜单里的icon在哪里修改？

### ISSUE THREAD

**Issue by caifu23** [nklayman/vue-cli-plugin-electron-builder#1614]
**Describe the bug**

**To Reproduce**

**Expected behavior**
希望electron打包后的桌面端，在任务栏右键的时候，里边的icon可以修改到.
- 修改了vue.config.js里，pluginOptions.electronBuilder.builderOptions.win.icon  这个配置，但是打包后，桌面快捷键图标+任务栏右键菜单里的图标，都没有修改到。
- 修改了vue.config.js里，pluginOptions.electronBuilder.builderOptions.icon  这个配置，桌面快捷键图标修改到了，但是任务栏右键菜单里的图标，还是没改到。

**Screenshots**
![This is an image](https://s3.bmp.ovh/imgs/2021/12/0b5b5fe703092625.png)

**Environment (please complete the following information):**
 - vue.config.js里icon的配置如下 - 
```
const TerserPlugin = require("terser-webpack-plugin");
module.exports = {
  lintOnSave: false,
  publicPath: !process.env.IS_ELECTRON ? './' : '/',
  pluginOptions: {
    electronBuilder: {
      preload: 'src/preload.js',
      mainProcessFile: 'src/main/index.js',
      builderOptions: {
          "productName": 'Creation',
          "appId": "com.example.yourapp",
          "icon": './public/app.ico', //桌面快捷键
          "win": {
              "icon": './public/app.ico',
              "target": [
              "nsis",
              "zip"
              ]
          },
          "nsis": {
              "oneClick": false, //是否一键安装
              "perMachine": true,
              "allowToChangeInstallationDirectory": true, // 容许修改安装目录
              "createDesktopShortcut": true, //是否创建桌面快捷方式
              "createStartMenuShortcut": true, //是否要创建开始菜单快捷方式
              "shortcutName": "FeiDao", //将用于所有快捷方式的名称。默认应用程序名称
              "installerIcon": "./public/app.ico", //安装程序图标的路径
              "uninstallerIcon": "./public/app.ico", //卸载程序图标的路径
              "installerHeaderIcon": "./public/app.ico", //仅限一键式安装程序。标题图标（进度条上方）
          },
          mac: {
            "icon": './public/app.png'
          }
      }
    },
  }
};

```

**Additional context**

**Comment by klren0312** [comment]
You can see this #1562

**Comment by caifu23** [comment]
Thanks, I have read the linked document but still don't know how to modify it in Window system. 
![icon](https://s3.bmp.ovh/imgs/2021/12/369b04bbbc5d4541.png)
![This is an image](https://s3.bmp.ovh/imgs/2021/12/6226c747f3d4d28d.png)

**Comment by klren0312** [comment]
try it 
https://github.com/klren0312/electronTemplate/blob/master/src/background.js#L76

**Comment by caifu23** [comment]
``
win = new BrowserWindow({
    ......
    // eslint-disable-next-line no-undef
    icon: path.resolve(__static, 'logo.png')
  })
```
This is what sets the logo in the upper left corner of the window。
The following image is displayed，1、2、4 is true；3、5 is false。So how to modify 3 and 5 
[img](https://s3.bmp.ovh/imgs/2021/12/2f6b296f9b03faf3.png)

**Comment by caifu23** [comment]
I ran the template code and clone from https://github.com/klren0312/electronTemplate.git
![](https://s3.bmp.ovh/imgs/2021/12/db4b0ae7fc8d55ac.png)

**Comment by klren0312** [comment]
build it please.  electron builder is use to build

**Comment by klren0312** [comment]
![image](https://user-images.githubusercontent.com/10903843/145952608-3c8cc8eb-a8f1-428d-900b-88672794a098.png)

**Comment by caifu23** [comment]
I ran the template code and clone from https://github.com/klren0312/electronTemplate.git
I ran the script `electron:build` in electronTemplate,  and then packaged software is ok。
Let me first look at the configuration in the template

**Comment by nklayman** [comment]
@caifu23 is the issue solved now? If so, please close this. Thanks for the help @klren0312.
