### ISSUE TITLE
Why latest-*.yml files aren't created when building app?

### ISSUE THREAD

**Issue by kilgaloon** [nklayman/vue-cli-plugin-electron-builder#1617]
**Describe the bug**
When I build the app with electron-builder there are files generated that are used for auto-updater feature. Those are `latest-*.yml`.

**To Reproduce**
run the following command: npm run electron:build

**Expected behavior**
I expect to see same behaviour like electron-builder

edit:
Also may i added that `app-update.yml` file is not created.

Here is my `vue.config.js`:

```
pluginOptions: {
    electronBuilder: {
      publish: [ 
        {
          provider: "generic",
          url: "https://localhost:9090/v1/envot/",
        }
      ],
      customFileProtocol: 'envot://./',
      appId: "io.envot.app",
      productName: "envot",
      linux: {
        target: "AppImage",
      },
      appImage: {
        artifactName: "envot-${channel}"
      },
      win: {
        target: "nsis",
        verifyUpdateCodeSignature: false
      },
      nsis: {
        createDesktopShortcut: "always",
      }
    }
  }
```

**Comment by nklayman** [comment]
It seems that you aren't nesting your electron-builder configuration properly. Any configuration related to electron-builder, not this plugin (such as `publish` or `appId`), should go in `pluginOptions.electronBuilder.builderOptions`. Let me know if your issue still occurs after changing that.
