### ISSUE TITLE
Bundling a splash screen into production app

### ISSUE THREAD

**Issue by megasanjay** [nklayman/vue-cli-plugin-electron-builder#1621]
Just wanted to see if anyone has had any luck bundling additional HTML files into the app. I have a splash screen that I show while the main app is loading in.  However, it doesn't seem to be picking up this file in the bundle for some reason. 

My splash screen is in the src folder alongside main.js. My files key in vue.config is:
```js
files: [ "**/*", "./src/splash-screen.html", ".splash-screen.html"],
```
I added both but neither seems to work.  I also added the splash-screen.html file manually to the dist_electron before building but that doesn't help either.

Any tips are welcome. Thanks :)

**Comment by nklayman** [comment]
Try placing the splash screen file in your `public` directory, it should be included automatically that way. See the [docs on static assets](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#handling-static-assets) for more details. If you run into issues, share the code in your main process file that configures the splashscreen so I can help more.
