### ISSUE TITLE
How to add buildResources?

### ISSUE THREAD

**Issue by chenweiyj** [nklayman/vue-cli-plugin-electron-builder#163]
**Is your feature request related to a problem? Please describe.**
I want to add logo icons to my app, electron-builder says to use buildResources directory, but how?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nklayman** [comment]
Place all electron-builder configuration in the electronBuilder section of the plug-in config, see [the docs](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#configuring-electron-builder) for more info.

**Comment by nklayman** [comment]
Just place all the icons in a folder called "build"

**Comment by nklayman** [comment]
Icon.ico, icon.icns, and a folder called icons should all be in the build folder. The icons folder should contain a bunch of differently sized icons, like 32x32.png and 64x54.png.
