### ISSUE TITLE
remains blank after compiling

### ISSUE THREAD

**Issue by gusgeek** [nklayman/vue-cli-plugin-electron-builder#1630]
**Describe the bug**
After compiling the application, installing it and running it on windows, it remains blank.
Try 2.0 and 3.0-A
**To Reproduce**
After compiling the application, installing it and running it .

**Screenshots**
![image](https://user-images.githubusercontent.com/38817071/148144861-e16aa57e-434a-49a1-bfc9-e68899a977b7.png)

**Comment by nklayman** [comment]
Please provide a repo that demonstrates the error. If I can't reproduce the issue I can't help you.
