### ISSUE TITLE
hi, do you know how to use serialport with vite?

### ISSUE THREAD

**Issue by Minori-ty** [nklayman/vue-cli-plugin-electron-builder#1631]
there is the project : https://github.com/cawa-93/vite-electron-builder.git
 Or create a vite-plugin for vite, thanks.
there is my demo with vue-cli:
https://github.com/Minori-ty/vue-cli-vue3-electron-serialport.git

**Comment by nklayman** [comment]
I'm not familiar with Vite at all so I don't know how to help you, although you will probably have to externalize serialport, maybe using this plugin: https://github.com/crcong/vite-plugin-externals. I may create an Electron plugin for Vite if I get the time, but I'm focusing on v3 of this plugin for now.

**Comment by Minori-ty** [comment]
> 

Thank you for your kind help! I will try it

**Comment by Minori-ty** [comment]
> I'm not familiar with Vite at all so I don't know how to help you, although you will probably have to externalize serialport, maybe using this plugin: https://github.com/crcong/vite-plugin-externals. I may create an Electron plugin for Vite if I get the time, but I'm focusing on v3 of this plugin for now.

But I also hava a confused，why it need to set externals？Does it have any effect? And unfortunatelly, it also don't work : (
It shows native code
![image](https://user-images.githubusercontent.com/79521943/148477135-b621f953-0e10-4bf0-bc58-5446263a5549.png)

**Comment by klren0312** [comment]
you can give the small template

**Comment by nklayman** [comment]
`f () { [native code] }` is what should be displayed afaik. Did you try calling the function?

**Comment by Minori-ty** [comment]
> 

Thanks for your attention again ! And I have resolved the problem. I thought `f () { [native code] }` it should be a  clear function such as `f(){ list() {...} open(){...} ...}` just like use in nodejs, and I calling the function  in renderer/vue  as  `import serialport from 'serialport '   serialport.list()` and it said that `Cannot read properties of undefined (reading 'list')`.

Finally, I use the electron contextBridge API to expose serialport ,and it work! 
Here is the vite-electron-serialport demo:
https://github.com/Minori-ty/vite-electron-serialport

you can see the method I use in packages/preload/src/index.ts

**Comment by nklayman** [comment]
Glad you could figure it out! That's also much more secure as it doesn't require nodeIntegration to be enabled.

**Comment by RDHB** [comment]
@Minori-ty  What were the changes you made in preload/src/index.ts file?
Because I have the same problem

**Comment by Minori-ty** [comment]
> @Minori-ty What were the changes you made in preload/src/index.ts file? Because I have the same problem

Here are the demo, https://github.com/Bread-etc/electron-vite-serialport
