### ISSUE TITLE
Cross Platform Build

### ISSUE THREAD

**Issue by KlausSchaefers** [nklayman/vue-cli-plugin-electron-builder#1633]
**Describe the bug**
I am building my project with the 'npm run electron:build' command. This only creates Mac installation files, but now windows or linux executables. What do I have to change?

**To Reproduce**
Create an default project on MAC and run 'npm run electron:build'

**Expected behavior**
Mac, Windows & Linux executables are build

**Screenshots**
None

**Environment (please complete the following information):**
 - MacOs

**Additional context**

**Comment by nklayman** [comment]
Try running `npm run electron:build -- --win --linux` to build for other platforms. There are some required dependencies, see https://www.electron.build/multi-platform-build for details.

**Comment by KlausSchaefers** [comment]
Thanks for the help and the awesome plugin!!!
