### ISSUE TITLE
MacOS createprotocol report error when url is "app://./index.html/#/live?wndName=liveWindow"

### ISSUE THREAD

**Issue by plumhly** [nklayman/vue-cli-plugin-electron-builder#1635]
**Describe the bug**
Window is OK, but MacOS report error: index.html/ is not a directory

createprotocol report error when url is "app://./index.html/#/live?wndName=liveWindow"。

maybe my url is invalid
**To Reproduce**
1. createprotocol("app");
2. set url = "app://./index.html/#/live?wndName=liveWindow"

**Expected behavior**
pathname is /index.html not /index.html/

**Environment (please complete the following information):**
vue-cli-plugin-electron-builder :2.1.1

**Comment by nklayman** [comment]
Try using `app://./index.html#/live?wndName=liveWindow` as your url. I think this will be fixed in v3 of this plugin anyways.

**Comment by plumhly** [comment]
@nklayman Thank you for your reply

This is how I currently solve it
