### ISSUE TITLE
3.0.0-alpha - Preload script error, unable to reference electron

### ISSUE THREAD

**Issue by shoeyn** [nklayman/vue-cli-plugin-electron-builder#1638]
The v3 alpha is causing the **preload** script to error out for me.
I'm getting: `TypeError: Cannot read properties of undefined (reading 'on')` referring to ipcRenderer:
```
import { contextBridge, ipcRenderer } from 'electron'

const windowLoaded = new Promise((resolve) => {
  window.onload = resolve
})

ipcRenderer.on('main-world-port', async (event) => {
  await windowLoaded
  if (process.env.WEBPACK_DEV_SERVER_URL) {
    window.postMessage(
      'main-world-port',
      process.env.WEBPACK_DEV_SERVER_URL,
      event.ports
    )
  } else {
    window.postMessage('main-world-port', 'app://./', event.ports)
  }
})

// more code related to contextBridge
```
Reverting to v2 makes it work again.
I've tried adding electron to the externals list to see if that made a difference, but it didn't. Anything I can do to help debug further?

**Comment by nklayman** [comment]
My bad, accidently added a bug that would break apps with preload scripts. Just published `3.0.0-alpha.1`, upgrade to that for a fix. Thanks for the report!
