### ISSUE TITLE
hope fix 1.x cant support electron14

### ISSUE THREAD

**Issue by imic07** [nklayman/vue-cli-plugin-electron-builder#1639]
**Describe the bug**
https://github.com/megahertz/electron-log/issues/187

vue-cli-plugin-electron-builder/lib/webpackConfig.js  
```
# require("electron").remote is removed in electron14
const realDirname = 'require("electron").remote.app.getAppPath()' 
```

**Fix**
use webpackConfig.js in vue-cli-plugin-electron-builder.2.x  instead of  vue-cli-plugin-electron-builder.1.x
```
// replace  require("electron").remote.app.getAppPath() （ fix electron-log err  https://github.com/megahertz/electron-log/issues/187）
const { devDependencies } = require(api.resolve('./package.json'))
const realDirname = semver.gte(
  ((devDependencies || {}).electron || '12.0.0').replace(/^\^/, ''),
  '12.0.0'
)
  ? '__dirname.replace(/electron\\.asar(\\\\|\\/)renderer/, "app.asar")'
  : 'require("electron").remote.app.getAppPath()'
```

**Comment by nklayman** [comment]
I'm not sure what you want me to do here. Can you please clarify?

**Comment by imic07** [comment]
> I'm not sure what you want me to do here. Can you please clarify?

The upgrade vue-cli-plugin-electron-builder.2.x cost is too high, and many dependencies are hard to solve，so we want to keep 1.x

**Comment by nklayman** [comment]
I'm not going to maintain v1.x. If you want to use it with a recent version of electron you'll have to fork it and fix it yourself. I'd recommend just upgrading, it's not very hard.
