### ISSUE TITLE
Error: Cannot find module 'request' when i opened the app.

### ISSUE THREAD

**Issue by itnikc** [nklayman/vue-cli-plugin-electron-builder#1640]
At first i am sorry.I don't kown where can i ask this question. so, i new this issue.please help me .

Okay, i use the 'request' module in the main process. I can build the app,but it show me 'Error: Cannot find module 'request'' when i open the app.

dependencies:

`
"dependencies": {
    "axios": "^0.24.0",
    "clipboard": "^2.0.8",
    "dayjs": "^1.10.7",
    "electron-store": "^8.0.1",
    "element-plus": "^1.2.0-beta.6",
    "pinia": "^2.0.9",
    "qs": "^6.10.2",
    "request": "^2.88.2",
    "sass": "^1.45.1",
    "simple-uploader.js": "^0.5.6",
    "spark-md5": "^3.0.2",
    "vue": "^3.2.22",
    "vue-i18n": "^9.1.9",
    "vue-router": "^4.0.11"
  }

`
And i use Vue3+Typescript+Vite2.

This is my main module package settings below：
`
import { join } from 'path'
import { builtinModules } from 'module'
import { defineConfig } from 'vite'

export default defineConfig({
  mode: process.env.NODE_ENV,
  root: join(__dirname, '../src/main'),
  build: {
    outDir: '../../dist/main',
    lib: {
      entry: 'index.ts',
      formats: ['cjs']
    },
    minify: process.env.NODE_ENV === 'production',
    emptyOutDir: true,
    rollupOptions: {
      external: [
        ...builtinModules,
        'electron'
      ],
      output: {
        entryFileNames: '[name].cjs'
      }
    }
  }
})

`

**Comment by nklayman** [comment]
This plugin doesn't support vite, I think you opened an issue on the wrong repository.

**Comment by jiumengs** [comment]
Would you consider using Vite?
Vite has many advantages

**Comment by nklayman** [comment]
If I have time later I'll look into making a plugin for vite.
