### ISSUE TITLE
electron:serve can't Launching Electron.. 

### ISSUE THREAD

**Issue by Vigayuan** [nklayman/vue-cli-plugin-electron-builder#1642]
when i use electron:serve it Compiled successfully  but can't Launching Electron and no error message!

**Comment by Vigayuan** [comment]
"vue-cli-plugin-electron-builder": "~2.1.1"
 "electron": "^13.0.0",
  "electron-devtools-installer": "^3.1.0",

**Comment by klren0312** [comment]
you can give the example

**Comment by Vigayuan** [comment]
I solved it, Previously I used NPM to install and there was a problem , Now i use yarn to install = =
