### ISSUE TITLE
Assets (e.g. SVG images and font files) are not being loaded correctly in built version of app using 3.0.0-alpha release

### ISSUE THREAD

**Issue by steveswinbank** [nklayman/vue-cli-plugin-electron-builder#1647]
**Describe the bug**
I'm including font files and images that are stored in `src/assets/img` and `src/assets/fonts`. They are loading and displaying correctly when I `npm run electron:serve`, but not when I build the app (`npm run electron:build`).

The issue is the same using versions 3.0.0-alpha.1 and 3.0.0-alpha.3.
The issue is not present in versions 2.x

PNG images are loading correctly - but not .svg, or font files (.woff2, .woff, and .ttf)

**To Reproduce**
- install new alpha version following instructions here: https://bestofvue.com/repo/nklayman-vue-cli-plugin-electron-builder-vuejs-vue-cli-3-plugins#releases
- Add an SVG image in src/assets/img and include it in the App.vue file, e.g.:
```
<img src="../assets/img/an-image.svg" >
```
- build app using `npm run electron:build`
- install / open the built application
- observe that the image file does not display correctly, instead there is a placeholder like this:

![image](https://user-images.githubusercontent.com/64836191/149933846-7269b0da-490a-4ae1-9de3-5d65eb35a856.png)

**Expected behavior**
Images and fonts should load

**Environment (please complete the following information):**
 Environment Info:

  System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.13.1 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Edge: Not Found
    Firefox: 95.0.2
    Safari: 15.2
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.1.1 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  5.0.0-rc.2 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  5.0.0-rc.2 
    @vue/cli-plugin-babel: ~5.0.0-rc.2 => 5.0.0-rc.2 
    @vue/cli-plugin-eslint: ~5.0.0-rc.2 => 5.0.0-rc.2 
    @vue/cli-plugin-router: ~5.0.0-rc.2 => 5.0.0-rc.2 
    @vue/cli-plugin-unit-jest: ~5.0.0-rc.2 => 5.0.0-rc.2 
    @vue/cli-plugin-vuex: ~5.0.0-rc.2 => 5.0.0-rc.2 
    @vue/cli-service: ~5.0.0-rc.2 => 5.0.0-rc.2 
    @vue/cli-shared-utils:  5.0.0-rc.2 
    @vue/component-compiler-utils:  3.3.0 
    @vue/eslint-config-airbnb: ^6.0.0 => 6.0.0 
    @vue/test-utils: ^1.1.3 => 1.3.0 
    @vue/vue2-jest: ^27.0.0-alpha.2 => 27.0.0-alpha.4 
    @vue/web-component-wrapper:  1.3.0 
    eslint-plugin-vue: ^8.0.3 => 8.3.0 
    eslint-plugin-vuejs-accessibility: ^1.1.0 => 1.1.1 
    jest-serializer-vue:  2.0.2 
    vue: ^2.6.14 => 2.6.14 
    vue-cli-plugin-electron-builder: ^3.0.0-alpha.3 => 3.0.0-alpha.3 
    vue-eslint-parser:  8.0.1 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  17.0.0 (15.9.8)
    vue-router: ^3.5.1 => 3.5.3 
    vue-style-loader:  4.1.3 
    vue-template-compiler: ^2.6.14 => 2.6.14 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.6.2 => 3.6.2 
  npmGlobalPackages:
    @vue/cli: 5.0.0-rc.2

**Comment by vangork** [comment]
I am upgrading the code now and met the same font loading issue now.(working well in versions 2.x)
No error during compilation `yarn electron:build`, but got the following error during execution.
```
Error: ENOENT, SegMDL2.39100a26.ttf not found in <path>\win-unpacked\resources\app.asar
    at createError (node:electron/js2c/asar_bundle:5:1243)
    at fsReadFileAsar (node:electron/js2c/asar_bundle:5:7694)
    at Object.e.readFile (node:electron/js2c/asar_bundle:5:8826)
    at Function.<anonymous> (<path>\win-unpacked\resources\app.asar\index.js:1:306009) {
  code: 'ENOENT',
  errno: -2
}
```
Font loaded by:
```
@font-face {
    font-family: "Segoe MDL2 Assets";
    src: url('../assets/fonts/SegMDL2.ttf') format("truetype");
}
```
Some finding: In the generated app.xxx.css file, the url path was replaced to `app:///fonts/SegMDL2.39100a26.ttf` while the correct path should be `app://./fonts/SegMDL2.39100a26.ttf`.

**Comment by steveswinbank** [comment]
In the built version of my app the font request URL looks correct`app://./fonts/ProximaNova-Regular.4e315317.woff2`, but it's not loading correctly, failing with error `net::ERR_FAILED`

![image](https://user-images.githubusercontent.com/64836191/150651328-37ed3e1d-ab38-45ea-b7ee-cdba995c88ed.png)

![image](https://user-images.githubusercontent.com/64836191/150651357-29fb4b70-c611-460a-90f7-85d7354447c7.png)

**Comment by nklayman** [comment]
This should be fixed in `v3.0.0-alpha.4`. Give it a try and let me know if it works.

**Comment by vangork** [comment]
My temp workaround is to change Electron Builder config of `customFileProtocol: './'`. and `win.loadURL(`file://${__dirname}/index.html`)`.
Not sure if there is any side effect.

**Comment by mrbuds** [comment]
I had same issue but only with fonts (working on dev, not on build)
`customFileProtocol: './'` fixed it, thanks @vangork

**Comment by HEllRZA** [comment]
I use that workaround now. Before i got the ungoogleable error

> axios "Unsupported protocol app:"

Int the electron app dev tools.

**Comment by karmac2015** [comment]
I still have the same problem with app protocol

**Comment by annymosse** [comment]
same for `vue ^2.7` issue

**Comment by hosnar** [comment]
> My temp workaround is to change Electron Builder config to `customFileProtocol: './'`. and `win.loadURL(`file://${__dirname}/index.html`)`. Not sure if there is any side effect.

Hi. This solution also appears to be working for my project. I was wondering, did anyone notice any side effects/problems after changing this protocol? Thanks

**Comment by Luury** [comment]
> My temp workaround is to change Electron Builder config to `customFileProtocol: './'`. and `win.loadURL(`file://${__dirname}/index.html`)`. Not sure if there is any side effect.

I tried this, works! But it created a new problem, any solution for it ?

![image](https://user-images.githubusercontent.com/56207672/220120730-4e2ddd06-534a-4fc9-8996-3db13cd75346.png)

My deps:
```json
  "devDependencies": {
    "@vue/cli-plugin-babel": "^5.0.6",
    "@vue/cli-plugin-router": "^5.0.8",
    "@vue/cli-plugin-vuex": "^5.0.8",
    "@vue/cli-service": "^5.0.8",
    "@vue/compiler-sfc": "^3.2.47",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "electron": "^23.1.0",
    "electron-devtools-installer": "^3.2.0",
    "electron-rebuild": "^3.2.9",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.20.0",
    "naive-ui": "^2.28.2",
    "prettier": "^2.6.2",
    "vue-cli-plugin-electron-builder": "^3.0.0-alpha.4"
  },
```
