### ISSUE TITLE
Cannot get cookie after build

### ISSUE THREAD

**Issue by iuzhao** [nklayman/vue-cli-plugin-electron-builder#1648]
Cannot get cookie after build, i use js-cookie in my prokect,  npm run serve is ok

**Comment by nklayman** [comment]
Please fill out the bug report  template, I need more information to solve this.

**Comment by iuzhao** [comment]
I seem to have found the reason. js-cookie is invalid in electron

thx !😂

**Comment by paramula** [comment]
> 

which use cookie plugin

**Comment by paramula** [comment]
> I seem to have found the reason. js-cookie is invalid in electron
> 
> thx !😂

which use cookie plugin
