### ISSUE TITLE
Multiple Version on Mac

### ISSUE THREAD

**Issue by KlausSchaefers** [nklayman/vue-cli-plugin-electron-builder#1651]
**Describe the bug**
I am building an electron app for Mac. Sometimes I try out the installation and install the DMG files after running the build. Before this I delete the app form the applications folder. For some reason, there seem to be multiple versions of the app on the machine now. If I right click on a file, and select the "Open With", I see several version of my app.

Even when I delete the app, I can still open it with 'Open With', which is really weird to me...

**To Reproduce**
1) Build app for MAC with file association
2) install the DMG
3) Run the app
4) Delete the app
5) Click on associated file

=> The app still shows up :)

**Expected behavior**
The app should not show up

Not sure if this bus the right forum...

**Comment by nklayman** [comment]
I don't own a mac so I can't help you here. However, I think this issue would fit better on the [electron-builder](https://github.com/electron-userland/electron-builder) repository. That project handles all the bundling and installer creation, this plugin just calls it with only a few custom settings, none of which would affect your issue.
