### ISSUE TITLE
Auto update appears again and again

### ISSUE THREAD

**Issue by catshanshan** [nklayman/vue-cli-plugin-electron-builder#1663]
Hi~ I'm doing some work on auto-update. I use the "generic" provider not "git",then I create a web on my localhost like that:

In vue.config.js:
builderOptions: {
                publish: [
                    {
                        provider: "generic",
		        url: "http://localhost/FE/",
                    }			
         },

In background.ts:
autoUpdater.setFeedURL("http://localhost/FE/");
autoUpdater.checkForUpdates();
When i finish downloading i set this code: autoUpdater.quitAndInstall()

then I build two versions,one is vesion 0.1.0 and the other one is version 0.1.1,which is upload to my localhost("http://localhost/FE/") together with the latest.yml.

Finally I open the exe with version 0.1.0, it prompts that a new version 0.1.1 can be downloaded,and I download it successfully.

Everything works well until I close the exe and launch it again ... It seems like the app go back to the old version0.1.0,and it asks me to download the new version again~  I think something are not saved,but I can't find how to...
Please help me ,thank you~~

**Comment by klren0312** [comment]
confirm your v0.1.1 exe is this version

**Comment by catshanshan** [comment]
> 



> confirm your v0.1.1 exe is this version

Yes,it is~ and the build command is "npm run electron:build"

**Comment by klren0312** [comment]
try this ? https://github.com/klren0312/electronTemplate/blob/master/src/updater.js

**Comment by catshanshan** [comment]
> try this ? https://github.com/klren0312/electronTemplate/blob/master/src/updater.js

Ah... That is my mistake,I confused the setup exe and the program exe. I have tried your code,it runs well, thank you~
