### ISSUE TITLE
Stylus in main process and render process not work

### ISSUE THREAD

**Issue by EryouHao** [nklayman/vue-cli-plugin-electron-builder#167]
**Describe the bug**
I want to use stylus in main process, and use to render `.styl` file, but when i import it, error is show.
ps: I use stylus in vue as same.

**Expected behavior**
it's work in main process and render process

**Screenshots**
![image](https://user-images.githubusercontent.com/17328747/50513131-bf45aa80-0ad0-11e9-8f6c-26acd8d27e5a.png)

**Environment (please complete the following information):**
 - OS and version: mac os mojave
 - node version: 10.0.0
 - npm version: 6.1.0
 - vue-cli-plugin-electron-builder version : 
 - electron version: 
 - other vue plugins used: 
 - custom config for vcp-electron-builder: ^1.0.0-rc.10

**Comment by nklayman** [comment]
You will have to configure [stylus loader](https://github.com/shama/stylus-loader) for the main process webpack config. See [the docs on webpack configuration](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#webpack-configuration). Use the `chainWebpackMainProcess`. Note that you will have to use [webpack chain](https://github.com/neutrinojs/webpack-chain).

Set your vue.config.js to this:

```javascript
// vue.config.js

module.exports = {
  pluginOptions: {
    electronBuilder: {
      chainWebpackMainProcess: config => {
		config.module.rule('stylus').test(/\.styl$/).use('babel').loader('css-loader!stylus-loader?paths=node_modules/bootstrap-stylus/stylus/')
      }
    }
  }
}
```
Let me know if that works.

**Comment by EryouHao** [comment]
@nklayman it's not work.
I push a small project to show this case. https://github.com/EryouHao/vcp-electron

if you have time, I hope you can run it. it not work.

if you remove the code from background.ts, it's works. 
```
import App from './server/renderder';
...
const appInstance = new App();
console.log(appInstance);
...
```
I think, I import stylus only.

thanks.

**Comment by nklayman** [comment]
Why are you trying to use stylus in the main process? All code that is part of the Vue app or displays UI should be part of the renderer process.

**Comment by EryouHao** [comment]
because I want to use electron client to Compile stylus file to css file, I solve it with less to replace stylus. thanks!
