### ISSUE TITLE
Add postuninstall script which installs app deps like postinstall

### ISSUE THREAD

**Issue by tuelsch** [nklayman/vue-cli-plugin-electron-builder#168]
**Describe the bug**
After uninstalling a package with yarn, libraries like sharp get rebuilt by yarn. This, however, does not work properly in an electron environment, because when I electron:serve after an uninstall, the package (in my case `sharp`) did not work anymore. It failed to load a dll.

**To Reproduce**
Create a new project with `vue create test`
Install this plugin with `vue add electron-builder`
Install sharp `yarn add sharp del` (del for testing)
Import sharp into main.js like `import sharp from 'sharp'`
Uninstall del `yarn remove del`
Sharp should report an error on the next build

**Expected behavior**
The `install-app-deps` command should be run on `postuninstall` as well.

**Environment (please complete the following information):**
 - OS and version: Windows 10 64bit
 - node version: 11.05.0
 - npm version: 6.4.0
 - yarn version (if used): 1.23.3
 - vue-cli-plugin-electron-builder version : 1.0.0-rc.10
 - electron version: 3.0.13
 - other vue plugins used: vuex, vue-router
 - custom config for vcp-electron-builder: ?

**Comment by nklayman** [comment]
You will have to configure [stylus loader](https://github.com/shama/stylus-loader) for the main process webpack config. See [the docs on webpack configuration](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#webpack-configuration). Use the `chainWebpackMainProcess`. Note that you will have to use [webpack chain](https://github.com/neutrinojs/webpack-chain).

**Comment by nklayman** [comment]
Whoops, that was for another issue

**Comment by nklayman** [comment]
This fix will be part of the next release, for now, just add the command manually. Thanks for reporting the issue!
