### ISSUE TITLE
Support for newer versions of electron builder

### ISSUE THREAD

**Issue by megasanjay** [nklayman/vue-cli-plugin-electron-builder#1680]
**Is your feature request related to a problem? Please describe.**
I know that development is being made on v3 but is it possible to get a new version of this library that uses a later version of electron builder? It would seem that a newer version is required for macOS arm builds support according to this issue: https://github.com/electron-userland/electron-builder/issues/5689#issuecomment-946528612

**Describe the solution you'd like**
A beta version of v2 could be handy for anyone still waiting on v3 of the plugin. 

**Describe alternatives you've considered**
I tried adding electron-builder manually but it seems like the build process uses `v22.11.7` internally.

**Comment by spuky** [comment]
my workarround maybe helps you... 

https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1691

but +1 for that the version bump

**Comment by spuky** [comment]
@megasanjay added a pull request that should help you...

**Comment by nklayman** [comment]
You can use Yarn resolutions to force a specific version of electron-builder. I'll also make this part of the v3 release, I can't do it with v2 as it's a major version upgrade and could contain breaking changes.
