### ISSUE TITLE
assets added through css/sass won't load in production

### ISSUE THREAD

**Issue by itsgoofer** [nklayman/vue-cli-plugin-electron-builder#1684]
I have the following code in my css:

```
.pic{
	background-image: url('@/assets/img/test.png');
	width: 200px;
	height: 200px;
}

```
it works fine while running the app in development mode, but in production the image was missing. 
Same happens with fonts: 

```
@font-face {
	font-family: 'Input Mono Narrow';
	src: url('@/assets/fonts/InputMonoNarrowBold.woff2') format('woff2'), url('@/assets/fonts/InputMonoNarrowBold.woff') format('woff');
	font-weight: bold;
	font-style: normal;
	font-display: swap;
}
@font-face {
	font-family: 'Input Mono';
	src: url('@/assets/fonts/InputMonoNarrowRegular.woff2') format('woff2'), url('@/assets/fonts/InputMonoNarrowRegular.woff') format('woff');
	font-weight: normal;
	font-style: normal;
	font-display: swap;
}
```

Ideas?

**Comment by omarfouad** [comment]
full path as in how? Could you elaborate @klren0312 please?

**Comment by omarfouad** [comment]
I actually tried the following but still didn't work 

```
url('./src/assets/img/test.png');
url('../assets/img/test.png');
url('/assets/img/test.png');
```

**Comment by megasanjay** [comment]
Try putting your fonts in your `static` folder. Those should copy over without modification

**Comment by wuql576** [comment]
Try change 
`protocol.registerSchemesAsPrivileged([
  { scheme: 'app', privileges: { secure: true, standard: true } }
])`
to 
`protocol.registerSchemesAsPrivileged([
  { scheme: 'app', privileges: { secure: true} }
])`
in your background.js

**Comment by pany-ang** [comment]
The same case, not on vue-cli 4.5.15, on  vue-cli 5.0.1

**Comment by pany-ang** [comment]
> 同样的情况，在 vue-cli 4.5.15 上没有，在 vue-cli 5.0.1 上

have to wait for the v3 version?  Now at v2.1.1

**Comment by ion1ze** [comment]
> Try change `protocol.registerSchemesAsPrivileged([ { scheme: 'app', privileges: { secure: true, standard: true } } ])` to `protocol.registerSchemesAsPrivileged([ { scheme: 'app', privileges: { secure: true} } ])` in your background.js

Thank you,solved my problem.

**Comment by Formsoftware** [comment]
> Try change `protocol.registerSchemesAsPrivileged([ { scheme: 'app', privileges: { secure: true, standard: true } } ])` to `protocol.registerSchemesAsPrivileged([ { scheme: 'app', privileges: { secure: true} } ])` in your background.js

Thank you,Successfully solved the problem that bothered me

**Comment by MatthijsBurgh** [comment]
Seems that this issue is solved by the solution provided by @wuql576
