### ISSUE TITLE
Build successfully, but open the application error 

### ISSUE THREAD

**Issue by yuemeng200** [nklayman/vue-cli-plugin-electron-builder#1686]
I use `vue-cli-plugin-electron-builder` for some demos about Vue, they all work perfect. 
So I decide to use it for my company's project of vue, It also behaves normally in the development state, so I package it with the command which is `npm run electron:build`, there is no exception in the console and prompt ` DONE  Build complete`.
But when I installed and opened the application, the screen was blank, DevTools reported an error saying `Uncaught ReferenceError: regeneratorRuntime is not defined`.
I suspect that there is a packaging problem in my front-end project itself, so I packaged the regular VUE project and deployed it on the Nginx server, but the project runs normally, so I am very confused now. I have searched the relevant errors on the Internet, and they are inconsistent with my situation and are invalid.  So I can only ask you to help me guess where the problem might be, please give me some suggestions, thank you !
💗

**Comment by megasanjay** [comment]
Start a new project using `vue-cli-plugin-electron-builder`. Then move your Vue application into the new project. I can only assume that something is missing in your dependencies.

**Comment by yuemeng200** [comment]
Its a error about babel, beacause my project is based on a lower version of Vue.js
[https://github.com/vuejs/vue/issues/5559](url)
It is still confuses me, but I have no time to go into it.
