### ISSUE TITLE
Question:  A module in node_modules referencing data files in the module directory

### ISSUE THREAD

**Issue by robogeek** [nklayman/vue-cli-plugin-electron-builder#169]
**Is your feature request related to a problem? Please describe.**

Yes ... I am building an application which includes some modules that each refer to files within the modules.  The files are referenced using `path.join(__dirname, 'partials')` to record the directory name, and later code uses files in the directory.  These modules work as expected in normal Node.js deployment scenarios where everything is in the `node_modules` directory, but I want to use the same code in my Electron application.

I see some similarities to issue #126 

The modules in question are running in the main process rather than the renderer, if this makes a difference.

**Describe the solution you'd like**

I don't understand Webpack very well and therefore don't understand what's possible.

Is it possible to configure Webpack to not bundle certain `node_modules` directories?  And that the application would consult those modules from `node_modules`?

In the discussion of #126 it's mentioned that "libraries" can be marked "external" (do you mean Node.js modules?).  Is this what I need to do - namely, I would list the corresponding module name in the externals array?  EDIT: This doesn't seem to be the case since on the Webpack site `externals` are described as something that will be installed in the environment.

The documentation mentions a file `vue.config.js` but a file by that name was not generated when initializing the project.  Two files `babel.config.js` and `postcss.config.js` were generated.  Do I simply create `vue.config.js`?

**Describe alternatives you've considered**

I'm rather stumped at the moment and don't know what to do.

**EDIT: Additional Context**

The pathname generated by the `path.join` is `/Volumes/Extra/akasharender/epubuilder-electron/dist_electron/partials`  Clearly this does not reference into the module directory.

**Comment by nklayman** [comment]
Just create the vue.config.js. to learn more about it, look at the [Vue cli docs](https://cli.vuejs.org).

**Comment by robogeek** [comment]
I'm reading over the docs - and see that it's simple to add config to either `package.json` or to create a `vue.config.js` file.

My real question may have been lost in too many words ...

How to read files from inside the module?  Currently I use `__dirname` to learn where the module is, it's pathname within `node_modules`, but obviously this won't work within something packaged by webpack.

**Comment by robogeek** [comment]
Yes that helps, thank you for the explanation.

**Comment by robogeek** [comment]
I tried - I'm trying to grok the documentation - in any case, using the vue.config.js file causes an error in loading another module.  The module in question - Opal-Runtime - is indirectly referenced from the my module.

See: https://github.com/Mogztter/opal-node-runtime/issues/6

**Comment by nklayman** [comment]
If you just need to read a file from it, the module should be included in the node_modules folder (inside the asar) even if it is not an external. Extract the asar and see if the module you need is somewhere inside it.

**Comment by nklayman** [comment]
The asar should be in dist_electron/platform-unpacked/resources/app.asar
