### ISSUE TITLE
Not building on M1 mac with Monterey

### ISSUE THREAD

**Issue by spuky** [nklayman/vue-cli-plugin-electron-builder#1691]
**Describe the bug**
apple removed python 3 support which prevents bundeling the dmg
see https://github.com/electron-userland/electron-builder/pull/6617

fixed in electron-builder v23

**To Reproduce**

try building an mac app 

**Expected behavior**

app builds without error

**Additional context**

for People running into this here is a workaround:

**EDIT: Workarround is not needed**
just add
"vue-cli-plugin-electron-builder": "git://github.com/spuky/vue-cli-plugin-electron-builder#b6826fc",
to your package.json to install with upgraded dependency

add a `.env` file to your project with your Python 3 location:

`PYTHON_PATH=/opt/homebrew/bin/python3`

gets rid of the first error:

Error: Exit code: ENOENT. spawn /usr/bin/python ENOENT

then edit core.py the file in the sceond error (might be in node_modules/electron-builder or node_modules/vue-cli-plugin-electron-builder  depending on the fact if you tried upgrading electron builder yourself..) you run into

Error: Exit code: 1. Command failed: /opt/homebrew/bin/python3 /Users/spuky/webstuff/myproject/node_modules/electron-builder/node_modules/dmg-builder/vendor/dmgbuild/core.py
Traceback (most recent call last):
  File "/Users/spuky/webstuff/myproject/node_modules/electron-builder/node_modules/dmg-builder/vendor/dmgbuild/core.py", line 7, in <module>
    reload(sys)  # Reload is a hack
NameError: name 'reload' is not defined

to read like this:

`# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
import re
import sys
from importlib import reload
reload(sys)  # Reload is a hack
#sys.setdefaultencoding('UTF8')`

new stuff is 
from importlib import reload
and the comented 
sys.setdefaultencoding('UTF8') 
line... 

then your app should build...

Resolution: 

Bumping the dependency of electron-builder to v23 should fix the issue..

**Comment by spuky** [comment]
just added a pullrequest anybody with this issue can add

`"vue-cli-plugin-electron-builder": "git://github.com/spuky/vue-cli-plugin-electron-builder#b6826fc",`

as a depency in his package.json to get working again no need for python path in env no changeing files..

**Comment by rankill** [comment]
Is there any update on this issue? I cannot build for in my MacBook M1

**Comment by MatthijsBurgh** [comment]
The default branch of this repo, does depend on `electron-builder` v23. It isn't released yet and this might still take some time.
