### ISSUE TITLE
Websocket don't allow app protocol

### ISSUE THREAD

**Issue by yuemeng200** [nklayman/vue-cli-plugin-electron-builder#1695]
I have shut the `webSecurity` option, the communication about `http` and `https` is normal, but the `websocket` is invalid. 
I am still using the default `app` protocol, I don't know much about the communication protocol, but now I just must to make it work as soon as possible, may I ask which Settings I need to change to make it suitable for WebSocket communication?  thank you.  
Below is my current setting：
```js
protocol.registerSchemesAsPrivileged([
  { scheme: "app", privileges: { secure: true, standard: true } },
]);
createProtocol("app");
win.loadURL("app://./index.html");
```
Window setting:
```js
  webPreferences: {
    nodeIntegration: true,
    webSecurity: false,
    contextIsolation: false,
    enableRemoteModule: true,
  },
```

**Comment by klren0312** [comment]
Is websocket server work well?
you use normal index.html, use js to connect websocket server, can you connect normally

**Comment by yuemeng200** [comment]
Bro, you are right ... I'm using the web version itself has this problem, thank you very much, otherwise I might never have solved this "bug". @klren0312
