### ISSUE TITLE
Include Google Fonts Material Icons

### ISSUE THREAD

**Issue by maurop123** [nklayman/vue-cli-plugin-electron-builder#17]
Hi, I'm new to using electron. I made my app like this...

``` bash
# Vue CLI v3.0.0-beta.16

vue create elec
vue add electron-builder
vue add vuetify
yarn serve:electron
```

When running the app, you can see that the icons aren't working. They are included in `public/index.html`, but I don't know if electron even uses this file. Does it? If not, how can I include the material icons?

Here's the app I made to help save time reproducing https://github.com/maurop123/vuetify-electron-test/blob/master/public/index.html

**Comment by luis-git** [comment]
have you tried to import the icons in main.js
`// main.js
import 'material-design-icons-iconfont/dist/material-design-icons.css' // `

**Comment by maurop123** [comment]
Just tried it and it worked. Thanks!

Just wondering, does electron not use the index.html?

**Comment by nklayman** [comment]
Yes, but not in this case. I use electron-webpack which has it's own config and index.html. In 1.0.0 I will be modifying the existing config to work with electron and it will then use index.html as well as vue cli's config.

**Comment by maurop123** [comment]
Cool. Thanks for the help!
