### ISSUE TITLE
macOS 12.3 (21E230) Exit code: ENOENT. spawn /usr/bin/python ENOENT

### ISSUE THREAD

**Issue by ningkexin** [nklayman/vue-cli-plugin-electron-builder#1701]
``` Error: Exit code: ENOENT. spawn /usr/bin/python ENOENT
    at /Users/xxx/web/xxx/node_modules/builder-util/src/util.ts:133:18
    at exithandler (node:child_process:406:5)
    at ChildProcess.errorhandler (node:child_process:418:5)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess.emit (node:domain:475:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
Please upgrade electron-builder 23.02 +

**Comment by hjMaGitHub** [comment]
我也遇到了，有解决办法了吗？

**Comment by hjMaGitHub** [comment]
Please ask is it solved

**Comment by lylyong** [comment]
how to upgrade electron-builder 23.02 +

**Comment by hjMaGitHub** [comment]
> ```
>     at /Users/xxx/web/xxx/node_modules/builder-util/src/util.ts:133:18
>     at exithandler (node:child_process:406:5)
>     at ChildProcess.errorhandler (node:child_process:418:5)
>     at ChildProcess.emit (node:events:526:28)
>     at ChildProcess.emit (node:domain:475:12)
>     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
>     at onErrorNT (node:internal/child_process:478:16)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21)
> ```
> 
> 请升级 electron-builder 23.02 +

Hello, it is already 23.0.2, but still reported an error, do you have any suggestions?
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/40014076/159145396-71476d88-11c8-4966-a9c1-08b3f57d094e.png">

**Comment by lylyong** [comment]
> > ```
> >     at /Users/xxx/web/xxx/node_modules/builder-util/src/util.ts:133:18
> >     at exithandler (node:child_process:406:5)
> >     at ChildProcess.errorhandler (node:child_process:418:5)
> >     at ChildProcess.emit (node:events:526:28)
> >     at ChildProcess.emit (node:domain:475:12)
> >     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
> >     at onErrorNT (node:internal/child_process:478:16)
> >     at processTicksAndRejections (node:internal/process/task_queues:83:21)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请升级 electron-builder 23.02 +
> 
> 
> Hello, it is already 23.0.2, but still reported an error, do you have any suggestions?
> <img alt="image" width="1179" src="https://user-images.githubusercontent.com/40014076/159145396-71476d88-11c8-4966-a9c1-08b3f57d094e.png">

looks,must upgrade electron-build in  vue-cli-plugin-electron-builder

**Comment by mx1120** [comment]
<img width="566" alt="image" src="https://user-images.githubusercontent.com/23393061/159657188-71db08be-763d-4bb7-ba88-7c7c29f5b2ba.png">
i'm also

**Comment by mx1120** [comment]
> 我也遇到了，有解决办法了吗？

有解决办法么？

**Comment by btribouillet** [comment]
vue-cli-plugin-electron-builder needs to update its dependencies to 23.0.3

https://github.com/electron-userland/electron-builder/issues/6732#issuecomment-1073288437

**Comment by btribouillet** [comment]
> If you use Yarn, you can use [selective dependency resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to force that module to use the newer electron-builder.

https://github.com/electron-userland/electron-builder/issues/6726#issuecomment-1073262721

```
  "resolutions": {
    "vue-cli-plugin-electron-builder/electron-builder": "^23.0.3"
  }
```

**Comment by JamesS-M** [comment]
+1 I'm also running into this issue.

**Comment by Camotubi** [comment]
As a workaround install python 2.7 with pyenv then set PYTHON_PATH when runinng `npm run electron:build` like this:
```sh
PYTHON_PATH=/Users/PUT_YOUR_USER_HERE/.pyenv/versions/2.7.18/bin/python npm run electron:build
```

**Comment by mx1120** [comment]
Can author update the version of electron builder to 23.0.3 in dependency

**Comment by huzunjie** [comment]
There is a simple solution 😂:

To install python 2.7, and the installation directory (for example: /XXX/versions/2.7/bin/python);

Open "YourProjectPath/node_modules/dmg-builder/out/dmg.js", find "/usr/bin/python", replace with "/XXX/versions/2.7/bin/python".

**Comment by mx1120** [comment]
> There is a simple solution 😂:
> 
> To install python 2.7, And get the installation path (for example: /XXX/versions/2.7/bin/python);
> 
> Open "YourProjectPath/node_modules/dmg-builder/out/dmg.js", find "/usr/bin/python", replace with "/XXX/versions/2.7/bin/python".

Support the m1pro version of python2.7 Where can I download it? I can't find it

**Comment by kurohoan** [comment]
I would like to support this in the form of using python 3.9 if possible, but is there a way to specify the vue-cli-plugin-electron-builder dependency in npm instead of yarn?

**Comment by kurohoan** [comment]
>  "resolutions": {
>     "vue-cli-plugin-electron-builder/electron-builder": "^23.0.3"
>   }

I tried the above, and now I have
When I run the `yarn electron:serve` command, it stops with the following message.

` INFO Launching Electron...`

**Comment by kurohoan** [comment]
> As a workaround install python 2.7 with pyenv then set PYTHON_PATH when runinng `npm run electron:build` like this:
> 
> ```shell
> PYTHON_PATH=/Users/PUT_YOUR_USER_HERE/.pyenv/versions/2.7.18/bin/python npm run electron:build
> ```

I installed python 2.7.18 with pyenv and ran this command and the error did not change in my environment.
Of course I changed the username to my own.

**Comment by MarMun** [comment]
Temporary (and simple) solution to this is [npm overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides):

```
package.json
{
 .
 .
 .
  "devDependencies": {
    "vue-cli-plugin-electron-builder": "^2.1.1"
  },
  "overrides": {
    "vue-cli-plugin-electron-builder": {
      "electron-builder": "^23.0.3"
    }
  }
}
```
After changing `package.json`, I did (there may be a less 'brutal' approach)
```
rm -rf node_modules
rm package-lock.json
npm install
```

result:
```
npm list electron-builder
foobar@1.0.0 /Users/me/Dev/foobar
└─┬ vue-cli-plugin-electron-builder@2.1.1
  └── electron-builder@23.0.3
```
Aaand build on mac os 12.3.1 works again :-)

**Comment by Jayin** [comment]
+1

**Comment by mx1120** [comment]
> There is a simple solution 😂:
> 
> To install python 2.7, And get the installation path (for example: /XXX/versions/2.7/bin/python);
> 
> Open "YourProjectPath/node_modules/dmg-builder/out/dmg.js", find "/usr/bin/python", replace with "/XXX/versions/2.7/bin/python".

The problem has been solved. Thank you very much ！

**Comment by peteyan** [comment]
> There is a simple solution 😂:
> 
> To install python 2.7, And get the installation path (for example: /XXX/versions/2.7/bin/python);
> 
> Open "YourProjectPath/node_modules/dmg-builder/out/dmg.js", find "/usr/bin/python", replace with "/XXX/versions/2.7/bin/python".

就这个最有用，那个改PYTHON_PATH也无效

**Comment by billmorgan123** [comment]
> Temporary (and npm native) solution to this is [npm overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides):
> 
> ```
> package.json
> {
>  .
>  .
>  .
>   "devDependencies": {
>     "vue-cli-plugin-electron-builder": "^2.1.1"
>   },
>   "overrides": {
>     "vue-cli-plugin-electron-builder": {
>       "electron-builder": "^23.0.3"
>     }
>   }
> }
> ```
> 
> After changing `package.json`, I did (there may be a less 'brutal' approach):
> 
> ```
> rm -rf node_modules
> rm package-lock.json
> npm install
> ```
> 
> result:
> 
> ```
> npm list electron-builder
> foobar@1.0.0 /Users/me/Dev/foobar
> └─┬ vue-cli-plugin-electron-builder@2.1.1
>   └── electron-builder@23.0.3
> ```
> 
> Aaand build on mac os 12.3.1 works again :-)

not working its update to 22.14.13

**Comment by do-web** [comment]
Any other workaround here?

**Comment by MatthijsBurgh** [comment]
The current master branch uses electron-builder 23. So you could use that instead of the released version.

**Comment by danline** [comment]
> > not working its update to 22.14.13
> 
> @do-web @billmorgan123 Did you delete `package-lock.json` before `npm install`?
> 
> Unsure if npm overrides actually overrules package-lock.

@MarMun - I did delete package-lock before running npm install. Pretty much followed this:

```
rm -rf node_modules
rm package-lock.json
npm install
```

Still what I am seeing is this:

```
desktop@0.6.38 /Users/daniel/Documents/Projects/desktop
├── electron-builder@23.3.3 
└─┬ vue-cli-plugin-electron-builder@2.1.1
  └── electron-builder@22.14.13 
```

Any help will be greatly appreciated!

**Comment by danline** [comment]
> > > not working its update to 22.14.13
> > 
> > 
> > @do-web @billmorgan123 Did you delete `package-lock.json` before `npm install`?
> > Unsure if npm overrides actually overrules package-lock.
> 
> @MarMun - I did delete package-lock before running npm install. Pretty much followed this:
> 
> ```
> rm -rf node_modules
> rm package-lock.json
> npm install
> ```
> 
> Still what I am seeing is this:
> 
> ```
> desktop@0.6.38 /Users/daniel/Documents/Projects/desktop
> ├── electron-builder@23.3.3 
> └─┬ vue-cli-plugin-electron-builder@2.1.1
>   └── electron-builder@22.14.13 
> ```
> 
> Any help will be greatly appreciated!

Never mind. My npm was out of date. I was still using npm v 6.14.8 which doesn't support overrides. Updating npm to the latest version resolved this.

**Comment by MarMun** [comment]
@danline Ah yes. Overrides require >= npm 8. Should have mentioned this. Sorry for the confusion.

**Comment by tkarnaAWS** [comment]
> There is a simple solution 😂:
> 
> To install python 2.7, And get the installation path (for example: /XXX/versions/2.7/bin/python);
> 
> Open "YourProjectPath/node_modules/dmg-builder/out/dmg.js", find "/usr/bin/python", replace with "/XXX/versions/2.7/bin/python".

It worked! Thanks a lot

**Comment by GerryDush** [comment]
> overrides

这方法解决了我的问题👍
