### ISSUE TITLE
Cannot read properties of undefined when using "this" in vue template

### ISSUE THREAD

**Issue by aquarius-wing** [nklayman/vue-cli-plugin-electron-builder#1706]
**Describe the bug**
like the title

**To Reproduce**
- vue create electron-demo1
- cd  electron-demo1
- vue add electron-builder
- yarn add ts-loader@8.2.0
- edit code in HomeView.vue
```vue
<template>
  <div class="home">
    <img alt="Vue logo" src="../assets/logo.png">
    <button @click="this.handleClick">Click me/button>
    <HelloWorld msg="Welcome to Your Vue.js + TypeScript App"/>
  </div>
</template>

<script lang="ts" setup>
const handleClick = () => {
  console.log('click')
}
</script>
```
- yarn electron:serve(it's ok when window is shown)
- yarn electron:build
 - install it and run it
 - click the button 
 - then you get error

**Expected behavior**
log click text

**Environment (please complete the following information):**
 - @vue/cli: 5.0.1
 - vue-cli-plugin-electron-builder: 2.1.1

**Additional context**
Windows 11 21H2

**Comment by megasanjay** [comment]
You don't need the `this` keyword in a template function.

**Comment by Wing-Lo** [comment]
I just confuse why "serve" mode is worked, but "build" mode doesn't

**Comment by megasanjay** [comment]
Vue will automatically abstract your data scopes. This works in the template in the development environment but `this` refers to something else when the app is built. That's why it doesn't work in the same way.

**Comment by MatthijsBurgh** [comment]
This is a vue problem, not related to this project.
