### ISSUE TITLE
Edit Built Installer Filename

### ISSUE THREAD

**Issue by grantdfoster** [nklayman/vue-cli-plugin-electron-builder#171]
**Is your feature request related to a problem? Please describe.**
Yes.  After much researching in electron, electron-builder, and vue-cli-3 docs, I'm having an issue setting the _filename_ for my installer after building.  I'd like to remove the version number from the filename to ease downstream processes.

**Describe the solution you'd like**
The ability to easily edit the installer filename produced by electron-builder and nsis.

**Describe alternatives you've considered**
After much research, it seems the following edit to the package.json file would result in correctly changing the installer filename after building:

`
"build": {
  "productName": "some product name",
  "nsis": {
    "artifactName": "some installer name.${ext}"
  }
}
`

**Additional context**
When adding the above code to my package.json, I get this error on build:
![vue-cli-3-electron-builder](https://user-images.githubusercontent.com/18288572/50662306-de7e8500-0f73-11e9-8882-85f37969f757.png)

_'build'_ is correctly present in my development package.json.  

It appears as though the builder is copying my package.json into dist_electron/ and I'm unsure how to specify otherwise.  I am aware of the "two package.json" method to distinguish between dev and app packages, but am unsure where to place the app package.json to get this to successfully work.  I've tried app/package.json to no avail, as well as a few other options.

**Comment by nklayman** [comment]
See the [docs on electron builder configuration](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#configuring-electron-builder). Place the productName and nsis config there instead.

**Comment by grantdfoster** [comment]
Thank you!  Works like a charm... appreciate the clarification.

**Comment by 1c7** [comment]
@nklayman 's  solution work for me!

## Here is example `vue.config.js`

```javascript
module.exports = {
  publicPath: process.env.NODE_ENV === 'production' ? './' : '/',
  runtimeCompiler: true,

  chainWebpack: config => {
    config.module.rules.delete('eslint');
  },

  productionSourceMap: false,
  configureWebpack: {
    module: {
      rules: [
        { test: /\.tsx?$/, loader: "ts-loader" }
      ]
    }
  },

  pluginOptions: {
    i18n: {
      locale: 'en',
      fallbackLocale: 'en',
      localeDir: 'locales',
      enableInSFC: true
    },
    electronBuilder: {
      builderOptions: {
        "productName": 'Tern-Subtitle File Translator',
        "extraResources": [
          {
            "from": "./extraResources/",
            "to": "extraResources",
            "filter": [
              "**/*"
            ]
          }
        ]
      },
    }
  },
}

```

## The key part is 
```javascript
pluginOptions: {
  electronBuilder: {
    builderOptions: {
      "extraResources": [
        {
          "from": "./extraResources/",
          "to": "extraResources",
          "filter": [
            "**/*"
          ]
        }
      ]
    },
  }
},
```

**Comment by 100Mbps** [comment]
problem solved .thanks a lot.
