### ISSUE TITLE
INFO  Launching Electron...　Stops with the above message displayed.

### ISSUE THREAD

**Issue by kurohoan** [nklayman/vue-cli-plugin-electron-builder#1720]
INFO Launching Electron...

Stops with the above message displayed.
Why is this? Is there an error log somewhere?

**Comment by klren0312** [comment]
need recurrent code

**Comment by kurohoan** [comment]
It is not possible to list all of them.
I would know why it stops if there was an error, but there is no error either.

**Comment by klren0312** [comment]
so need your code, to test
judge environmental issue or code issue

**Comment by kurohoan** [comment]
npn run electron:serve

**Comment by klren0312** [comment]
try to run this? https://github.com/klren0312/electronTemplate

**Comment by kurohoan** [comment]
I have no idea what caused it, but I reverted to a past version and was able to start it.

If this happens again, I will report it again.

**Comment by kurohoan** [comment]
I don't know what it is, but it stops when I install "yarn".
If I uninstall "yarn", I can start it.

**Comment by klren0312** [comment]
delete yarn.lock ?

**Comment by kurohoan** [comment]
yes.

**Comment by kurohoan** [comment]
"vue": "^2.6.14",
    "vue-js-modal": "^2.0.1",
    "vue-router": "^3.2.0",
    "vuejs-dialog": "^1.4.2",

**Comment by klren0312** [comment]
see this https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1475

**Comment by kurohoan** [comment]
https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1641
I updated to version 3.0.0-alpha.3 based on the above article, but
As usual, INFO Launching Electron... is still displayed.

**Comment by kurohoan** [comment]
@nklayman 
Whenever you notice it is fine.
I would like to get some tips on how to solve the problem.

**Comment by kurohoan** [comment]
sorry!!
As for this problem, it was caused by my accidental deletion of the code to configure the Electron screen.
However, a new issue will be issued for the ongoing problem that occurs when yarn is used.
Thanks.
