### ISSUE TITLE
Question: how to change the default icon ?

### ISSUE THREAD

**Issue by TrustNguyen** [nklayman/vue-cli-plugin-electron-builder#173]
I don't know what file to use to change the default icon of Electron app. Please share your knowledge. Thank you !

**Comment by nklayman** [comment]
Follow the [Electron Builder Icon guide](https://www.electron.build/icons).

**Comment by YoussF** [comment]
@TrustNguyen hello, did you manage to get this working ? I spend one entire day trying to get this working, without any success :(

**Comment by nklayman** [comment]
Check out this demo repo i made: https://github.com/nklayman/electron-icon-example

**Comment by YoussF** [comment]
@nklayman Thank you !

**Comment by nklayman** [comment]
No problem, notice the `electron:generate-icon` script in the `package.json`.
