### ISSUE TITLE
Question: how to add a zip file to electron.asar or app.asar ?

### ISSUE THREAD

**Issue by TrustNguyen** [nklayman/vue-cli-plugin-electron-builder#174]
I have some files which I want to add to dir C:\Users\UserPC\AppData\Local\Programs\Tool\resources when the app has already installed. I would like to add 1 zip file to this dir or to app.asar or to electron.asar or another .asar. Please help me!!!

**Comment by nklayman** [comment]
Check the [electron-builder docs](https://www.electron.build/configuration/configuration), it's the tool this plugin uses to package your app. It appears you need to use the `files` config option. Let me know if you have any more questions.

**Comment by crossle** [comment]
I face the same problem, add a js or wasm file to app.asar, but it can not work
```
        files: ["./public/wasm_exec.js"]
```

**Comment by nklayman** [comment]
Files in your public folder are included automatically.

**Comment by nklayman** [comment]
Get the path to them with `__static`

**Comment by crossle** [comment]
Thank your reply, found two dist dir, /dist /dist_electron, the file auto generate to ./dist, but packaged /dist_electron, dont know why

**Comment by crossle** [comment]
```
⠧  Building legacy bundle for production...

 DONE  Compiled successfully in 6095ms                                                                                                                                                                                         4:23:09 PM

  File                                      Size             Gzipped

  dist_electron/bundled/js/chunk-vendors    864.15 KiB       278.28 KiB
  -legacy.31b20abb.js
  dist_electron/bundled/js/app-legacy.fc    124.98 KiB       33.01 KiB
  d0a8a8.js
  dist_electron/bundled/css/app.52fe7e1d    29.19 KiB        4.84 KiB
  .css

  Images and other types of assets omitted.


⠴  Building for production...

 DONE  Compiled successfully in 5496ms                                                                                                                                                                                         4:23:16 PM

  File                                 Size               Gzipped

  dist/js/chunk-vendors.bae2561c.js    803.33 KiB         253.90 KiB
```
Why Building for production, not modern production?

**Comment by nklayman** [comment]
That is the vue cli build command, I don't change that other than the webpack confiig

**Comment by crossle** [comment]
Why need Building two times?

**Comment by nklayman** [comment]
Until vue cli 3.4.1, I could not disable the legacy mode. as of v1.1.0 I have now disabled the legacy build (requires vue cli service 3.4.1+).

**Comment by crossle** [comment]
COool, test now

**Comment by crossle** [comment]
Worked, thank you
