### ISSUE TITLE
Initial Route not working in build electron.exe

### ISSUE THREAD

**Issue by MBurchard** [nklayman/vue-cli-plugin-electron-builder#1741]
**Describe the bug**
The Initial Route is not loaded/shown in the build electron.exe.  
I'd like to confirm if this is a bug in this cli or in the electron-builder.

**To Reproduce**
I have setup a very basic project: https://github.com/MBurchard/vue-electron-bug-2022-05-16

1. An initial Vue 3 project.
2. `vue add electron-builder@alpha`
3. change `tsconfig.json`, add `"useUnknownInCatchVariables": false,`
4. Test the project with `npm run electron:serve` --> All looks fine
5. Build the project with `npm run electron:build`
6. switch to folder `dist_electron\win-unpacked` and start the electron.exe --> Initial Route not loaded... Router works when using the links.

**Expected behavior**
The initial Route should be loaded correctly like in the serve mode.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4256302/168681526-a73d9417-89e3-444f-9ec0-d8e5be6aba11.png)

**Comment by Olesko24** [comment]
I faced the same problem and my solution was to use the `onMounted` hook in Vue.

Example: 
```typescript
onMounted(() => {
this.$router.push('/');
})
```

**Comment by MBurchard** [comment]
yes, we also have a workaround in place for our application, but it should work without it and it would be nice if this can be fixed.

**Comment by MatthijsBurgh** [comment]
No support to the alpha release.
