### ISSUE TITLE
I was unable to successfully publish the package to a private repository

### ISSUE THREAD

**Issue by AutismPatient** [nklayman/vue-cli-plugin-electron-builder#1743]
**Describe the bug**
I had an error building the package application：

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config  file=electron-output\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=18.1.0 appOutDir=electron-output\win-unpacked
  • Cannot detect repository by .git/config. Please specify "repository" in the package.json (https://docs.npmjs.com/files/package.json#repository).
Please see https://electron.build/configuration/publish
  • default Electron icon is used  reason=application icon is not set
  • building        target=nsis file=electron-output\wehub Setup 0.0.1.exe archs=x64 oneClick=true perMachine=false
  • building block map  blockMapFile=electron-output\wehub Setup 0.0.1.exe.blockmap
  • Cannot detect repository by .git/config. Please specify "repository" in the package.json (https://docs.npmjs.com/files/package.json#repository).
Please see https://electron.build/configuration/publish
  • Cannot detect repository by .git/config. Please specify "repository" in the package.json (https://docs.npmjs.com/files/package.json#repository).
Please see https://electron.build/configuration/publish
TypeError: Cannot read properties of null (reading 'provider')
    at Object.createUpdateInfoTasks (D:\work\hub\node_modules\app-builder-lib\src\publish\updateInfoBuilder.ts:116:44)

The prerequisite is that I have followed the configuration steps： [auto-update](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#auto-update)，And I've set the environment variables  ``set GH_TOKEN=****`` 

**background.js**
`
import {autoUpdater} from "electron-updater"
autoUpdater.checkForUpdatesAndNotify()
`
**vue.config.js**
`
 builderOptions: {
    publish: ['github']
}
`
**package.json**
`
"repository": {
    "type": "git",
    "url": "https://***/***.git" 
  },
`

I don't know what went wrong, the versions I'm using are up to date

**Comment by MatthijsBurgh** [comment]
I suggest you first clone https://github.com/nklayman/electron-auto-update-example and get that one working for you. So first get it working for publishing to a public repository. Then get it working for a private repository. Finally apply it to your own project.

**Comment by AutismPatient** [comment]
> 我建议你首先克隆https://github.com/nklayman/electron-auto-update-example并让那个为你工作。所以首先让它工作以发布到公共存储库。然后让它为私有存储库工作。最后将其应用到您自己的项目中。

I didn't find anything different, which made it impossible for me to determine the source of the problem

**Comment by MatthijsBurgh** [comment]
Please follow my suggestions. Start by publishing this example to a public repository.

When you don't want to do that, I can't help you.
