### ISSUE TITLE
The icon could not be applied

### ISSUE THREAD

**Issue by AutismPatient** [nklayman/vue-cli-plugin-electron-builder#1744]
![image](https://user-images.githubusercontent.com/37021551/169502742-09d7eef5-bbab-4855-9755-3490dace297c.png)

from： [icon](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#icons)

![image](https://user-images.githubusercontent.com/37021551/169502915-b34efbcb-00a1-4d7e-bee6-9a2dbf98acc9.png)

Did I put it in the wrong place? I think I need an answer 🤒

**Comment by MatthijsBurgh** [comment]
I think this is an issue in `electron-builder`. In this repo, there is no code managing the icon. It is in the docs, only to be more helpful.

**Comment by klren0312** [comment]
https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#icons

**Comment by MatthijsBurgh** [comment]
> It is in the docs, only to be more helpful.
@klren0312 Please elaborate on dropping just an url.

**Comment by klren0312** [comment]
try to move the `build` folder to root directory
