### ISSUE TITLE
Install the latest version of Electron?  Like electron 18,19,20

### ISSUE THREAD

**Issue by chenweihan** [nklayman/vue-cli-plugin-electron-builder#1761]
Hi   I plan to use the latest version of Electron, but run "vue add electron- Builder"
 

?  Choose Electron Version (Use arrow keys)
 

^ 11.0.0
 

^ 12.0.0
 

> ^ 13.0.0

How do I solve this problem? thank you

**Comment by MatthijsBurgh** [comment]
Edit it yourself afterwards.

When you want to use spectron for testing you are limited to electron 17/spectron 19.
