### ISSUE TITLE
ts-loader version problem

### ISSUE THREAD

**Issue by zwfengineer** [nklayman/vue-cli-plugin-electron-builder#1768]
![image](https://user-images.githubusercontent.com/33892516/172594759-48603531-2491-4557-bde9-e12c855430c2.png)
when i use default conig run electron:server 
,when i use ts-loader@8.2.0 no problem

**Comment by zwfengineer** [comment]
![image](https://user-images.githubusercontent.com/33892516/172595473-de583bde-dad9-44b2-a5e3-8a55b8ee5980.png)

**Comment by amanf244** [comment]
Same problem

**Comment by annymosse** [comment]
Same problem

**Comment by MatthijsBurgh** [comment]
Solution provided by https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1768#issuecomment-1182442312
