### ISSUE TITLE
CleanWebpackPlugin does not work

### ISSUE THREAD

**Issue by LoveCodingOnGithub** [nklayman/vue-cli-plugin-electron-builder#1782]
I use `vue-cli-plugin-electron-builder` in my project, but when I run `npm run electron:build` , the files still exist in the 'dist_electron' directory.  So I installed the `clean-webpack-plugin`.  But when I run the script again, it still doesn't work.  Then I run `npm run build` and it works well.  What should I do? 

This is the screenshot

![Snipaste_2022-06-22_11-24-33](https://user-images.githubusercontent.com/45458688/174937027-cdbc1558-b234-4780-9685-f9ecd53f258b.png)

**Comment by klren0312** [comment]
![image](https://user-images.githubusercontent.com/10903843/174952204-b6270930-f735-4105-b180-e16d6e70ddd9.png)
I think the `dist_electron` contains some files that used in development

if you need delete some old files, you can write code to delete

**Comment by LoveCodingOnGithub** [comment]
@klren0312 Ok , got it . Thanks , maybe I need to write a plugin to delete some useless files automatically or delete these files manually .

**Comment by MatthijsBurgh** [comment]
You can use `clean-webpack-plugin`, but you will need to configure it in `vue.config.js`. Or use `rimraf`, which you also need to configure. I suggest a `preelectron:build` script. But this is not related to this project. So closing this issue.
