### ISSUE TITLE
run in win7 xhr is slow ,win10 is ok

### ISSUE THREAD

**Issue by doublebody** [nklayman/vue-cli-plugin-electron-builder#179]
**Describe the bug**
win7 

**To Reproduce**
axios  xhr slow

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS and version:
 - node version: 
 - npm version:
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 
 - electron version:

 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**

win7:
![image](https://user-images.githubusercontent.com/18657535/50947135-c066d680-14d7-11e9-95c0-700f27bf2ff1.png)

win10:
![image](https://user-images.githubusercontent.com/18657535/50947286-74686180-14d8-11e9-81f9-0a71b324c399.png)

**Comment by nklayman** [comment]
Can you run in a clean Windows 7 environment? It is likely that there is some app interfering with the requests. Even if it is slow on Windows 7, it is the fault of Electron, rather than this plugin. If it is still slow in a clean environment, open an issue on Electron's github repo.

**Comment by nklayman** [comment]
I checked by running in a windows 7 vm, and the time was about the same for making 20 requests to google.com:
Windows 7:
![image](https://user-images.githubusercontent.com/12448243/51097773-861d6380-177b-11e9-9eeb-d9e1b68f9731.png)
Windows 10:
![image](https://user-images.githubusercontent.com/12448243/51097785-946b7f80-177b-11e9-80fb-244625a37231.png)
