### ISSUE TITLE
serialport module works on Linux but can't cross-compile for Windows

### ISSUE THREAD

**Issue by mwllgr** [nklayman/vue-cli-plugin-electron-builder#1792]
**Describe the bug**
When compiling a vue-cli-pl...-project for Windows via the suggested Docker-approach on a Ubuntu at https://www.electron.build/multi-platform-build.html#build-electron-app-using-docker-on-a-local-machine - it looks like it compiled everything alright, but then, it doesn't work on Windows.

I'm compiling for Windows using `yarn run electron:build --win`.
 
I'm wondering if it's normal that it does not use any prebuilt packages, but rather tries to rebuild them:
![Screenshot_20220705_225307](https://user-images.githubusercontent.com/25794895/177414896-99c6d199-f573-4523-a154-f5b18d70a302.png)

As soon as serialport is needed, the following error appears:
![Screenshot: Error in developer console](https://user-images.githubusercontent.com/25794895/177414321-56cb939c-3b7b-4e53-b111-3ad01150f71f.png)

I'm sorry if this is the wrong place to ask but I ran out of ideas on how to fix this.

Files/info that might be helpful:

- [package.json](https://p.kll.li/?4296d4715e31f82c#Bv287PP3aY9vuG1r1apwWuqQ8VU8hj6M6DzfHte3xLPW)
- [vue.config.js](https://p.kll.li/?15d5557037e044c3#g8JFYNEepjK27Z3vCCy1e3RnTjGFkDoN6zjyLGydWQj)
- Node v14.19.3
- NPM v6.14.17
- yarn v1.22.19
- Ubuntu 20.04

**Comment by MatthijsBurgh** [comment]
First try to get a simple project working without Vue and this package. So just `electron-builder` and the problematic `serialport` package. I can't help you for now.
