### ISSUE TITLE
exposeInMainWorld prevents to add classes.

### ISSUE THREAD

**Issue by sharifcse57** [nklayman/vue-cli-plugin-electron-builder#1810]
I am making an app which will store data as offline using sqlite3 database with sequelize plugin.

In sequelize all model is class based so I have to work with model classes and others.
I turned off nodeIntegration for security risk. So I can't find node environment in renderer process files. So for this reason I have to load sequelize file in preload.js and send it to renderer js file.

I know in contextBridge exposeInMainWorld documentation says I can't bind class to exposeInMainWorld. 

So how can I pass sequelize models to renderer js files while contextIsolation is true.

I can do that by turning off contextIsolation but I dont want to do that way. Can't think anything as I stuck on this.

**Comment by MatthijsBurgh** [comment]
This is really an electron question. Please revert to their documentation/support channels.
