### ISSUE TITLE
Update electron-builder to support macOS 12.3

### ISSUE THREAD

**Issue by YornQiu** [nklayman/vue-cli-plugin-electron-builder#1814]
building on macOS 12.3 thrown an error.

electron-builder need to be updated to 23.0.3.

Please refer this [issue](https://github.com/gravitational/webapps/pull/689) .

**Comment by megasanjay** [comment]
Also, a fork is available on #1680

**Comment by MatthijsBurgh** [comment]
`electron-builder` is updated to `^23.0.3` on the default branch of this repo. It is not released yet. And it will still take some to be released. But closing this as it is fixed on the default branch.
