### ISSUE TITLE
Attempt to access files in app.asar failed

### ISSUE THREAD

**Issue by Lee-42** [nklayman/vue-cli-plugin-electron-builder#1827]
**Describe the bug**
I use `unzip(join(__static, "zips/nt_demo_src.zip"), "/Volumes/T7/empty")` unzip an file。works in development mode。
But after I pack， It reported such an error。

![Xnip2022-08-31_09-40-01](https://user-images.githubusercontent.com/95179300/187574007-c8eb8539-3d5b-49be-9a35-76f37bec375e.jpg)

This error is issued by the compression module and will be thrown when the path is incorrect. So we can't access the files in the app.asar

**Comment by MatthijsBurgh** [comment]
Does the `zipPath` really exist?

**Comment by MatthijsBurgh** [comment]
Stale
