### ISSUE TITLE
How can i change app protocol back to file protocol

### ISSUE THREAD

**Issue by cxyao** [nklayman/vue-cli-plugin-electron-builder#183]
I'm using a commercial library, which's license key only support file protocol.
I did something to change app protocol to file protocol, but failed.
I did somthing blow:

```js
// vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      noAppProtocol: true
    }
  }
}
```
```js
// background.js
// Standard scheme must be registered before the app is ready
// protocol.registerStandardSchemes(['app'], {
//   secure: true
// })
const winURL =
  process.env.NODE_ENV === 'development'
    ? `http://localhost:8000`
    : `file://${__dirname}/index.html`

    // createProtocol('app')
    // Load the index.html when not in development
    // win.loadURL('app://./index.html')
    win.loadURL(winURL)
```
Error message:

Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec. 

FROM: js/app.0a0def40.js:1

**Environment:**
- node version: v10.0.0
- yarn version : 1.7.0
- vue-cli-plugin-electron-builder version : 1.0.0-rc.10
- electron version: 3.0.0

Any advice? Thanks.

**Comment by Wurielle** [comment]
One way to do it if you know where the file is located (e.g: in the userData folder) you could register a file protocol by adding:
```javascript
import {app, protocol} from 'electron';
import path from 'path';

app.on('ready', async () => {
    // Give a name to your protocol, here we'll use 'userdata'
    protocol.registerFileProtocol('userdata',
        (request, callback) => {
            const url = request.url.replace(/(^\w+:|^)\/\//, '');
            // Get the path to the folder containing what you need, here we'll use app.getPath('userData') to point to 'C:\Users\myUser\AppData\Roaming\myApp'
            callback({path: path.join(app.getPath('userData'), url)});
        },
        (error) => {
            if (error) console.error(error);
        }
    );
});
```
and then call your file using something like:
```javascript
const fileUrl = 'userdata://path/to/file.ext'
// Which will point to: C:\Users\myUser\AppData\Roaming\myApp\path\to\file.ext once interpreted by the renderer
```

However I second @cxyao and would also like to know how to switch back to the file protocol if possible.
There are cases where a path might be saved as absolute, for instance, if my app is in charge of backing up images, locations would be provided by the user and the images would need to be displayed in the app.

**Comment by nklayman** [comment]
See the [docs here](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#changing-the-file-loading-protocol). Make sure you upgrade to v1.0.0.

**Comment by cxyao** [comment]
> See the [docs here](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#changing-the-file-loading-protocol). Make sure you upgrade to v1.0.0.

Thanks @nklayman good job!

When revert back to file protocol with v1.0.0, I did something blow, and successed.
```js
// vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      customFileProtocol: './'
    }
  }
}
```
```js
// background.js
// ...
    win.loadURL(`file://${__dirname}/index.html`)
// ...
```
```js
electron:build --legacy
```

but still have a question about the [docs](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#changing-the-file-loading-protocol), "customFileProtocol" should be "myCustomProtocol://./" ?

**Comment by nklayman** [comment]
You're right! I fixed the docs now, thanks for letting me know.
