### ISSUE TITLE
vue-cli failed to install plugin electron-builder with node 18

### ISSUE THREAD

**Issue by acantepie** [nklayman/vue-cli-plugin-electron-builder#1836]
Hi,

**Describe the bug**
I can't install plugin electron-builder with vue-cli because i am using node 18

```
❯ vue add electron-builder

📦  Installing vue-cli-plugin-electron-builder...

yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "18.8.0"
error Found incompatible module.
```

Not sure, but i think it's because vue-cli try to install an old version of your plugin that required an old version of [@vue/cli-shared-utils](https://github.com/vuejs/vue-cli/tree/v5.0.3/packages/%40vue/cli-shared-utils) (that required a version of @achrinza/node-ipc@ not compatible with my node version)

**Env**
```
❯ vue info

Environment Info:

  System:
    OS: Linux 5.19 Arch Linux
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
  Binaries:
    Node: 18.8.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: Not Found
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.4.0 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.1.1 
    @vue/babel-plugin-transform-vue-jsx:  1.4.0 
    @vue/babel-preset-app:  5.0.8 
    @vue/babel-preset-jsx:  1.4.0 
    @vue/babel-sugar-composition-api-inject-h:  1.4.0 
    @vue/babel-sugar-composition-api-render-instance:  1.4.0 
    @vue/babel-sugar-functional-vue:  1.4.0 
    @vue/babel-sugar-inject-h:  1.4.0 
    @vue/babel-sugar-v-model:  1.4.0 
    @vue/babel-sugar-v-on:  1.4.0 
    @vue/cli-overlay:  5.0.8 
    @vue/cli-plugin-babel: ~5.0.0 => 5.0.8 
    @vue/cli-plugin-eslint: ~5.0.0 => 5.0.8 
    @vue/cli-plugin-router:  5.0.8 
    @vue/cli-plugin-vuex:  5.0.8 
    @vue/cli-service: ~5.0.0 => 5.0.8 
    @vue/cli-shared-utils:  5.0.8 
    @vue/compiler-core:  3.2.39 
    @vue/compiler-dom:  3.2.39 
    @vue/compiler-sfc:  3.2.39 
    @vue/compiler-ssr:  3.2.39 
    @vue/component-compiler-utils:  3.3.0 
    @vue/reactivity:  3.2.39 
    @vue/reactivity-transform:  3.2.39 
    @vue/runtime-core:  3.2.39 
    @vue/runtime-dom:  3.2.39 
    @vue/server-renderer:  3.2.39 
    @vue/shared:  3.2.39 
    @vue/web-component-wrapper:  1.3.0 
    eslint-plugin-vue: ^8.0.3 => 8.7.1 
    vue: ^3.2.13 => 3.2.39 
    vue-eslint-parser:  8.3.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  17.0.0 (15.10.0)
    vue-style-loader:  4.1.3 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: Not Found

```

**Comment by MatthijsBurgh** [comment]
@ivysrono although it is LTS, doesn't mean I have been able to get things working with node 18 yet. But I think the compatibility allows this package to be updated to the required version.

**Comment by MatthijsBurgh** [comment]
Current master uses `@achrinza/node-ipc@9.2.5`, which does support node 18. So problem should be solved.

**Comment by cpgb85** [comment]
I wouldn't say the problem is solved. I justed tried to install  this and it still uses v 9.2.2 which says it's not compatible with node 18

**Comment by MatthijsBurgh** [comment]
Did you try to install master or the latest release?

**Comment by cpgb85** [comment]
How do I Install master? Sorry for my ignorance

**Comment by MatthijsBurgh** [comment]
```json
"dependencies": {
  "package": "git://github.com/username/package.git#commit"
}
```
The `#commit` is optional and can be any version ref.

**Comment by Zhengkang-Zhang** [comment]
I've got the same question O__O "…

**Comment by Zhengkang-Zhang** [comment]
I've got the same question O__O "…

**Comment by cpgb85** [comment]
> > Would you provide new npm version?
> 
> I have no clue, what you want.

Something that is installable on the latest version of node.  Right now I have to add @alpha to my request in order to get this to work. @master used to work but that seems to have stopped working.

**Comment by Yumacorn** [comment]
I see that this thread is closed, but there was a comment last week by @cpgb85 so I'll drop my 2 cents here

There is a [StackOverflow answer](https://stackoverflow.com/questions/69665222/node-js-17-0-1-gatsby-error-digital-envelope-routinesunsupported-err-os/69746387#69746387:~:text=This%20might%20help.%20Add%20these%20scripts%20in%20the%20package.json%20file.) that allowed me to work, but it seems to be a hack rather than a solution. 

I'm still using Node 18.5.0, but the dependency will function as if you are on Node 17 and bypass the error.

**Comment by Franklyn-R-Silva** [comment]
Force Installation: Sometimes, installation can be forced even when errors occur. Try forcing the installation of the package using the following command:

`yarn add vue-cli-plugin-electron-builder -D --tilde --force`
