### ISSUE TITLE
How to replace loadURL with loadFile in production mode

### ISSUE THREAD

**Issue by JunzheFan** [nklayman/vue-cli-plugin-electron-builder#1837]
**Describe the bug**
I built my electron app with electron-build and passed NSIS options to generate a Window installer, I tested it on my Win11 machine everything was fine.  However, when I tested on another Win 10 machine, the app took like 7-9 seconds to load(i.e. time it took for `did-finish-load` electron-event to fire).  The screen was initially blank for 7~9 seconds after that the page immediately showed up 

I just use the default template generated by VCPLB to load the HTML in production mode as follows
```
    createProtocol('app')
    //Load the index.html when not in development
    mainWindow.loadURL('app://./index.html')
```
I tried to change the loadURL to loadFile method to see if it helped but this time app could not load the html, I assumed the path must be wrong but not sure how to determine where to find the index.html when it's being packaged
The index.html currently resides in the **public** folder, which is the same level as the **src** foler , the background.js is within the `src `folder
`  mainWindow.loadFile(path.join(__dirname, './index.html')) `  // none of these works
`      mainWindow.loadFile(path.join(__dirname, '../public/index.html'))`

I am using VCPEB version 2.1.1, thanks for the help

**Comment by MatthijsBurgh** [comment]
@JunzheFan did you solve the issue? If it the case, could you share the solution?

**Comment by peter-rb2** [comment]
@MatthijsBurgh Hi! , I successfully replaced the correct path using `loadFile` function, but unfortunately it didn't sovle that slow loading issue on specific version of Win10,  so i guess this is related to the electron itself not this plugin project?   I will submit an issue to electron I guess
