### ISSUE TITLE
When you start Electron, you get an error that the version of Node.js is not supported

### ISSUE THREAD

**Issue by kurohoan** [nklayman/vue-cli-plugin-electron-builder#1842]
When you start Electron, you get an error that the version of Node.js is not supported.

The operating system is Windows. When I update Node.js and do node -v, it shows v16.17.1. When I start it with npm run electron:serve, the following error appears again. What could be the cause? The following modules are used to start Electron. "vue-cli-plugin-electron-builder".

`You are running Node.js 12.14.1.
Playwright requires Node.js 14 or higher.
Please update your version of Node.js.`

**Comment by MatthijsBurgh** [comment]
I think there are multiple node versions on your system.

**Comment by kurohoan** [comment]
Where can I check?
 If I uninstall Node.js in v16.17.1, I also get an error when I start Electron that Node.js is missing.

**Comment by kurohoan** [comment]
I tried installing with nvm as a trial, but the error remains the same.

**Comment by kurohoan** [comment]
I am trying to use Playwright. This may be relevant to the linked article.

https://stackoverflow.com/questions/72325732/updating-nextjs-playwrights-nodejs-version

**Comment by MatthijsBurgh** [comment]
Try to print the node version in your scripts. Also try to print the path. Hopefully this gives a better insight.

Playwright is really finding a different node version. It isn't joking you.

**Comment by MatthijsBurgh** [comment]
> I am trying to use Playwright. This may be relevant to the linked article.
> 
> https://stackoverflow.com/questions/72325732/updating-nextjs-playwrights-nodejs-version

Are you using Vercel?

**Comment by kurohoan** [comment]
The direct cause is unknown, but it appears that the version of Electron was too old.

**Comment by stockersky** [comment]
New to Electron and I played around their [tutorial](https://www.electronjs.org/docs/latest/tutorial/tutorial-preload).
One point of this tutorial is to display Node, Chrome and Electron versions.

I am surprised to discover that Nodejs found by the main Process has never been installed on my machine (try on two laptops).

![image](https://user-images.githubusercontent.com/22478549/194525425-7d93bc2c-f64f-404e-bbd3-4e53753b75b0.png)

```
$ node -v
v16.17.1
```

Where does it get this node 14.16.0 ???

I am also wondering why is the Electron version supported by vue-cli-plugin-electron-builder  (v13.6.9) is so far from the current Electron Release ([Electron 21.0.1](https://www.electronjs.org/releases/stable#21.0.1).

**Comment by MatthijsBurgh** [comment]
Yes, good question. Sorry I can't help you with that.

About electron version see https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1761#issuecomment-1140226897 and https://github.com/nklayman/vue-cli-plugin-electron-builder/discussions/1824

**Comment by stockersky** [comment]
@MatthijsBurgh : Thanks for the trick !

By "do it manually", I guessed it meant edit the `package.json` :) !

Well, this is what I did then `yarn install` and here is the result :

![image](https://user-images.githubusercontent.com/22478549/194575395-c476f8f5-38a0-4a33-8078-596b80d2eb70.png)

The interesting part is the Nodejs version which has changed (look at my previous post in this thread)... But it still not the version installed on my system (16.17.1).

I really wonder where it's getting the value ???

Ah ! Chrome version has also changed (I think it's bundled with NodeJS) !!!
