### ISSUE TITLE
Custom `background.js|ts` directory

### ISSUE THREAD

**Issue by robertsLando** [nklayman/vue-cli-plugin-electron-builder#1843]
I would like to be able to place all electron related files inside a separete directory instead of `src`.

**Comment by MatthijsBurgh** [comment]
Sorry, this is not possible right now.  I think https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/ebb9183f4913f927d4e4f4eb1fbab61a960f7a09/index.js#L661 is the issue. Could be there are some other hidden issues.

Feel free to open a PR, which makes this configurable.

**Comment by robertsLando** [comment]
> Feel free to open a PR, which makes this configurable.

Would be really pleased to do it but I really have low time right now even for my own OSS projects, requires me to study the entire codebase. Also it's not that important was just a matter of taste in application structure, I personally prefer to keep things separeted
