### ISSUE TITLE
I'm trying to copy some files during the app installation to OS home path but isn't working

### ISSUE THREAD

**Issue by lucaslgr** [nklayman/vue-cli-plugin-electron-builder#1859]
**Description**
I'm trying a cross-platform way to have a folder named `resources` with some files available to the app use it. 

What I've tried:

1º - I put my `resource` folder into my `public` folder in the project because I noticed that everything into `public` directory will be available into `dis_electron/bundled` directory after run `npm run electron:build` as the image below:
![image](https://user-images.githubusercontent.com/30275723/197086378-3890bb01-965f-4d86-ac6b-963522de1e99.png)

2º - So, when the user open the application in the first time I create a folder `.simulans` into the path that I obtain using this `app.getPath("home")`.

3º - I run a code in `background.js` to move the `resources` folder with everything from `dis_electron/bundled` to the folder that I've created in step 2 using these code to get the paths:
- This to get the origin path:
`path.join(app.getAppPath(), "bundled", "resources")`
- This to get the destiny path:
`path.join(app.getPath("home"), ".simulans", "resources")`

This solution worked very well during the development process, when I've ran the `npm run electron:serve` and open the application the `resource` folder was moved to the path that I wanted. But now I'm currently generating my installers for linux and windows and after install it and open the app, the error of folder not found happens.

I've read a lot of stuff but I'm still confusing of how can I make it work. I'm not attached with this way, if there is a simple way to deal with that I'll try. I've read a lot about set the `extraFiles` property is this documentation, but I've tried it and didn't worked. 
- When I use `extraFiles` settings, where need to be my `resources` folders ? need to be into the public folder or out ? 
- And how can I access my `resources` files after the installation if I use `extraFiles`? Using `path.join(app.getAppPath(), "resources")` ?

Here is the info of my `package.json` file:
```
{
  "name": "simulans",
  "version": "1.0.0",
  "email": "lucaslgr1206@gmail.com",
  "author": "Lucas Guimarães da Rocha <lucaslgr1206@gmail.com>",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve --remote-debugging-port=9222",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps"
  },
  "main": "background.js",
  "dependencies": {
    "anim-event": "^1.0.17",
    "big.js": "^6.1.1",
    "core-js": "^3.6.5",
    "cssprefix": "^2.0.17",
    "eigen": "^0.2.0",
    "fs": "*",
    "fs-extra": "^10.1.0",
    "leader-line": "^1.0.5",
    "lodash.clonedeep": "^4.5.0",
    "m-class-list": "^1.1.10",
    "plain-draggable": "^2.5.14",
    "plotly.js-dist-min": "^2.6.3",
    "plotly.js-locales": "^2.8.1",
    "pointer-event": "^1.0.2",
    "vue": "^2.6.11",
    "vue-router": "^3.0.3",
    "vuex": "^3.4.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "^3.1.1",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "^3.0.5",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "electron": "^13.0.1",
    "electron-devtools-installer": "^3.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^6.2.2",
    "prettier": "^2.2.1",
    "skeleton-loader": "^2.0.0",
    "vue-cli-plugin-electron-builder": "~2.0.0",
    "vue-template-compiler": "^2.6.11"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended",
      "@vue/prettier"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {
      "prettier/prettier": 0
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
```

And my `vue.config.js` file:
```
module.exports = {
  pluginOptions: {
    electronBuilder: {
      preload: "src/backend/preload.js",
      nodeIntegration: false,
      contextIsolation: false,
      // Or, for multiple preload files:
      // preload: { preload: "src/preload.js", otherPreload: "src/preload2.js" },
      builderOptions: {
        productName: "simulans",
        appId: "lucaslgr.simulans",
        copyright: "Copyright © 2022 ${author}",
        dmg: {
          contents: [
            {
              x: 410,
              y: 150,
              type: "link",
              path: "/Applications"
            },
            {
              x: 130,
              y: 150,
              type: "file"
            }
          ]
        },
        directories: {
          output: "build"
        },
        fileAssociations: [
          {
            ext: "sml",
            role: "Editor",
            icon: "build/icons/icon.icns",
            description: "Circuito elétrico do simulador Simulans"
          }
        ],
        nsis: {
          //othersettings,
          perMachine: true
        },
        mac: {
          icon: "./src/assets/img/simulans-icon.ico"
        },
        win: {
          icon: "build/icons/icon.ico"
        },
        linux: {
          icon: "build/icons",
          target: [
            "deb",
            "snap"
          ]
        }
      }
    },
  },
  configureWebpack: {
    module: {
      rules: [
        {
          test: require("path").resolve(__dirname, "node_modules/leader-line/"),
          use: [
            {
              loader: "skeleton-loader",
              options: {
                procedure: (content) => `${content}export default LeaderLine`,
              },
            },
          ],
        },
      ],
    },
  },
};
```

This is my final project to be graduated in the university, I'm struggling to make it work. Thanks in advance!!

**Comment by MatthijsBurgh** [comment]
I am using `__static` in my `background.js`. It resolves to the public folder during development, but resolves to the bundled path in production.

`extraFiles` is a configuration of `electron-builder`, so you should check their docs. Otherwise stackoverflow probably has some info about it.

**Comment by lucaslgr** [comment]
I didn't understand. __static worked for both environments? production and development?

**Comment by MatthijsBurgh** [comment]
Yes `__static`, does work in both environments for me.

**Comment by MatthijsBurgh** [comment]
@lucaslgr Did it solve your issue?

Without response I am closing this in 3 days.
