### ISSUE TITLE
Build for Windows on Linux

### ISSUE THREAD

**Issue by Lanseuo** [nklayman/vue-cli-plugin-electron-builder#186]
**Describe the bug**
I am trying to build a Vue.js application for Windows (exe) on Linux Ubuntu. According to other issues I use the following command `npm run electron:build --win`. But I still get out an AppImage and a snap for Linux.

```
INFO Building app with electron-builder:
  • electron-builder version=20.38.5
  • packaging        platform=linux arch=x64 electron=3.1.3 appOutDir=dist_electron/linux-unpacked
  • building         target=snap arch=x64 file=dist_electron/schoolsen-sync-ui_0.1.0_amd64.snap
  • building         target=AppImage arch=x64 file=dist_electron/schoolsen-sync-ui 0.1.0.AppImage
```

**To Reproduce**
`npm run electron:build --win`

**Expected behavior**
Get an EXE that is runnable on Windows.

**Environment (please complete the following information):**
 - OS and version: Linux Ubuntu 18.04.1
 - node version: 10.12.0
 - npm version: 6.4.1
 - vue-cli-plugin-electron-builder version: 1.0.0-rc.10
 - electron version: 3.0.0

**Comment by nklayman** [comment]
Try `npm run electron:build -- --win`. Npm requires you place `--` before args that are to be passed to the script.

**Comment by hedii** [comment]
@nklayman put this somewhere in the docs please :)

**Comment by nklayman** [comment]
This is a known catch of NPM scripts. For all scripts, `--` must be added before args, as noted in the [official documentation](https://docs.npmjs.com/cli/run-script.html). I recommend using [yarn](https://yarnpkg.com) as the `--` is not required, among many other features.

**Comment by internetztube** [comment]
Please put that in the docs. That cost me 30 mins.
