### ISSUE TITLE
Is there any way to remove this source code in chrome/source/page?

### ISSUE THREAD

**Issue by aquarius-wing** [nklayman/vue-cli-plugin-electron-builder#1862]
Hi, I get this problem: how to remove this?

![CleanShot 2022-10-26 at 17 18 14@2x](https://user-images.githubusercontent.com/16633962/197987836-0f689c13-b68a-4943-9514-7242df70aa77.png)

This will expose my some typescript code in production mode.

Thanks.

**Comment by MatthijsBurgh** [comment]
I have no clue. I think this is a question for `electron-builder`

**Comment by aquarius-wing** [comment]
> 

I copy the link of file, which start with "webpack://"
Is there prossable the vue cli start the webpack dev server, and in the electron production, it still start the server?

**Comment by MatthijsBurgh** [comment]
Could please provide a bit more context. Too much information is much preferred over no/too less information.

**Comment by aquarius-wing** [comment]
Thanks for reply, here is my repository.

[electron-demo2](https://github.com/aquarius-wing/electron-demo2)

![CleanShot 2022-10-26 at 19 44 12@2x](https://user-images.githubusercontent.com/16633962/198017780-fd843345-15b6-4b56-9176-de59d71572d6.png)

The key problem is, no matter how encrypted and confused the code, the source code specially the typescript file, will display directaly.

**Comment by JunzheFan** [comment]
even though you can see the source code in the chrome development tool,  but in production mode the dev tool is not visible to the users,  is there any way you can force that dev tool to open during production?

**Comment by aquarius-wing** [comment]
> even though you can see the source code in the chrome development tool, but in production mode the dev tool is not visible to the users, is there any way you can force that dev tool to open during production?

I just want know is there any way to remove this, because my app is in the internel test stage now, so I need my user can open the devtool so help my find the bug....

**Comment by aquarius-wing** [comment]
I finnally understand how to fix.Just add this config:
```js
module.exports = defineConfig({
  productionSourceMap: false,
  //...
})
```
Why is this setting defaulted to true? Who would want a source map in a production environment?
I'm quite confused...
