### ISSUE TITLE
Empty page when app running

### ISSUE THREAD

**Issue by meverikxp** [nklayman/vue-cli-plugin-electron-builder#1867]
**Describe the bug**
Hello, I build exe file with electron:build but when I run it I see empty page, 
when I run electron:serve all is fine and my application works fine
I using Vue js 3 
Thank you

**Comment by MatthijsBurgh** [comment]
This is just way too less information to help you in any way.

Only the V3-alpha supports vue3. As it is still an alpha. I am not supporting it for now.

**Comment by meverikxp** [comment]
it's not alpha, but I found the problem. It was with router. 
Was
`const router = createRouter({
  history: createWebHistory(process.env.BASE_URL),
  routes
})
`
changed to
`const router = createRouter({
  history: createWebHashHistory(),
  routes
})`
And it start works. 
Thank you!
