### ISSUE TITLE
installVueDevtools is not exported

### ISSUE THREAD

**Issue by bruceauyeung** [nklayman/vue-cli-plugin-electron-builder#1869]
**Describe the bug**
looks like it's exported in master branch,but not in `3.0.0-alpha.4`

**Comment by MatthijsBurgh** [comment]
It is deprecated, see https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/6a7b3ab3d9f4dd2aa666cbcdc53fc71689f3cccd/lib/installVueDevtools/index.js#L23-L29

and 

https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-rc.4

**Comment by bruceauyeung** [comment]
[`https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-rc.4`](https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-rc.4) is not visible in [`https://github.com/nklayman/vue-cli-plugin-electron-builder/tags`](https://github.com/nklayman/vue-cli-plugin-electron-builder/tags) ,but it can be directly accessed, weird!

**Comment by MatthijsBurgh** [comment]
@bruceauyeung 
https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-rc.4 is both visible in the releases as tags list. I even checked in private mode, to be sure it is visible when logged in.

releases:
![image](https://user-images.githubusercontent.com/18014833/199936443-bb56f32e-c6bb-4fe1-a81e-80617261ece7.png)
tags:
![image](https://user-images.githubusercontent.com/18014833/199936513-a9991927-f7e8-49c2-b495-3dc69b791942.png)
