### ISSUE TITLE
Build for armv7l - from linux 64

### ISSUE THREAD

**Issue by InspireTheLostBoys** [nklayman/vue-cli-plugin-electron-builder#189]
Hi there,

I am struggling to change the settings of the electron-builder and would like some assistance on changing the output.

Electron-builder configuration used to be in package.json. I am struggling to find where i can change the build options.

Also, does the this plugin still support armv7l?

Thanks in advance

**Comment by deathblade89** [comment]
Please assist : Would like to configure manually a armv7l build for electron-builder, not sure how or where to configure this using this plugin

**Comment by deathblade89** [comment]
I have managed to package successfully for:
Windows
Linux 64

I am now trying to do the same for armv7l on Ubuntu 16.04. Seeing as the plugin does detect the correct architectures that it is running on, i assumed if i tried to run the build from a armv7l device that all would work.

However the ERROR i receive is : Unsupported Arch : arm

Looking at the electron-builder : Armv7l is definitely supported.

Can you please point me in the right direction?

By the way : I think your plugin is awesome, it solves so many configuration issues, except obviously the one i am posting for.

**Comment by deathblade89** [comment]
Will the plugin still look at the package.json file for build configurations?

**Comment by deathblade89** [comment]
Hi again,

So interestingly enough. The confusion comes in with armhf and arm7vl.
I think the quickest way around this is for me to build on a linux 64 for armv7l which used to work with electron-builder.

So if i could just get the place where i can configure my own build targets without it auto detecting that would be great. Thanks alot.

**Comment by nklayman** [comment]
See the [docs on configuring electron-builder](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#configuring-electron-builder) for instructions on where to place electron-builder configuration. Let me know if you have more questions.
