### ISSUE TITLE
native module issues ,can't  find the file specified

### ISSUE THREAD

**Issue by vjeson** [nklayman/vue-cli-plugin-electron-builder#190]
I use three native modules in my project , but I  always need to set externals section in vue.config.js ,or it won't work , In debug module , it works fine ,but when build with yarn electron:build ,  it always report 
"Could not load file or assembly 'file:///D:\electron\vuetsdemo\dist_electron\win-unpacked\resources\app.asar\node_modules\edge-cs\lib\edge-cs.dll' or one of its dependencies. 
I extracted the app.asar and make sure it's exist ,and the asarUnpack config also seems not effect. 

OS : windows windows 10
Node  : 10.15.0
Vue ClI : 3.4.0

`
electronBuilder: {
      externals: ['ffi','better-sqlite3','electron-edge-js'],
      builderOptions: {
        "asarUnpack": [
          "node_modules/ffi",
          "node_modules/ref",
          "node_modules/edge-cs",
          "node_modules/electron-edge-js",
          "node_modules/better-sqlite3"
        ]
        ]
      }
}
`
I want to migrate my project from https://github.com/SimulatedGREG/electron-vue to the plugin. All the 3 modules work fine in old project

**Comment by nklayman** [comment]
I get the same error on edge using electron-vue. Can you create a github repo using electron-vue and one with vue-cli-plugin-electron-builder and share them with me?

**Comment by vjeson** [comment]
It's really strange , I create a new project from simulatedgreg/electron-vue template , After build ， get the same error.  But my old project is working fine。 And I find a way to fix the issue .https://github.com/tjanczuk/edge/issues/411
use "asarUnpack": [ "node_modules/edge-cs/**","node_modules/electron-edge-js" ] and update js lib with .replace('app.asar', 'app.asar.unpacked'))
Another question when i set asarUnpack , the nodem_modules shouldn't be package into app.asar, but it still include it

**Comment by nklayman** [comment]
Seems like the issue is that `electron-edge-js` isn't including the built files. Try opening an issue on their repo.

**Comment by nklayman** [comment]
Or maybe electron-builder is failing to build the dep properly

**Comment by vjeson** [comment]
thanks for digging into the problem . you can close the issue now.
one suggestion  According to your document , we don't need to do nothing when build with native modules ,but now I must set externals configure when using native modules

**Comment by nklayman** [comment]
I try to detect native modules automatically. However, it doesn't work all that well. In the docs I say to add it to externals if it doesn't work.
