### ISSUE TITLE
.env config not working in main process for electron:build

### ISSUE THREAD

**Issue by hgl** [nklayman/vue-cli-plugin-electron-builder#191]
**To Reproduce**
add `VUE_APP_HOST=foo` to `.env`
add `throw new Error(process.env.VUE_APP_HOST);` to `background.js`
running `vue-cli-service electron:serve` gives `foo`
but running `vue-cli-service electron:build` and run the app gives `undefined`

**Expected behavior**
running `vue-cli-service electron:build` and run the app give `foo`

**Environment (please complete the following information):**
vue-cli-plugin-electron-builder 1.0.0

**Comment by nklayman** [comment]
Thanks for the report! I can't believe I missed that. Available in `v1.0.1`.
