### ISSUE TITLE
Are there any plans to support new Electron versions?

### ISSUE THREAD

**Issue by kurohoan** [nklayman/vue-cli-plugin-electron-builder#1916]
Currently, the latest version of Electron is v22.0.3.
Is there any plan to be able to install a newer Electron version, as the supported versions are considered to be quite old?

**Comment by MatthijsBurgh** [comment]
You can check my own project, https://github.com/tue-robotics/hero-dashboard, or PR #1875 to get to electron 17. The issue to go higher is spectron is not supported anymore, so you can't test anymore.

The migration to playwright is also difficult, as I experienced some difficulties with testing the build app. So yes things should work, But testing is limited and therefore, the library hasn't moved forward (yet).

**Comment by MatthijsBurgh** [comment]
But feel free to open PRs, if you are able to migrate stuff forward without reducing the tests.
