### ISSUE TITLE
Updating to vue-cli-plugin-electron-builder 1.0.0-rc.4 due to update to Electron 4.0.4 causes packaging to crash

### ISSUE THREAD

**Issue by adday** [nklayman/vue-cli-plugin-electron-builder#192]
ERROR  Error: Application entry file "dist_electron/bundled/background.js" in the "<removed_for_ip_reasons>/dist_electron/win-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.

**Expected behavior**
Update would not prevent building electron packager.

**Environment (please complete the following information):**
 - OS and version: Mac OS High Sierra 
 - node version: v10.11.0
 - npm version: 6.4.1
 - yarn version (if used): 1.10.1
 - vue-cli-plugin-electron-builder version : 1.0.0-rc.4
 - electron version: 4.0.4
 - other vue plugins used: 
    "@vue/cli-plugin-babel"
    "@vue/cli-plugin-eslint"
    "@vue/cli-service"
    "vue-cli-plugin-vuetify"
    "vue-template-compiler"
    "vue"
    "vue-clickaway2"
    "vue-shortkey"
    "vuetify"
    "vuex"
    "vuex-map-fields"

**Additional context**
I have tried all googleable fixes to this issue to no avail.

**Comment by nklayman** [comment]
Change the `main` field of your `package.json` to just `background.js`. See the [RC.4 release notes](https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v1.0.0-rc.4) for more info. Now that the plugin has hit `1.0.0`, there won't be any more breaking changes like that.
