### ISSUE TITLE
Module parse failed: Unexpected character '#'

### ISSUE THREAD

**Issue by AutismPatient** [nklayman/vue-cli-plugin-electron-builder#1924]
**Describe the bug**
npm run electron:serve
![image](https://user-images.githubusercontent.com/37021551/217203517-92ee2cc1-5170-49c2-9685-85981ede80f3.png)

**To Reproduce**
[good running](javascript:;)

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
```
module.exports = {
    lintOnSave: false,
    devServer: {
        port: 8089
    },
    pluginOptions: {
        electronBuilder: {
            preload: 'src/preload.js',
            builderOptions: {
                publish: [
                    {
                        provider: "github",
                        releaseType: 'release',
                        private: true,
                    }
                ],
                win: {
                    target: ['zip'],
                    icon: 'build/WeHub.png',
                },
                extraResources: [
                    "script/check_db_export.bat",
                    "releases.md",
                    "script/bc4svn.bat",
                    'build/WeHub.png',
                    'build/icon.png'
                ],
                extraFiles: [
                    {
                        'from': 'golang',
                        'to': 'golang',
                        "filter": ["**/*"]
                    }
                ],
                afterAllArtifactBuild: './script/AfterAllArtifactBuild.js',
                afterPack: './script/BeforeAllArtifactBuild.js',
            },
            outputDir: 'electron-output'
        }
    }
}
```

**Additional context**

I used the node native module，But it seems to have failed

**Comment by MatthijsBurgh** [comment]
This is a problem with webpack and `private class features` in a 3rdparty library you use in your project. (https://github.com/npm/make-fetch-happen/blob/cd1ddb4aa73c44a082d3f1d6076b08534c6d9853/lib/pipeline.js#L6)

I can not help you much with this. Check the following to figure out the solution.
https://github.com/webpack/webpack/issues/10216
https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#webpack-configuration
https://webpack.js.org/loaders/babel-loader/
https://babeljs.io/docs/en/babel-plugin-proposal-class-properties

**Comment by MatthijsBurgh** [comment]
Probably similar, not the same, solution required as https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1833

**Comment by AutismPatient** [comment]
[Thank you，brother.](javascript:;)    
![DF73DAD4](https://user-images.githubusercontent.com/37021551/217217164-fcff1443-4823-4a62-9d63-4ad30efc7b9a.png)

**Comment by AutismPatient** [comment]
![image](https://user-images.githubusercontent.com/37021551/217241171-90bd59c9-12d3-45e3-b09b-a9517b0b6cc5.png)

It doesn't seem to work ，I spent the whole day with no clue 
![DFFB41EA](https://user-images.githubusercontent.com/37021551/217248411-5e500e63-c1d9-44a9-91c4-ec1b05d4bebe.png)

**Comment by AutismPatient** [comment]
After all, this problem points to an environment where C++ compilation is not configured correctly
