### ISSUE TITLE
Is there a risk that the github token in vue.config.js can be analysed and viewed by the distributed production version?

### ISSUE THREAD

**Issue by kaede-labs-jp** [nklayman/vue-cli-plugin-electron-builder#1927]
Is there a risk that the github token in vue.config.js can be analysed and viewed by the distributed production version?
I would like to use this functionality with automatic updates.

**Comment by MatthijsBurgh** [comment]
I assume it is part of the `builderOptions`, so you should check the docs of `electron-builder`.

**Comment by kaede-labs-jp** [comment]
ok
