### ISSUE TITLE
Will vue's dependencies be packaged into the exe when packaging

### ISSUE THREAD

**Issue by fanchenio** [nklayman/vue-cli-plugin-electron-builder#1928]
I have this question, can anyone answer it for me?

**Comment by MatthijsBurgh** [comment]
Everything Vue needs is packaged.

**Comment by fanchenio** [comment]
> Vue 需要的一切都被打包了。

![image](https://user-images.githubusercontent.com/88647148/218037507-788786c2-11a5-4f42-81f4-dcad85a3f743.png)
Does this exe file contain vue dependencies?

**Comment by fanchenio** [comment]
@MatthijsBurgh

**Comment by MatthijsBurgh** [comment]
@fanchenio no need to tag me.
Yes, it is a standalone exe. It doesn't need any external files to run.

**Comment by fanchenio** [comment]
So wouldn't this cause redundant dependencies? exe itself does not need vue dependencies, only app.asar really needs vue dependencies.

**Comment by MatthijsBurgh** [comment]
The exe is just a bundled version of everything else in that folder. So you can check what is packaged. It should only package all the stuff it needs, no extra stuff.
