### ISSUE TITLE
How exclude file in public from reload

### ISSUE THREAD

**Issue by Nisgrak** [nklayman/vue-cli-plugin-electron-builder#193]
Hi!

I tried this:

```js
// vue.config.js

module.exports = {
	configureWebpack: {
		watchOptions: {
			ignored: /library\.json/
		}
	}
}
```

But didn't work, and I don't know if I need change webpack or other options.

Thanks :)

**Comment by nklayman** [comment]
The dev server implementation is handled by vue-cli as it is the same as the one used in a regular `serve`. Open an issue on the [vue-cli github repo](https://github.com/vuejs/vue-cli) instead, as that is where the dev server code is. You may want to look at the [vue cli docs for configuring the dev server](https://github.com/vuejs/vue-cli). I'm not sure how to solve your problem though.
