### ISSUE TITLE
Bump electron-builder to ^23.6.0 | 3.0.0-alpha.4 

### ISSUE THREAD

**Issue by palmtown** [nklayman/vue-cli-plugin-electron-builder#1931]
**Describe the bug**
Please bump electron-builder to ^23.6.0 as 3.0.0-alpha.4 installs 22.14.13 by default.  

**To Reproduce**
Install 3.0.0-alpha.4

**Expected behavior**
electron-builder 23.6.0 installed 

**Screenshots**

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 
 - terminal output from running `vue info`:

**Additional context**

**Comment by MatthijsBurgh** [comment]
No support for alpha releases.  I am working on vue2 in combination with playwright.

After which i maybe get working on a vue3 version of it.
