### ISSUE TITLE
How can private repositories be securely and automatically updated?

### ISSUE THREAD

**Issue by kaede-labs-jp** [nklayman/vue-cli-plugin-electron-builder#1932]
Is there a way to implement automatic updates to a private repository using AutoUpdater without having to include the github token in the file?

Also, I have tried Nuts on Heroku, but which files should be uploaded manually to Github Release?
Are there other files that should be uploaded besides the exe file?
If possible, I would like to release this automatically too, but is this difficult due to security reasons?

**Comment by MatthijsBurgh** [comment]
This project mainly brings multiple systems together. Support will be provided for any issue in combining these systems.

This is an feature of electron-builder. You also commented on #1157. Which has two links provided to get stuff working. For such specific questions, you need to contact the maintainers of electron-builder.

**Comment by kaede-labs-jp** [comment]
Apologies.
We had posted the information to the wrong address.
