### ISSUE TITLE
`.env` config not work in main process for build bundle(vue-cli-service electron:build --dir)

### ISSUE THREAD

**Issue by dongsir** [nklayman/vue-cli-plugin-electron-builder#194]
**Describe the bug**
`.env` config not work in main process for build bundle(vue-cli-service electron:build --dir), but it can work in serve bundle(vue-cli-service electron:serve). 
  It also work in render process whether build bundle or  serve bundle

**To Reproduce**
* create `.env` in project root
* create and set a env, example `VUE_APP_TITLE=Electron`
* build and run, try output `process.env.VUE_APP_TITLE` in background.js

**Expected behavior**
Can output `Electron` of `process.env.VUE_APP_TITLE` in main process for  build bundle

**Environment (please complete the following information):**
* OS and version: windows 10
* Node version: v10.150
* npm version: 6.4.1
* vue-cli-plugin-electron-builder version : ^1.0.0

**Comment by nklayman** [comment]
Duplicate of #191, fixed in `v1.0.1`.
