### ISSUE TITLE
Transferring this repo?

### ISSUE THREAD

**Issue by MatthijsBurgh** [nklayman/vue-cli-plugin-electron-builder#1942]
@nklayman As you don't support this repo anymore. Would you be willing to transfer this repo to me?

P.S. I sent you an email with more details about it.

**Comment by kennethtussey-gryfn** [comment]
1 year anniversary of this issue- any word back from the owners @MatthijsBurgh ?

**Comment by MatthijsBurgh** [comment]
I forked it and continued on my own version, https://github.com/MatthijsBurgh/vue-cli-plugin-electron-builder
