### ISSUE TITLE
Lost hot reloading?

### ISSUE THREAD

**Issue by PaulBernier** [nklayman/vue-cli-plugin-electron-builder#195]
**Describe the bug**
When launching the app in dev mode (`npm start electron:serve`) I get this warning:
```bash
WARNING  Compiled with 1 warnings                                                                                                                                                                5:39:30 PM

 warning  in ./node_modules/write-file-atomic/index.js

Module not found: Error: Can't resolve 'worker_threads' in '/home/paul/factom/fat-wallet/node_modules/write-file-atomic'
```
As a consequence it seems that the hot reloading is not working.

**To Reproduce**
I have version 1.01. of vue-cli-plugin-electron-builder, version 4.0.5 of Electron. I just run `npm start electron:serve`. Repo is here: https://github.com/Factom-Asset-Tokens/wallet/tree/development

**Expected behavior**
Hot reloading working (modifying a .vue file should reload the app content)

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS and version: Ubuntu 18.04.2 LTS
 - node version: 10.15.1 (LTS)
 - npm version: 6.4.1
 - yarn version (if used): N/A
 - vue-cli-plugin-electron-builder version :  1.0.1
 - electron version: 4.0.5
 - other vue plugins used: vuex, vuetify
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: https://github.com/Factom-Asset-Tokens/wallet/tree/development

**Additional context**
It used to work... I cannot pinpoint at which point it broke though...

**Comment by PaulBernier** [comment]
Ok it seems hot reloading is working (sometimes) so it may be an unrelated problem. I don't know if you still want to investigate that warning. If not, you can resolve this issue. Thanks.

**Comment by beatgates** [comment]
I second that. v1.0.0 was good but after updated to 1.0.1, I have to constantly run npm electron:serve to get changes shown.
OS: Windows 7
electron: 4.04 + node v10.11.0

**Comment by nklayman** [comment]
@PaulBernier When I try and install deps on your repo, it goes in an infinite loop of `cd fat-js && npm install`. let me know when you fix this so I can debug the issue. @beatgates The only change from 1.0.0 -> 1.0.1 is a fix with `VUE_APP` env vars not being available in builds. Chances are it was another dep updating.

**Comment by PaulBernier** [comment]
Erf sorry about that @nklayman the build instructions in the README were building the master branch which is not relevant, you need to checkout the development branch. The revised instructions are:
```bash
git clone https://github.com/Factom-Asset-Tokens/wallet.git fat-wallet
cd fat-wallet
git checkout development
npm install
npm run electron:build
```

**Comment by ppulwey** [comment]
May be related.

Win10, Fresh project with TypeScript (Tried Electron 3 and 4 => Same result).
No error on build.

![image](https://user-images.githubusercontent.com/20904579/53006361-5d9d1f00-3435-11e9-9ba3-24ee85d8550b.png)

**Comment by nklayman** [comment]
@ppulwey What happens when you run a regular `serve`? The hot reload is all handled by vue cli.

**Comment by nklayman** [comment]
@PaulBernier The hot reload is working fine for me. I am Linux as well (ubuntu 18.10). Try re-installing deps `rm -rf node_modules && npm i`. I am running the same version of node, but my npm version is `6.8.0`.

**Comment by PaulBernier** [comment]
Yes, as of now I cannot reproduce the hot reloading issue. I thought that warning during the build could have been related to what I was experiencing. Still not sure what that warning is about. Anyway I'm good on my side, thank you.

**Comment by ppulwey** [comment]
Seems that this is a problem with the company's network / pc. This is working fine on my Mac at home.
But I think this will not happen when electron will use localhost to show the App.
@nklayman Is there a reason this is not running on localhost?

**Comment by nklayman** [comment]
No idea. Localhost should be used. The plugin uses whatever vue cli gives it, which is usually localhost:8080.
