### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Anu1601CS** [nklayman/vue-cli-plugin-electron-builder#198]
**To Reproduce**

Try to build app.
`npm run electron:build`

**Expected behavior**
Build successful.

**Screenshots**

![screenshot from 2019-02-19 00-43-55](https://user-images.githubusercontent.com/30978328/52972013-7844a900-33df-11e9-8ff7-c116bdde6d07.png)

**Environment (please complete the following information):**
https://github.com/lazyDrive/drive

**Additional context**

**Comment by nklayman** [comment]
Move `electron` from `dependencies` to `devDependencies`, and remove the `directories` field of your `package.json`. If you need the `directories` field of your `package.json` for something else, open an issue on [electron-builder's repo](https://github.com/electron-userland/electron-builder) instead, as that is what is throwing the error.

**Comment by Anu1601CS** [comment]
Thanks @nklayman
