### ISSUE TITLE
Configuration option to install additional devtools extensions

### ISSUE THREAD

**Issue by smackesey** [nklayman/vue-cli-plugin-electron-builder#199]
**Is your feature request related to a problem? Please describe.**
I am trying to use the Apollo devtools extension in my app. I looked into how to include them in an Electron app and discovered [electron-devtools-installer]() (EDI). The docs for `vue-cli-plugin-electron-builder` mention that EDI is used to automatically install the Vue devtools. And the EDI docs show that it is easy to install multiple extensions. But I am not sure how to add the Apollo devtools to the extensions that `vue-cli-plugin-electron-builder` installs.

**Describe the solution you'd like**
A configuration option allowing the specification of additional devtools extensions to install.

**Describe alternatives you've considered**
I tried installing EDI and putting the following code in my `main.js`, but it threw an error. Not sure what else to do.

```
import installExtension, {
  APOLLO_DEVELOPER_TOOLS
} from 'electron-devtools-installer'

installExtension(APOLLO_DEVELOPER_TOOLS)
  .then((name) => console.log(`Added extension: ${name}`))
  .catch((err) => console.log('An error occured: ', err))
```

**Comment by nklayman** [comment]
Move the `installExtension(...` to after where vue devtools are installed (line #58).
