### ISSUE TITLE
npm run serve:electron fails on macOS

### ISSUE THREAD

**Issue by teddylindsey** [nklayman/vue-cli-plugin-electron-builder#2]
Running `npm run serve:electron` works fine on Windows but fails on macOS with the following error:
```
Error: spawn /Users/tlindsey/gitlab/project-name\node_modules\.bin\electron-webpack ENOENT
```

It appears that there are backslashes in the path which I suspect is part of the problem.

**Comment by nklayman** [comment]
Yah, that makes sense. I will fix it later today.

**Comment by teddylindsey** [comment]
Awesome, thanks!
