### ISSUE TITLE
eletron:build 

### ISSUE THREAD

**Issue by lytian** [nklayman/vue-cli-plugin-electron-builder#200]
**Describe the bug**
!include: could not find: "E:\WorkFile\xxxx\node_modules\app-builder-lib\templates\nsis\include\StdUtils.nsh"
Error in script "<stdin>" on line 1 -- aborting creation process

**To Reproduce**
1. yarn eletron:build
2. Error: C:\Users\Vincent\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.3.2\Bin\makensis.exe exited with code 1
        Output:
Command line defined: "APP_ID=com.iwiteks.hryoa"
Command line defined: "APP_GUID=805fa2f0-037f-5a40-9517-6a6c9fb56601"
Command line defined: "UNINSTALL_APP_KEY=805fa2f0-037f-5a40-9517-6a6c9fb56601"
Command line defined: "PRODUCT_NAME=����ԴOA"
Command line defined: "PRODUCT_FILENAME=����ԴOA"
Command line defined: "APP_FILENAME=iwiteks_admin_for_hry"
Command line defined: "APP_DESCRIPTION="
Command line defined: "VERSION=0.8.0"
Command line defined: "PROJECT_DIR=E:\WorkFile\�������Դ�ز�\iwiteks_admin_for_hry"
Command line defined: "BUILD_RESOURCES_DIR=E:\WorkFile\�������Դ�ز�\iwiteks_admin_for_hry\build"
Command line defined: "MUI_ICON=E:\WorkFile\�������Դ�ز�\iwiteks_admin_for_hry\public\favicon.ico"
Command line defined: "MUI_UNICON=E:\WorkFile\�������Դ�ز�\iwiteks_admin_for_hry\public\favicon.ico"
Command line defined: "APP_64=E:\WorkFile\�������Դ�ز�\iwiteks_admin_for_hry\dist_electron\iwiteks_admin_for_hry-0.8.0-x64.nsis.7z"
Command line defined: "APP_64_NAME=iwiteks_admin_for_hry-0.8.0-x64.nsis.7z"
Command line defined: "APP_64_HASH=9DDDA63369C14F0401C8A8B0BAD12572FD62CB40CBDCAA950335A410A4E3B926321664701C09517040A60140BC44DAFA6F97E1F0563FD18CA60CA3545253D4CC"
Command line defined: "APP_PRODUCT_FILENAME=����ԴOA"
Command line defined: "APP_INSTALLER_STORE_FILE=iwiteks_admin_for_hry-updater\installer.exe"
Command line defined: "COMPRESSION_METHOD=7z"
Command line defined: "MULTIUSER_INSTALLMODE_ALLOW_ELEVATION"
Command line defined: "INSTALL_MODE_PER_ALL_USERS_REQUIRED"
Command line defined: "SHORTCUT_NAME=����ԴOA"
Command line defined: "UNINSTALL_DISPLAY_NAME=����ԴOA 0.8.0"
Command line defined: "MUI_WELCOMEFINISHPAGE_BITMAP=${NSISDIR}\Contrib\Graphics\Wizard\nsis3-metro.bmp"
Command line defined: "MUI_UNWELCOMEFINISHPAGE_BITMAP=${NSISDIR}\Contrib\Graphics\Wizard\nsis3-metro.bmp"
Command line defined: "ESTIMATED_SIZE=229873"
Command line defined: "COMPRESS=auto"
Command line defined: "BUILD_UNINSTALLER"
Command line defined: "UNINSTALLER_OUT_FILE=E:\WorkFile\�������Դ�ز�\iwiteks_admin_for_hry\dist_electron\.__uninstaller-nsis-iwiteks_admin_for_hry.
exe"
Processing config: C:\Users\Vincent\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.3.2\nsisconf.nsh
Processing script file: "<stdin>" (ACP)

  Error output:
!include: could not find: "E:\WorkFile\xxxx\node_modules\app-builder-lib\templates\nsis\include\StdUtils.nsh"
Error in script "<stdin>" on line 1 -- aborting creation process

    at ChildProcess.childProcess.once.code (E:\WorkFile\xxxx\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5) 

**Environment (please complete the following information):**
 - node version:  10.15.1
 - npm version:  6.4.1
 - yarn version (if used): 1.9.4
 - vue-cli-plugin-electron-builder version : 1.0.2
 - electron version:  4.0.0
 - other vue plugins used:   cli-plugin-eslint
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**

**Comment by nklayman** [comment]
Does this happen on a clean project as well? The error is thrown by [electron-builder](https://electron.build). You should open an issue on [their repo](https://github.com/electron-userland/electron-builder) instead.

**Comment by Jerryz0312** [comment]
ok
