### ISSUE TITLE
Module parse failed: Unexpected token (36:11) You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by dongsir** [nklayman/vue-cli-plugin-electron-builder#204]
**Describe the bug**
Build failed with errors.(npm run electron:serve) when use ES6 class properties in background.js

Error info:
```
Module parse failed: Unexpected token (36:11)
You may need an appropriate loader to handle this file type.
|
| class DataStroe {
>   datastore;
|
|   constructor() {

 @ ./src/background.js 7:0-47 33:22-31
```

**To Reproduce**

in background.js

```
class DataStroe {
  datastore;

  constructor() {
  }
}
```

**Expected behavior**
can build sucessfully

**Environment (please complete the following information):**
* OS and version: windows 10
* Node version: v10.150
* npm version: 6.4.1
* vue-cli-plugin-electron-builder version : ^1.0.1

**Comment by dongsir** [comment]
It work well in App.vue
```
<script>
class DataStroe {
  datastore;

  constructor() {
    return {};
  }
}
export default {
  mounted() {
    let ds = new DataStroe();
  },
};
</script>
```

**Comment by nklayman** [comment]
This is because [field declarations are an experimental feature](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Field_declarations). It has to be transpiled with [babel](https://babeljs.io/) to be used. See [the docs on webpack configuration](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#webpack-configuration) if you want to add babel to the main process webpack config.

**Comment by nklayman** [comment]
set your `vue.config.js` to this:
```javascript
// vue.config.js

module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['electron'],
      chainWebpackMainProcess: config => {
        config.module
          .rule('babel')
          .test(/background\.js$/)
          .use('babel')
          .loader('babel-loader')
          .options({
            presets: [['@babel/preset-env', { modules: false }]],
            plugins: ['@babel/plugin-proposal-class-properties']
          })
      }
    }
  }
}
```

**Comment by dongsir** [comment]
@nklayman  Thank you!

**Comment by rathboma** [comment]
@nklayman this doesn't seem to work for me? Did something change in the version 2.0 release?

**Comment by snapxtp** [comment]
@nklayman  My config file still fails for the files I import into the background.js file as below.
 
My error:
in ./src/data/store.js

Module parse failed: Unexpected token (8:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| class MainStore {
>    group = [];
|     groupUsers = [];
|     activeUser = {};

MY vue.config.js

module.exports = {
  "transpileDependencies": [
    "vuetify"
  ],
  runtimeCompiler: true,
  css: {
    loaderOptions: {
      scss: {
        prependData: `@import "@/assets/scss/variable.scss";`
      }
    }
  },
  pluginOptions: {
    electronBuilder: {
      chainWebpackMainProcess: config => {
        config.module
          .rule('babel')
          .test(/background\.js$/)
          .use('babel')
          .loader('babel-loader')
          .options({
            presets: [['@babel/preset-env', { modules: false }]],
            plugins: ['@babel/plugin-proposal-class-properties']
          })
      },
      nodeIntegration: true,
      externals: ['serialport', 'usb', 'escpos'],
      builderOptions: {
        mac: {
          icon: './src/icons.icns'
        },
        win: {
          icon: './src/icons.ico'
        }
      }
    }
  }
}
