### ISSUE TITLE
Renderer Main Folder Structure

### ISSUE THREAD

**Issue by RacerDelux** [nklayman/vue-cli-plugin-electron-builder#205]
One thing I liked about SimulatedGREG/electron-vue was that it kept the main and rendered files in separate folders on generation. I think this is a better practice, as the main and rendered can not directly communicate (via an import or something).
![image](https://user-images.githubusercontent.com/2667344/53188129-578c7700-35ca-11e9-8102-56224b8d5616.png)
On a separate note, if I wanted to modify the structure to move the nodejs files into a main folder and the vue files into a render folder, what all would need to be changed in the configs?

**Comment by nklayman** [comment]
There are two reasons I don't have it in separate folders:
1. Vue cli has a pretty strict folder structure, and I don't think it will play nice with everything moved into a `renderer` folder
2. For most projects, the `background.js` is just a single file with little added logic.

You can always change the main process file like so:
```javascript
// vue.config.js

module.exports = {
  pluginOptions: {
      mainProcessFile: 'src/main/index.js',
    }
  }
}
```
If you can find a way to change the main directory of the Vue app code, then you can create the two-directory structure for your own projects. [This issue](https://github.com/vuejs/vue-cli/issues/2179) might help you set this up. [this issue](https://github.com/vuejs/vue-cli/issues/3061) may be useful as well.

**Comment by RacerDelux** [comment]
Got it, thanks. Moving the main files to their own folder should be enough as well. As long as I can add some sort of physical separation.

**Comment by alexpopovme** [comment]
I have this two-folder structure: **application**, **client**.
For the main process, I've set config as @nklayman mentioned.
And my vue.conf.js changes for vue app files:
```Javascript
module.exports = {
  chainWebpack: config => {
    config
      .entry('app')
      .clear()
      .add('./src/client/main.js')
  }
}
```

**Comment by patarapolw** [comment]
This isn't working,

```javascript
module.exports = {
  pluginOptions: {
    mainProcessFile: 'src/main/background.ts',
  },
  pages: {
    index: 'src/renderer/main.ts'
  }
}
```

```
This dependency was not found:

* /Users/patarapolw/GitHubProjects/r2r-app/app/src/background.ts in multi ./src/background.ts

To install it, you can run: npm install --save /Users/patarapolw/GitHubProjects/r2r-app/app/src/background.ts
```

In short, I cannot rename, nor move `background.ts`.

**Comment by patarapolw** [comment]
I can rename main process, but I have to tweak it a bit (and look up the source code).

```javascript
module.exports = {
  pluginOptions: {
    electronBuilder: {
      mainProcessFile: './src/main/main.ts'
    }
  },
  pages: {
    index: './src/renderer/main.ts'
  }
}
```
