### ISSUE TITLE
Fonts are loaded in serve mode, but are missing after build.

### ISSUE THREAD

**Issue by codenotfound** [nklayman/vue-cli-plugin-electron-builder#206]
Hello,

In serve mode the fonts are loading correctly, with paths like `http://localhost:8080/fonts/TeleGroteskNext-RegularItalic.79b7745c.woff2`, but after build they can't be reached on paths like `app://fonts/TeleGroteskNext-RegularItalic.79b7745c.woff2`.

Even though font files appear in dist_electron/bundled folder correctly.

What could be the issue? 

**Environment:**
 - OS and version: Win 10 x64
 - node version: v10.11.0
 - npm version: 6.4.1
 - yarn version (if used): 1.13.0 
 - vue-cli-plugin-electron-builder version : 1.0.4
 - electron version: 3.0.0
 - other vue plugins used: 
    "@kazupon/vue-i18n-loader": "^0.3.0",
    "@vue/cli-plugin-e2e-nightwatch": "^3.0.0-beta.15",
    "@vue/cli-plugin-typescript": "^3.0.0-beta.15",
    "@vue/cli-plugin-unit-jest": "^3.0.0-beta.15",
    "@vue/cli-service": "^3.0.0-beta.15",
    "@vue/test-utils": "^1.0.0-beta.16"

Thanks, 
Dmitry

**Comment by nklayman** [comment]
Can you create a small demo repo with the fonts imported and working on a serve?

**Comment by codenotfound** [comment]
`app://./fonts/TeleGroteskNext-Regular.woff2`
this type of path worked
Anyways, probably not an issue with the plugin. Can be closed.

**Comment by nklayman** [comment]
Electron has to use relative paths, otherwise it will look for files in the root of your C drive.

**Comment by cristi9flavors** [comment]
I am having the same issue. How did you changed the path?
