### ISSUE TITLE
How to configure to package a precompiled binary?

### ISSUE THREAD

**Issue by PaulBernier** [nklayman/vue-cli-plugin-electron-builder#207]
Let's say I have a daemon app, and I have pre compiled binaries for windows, macOs and linux. How/where do I configure the project to include those binaries in the app so I can spawn the daemon from the Electron app?

**Comment by nklayman** [comment]
Try putting them inside the `public` folder. Then execute them via `child_process.execFile`, with the path being `path.join(__static, 'fileName.bat/sh')`. See [this issue](https://github.com/electron/electron/issues/3512) for more details.

**Comment by PaulBernier** [comment]
Thanks for the suggestion! I put the daemon binary in `public` folder and added this code to `background.js`: 
```javascript
import { join } from 'path'
import { execFile } from 'child_process'
const file = join(__static, 'factom-walletd')

execFile(file, [], (error, stdout, stderr) => {
  if (error) {
    throw error;
  }
  console.log(stdout);
});
```

- This does work when running `electron:serve`
- This **does not** work when the application is packaged in a AppImage binary (Ubuntu). I can tell the daemon is not started as I cannot reach the API it's supposed to expose. Not sure how to debug more than that.
- The daemon binary is 18Mb and I noticed that the AppImage binary size only increase by 8Mb after adding the binary in the `public` folder. Quite puzzling...

**Comment by PaulBernier** [comment]
Ok I confirmed the daemon is packaged in the app. The problem seems to be an EACCES error. I will figure it out, thanks.

**Comment by nklayman** [comment]
Files inside an asar are read only, that could be your issue.

**Comment by UnendingGlory** [comment]
Hi, i have come across the same problem.
I have put my precompiled binary under the public folder and used the `execFile`.
It worked well while in developing, but after building, execFile threw an `Uncaught Error: spawn EACCES`.
How can i figure it out?
