### ISSUE TITLE
electron-builder ignores build config

### ISSUE THREAD

**Issue by moeen** [nklayman/vue-cli-plugin-electron-builder#208]
According to [your documentation](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#configuring-electron-builder), I added some configs in my `vue.config.js`.
But it seems that electron-builder is ignoring this config.

Build log: https://travis-ci.org/moeen/ganjoor-electron/builds/500725943
Repo: https://github.com/moeen/ganjoor-electron

**Comment by nklayman** [comment]
All of the electron builder config has to go inside `builderOptions` which is inside of `electronBuilder` this is to tell the difference between electron builder config and config for this plugin.

**Comment by nklayman** [comment]
Also, i think you need to replace `window` with `win`.
