### ISSUE TITLE
Failed to execute 'fetch' on 'Window' with node-gitlab

### ISSUE THREAD

**Issue by patrickalima98** [nklayman/vue-cli-plugin-electron-builder#210]
**Describe the bug**
When using the node-gitlab module the xmlHttpRequest request is not working, it displays the following error

**To Reproduce**
1- Create a new application with TypeScript
2- Install node-gitlab with `npm install gitlab@next`
3- Import on anything file vue with `const {Gitlab} = require('gitlab');`
4- Start a new connection:
```
// Instantiating
const api = new Gitlab({
  host:   'http://example.com', // Defaults to https://gitlab.com
  token: 'abcdefghij123456'	// Can be created in your profile.
})
```
5- Call a Api:
```
api.Projects.all({ maxPages:1, perPage:40 });
```

**Expected behavior**
A json return with 40 projects

**Screenshots**
![image](https://user-images.githubusercontent.com/17622137/53828013-42650000-3f5b-11e9-928a-f02dee6acdf3.png)

**Environment (please complete the following information):**
 - OS and version: Windows 10
 - node version: 11.4.0
 - npm version: 6.4.1
 - vue-cli-plugin-electron-builder version : 1.0.0
 - electron version: 4.0.4

Any ideia how to fix this?

**Comment by nklayman** [comment]
Can you create a demo repository that fails? When I follow your reproduction instructions, it works fine.

**Comment by nklayman** [comment]
```js
import Gitlab from "gitlab";
const api = new Gitlab({
  token: "ACCESS_TOKEN" // Can be created in your profile.
});
api.Projects.all({ maxPages: 1, perPage: 40 }).then(data => {
  console.log(data);
});
```

**Comment by patrickalima98** [comment]
@nklayman the demo repository is here:
https://github.com/patrickalima98/gitlab-electron-vue/

The project is using typescript and gitlab @ next, there was a failure copying the url from it, I corrected it in the instructions to reproduce

**Comment by nklayman** [comment]
The error appears when running in the browser as well. This is probably an issue with gitlab, not this plugin. Open an issue there instead.
