### ISSUE TITLE
Build renderer process only

### ISSUE THREAD

**Issue by romansp** [nklayman/vue-cli-plugin-electron-builder#212]
**Is your feature request related to a problem? Please describe.**
I'm building an app that runs both in electron and in browser. But when in electron, app is also served from publicly hosted files. For it to work properly it should be separately bundled via webpack's `target: electron-renderer` in mind. In other words regular browser loads `host.com/app/index.html`, but renderer goes to `host.com/electron/index.html`.

**Describe the solution you'd like**
I would like a command-line switch like `--skipBundle`, or an option inside `pluginOptions` configuration object, to skip `electron-builder` step completely.

**Describe alternatives you've considered**
I've considered creating dedicated `vue.config.js` for building app process and targeting `electron-renderer`, and all other required things. But it will the same this already plugin does over there and below. So why reinvent? https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/e99bba0f056b2b970b9508c3474163d24f79b778/lib/webpackConfig.js#L9-L14

**Additional context**
I already use undocumented `bundleMainProcess: false` to skip bundling of main process. Please keep it 👍.

**Comment by nklayman** [comment]
What you can do is `require` the `lib/webpackConfig` from the plugin and use that in your `vue.config.js`. Then you don't have to rewrite the code.

**Comment by nklayman** [comment]
This is such an edge case scenario that I don't think it's necessary to add to the plugin. If you can't get it to work by the method above, I'll consider adding it.

**Comment by alectrocute** [comment]
I ran into this today. :(

May be worth adding a flag.
