### ISSUE TITLE
Webstorm run/debug configuration

### ISSUE THREAD

**Issue by RacerDelux** [nklayman/vue-cli-plugin-electron-builder#214]
I have been looking into setting up a run and debug command for webstorm. I have been having trouble figuring out how to get to yarn electron:serve.

Could a build config be included in the repo/does anybody have a build config that works?

Being able to attach a debugger would be a great bonus.

Seems to me a good way to go about this is to ask if you want webstorm or vscode run configs setup when you add the package.

**Comment by skn3** [comment]
yes please, really struggling to find a solution for this!

**Comment by nklayman** [comment]
See the [new vscode debugging recipe](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#debugging-with-vscode). I have never used webstorm, so I'm not sure what the config for that would look like. Maybe you could convert the vscode config to webstorm?

**Comment by RacerDelux** [comment]
So I went to test this on vscode first to see it working, and ran into this error:
![image](https://user-images.githubusercontent.com/2667344/54560634-c58d4980-4990-11e9-8909-4021c797382e.png)

**Comment by nklayman** [comment]
I just pushed a fix that fixes the config for windows (thanks to @kpez) for providing the fix. Check the updated docs and copy in the new tasks.json.

**Comment by RacerDelux** [comment]
A little bumpy, but once the electron debug was fully started it worked fine. (I had to make sure the app was built and running before I started debugging).

One thing I noticed that the hot reload was not on - is this not possible in development?

**Comment by nklayman** [comment]
The `Electron: Main` debug configuration should launch Electron for you. Hot reload works fine for me (I'm on Ubuntu Linux). Try using the `Electron: All` debug configuration.

**Comment by RacerDelux** [comment]
This is what I get when I do Electron:All
![image](https://user-images.githubusercontent.com/2667344/54695424-ede38800-4af7-11e9-805a-adb36c6da0ed.png)

**Comment by nklayman** [comment]
@RacerDelux Did you update to the latest [tasks.json](https://github.com/nklayman/electron-vscode-debug-example/blob/master/.vscode/tasks.json)? If so, can you send me the logs? Your electron app should be started by the `Electron: Main` debug config.

**Comment by RacerDelux** [comment]
@nklayman I did. Where are those logs found, or are you referring to the output from the console?

**Comment by nklayman** [comment]
By logs I mean the task output from where `electron:serve` is run.

**Comment by Neko911** [comment]
+1
Same problem with WebStorm debugger;
```
/home/vlad/projects/playground/node_modules/electron/dist/electron --type=renderer --field-trial-handle=696921918122827264,2031100527710197737,131072 --disable-features=SpareRendererForSitePerProcess --lang=en-US --standard-schemes=app --secure-schemes=app --bypasscsp-schemes --cors-schemes --fetch-schemes --service-worker-schemes --app-path=/home/vlad/projects/playground/dist_electron --node-integration --no-sandbox --no-zygote --background-color=#fff --num-raster-threads=2 --enable-main-frame-before-activation --service-request-channel-token=6451743705860089792 --renderer-client-id=6 --no-v8-untrusted-code-mitigations --shared-fil[25385]: ../../third_party/electron_node/src/inspector_agent.cc:793:bool node::inspector::Agent::StartIoThread(): Assertion `(client_) != nullptr' failed.

```
