### ISSUE TITLE
Strict Mode Error for Production Build

### ISSUE THREAD

**Issue by Latentimagedesign** [nklayman/vue-cli-plugin-electron-builder#215]
Hi -

npm run electron:serve is working great - no issues! Even my production (npm run electron:build) completes without any console errors. 

But once I finish installing the application and running it - it throws a console error:
Uncaught SyntaxError: Strict mode code may not include a with statement

This error is being thrown by my chunk-vendors.js files.

Is there a workaround for this issue? I can obviously go through and remove the "Use Strict" option from my chunk_vendors.js file but it gets replaced once I do a new build.

Is there special configuration I can add to skip the "Use Strict" mode?

**Comment by nklayman** [comment]
Does this error occur on a regular build (`npm run build`)? The build process is handled by vue-cli, this plugin just changes it a little to support electron. Chances are, your issue is with vue cli, not the plugin. If it does fail with a regular build, open an issue on [vue cli's repo](https://github.com/vuejs/vue-cli) instead.

**Comment by Latentimagedesign** [comment]
This error does not occur when using npm run build.  Only when doing npm run electron:build. I'm not really sure where the best place to troubleshoot is. Is it possible to remove the strict mode option that gets added during build?

**Comment by nklayman** [comment]
Do you know which module is causing the error? I need some way to reproduce the issue so I can fix it. If your repo is open source, send me a link and I will look into it.

**Comment by Latentimagedesign** [comment]
I think this ticket can probably be closed down. It looks like its a module issue - i'm trying to figure out which one. I searched my modules folder for "with(obj" but it didn't show up anywhere so i'm not sure how it makes it into chunk-vendors.js :(

**Comment by Latentimagedesign** [comment]
one of culprits is html-docx-js in case someone else finds this thread useful
