### ISSUE TITLE
Open a second window on start with hash route

### ISSUE THREAD

**Issue by zendiik** [nklayman/vue-cli-plugin-electron-builder#216]
Hello,

when I tried to open second window on electron start with hash route (history mode is disabled), window loads home route, but when I try to load Google or some other public url, it loads normally.

Do you know what is wrong?

Thank you

**Comment by nklayman** [comment]
What is the issue exactly? You say it loads normally, what were you expecting?

**Comment by zendiik** [comment]
It doesn't work loading route eg. http://localhost:8080/#/second_route in the second window. It loads http://localhost:8080/ everytime, but when I set https://www.google.com to load in second window, it loads correctly.

**Comment by nklayman** [comment]
Load the `index.html` normally, then run this:
```js
win.webContents.executeJavaScript('window.location.hash = "/about"')
```
Where `about` is the route you want to go to.
