### ISSUE TITLE
Error running electron:build script from package.json

### ISSUE THREAD

**Issue by omritelem** [nklayman/vue-cli-plugin-electron-builder#219]
Im trying to run "electron:build" command, but it gives an error:
"UnhandledPromiseRejectionWarning: TypeError: yargs.parserConfiguration is not a function"
in the builder.js of electron builder node module.

**To Reproduce**
Run electron:build script from package.json

**Expected behavior**
Building script end up with success and a new dist file.

**Environments:**
 - OS and version: Mac - version: 10.14 
 - node version: V11.3.0
 - npm version:V6.4.1
 - yarn version: V1.2.1
 - vue-cli-plugin-electron-builder version : ^1.1.2
 - electron version: ^4.0.0

**Comment by rickbsgu** [comment]
Seeing the same thing on Windows and Ubuntu.

**Comment by ej-santoemma** [comment]
I've some suspect on electron-builder version > 20.38.5

To fix it, waiting for further analysis, I used a yarn.lock from a similar project created a couple weeks ago.
This yarn.lock has electron-builder version 20.38.5, but of course it has different version of other packages too.

**Comment by zyuhel** [comment]
Same issue. 20.39.0 electron-builder fails, 20.38.5 old yargs log works fine. But old yarn.lock has version of vue-cli-plugin-electron-builder version 1.0.4
Fails on all OSes, Ubuntu, Windows, OSX

**Comment by zyuhel** [comment]
#218 says that electron version should be pinned down :)

**Comment by nklayman** [comment]
fixed in `v1.1.3`, thanks for the report and investigation!

**Comment by crossle** [comment]
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.

**Comment by nklayman** [comment]
That is electron-builder's issue, not mine. They use the JS api as well, but keep the `package.json` config for some reason. If there isn't an issue open on their repository already, I'd suggest opening one.

**Comment by omritelem** [comment]
Upgrade vue-cli-plugin-electron-builder vesrion to v1.1.3 fixed the problem, thanks!
