### ISSUE TITLE
Electron 4.0.8 build error - win + linux

### ISSUE THREAD

**Issue by rickbsgu** [nklayman/vue-cli-plugin-electron-builder#221]
**Describe the bug**
get a build error when trying to build on windows or linux:

"Error: ENAMETOOLONG: name too long, copyfile '/home/dev/rccs/mkxlsx/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/win-unpacked/dist_electron/win-unpacked/node_modules/exceljs/dist/es5/config/set-value.js' -> '/home/dev/rccs/mkxlsx/dist_electron/win-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/linux-unpacked/dist_electron/win-unpacked/dist_electron/win-unpacked/node_modules/exceljs/dist/es5/config/set-value.js'"

**To Reproduce**
build w/ electron 4.0.8

**Expected behavior**
successful build

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: Ubuntu 18.10
 - node version: 10.15.3
 - npm version: 6.4.1
 - yarn version (if used): 1.13.0
 - vue-cli-plugin-electron-builder version : 1.1.3
 - electron version: 4.0.8

**Additional context**
Works fine if I revert to 4.0.7

**Comment by nklayman** [comment]
Does this fail on a clean project as well? I cannot reproduce the error, I am on Ubuntu 18.10. Also try upgrading to a more recent electron version.

**Comment by rickbsgu** [comment]
Ooo.  I didn't realize they had bumped to 4.1.0.  I'll try with that.

**Comment by nklayman** [comment]
Did 4.1.0 work?

**Comment by rickbsgu** [comment]
Sorry for the delay - just got it and built it.  Looks good.

thx
