### ISSUE TITLE
Can't get debugger to work in vscode - Linux or Win

### ISSUE THREAD

**Issue by rickbsgu** [nklayman/vue-cli-plugin-electron-builder#222]
**Describe the bug**
Can't debug main process.

Bringing up debugger doesn't stop on breakpoints.  Breakpoints red before invocation, greyed out on execution and application doesn't stop.

**To Reproduce**

Per instructions, launch yarn dev in a separate shell before invoking the debugger.  Invoke the debugger with the following launch config:

```
    {
      "type": "node",
      "request": "launch",
      "name": "electron",
      "cwd": "${workspaceRoot}",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
      "windows": {
        "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
      },
      "args" : ["./dist_electron/bundled/background.js"],
      "outputCapture": "std"
    }
```

the app runs without breaking

If I change the args to point to the src/background.js, then I get this error:
```
  import { app, protocol, BrowserWindow } from 'electron'
             ^

  SyntaxError: unexpected token {
  ...
```

which looks like a babel or source map issue.  AFAIK, source mapping is enabled by default with vue-cli3 - I found an earlier issue that recommended adding a source map directive in the vue.config.js file: 

```
  configureWebpack: {
    devtool: 'source-map'
  }
```

which I tried, but no change.

**Expected behavior**
Stop at a breakpoint

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: Ubuntu 8.10 / Windows 10
 - node version: 10.15.3
 - npm version: 6.4.1
 - yarn version (if used): 1.13.0
 - vue-cli-plugin-electron-builder version : 1.1.3
 - electron version: 4.0.7

**Additional context**
My guess is it's a source mapping issue -- the background.js file in the distribution is minified, so you can't really put a breakpoint on it.

**Comment by proepkes** [comment]
try this:
"args" : ["./dist_electron/index.js"],

**Comment by nklayman** [comment]
Use args: ./dist_electron. It will detect the index automatically, and electron has some crazy wierd issues when you point it directly to a file.

**Comment by rickbsgu** [comment]
Bueno.  Thx.  Might want to update the docs.

**Comment by nklayman** [comment]
See the [new vscode debugging recipe](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#debugging-with-vscode).

**Comment by caixiaosong** [comment]
Thanks for the contribution
