### ISSUE TITLE
Cannot change main entry file path

### ISSUE THREAD

**Issue by julesGoullee** [nklayman/vue-cli-plugin-electron-builder#225]
I follow the doc and I change the value of main file in package.json, when  I run electron:serve it's work but not for electron:build failed with:

` Application entry file "myPath/background.js" in the "myPath/MyApp.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.`

**Comment by nklayman** [comment]
Use the `mainProcessFile` option in the plugin's options. See [this example](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#webpack-configuration) for more information. Don't change the `main` field of your `package.json`. The outputted file will have the same name, regardless of the input.
