### ISSUE TITLE
Error Attempting Basic OOB Build

### ISSUE THREAD

**Issue by mfreeman-xtivia** [nklayman/vue-cli-plugin-electron-builder#228]
Receive the following error when attempting to run 'yarn electron:serve':

```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/mfreeman/temp/fark/fuzz/src/main.js: Cannot find module '@babel/preset-env/data/built-ins.json' (While processing: "/Users/mfreeman/temp/fark/fuzz/node_modules/@vue/babel-preset-app/index.js")
```

Did the most basic sample build by doing 'vue add electron-builder' and then attempting to execute the project. FWIW 'yarn electron:build' works fine.

Node: 8.15 on Mac OSX Mojave

**Comment by nklayman** [comment]
Try deleting your `node_modules` folder and re-installing deps.
