### ISSUE TITLE
CLI Error on publishing

### ISSUE THREAD

**Issue by pvankralingen** [nklayman/vue-cli-plugin-electron-builder#229]
**Describe the bug**
When running `vue-cli-service serve` and `vue-cli-service build` everything works. However, when trying to run `electron-builder -p always`  it errors out. this is a "clean" repo with little changes.

**Error** 
`Error: Application entry file "background.js" in the "C:[location]\dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.`

Note: In `package.json` the following is noted: `"main": "background.js"`.

**To Reproduce**
- Clone repo
- Create vue project with **all options** checked except PWA. 
- Add electron builder
- Make sure all deps are of latest version.
- setup `electron-builder.json` file (for AWS, even though we havent got here yet) and `package.json`
- run `electron-builder -p always` 

**Expected behavior**
Either publish the artifact to Amazon S3, or return an error regarding permissions, bucket policies etc.

**Environment:**
 - OS : Win 10 pro
 - node version: 10.14.1
 - npm version: 6.9.0
 - vue-cli-plugin-electron-builder version : 1.1.3 
 - electron version: 4.1.1

**Additional context**
I havent changed much to the original repo. Another project ( without some of the vue options like testing + typescript ) does work. Many of the packages have the exact same version. 

**Package.json**
```
{
  "name": "name",
  "version": "0.1.0",
  "description": "desc",
  "author": "auth",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "compile": "electron-webpack",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps",
    "publish": "electron-builder -p always",
    "test:e2e": "vue-cli-service test:e2e",
    "test:unit": "vue-cli-service test:unit"
  },
  "main": "background.js",
  "dependencies": {
    "vue": "^2.6.10",
    "vue-class-component": "^7.0.1",
    "vue-property-decorator": "^8.1.0",
    "vue-router": "^3.0.2",
    "vuex": "^3.1.0"
  },
  "devDependencies": {
    "@types/jest": "^24.0.11",
    "@vue/cli-plugin-babel": "^3.5.1",
    "@vue/cli-plugin-e2e-cypress": "^3.5.1",
    "@vue/cli-plugin-typescript": "^3.5.1",
    "@vue/cli-plugin-unit-jest": "^3.5.1",
    "@vue/cli-service": "^3.5.1",
    "@vue/test-utils": "1.0.0-beta.29",
    "babel-core": "7.0.0-bridge.0",
    "dotenv": "^7.0.0",
    "electron": "^4.1.1",
    "fibers": "^3.1.1",
    "lint-staged": "^8.1.5",
    "sass": "^1.17.3",
    "sass-loader": "^7.1.0",
    "ts-jest": "^24.0.0",
    "typescript": "^3.3.4000",
    "vue-cli-plugin-electron-builder": "^1.1.3",
    "vue-template-compiler": "^2.6.10"
  },
  "gitHooks": {
    "pre-commit": "lint-staged"
  },
  "lint-staged": {
    "*.ts": [
      "vue-cli-service lint",
      "git add"
    ],
    "*.vue": [
      "vue-cli-service lint",
      "git add"
    ]
  },
  "publish": {
    "provider": "s3",
    "bucket": "bucket"
  },
  "files": [
    "**/*",
    "!tests${/*}"
  ]
}
```

**electron-builder.json**
```
{
    "appId": "Desktop",
    "productName": "prodname",
    "copyright": "...",
    "win": {
      "target": "nsis",
      "icon": "build/icon.ico",
      "publisherName": "name"
    },
    "nsis": {
      "installerIcon": "build/icon.ico",
      "uninstallerIcon": "build/icon.ico"
    },
    "publish": {
      "provider": "s3",
      "bucket": "bucko",
      "path": "/releases"
    }
  }
  ```

**Comment by nklayman** [comment]
This is because you are not bundling your app with webpack before running electron builder. Use the `electron:build` script in your `package.json` instead of calling electron-builder directly. It will bundle the main and renderer processes with webpack, and then run electron-builder for you. You can pass the `-p always` argument to the `electron:build` command, and it will be forwarded to electron-builder.
