### ISSUE TITLE
Error: connect ETIMEDOUT 52.216.110.203:443

### ISSUE THREAD

**Issue by bibichuan** [nklayman/vue-cli-plugin-electron-builder#233]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: Win10 1809
 - node version: 10.15.3
 - npm version:6.4.1
 - yarn version (if used): 1.15.2
 - vue-cli-plugin-electron-builder version : 1.2.0
 - electron version: 4.0.0
 - other vue plugins used: no
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**
 “ERROR  command failed: yarn add -D --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist vue-cli-plugin-electron-builder”，“Error: connect ETIMEDOUT 52.216.110.203:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
 ERROR  command failed: yarn --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist“,this is the error message。
I used it ” yarn add -D --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist vue-cli-plugin-electron-builder“，but it can't be installed all the time.

**Comment by bibichuan** [comment]
![TIM截图20190402165810](https://user-images.githubusercontent.com/14054904/55389847-9964f180-5568-11e9-9ac2-7ba3d8c16c8a.png)

**Comment by nklayman** [comment]
Add `https://` before the urls.

**Comment by bibichuan** [comment]
vue add electron-builder执行后错误
![error](https://user-images.githubusercontent.com/14054904/55528572-e9aa9380-56cf-11e9-9ac6-7f61a2b32193.png)

**Comment by nklayman** [comment]
Electron is failing to download from the default mirror. Use the Chinese mirror by prepending the install command with `ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/"` (sets the env var). See the [Electron Install Docs](https://electronjs.org/docs/tutorial/installation#custom-mirrors-and-caches) for more info.

**Comment by bibichuan** [comment]
npm config set registry https://registry.npm.taobao.org/
npm config set ELECTRON_MIRROR http://npm.taobao.org/mirrors/electron/

**Comment by Ken-twenty** [comment]
> npm config set registry https://registry.npm.taobao.org/
> npm config set ELECTRON_MIRROR http://npm.taobao.org/mirrors/electron/

just in case somebody get stuck, it is [https://npm.taobao.org/mirrors/electron/](ELECTRON_MIRROR), **HTTPS**. Good luck.
