### ISSUE TITLE
package existing Nuxt app and run as a desktop app using this electron-builder plugin

### ISSUE THREAD

**Issue by ChunAllen** [nklayman/vue-cli-plugin-electron-builder#234]
I would like to use this package on my existing Nuxt App. I'm currently using nuxt 2.5.1 and I would like to run my application as a desktop application. The current application runs in `spa` mode

**Comment by nklayman** [comment]
This plugin only works with an app created with vue-cli 3. IF you use the Nuxt starter template, you will have to set up electron on your own. Nuxt is pretty popular, some google searching might find an article or tool to help you.
