### ISSUE TITLE
Native modules do not load on windows (using typescript)

### ISSUE THREAD

**Issue by jrd-rocks** [nklayman/vue-cli-plugin-electron-builder#235]
**Describe the bug**
Loading nodejs modules that are native like sqlite3 and better-sqlite3 does not work

**To Reproduce**
```
//main.ts
....
const db = require('better-sqlite3'); 
....
```
```
//vue.condfig.js
module.exports = {
    pluginOptions: {
        electronBuilder: {
          // List native deps here if they don't work
          externals: {"better-sqlite3": "better-sqlite3"},
          // If you are using Yarn Workspaces, you may have multiple node_modules folders
          // List them all here so that VCP Electron Builder can find them
          nodeModulesPath: ['../../node_modules', './node_modules']
        }
      }  
}
```

```
Then `npm run electron:serve` throws an error:

 error  in ./node_modules/integer/build/integer.node

Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)

 @ ./node_modules/integer/lib/index.js 2:33-65
 @ ./node_modules/better-sqlite3/lib/index.js
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.1.10:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

 error  in ./node_modules/better-sqlite3/build/better_sqlite3.node
```

Other scenario with `externals: ["better-sqlite3"],` in vue.config.js, now electron launches, but there is an error in the developer console

```
ELECTRON_ASAR.js:160 Uncaught Error: The specified module could not be found.
\\?\Z:\projects\...\client\node_modules\better-sqlite3\build\better_sqlite3.node
    at process.module.(:8080/anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722)
    at Object.module.(:8080/anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602)
    at tryModuleLoad (internal/modules/cjs/loader.js:541)
    at Function.Module._load (internal/modules/cjs/loader.js:533)
    at Module.require (internal/modules/cjs/loader.js:640)
    at require (internal/modules/cjs/helpers.js:20)
    at Object.<anonymous> (Z:\projects\...\client\node_modules\better-sqlite3\lib\database.js:5)
    at Object.<anonymous> (Z:\projects\...\client\node_modules\better-sqlite3\lib\database.js:57)
```
Not sure it's related, but it says it cannot find `\\?\Z:\projects\...\client\node_modules\better-sqlite3\build\better_sqlite3.node` i would expect `Z:\projects\...\client\node_modules\better-sqlite3\build\better_sqlite3.node` without the `\\?\` prefix (which exists and is compiled for electron with electron-rebuild).

**Expected behavior**
No errors

**Environment (please complete the following information):**
 - OS and version: Windows 10
 - node version: 10.5.0
 - npm version: 6.9.0
 - vue-cli-plugin-electron-builder version : ^1.2.0,
 - electron version:  4.0.0
 - other vue plugins used: none
 - custom config for vcp-electron-builder:  none
 - (if possible) link to your repo: none

UPDATE

I got https://www.npmjs.com/package/sqlite working by adding an extra loader: https://github.com/evonox/electron-native-plugin i don't understand how or why this extra loader makes things work (the js build/webpack ecosystem is new and way too complicated for me at the moment), but it does. ***update** it seem the electron-native-plugin only works sometimes for sqlite and never for better-sqlite3.

I've create an empty default project that has this problem: https://github.com/jrd-rocks/vcpeb-example-problem. The only files i canged are https://github.com/jrd-rocks/vcpeb-example-problem/blob/master/vue.config.js to add the externals , https://github.com/jrd-rocks/vcpeb-example-problem/blob/master/src/main.ts to add the db modules, https://github.com/jrd-rocks/vcpeb-example-problem/blob/master/src/native/db.ts the db modules that uses better-sqlite3

**Comment by jrd-rocks** [comment]
Oops, this was fully my mistake. I got better-sqlite3 to work, i think sqlite3 as well, but that library seems to create a race condition and never returns.

The problem: i had electron 1.4 installed globally. webpack-rebuild rebuild against the global version, once i noticed i had two node_sqlite3.node artifacts, both 1.4 and 4.1, i realized something was wrong. after manually deleting (npm update or install for some reason never worked) the old electron things work.

**Comment by nklayman** [comment]
Yeah, make sure that the `postinstall` script gets ran, it will rebuild all your native modules for you.
