### ISSUE TITLE
Cannot change package name

### ISSUE THREAD

**Issue by Kylart** [nklayman/vue-cli-plugin-electron-builder#236]
**Describe the bug**
If you get the Get Started project and simply change the name property of the `package.json` file, the app won't start anymore

**To Reproduce**
1. Get a starter app
2. Change package.json's name property
3. run `npm run electron:serve` or `yarn electron:serve`

**Expected behavior**
The app behavior should be independent from the package name

**Environment (please complete the following information):**
 - OS and version: Mac OS Mohjave
 - node version: 11.8.0
 - npm version: 6.9.0
 - yarn version (if used): 1.15.1
 - vue-cli-plugin-electron-builder version : latest
 - electron version: ^4
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo:

**Comment by nklayman** [comment]
When you change the name of your app, it changes the cache dir. This means that Vue devtools have to be redownload. Try commenting out the Vue devtools installation in your background.js and it should work fine.

**Comment by Kylart** [comment]
Alright so I had the case where it just stopped working without even changing the name.

I tried commenting our the `installVueDevtools` but I had no success.

However, I can describe the problem a little more. I know for a fact that my `background.js` file is executed as I have logs proving it. I am going to investigate a little bit more as to where does the process exits. 

I'd love some more ideas tho.

**Comment by Kylart** [comment]
Alright, so I figured it out, it is really funny that this never happened before.

I do have on my computer my app turning in production mode because I use it quite often. I also have a security to ensure my app doesn't open twice. So I ask for a [single instance lock](https://electronjs.org/docs/api/app#apprequestsingleinstancelock) in the `background` file. This was forcing the app to quit in dev mode when the production app was running.

Now, I am migrating my app to `vue-cli-electron-builder` and this is the first time I've seen such behavior. I have no idea why it doesn't know that the dev version and the production version are not the same app.
