### ISSUE TITLE
External browser window renderer does not find its packages any more

### ISSUE THREAD

**Issue by iklemm** [nklayman/vue-cli-plugin-electron-builder#237]
**Describe the bug**
I am not sure if this is a bug or a misconfiguration on my side.

So this is more a request for help then a bug report.

I have a vue-electron app that i used to built with  "vue-cli-plugin-electron-builder": "^1.0.0-rc.9".
This vue app opens some external BrowserWindows which do not depend on vue and have its own simple renderer written in TS. TS is compiled here independently with its own tsconfig file with the ide-compiler.  options are: "target": "es2015",   "module": "commonjs", ...
Theses external Windows (html and renderer-js) live standalone in the public folder of the project.

This worked fine until i updated to v1.2.0.

After the update external packages like "fs-extra"  that are required by "const fs = require('fs-extra');" can't be resolved by the module loader any more. Nevertheless, native node packages like "path" are found.

Any hint how to solve this would be great. Thank You.

**Comment by nklayman** [comment]
List `fs-extra` as an external dep in your `vue.config.js`:
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['fs-extra']
    }
  }
}
```

v1.2.0 only includes deps in your packaged app if they are externals. Non-external deps are bundled into your app via webpack, so they don't need to be included and take up extra space in your app. This is a weird scenario as `fs-extra` isn't being detected as an external dep yet is not getting bundled into your app via webpack.

**Comment by iklemm** [comment]
Great, thank you very much!
