### ISSUE TITLE
Running express inside electron app

### ISSUE THREAD

**Issue by Obippin** [nklayman/vue-cli-plugin-electron-builder#238]
How do I bundle express server and Vue-Electron app?

I have used express server for fetching and storing data.
User login credentials are stored in mysql database, login form calls the express server.
User can register with new credentials which again calls the local express server and stores in local mysql database.
It would be perfect if I could package everything inside one app and still be able to access express server.

Running electron app and the separate express server works but I want to package both electron and express so that I can perform actions only with electron app.

**Comment by nklayman** [comment]
Express should function as normal. The only issue would come from mysql. See https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/76#issuecomment-420060179 for instructions on using mysql.
