### ISSUE TITLE
1.2.0 release package run error

### ISSUE THREAD

**Issue by crossle** [nklayman/vue-cli-plugin-electron-builder#240]
**Describe the bug**
Release package error

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: MacOS latest
 - node version:  latest
 - npm version:
 - yarn version (if used): 1.5.2 
 - vue-cli-plugin-electron-builder version : 1.2.0
 - electron version: 
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**
1.1.3 work well, upgrade to 1.2.0 release package error

```
Uncaught Error: Cannot find module 'bytebuffer'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584)
    at Function.Module._resolveFilename .app/Contents/Resources/electron.asar/common/reset-search-paths.js:43)
```

**Comment by nklayman** [comment]
Try listing bytebuffer as an external in your `vue.config.js`:

```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['bytebuffer']
    }
  }
}
```

**Comment by crossle** [comment]
Thanks
