### ISSUE TITLE
Run E2E tests with Cypress

### ISSUE THREAD

**Issue by FPierre** [nklayman/vue-cli-plugin-electron-builder#241]
**Describe the bug**

When I run `yarn run test:e2e`, Cypress run it's own UI, but fails with **Can't start server** issue.

I'm a little lost to fix this bug :)

**Screenshots**

![cypress-error](https://user-images.githubusercontent.com/3307327/55938733-4bbd4880-5c3c-11e9-9c35-e1407be1a18c.png)

**Environment (please complete the following information):**

 - OS and version: Linux Ubuntu 18.10
 - node version: v11.5.0
 - yarn version: v1.15.2
 - vue-cli-plugin-electron-builder version : v1.2.0
 - electron version: v4.1.4
 - other vue plugins used: 

`package.json`:

```json
"scripts": {
  "test:e2e": "vue-cli-service test:e2e",
  "electron:build": "vue-cli-service electron:build",
  "electron:serve": "vue-cli-service electron:serve"
},
  "dependencies": {
    "electron": "^4.1.3",
    "vue": "^2.5.17",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1",
    "vuex-router-sync": "^5.0.0"
},
"devDependencies": {
  "@cypress/webpack-preprocessor": "^4.0.3",
  "@vue/cli-plugin-babel": "^3.1.0",
  "@vue/cli-plugin-e2e-cypress": "^3.1.0",
  "@vue/cli-plugin-eslint": "^3.1.0",
  "@vue/cli-plugin-unit-jest": "^3.1.0",
  "@vue/cli-service": "^3.1.0",
  "@vue/eslint-config-airbnb": "^4.0.0",
  "@vue/test-utils": "^1.0.0-beta.20",
  "vue-cli-plugin-electron-builder": "^1.2.0",
  "vue-template-compiler": "^2.5.17"
}
```

**Additional context**

Cypress and E2E tests files are untouched

`cypress.json`:

```json
{
  "pluginsFile": "tests/e2e/plugins/index.js"
}
```

`tests/e2e/plugins/index.js`:

```js
// https://docs.cypress.io/guides/guides/plugins-guide.html
/* eslint-disable import/no-extraneous-dependencies, global-require */
const webpack = require('@cypress/webpack-preprocessor');

module.exports = (on, config) => {
  on('file:preprocessor', webpack({
    webpackOptions: require('@vue/cli-service/webpack.config'),
    watchOptions: {},
  }));

  return Object.assign({}, config, {
    fixturesFolder: 'tests/e2e/fixtures',
    integrationFolder: 'tests/e2e/specs',
    screenshotsFolder: 'tests/e2e/screenshots',
    videosFolder: 'tests/e2e/videos',
    supportFile: 'tests/e2e/support/index.js',
  });
};
```

`tests/e2e/specs/test.js`:

```js
// https://docs.cypress.io/api/introduction/api.html

describe('My First Test', () => {
  it('Visits the app root url', () => {
    cy.visit('/');
    cy.contains('h1', 'Welcome to Your Vue.js App');
  });
});
```

**Comment by nklayman** [comment]
It works fine for me, can you try with an empty project? If that fails, upload it to github and send me the link. Thanks!

**Comment by FPierre** [comment]
Actually a good way to test :+1: 

It's works with an empty project. My guess is I've change some files that I shouldn't have changed.
I will reset my files from a fresh installation

**Comment by FPierre** [comment]
OK, back to this issue. there's probably something I misunderstood on e2e testing: when `yarn run test:e2e` is runned, it's only run Vue.js project without Electron, right?

So how can I test something like that:

`src/components/HelloWorld.vue`:

```js
<script>
import { app, remote } from 'electron';

const electronApp = remote ? remote.app : app;
console.log(electronApp);

export default {
  // ...
}
</script>
```

It produces the following:

![Screenshot from 2019-04-17 18-35-46](https://user-images.githubusercontent.com/3307327/56305010-a32d4e00-613f-11e9-97b5-65d45b67fe76.png)

with `tests/e2e/specs/test.js`:

```js
describe('My First Test', () => {
  it('Visits the app root url', () => {
    cy.visit('/');
    cy.contains('h1', 'Welcome to Your Vue.js App');
  });
});
```

(on a fresh new project)

**Comment by nklayman** [comment]
Cypress does not support testing electron apps. See https://github.com/cypress-io/cypress/issues/2072 for more details. To test an electron app, use spectron. See [the docs on testing and debugging](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/testingAndDebugging.html#testing).
