### ISSUE TITLE
Cross compilation of binaries

### ISSUE THREAD

**Issue by PaulBernier** [nklayman/vue-cli-plugin-electron-builder#242]
Hello,

Is it possible to cross compile the application binary? As of now if I want to build the app for Windows I need to pull the project on a Windows machine and built it there. Same for macOS. Ideally I could built all platforms from my linux for instance, that would make the release process infinitely faster and easier.

**Comment by nklayman** [comment]
See the [Electron Builder CLI docs](https://www.electron.build/cli). All arguments passed to the `electron:build` command will be forwarded to Electron Builder. Use `--win`, `--linux`, and `--mac` to specify target platforms. You can list installers to create after each platform arg as well. Windows and Linux can build for each other, but the only way to build for a Mac is to use a Mac (Macs can also build for win/linux).

**Comment by Lindenk** [comment]
Neither setting the command `electron:build` to `vue-cli-service electron:build --win` nor passing `--win` in `npm run electron:build --win` seem to work for a default skeleton project created with `vue-cli` and using this plugin with `vue add electron-builder`
