### ISSUE TITLE
Use the shortcut key to refresh the page after the page blank

### ISSUE THREAD

**Issue by HeiShanLaoYao889** [nklayman/vue-cli-plugin-electron-builder#243]
When I finished packaging my project, I refreshed the page with the menu role= 'reload' shortcut provided by the electron official, the page was blank.While In development mode, it is normal to use the shortcut key to reload the page.
`{
                label:'刷新',
                role:'reload'
            },`
When I debug my packaged project, after refreshing the page, the debug found.
The refresh before:
![image](https://user-images.githubusercontent.com/24189898/56114568-d0d59400-5f93-11e9-9644-b2ffeb2bf5b6.png)
After the refresh:
![image](https://user-images.githubusercontent.com/24189898/56114836-9c160c80-5f94-11e9-9ec1-cabd40961fa2.png)

**Comment by listc** [comment]
router用history模式的情况下会出现这种情况。
测试了几个版本都有这个问题，具体原因不清楚，但桌面软件一般都是禁止用户手动刷新的吧
如果确实有这个需求，将vue-router改为hash模式

**Comment by ioslide** [comment]
So do I

**Comment by NateScarlet** [comment]
Seems vue-router can not parse `app:` protocol url correctly.
My workaround:

```typescript
  router.afterEach(
    (to): void => {
      sessionStorage.setItem('router-location', to.fullPath);
    }
  );
  const l = sessionStorage.getItem('router-location');
  if (l) {
    router.push(l || '/');
  }
```

**Comment by NateScarlet** [comment]
Maybe there should be a `fallback` option for `createProtocol` function

**Comment by nklayman** [comment]
Electron has `ctrl-r` to reload enabled by default and it works fine.
