### ISSUE TITLE
How to use child_process?

### ISSUE THREAD

**Issue by Corben78** [nklayman/vue-cli-plugin-electron-builder#244]
After creating a simple vue.js electron app with this plugin, I'm struggling with using e.g. exec from child_process.

In the HelloWorld.vue file, I try:
```javascript
<script>
import { exec } from 'child_process'

export default {
  created() {
    exec('ls -lah /tmp', function(error, stdout, stderr) {
      console.log(stdout);
    });
  }
}
</script>
```
This results in
```
[Vue warn]: Error in created hook: "TypeError: Object(...) is not a function"
```

I've seen this https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/121#issuecomment-433199340, but adding this to `vue.config.js`
```javascript
module.exports = {
  configureWebpack: (config) => {
    config.externals = { 'child_process': 'require("electron").remote.require("child_process")' };
  },
};
```
causes this error:
```
ReferenceError: require is not defined
```
Further researches on this lead me to [How to include Node modules with Webpack](http://www.matthiassommer.it/software-architecture/webpack-node-modules/), but adding `target:'electron-renderer'` or `target: 'node-webkit'` as suggested [here](https://stackoverflow.com/questions/50200158/nw-js-child-process-not-working-with-vue-js-app) leads again to the `require is not defined` error.
I also tried to prepend the previous externals with `...config.externals` as I've found [here](https://forum.vuejs.org/t/vue-cli-adding-external-js-and-css-libraries/38946/10), also with no luck.

When I import exec like this (removing all previous stuff again I changed, like the webpack settings):
```javascript
const exec = require('electron').remote.require('child_process').exec;
```
And then call exec like above, I get a different error:
```
TypeError: fs.existsSync is not a function
```

Any idea how to properly import functions from `child_process` and call them from a Vue component with vue-cli-plugin-electron-builder?

**Comment by Corben78** [comment]
Oh dear... stupid me.
I was testing in the browser with `npm run serve` which of course doesn't work, as the browser doesn't it.
Running via `npm run electron:serve` works. Without any changes to the webpack config. Just importing via `import { execFile } from 'child_process';` is enough.

**Comment by Hariprabu94** [comment]
electron-vue childprocess not working for me. console log is   **this.$exec is not function**

kindly assist

**Comment by caballerofelipe** [comment]
> ![Untitled](https://user-images.githubusercontent.com/56619957/90327365-a09b6c80-dfb0-11ea-89b0-4091acc922cf.png)
> am getting above error while electron running
> 
> kindly assist

I'm having the same issue. Maybe it has something to do with the latest release.

**Comment by Hariprabu94** [comment]
> > am getting above error while electron running
> > kindly assist
> 
> I'm having the same issue. Maybe it has something to do with the latest release.

**vue init simulatedgreg/electron-vue my-project** child process was worked well in this method. But once npm packages are updated to latest version, Its listing out my directory in electron not my app. Afterwards  its showing ESLINT error😑

**Comment by caballerofelipe** [comment]
I created a full issue here: #986 .

**Comment by gt2ming** [comment]
I am using `npm run electron:serve` to run the electron, but it still doesn't work.
Just like this,
```
<script>
import exec from 'child_process'

export default {
  name: 'InstanceManage',
  data: () => ({
  }),
  methods: {
    createInstance: function () {
      exec('dir')
    }
  }
}
</script>
```

And i call this method in the Vue template

```
<v-btn class="mx-2" fab dark color="blue" @click="createInstance">
```

![1](https://user-images.githubusercontent.com/26201976/100176484-53159080-2f0b-11eb-9605-22e8b345d6af.png)

Can you have other solutions?

**Comment by str028** [comment]
Same for me
<template>
  <div id="app">
    <div v-for="index in 25" :key="index">
      <button class="rounded m-2" @click="logSample">
        Chrome-{{index}}
      </button>
    </div>
  </div>
</template>

<style>
 @import 'build/styles.css';
</style>

<script>
export default {
  name: "app",
  methods: {
    logSample:function () {
      console.log("Test1");
      console.log("Test2");
    }
  }
}
</script>


![Uploading image.png…]()

**Comment by str028** [comment]
Same for me
<template>
  <div id="app">
    <div v-for="index in 25" :key="index">
      <button class="rounded m-2" @click="logSample">
        Chrome-{{index}}
      </button>
    </div>
  </div>
</template>

<style>
 @import 'build/styles.css';
</style>

<script>
export default {
  name: "app",
  methods: {
    logSample:function () {
      console.log("Test1");
      console.log("Test2");
    }
  }
}
</script>


![image](https://user-images.githubusercontent.com/22391365/100747939-a745d680-341d-11eb-873d-64250a5a969f.png)

**Comment by austenc** [comment]
Also experiencing this issue on `2.0.0-rc.5`

**Comment by austenc** [comment]
For folks coming here from a google search and thinking "but I have this correct in my `vue.config.js` file":

Chances are you have a bug elsewhere which is causing this same `Object(...)` error! That was my problem, the solutions suggested in the docs page work correctly:
https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration
