### ISSUE TITLE
stuck at building fresh packages for hours and fail

### ISSUE THREAD

**Issue by iQuin** [nklayman/vue-cli-plugin-electron-builder#245]
**Describe the bug**
stuck at building fresh packages for hours and fail
Here is my console log:
```
Choose Electron Version ^4.0.0

�  Invoking generator for vue-cli-plugin-electron-builder...
�  Installing additional dependencies...

yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.8: The platform "win32" is incompatible with this module.
info "fsevents@1.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error D:\quinn\tasks\ultimate3x3\node_modules\electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: D:\quinn\tasks\ultimate3x3\node_modules\electron
Output:
Downloading tmp-9000-0-electron-v4.1.4-win32-x64.zip
Error: read ECONNRESET
D:\quinn\tasks\ultimate3x3\node_modules\electron\install.js:49
  throw err
  ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:139:27)
 ERROR  command failed: yarn --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist
```

And my package.json:
```
{
  "scripts": {
    "cache-clean": "rm -rf ~/.electron && rm -rf dist",
    "postinstall": "node install.js",
    "pretest": "npm run cache-clean",
    "test": "standard"
  },
  "bin": {
    "electron": "cli.js"
  },
  "main": "index.js",
  "types": "electron.d.ts",
  "dependencies": {
    "@types/node": "^10.12.18",
    "electron-download": "^4.1.0",
    "extract-zip": "^1.0.3"
  },
  "devDependencies": {
    "home-path": "^0.1.1",
    "path-exists": "^2.0.0",
    "standard": "^5.4.1"
  },
  "directories": {
    "test": "test"
  },
  "engines": {
    "node": ">= 4.0"
  },
  "name": "electron",
  "version": "^4.0.0",
  "repository": "https://github.com/electron/electron",
  "description": "Build cross platform desktop apps with JavaScript, HTML, and CSS",
  "license": "MIT",
  "author": "Electron Community",
  "keywords": [
    "electron"
  ]
}
```

**To Reproduce**
Just 
vue create project
cd project
vue add electron-builder

**Environment (please complete the following information):**
 - OS and version: windows 10
 - node version:  11.14.0
 - yarn version: 1.15.2
 - electron version:  4.1.4

**Comment by iQuin** [comment]
Finally I solved the problem by changing the electron vision in _package.json_ to 4.1.3. But I still haven't figure out what went wrong when I install vision 4.1.4.

**Comment by nklayman** [comment]
Seems like you had a bad connection while trying to download electron. 4.1.3 may have been cached. Try using the latest electron with a good internet connection.

**Comment by nklayman** [comment]
If you are in China, use the Chinese download mirror by prepending the install command with ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/" (sets the env var). See the [Electron Install Docs](https://electronjs.org/docs/tutorial/installation#mirror) for more info.

**Comment by iQuin** [comment]
Problem solved! Thanks a lot. I feel bad that I missed this part of the document earlier. Not figure out what's wrong with Internet connection yet, but now I can use the latest electron by manually download the released zip from mirror and put it into the cache folder. 
Thanks!
