### ISSUE TITLE
Update Electron Version from 3 to 4

### ISSUE THREAD

**Issue by Latentimagedesign** [nklayman/vue-cli-plugin-electron-builder#248]
**Is your feature request related to a problem? Please describe.**
I'm just trying to update the Electron version from 3 to 4. I was not able to find this documented anywhere - so i'm just wondering if it needs to be documented? or simply added as a feature?

**Describe the solution you'd like**
Easy upgrade document to go from version 3 to version 4 of electron

**Describe alternatives you've considered**
I've created a new project from scratch and just copy/pasted my files over. Worked great but took some time.

**Additional context**

**Comment by nklayman** [comment]
In your app's `package.json` under `devDependencies`, change the `electron` version to `^4.0.0`:

```
"devDependencies": {
  ...
 "electron": "^4.0.0",
  ...
}
```

Then, reinstall deps by running `npm install` or `yarn install`.
