### ISSUE TITLE
How to build app for Windows 32bit version?

### ISSUE THREAD

**Issue by wakamin** [nklayman/vue-cli-plugin-electron-builder#251]
I am using Windows 64bit for development, after I execute npm run electron:build, it produce .exe file for 64bit system. How to build for 32bit system?

**Comment by nklayman** [comment]
Add the `--ia32` flag to the build command:
```
(yarn|npm run) electron:build --ia32
```

**Comment by BHDHakim** [comment]
> Add the `--ia32` flag to the build command:
> 
> ```
> npm run electron:build -- --ia32
> ```
> 
> or
> 
> ```
> yarn electron:build --ia32
> ```

@nklayman, It work perfectly, but please how is it possible to add it in vue.config.js

**Comment by nklayman** [comment]
See [the electron-builder docs](https://www.electron.build/cli#targetconfiguration).

**Comment by glaucusec** [comment]
I am so new to this, can anyone please tell me from where should I run these command. I have a old 32 bit windows pc and was trying to figure out a way of doing this.

**Comment by klren0312** [comment]
> I am so new to this, can anyone please tell me from where should I run these command. I have a old 32 bit windows pc and was trying to figure out a way of doing this.

Can set `vue.config.js` like this 
https://github.com/klren0312/electronTemplate/blob/master/vue.config.js#L20

```js
pluginOptions: {
  electronBuilder: {
    builderOptions: {
      win: {
        target: [
          {
            target: 'nsis',
            arch: ['ia32'] // windows 32
          }
        ]
      }
    }
  }
}
```

**Comment by glaucusec** [comment]
Can you please a give me a 32 bit windows exe file?

**Comment by klren0312** [comment]
> Can you please a give me a 32 bit windows exe file?

You can build my project get win32 exe
https://github.com/klren0312/electronTemplate
