### ISSUE TITLE
Failed re-launch by dev server

### ISSUE THREAD

**Issue by kPherox** [nklayman/vue-cli-plugin-electron-builder#252]
**Describe the bug**
`ELIFECYCLE` error throw when saved `background.js`.

**To Reproduce**
1. Run `vue-cli-service electron:serve`.
2. Save `background.js` when finished Launch Electron.

**Expected behavior**
Restarting Electron.app

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: macOS Mojave 10.14.4
 - node version: v10.6.0
 - npm version: 6.9.0
 - yarn version (if used): -
 - vue-cli-plugin-electron-builder version : 1.3.0
 - electron version: 4.1.5
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: https://github.com/cutls/TheDesk/tree/rewrite-vue

**Additional context**
Error log
```
./node_modules/vue-cli-plugin-electron-builder/index.js:462
            if (child.killed) {
                      ^

TypeError: Cannot read property 'killed' of null
    at ChildProcess.child.on (./node_modules/vue-cli-plugin-electron-builder/index.js:462:23)
    at ChildProcess.emit (events.js:187:15)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
```

**Comment by nklayman** [comment]
Try updating to v1.3.1, that should have fixed the issue.

**Comment by kPherox** [comment]
Looks like it works, thx!
