### ISSUE TITLE
Electron 5 Scheme Registration

### ISSUE THREAD

**Issue by jmmk** [nklayman/vue-cli-plugin-electron-builder#253]
**Describe the bug**

The updated generator writes the following:
`protocol.registerSchemesAsPrivileged([{scheme: 'app', secure: true }])`

But it appears the correct way is:
`protocol.registerSchemesAsPrivileged([{scheme: 'app', privileges: {secure: true}}])`

**Comment by nklayman** [comment]
Thanks for the tip! Looks like there was an issue with the electron docs: https://github.com/electron/electron/pull/16601.
