### ISSUE TITLE
Electron 5.0.0 not working

### ISSUE THREAD

**Issue by d0whc3r** [nklayman/vue-cli-plugin-electron-builder#258]
**Describe the bug**
When run electron:serve using electron 5.0.0 nothing happens

**To Reproduce**
Update electron to 5.0.0 and run electron:serve

**Expected behavior**
Main window is open

**Environment (please complete the following information):**
 - OS and version: linux
 - node version: 10
 - npm version: 6.9
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 1.3.1
 - electron version: 5.0.0
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo:

**Comment by nklayman** [comment]
In your `background.js`, replace:
```js
protocol.registerStandardSchemes(['app'], { secure: true })
```
with
```js
protocol.registerSchemesAsPrivileged([{scheme: 'app', privileges: { secure: true } }])
```

**Comment by d0whc3r** [comment]
Yes... I made that change, and I made all changes in https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md but is not working anyway

**Comment by TranceGeniK** [comment]
I'm having the same issue here, but only when navigating via a router-link

```
Failed to register app protocol { [Error: ENOENT: no such file or directory, open '/home/me/dev/electron/vs-tools/dist_electron/linux-unpacked/resources/app/home/me/dev/electron/vs-tools/dist_electron/linux-unpacked/resources/app/']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path:
   '/home/me/dev/electron/vs-tools/dist_electron/linux-unpacked/resources/app/home/me/dev/electron/vs-tools/dist_electron/linux-unpacked/resources/app/' }
```

If @d0whc3r used `this.$router.push('/')` as suggested in the doc, it could show a blank page at startup

**Comment by nklayman** [comment]
@d0whc3r try deleting your node_modules folder and reinstalling all deps.

**Comment by d0whc3r** [comment]
I just created a totally new project using: `vue create` and then add vue-cli-plugin-electron using: `vue add electron-builder` then, when I run `npm run electron:serve` this will be output before program closes without showing any electron window

```
❯ npm run electron:serve

> electron5-vue@0.1.0 electron:serve /disk2/projects/test/electron-vue/electron5-vue
> vue-cli-service electron:serve

 INFO  Starting development server...
 98% after emitting CopyPlugin                                                   

 DONE  Compiled successfully in 2045ms                                                                                                    22:22:12

 
  App running at:
  - Local:   http://localhost:8081/ 
  - Network: http://192.168.1.10:8081/

  Note that the development build is not optimized.
  To create a production build, run yarn build.

⠼  Bundling main process...

 DONE  Compiled successfully in 337ms                                                                                                     22:22:12

  File                      Size                     Gzipped

  dist_electron/index.js    650.41 KiB               148.64 KiB

  Images and other types of assets omitted.

 INFO  Launching Electron...
```

This is the repo: https://github.com/d0whc3r/electron5-vue

@nklayman I'm using linux

**Comment by nklayman** [comment]
The repo works fine for me on Ubuntu 19.04. It seems your electron cache may be corrupted. Clear your electron cache by running `rm -r ~/.cache/electron`.

**Comment by d0whc3r** [comment]
Ok, the only way I can run electron 5 is setting `ELECTRON_DISABLE_SANDBOX=yes` otherwise I can not run electron 5
Many thanks for all the support :smile:

**Comment by martijnmichel** [comment]
@d0whc3r can you maybe tell me how i can set ELECTRON_DISABLE_SANDBOX=yes for electron-builder ? I have this exact same problem and cant figure out how to fix it. :(

**Comment by d0whc3r** [comment]
@martijnmichel using cross-env or dotenv to export `ELECTRON_DISABLE_SANDBOX` environment variable in build system
