### ISSUE TITLE
HMR doesn't work

### ISSUE THREAD

**Issue by algil** [nklayman/vue-cli-plugin-electron-builder#26]
Hi!

HotModuleReplacement doesn't work in version alpha.9. I need to reload window in order to view changes.

Regards!

**Comment by nklayman** [comment]
This is really annoying to fix as it works when I link the package, but not when added remotely. I will still look into this though.

**Comment by u3u** [comment]
I use jsx instead of templates, and I solved this problem by manually configuring `vue-jsx-hot-loader`. However, you need to manually run `yarn serve:electron` every time the main process code is modified.

**Comment by u3u** [comment]
I want to ask extra questions here:

1. Is it possible to output an error message on the terminal when the main process has an error?
2. How to debug the main process?

**Comment by nklayman** [comment]
If there is an error in the main process, it should be logged in the console and the program should exit. If that is somehow missing, please create a separate issue with reproduction steps. The main process does not have hot reload as electron would have to be relaunched every time it changes (let me know if I'm wrong). As for debugging the main process, I'm currently working on an implementation for that and would appreciate a PR 😄 .

**Comment by nklayman** [comment]
What do you think about having `serve:electron` take a `--debug` argument that disables minification of the main process and doesn't launch electron? Then, electron can be launched through a debugger as documented [here](https://electronjs.org/docs/tutorial/debugging-main-process).

**Comment by u3u** [comment]
> @nklayman:
The main process does not have hot reload as electron would have to be relaunched every time it changes (let me know if I'm wrong).

Can you let it restart automatically when the main process changes? 🤔

> @nklayman:
Take a `--debug` argument that disables minification of the main process and doesn't launch electron

I think this is good 😄

**Comment by nklayman** [comment]
I was also thinking that I could export a function used for testing. It starts `serve: electron` and returns a promise that resolves when the server is ready, including info like the server url and other info. This would be helpful for testing with spectron. Do you think this would be useful? I could also configure electron to restart on the main process change.

**Comment by nklayman** [comment]
Beta.4 has been released with [testing and debugging support](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/testingAndDebugging.html#testing-and-debugging). Unfortunately, no HMR or auto restarting electron when main config changes (yet).

**Comment by nklayman** [comment]
@u3u With 1.0.0-beta.6, electron is restarted automatically when the main process changes!

**Comment by u3u** [comment]
@nklayman thank you very much!

**Comment by nklayman** [comment]
HMR works fine on Linux, not sure about Windows (will check soon) or MacOS.

**Comment by xdk78** [comment]
I tested on Windows and works fine.

**Comment by Kaffiend** [comment]
HMR for the renderer process is not working now on windows.  Electron 2^ 
The console logs its running and waiting for an update, the system rebuilds to renderer process just doesnt replace the modules or "reload"

**Comment by nklayman** [comment]
@Kaffiend can you confirm that it doesn't work with a blank project, and that it works with a regular `serve`. It works fine for me on linux with a blank project.
