### ISSUE TITLE
Access to the Indexed Database API is denied in this context

### ISSUE THREAD

**Issue by gg-g** [nklayman/vue-cli-plugin-electron-builder#263]
**Describe the bug**
I made an app using pouchdb as local storage. All is well under electron:serve

After issuing `npm run electron:build`, I was present with a blank screen. The developer tools showed an error stating:

`'Uncaught DOMException: Failed to execute 'open' on 'IDBFactory': access to the Indexed Database API is denied in this context'`

**To Reproduce**
See above

**Expected behavior**
Access to Indexed DB

**Screenshots**
n/a

**Environment (please complete the following information):**
 - OS and version: elementary OS 5.0 (Juno)/Ubuntu 18.04 LTS (bionic)
 - node version: v10.15.3
 - npm version: 6.4.1
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 1.3.1
 - electron version: 5.0.0
 - other vue plugins used: pouchdb@7.0.0
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**
I got around this by changing how the main window loads the entry point in background.js
from this:

`win.loadURL("app://./index.html");`

to this:

```
const path = require("path");
win.loadFile(path.resolve(__dirname, "./index.html"));
```
Is this related to #76 ? 

Thank you for this plugin; exactly what I needed.

**Comment by nklayman** [comment]
These was caused by the `app://` scheme not being registered as standard. This is fixed as of version `1.3.2`. If you were previously using an older version, you must manually update your `background.js`:

```js
// Replace
protocol.registerSchemesAsPrivileged([{scheme: 'app', privileges: { secure: true } }])
// With
protocol.registerSchemesAsPrivileged([{scheme: 'app', privileges: { secure: true, standard: true } }])
```
