### ISSUE TITLE
electron-updater Error

### ISSUE THREAD

**Issue by waveTan** [nklayman/vue-cli-plugin-electron-builder#266]
ENOENT: no such file or directory, open 'D:\work\wallet_2.0\dist_electron\dev-app-update.yml'

**Comment by nklayman** [comment]
Can you please create a new issue that follows [the bug report template](https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/master/.github/ISSUE_TEMPLATE/bug-report.md).
