### ISSUE TITLE
Native module issue (serialport) after upgrading from 1.2.0 to 1.3.2

### ISSUE THREAD

**Issue by Corben78** [nklayman/vue-cli-plugin-electron-builder#269]
I just upgraded my electron-app from vue-cli-plugin-electron-builder 1.2.0 to 1.3.2, including the upgrade from electron 4.0.0 to 5.0.1.

This cause some issues, which I mainly could solve:
* in `backround.js` it's now:
```javascript
protocol.registerSchemesAsPrivileged([{scheme: 'app', privileges: { secure: true, standard: true } }])
```
* `nodeItegration` defaults to false [now](https://electronjs.org/blog/electron-4-0#webpreferences-default-values), causing `require is not defined` errors:
```javascript
  win = new BrowserWindow({
    webPreferences: {
      nodeIntegration: true
    }
  })
```
* A default menu is [now](https://electronjs.org/blog/electron-5-0#defaults-for-packaged-apps) also shown in packaged builds, but the new `win.removeMenu()` has no effect, this works for me:
```javascript
if (! isDevelopment) {
  win.setMenuBarVisibility(false)
}
```

But I couldn't solve properly my issue with serialport. I've read in the [documentation](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules) about native modules, that they should be included with an `externals` entry, which worked before. But now it's complaining about version mismatches, like mentioned in the [Using Native Modules](https://electronjs.org/docs/tutorial/using-native-node-modules) of the electron docs:
```
Error: The module '/path/to/native/module.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION $XYZ. This version of Node.js requires
NODE_MODULE_VERSION $ABC. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```
I was using nodejs v10, and I guess I was just lucky that electron's (v4.x) nodejs version matched my local version. Because now I upgraded to nodejs v12, which is the included nodejs version of electron v5, but there is still a minor version mismatch (70 vs 74). I got the 74 version after executing `npm rebuild`, as `npm install` gives me an even older version.

So I followed the instructions to install electron-rebuild, and changed the "postinstall" in `package.json` to: `"electron-rebuild -f -w serialport; electron-builder install-app-deps"`

Now it works, but when inovking `npm run electron:build` the output states:
```bash
electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies
```

So, what's the proper way to get a matching version of serialport for electron via vue-cli-plugin-electron-builder?

**Comment by nklayman** [comment]
Use `electron-builder install-app-deps`. Electron Builder has a dependency rebuild feature built in, so electron-rebuild is not necessary. After running that, you should be able to use it with electron. That should be in your `postinstall` script so that it gets run each time deps are rebuilt with yarn.

**Comment by Corben78** [comment]
Yeah, I thought so. But apparently I'm missing a piece. Is yarn a necessity? I'm using npm for package management.

As written above, with nodejs 10 LTS, electron 4 and vue-cli-plugin-electron-builder it's still working this way. But after the upgrade, the serialport package is not rebuild for the new version of electron and fails. After I delete the `node_modules` folder, and do a `npm install` followed by `npm run electron:serve` I get:
```
Uncaught Error: The module '/home/corben/git/electron_app/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 47. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```
When running `npm rebuild` and then `npm run electron:serve` I get:
```
Uncaught Error: The module '/home/corben/git/electron_app/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```
And I just realize I mistyped in my original posting, it's complaining about version 72 vs 70.

In my `package.json` I have exactly as you wrote: 
```
"postinstall": "electron-builder install-app-deps"
```
But it's not working. Only when I change that to:
```
"postinstall": "electron-builder install-app-deps; electron-rebuild -f -w serialport"
```
It's rebuilding after `npm install` and working then:
```
$ npm install

> movemaster_evue@0.5.0-rc2 postinstall /home/corben/git/electron_app
> electron-builder install-app-deps; electron-rebuild -f -w serialport

Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
  • electron-builder version=20.39.0
  • rebuilding native production dependencies platform=linux arch=x64
✔ Rebuild Complete
```
The last entry (rebuild complete) then rebuilds serialport, and I can run `npm run electron:serve` or `npm run electron:build` successfully.

What am I missing?

**Comment by gilfuser** [comment]
I had the exact same problem and `electron-builder install-app-deps` didn't work for me too.
As a workaround I'm using electron-rebuild. I know it shouldn't be necessary but its the way I found to keep things rolling.

**Comment by nklayman** [comment]
Seems like this is an issue with [electron-builder](https://github.com/electron-userland/electron-builder). My guess is that electron-builder got updated when you updated vue-cli-plugin-electron-builder, as nothing related to native modules was changed from 1.2.0 to 1.3.2. Try opening and issue on their repository instead.
