### ISSUE TITLE
from Terser Octal escape sequences are not allowed in template strings

### ISSUE THREAD

**Issue by BHDHakim** [nklayman/vue-cli-plugin-electron-builder#270]
![err](https://user-images.githubusercontent.com/30724283/57468478-5ec23900-7239-11e9-9eb3-4bf9278af9ec.PNG)

**Describe the bug**
when trying to build vue electron app with @vue/cli-service, it fails to cmopile because **Terser** moduel find an Octal esacape sequences.
after a long search I found out that importing mongoose in the main process is causing the problem by deleting it everything works fine

**Environment :**
 - OS and version: win32
 - vue-cli-plugin-electron-builder version : 1.3.1
 - electron version: 4.0.0
 - mongoose: 5.5.0

**Comment by nklayman** [comment]
Try setting mongoose as an [external](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules) by setting your `vue.config.js` to this:

```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['mongoose']
    }
  }
}
```

**Comment by BHDHakim** [comment]
> Try setting mongoose as an [external](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules) by setting your `vue.config.js` to this:
> 
> ```js
> module.exports = {
>   pluginOptions: {
>     electronBuilder: {
>       externals: ['mongoose']
>     }
>   }
> }
> ```

**Comment by BHDHakim** [comment]
> Try setting mongoose as an [external](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules) by setting your `vue.config.js` to this:
> 
> ```js
> module.exports = {
>   pluginOptions: {
>     electronBuilder: {
>       externals: ['mongoose']
>     }
>   }
> }
> ```
It did totaly worked, thank you so much. so I think i should close the issue since it's solved and get to learn more about @vue/cli
