### ISSUE TITLE
field unpackDirName unsupported?

### ISSUE THREAD

**Issue by Sombian** [nklayman/vue-cli-plugin-electron-builder#271]
**Describe the bug**
since 20.40.1 electron-builder has added new field [unpackDirName] and this yet implemented.

**To Reproduce**
declare [unpackDirName] under the key [portable].

**Expected behavior**
let users allow to control temp extract folder directory.

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: windows / latest
 - node version: latest
 - npm version: latest
 - yarn version (if used): latest
 - vue-cli-plugin-electron-builder version : latest
 - electron version: latest
 - other vue plugins used: vuetify, vue-router, vuex, vuetify-loader, vue-template-compiler
 - custom config for vcp-electron-builder: none
 - (if possible) link to your repo: 

**Additional context**

**Comment by nklayman** [comment]
I can't seem to find documentation for `unpackDirName`. Can you link to the page on electron-builder's docs where it described?

**Comment by Sombian** [comment]
https://github.com/electron-userland/electron-builder/issues/3799#issuecomment-480185505

**Comment by nklayman** [comment]
All electron-builder option should be supported as electron-builder is called directly without any custom modifications. Can you send me a demo repo that demonstrates the problem?

**Comment by Sombian** [comment]
Im on a festival now. Ill let you know further details when back home. All i remember is error messages that says i cant declared unallowed key.

**Comment by Sombian** [comment]
> All electron-builder option should be supported as electron-builder is called directly without any custom modifications. Can you send me a demo repo that demonstrates the problem?

sorry for late response. been busy these days.

`    var $ = function (index, safety, process) {
      global._module_.configuration.downloader(index, safety, function (result) {
        console.log(`(MODE: ${safety ? "SLOW" : "FAST"} | progress: ${index}/${process} | detail: ${JSON.stringify(global._module_.configuration.json.downloader.process[index])})`);
        if (process === index) {
          return;
        }
        else if (process > index) {
          $(result || safety ? index + 1 : index, result || safety ? false : true, process);
        }
      });
    }
    $(0, false, global._module_.configuration.json.downloader.process.length);`

**Comment by nklayman** [comment]
The electron-builder version is out of date. Try `npm i --save-dev vue-cli-plugin-electron-builder`.

**Comment by Sombian** [comment]
> The electron-builder version is out of date. Try `npm i --save-dev vue-cli-plugin-electron-builder`.

nothing changed. can you please update ``electron-builder`` version in ``package.json`` to ``^20.41.0``?

https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/master/package.json

**Comment by nklayman** [comment]
I'd rather not update the version in the `package.json` as previous versions work just work fine. Use [yarn resolutions](https://yarnpkg.com/en/docs/selective-version-resolutions) or [edit the package-lock.json](https://stackoverflow.com/a/48524488) to force electron-builder to update.
