### ISSUE TITLE
Webpack aliases not working in background.js

### ISSUE THREAD

**Issue by angeliski** [nklayman/vue-cli-plugin-electron-builder#274]
**Describe the bug**
The webpack aliases created in vue.config.js are not being resolved in the background.js
ps. The repo has using the default vue-cli alias @ -> src, but customized alias not working too.

**To Reproduce**
- Create a project with Vue CLI
- Install vue-cli-plugin-electron-builder via terminal
- Add a import with alias in the background.js (like @/file)
- Run the command npm run serve:electron

**Expected behavior**
The same alias configuration works with npm run serve & build is being created successfully. It fails with this plugin only.

**Screenshots**
![1__rogerio_imac-do-rogerio____workspace_electron-builder-alias__zsh_](https://user-images.githubusercontent.com/1574240/57621548-1faa2580-7562-11e9-8ebe-d68e4bfe9a8d.png)

**Environment (please complete the following information):**
Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.7.0 - ~/.yarn/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: Not Found
    Safari: 12.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.7.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.7.0
    @vue/cli-plugin-babel: ^3.7.0 => 3.7.0
    @vue/cli-plugin-eslint: ^3.7.0 => 3.7.0
    @vue/cli-service: ^3.7.0 => 3.7.0
    @vue/cli-shared-utils:  3.7.0
    @vue/component-compiler-utils:  2.6.0
    @vue/eslint-config-prettier: ^4.0.1 => 4.0.1
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.2
    vue: ^2.6.10 => 2.6.10
    vue-cli-plugin-electron-builder: ^1.3.2 => 1.3.2
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: 3.4.0

 - (if possible) link to your repo: https://github.com/angeliski/electron-builder-alias/blob/master/src/background.js

**Comment by nklayman** [comment]
As per the [plugin docs on webpack config](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#webpack-configuration), the main process has a separate configuration, you must define your aliases there.
