### ISSUE TITLE
Using local database after electron build

### ISSUE THREAD

**Issue by j-nguyen** [nklayman/vue-cli-plugin-electron-builder#275]
Hey all. I'm currently using Electron 5.0.1, Vue 2.6, and The Electron Builder v1.3.1. I'm having trouble getting SQLite to work when I'm trying to build a MacOS or Windows app.

Here's what my `vue.config.js` looks like:

```javascript
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        data: `
          @import "@/styles/main.scss";
        `,
      },
    },
  },
  configureWebpack: {
    externals: {
      sequelize: "require('sequelize')",
    },
  },
  pluginOptions: {
    electronBuilder: {
      externals: ['sequelize'],
      builderOptions: {
        extraResources: ['src/data.db'],
      },
    }
  },
};
```

and Here's how I connect via my db:

```javascript
import Sequelize from 'sequelize';
import Component from '@/models/component';
import Element from '@/models/element';
import Kiosk from '@/models/kiosk';
import Page from '@/models/page';
import path from 'path';

const isBuild = process.env.NODE_ENV === 'production';
const pathToDbFile = path.join( // eslint-disable-next-line
  (isBuild ? __dirname : __static),
  (isBuild ? '../../' : ''),
  '../src/data.db',
);

// setup the connection to make sure it works
const sequelize = new Sequelize({
  dialect: 'sqlite',
  storage: pathToDbFile,
  logging: (process.env.NODE_ENV !== 'production') ? console.log : false,
  define: {
    timestamps: false,
    underscored: true,
  },
});

const db = {};

// test for the connection
if (process.env.NODE_ENV !== 'production') {
  sequelize.authenticate()
    .then(() => {
      console.log('Connection has been established.');
    })
    .catch(console.error);
}

db.Component = Component.init(sequelize);
db.Element = Element.init(sequelize);
db.Kiosk = Kiosk.init(sequelize);
db.Page = Page.init(sequelize);

Object.keys(db).forEach((modelName) => {
  if (db[modelName].associate) db[modelName].associate(db);
});

db.Sequelize = Sequelize;
db.sequelize = sequelize;

export default db;
```

Any idea what's going on?

**Comment by nklayman** [comment]
I don't see any error when I run it myself. Please send me a demo repo that has the error.

**Comment by j-nguyen** [comment]
Hello, @nklayman.

Here's the repo:
https://github.com/j-nguyen/demo_vue_electron_sqlite

Here's some context. When I use `npm run electron:build` to generate a MacOS binrary, or Windows app, this is the error I receive:

![Screen Shot 2019-05-21 at 4 24 59 PM](https://user-images.githubusercontent.com/7433097/58128554-ed459b80-7be5-11e9-9e5d-ad98941af069.png)

**Comment by nklayman** [comment]
Use this:
```js
const pathToDbFile = path.join(
  // eslint-disable-next-line
  isBuild ? __dirname : __static,
  '../src/data.db',
);
```
not sure why the path changed, but this works now.

**Comment by j-nguyen** [comment]
@nklayman 

Thank you! This works, but I have another issue with sequelize and SQLite. I don't have a table named `fs`, but it keeps yelling at me that there is no such table for it. This hasn't happened to me when doing `electron:serve`, so I'm a bit confused now.

![Screen Shot 2019-05-23 at 4 44 14 PM](https://user-images.githubusercontent.com/7433097/58285168-3595c280-7d7a-11e9-890b-3d0e40c08484.png)

**Comment by j-nguyen** [comment]
Oh, nevermind. Got it cleared up. Just had to declare the `modelName` on sequelize. Thank you for your help!

**Comment by techuila** [comment]
@j-nguyen Have you encountered this error? 

>  Please install sqlite3 package manually

**Comment by ihewro** [comment]
> @j-nguyen Have you encountered this error?
> 
> > Please install sqlite3 package manually

`externals: ['sequelize'] ` in the vue.config.js works for me
