### ISSUE TITLE
Native module issue can't find module

### ISSUE THREAD

**Issue by toams69** [nklayman/vue-cli-plugin-electron-builder#276]
Hi,
First thanks for this awesome vue cli plugin, I am using it since few months...

Last week I've tried to add to my project a new native node module called 'netcdf4'. 
When I run npm/yarn install everything seems working, but when I run in dev mode the app I've got this issue:
(node:8948) UnhandledPromiseRejectionWarning: Error: Le module spécifié est introuvable.
\\?\C:\Projects\test\node_modules\netcdf4\build\Release\netcdf4.node

**Environment **
 - OS and version: Windows 10
 - node version: 11.6.0
 - npm version: 6.5.0-next.0
 - yarn version (if used): 1.13.0
 - vue-cli-plugin-electron-builder version : 
"dependencies": {
    "buefy": "^0.7.6",
    "core-js": "^2.6.5",
    "electron-promise-ipc": "^1.2.2",
    "fs-extra": "^8.0.1",
    "lodash": "^4.17.11",
    "material-design-icons": "^3.0.1",
    "moment": "^2.24.0",
    "netcdf4": "^0.4.1",
    "typeface-montserrat": "^0.0.54",
    "vue": "^2.6.10",
    "vue-class-component": "^7.0.2",
    "vue-i18n": "^8.11.2",
    "vue-property-decorator": "^8.1.0",
    "vue-router": "^3.0.3",
    "vuex": "^3.0.1",
    "vuex-class": "^0.3.2",
    "winston": "^3.2.1",
    "winston-daily-rotate-file": "^3.9.0",
    "xml2js": "^0.4.19"
  },

I am stuck on this point if someone could help me to resolve this :)

Thanks,

**Comment by nklayman** [comment]
It fails to install for me, so I can't verify that it will work, but try listing netcdf4 as an [external](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules) by changing your `vue.config.js`:

```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['netcdf4']
    }
  }
}
```

**Comment by toams69** [comment]
thanks for ur help. I've already tried with this, but I still have the issue..

**Comment by j-nguyen** [comment]
@toams69 , have you tried configuring via `webpacker`? I had a similar issue with `sequelize`, and had to do both the electron builder and the `webpacker` configuration.

ex (`vue.config.js`):

```javascript
module.exports = {
  configureWebpack: {
    externals: {
      sequelize: "require('sequelize')",
    },
  },
  pluginOptions: {
    electronBuilder: {
      externals: ['sequelize'],
    }
  },
}
```

**Comment by nklayman** [comment]
@j-nguyen Not sure why you had to add it in both places. The plugin is supposed to add the external config for you.

**Comment by j-nguyen** [comment]
You're absolutely right. I just removed it and it worked for me now. Yeah, I'm sorry @toams69, I have no idea what the error is. If you could provide a demo repo, me, or someone else could try seeing what the issue might be.

**Comment by erikkallen** [comment]
I have a similar issue, when I use electron 5 is does not seem to build the native modules anymore, switching back to electron 4 seems to solve it for me.

**Comment by nklayman** [comment]
I was able to use netcdf fine without issue, whether or not I listed it as an external. Make sure electron-builder has rebuilt it (run `electron-builder install-app-deps`, should be your `postinstall`/`postuninstall` scripts). If it still doesn't work for you, please send me a demo repo.

**Comment by toams69** [comment]
Sorry for the delay.
@nklayman I found the issue, it was due to the fact than in windows, the netcdf bin folder was not correctly added in the path. Once fixed, it was working in dev mode. 
In prod mode I've updated the build to copy the dll/lib depending on the target os + arch in the app folder. 
It works now.
Thanks for your help
