### ISSUE TITLE
How to support you? 

### ISSUE THREAD

**Issue by sanch941** [nklayman/vue-cli-plugin-electron-builder#278]
**Can u give your paypal or visa or mastercard to support this project?**
This project is very cool and i wanna help you. Think other support too if there will be support page

**Comment by nklayman** [comment]
I'm really glad you appreciate my work! I've signed up for [Github Sponsors](https://help.github.com/en/articles/about-github-sponsors). Right now it is a closed beta, so hopefully they accept me soon. If I don't hear back in a few days, I'll set up Patreon or Paypal or something else. Thanks again for your support!

**Comment by sanch941** [comment]
> I'm really glad you appreciate my work! I've signed up for [Github Sponsors](https://help.github.com/en/articles/about-github-sponsors). Right now it is a closed beta, so hopefully they accept me soon. If I don't hear back in a few days, I'll set up Patreon or Paypal or something else. Thanks again for your support!

Nice!

**Comment by sanch941** [comment]
> I'm really glad you appreciate my work! I've signed up for [Github Sponsors](https://help.github.com/en/articles/about-github-sponsors). Right now it is a closed beta, so hopefully they accept me soon. If I don't hear back in a few days, I'll set up Patreon or Paypal or something else. Thanks again for your support!

Is there any news from github sponsors?

**Comment by nklayman** [comment]
Unfortunately I haven't gotten any response yet. In the meantime, you can donate to my Paypal or Venmo. My email address is `noahklayman@gmail.com` for both platforms. I'll add a sponsors/backers section to the readme/docs and will put the name and picture of anyone who donates there.

**Comment by nklayman** [comment]
I added sponsor links to my Venmo and PayPal in the repository, which should be enough for now. As soon as I get accepted to GitHub sponsors I will add that.

**Comment by nklayman** [comment]
My [github sponsors profile](https://github.com/sponsors/nklayman) is now live! Github will match donations for the first year as well!
