### ISSUE TITLE
"doc.save" is not working in electron build and serve environment

### ISSUE THREAD

**Issue by dhall2211** [nklayman/vue-cli-plugin-electron-builder#280]
**Describe the bug**
I have created a simple pdf generator and I have found that when I run npm run serve my logic is working however when I build the electron app from the electron environment this feature is not working. I have seen other come up with the same issue. later I tried to install an electron environment outside the CLI and found that It worked. i think it is something to do with node server running but I am not sure.
**To Reproduce**

start a project and add this dependancy
npm install jspdf --save

add this logic to a project in a method and connected it to a button click
submitPdf () {
      console.log('hello')
      var doc = new jsPDF();
     doc.text(10, 10, 'hello world')
      doc.save("test.pdf");
    }

**Expected behavior**
you should be able to create a pdf with hello world

**Environment (please complete the following information):**
 - OS and version: windows 10
 - node version: 10.15.1 
 - npm version: 6.4 .1
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version :  1.3 0
 - electron version: 5.0.0
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**

**Comment by dhall2211** [comment]
I found a fix add this to main.js...
in createWindow function add as a parameter
webPreferences: {
      nodeIntegration: true
    }

**Comment by nklayman** [comment]
Without `nodeIntegration`, you can't use any node APIs (like fs). It seems like jspdf uses the fs api, so `nodeIntegration` would have to be enabled.
