### ISSUE TITLE
Unable to use jsx

### ISSUE THREAD

**Issue by u3u** [nklayman/vue-cli-plugin-electron-builder#29]
![image](https://user-images.githubusercontent.com/20062482/42102054-76131fc2-7bf7-11e8-8f00-0f730af6e48e.png)

**Comment by nklayman** [comment]
You have to add support for jsx manually. See the readme for more details. A better alternative is to use the 1.0.0 alpha version. It is almost equally stable compared to the standard release, and is much better overall.

**Comment by u3u** [comment]
I tried to manually add a type definition to test, TS passed the check, but still prompt module can not be resolved. Why is this? 🤔

```bash
$ echo 'export default function(scheme: string): void;' >> node_modules/vue-cli-plugin-electron-builder/lib/createProtocol.d.ts
```

**Comment by nklayman** [comment]
When the first 1.0.0 beta comes out (next release) all of the changes you had to do will be automatic. I can add the createprotocol.d.ts file if you think it is necessary, but it seems overkill as it is just a single function that isn't used outside of the generated files.

**Comment by u3u** [comment]
Ok, now I disable the main process TypeScript via `disableMainProcessTypescript`.
Maybe you can set `v1-dev` as the default branch first.
Thank you for your great job!

**Comment by nklayman** [comment]
No problem, glad that you fixed it. As soon as the beta comes out it will be the default version. It will have near 100% test coverage and should be very stable.

**Comment by nklayman** [comment]
v1.0.0-beta.1 is out, you can use that now as it includes typings for createProtocol()
