### ISSUE TITLE
[Question] Some dependencies are missing in the production build

### ISSUE THREAD

**Issue by Last-Order** [nklayman/vue-cli-plugin-electron-builder#294]
I'm not sure where to report this problem. 

After building with electron builder, I found that socket.io (one of my dependencies) is not packed into the production build, which caused errors.

If it's possible related to the `.` character in the package name? I found this related issue: https://github.com/electron-userland/electron-packager/issues/768

I also tried to configure electron builder's `files` option. 

when it sets to 

```
files: [
                    "**/*",
                    "!node_modules",
                    "node_modules/socket.io",
                ],
``` 

nothing was packed.

but if it sets to

```
files: [
                    "**/*",
                    "!node_modules",
                    "node_modules/express"
                ],
```

then only express was packed.

when sets to 
```
files: [
                    "**/*",
                    "!node_modules",
                    "node_modules/socket.io",
                    "node_modules/express"
                ],
```

only express was packed too.

Do you have any ideas? Thanks.

fyi. [my project](https://github.com/Last-Order/YouTube-Live-Poll)

**Comment by nklayman** [comment]
You'll need to list `socket.io` as an [external](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules) by setting your `vue.config.js` to this:
```js
module.exports = {
    devServer: {
        host: 'localhost',
        disableHostCheck: true
    },
    transpileDependencies: [
        'vue-echarts',
        'resize-detector'
    ],
    pluginOptions: {
        electronBuilder: {
            chainWebpackMainProcess: config => {
                // Chain webpack config for electron main process only
                config.mode('development');
                // config.externals(['uws']);
            },
            externals: ['socket.io'], // This marks socket.io as an external
            builderOptions: {
                // files: [
                //     "**/*",
                //     "!node_modules",
                //     "node_modules/socket.io",
                //     "node_modules/express"
                // ],
                appId: 'moe.sound.sora.ylp',
                asar: false,
                artifactName: "ylp-${os}-${version}.${ext}",
                productName: 'YouTube Live Poll',
                win: {
                    target: ['msi'],
                    icon: 'build/icons/icon.ico'
                },
                mac: {
                    category: 'public.app-category.developer-tools',
                    target: ['dmg']
                },
                linux: {
                    target: ['deb', 'appImage']
                }
            }
        }
    }
}
```

**Comment by nklayman** [comment]
The reason socket.io is not included is because non-externals are supposed to be bundled by webpack. Since your server file is not bundled by webpack, socket.io is not bundled. It is probably better to have your server file bundled into the `background.js` as that will increase performance by reducing the number of `require`s.

**Comment by Last-Order** [comment]
Thanks for your solution and advice. Thanks a lot!

**Comment by mxswat** [comment]
This solution also allows us to run a socket.io server + express inside the electron process
