### ISSUE TITLE
vue add electron-builder 

### ISSUE THREAD

**Issue by tensor2flow** [nklayman/vue-cli-plugin-electron-builder#297]
�  Installing vue-cli-plugin-electron-builder...

yarn add v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
error electron-builder@20.41.0: The engine "node" is incompatible with this module. Expected version ">=8.12.0". Got "8.11.3"
 Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
 ERROR  command failed: yarn add -D vue-cli-plugin-electron-builder

**Comment by nklayman** [comment]
[Electron Builder](https://electron.build), a dependency of Vue CLI Plugin Electron Builder, requires a more recent version of Node. Update your Node version and re-install the plugin. I recommend upgrading to v10.x.
