### ISSUE TITLE
Best way to change the renderer and main process entry point?

### ISSUE THREAD

**Issue by dylrich** [nklayman/vue-cli-plugin-electron-builder#30]
Hi there, I attempted to change the main process entrypoint using the WebPack configuration in vue.config.js mentioned in the readme and did not have any success - serve:electron was still only looking for index/main/app.js in a main folder. I also could not find information on how to change the entrypoint for the renderer process from index/main/app.js in the root directory. Any more detailed instructions on how to configure these two entrypoints would be fantastic! Thanks!

**Comment by nklayman** [comment]
Are you using the 1.0.0 beta? If so, the render process entrypoint is the same as your SPA build, and the main process entrypoint can be customized with the `mainProcessFile` key under vcp-elctron-builder's plugin options.

If you are not using the 1.0.0 beta, I recommend upgrading (it is quite stable). If you can't upgrade, you have to [configure electron-webpack](https://webpack.electron.build/configuration) to customize your entrypoints.

**Comment by dylrich** [comment]
I am not using the 1.0.0 beta, but I will take a look at upgrading. Appreciate the response!

**Comment by nklayman** [comment]
Glad I could help. The 1.0 beta is better for a multitude of reasons. It is just as stable and I'm only waiting for more feedback before the final release.
