### ISSUE TITLE
Electron shell cant open __static folder files in production

### ISSUE THREAD

**Issue by sanch941** [nklayman/vue-cli-plugin-electron-builder#300]
**Describe the bug**
I use electron shell to open file from public folder via __static variable. In development this works but when i build project and install it there is no files from public folder

**To Reproduce**
create file in public
open it in main process via electron shell
import { shell } from 'electron'
import path from 'path'

const dir = path.join(__static, 'myElectronFile.exe' )
shell.openItem(dir)

**Expected behavior**
start exe file in production

**Additional context**

**Comment by nklayman** [comment]
The issue is that your app is packaged into an asar archive. `openItem` only works if the file is in an uncompressed directory. Follow [these instructions](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/76#issuecomment-420060179) to package a file outside of the asar.
