### ISSUE TITLE
Dynamically require module in main thread from any location

### ISSUE THREAD

**Issue by KenavR** [nklayman/vue-cli-plugin-electron-builder#301]
**Describe the bug**
*Not sure if that is an actual bug or something I am doing wrong*
I am trying to dynamically `require` modules from an undefined location (at build time) in the main thread at run time. When I call `require(join(root, pluginPath))` in the main thread I get 
`Error: Cannot find module ...` and some webpack hints in the stack. As I understand it, webpack shouldn't be involved in the main thread.   

**To Reproduce**
Require a module that is not part of the project using `const path = "..."; require(path)` in the main thread.

**Expected behavior**
The module gets loaded and I can access it's exported api.

**Environment (please complete the following information):**
 - OS and version: Windows 10 1803
 - node version: 10.15.3
 - npm version: 6.9.0
 - vue-cli-plugin-electron-builder version : 1.3.2
 - electron version: 5.0.1
 - other vue plugins used: none
 - custom config for vcp-electron-builder: none
 - (if possible) link to your repo: private, but if necessary I can create one showing the error.

Is there some configuration I need to webpack to make that work?

**Comment by nklayman** [comment]
Webpack will try and bundle your modules at build time, unless they are marked as an [external](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules). Once they are marked as an external, they won't be bundled by webpack and instead will be resolved at runtime.

**Comment by KenavR** [comment]
The problem is I can't define them as external, because they can be anywhere on disk. The user defines where the modules are stored. The root path is loaded from a config file at run time.

**Comment by nklayman** [comment]
Oh yeah, duhhh. Use `__non_webpack_require__`. It functions the same way as `require`, but is ignored by webpack.

**Comment by KenavR** [comment]
thanks
