### ISSUE TITLE
.env.production not work

### ISSUE THREAD

**Issue by huangdongqin** [nklayman/vue-cli-plugin-electron-builder#304]
**Describe the bug**

**To Reproduce**
1. in the root , i have .env , .env.production, and .env.development
2. i set the NODE_ENV=production in the .env file
3. run vue-cli-service electron:build
4. in the dist, my electron programe can't read .env.production‘s value, BUT IT CAN READ .env values

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: win10
 - node version: 10.0
 - npm version: 
 - yarn version (if used): not
 - vue-cli-plugin-electron-builder version : 1.3.4 
 - electron version: 5.0
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**

**Comment by nklayman** [comment]
Env variables should function the same way as a web app as the build process is the same. I tried it myself and was unable to replicate the error. Can you try with a blank project and send me an example repo that contains the error?

**Comment by huangdongqin** [comment]
> Env variables should function the same way as a web app as the build process is the same. I tried it myself and was unable to replicate the error. Can you try with a blank project and send me an example repo that contains the error?

thx for u repay, and i try make a blank project https://github.com/huangdongqin/test-vue-electronbuilder-env
but it works....it works.....
so sad, it must something wrong with my production project, i will check again.

**Comment by huangdongqin** [comment]
> Env variables should function the same way as a web app as the build process is the same. I tried it myself and was unable to replicate the error. Can you try with a blank project and send me an example repo that contains the error?

u are right, i just make a mistake, my real project .env.production file name is wrong. it works well now. thanks.....

**Comment by nklayman** [comment]
Glad you could figure it out!
