### ISSUE TITLE
nedb no visible

### ISSUE THREAD

**Issue by sujianqingfeng** [nklayman/vue-cli-plugin-electron-builder#307]
**Describe the bug**
nedb file no visible，but data can be read，Can you give me an answer? Thx

```
# data.js

import Datastore from 'nedb'
import path from 'path'
import {remote} from 'electron'


const a = path.join(remote.app.getPath('userData'),'/data.db')

console.log(a)
const db = new Datastore({
    autoload:true,
    filename:a
})
```

```
# main.js
import './data.js'
...
```

**Comment by nklayman** [comment]
Is this in the main or renderer process?

**Comment by sujianqingfeng** [comment]
The rendering process is invisible and the main process is visible. Finally, I changed to lowdb.thx

**Comment by nklayman** [comment]
This is the same issue as https://github.com/louischatriot/nedb/issues/531. Mark `nedb` as an external to use the database file instead of IndexedDB:

```js
// vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['nedb']
    }
  }
}
```

**Comment by nklayman** [comment]
The main process is bundled with the webpack target set to `electron-main`, while the rendere is bundled with `electron-renderer`. This causes nedb to use IndexedDB in the renderer process.

**Comment by Hariprabu94** [comment]
> This is the same issue as [louischatriot/nedb#531](https://github.com/louischatriot/nedb/issues/531). Mark `nedb` as an external to use the database file instead of IndexedDB:
> 
> ```js
> // vue.config.js
> module.exports = {
>   pluginOptions: {
>     electronBuilder: {
>       externals: ['nedb']
>     }
>   }
> }
> ```

i added this to my vue.config.js file. even nedb saving data to indexed db only. What i should do to keep external file.
 my vue cli version is 4.4.6
