### ISSUE TITLE
Blank screen only for build

### ISSUE THREAD

**Issue by infinitetrinity** [nklayman/vue-cli-plugin-electron-builder#308]
**Describe the bug**
Application works in serve mode but blank screen on build

**Environment (please complete the following information):**
 - OS and version: Window 10
 - node version: v10.15.3
 - npm version: 6.4.1
 - yarn version (if used): 1.3.2
 - vue-cli-plugin-electron-builder version : ^1.1.1
 - electron version: ^4.0.0
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

I have tried the [history mode fix ](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#blank-screen-on-builds-but-works-fine-on-serve) and also did `vue invoke electron-builder` with no result.

My package.json as below:
```
{
  "name": "application",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "dist": "electron-builder",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "pack": "electron-builder --dir",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps"
  },
  "dependencies": {
    "macaddress": "^0.2.9",
    "node-machine-id": "^1.1.12",
    "printer": "^0.2.2",
    "vue": "^2.6.6",
    "vue-notification": "^1.3.16",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.15",
    "@fortawesome/free-regular-svg-icons": "^5.7.2",
    "@fortawesome/free-solid-svg-icons": "^5.7.2",
    "@fortawesome/vue-fontawesome": "^0.1.5",
    "@vue/cli-plugin-babel": "^3.5.0",
    "@vue/cli-plugin-eslint": "^3.5.0",
    "@vue/cli-service": "^3.5.0",
    "axios": "^0.18.0",
    "babel-eslint": "^10.0.1",
    "electron": "^4.0.0",
    "electron-rebuild": "^1.8.4",
    "eslint": "^5.8.0",
    "eslint-plugin-vue": "^5.0.0",
    "idb": "^3.0.2",
    "jquery": "^3.3.1",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "node-thermal-printer": "^4.0.2",
    "tailwindcss": "^0.7.4",
    "v-click-outside": "^2.0.2",
    "vue-cli-plugin-electron-builder": "^1.1.1",
    "vue-scroll": "^2.1.9",
    "vue-scrollto": "^2.15.0",
    "vue-select": "^2.6.0",
    "vue-slick": "^1.1.15",
    "vue-template-compiler": "^2.5.21",
    "vuelidate": "^0.7.4",
    "windows-build-tools": "^5.1.0"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "tailwindcss": "./tailwind.js",
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ],
  "externals": [
    "printer"
  ],
  "main": "background.js"
}
```

No error message/popup, no menu bar so i cant open devtools to check. shortcut for devtools dont work. Any idea? 
Thanks!

**Comment by nklayman** [comment]
In your `background.js`, move the `if (!process.env.IS_TEST) win.webContents.openDevTools()` outside of the `if (process.env.WEBPACK_DEV_SERVER_URL)` block so that devtools will open in build. Then you can try and debug your issue further.

**Comment by joeelia** [comment]
Hmm I had the same issue and fixed it with the history mode fix

Although I am using:
OS and version: OSX 10.14.5
node version: v12.3.1
electron version: ^5.0.0

Good luck!

**Comment by infinitetrinity** [comment]
Resolved the issue after unblocking devtools.
Problem lies with 'node-thermal-printer' package and [this ](https://github.com/Klemen1337/node-thermal-printer/pull/106)will fix the issue.
Thanks for helping!
