### ISSUE TITLE
ipc renderer or ipc main function stop working on electron:build

### ISSUE THREAD

**Issue by nickfan** [nklayman/vue-cli-plugin-electron-builder#311]
**Describe the bug**
i build my app with vue-cli-plugin-electron-builder
it works fine when i'm develop with 
```electron:serve``` aka ``` vue-cli-service electron:serve ```
but when i'm try to release the app,and run the app 
ipc renderer or ipc main function seems stop working on electron:build
other function seems work fine(shell.openExternal,shell.showItemInFolder on the client side)

at first i thought it might be the custom protocol problem,i switch back to 'app://./',it didn't work.

and i got nothing respone from log file or the devtools console,
so i install devtron,and open the ipc panel:
and i found message send from renderer but nothing responsed.
and i could not find where to read from app(main) console,
so how could i debug the problem?

![image](https://user-images.githubusercontent.com/100613/59490486-69ff2900-8eb7-11e9-9051-a82616ce58a6.png)

**To Reproduce**

**Expected behavior**
ipcmain and ipcrenderer send and receive message from each side.

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: mac 10.14.5
 - node version: v10.15.3
 - npm version: 6.9.0
 - yarn version (if used): 1.16.0
 - vue-cli-plugin-electron-builder version : 1.3.4
 - electron version: 5.0.1
 - other vue plugins used: 
```
"dependencies": {
    "@chenfengyuan/vue-qrcode": "^1.0.0",
    "@trodi/electron-splashscreen": "^0.3.4",
    "axios": "^0.19.0",
    "carlo": "^0.9.45",
    "chai-as-promised": "^7.1.1",
    "chalk": "^2.4.2",
    "cheerio": "^1.0.0-rc.3",
    "core-js": "^2.6.5",
    "dayjs": "^1.8.14",
    "dotenv": "^8.0.0",
    "electron-json-storage": "^4.1.6",
    "electron-log": "^3.0.6",
    "iview": "^3.0.1",
    "js-cookie": "^2.2.0",
    "jsotp": "^1.0.4",
    "lodash": "^4.17.11",
    "nedb": "^1.8.0",
    "nedb-models": "^2.2.6",
    "nedb-promises": "^3.0.4",
    "superagent": "^5.0.5",
    "uuid": "^3.3.2",
    "vue": "^2.6.10",
    "vue-electron-json-storage": "^1.0.1",
    "vue-resource": "^1.5.1",
    "vue-router": "^3.0.3",
    "vuex": "^3.0.1",
    "vuex-persistedstate": "^2.5.4"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.8.0",
    "@vue/cli-plugin-eslint": "^3.8.0",
    "@vue/cli-plugin-unit-mocha": "^3.8.0",
    "@vue/cli-service": "^3.8.0",
    "@vue/eslint-config-prettier": "^4.0.1",
    "@vue/test-utils": "1.0.0-beta.29",
    "babel-eslint": "^10.0.1",
    "babel-plugin-lodash": "^3.3.4",
    "canvas-mock": "^0.0.0",
    "chai": "^4.1.2",
    "cross-env": "^5.2.0",
    "devtron": "^1.4.0",
    "electron": "^5.0.0",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "lodash-webpack-plugin": "^0.11.5",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.1.0",
    "vue-cli-plugin-electron-builder": "^1.3.4",
    "vue-cli-plugin-iview": "^1.0.6",
    "vue-template-compiler": "^2.6.10"
  },
"resolutions": {
    "@vue/eslint-config-prettier/prettier": "1.13.7"
  }
```

 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

```
module.exports = {
  lintOnSave: true,
  pluginOptions: {
    electronBuilder: {
      customFileProtocol: "bzwb://./",
      // customFileProtocol: 'file://./',
      removeElectronJunk: false,
      builderOptions: {
        // options placed here will be merged with default configuration and passed to electron-builder
        appId: "com.example.app",
        productName: "MyExample",
        protocols: [
          {
            name: "My Example URL",
            schemes: ["bzwb"]
          }
        ],
        mac: {
          target: "default"
        },
        nsis: {
          oneClick: false,
          perMachine: true,
          allowToChangeInstallationDirectory: true
        },
        win: {
          target: [
            {
              target: "nsis",
              arch: ["x64", "ia32"]
            }
          ]
        }
      }
    }
  }
};

```

**Additional context**

**Comment by nklayman** [comment]
Can you upload your `background.js` as well. I've used IPC without issue.

**Comment by nickfan** [comment]
ok,i found the reason,it's my design problem,
i build my event listeners regist depends on the class name,in the DEV mode,it's fine for that,but after asar or webpack uglify plugin minify the production file,it will change the class name so my listeners regist flow stop working.


and i found that the only way to avoid that is 

```
class SomeClass {
  static getClassName(){ return 'SomeClass'; }
  getClassName(){ return this.constructor.getClassName(); }
  constructor() {}
}
```

reference:

https://stackoverflow.com/questions/29310530/get-the-class-name-of-es6-class-instance
