### ISSUE TITLE
Production external dependencies not bundled with electron:build

### ISSUE THREAD

**Issue by Muffinman** [nklayman/vue-cli-plugin-electron-builder#312]
**Describe the bug**
As described in the docs [here](https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/master/docs/guide/guide.md), I'm attempting to package the [hostile](https://www.npmjs.com/package/hostile) module as an external dependency and make it available to call within the app. However, the build command runs successfully but no dependencies are installed into `dist_electron/bundled/node_modules`.

I think I need to package this as an external dependency, because the app needs to call it through the `sudo-prompt` module as a CLI call.

My vue.config.js:
```js
const CopyPlugin = require('copy-webpack-plugin');

module.exports = {
    configureWebpack: {
        plugins: [
            new CopyPlugin([
                {
                    from: 'storage/snippets',
                    to: 'storage/snippets',
                },
            ]),
        ]
    },
    pluginOptions: {
        electronBuilder: {
            // List native deps here if they don't work
            externals: ['hostile'],
        }
    }
}
```

**To Reproduce**

1. Require module with `npm install --save hostile`
2. Add as an external dependency in `vue.config.js`
3. Run `npm run electron:build`
4. Check `dist_electron/bundled/node_modules` (it's empty)

**Expected behavior**
1. External dependency gets packaged into `dist_electron/bundled/package.json` (it does this correctly)
2. Dependency gets installed into production app node_modules folder

**Environment (please complete the following information):**
 - OS and version: `MacOS Mojave`
 - node version: `v10.16.0`
 - npm version: `6.9.0`
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : `^1.3.4`
 - electron version: `^5.0.4`
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

My full root `package.json`:

```js
{
  "name": "devhosts",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps"
  },
  "main": "background.js",
  "dependencies": {
    "core-js": "^2.6.5",
    "fix-path": "^2.1.0",
    "hostile": "^1.3.2",
    "sudo-prompt": "^9.0.0",
    "vue": "^2.6.10",
    "vue-router": "^3.0.3",
    "vuex": "^3.0.1",
    "vuex-persist": "^2.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.8.0",
    "@vue/cli-plugin-eslint": "^3.8.0",
    "@vue/cli-service": "^3.8.4",
    "babel-eslint": "^10.0.1",
    "buefy": "^0.7.7",
    "electron": "^5.0.4",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "lodash": "^4.17.11",
    "sass": "^1.21.0",
    "sass-loader": "^7.1.0",
    "vee-validate": "^2.2.10",
    "vue-cli-plugin-electron-builder": "^1.3.4",
    "vue-template-compiler": "^2.6.10"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ],
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  }
}
```

Any help is greatly appreciated.

**Comment by nklayman** [comment]
This is intentional. The dir is supposed to be empty, otherwise electron-builder will reinstall deps with npm into that folder. Even if the folder is empty, the modules still get bundled into the asar. Install the `asar` package globally with `npm install --global asar`, and then extract the asar with `asar extract ./dist_electron/linux-unpacked/resources/app.asar ./asar`. If you look in the `asar/node_modules` folder, you will see that hostile and its dependencies are included. In the ned, the files are read from the asar archive, so that is all that matters.

**Comment by Muffinman** [comment]
Thanks for the info! I'm a little confused as to why that folder exists at all if is meant to be empty, but that does clear things up thank you.

I'm aware this may not be the right place to ask (the Google results on the subject seem quite limited), but I'm wondering if you could give me any advice on the best way to handle calling external binaries within the electron app?

Basically my use case is I'm building a little app to manage Nginx vhosts on Mac / Linux development environments. This requires that I use `sudo` ([sudo-prompt](https://github.com/jorangreef/sudo-prompt)) to rewrite the machine's `/etc/hosts` file and `restart nginx`.

I'm using [hostile](https://github.com/feross/hostile) to handle the hosts file editing, and this needs to be bundled with the app and executable by `sudo-prompt`. 

```js

const nginxPath = '/usr/local/bin/nginx';
const nginxRestartCmd = '/usr/local/bin/brew services restart nginx';
const hostilePath = 'hostile'; // This works with `electron:serve` but not `electron:build`
let commands = [];

commands.push(nginxPath + ' -t ')
commands.push(nginxRestartCmd)
commands.push(hostilePath + ' add ' + this.hostname)

sudo.exec(commands.join(' && '), { name: 'Devhost manager', icns: 'src/assets/logo.png' },
    function(error, stdout, stderr) {
        // ...
    }
}
```

It all works great on OSX when running in dev mode, but as soon as I build for production the hostile path does not work. Can you offer any advice?
