### ISSUE TITLE
error about builder

### ISSUE THREAD

**Issue by bhabgs** [nklayman/vue-cli-plugin-electron-builder#316]
**Describe the bug**
The packaging failed, but the installation package appeared successfully

**To Reproduce**
yarn electron:builder

**Expected behavior**
I hope there will be no more mistakes

**Screenshots**

![image](https://user-images.githubusercontent.com/19221378/59988865-38cce880-966f-11e9-88a8-a508efde7bb5.png)

**Environment (please complete the following information):**
 - OS and version:
 - node version: 8.13
 - npm version:
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 1.3.4
 - electron version: 5
 - other vue plugins used: ant-design-vue vuex-class
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**

**Comment by nklayman** [comment]
The error says you need to install the `Mac::Memory` module. Unfortunately, I don't know exactly what that means as I don't own a mac. Try with a blank project and see if you still get the error. If you can't figure it out, open an issue on [Electron Builder's Repository](https://github.com/electron-userland/electron-builder), as that is what is throwing the error, not this plugin.

**Comment by bhabgs** [comment]
thank you
