### ISSUE TITLE
Turn dependency peer requirements from error to warning during build

### ISSUE THREAD

**Issue by bdiz** [nklayman/vue-cli-plugin-electron-builder#32]
**Describe the bug**
When a dependency of your project has a peer dependency in their package.json and npm thinks it is not installed vcp-electron-builder errors out on build. 

npm install just prints a warning but still builds fine.

**To Reproduce**
```
vue create my-app
cd my-app
npm install --save-dev vue-cli-plugin-electron-builder@1.0.0-beta.5
vue invoke vue-cli-plugin-electron-builder
npm install --save vuexfire@3.0.0-alpha.5 @firebase/app
npm run build
# npm WARN vuexfire@3.0.0-alpha.5 requires a peer of firebase@>= 4.0.0 but none is installed. You must install peer dependencies yourself.
# build succeeds
npm run build:electron
# Unhandled rejection Error: Unresolved node modules: firebase
# build fails
```

**Expected behavior**
I expect a warning peer dependencies like `npm run build` and the build to succeed. 

**Environment (please complete the following information):**
 - OS and version: Ubuntu 16.10
 - Node version: v10.5.0
 - npm version: 6.1.0
 - yarn version (if used):
 - vue-cli-plugin-electron-builder version : 1.0.0-beta-5
 - vue/cli-service: 3.0.0-rc.3
 - other vue plugins used: none
 - custom config for vcp-electron-builder: none
 - (if possible) link to your repo: not possible

**Additional context**
I install firebase using @firebase/app to save on bundle size when built for web. This is why I get the warning with `npm run build` but my app will still function properly. 

I actually don't use firebase for electron builds and instead use an on disk db which really makes this warning unimportant to me for electron builds.

**Comment by nklayman** [comment]
For some reason, my build works completely fine after following your reproduction instructions. I am on windows though, so that might be why. I am going camping for two weeks starting later today, so I will not be able to help after 1:30ish pacific time. You might have to figure this one out on your own.

**Comment by nklayman** [comment]
I believe this issue was fixed in [electron-builder](https://github.com/electron-userland/electron-builder/issues/611). I will close this issue, if it still fails feel free to re-open it.
