### ISSUE TITLE
Unpacked files are are owned by root

### ISSUE THREAD

**Issue by alex-dow** [nklayman/vue-cli-plugin-electron-builder#321]
**Describe the bug**
My electron app bundles a java service that it tries to start. The service is unpacked into a /tmp folder on linux. This folder and all its contents are owned by root. I am unable to start the service as a result since the user starting the application is not and should not be root.

**To Reproduce**

Simply look at the folder generated in your /tmp folder for the electron application.

**Expected behavior**
Tmp files are owned by the user who runs the application, and not root.

**Environment (please complete the following information):**
 - OS and version: Ubuntu 16 / CentOS 7
 - node version: 10.15.1
 - npm version: 6.4.1
 - yarn version (if used): 1.16.0
 - vue-cli-plugin-electron-builder version : ^1.3.4
 - electron version: ^4.0.0
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 

```
      electronBuilder: {
        builderOptions: {
            appId: "myapp.id",
            productName: "My Product Name",
            copyright: "My Component",
            asar: true,
            asarUnpack: ['java-service'],
            win: {
                target: "portable",
            },
            linux: {
                target: "AppImage",
                maintainer: "My Company",
                vendor: "My Company",
                synopsis: "Description",
                category: "System",
            },
            appImage: {
                artifactName: "app.bin"
            },
            extraResources: [
                'java-service'
            ]
        },
        nodeModulesPath: ['../../node_modules', './node_modules', '../common/node_modules']
    }
```

**Additional context**

I did mention this on electron-builder, was told to upgrade electron-builder: https://github.com/electron-userland/electron-builder/issues/3918#issuecomment-506205812

But doing so breaks everything with our current setup (it's a major upgrade). So I'm hoping there is an alternative work around as I don't want to go manually setup everything that this great plugin is doing.

**Comment by nklayman** [comment]
I really have no idea how to fix this. You could try keeping it packaged and then unpack it manually on app start. I know that files extracted by the app won't be owned by root, as one of my apps has an update service that downloads a zip and executes a file in it. If you use [yarn](https://yarnpkg.com) (which you should), you can add a resolution to your `package.json` file, which will allow you to use the newer version of electron-builder. As soon as the `21.x` release is no longer tagged `pre-release`, I will look into creating a new release of this plugin that uses electron-builder `21.x` by default. The only breaking change is to how AppImages are packaged, so upgrading shouldn't be an issue (It worked with a blank project just fine).

To use the latest electron-builder with [yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/), add this to your `package.json`:

```json
"resolutions": {
    "electron-builder": "^21.0.0"
  },
```
