### ISSUE TITLE
testWithSpectron doesn't resolve with https

### ISSUE THREAD

**Issue by fankohr** [nklayman/vue-cli-plugin-electron-builder#326]
**Describe the bug**
We use https in our project because somes third parto oauth2 enforce it ( Facebook 👎  ). I've digged a little bit inside "testWithSpectron" and identified the issue, the urlMatch regex doesn't handle "https", i guess changing 
`/\$WEBPACK_DEV_SERVER_URL=http:\/\/[^/]+\//` to `/\$WEBPACK_DEV_SERVER_URL=https?:\/\/[^/]+\//` will do the trick

**To Reproduce**

1. Setup https webpack in vue.config.js (https://webpack.js.org/configuration/dev-server/#devserverhttps)
2. Create a simple unit test (see below)
3. It will hand indefinitely because the URL is not matched

**Expected behavior**
https should be handled by testWithSpectron

**Screenshots**
![image](https://user-images.githubusercontent.com/15244542/60592096-286bea80-9da0-11e9-8870-cb0c0b7f41c2.png)
![image](https://user-images.githubusercontent.com/15244542/60592013-fe1a2d00-9d9f-11e9-9f60-2e1584b405ae.png)

**Environment (please complete the following information):**
 - OS and version: Windows 10 Version 10.0.17763 n° 17763
 - node version: 10.16.0 (LTS)
 - npm version: 6.4.1
 - yarn version (if used): 1.16.0
 - vue-cli-plugin-electron-builder version : 1.3.5
 - electron version: 5.0.2
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**
That's one of the most useful github repo i've used so far, you are doing an awesome job 👍

**Comment by nklayman** [comment]
Version `1.3.6` includes the fix.
