### ISSUE TITLE
Env variables not functioning correctly

### ISSUE THREAD

**Issue by doyle-mark** [nklayman/vue-cli-plugin-electron-builder#328]
**Describe the bug**
Attempting to read an environment variable results in `undefined`

**To Reproduce**

1. Define and env variable in .env. Ex. `VUE_APP_BASE_URL = http://yourbaseurl.test/`
2. Attempt to read the variable. Ex. `console.log(process.env.VUE_APP_BASE_URL)`

**Expected behavior**
`http://yourbaseurl.test/` should be written to the JavaScript console.

**Environment:**
 - OS and version: Windows 10 1803 (17134.829)
 - node version: v10.16.0
 - npm version: v10.16.0
 - vue-cli-plugin-electron-builder version : 3.8.4
 - electron version:  5.06
 - (if possible) link to your repo: https://github.com/doyle-mark/aeric

**Comment by nklayman** [comment]
It works fine for me. Try upgrading vue-cli-plugin-electron-builder. If that still fails, try with a blank repository. If that fails, send it to me. The renderer process env variables are handled by vue cli, and the main process env variables are injected as well here: https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/d885477801fda86376167107bda1d68c87a36378/index.js#L544-L550
