### ISSUE TITLE
Ability to set --inspect or --inspect-brk with a port

### ISSUE THREAD

**Issue by TotomInc** [nklayman/vue-cli-plugin-electron-builder#33]
**Is your feature request related to a problem? Please describe.**
I would like to access my main electron process logs from devtools instead of reading them in the terminal.

**Describe the solution you'd like**
This could be done in a NodeJS environment by passing `--inspect=[PORT]` or `--inspect-brk=[PORT]` to the `serve:electron` script. This way, we could use the extension [Node Inspector Manager](https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj) to automatically open/reload our devtools tab.

**Describe alternatives you've considered**
No alternatives considered.

I have no idea if it is possible to implement this in the `vue-cli-plugin-electron-builder` without editing other `vue-cli` specific files.

**Comment by nklayman** [comment]
Note: this assumes you are using v1.0.0 beta of vcp electron builder. If you aren't, I recommend upgrading. If you don't upgrade, only the first method will work.

There are 2 ways you can do this. You can inspect the entire script by running `node [inspect args] node_modules/@vue/cli-service/bin/vue-cli-service.js serve:electron` or, to just inspect the electron launch (main process logs come from here), run `npm run serve:electron --debug`. In this case, electron will not be launched. You can then launch electron yourself with the inspect arguments. Look at the docs for [testing and debugging](https://nklayman.github.io/vue-cli-plugin-electron-builder) for more info.

**Comment by TotomInc** [comment]
Running `node --inspect node_modules/@vue/cli-service/bin/vue-cli-service.js serve:electron` works well, however I can't get the second method to work (I am probably missing something).

When running `yarn serve:electron --debug` I should pass after `electron --inspect ./dist_electron/background.js`? This is what I understand from the [Electron testing docs](https://electronjs.org/docs/tutorial/debugging-main-process#--inspectport), but my Electron app doesn't start.

Sorry if this seems dumb, I picked-up Electron a few days ago and I find it kinda hard to learn it.

**Comment by nklayman** [comment]
Yes, the command you give to electron tells it where the background file is. Try placing the inspect arg after the background file path and see if that works.
