### ISSUE TITLE
session id in server side is different with dev mode.

### ISSUE THREAD

**Issue by uniorder** [nklayman/vue-cli-plugin-electron-builder#330]
In dev mod, I can set vue.config.js like:
`module.exports = {
	devServer: {
		proxy: {
			'/': {
				target: 'http://192.168.218.59/',
				secure: true
			}
		}
	}
}
`
It's running okay, but after built application, every request has different session id.
so anyone help me what can i do?

Thanks.

**Comment by nklayman** [comment]
What do you mean by session ID? What server framework are you using to determine the session ID? I can't debug this if I can't reproduce the issue myself.
