### ISSUE TITLE
How to Resolve Conflicts between x86 and x64 （serialport）

### ISSUE THREAD

**Issue by xixixida** [nklayman/vue-cli-plugin-electron-builder#331]
**Describe the bug**

When using serialport, I want to put it in node_model, but find that when adding externals, serialport is packaged according to the number of system bits. But when I packed it on my computer, I found that only x64 could not be used on x86. What should I do to solve this problem?
```
Externals: ['serialport']
```
![image](http://doubaobit.oss-cn-beijing.aliyuncs.com/text/82BEA22E-DE4A-4153-A849-BC5CF735AC30.png)
**Environment (please complete the following information):**
 - node version: 12.3.1
 - npm version: 6.9.0
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 1.2.0
 - electron version: 5.0.0
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: https://github.com/xixixida/serialportx86-x64

**Additional context**

**Comment by nklayman** [comment]
Electron builder's [install-app-deps function](https://github.com/electron-userland/electron-builder/issues/1906) should build the package for the appropriate architecture and platform you are targeting when building your app. If it is not, you should open an issue on their repo instead. That package handles the entire electron build process.
