### ISSUE TITLE
Question||'build' in the application package.json is not supported since 3.0

### ISSUE THREAD

**Issue by JamesDream87** [nklayman/vue-cli-plugin-electron-builder#332]
'build' in the application package.json is not supported since 3.0 anymore. Please move 'build' into the development package.json.
How can I setting like this:
```
"build": {
    "appId": "test.com",
    "win": {
      "icon": "public/windows.ico"
    }
  }
```

**Comment by nklayman** [comment]
See the [docs on configuring electron builder](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#configuring-electron-builder). Set your `vue.config.js` to this: 
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
        appId: 'test.com',
        win: {
          icon: 'public/windows.ico'
        }
      }
    }
  }
}
```

**Comment by JamesDream87** [comment]
thanks

**Comment by ponahoum** [comment]
Thanks it works !! It is extremely badly documented, have been wandering to change the icon for a while...

**Comment by nklayman** [comment]
@ponahoum See [the icon guide](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#icons).

**Comment by MengLeangg** [comment]
@nklayman  Thank you so much. It's working for me.

**Comment by Motmaimai** [comment]
@nklayman Thank you so much.
