### ISSUE TITLE
How to use app.getAppPath?

### ISSUE THREAD

**Issue by pacific202** [nklayman/vue-cli-plugin-electron-builder#335]
I'm trying to access app.getAppPath() in a component, but nothing I have tried is returning this property.

It would be super if the docs included how to do this.

Here is the snippet of the last thing I tried:

```
const { app } = require('electron');

export default {
  
  name: 'ImportExport',
  
  data: function(){
    return {
      midiAccess: null,
      activePort: null,
      log: [],
      appPath: app.getAppPath()
    }
  },
```

**Comment by nklayman** [comment]
You need to use [Electron Remote](https://electronjs.org/docs/api/remote#accessing-built-in-modules-in-the-main-process):

```js
import { remote } from 'electron'

const { app } = remote

// then just use app.getAppPath()
```

**Comment by pacific202** [comment]
Perfect, thank you.

Would you like me to make a pull request and add this to the docs?

**Comment by nklayman** [comment]
Since this isn't related to this plugin, there is no need to put it in the docs. You should use the official electron docs instead.

**Comment by pacific202** [comment]
Well, thank you for your quick reply.  I greatly appreciate this, and your superb project here too.  Very impressive.

**Comment by ChunAllen** [comment]
I'm getting Uncaught `TypeError: fs.existsSync is not a function` when I'm importing electron
```
import { remote } from 'electron'

const { app } = remote
```
