### ISSUE TITLE
OSX build paths

### ISSUE THREAD

**Issue by gtamas** [nklayman/vue-cli-plugin-electron-builder#336]
I'm trying to create an OSX build. However, once the app is packaged as asar some paths stop working.

Some of the dependencies (like grpc) are trying to read files, but they can't find the files in the asar archive.

Same setup works fine in dev env, this only happens in production.

For example I'm getting this error:

```
Error: ENOENT: no such file or directory, open 'google/protobuf/api.proto'
```

I'm not using protobufs.js directly, it's just a dependency of grpc. So how can fix these paths?

**Comment by zugende** [comment]
hi @gtamas did you find a solution to this problem?
