### ISSUE TITLE
error on assets folder when I build app

### ISSUE THREAD

**Issue by dhall2211** [nklayman/vue-cli-plugin-electron-builder#337]
when I do npm run electron:build. my app builds with no problems but when I log in im getting an error on my asset and a lot of my components are not showing. i have zero issues with npm electron:serve or regular serve.

![electronerr](https://user-images.githubusercontent.com/25202358/61057731-2b955500-a3f6-11e9-8b3d-3cc37051f83f.PNG)

**Comment by nklayman** [comment]
Looks like a duplicate of https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/263. Try the fix posted there.

**Comment by dhall2211** [comment]
yeah that worked thanks!
