### ISSUE TITLE
App fails to build for production

### ISSUE THREAD

**Issue by justintaddei** [nklayman/vue-cli-plugin-electron-builder#339]
This is similar to #261 but I'm not using any SCSS library and my codebase is small still that I know I haven't made any syntax errors.
Everything works as expected when running `npm run electron:serve` but `npm run electron:build` fails with:
`Error: CSS minification error: Expected a pseudo-class or pseudo-element.. File: css/app.5d14f35d.css` at `optimize-cssnano-plugin` 

**To Reproduce**
`npm run electron:build`

**Expected behavior**
For it to build without failing 😂

![image](https://user-images.githubusercontent.com/16705594/61089143-d3635080-a3ff-11e9-8ec5-e929a59185b2.png)
![image](https://user-images.githubusercontent.com/16705594/61089218-04438580-a400-11e9-9f80-a9738a73b77f.png)

**Environment (please complete the following information):**
 - OS and version: Windows 10 build 1903
 - node version: v10.13.0
 - npm version: 6.10.0
 - vue-cli-plugin-electron-builder version : 1.3.5
 - electron version: 5.0.6
 - other vue plugins used:
```json
{
    "@vue/cli-plugin-babel": "^3.8.0",
    "@vue/cli-plugin-typescript": "^3.8.0",
    "@vue/cli-plugin-unit-jest": "^3.8.0",
    "@vue/cli-service": "^3.8.0",
    "@vue/test-utils": "1.0.0-beta.29",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.1.0"
}
```

I would've filed this issue somewhere else except for the fact that it works if development

**Comment by nklayman** [comment]
There error is thrown by the renderer process build, which is handled by vue cli. Can you try a non-electron build? The reason the error is only during build is because optimizations like css minification are disabled in development.

**Comment by justintaddei** [comment]
Thank you for the quick reply, and sorry for my slow reply. The non-electron build is failing with same error.

**Comment by nklayman** [comment]
In that case, open an issue on the vue-cli repository, as they are responsible for the error.

**Comment by justintaddei** [comment]
Will do. Thanks.

**Comment by Nisthar** [comment]
@justintaddei did u find a solution?

**Comment by justintaddei** [comment]
@Nisthar nope. I ended up starting from scratch and just copied over my source files. Whatever it was it was something to with the build process and not my source.
