### ISSUE TITLE
Some modules can't be resolved and successfully imported using TypeScript (can't resolve .ts in modules index)

### ISSUE THREAD

**Issue by TotomInc** [nklayman/vue-cli-plugin-electron-builder#34]
**Describe the bug**
When using [Axios](https://github.com/axios/axios) or [Request](https://github.com/request/request) (or some other modules that doesn't have `.ts` files), it looks like TS (and/or Electron) doesn't want to resolve modules with `.js` files and expect `.ts` file extension.

**To reproduce**
- Generate a project using Vue-CLI (Vue + Typescript), invoke `vue-cli-plugin-electron-builder`.
- `yarn add request` **or** `yarn add axios`.
- Import the module into your `background.ts`:

```
import request from 'request';
// OR
import axios from 'axios';

// try to call the imported module, in this case axios:
console.log(axios);
```

- Run `yarn serve:electron`.
- Errors will pop at `Bundling main process` step.

**Expected behavior**
Should properly import modules.

**Screenshots**
No screenshots so I'm putting logs:

```
./node_modules/axios/index.js

Module not found:
  Error: Can't resolve './lib/axios' in '/Users/totominc/Desktop/Git/poe-mapper-tracker/node_modules/axios'
  resolve './lib/axios' in '/Users/totominc/Desktop/Git/poe-mapper-tracker/node_modules/axios'
  using description file: /Users/totominc/Desktop/Git/poe-mapper-tracker/node_modules/axios/package.json (relative path: .)
  using description file: /Users/totominc/Desktop/Git/poe-mapper-tracker/node_modules/axios/package.json (relative path: ./lib/axios)
  no extension /Users/totominc/Desktop/Git/poe-mapper-tracker/node_modules/axios/lib/axios doesn't exist .ts
  /Users/totominc/Desktop/Git/poe-mapper-tracker/node_modules/axios/lib/axios.ts doesn't exist
  as directory /Users/totominc/Desktop/Git/poe-mapper-tracker/node_modules/axios/lib/axios doesn't exist

[/Users/totominc/Desktop/Git/poe-mapper-tracker/node_modules/axios/lib/axios]
[/Users/totominc/Desktop/Git/poe-mapper-tracker/node_modules/axios/lib/axios.ts]

@ ./node_modules/axios/index.js 1:17-39
@ ./src/background.ts
@ multi ./src/background.ts'
```

**Environment:**
 - OS and version: macOS High Sierra 10.13.5
 - Node version: 8.11.2
 - npm version: 6.1.0
 - yarn version (if used): 1.7.0
 - vue-cli-plugin-electron-builder version: 1.0.0-beta.5
 - other vue plugins used: TypeScript, Vuex
 - custom config for vcp-electron-builder: none
 - link to your repo:
	- [poe-mapper-tracker](https://github.com/TotomInc/poe-mapper-tracker/tree/import-error) (branch `import-error`)
	- [vcp-typescript-error](https://github.com/TotomInc/vcp-typescript-error) created a blank project with vue-cli (TS + VueX + VCP-electron-builder), added axios and tried to use it. No config edited.

**Comment by TotomInc** [comment]
After some research, it looks like the issue come from the webpack configuration. I came across multiple SO/GitHub issues talking about webpack `resolve#extensions`.

[This one for example](https://stackoverflow.com/a/43877900/8073629), which is exactly the same error as I have.

**Comment by daprahamian** [comment]
👍 Would love eyes on this

**Comment by TotomInc** [comment]
@daprahamian so I'm not crazy and this issue doesn't affect only me right? 😄

**Comment by nklayman** [comment]
The issue was that the resolve extensions didn't contain `'.js'`. This is fixed and you can switch back to the beta with version `1.0.0-beta.6` when it comes out.

**Comment by TotomInc** [comment]
Thanks for the fix @nklayman, any ETA for the `1.0.0-beta.6`?

**Comment by nklayman** [comment]
Beta.6 has just been released, you can use that now!

**Comment by TotomInc** [comment]
Works fine, it can now resolve `.js` index files from `node_modules`.

**Comment by beeing** [comment]
Hi, I'm experiencing similar issue but for .json file which from a npm module called `spinnies`. Is there any workaround for this? 

Thanks in advance.

**Comment by nklayman** [comment]
@beeing Try this:
```
// vue.config.js on the root of the project
module.exports = {
  chainWebpack: config => {
    config.resolve.extensions.add('.json')
  }
}
```
