### ISSUE TITLE
vue.config.js asarUnpack doesn't work

### ISSUE THREAD

**Issue by HarlanGitHub** [nklayman/vue-cli-plugin-electron-builder#353]
**Describe the bug**
I have a plug-in folder. I want to pack it and put it in the app. asar. unpacked folder.I set the following in vue. config.js.  When I build it  and found it doesn't work. 

`module.exports = {
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
          "appId": "xx",
          "productName": "xx",
          "copyright":"xx",
          "win": {  
              "icon": "res/logo.ico"
           },        
           "publish": [
            {
              "provider": "generic",
              "url": "http://xxx/version/",
            }
          ],
          "asar":true,
          "asarUnpack":[
           "plugins"
         ]         
      }
    }
  },
 pages: {
    index: 'src/main.js',
    main: 'src/views/Main/main.js',
    setting: 'src/views/Setting/main.js',
  }
}`

**To Reproduce**

**Expected behavior**
I want build it and  lets plug-in files be placed in the app.asar.unpacked folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/17823186/61192823-dacd7700-a6e9-11e9-9c8e-9beecffce8b6.png)

**Environment (please complete the following information):**
 - OS and version: windows10
 - node version: 10.15.3
 - npm version: 6.4.1
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : latest
 - electron version: 5.0.6
 - other vue plugins used: vuetify, vue-router, vuex, vuetify-loader, vue-template-compiler
 - custom config for vcp-electron-builder: none
 - (if possible) link to your repo: 

**Additional context**

**Comment by nklayman** [comment]
From the electron builder documentation:
>  If you need to use some files, e.g. as tray icon, please include required files explicitly: "files": ["**/*", "build/icon.*"]

Folders in your project won't be included in the built app unless listed here. List you plugins folder here as well, and it should work.

**Comment by HarlanGitHub** [comment]
Thanks,  I have solved it in the following ways:

**Comment by HarlanGitHub** [comment]
Thanks, I have solved it in the following ways: 
"extraFiles":{
          "from":"plugins",
          "to":"./resources/app.asar.unpacked/plugins/" 
        }

**Comment by nklayman** [comment]
Closing as you found a solution.

**Comment by mxswat** [comment]
> Thanks, I have solved it in the following ways:
> "extraFiles":{
> "from":"plugins",
> "to":"./resources/app.asar.unpacked/plugins/"
> }
@HarlanGitHub 

Your answer saved my day thanks!
