### ISSUE TITLE
How to set custom app name

### ISSUE THREAD

**Issue by wakamin** [nklayman/vue-cli-plugin-electron-builder#369]
It seems the app name in the windows desktop was taken from the name of the package.json file. I'd like to change the app name to "App Name", by doing that, the package.json file will be invalid.

How to set the custom app name?

**Comment by nklayman** [comment]
Set your [vue.config.js](https://cli.vuejs.org/config/#vue-config-js) to:

```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
        productName: 'App Name'
      }
    }
  }
}
```

**Comment by janosvajda** [comment]
> Set your [vue.config.js](https://cli.vuejs.org/config/#vue-config-js) to:
> 
> ```js
> module.exports = {
>   pluginOptions: {
>     electronBuilder: {
>       builderOptions: {
>         productName: 'App Name'
>       }
>     }
>   }
> }
> ```

This does not work, unfortunately. All dialogue boxes' titles and notifications titles still come from the package.json and this setting does not replace it. I use vue-cli-plugin's 2.0.0-rc.6.

**Comment by SuperKirik** [comment]
As I understood, the solution can be found here:
https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1125
