### ISSUE TITLE
require.resolve doesn't seem to work in prod

### ISSUE THREAD

**Issue by gtamas** [nklayman/vue-cli-plugin-electron-builder#375]
The require.resolve() function returns nothing in prod builds.

OS and version: MacOS Mojave
node version: 10.16
npm version: 6.x
yarn version (if used): 1.16x
vue-cli-plugin-electron-builder version :
electron version: 5.0.6
other vue plugins used:

I have node_modules in the app.asar file. There are many modules installed. However, if I add require.resolve('somemodule'), it just returns an empty string.

This happens only in prod, dev works fine.

Could this be caused by webpack?

I have mininal extra config for electron builder

```
 electronBuilder: {
            builderOptions: {
                win: {
                    icon: './public/win/etcd_logo.png.ico',
                },
                mac: {
                    icon: './public/mac/etcd_logo.png.icns',
                },
                files: [
                    '**/*',
                    {
                        from:
                            '../../node_modules',
                        to: 'node_modules',
                    }
                ],
            },
        },
```

Please help!

P.S.: Require.resolve() looks up the modules in the app.asar node_modules directory, right? I also have an empty node_modules directory in the electron_dist/bundled folder. That's created by webpack and I guess the app doesn't use it.

**Comment by gtamas** [comment]
Hello? Anyone?

Can you please tell me if require.resove() is replaced by webapck's version in prod builds?
It looks like the dev build (electron:serve) uses the node version, which returns the expected results, but the prod build seems to use a mocked function? It returns nothing, no matter which module's location I'm trying to resolve.

Please help!

**Comment by gtamas** [comment]
Anybody else having problems with require.resolve()???

**Comment by nklayman** [comment]
Make sure you [mark native modules as externals](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules). Otherwise, they will not be copied into your built app and you will not be able to `require` them. Since webpack bundles other modules into you app, there is no need to copy the `node_modules` folder, as it will just increase your app's size.
