### ISSUE TITLE
Issues after Upgrading to 1.0.0 beta with SQLite 3

### ISSUE THREAD

**Issue by dylrich** [nklayman/vue-cli-plugin-electron-builder#38]
Hi there, I am having issues after upgrading to the 1.0.0 beta when requiring the SQLite3 module. The version of my app running the 0.3.2 version of this plugin does not have this issue, and my app does run under the new version when I remove sqlite3 from the project. While bundling my main process (where SQLite3 is being run), I get an extremely long, unformatted error stack trace with errors like this:

Error: Can't resolve 'aws-sdk' in '/home/dylrich/dev/project/node_modules/node-pre-gyp/lib'. 

Clearly there is some sort of issue happening with the interaction between this plugin, webpack, node-pre-gyp and sqlite3. No matter what I try I cannot get the package to bundle if SQLite3 is loaded anywhere. If anyone has some hints on how to sort this out so that I can use the updated 1.0.0 plugin that would be fantastic.

**Comment by dylrich** [comment]
Adding require("aws-sdk/dist/aws-sdk"); before importing SQLite 3 fixes this for me, although WebPack is still complaining and I imagine I would need to put something in vue.config.js to get it to shut up. This is obviously not an ideal solution, but any thoughts on fixing this weird issue would be wonderful

**Comment by dylrich** [comment]
One more update: After moving the import from a forked process into my main process, I can no longer launch my app. I've described the error in detail here: https://stackoverflow.com/questions/51466585/webpack-fails-to-compile-vue-electron-project-with-sqlite3

**Comment by nklayman** [comment]
This issue appears to be unrelated to my plugin, so I will close it (but continue to help you if I can). I found a [question thread](https://stackoverflow.com/questions/32504307/how-to-use-sqlite3-module-with-electron) that has some information that may be useful to you. Also, check out [electron native modules documentation](https://electronjs.org/docs/tutorial/using-native-node-modules). An alternative would be to use [sql.js](https://github.com/kripken/sql.js/), which does not use native modules. I tried this and it worked fine.

**Comment by nklayman** [comment]
It's a little late, but I have a fix for you. Set `vue.config.js` to:
```javascript
module.exports = {
    pluginOptions: {
        electronBuilder: {
            chainWebpackRendererProcess: config => {
                config.module
                    .rule('node-loader')
                    .test(/\.node$/)
                    .use('node')
                    .loader('node-loader')
                config.resolve.alias.set(
                    'sqlite3',
                    'sqlite3/lib/binding/electron-v2.0-linux-x64/node_sqlite3.node'
                )
                return config
            }
        }
    }
}
```
and install `node-loader`

**Comment by nklayman** [comment]
1.0.0-rc.1 has landed with support for native modules. Upgrade to the latest version of vcp-electron-builder, and re-invoke the generator. Then, sqlite3 should work fine. The generator will not effect any code other than adding the missing requirements for native modules. You can also remove the config I suggested above.
