### ISSUE TITLE
Missing latest-[platform].yaml

### ISSUE THREAD

**Issue by elmasry** [nklayman/vue-cli-plugin-electron-builder#381]
**Describe the bug**
I'm trying to configure auto updater using Hazel update server, however, when I build the app it doesn't generate a latest-[platform].yaml file that Hazel and other update servers use to determine the download/update files for each platform.

**To Reproduce**
yarn electron:build

**Expected behavior**
a generated latest-[platform].yaml file

**Environment (please complete the following information):**
 - OS and version: macos mojave 10.14.5
 - node version: 12.6.0
 - npm version: 6.9.0
 - yarn version (if used): 1.17.3
 - vue-cli-plugin-electron-builder version : 1.3.6
 - electron version: 4.0.0

**Comment by elmasry** [comment]
I finally figured it out, I had to add publish config to vue.config.js
```
publish: [
	{
		provider: "generic",
		url: "http://127.0.0.1:8000/",
		channel: "latest"
	}
]
```

There is no documentation for that thought, you may need to add it

**Comment by dlt1111** [comment]
> I finally figured it out, I had to add publish config to vue.config.js
> 
> ```
> publish: [
> 	{
> 		provider: "github",
> 	}
> ]
> ```
> 
> There is no documentation for that thought, you may need to add it

I can't generate a latest-[platform].yaml whatever I do. Could you plz show me ur vue.config.js.

**Comment by nklayman** [comment]
@dlt1111 Make sure you are running the app after installing it, it must be installed for auto-update to work.
