### ISSUE TITLE
Call a vuex store mutation from the background.js file via a accelerator keyboard shortcut?

### ISSUE THREAD

**Issue by MrHarrisOnline** [nklayman/vue-cli-plugin-electron-builder#382]
Is there a way to use mapMutations or anyway to affect the vuex store from background.js via a accelerator keyboard shortcut? I think the title says it all.

I was thinking to use a keyboard shortcut solution from the vue end of things but then I stopped.

I am very new to Vue, well I actually used it a bunch then stopped for five months.
This may to an obvious question. I have tried to look up a solution.

Thank you.

**Comment by rjoo** [comment]
I would maybe bind [local shortcuts](https://electronjs.org/docs/tutorial/keyboard-shortcuts#local-shortcuts) and [send events via webcontents](https://electronjs.org/docs/api/web-contents#contentssendchannel-arg1-arg2-) to the renderer (Vue app). The Vue app then listens in with `ipcRenderer` and mutates the store accordingly.

**Comment by nklayman** [comment]
@MrHarrisOnline follow @rjoo's instructions. The only difference is you should use `import` statements instead of `require`.

**Comment by RodrigoLeiteF** [comment]
[This extension](https://github.com/vue-electron/vuex-electron) allows accessing the store directly from electron. Is it possible to add compatibility to it? In the case of a front-end that is supposed to work on the web as well, it would be nice to not have to shove electron logic in the components.

**Comment by nklayman** [comment]
You should be able to use that plugin as if you were in a regular electron app. Just follow its install instructions.
