### ISSUE TITLE
Memory leak when reload

### ISSUE THREAD

**Issue by NateScarlet** [nklayman/vue-cli-plugin-electron-builder#384]
**Describe the bug**
Memory usage increase after auto reload that triggered by watched file change.

**To Reproduce**

1. `git clone -b vue-cli-plugin-electron-builder-1 https://github.com/NateScarlet/issue-repro.git`
2. `cd issue-repro`
3. `npm run electron:serve`
4. repeatly save src/background.ts
5. see memory usage increase

**Expected behavior**

Memory usage not keep increase.

**Screenshots**

![2019-07-29_10-46-06](https://user-images.githubusercontent.com/21083014/62019052-c2805080-b1ef-11e9-92b9-b275742b7b08.gif)

**Environment (please complete the following information):**
 - OS and version: Windows 7 (7601)
 - node version:  v10.16.0
 - npm version: 6.9.0
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 1.3.6
 - electron version: 5.0.8
 - other vue plugins used: typescript babel unit-mocha
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: https://github.com/NateScarlet/issue-repro/tree/vue-cli-plugin-electron-builder-1

**Additional context**

In my application, every reload increase 400MB memory usage, cause crash after few reload.

**Comment by Goran-n** [comment]
Same issue here, started occurring randomly. +1

**Comment by nklayman** [comment]
@NateScarlet can you try to reproduce with the [v2.0 beta](https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-beta.0) and electron 7?
