### ISSUE TITLE
auot reload does not occur when other imported files are changed

### ISSUE THREAD

**Issue by king-alpha** [nklayman/vue-cli-plugin-electron-builder#385]
**Is your feature request related to a problem? Please describe.**
It's really frustrating when you split your background.js code into multiple files because a change in any of those files does not cause auto-reload to execute.
**Describe the solution you'd like**
an example is, you decide to just do `console.log('test')` in a src/background2.js and then require background2.js in background.js and then make a change to the code in background2.js, the expected behaviour is for auto-reload to kick in but it does not.
**Describe alternatives you've considered**
at least code splitting is something we do occasionally when our files start growing so it should be a normal behaviour for auto-reload to support this.

**Additional context**

**Comment by rjoo** [comment]
Although I get the expectation with watching imported files, there is a `mainProcessWatch` config setting that will recompile the main process on changes.

````
// vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      mainProcessWatch: ['src/background2.js']
    }
  }
}
````

**Comment by king-alpha** [comment]
Works just fine as u described. Many thanks
