### ISSUE TITLE
Vuetify 2.0.2 upgrade hanging on electron launch

### ISSUE THREAD

**Issue by Aegis18** [nklayman/vue-cli-plugin-electron-builder#388]
**Describe the bug**
I am trying to upgrade from vuetify 1.5.5 to vuetify 2.0.2 (using `yarn remove vuetify` then `yarn add vuetify`) once doing so I try to do `yarn electron:serve` and the compilation finishes but the application does not get created. It just freezes. (I am using vue-cli 3.7.0) 

**Expected behavior**
My electron application to appear once the compilation has been completed

**Screenshots**
![image](https://user-images.githubusercontent.com/27922019/62163242-f8086500-b2e7-11e9-959a-5e92950542e7.png)
it just "freezes" after 'Time' 

**Environment (please complete the following information):**
 - OS and version: Windows 10
 - node version: 10.15.3
 - npm version: 6.4.1
 - yarn version (if used):  1.15.2
 - vue-cli-plugin-electron-builder version : 1.3.0 (Whatever comes with vue add electron-builder)
 - electron version: 6.0.0
 - other vue plugins used: N/A 
 - custom config for vcp-electron-builder:  
 - (if possible) link to your repo: 

**Additional context**

**Comment by rjoo** [comment]
I have no problem running Vuetify 2.0.2. Have you tried fixing all compile errors first?

**Comment by Aegis18** [comment]
> I have no problem running Vuetify 2.0.2. Have you tried fixing all compile errors first?

Thanks for getting back to me, but I don't think this is the issue. As you can see even thought it says `ERROR` it just means says there is an implicit type of any. Also When I am running Vuetify 1.5.5 the compiler error still exists but electron can launch

**Comment by rjoo** [comment]
Ah. Could this be your issue? https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/390

**Comment by nklayman** [comment]
@Aegis18 Can you try running the regular `yarn serve` command? If that fails as well, that means the issue is with your app, not this plugin. It appears that the issue is caused by an error with your app, not the plugin.

**Comment by Aegis18** [comment]
> @Aegis18 Can you try running the regular `yarn serve` command? If that fails as well, that means the issue is with your app, not this plugin. It appears that the issue is caused by an error with your app, not the plugin.

Sorry for the long delay of the reply. I was not able to work on this for a few days. I am getting the freeze with `yarn serve` as well. this only happens when I update `vuetify`

**Comment by nklayman** [comment]
If the freeze occurs with yarn serve, then the issue is unrelated to this plugin. Please open an issue on https://github.com/vuetifyjs/vue-cli-plugin-vuetify instead.

**Comment by Aegis18** [comment]
> > @Aegis18 Can you try running the regular `yarn serve` command? If that fails as well, that means the issue is with your app, not this plugin. It appears that the issue is caused by an error with your app, not the plugin.
> 
> Sorry for the long delay of the reply. I was not able to work on this for a few days. I am getting the freeze with `yarn serve` as well. this only happens when I update `vuetify`

Sorry another thing. I just made a new project using webstorm and did it still doesn't work, but I have confirmed that `npm serve` works on this new project
