### ISSUE TITLE
Adding vue destroy callback on electron window close

### ISSUE THREAD

**Issue by theo-walton** [nklayman/vue-cli-plugin-electron-builder#389]
_pre note: I am using typescript_

I want to destroy the vue app when the window closes (so that all my cleanup can be done at the component level by being a callback to `beforeDestroy`. Currently all the electron callbacks are done in the autogenerated `background.ts` which does not have access to the vue app. How can I reference my vue app inside an electron callback?

I have tried importing the vue app from `main.ts` but as soon as I use the imported variable my electron app does't load and gives this error: 

```
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type,
currently no loaders are configuredto process this file.
See https://webpack.js.org/concepts#loaders
```

**Comment by theo-walton** [comment]
I also just tried exporting the app from `background.ts` and using it in `main.ts` but I then get the error:

`Uncaught TypeError: Cannot read property 'registerSchemesAsPrivileged' of undefined`


**background.ts:**
```typescript
'use strict'

import { app, protocol, BrowserWindow } from 'electron'

...

// Scheme must be registered before the app is ready
protocol.registerSchemesAsPrivileged([{scheme: 'app', privileges: { secure: true, standard: true } }])

...

export default app
```

**main.ts:**
```typescript
'use strict'

import Vue from 'vue'
import App from './App.vue'
import store from './store'
import app from "./background"

Vue.config.productionTip = false

let vueApp = new Vue({
  store,
  render: h => h(App),
  methods: {
    destroy() {
      this.$destroy();
    }
  }
}).$mount('#app')

app.on('window-all-closed', () => {
  vueApp.destroy();
  app.quit()
})
```

**Comment by rjoo** [comment]
`app.quit()` executes the window's `beforeunload` and `unload` events. You could try binding a listener on that.

````
window.addEventListener('beforeunload', () => vueApp.$destroy())
````

**Comment by nklayman** [comment]
@theo-walton the solution @rjoo should work. Please try that and close this issue if it works.
