### ISSUE TITLE
Built app doesn't launch with Electron 6.0.0 due to outdated electron-builder

### ISSUE THREAD

**Issue by caesar** [nklayman/vue-cli-plugin-electron-builder#390]
**Describe the bug**
Electron 6.0.0. has three new Helper apps which must be included in the build.
The version of `electron-builder` used by this module doesn't handle this.
A new version `21.2.0` was just released which correctly copies the new helpers.

**To Reproduce**
1. Set up a `vue-cli-plugin-electron-builder` with Electron 6.0.0.
2. Build.
3. Try launching the app.

**Expected behavior**
`vue-cli-plugin-electron-builder` should work with Electron 6.0.0

**Environment (please complete the following information):**
 - OS and version: macOS (any)
 - node version: any
 - npm version: any
 - yarn version (if used): any
 - vue-cli-plugin-electron-builder version : 1.3.6
 - electron version: 6.0.0

**Additional context**
- https://github.com/electron-userland/electron-builder/issues/4104
- https://github.com/electron/electron/issues/19511

**Comment by nklayman** [comment]
Fixed in `v1.4.0` by upgrading electron-builder version.
