### ISSUE TITLE
native module issues

### ISSUE THREAD

**Issue by aispark** [nklayman/vue-cli-plugin-electron-builder#396]
**Describe the bug**
electron-edge-js not found module

**To Reproduce**
$ vue create my-app
$ vue add electron-builder
$ yarn add electron-edge-js
$ yarn electron:serve

![20190805_212232](https://user-images.githubusercontent.com/5924872/62464570-e6cbc680-b7c7-11e9-84e1-4539df4b7086.png)

add configuration

![20190805_213933](https://user-images.githubusercontent.com/5924872/62465339-99505900-b7c9-11e9-80cf-c16f746ac973.png)

$ yarn electron:serve
![20190805_213836](https://user-images.githubusercontent.com/5924872/62465680-74101a80-b7ca-11e9-9165-af15c70dae83.png)

**Environment (please complete the following information):**
 - OS and version: windows10
 - node version:  v10.16.1
 - npm version: 6.9.0
 - yarn version (if used): 1.17.3
 - vue-cli-plugin-electron-builder version : 1.4.0
 - electron version: 5.0.0

 - (if possible) link to your repo: https://github.com/aispark/vuecli-electron-test

**Comment by nklayman** [comment]
Try removing the `asarUnpack` config option. Electron Builder will automatically keep executable files outside of the asar. Also, try deleting your `node_modules` folder and reinstalling deps. The issue isn't requiring the module itself, it's requiring the native part of the module.

**Comment by aispark** [comment]
Great, thank you very much!
