### ISSUE TITLE
assets not working

### ISSUE THREAD

**Issue by indus** [nklayman/vue-cli-plugin-electron-builder#4]
I can't get a path to the logo in the assets folder of the default project.

**Comment by nklayman** [comment]
I think the issue is that whenever a plugin's generator is invoked (`vue add my-plugin`), Vue cli corrupts the logo and favicon. If you reset the logo to before you added electron-builder (or any other plugin) it should work fine. Please confirm so I can close this issue. 

Thanks.

**Comment by indus** [comment]
You are right. I'm not sure what happend but after restating the with "npm run serve" it now works.

**Comment by iamazik** [comment]
@nklayman @indus I am able to reproduce the issue. When adding `vue add router` and build the package, assets are not loading open running the app. However, when going to a different route and get back to the home, assets then load fine as expected. For your convenience, I have added a gif [here](https://cl.ly/df730a3102be).

**Comment by nklayman** [comment]
@iamazik this is probably because you are using history mode, which has issues with electron. Remove the `mode` key from your router configuration to fix it.

**Comment by iamazik** [comment]
Right, that fixed it 👍
