### ISSUE TITLE
Problem with using dugite

### ISSUE THREAD

**Issue by patrickalima98** [nklayman/vue-cli-plugin-electron-builder#40]
**Describe the bug**
Currently I'm having problems using the Problem with using dugite module, I'm trying to use a simple function to get the status of a directory, but when importing the module and calling the function it says it can not find the executable, see the image below :

**To Reproduce**

1. create a new project whith vue-cli-plugin-electron-builder
2. install dugite module: `npm i dugite --save`
3. clone any repository with git
4. update your App.vue for this:

```
<template>
  <div id="app">
  </div>
</template>

<script>
  import { GitProcess } from 'dugite'
  export default {
    mounted () {
      let path = 'path for your cloned repositorie in step 3'
      GitProcess.exec(['status', '-s'], path)
        .then((result) => {
          console.log(result)
        })
    }
  }
</script>
```
5. Run!

**Expected behavior**
It should display a list of files or some git executable message

**Screenshots**
![captura de tela 38](https://user-images.githubusercontent.com/17622137/43687407-0765ff2e-98ab-11e8-9f10-fcdf31ed67c4.png)

**Environment (please complete the following information):**
 - OS and version: Windows 10 x64 1803
 - Node version: 8.11.1
 - npm version: 5.6.0
 - vue-cli-plugin-electron-builder version : 1.0.0-beta.6
 - other vue plugins used: Vuex

**Additional context**
My package.json

```
{
  "name": "gitlab-discovery",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "build:electron": "vue-cli-service build:electron",
    "serve:electron": "vue-cli-service serve:electron"
  },
  "dependencies": {
    "dugite": "^1.69.0",
    "gitlab": "^3.7.0",
    "moment": "^2.22.2",
    "vue": "^2.5.16",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.0-rc.10",
    "@vue/cli-plugin-eslint": "^3.0.0-rc.10",
    "@vue/cli-service": "^3.0.0-rc.10",
    "css-loader": "^1.0.0",
    "electron": "^2.0.2",
    "eslint-config-standard": "^11.0.0",
    "eslint-friendly-formatter": "^4.0.1",
    "eslint-loader": "^2.1.0",
    "eslint-plugin-html": "^4.0.5",
    "eslint-plugin-import": "^2.13.0",
    "eslint-plugin-node": "^7.0.1",
    "eslint-plugin-promise": "^3.8.0",
    "eslint-plugin-standard": "^3.1.0",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.1.0",
    "vue-cli-plugin-electron-builder": "^1.0.0-beta.6",
    "vue-template-compiler": "^2.5.16"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ],
  "main": "dist_electron/bundled/background.js"
}
```
I thank you all from now on!

**Comment by nklayman** [comment]
set your `vue.config.js` to look like this:
```javascript
const EnvironmentPlugin = require('webpack').EnvironmentPlugin

module.exports = {
  pluginOptions: {
    electronBuilder: {
      chainWebpackRendererProcess: config => {
        config.plugin('env').use(EnvironmentPlugin, [
          {
            LOCAL_GIT_DIRECTORY: 'node_modules/dugite/git'
          }
        ])
        return config
      }
    }
  }
}

```

The issue is that dugite expects git to be in a certain path relative to `__dirname`. This path is incorrect, but it can be overwritten by the `LOCAL_GIT_DIRECTORY` env variable. The code above sets this to `node_modules/dugite/git` in electron builds. Note that for some reason, changing this code after running it has no effect (some weird caching problem I think).
