### ISSUE TITLE
Cannot find module 'mongoose' when building for production

### ISSUE THREAD

**Issue by samuelcseto** [nklayman/vue-cli-plugin-electron-builder#404]
**Describe the bug**
When the app runs in development mode (webpack server) everything works correctly. Once I build for production the build succeeds but upon launch of the app an error appears in the chrome devtools console
`Uncaught Error: Cannot find module 'mongoose'`

**Expected behavior**
`mongoose` is included in the package.json as a dependecy so it should get bundled with the others libraries when building for production

**Screenshots**
![Image of Error](https://i.imgur.com/SuE3YPZ.png)

**Environment (please complete the following information):**
 - OS and version: Windows 10 Home build 1903
 - node version: v10.1.0
 - npm version: -
 - yarn version (if used): 1.17.3
 - vue-cli-plugin-electron-builder version : 1.3.6
 - electron version: 5.0.0
 - other vue plugins used: _**see dependencies**_
 - custom config for vcp-electron-builder: -
 - (if possible) link to your repo: 

**Dependencies**
```json
"dependencies": {
    "@jaames/iro": "^4.5.1",
    "@mdi/font": "^3.8.95",
    "@vue/eslint-config-prettier": "^5.0.0",
    "animate.css": "^3.7.2",
    "electron": "^5.0.0",
    "interactjs": "^1.5.4",
    "izitoast": "^1.4.0",
    "lodash-es": "^4.17.15",
    "moment": "^2.24.0",
    "mongoose": "^5.6.8",
    "node-thermal-printer": "^4.1.0",
    "printer": "github:DatabaseWorks/node-printer",
    "simplebar-vue": "^1.1.0",
    "tailwindcss": "^1.0.5",
    "vue": "^2.6.10",
    "vue-router": "^3.0.3",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-eslint": "^3.9.0",
    "@vue/cli-service": "^3.9.0",
    "@vue/eslint-config-standard": "^4.0.0",
    "babel-eslint": "^10.0.1",
    "electron-rebuild": "^1.8.5",
    "eslint": "^5.16.0",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-vue": "^5.0.0",
    "lint-staged": "^8.1.5",
    "sass": "^1.18.0",
    "sass-loader": "^7.1.0",
    "vue-cli-plugin-electron-builder": "^1.3.6",
    "vue-template-compiler": "^2.6.10"
  },
```

**Comment by nklayman** [comment]
Since webpack bundles most deps into your app, they are not copied into your built app by default. You must mark them as [external](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules) for them to be copied.

**Comment by samuelcseto** [comment]
Thanks so much, I didn't catch that in the documentation. For future reference, adding the code bellow to `vue.config.js` fixed the issue.
```js
pluginOptions: {
	electronBuilder: {
		externals: ['mongoose']
	}
}
```
