### ISSUE TITLE
[Question] Notifications only work in development

### ISSUE THREAD

**Issue by tzaitoun** [nklayman/vue-cli-plugin-electron-builder#411]
I am using the Notifications API (https://electronjs.org/docs/tutorial/notifications) in the renderer process. The notifications show when I am in development mode but not when I build the application (I am on Windows 10). I am using app.setAppUserModelId(id) as in the tutorial and made sure my app is pinned in start. Is there a configuration that I am missing for electron-builder? Thanks.

**Comment by nklayman** [comment]
Are you launching via the `exe` in the `win-unpacked` folder, or are you installing it first and then launching the installed app. I think the app has to be installed for notifications to work.

**Comment by tzaitoun** [comment]
I added builderOptions in vue.config.js with appId being the same one I used in setAppUserModelId. With that change, it seems to work now, I'm can't remember if that was the only change I made. It could have been what you said too. Thanks.
