### ISSUE TITLE
'@' alias to 'src/' dir

### ISSUE THREAD

**Issue by Neko911** [nklayman/vue-cli-plugin-electron-builder#415]
vue-cli has automatically added '@' alias to 'src/' project directory, but it not working in background.js file. Looks like vue-electron-builder not using tsconfig.json and babel.config.js in the root of my project. I don`t know is it a bug, or not, but this function is critical for me.

P.s. tested with disabled TS too.

**Comment by nklayman** [comment]
This isn't included by default on the main process. To add it manually, add this to your `vue.config.js`:

```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      chainWebpackMainProcess: config => {
        config.resolve.alias.set('@', path.join(__dirname, 'src'))
      }
    }
  }
}
```
