### ISSUE TITLE
js-ipfs issues

### ISSUE THREAD

**Issue by pruflyos** [nklayman/vue-cli-plugin-electron-builder#416]
[js-ipfs](https://github.com/ipfs/js-ipfs) runs fine in plain vanilla electron (^6.0.0) (see this example: [js-ipfs/examples/run-in-electron](https://github.com/ipfs/js-ipfs/tree/master/examples/run-in-electron))

However, when applied to a simple vue-cli 3 project with vue-cli-plugin-electron-builder exceptions are thrown.

I'm trying to figure out for days now what's the **difference between** `vanilla electron` and `vue-cli-plugin-electron-builder` that causes these issues. Any hints are very appreciated.

Steps to reproduce:

1. `vue create ipfstest`. Choose` default (babel,eslint)` and `yarn`.
2. `cd ipfstest`
3. `vue add electron-builder`. Choose `^6.0.0`.
4. `yarn add ipfs`
5. Add the following lines to `src/background.js`:
```Diff
diff --git a/src/background.js b/src/background.js
index a858cb2..ff3551d 100644
--- a/src/background.js
+++ b/src/background.js
@@ -1,6 +1,7 @@
 'use strict'
 
 import { app, protocol, BrowserWindow } from 'electron'
+import IPFS from "ipfs"
 import {
   createProtocol,
   installVueDevtools
@@ -71,6 +72,17 @@ app.on('ready', async () => {
 
   }
   createWindow()
+
+  try {
+    console.log(`Spawning IPFS node...`)
+
+    const node = await IPFS.create()
+    const id = await node.id()
+
+    console.log(`IPFS Node ID: ${id}`)
+  } catch (err) {
+    console.error(err)
+  }
 })
```
6. `yarn run electron:serve`

This will result in a popup window with the following error:

**A JavaScript error occurred in the main process**
```
uncaught Exception:
TypeError: __get is not a function
at buildConfig (webpack:///./node_modules/ipfs-repo/src/index.js?:
376:59)
at eval (webpack:///./node_modules/ipfs-repo/src/index.js?:73:31)
at eval (webpack:///./node_modules/async/internal/parallel.js?:31:39)
at replenish (webpack:///./node_modules/async/internal/
eachOfLimit.js?:66:17)
at iterateeCallback (webpack:///./node_modules/async/internal/
eachOfLimit.js?:50:17)
at eval (webpack:///./node_modules/async/internal/onlyOnce.js?:
12:16)
at eval (webpack:///./node_modules/async/internal/parallel.js?:36:13)
at eval (webpack:///./node_modules/ipfs-repo/src/index.js?:345:5)
at Immediate.eval (webpack:///./node_modules/async/internal/
setlmmediate.js?:27:16)
at processlmmediate (internal/timers.js:439:21)
```

**Comment by nklayman** [comment]
Try marking `js-ipfs` as an external by setting your `vue.config.js` to:

```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['js-ipfs']
    }
  }
}
```

**Comment by pruflyos** [comment]
Thanks, this does the trick. At least it works for development mode now: `yarn run electron:serve`

```javascript
// vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['ipfs']
    }
  }
}
```

However, `ipfs` then doesn't seem to get packaged into the final **AppImage** when running `yarn run electron:build`. Is there any guide/tutorial how to combine `vue-cli-plugin-electron-builder` with [electron-rebuild](https://github.com/electron/electron-rebuild) for example?

The idea is that the user shouldn't have to install anything in addition and only need to run the downloaded executable.

**Comment by nklayman** [comment]
It should be inside the `dist_electron/linux-unpacked/resources/app.asar/node_modules` folder. Electron Builder (what packages the app into exe and other installers) automatically builds native modules for the necessary platform and includes them in the `app.asar`. Run `yarn global add asar` and then `asar extract dist_electron/linux-unpacked/resources/app.asar ./asar-unpacked`. Check the `asar-unpacked/node_modules` folder for `ipfs`.
