### ISSUE TITLE
Provide more details for Spectron testing

### ISSUE THREAD

**Issue by ezpzlmnsqz1337** [nklayman/vue-cli-plugin-electron-builder#418]
**Is your feature request related to a problem? Please describe.**
Today I spent whole day trying to run the simplest Spectron test. The documentation in this area in this plugin is really brief, even missing a simple working example with specifications of what needs or not need to be installed. It was already mentioned in this issue #136 , where I was finally able to find something, that was usable, even though I had to dramatically (double) increase the timeout, but I guess this is due to the size of my application.

**Describe the solution you'd like**
- [ ] Add the working example from the issue referenced above to the docs.
- [ ] Specify what the user needs to have installed to run the example (`@vue/cli-plugin-unit-jest` for example, or that he does not need to install `spectron`, `chromedriver `etc.), I tried so many things, that at this point I am not sure if I really needed anything besides this plugin or not.

**Additional context**
It could save someone a lot of bad time and provide a starting point for e2e testing, with just a little modification to the plugin web page, with content already available in the above mentioned issue.

Besides that, I really like this plugin, thanks a lot!

**Comment by nklayman** [comment]
I added a link to the complete examples for jest and mocha. These should have been automatically added when you installed the plugin if the jest or mocha plugins were installed first. The example in the docs was missing the `jest.setTimeout` call, which I added as well.
