### ISSUE TITLE
build problem with mode

### ISSUE THREAD

**Issue by MrZhangbing** [nklayman/vue-cli-plugin-electron-builder#423]
**Describe the bug**
When I created the electron app, I added the environment variable package
Ps: in package.json scripts:{
"electron:build": "vue-cli-service electron:build --mode test",
}, and add the .env.test file in the root directory
Packing error:
(node:18936) UnhandledPromiseRejectionWarning: WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.mode should be one of these:
   "development" | "production" | "none"
   -> Enable production optimizations or development hints.
    at webpack (/Users/01380979/Desktop/test/ele-demo/node_modules/webpack/lib/webpack.js:31:9)
    at bundleMain (/Users/01380979/Desktop/test/ele-demo/node_modules/vue-cli-plugin-electron-builder/index.js:588:10)
    at Promise (/Users/01380979/Desktop/test/ele-demo/node_modules/vue-cli-plugin-electron-builder/index.js:161:28)
    at process._tickCallback (internal/process/next_tick.js:178:7)
(node:18936) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18936) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS and version:18.2
 - node version: 10
 - npm version:5.6
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 1.4
 - electron version: 6
 - other vue plugins used: none
 - custom config for vcp-electron-builder: none
 - (if possible) link to your repo: none

**Additional context**

**Comment by nklayman** [comment]
Try setting the `NODE_ENV` environment variable to `production` or `development` by adding the following to your `.env.test` file:

```
NODE_ENV=development (or production)
```
This plugin passes the current env to webpack so that it can optimize the build for production if you are building your app and include debugging support in development.
