### ISSUE TITLE
Add extra utils for development?

### ISSUE THREAD

**Issue by TotomInc** [nklayman/vue-cli-plugin-electron-builder#43]
If you plan to add QoL features for development, you can add [Devtron](https://github.com/electron/devtron) for a specific Electron devtools tab and [electron-timber](https://github.com/sindresorhus/electron-timber) for logging.

I don't really know if it is the appropriate place to provide them, or if it should be installed separately by the user.

**Comment by nklayman** [comment]
I plan on having a prompt where the user can select what devtools they want to install. This list will include vue-devtools and devtron, but not electron-timber. My reasoning behind this is that electron-timber has practically no setup, is not necessary, and, if placed in the renderer process, might break deployment as an SPA.

**Comment by TotomInc** [comment]
Your idea looks nice, do you have a clear idea of what features you want to implement?

**Comment by nklayman** [comment]
Unfortunately, I run into [this issue](https://github.com/electron/devtron/issues/99) with Devtron. I also noticed it hasn't been updated in 2 years, and seems like a dead project. I'm thinking of just sticking with VueJS devtools. What are your thoughts? Any up-to-date alternatives?

**Comment by TotomInc** [comment]
Yes it looks like the project is dead. I don't think there are devtron-like tools, so we may omit this one.

**Comment by nklayman** [comment]
I will close this issue as Devtron is deprecated and electron-timber is not necessary and has no setup or initialization code. I don't think there needs to be a prompt for installing vue-devtools as they don't get in the way and are very useful.
