### ISSUE TITLE
Possibility to change renderer process file name and path

### ISSUE THREAD

**Issue by brunogaspar** [nklayman/vue-cli-plugin-electron-builder#44]
Hello 👋 

Would be possible to change the renderer process file name and path, like how we can with the main by using `mainProcessFile` config option?

I tried to look into the source, but couldn't find a sane way to do it.

Thanks in advance!

**Comment by nklayman** [comment]
Almost all of the renderer process config is handled by vue-cli, just like your regular build. You will have to set it through the `chainWebpack` option in `vue.config.js`. I think this will work, but I am not sure (will test later today):

```javascript
// vue.config.js

module.exports = { 
  chainWebpack: (config) => {
    config.entry('app').clear().add('path to entry file')
  }
}
```
