### ISSUE TITLE
Electron isn't launching on serve:electron

### ISSUE THREAD

**Issue by charliezzo** [nklayman/vue-cli-plugin-electron-builder#441]
**Describe the bug**

it‘s not word on latest update "1.4.0" with electron version "6.0.4".
There is no warning or error, just "INFO Launching Electron..." and nothing else.

**To Reproduce**

vue create demo

vue add electron-builder

npm i

npm run serve:electron

**Expected behavior**

not work

**Screenshots**
![image](https://user-images.githubusercontent.com/9925064/63748891-d4334180-c8dc-11e9-837e-912afc6bf1c0.png)

no window opened after this message

**Environment (please complete the following information):**
 - OS and version: linux
 - node version: 11.15.0
 - npm version: 6.10.3
 - yarn version (if used): no
 - vue-cli-plugin-electron-builder version : 1.4.0
 - electron version: 6.0.4
 - other vue plugins used: element-ui (Whether I use this plug-in or no)
 - custom config for vcp-electron-builder: no
 - (if possible) link to your repo: https://github.com/charliezzo/gRPC-testing-tool

**Additional context**

windows10 is run perfact, only  linux can't bee used

**Comment by jerryshell** [comment]
https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/24#issuecomment-525184109
