### ISSUE TITLE
Expose settings for other files to watch for restarting Electron in serve:electron

### ISSUE THREAD

**Issue by stephenwilliams** [nklayman/vue-cli-plugin-electron-builder#45]
**Is your feature request related to a problem? Please describe.**
I have a rather large background.js/ts file due to what I am accomplishing in it. I'd like to split up parts of the file into different files. Unfortunately, it only restarts electron when the background.js/ts file is updated.

**Describe the solution you'd like**
I believe this could be worked around with making an array exposed in the configuration for adding files/globs to watch. 

**Describe alternatives you've considered**
I've not thought of any other solutions.

_P.S. I greatly appreciate the work you've put into this project! Thanks!_

**Comment by nklayman** [comment]
This feature has been added in commit e4d27aea8cb0370da91a952bbdb4f717ea08346f. It will be available in the next release. If you want to use it now, set `vue-cli-plugin-electron-builder`'s version to `nklayman/vue-cli-plugin-electron-builder`. This will install it directly from github. I'm glad you enjoy using it, let me know if you have any other suggestions, and thanks for this one.
