### ISSUE TITLE
background.js 加载 ssh2 模块出错  Cannot find module dist_electron/buffer-helpers

### ISSUE THREAD

**Issue by cloudcome** [nklayman/vue-cli-plugin-electron-builder#450]
**Describe the bug**
background.js 加载 ssh2 模块出错，提示：
```
Cannot find module dist_electron/buffer-helpers
```

**To Reproduce**
background.js 只有一行代码：

```
// background.js

import { Client } from 'ssh2';
```

**Expected behavior**
/

**Screenshots**
![image](https://user-images.githubusercontent.com/3362033/63907371-bcc79600-ca4d-11e9-8f28-5fd1b8ba957e.png)

**Environment (please complete the following information):**
 - OS and version: mac os 10
 - node version: v10.16.0
 - npm version: v6.9.0
 - yarn version (if used): v1.17.3
 - vue-cli-plugin-electron-builder version :  ^1.4.0
 - electron version:  ^6.0.0
 - other vue plugins used:  NONE
 - custom config for vcp-electron-builder: 
```
module.exports = {
    devServer: {
        port: 8083,
        host: '0.0.0.0'
    },
    css: {
        loaderOptions: {}
    },
    chainWebpack: config => {},
    configureWebpack: {
        plugins: [],
        devtool: 'source-map'
    },
    pluginOptions: {
        electronBuilder: {
            chainWebpackMainProcess: config => {},
            chainWebpackRendererProcess: config => {},
            builderOptions: {},
            mainProcessFile: 'src/background.js',
            mainProcessWatch: ['src/background.js', 'src/runtimes/**/*.js', 'src/configs.js'],
            mainProcessArgs: []
        }
    }
};
```
 - (if possible) link to your repo: 

**Additional context**
/

**Comment by cloudcome** [comment]
错误应该是在这里发生的：

![image](https://user-images.githubusercontent.com/3362033/63907683-fa78ee80-ca4e-11e9-9282-7ca34732e2f1.png)

构建之后的 __dirname 参数指向了固定的目录 `dist_electron`

**Comment by nklayman** [comment]
Try marking `ssh2` as an external by adding the following to your `vue.config.js`:

```js
module.exports = {
    pluginOptions: {
        electronBuilder: {
            externals: ['ssh2']
        }
    }
};
```

**Comment by cloudcome** [comment]
yes done!
