### ISSUE TITLE
renderer preload

### ISSUE THREAD

**Issue by Neko911** [nklayman/vue-cli-plugin-electron-builder#454]
**Describe the bug**
Preload not working, in both build and development mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/24293461/64025767-1ca16800-cb46-11e9-967a-576bda8fe08f.png)
![image](https://user-images.githubusercontent.com/24293461/64026378-51fa8580-cb47-11e9-8344-63be6118c686.png)

**Environment (please complete the following information):**
 - OS and version: Ubuntu 18.04
 - node version: 10.16.2 
 - vue-cli-plugin-electron-builder version : current
 - electron version: 6.0.0
 - other vue plugins used: typescript, vuetify, i18n
 - custom config for vcp-electron-builder: 
```

    electronBuilder: {
      mainProcessFile: 'src/electron/background.ts',
      chainWebpackMainProcess: (config) => {
        config.resolve.alias.set('@', path.join(__dirname, 'src'));
        config.resolve.alias.set('@core', path.join(__dirname, 'core'));
        config.module.rule('wasm').test(/\.wasm$/).use('file-loader').loader('file-loader');
        config.module.rule('node').test(/\.node$/).use('node-loader').loader('node-loader');
      },
      mainProcessTypeChecking: true,
      builderOptions: {},
    },
```
 - (if possible) link to your repo: imposible

linked issue: https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/89

**Comment by nklayman** [comment]
Did you make sure to put the `preload.js` file in the `public` folder? it works fine for me with the same main process code.

**Comment by Neko911** [comment]
I'm sure, also it there a way to bundle preload.js with webpack too?

**Comment by nklayman** [comment]
It may be possible to bundle it with webpack, but it would require a lot of config. Can you please create a sample repo that reproduces the issue. I am unable to replicate the error, so I can't fix it.

**Comment by cocochepeau** [comment]
Hi. ATM `__dirname` is in fact pointing to the dist directory.

**Comment by nklayman** [comment]
@cocochepeau `__dirname` should point to the directory in which the app is being run, which is `dist`. You shouldn't require any files of source during runtime as that will not be available in a built app. All of your `src` files should be bundled with webpack.

**Comment by SD-Gaming** [comment]
according to the Document - Guide - Preload Files to setting preload file, the same error occurs

could you show me how can I fix it, please? I'd appreciate it if you could help me. thank you!

![image](https://user-images.githubusercontent.com/25575589/85376763-bec58d00-b56a-11ea-80ac-cbdf81edd2e3.png)

**Comment by nklayman** [comment]
@SD-Gaming make sure you are on the latest version of the plugin (`v2.0.0-rc.2`).

**Comment by SD-Gaming** [comment]
thank your reply.
Yes, I sure definitely.
my devDep is `"vue-cli-plugin-electron-builder": "~2.0.0-rc.3"` now. 😔
@nklayman

**Comment by nklayman** [comment]
@SD-Gaming you have to use `path.join(__dirname, 'preload.js')`, not `__dirname + 'preload.js'`.

**Comment by SD-Gaming** [comment]
thanks a lot!
I have tried this way ever but it doesn't work,
but now it works well!
maybe change the option must re-serve the app.
@nklayman

**Comment by lahmidiamoumen** [comment]
update your vue.config.js as so:

module.exports = {
  pluginOptions: {
    electronBuilder: {
      preload: 'src/preload.js',
      // Or, for multiple preload files:
      preload: { preload: 'src/preload.js', otherPreload: 'src/preload2.js' }
    }
  }
}

**Comment by Infinituum17** [comment]
I have the same issue:

1. I put the preload tag inside my `vue.config.js` file 
![image](https://user-images.githubusercontent.com/40234342/103110965-0cb96b80-4648-11eb-97bc-e7df384d6659.png)
2. I put the same tag inside my `BrowserWindow` object (in `background.js`) 
![image](https://user-images.githubusercontent.com/40234342/103111013-818ca580-4648-11eb-8919-d461c5e6cfbf.png)

The error I got: 
![image](https://user-images.githubusercontent.com/40234342/103111030-c4e71400-4648-11eb-9187-911048f72d74.png)

All my dependencies: 
![image](https://user-images.githubusercontent.com/40234342/103111064-2d35f580-4649-11eb-8ab6-59c41e4bede9.png)

**Comment by lahmidiamoumen** [comment]
> I have the same issue:
> 
> 1. I put the preload tag inside my `vue.config.js` file
>    ![image](https://user-images.githubusercontent.com/40234342/103110965-0cb96b80-4648-11eb-97bc-e7df384d6659.png)
> 2. I put the same tag inside my `BrowserWindow` object (in `background.js`)
>    ![image](https://user-images.githubusercontent.com/40234342/103111013-818ca580-4648-11eb-8919-d461c5e6cfbf.png)
> 
> The error I got:
> ![image](https://user-images.githubusercontent.com/40234342/103111030-c4e71400-4648-11eb-9187-911048f72d74.png)
> 
> All my dependencies:
> ![image](https://user-images.githubusercontent.com/40234342/103111064-2d35f580-4649-11eb-8ab6-59c41e4bede9.png)
> 
> My folder structure:
> ![image](https://user-images.githubusercontent.com/40234342/103111123-c95ffc80-4649-11eb-8c78-d4af8dfbbb64.png)

Set ` nodeIntegration: false` why then you are using preload 
For more details check this https://github.com/electron/electron/issues/9920#issuecomment-575839738

**Comment by Infinituum17** [comment]
I was using the preload file to load some data before my app is executed.
I tried in every other way, it doesn't seem to work (even loading it inside the `background.js` file, before creating the actual Electron window). I don't know if it doesn't work just because I'm using a static class with static methods to load data.
And after all, after setting `nodeIntegration: false` in my `vue.config.js` I get the same error.
If you have some suggestions please share them with me, I'm new to Electron.

**Comment by MrZupperman** [comment]
Had the same issue. For me this was fixed by enabling the **enableRemoteModule: true** flag in the background.ts file, i.e.,
`mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    frame: false,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      enableRemoteModule: true,
      nodeIntegration: true,
    }
  })`

@nklayman Maybe this should be added to the documentation [here](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#preload-files).

**Comment by inksnowhailong** [comment]
> 有同样的问题。对我来说，这是通过在 background.ts 文件中启用**enableRemoteModule: true**标志来解决的，即 `mainWindow = new BrowserWindow({ width: 800, height: 600, frame: false, webPreferences: { preload: path.join(__dirname, 'preload.js'), enableRemoteModule: true, nodeIntegration: true, } })`
> 
> @nklayman也许这应该被添加到[这里](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#preload-files)的文档中。

no working

**Comment by haoranisg** [comment]
Everybody try this. 所有人试一下这个
  ```
  webPreferences: {
      // Use pluginOptions.nodeIntegration, leave this alone
      // See nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration for more info
      nodeIntegration: process.env.ELECTRON_NODE_INTEGRATION,
      contextIsolation: !process.env.ELECTRON_NODE_INTEGRATION,
      preload: preloadpath,

    },
```
<img width="763" alt="image" src="https://github.com/nklayman/vue-cli-plugin-electron-builder/assets/22336114/8353fb3b-25bb-4a8e-b234-1b7dfe4a98f4">
