### ISSUE TITLE
Error when I import nightmarejs

### ISSUE THREAD

**Issue by ahernand53** [nklayman/vue-cli-plugin-electron-builder#466]
At the moment that import the nightmarejs package it throw me an warning error
` warning  in ./node_modules/nightmare/lib/nightmare.js`
`Critical dependency: the request of a dependency is an expression`

structure where have the import 
`app/src/services/file.js`

I am importing it in the following way, but I guess that is where the error should be, the route from where I am importing it.
`import Nightmare from 'nightmare'`

in the devtools it shows me the following
![Screenshot from 2019-09-10 18-37-09](https://user-images.githubusercontent.com/40077239/64657691-3ff7cd00-d3fa-11e9-97ba-f07750a71e75.png)

**Comment by ahernand53** [comment]
Looking in many place I found this,

>  it turns out that webpack replaces __dirname with '/' by default. You must use an option to use the true value, which is documented here: https://webpack.js.org/configuration/node/.

 But I can't find a way to define that true value. Can anybody help me?

**Comment by nklayman** [comment]
The plugin sets that by default. I think the issue is that you need to mark nightmare as an [external](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules). To do this, set your `vue.config.js` to:

```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['nightmare']
    }
  }
}
```

**Comment by hexters** [comment]
I get this error
<img width="712" alt="Screen Shot 2019-11-11 at 11 07 32" src="https://user-images.githubusercontent.com/7827420/68560469-d042a480-0473-11ea-949f-67bc5c2b2fe0.png">

when I try this code 
```
const Nightmare = require('nightmare')
const nightmare = Nightmare({ show: true })

nightmare
  .goto('https://duckduckgo.com')
  .type('#search_form_input_homepage', 'github nightmare')
  .click('#search_button_homepage')
  .wait('#r1-0 a.result__a')
  .evaluate(() => document.querySelector('#r1-0 a.result__a').href)
  .end()
  .then(console.log)
  .catch(error => {
    console.error('Search failed:', error)
  })
```
