### ISSUE TITLE
Calling testWithSpectron() opens infinite windows

### ISSUE THREAD

**Issue by thislooksfun** [nklayman/vue-cli-plugin-electron-builder#467]
**Describe the bug**
Calling `testWithSpectron()` hangs the tests, and starts opening as many Electron windows as it can until the tests time out.

**To Reproduce**
Run the following spec:
```js
import testWithSpectron from "vue-cli-plugin-electron-builder/lib/testWithSpectron";
import chai, { expect } from "chai";
import chaiAsPromised from "chai-as-promised";

chai.use(chaiAsPromised);

describe("Application launch", function() {
  this.timeout(30000);

  beforeEach(function() {
    console.log("Before Each -- testWithSpectron()");
    return testWithSpectron().then(instance => {
      console.log("testWithSpectron().then");
      this.app = instance.app;
      this.stopServe = instance.stopServe;
    });
  });

  beforeEach(function() {
    console.log("Before Each -- chaiAsPromised");
    chaiAsPromised.transferPromiseness = this.app.transferPromiseness;
  });

  afterEach(function() {
    console.log("After");
    if (this.app && this.app.isRunning()) {
      return this.stopServe();
    }
  });

  it("opens a window", function() {
    console.log("opens?");
    const gwc = this.app.client.getWindowCount();
    console.log(gwc);
    return expect(gwc).to.eventually.have.at.least(1);
  });
});
```

**Expected behavior**
I expected the output
```
> Before Each -- testWithSpectron()
> testWithSpectron().then
> Before Each -- chaiAsPromised
> opens?
> After
```

And for it to only open one Electron window (or maybe even 0, if it should be headless).

Instead, it opens 5-10 windows (just keeps going until Mocha times out).

**Screenshots**
<img width="1024" alt="Screen Shot 2019-09-10 at 9 54 53 PM" src="https://user-images.githubusercontent.com/5367333/64664790-e8fff100-d415-11e9-8ad5-d7b7c9a23e45.png">
<img width="1988" alt="Screen Shot 2019-09-10 at 9 55 34 PM" src="https://user-images.githubusercontent.com/5367333/64664807-fddc8480-d415-11e9-9bc6-4f830ec91f74.png">
<img width="338" alt="Screen Shot 2019-09-10 at 9 56 07 PM" src="https://user-images.githubusercontent.com/5367333/64664799-f2895900-d415-11e9-8d3a-7ff7ca4c3f33.png">

**Environment (please complete the following information):**
 - OS and version: macOS 10.14.6 (18G87)
 - node version: v12.5.0
 - npm version: 6.9.0
 - yarn version (if used): N/A
 - vue-cli-plugin-electron-builder version : 1.4.0
 - electron version: 6.0.7
 - other vue plugins used:
   * @vue/cli-plugin-babel: 3.11.0
   * @vue/cli-plugin-eslint: 3.11.0
   * @vue/cli-plugin-unit-mocha: 3.11.0
   * @vue/cli-service: 3.11.0
   * @vue/test-utils: 1.0.0-beta.29
 - custom config for vcp-electron-builder:
```js
// vue.config.js
const path = require("path");

module.exports = {
  configureWebpack: {
    resolve: {
      alias: {
        Disciplines$: path.join(__dirname, "src/assets/earthdawn/disciplines"),
        Races$: path.join(__dirname, "src/assets/earthdawn/races"),
        Skills$: path.join(__dirname, "src/assets/earthdawn/skills"),
        Talents$: path.join(__dirname, "src/assets/earthdawn/talents"),
      },
    },
  },
  chainWebpack: config => {
    config.module
      .rule("yaml")
      .test(/\.ya?ml$/)
      .use("js-yaml-loader")
      .loader("js-yaml-loader")
      .end();
  },
  pluginOptions: {
    electronBuilder: {
      chainWebpackMainProcess: config => {
        config.resolve.alias.set("@", path.join(__dirname, "src/"));
      },
    },
  },
};
```
 - (if possible) link to your repo: https://github.com/thislooksfun/earthdawn

**Additional context**
N/A

**Comment by kelsos** [comment]
@thislooksfun any luck with that? I am also stumbling on the exact same issue.

**Comment by ekoeryanto** [comment]
If you in hurry, just like me.
try
```bash
npm i -D git://github.com/ekoeryanto/vue-cli-plugin-electron-builder#patch-1
```

**Comment by JBSoul** [comment]
I had the same issue and couldn't find any solution. Your patch solved it nicely :)

**Comment by nklayman** [comment]
V2.0 of this plugin includes an upgrade to spectron. I will release it soon, but for now: `yarn add -D vue-cli-plugin-electron-builder@alpha`.

**Comment by ezpzlmnsqz1337** [comment]
For me only the @ekoeryanto patch works, the alpha version still opens infinite windows until timeout.

**Comment by nklayman** [comment]
With the [v2.0.0 beta](https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-beta.0), you pass the spectron module to the `testWithSpectron` function, so you can install the proper version of spectron to match your electron version.
