### ISSUE TITLE
Fail to build windows on macOS Catalina

### ISSUE THREAD

**Issue by jie** [nklayman/vue-cli-plugin-electron-builder#468]
Fail to build windows on macOS Catalina

npm run electron:build -- --win

```
  • writing effective config  file=dist_electron/builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=6.0.8 appOutDir=dist_electron/win-unpacked
  • default Electron icon is used  reason=application icon is not set
  • building        target=nsis file=dist_electron/build_test Setup 0.1.0.exe archs=x64 oneClick=true perMachine=false
 ERROR  Error: Exit code: ENOENT. spawn prlctl ENOENT
Error: Exit code: ENOENT. spawn prlctl ENOENT
    at /Users/zhouyang/coding/build_test/node_modules/builder-util/src/util.ts:125:16
    at exithandler (child_process.js:297:5)
    at ChildProcess.errorhandler (child_process.js:309:5)
    at ChildProcess.emit (events.js:200:13)
    at ChildProcess.EventEmitter.emit (domain.js:471:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:74:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! build_test@0.1.0 electron:build: `vue-cli-service electron:build "--win"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the build_test@0.1.0 electron:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhouyang/.npm/_logs/2019-09-11T03_05_16_087Z-debug.log
```

**Comment by nklayman** [comment]
I don't have access to a mac, so I can't reproduce the issue myself. Try removing `node_modules` and reinstalling deps. Also, try upgrading to the latest electron-builder by adding the following to your `package.json`:

```json
"resolve": {
  "electron-builder": "^21.2.0"
}
```

You will need to use [yarn](https://yarnpkg.com) for this to work.

**Comment by mazlano27** [comment]
@nklayman I just updated to Catalina and i'm facing this same issue. I did what you suggested but could not get it to work. @jie did you manage to resolve this issue?

**Comment by ukmarn** [comment]
@jie @mazlano27 I am also experiencing this. Any updates?

**Comment by mazlano27** [comment]
@ukmarn I ended up building my app on a Windows pc. Based on what I found - this error is due to Catalina dropping support for 32 bit apps (like wine which was used to create the windows installers)

**Comment by maximilianschmidt** [comment]
maybe this will help, didn't have the chance to test it myself yet though: https://github.com/electron/node-rcedit/issues/51#issuecomment-546234084

**Comment by utd1878** [comment]
I'm still seeing this.  I've attempted to follow the instructions that @maximilianschmidt linked to and it still doesn't build.  It gives me the same error Error: spawn Unknown system error -86

**Comment by AndreiSoroka** [comment]
You can fix
`npm i electron-builder@22.2.0 --save`
or just wait for https://github.com/nklayman/vue-cli-plugin-electron-builder/pull/574

**Comment by gudqs7** [comment]
electron-builder-22.2.0 

work for me 
see https://github.com/electron-userland/electron-builder/issues/4305

**Comment by oshell** [comment]
add this to your package.json

```
  "resolutions": {
    "electron-builder": "22.2.0"
  },
```
