### ISSUE TITLE
"vue-cli-service electron:serve" don't relaunch app

### ISSUE THREAD

**Issue by Incont** [nklayman/vue-cli-plugin-electron-builder#469]
**Describe the bug**
"vue-cli-service electron:serve" don't relaunch app

**To Reproduce**
When I modify a script that imported in background.js, electron app doesn't restart

**Environment (please complete the following information):**
 - OS and version:  Win10
 - node version:  v10.16.0
 - npm version: 6.9.0
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version :  1.4.0
 - electron version: 6.0.0
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo:

**Comment by nklayman** [comment]
Add the file you want to watch to the [mainProcessFile](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#webpack-configuration) array. It doesn't watch imported files by default.
