### ISSUE TITLE
Play MP3 file

### ISSUE THREAD

**Issue by brunokunace** [nklayman/vue-cli-plugin-electron-builder#47]
I need to play sound on "mounted()" of one component, how to access the mp3 file inside vue component?

i have a sound.mp3 inside src/assets folder

my component its on src/views folder

i try make it on mounted (): 
`const audio = new Audio('../assets/sound.mp3')`

but i receive error on console in electron app, talking for error on source.

How best way to access those files?

Thanks!

**Comment by brunokunace** [comment]
Thanks a lot, works fine

**Comment by brunokunace** [comment]
Sorry, need reopen

Its works fine on serve:electron, but on build, the sound.mp3 dont play.

Versions:
Vue: 3.0.0,
Node: 8.9.4

Console response:
```
Building app with electron-builder:

  • electron-builder version=20.27.1
  • description is missed in the package.json appPackageFile=F:\docker\mypharmabr\new-order-popup\package.json
  • author is missed in the package.json appPackageFile=F:\docker\mypharmabr\new-order-popup\package.json
  • writing effective config file=dist_electron\builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=2.0.7 appOutDir=dist_electron\win-unpacked
  • default Electron icon is used reason=application icon is not set
  • building        target=nsis file=dist_electron\new-order-popup Setup 0.1.0.exe archs=x64 oneClick=true
  • building block map blockMapFile=dist_electron\new-order-popup Setup 0.1.0.exe.blockmap

Build complete!
```

**Comment by nklayman** [comment]
Can you post the file tree of the `dist_electron/win-unpacked` folder. `process.env.BASE_URL` is set to `__dirname` in electron builds. All files in public should be copied there, including the audio file.

**Comment by nklayman** [comment]
Also, did the `../assets/audio.mp3` work in regular build/serve?

**Comment by brunokunace** [comment]
![image](https://user-images.githubusercontent.com/16597320/44179508-a44c3e00-a0cd-11e8-89e7-a001aef53cd4.png)
![image](https://user-images.githubusercontent.com/16597320/44179538-b7f7a480-a0cd-11e8-9d6e-ec8342eb85e5.png)
![image](https://user-images.githubusercontent.com/16597320/44179542-c0e87600-a0cd-11e8-9925-ae4e27b86fef.png)

**Comment by brunokunace** [comment]
const audio = new Audio(process.env.BASE_URL + 'sound.mp3')

this code works fine on serve:electron, my sound file is under the public folder.

**Comment by nklayman** [comment]
make sure to import `url` and `path`
use:
```javascript
const soundFile =
    process.env.BASE_URL !== '/'
        ? url.format({
              pathname: path.join(process.env.BASE_URL, 'sound.mp3'),
              protocol: 'file',
              slashes: true
          })
        : path.join(process.env.BASE_URL, 'sound.mp3')
const audio = new Audio(soundFile)
```
This works in SPA build/serve and Electron build/serve

**Comment by Japangeek** [comment]
I need to reopen it. Even with your solution (@nklayman) doesnt work on build. However, on serve, it works fine.

If I'm entering:

```javascript
const soundFile =
    process.env.BASE_URL !== '/'
        ? url.format({
              pathname: path.join(process.env.BASE_URL, 'sound.mp3'),
              protocol: 'file',
              slashes: true
          })
        : path.join(process.env.BASE_URL, 'sound.mp3')
console.log(soundFile);
const audio = new Audio(soundFile);
```
Then I got as console.log -> 
`file:///C:/Users/John/AppData/Local/Programs/TestApplication/resources/app.asar/sound.mp3`
Which obviously doesnt work since app.asar is not a directory.
Also I couldn't find the "sound.mp3" somewhere at TestApplication/resources.

**Comment by Japangeek** [comment]
I got fixed by using import

```
// @ts-ignore
import sound from './assets/audio/sound.mp3'
const audio = new Audio(sound);
```

you can import files from assets through webpack

**Comment by alectrocute** [comment]
Worked for me @Japangeek. Thanks.

**Comment by michaelmano** [comment]
I know this is closed, However none of the above solutions work with the latest versions.
https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/872#issuecomment-656292808
This solution worked however.

I just changed it to `local-asset` in place of video.

**Comment by cassiorsfreitas** [comment]
What about a playlist rather than only single song? Should I need to import every file previously?
