### ISSUE TITLE
【lint】'__static' is not defined

### ISSUE THREAD

**Issue by webees** [nklayman/vue-cli-plugin-electron-builder#470]
`npm run lint`

![image](https://user-images.githubusercontent.com/5155291/64695616-2aa0a280-d4cf-11e9-8997-578148f57b71.png)

I don't know how to solve it, ask for help, thank you.

https://github.com/webees/electron-base/blob/master/src/__electron__/init.js

**Comment by nklayman** [comment]
@ahernand53 answer is correct. You can also put the comment at the top of the file, which I recommend.

**Comment by webees** [comment]
There must be a better way.

**Comment by lisonge** [comment]
@ahernand53 
in typescript, how can  lint its type?
like this ?
`
 / * global __static:string * /
`
but vscode tip its type is any

**Comment by TiagoSilvaPereira** [comment]
Thanks @ahernand53 it worked very well here :smiley:

**Comment by darkomenx** [comment]
Ok it solve the issue but this is a dirty way for that.

Why ESLint say that __static is not defined ?

Perhaps we can import module for solving this ?

**Comment by klren0312** [comment]
can set in `.eslintrc.js`
https://eslint.org/docs/rules/no-restricted-globals#disallow-specific-global-variables-no-restricted-globals

```js
module.exports = {
  rules: {
    'no-restricted-globals': ['__static']
  }
}
```
