### ISSUE TITLE
webview tag doesn't work

### ISSUE THREAD

**Issue by huxiaoxi1992** [nklayman/vue-cli-plugin-electron-builder#472]
**Describe the bug**

Webview tag shows a blank page.

**To Reproduce**

1. Init with Vue CLI, use default configs
2. Add vcp to project
3. Replace `App.vue` template with webview tag
```html
<template>
  <div id="app">
    <webview
      id="foo"
      src="https://www.github.com/"
      style="display:inline-flex; width:640px; height:480px"
    ></webview>
  </div>
</template>
```
4. yarn electron:serve

**Expected behavior**
The window shows the github page.

**Screenshots**
![image](https://user-images.githubusercontent.com/17983389/64769177-68f49b00-d57d-11e9-83eb-75d1026ef720.png)

**Environment (please complete the following information):**
 - OS and version: win 10 1903
 - node version: 10.15.3
 - yarn version: 1.17.3

```json
  "dependencies": {
    "core-js": "^2.6.5",
    "vue": "^2.6.10"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.11.0",
    "@vue/cli-plugin-eslint": "^3.11.0",
    "@vue/cli-service": "^3.11.0",
    "babel-eslint": "^10.0.1",
    "electron": "^5.0.0",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "vue-cli-plugin-electron-builder": "^1.4.0",
    "vue-template-compiler": "^2.6.10"
  },
```
 - custom config for vcp-electron-builder: none

**Comment by zhouyangit** [comment]
You now need to explicitly enable webviewTag in your webPreferences object.
```
const mainWindow = new BrowserWindow({
  webPreferences: {
    webviewTag: true
  }
})
```

[](https://electronjs.org/docs/api/webview-tag)
