### ISSUE TITLE
Crash when importing Google Cloud Speech to Text

### ISSUE THREAD

**Issue by avi12** [nklayman/vue-cli-plugin-electron-builder#476]
**Describe the bug**
I tried importing `@google-cloud/speech`, but running `yarn electron:serve` will eventually result in a crash.

**To Reproduce**
```
vue create vue-electron-test
cd vue-electron-test
vue add electron-builder (choose the latest Electron - 6, at the time of writing the post)
yarn add @google-cloud/speech
```
Add to `background.js`:
```js
import speech from "@google-cloud/speech";
const client = new speech.SpeechClient({keyFilename: "credentials.json"});
```
Then, run:
```
yarn electron:serve
```

**Expected behavior**
I expect the line of `const client = new speech.SpeechClient({keyFilename: "credentials.json"});` to work normally, i.e. to initialize the `SpeehClient()` instance while using the credentials in `credentials.json`

**Screenshots**
![](https://i.imgur.com/STMrzoq.png)

**Environment (please complete the following information):**
 - OS and version: Windows 10 Pro 1903 build 18362.3356
 - node version: 10.16.3
 - npm version: 6.9.0
 - yarn version: 1.17.3
 - vue-cli-plugin-electron-builder version : ^1.4.0
 - electron version: 6.0.9
 - other vue plugins used: Nothing
 - custom config for vcp-electron-builder: Nothing
 - (if possible) link to your repo: No repo, but no need for it - just follow the steps to reproduce.

**Additional context**
The project itself is under `C:\repositories\speech-to-text-test`

**Comment by nklayman** [comment]
Try marking `@google-cloud/speech` as an [external](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules) by setting your `vue.config.js` to:
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['@google-cloud/speech']
    }
  }
}
```

**Comment by avi12** [comment]
I tried doing that and it indeed prevent the crash of importing `@google/speech-to-text`.
Though there is still a problem that causes it to crash - when I try to use [node-record-lpcm16](https://www.npmjs.com/package/node-record-lpcm16), or more specifically - the `record.start()`, I get the following error:
![electron_yFHQyW3sLH](https://user-images.githubusercontent.com/6422804/66208531-ee232980-e6bd-11e9-8186-64865d0ff4f1.png)

**Comment by nklayman** [comment]
Try adding that module as an external too.

**Comment by avi12** [comment]
I tried. Sadly, it didn't help - got the same error

**Comment by avi12** [comment]
@nklayman 
> Try adding that module as an external too.

Do you have any idea how to solve the problem?

**Comment by nklayman** [comment]
That is because there is no `start` function for that module. See the [example](https://www.npmjs.com/package/node-record-lpcm16#usage).

**Comment by avi12** [comment]
After digging into the code, I saw it as well.
The only problem right now is that since I'm on Windows, it won't work out of the box - I need to make the `node-record-lpcm16/index.js` spawn a process of `sox.exe`, while by default it will attempt spawning `sox`.
Since I want my application to be portable, I won't wanna make the user to install an extra application, but rather bundle it with mine, i.e. I need to modify the code myself to make the `index.js` execute `sox.exe`

**Comment by avi12** [comment]
Seems like the easiest way to solve the problem is by simply using [SoX 14.4.1](https://sourceforge.net/projects/sox/files/sox/14.4.1/sox-14.4.1-win32.zip/download) rather than 14.4.2

**Comment by avi12** [comment]
Oh, I'd like to mention that in order to get it to work, the parameter `--type` must have the value `raw`, i.e. make sure that in the SoX's arguments list, there's `"--type", "raw",`
Plus, I discovered that I _do_ need to add the `node-record-lpcm16` to `pluginOptions.electronBuilder.externals` in `vue.config.js`

Other than that, it works flawlessly!
