### ISSUE TITLE
Electron app don't apply devServer.proxy

### ISSUE THREAD

**Issue by CHNB128** [nklayman/vue-cli-plugin-electron-builder#477]
**Describe the bug**
When i build my app for windows (unpacked, portable) `devServer.proxy` in `vue.config.js` don't apply for my application. 
Application use default `app://` base url insted of `http://hostname:port`, as example.

**To Reproduce**
build application under windows with 
`vue.config.js`
```
module.exports = {
  publicPath: '/',
  devServer: {
    proxy: {
      [process.env.VUE_APP_BASE_API]: {
        target: `http://${process.env.VUE_APP_API_HOST}:${process.env.VUE_APP_API_PORT}/api`,
        changeOrigin: true,
        pathRewrite: {
          ['^' + process.env.VUE_APP_BASE_API]: ''
        }
      },
    }
  },
}
```
`axios`
```
const service = axios.create({
  // url = base url + request url
  baseURL: '/api'
  // send cookies when cross-domain requests
  // withCredentials: true,
  // request timeout
  timeout: 5000
});
```

**Expected behavior**
Expect that electron application apply proxy configuration as default vue do.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/26171209/64978705-f61a5580-d8d7-11e9-890f-b851dea523d1.png)

**Environment (please complete the following information):**
 - OS and version: Windows 10
 - node version: 12.7.0
 - npm version: 6.10.0
 - yarn version (if used): 1.17.3
 - vue-cli-plugin-electron-builder version : ^1.4.0
 - electron version: 6.0.0
 - other vue plugins used: 
    "@vue/cli-plugin-babel": "^3.11.0",
    "@vue/cli-plugin-eslint": "^3.11.0",
    "@vue/cli-service": "^3.11.0",
    "@vue/eslint-config-standard": "^4.0.0",
    "vue-cli-plugin-vuetify": "^0.6.3",
 - custom config for vcp-electron-builder: 
```
electronBuilder: {
  builderOptions: {
    appId: 'com.bitplay.app',
    win: {
      target: [
        {
          target: 'portable'
        }
      ]
    },
    linux: {
      target: [
        {
          target: 'appImage'
        },
        {
          target: 'snap'
        },
        {
          target: 'deb'
        },
        {
          target: 'pacman'
        }
      ]
    }
  }
}
```
 - (if possible) link to your repo: 

**Additional context**

**Comment by nklayman** [comment]
`devServer.proxy` only applies for the dev server, not the built app. See [Changing the file loading protocol](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#changing-the-file-loading-protocol) for instructions on using a custom protocol.
