### ISSUE TITLE
Dashboard Support

### ISSUE THREAD

**Issue by wspl** [nklayman/vue-cli-plugin-electron-builder#48]
Task `serve:electron` don't have "Dashboard" page like task `serve`.

![Dashboard page of `serve:electron`](https://user-images.githubusercontent.com/2133311/44135850-44a99446-a09d-11e8-8a16-8d7a145b4094.png)

![Dashboard page of `serve`](https://user-images.githubusercontent.com/2133311/44135839-3da705ac-a09d-11e8-934e-5c31517ddfd1.png)

Is it a bug or unimplemented feature?

**Comment by nklayman** [comment]
Currently the UI is broken, waiting on [this issue](https://github.com/vuejs/vue-cli/issues/2361) till I can fix it.

**Comment by theharshin** [comment]
When using UI, the `--dashboard` argument on `electron:build` command is appended at last. So final string becomes `vue-cli-service electron:build --macos dmg zip --ia32 --dashboard`

As menthioed in docs,
> All CLI arguments passed to electron:build will be forwarded to electron-builder.

So `--dashboard` argument is passed to `electron-builder` which throws an error. Can we remove the argument till the dashboard support is added?

**Comment by nklayman** [comment]
As of rc.3 I think, the dashboard command is removed from the args passed to electron-builder.

**Comment by theharshin** [comment]
I can see it here. I've commented this line on my local and it is working fine.
https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/v1.0.0-rc.7/ui.js#L121

**Comment by nklayman** [comment]
Shoot, that was supposed to be removed. I fixed it with d122fe60330832f7c8368fb36d5e34edd1d65df0 (https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/d122fe60330832f7c8368fb36d5e34edd1d65df0/index.js#L72).

**Comment by fenixphp** [comment]
the ideal option is to leave only the console output. remove everything else.

**Comment by nklayman** [comment]
Now only the console page is shown. You can run a regular build for webpack dashboard and bundle analyzer.
