### ISSUE TITLE
Doesn't take the route en production from vue-router

### ISSUE THREAD

**Issue by ahernand53** [nklayman/vue-cli-plugin-electron-builder#485]
I am assigning a route with vue-router as follows in the documentation 
`loginWindow.loadURL(process.env.WEBPACK_DEV_SERVER_URL + 'login')`

but in the production section, I don't know if I should create a new file called login or assign it to it, I refer to this part
 `loginWindow.loadURL('app: //./index.html')`

some help with this?

**Comment by JustGogoing** [comment]
same issue  .....

**Comment by JustGogoing** [comment]
> 我正在使用vue-router分配路由，如下文档中所述
> `loginWindow.loadURL(process.env.WEBPACK_DEV_SERVER_URL + 'login')`
> 
> 但是在生产部分中，我不知道是否应该创建一个名为login的新文件或将其分配给它，我指的是这一部分
> `loginWindow.loadURL('app: //./index.html')`
> 
> 一些帮助吗？

How did you solve it??  i need u help

**Comment by JustGogoing** [comment]
`
 if (process.env.WEBPACK_DEV_SERVER_URL) {
    login.loadURL(`${process.env.WEBPACK_DEV_SERVER_URL}#/login`)
    if (!process.env.IS_TEST) login.webContents.openDevTools()
  } else {
    createProtocol('app')
    login.loadURL('app://./index.html#/login')
  }
`

success 搞定

**Comment by ahernand53** [comment]
thanks, I need that.
