### ISSUE TITLE
App Icon is not getting loaded 

### ISSUE THREAD

**Issue by MoezBouaggad** [nklayman/vue-cli-plugin-electron-builder#49]
Im setting the icon file in background.js file but its not getting loaded for some reason.
`const window = new BrowserWindow({
    width: 1450,
    height: 750,
    icon: path.join(__dirname, "assets/icons/64x64.png")
  });`

**Comment by nklayman** [comment]
The assets folder gets transpiled and renamed by webpack. Move the icon folder into the public folder and set the path to `path.join(__static, "icons/64x64.png")`. If it works, please close this issue.

**Comment by MoezBouaggad** [comment]
Thanks, it works.

**Comment by RealGoodProgrammer** [comment]
1.0.0-rc3 Your solution not works in GNU/Linux GNOME 3. And how can I achieve the same through package.json instead of background.js?
