### ISSUE TITLE
electron:build ignores --mode environment file

### ISSUE THREAD

**Issue by Latentimagedesign** [nklayman/vue-cli-plugin-electron-builder#490]
**Describe the bug**
We have environment files setup for two versions of our app:

.env.starter
.env.pro

When running the regular serve command with the correct mode (npm run serve --mode starter) it correctly sets the variables we have set in the file in order for our app to read them.

However, when we switch the command to use electron:serve --mode starter it does not read the .env.starter file's variables. 

ps. It does work with a normal .env file (no mode). 

**To Reproduce**
Setup a environment file for a specific mode (https://cli.vuejs.org/guide/mode-and-env.html#modes) and run: npm run electron:serve --mode [mode]

**Expected behavior**
The variables stored in a mode specific environment files should be available in the application when that mode name is passed in.

**Comment by nklayman** [comment]
Make sure to run `npm run electron:serve -- --mode starter`. Note the `--`. This is required so that npm knows to pass the args to the script being run.

**Comment by Latentimagedesign** [comment]
@nklayman - thanks again man. I can't believe we didn't try that first.
