### ISSUE TITLE
Route path wrong when using history.back()

### ISSUE THREAD

**Issue by Christilut** [nklayman/vue-cli-plugin-electron-builder#492]
**Describe the bug**
This only happens in the build version, not in development.

When I use the mouse back button or when I use `history.back()`, I end up with a `null` route.

This is because the `to.fullPath` in the router contains the full absolute path to the asar file, and the route behind it, eg: `/C/Users/etc../app.asar/home`

Vue router can't match the path and so it goes to an empty page.
 
I've done a workaround like this for now:
```js
router.beforeEach((to, from, next) => {
  if (to.fullPath.includes('.asar')) {
    const split: string[] = to.fullPath.split('.asar')
    const fixedPath: string = split[split.length - 1]

    return next({
      path: fixedPath
    })
  }

  next()
})
```

**To Reproduce**
Go to any page. Now go to another to make sure you can go back. Press mouse back button or do it programmatically with `history.back()`

**Expected behavior**
It should go back to the previous route. It should not use the asar path.

**Environment (please complete the following information):**
 - OS and version: Win10
 - node version: 10.15.1
 - npm version: 6.4.1
 - vue-cli-plugin-electron-builder version : 1.4.0
 - electron version: 6.0.0
 - other vue plugins used: router 3.0.3, vue 2.6.10

**Comment by nklayman** [comment]
I don't have any issues using the mouse to go back. Make sure you have vue-router using hash mode, not history.

**Comment by Christilut** [comment]
Okay that solves it.

But I don't see this anywhere in the docs. And maybe the plugin should change it automatically from history to hash?
