### ISSUE TITLE
[HELP] How to include images in background.js

### ISSUE THREAD

**Issue by mattschlosser** [nklayman/vue-cli-plugin-electron-builder#494]
I need to include an icon image for the tray icon, and have no idea. Can someone point me in the right direction, in what I need to accomplish this. In which directory do I put the image file so it is packaged into the app after it is built?

Any advice and direction would be much appreciated

```
\\ background.js
let tray = new Tray('/some/static/path/to/image/that/must/be/shipped/with/the/app');
```

**Comment by nklayman** [comment]
See the [icon guide](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#icons). It doesn't cover tray icons, but you should just be able to use the path to the app icon.

**Comment by mattschlosser** [comment]
Thanks. And to think I was on the same page earlier setting up the vscode debugging :P
