### ISSUE TITLE
Empty mac app window

### ISSUE THREAD

**Issue by pksunkara** [nklayman/vue-cli-plugin-electron-builder#50]
**Describe the bug**
`build:electron` building empty app window with no menus. Can't even find the error

**To Reproduce**
1. Clone git://github.com/osapps/dotsync
2. `cd packages/@dotsync/app`
3. `npm install`
4. `npm run build:electron`

**Expected behavior**
App should be produced when opened that should render my file and menus.

**Environment (please complete the following information):**
 - OS and version: Mac
 - Node version: 10
 - npm version:
 - yarn version (if used): 1.9.4
 - vue-cli-plugin-electron-builder version : 1.0.0-beta.6
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo:

**Comment by nklayman** [comment]
In `router/index.js`, change the router creation to:
```javascript
const router = new VueRouter({
  base: '/',
  routes,
});
```
History mode doesn't work in electron builds, and `process.env.BASE_URL` gets set to `./` instead of `/`.
