### ISSUE TITLE
Plugin vue-cli-plugin-electron-builder does not have a generator to invoke

### ISSUE THREAD

**Issue by enbermudas** [nklayman/vue-cli-plugin-electron-builder#500]
**Describe the bug**
I just created a fresh project with the @vue/cli and the installed the plugin by running `vue add electron-builder` but the next thing appears in my terminal:

```
�  Installing vue-cli-plugin-electron-builder...

yarn add v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
✔  Successfully installed plugin: vue-cli-plugin-electron-builder

Plugin vue-cli-plugin-electron-builder does not have a generator to invoke
```
After that, I can't use the `yarn electron:serve` command.

Not a single file of my project has been modified by me or the plugin installation.

**To Reproduce**

1. Create a fresh new project by running: vue create app-name
2. Run `vue add electron-builder`
3. Run `yarn electron:serve`

**Expected behavior**
Serve the project.

**Environment (please complete the following information):**
 - OS and version: Windows 7
 - node version: 12.0.4
 - yarn version (if used): 1.13.0
 - vue-cli-plugin-electron-builder version : 1.4.0

**Comment by nklayman** [comment]
It seems like the download failed and the package is corrupted. Try reinstalling modules (`rm -r node_modules && yarn`). If that still doesn't work, clear the package cache for this plugin (`yarn cache clean vue-cli-plugin-electron-builder`).

**Comment by enbermudas** [comment]
I've got the same result by doing the steps described above

**Comment by enbermudas** [comment]
I ended up creating a whole new project and that worked just fine. Thanks for the help!

**Comment by nklayman** [comment]
Sometimes the download of a package just gets messed up. Normally clearing node_modules and reinstalling fixes it. Did you clear and reinstall node_modules after clearing the cache?

**Comment by EvanXzj** [comment]
I've got the same output with electron-builder@2.0.0-beta.0
@nklayman please help!

**Ouputs**

```bash
 vue add electron-builder@2.0.0-beta.0

📦  Installing vue-cli-plugin-electron-builder@2.0.0-beta.0...

> ejs@3.0.1 postinstall /Users/xxxx/projects/xxx/my-wallet/node_modules/app-builder-lib/node_modules/ejs
> node ./postinstall.js

+ vue-cli-plugin-electron-builder@2.0.0-beta.0
added 202 packages from 121 contributors in 22.743s
✔  Successfully installed plugin: vue-cli-plugin-electron-builder@2.0.0-beta.0

Plugin vue-cli-plugin-electron-builder@2.0.0-beta.0 does not have a generator to invoke
```

**Expected behavior**
Serve the project.

**To Reproduce**

```bash
vue create my-wallet
cd my-wallet
npm run serve  # Ctrl + c  Stop Server
vue add electron-builder@2.0.0-beta.0
```

**Environment**
```
OS:  MacOs 0.13.6
Node: v10.17.0
Npm: v6.12.0
vue-cli:  4.1.2
```

**Comment by nklayman** [comment]
@evanxzj you will need to run `vue invoke electron-builder`. Vue cli doesn't work properly when you specify a version of a plugin.

**Comment by EvanXzj** [comment]
@nklayman Thanks!!
