### ISSUE TITLE
Make background.js / background.ts dynamic

### ISSUE THREAD

**Issue by dlesendric** [nklayman/vue-cli-plugin-electron-builder#504]
Hello ,
it will be nice to we have some config for this file (src/background.js). 
I would like to change destination of that file from src to some other div. Ideal will be that this can be configureable from package.json or in other way.

**Comment by BojanRatkovic** [comment]
+1

**Comment by nklayman** [comment]
You already can, set your `vue.config.js` to:
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      mainProcessFile: 'src/myBackgroundFile.js'
    }
  }
}
```
