### ISSUE TITLE
Access is denied error while trying to build app

### ISSUE THREAD

**Issue by SerekKiri** [nklayman/vue-cli-plugin-electron-builder#509]
While running `yarn dist` -> `"dist": "electron-builder --x64 --win",` 
I get error `asapp.exe: Access is denied.`

**To Reproduce**
Try to build [asapp](https://github.com/asasakpl/asapp). 

**Expected behavior**

App should build version for windows to dist folder

**Screenshots**

**Environment (please complete the following information):**
 - OS and version:
 - node version:  v12.10.0
 - npm version:6.11.3
 - yarn version (if used): 1.19.1
 - vue-cli-plugin-electron-builder version : ^1.4.0
 - electron version: ^5.0.0
 - other vue plugins used: vuetify plugin
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: https://github.com/asasakpl/asapp

**Comment by SerekKiri** [comment]
More of error
```
yarn run v1.19.1
$ electron-builder --x64 --win -p always GH_TOKEN
  • electron-builder  version=21.2.0 os=10.0.17763
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=5.0.11 appOutDir=dist\win-unpacked
  ⨯ remove asapp\dist\win-unpacked\asapp.exe: Access is denied.
app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
```

**Comment by SerekKiri** [comment]
Ok, it seems like error appears when I'm trying to add auto update, I will work around this asap but maybe you have any tips how to add auto update while using vue-cli-plugin-electron-builder?

**Comment by nklayman** [comment]
Check out the new [auto update guide](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#auto-update).

**Comment by SerekKiri** [comment]
It seems like it works right now, but still throw `app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE` on linux. I will check later on windows :+1:

**Comment by SerekKiri** [comment]
It works :+1:
