### ISSUE TITLE
Errors retrieving paths, node-module externalization?

### ISSUE THREAD

**Issue by lspohn** [nklayman/vue-cli-plugin-electron-builder#51]
**Describe the bug**

Hello! Thanks a lot to your for providing this plugin.

I tried to migrate my project from electron-webpack to vue-cli-plugin-electron-builder cause HMR is broken in electron-webpack atm.

I created a new project with vue cli and then merged the automatically created files with my project and deleted the unneccesary ones.

When I run serve:electron, I get the error shown in the screenshot. Note that leveldown is a native dependency in my project and shouldnt be included in Webpack.

![image](https://user-images.githubusercontent.com/32612162/44211957-66512780-a16a-11e8-9766-4e4e433f3831.png)

With electron-webpack, the "renderer.js" webpack file has 4,000 lines.
With vue-cli-plugin-electron-builder, I get to 19,000 lines in "app.js"!

I suspected that webpack didn't externalize the node-modules. 

So I then changed the vue.js.config to externalize all packages in my package.json by webpack (see below). Then, I get a strange path error. It seems to try to fetch modules from:

"C:\[appfolder]\node_modules\electron\dist\resources\default_app.asar\node_modules"
"C:\[appfolder]\node_modules\electron\dist\resources\node_modules"
"C:\[appfolder]\node_modules\electron\dist\resources\electron.asar\renderer\api\exports"
and throws an error (cause package is located in "C:\[appfolder]\node_modules")

To summarize:
- Something's wrong with the module externalization
- Something's wrong with the path.

Thanks a lot for your help.

**To Reproduce**
- Add node-modules as webpack.externals
- Check projects with native libraries

**Environment (please complete the following information):**
 - OS and version: Win 10 x64 Prof
 - Node version: 8.11.4
 - npm version: recent
 - yarn version (if used): recent
 - other vue plugins used: 
    "vue": "^2.5.17",
    "vue-async-computed": "^3.4.0",
    "vue-electron": "^1.0.6",
    "vue-router": "^3.0.1",
    "vue-shortkey": "^3.0.2",
    "vuedraggable": "^2.16.0",
    "vuetify": "^1.1.11"
    "@vue/cli-plugin-babel": "^3.0.0",
    "@vue/cli-plugin-eslint": "^3.0.0",
    "@vue/cli-plugin-unit-jest": "^3.0.0",
    "@vue/cli-service": "^3.0.0",
    "@vue/eslint-config-standard": "^3.0.0",
    "@vue/test-utils": "^1.0.0-beta.20",
    "vue-cli-plugin-electron-builder": "^1.0.0-beta.6",
    "vue-template-compiler": "^2.5.17",
 - custom config for vcp-electron-builder: 
```
var nodeExternals = require('webpack-node-externals');
module.exports = {
  pluginOptions: {
    electronBuilder: {
      chainWebpackRendererProcess: config => {
        config.externals(nodeExternals(
          {
            modulesFromFile: true,
            whitelist: ['vue']
          }
        ))
        return config
      },
  }
}
}
```

**Comment by nklayman** [comment]
For me, everything worked fine for build. However, it does fail for serve (will continue to look into). As for the larger `app.js`, this is caused by `vue-cli`'s build config. All of the renderer process build (except for electron-specific additions) is the same as an SPA (regular `build` command) build. If you think externalization should be enabled by default for electron builds only, I will look into that.

**Comment by lspohn** [comment]
Hey, thanks for your fast answer. It seems that other boilerplates externalize dependencies listed in package.json automatically. But I don't know if that is of any advantage - so maybe I'd just add the option to do so in a future release.

Coming back to my problem - WebPack with your plugin also includes libraries that are built as native library and therefore should definitely not become included as .js.

Do you know how to extend the options in your script so that doesn't happen & so that the native libraries (I think they are compiled as .node-Module) are loaded?

When I used electron-webpack, no further config was neccessary, it did work out of the box. Maybe the config from that can be adapted?

**Comment by nklayman** [comment]
Alright, I have a solution! Set `vue.config.js` to:
```javascript
module.exports = {
    pluginOptions: {
        electronBuilder: {
            chainWebpackRendererProcess: config => {
                config.module
                    .rule('node-loader')
                    .test(/\.node$/)
                    .use('node')
                    .loader('node-loader')
                config.resolve.alias.set(
                    'leveldown',
                    'leveldown/build/Release/leveldown.node'
                )
                return config
            }
        }
    }
}
```
This redirects `leveldown` to the actual `leveldown.node` file and configures `node-loader` (which you will need to install with `yard add -D node-loader`). This might be a poor way to do this (I know very little about native modules/externals). If you think so, I will look to find a better way.

**Comment by nklayman** [comment]
Electron-Webpack uses node loader as well. I think that they don't need the alias mapping becuase they use the recommended electron structure, while vcp-electron-builder has to use that of vue-cli. They might have some other setting that makes it work that I would love to implement, so let me know if you find anything.

**Comment by lspohn** [comment]
Hi! That solved the issue with Leveldown, great. Unfortunately, I get other bugs which are related to native dependencies.

I'll further investigate this. As the bugs don't happen with electron-webpack, I guess the webpack bundling might interfere with the dependencies.

If you can provide a workflow how to externalize specific dependencies manually, that would be great.

Thanks a lot for your help!

**Comment by nklayman** [comment]
Here is the config for electron-vue. It seems to be the same as what I have, although `__node` and `__dirname` are set to true, that could be the issue.
https://github.com/SimulatedGREG/electron-vue/blob/master/template/.electron-vue/webpack.renderer.config.js

**Comment by nklayman** [comment]
What do you think about injecting it into the `index.html`? This is what vue-electron and electron-webpack do.

**Comment by lspohn** [comment]
Hi!

I added the absolute path to node_modules via: config.resolve.modules.prepend(), and then tried to externalize all dependencies. Curiously, it still can't find the modules and throws an error.

This all is quite strange. I could get the app running with the aliasses, but had the drawback that I had to specify exact paths to the native builds - but they have to be changed when building for other platforms. Also, I still get strange errors within my app, while with electron-webpack all worked fine without any further config.

Maybe, adding the node-loader by default and provide a flag to externalize all dependencies listed in package.json (+ whitelists, siminar to electron-webpack), into you project would be great. Then users like me, which deal with various native depenencies, don't get the performance benefit of bundling everything but it should then work at least.

I didn't understand what you mean with injecting it into "index.html" - but if the others do it, I'd just copy it. Both other projects seem to be less good maintained. So I really appreciate the work you put into this!

**Comment by lspohn** [comment]
Ah, I tried - getting the error message:

> external "leveldown"?07eb:1 Uncaught ReferenceError: leveldown is not defined
>     at eval (external "leveldown"?07eb:1)
>     at Object.leveldown (app.js:20021)
>     at __webpack_require__ (app.js:725)

(my IDE also said, "Unresolved variable globalPaths")

This is my vue.config.js now.

`      chainWebpackRendererProcess: config => {
        config.module
          .rule('node-loader')
          .test(/\.node$/)
          .use('node-loader')
          .loader('node-loader')
        config.externals({leveldown: 'leveldown', sodium_native: 'sodium-native', grpc: 'grpc', node_sass: 'node-sass'})
        return config
      }`

Ideas? Thank you!

**Comment by nklayman** [comment]
Hmm, I'm not sure what's wrong. I should have the auto-externalization feature ready later today, so you can just wait for that.

**Comment by nklayman** [comment]
Use the node externals plugin as well for a temporary fix

**Comment by nklayman** [comment]
I'd rather not use that as it is faster to bundle of requiring

**Comment by nklayman** [comment]
I got it to work without the node-externals plugin. Just need to write tests and we're good.

**Comment by lspohn** [comment]
Very excited, I'll try it out quickly then!

**Comment by lspohn** [comment]
Hey!

Just tried it out!

I get the same error like in post 1. It seems to try to load the JS version of leveldown? When I add the "alias", it throws an error because node-loader is missing.

Did you include some script for loading the .node files which include the native binaries? (Or maybe: all the node files in node_externals so that I don't have to specify alias for each package)

Greetings and tanks! 👍

**Comment by nklayman** [comment]
Try creating a blank project with leveldown and the latest vcp-electron-builder. A blank project works fine for me. I am on Linux though, but will test with windows soon.

**Comment by lspohn** [comment]
Doesnt work either!

"Cannot find module 'leveldown'"

=> Yarn.lock doesn't include a loader for .node files. Is this missing?

**Comment by nklayman** [comment]
Make sure you invoke the generator of the github version. Create a fresh project and run `yarn add --dev nklayman/vue-cli-plugin-electron-builder` and then `vue invoke electron-builder` to make sure it invokes the latest version.

**Comment by lspohn** [comment]
Ok, I did so.

added leveldown to dependencies.

Then in main.js "import leveldown from 'leveldown'" to test it.

Still same error. Could be related to windows.

Installing native deps works and shows.

No errors with build!

There is no dependency to your package with looks like a node-loader. Maybe something is missing?

Btw: I would add the rebuild process to "postinstall". Rebuilding on every serve takes too much time.

we added in our package.json: "postinstall": "npm rebuild node-sass && yarn rebuild-deps"

**Comment by nklayman** [comment]
Can you send me the index.html after it gets compiled (use the sources tab in electron's devtools).

**Comment by lspohn** [comment]
On a fresh project, it works now!

But still not in my main project, where I merged all files generated in the fresh one. However, leveldown is there required in a library by a module itself. Still the error from above.

**Comment by nklayman** [comment]
Send me the compiled index.html of the existing project and run require('module'). globalPaths and send me the output.

**Comment by lspohn** [comment]
Here is the Error!

globalPaths = C:UserslcsspIdeaProjectsxxx-xxx-xxx↵ode_module

Seems a problem of String escaping.

I html:

<script>require('module').globalPaths.push('C:\Users\lcssp\IdeaProjects\xxx-xxx-xxx\node_modules')</script>

**Comment by nklayman** [comment]
Make sure your `index.html` has `<script>require('module').globalPaths.push('<%= VUE_APP_NODE_MODULES_PATH %>')</script><% } %>` in it. As of the latest [commit](e1e08c56b203ffd442c7b55ba9bb667c6beee4dc) (you may need to update) it replaces all `\`s with `/`s, fixing the character escaping problem.

**Comment by nklayman** [comment]
I also set `electron-builder install-app-deps` to be part of postinstall. If you have an existing postinstall script, it will be added on.

**Comment by lspohn** [comment]
Still not!

globalPaths is now:

C:/Users/lcssp/IdeaProjects/xxx-xxx-xxx/node_modules

But windows requires \ slashes!

**Comment by nklayman** [comment]
Forward slashes worked fine for me, try setting it manually with backslashes.

**Comment by nklayman** [comment]
1.0.0-rc.1 [has landed](https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v1.0.0-rc.1) with support for native modules. Remove any changes you made after added leveldown, upgrade to the latest version of vcp-electron-builder and re-invoke the generator. Then, leveldown should work fine. The generator will not effect any code other than adding the missing requirements for native modules.
