### ISSUE TITLE
Property 'Notification' does not exist on type 'Window'.

### ISSUE THREAD

**Issue by GanZhiXiong** [nklayman/vue-cli-plugin-electron-builder#526]
Error reported by running "yarn electron:build", as shown below
![image](https://user-images.githubusercontent.com/27394631/67175102-57fa3d80-f3f7-11e9-9713-c2c5aa59eba9.png)

Running "yarn electron:serve" was successful and the notification was displayed, so the code should be fine

**Comment by nklayman** [comment]
Try using `new Notification` instead of `new window.Notification` as per [mdn docs](https://developer.mozilla.org/en-US/docs/Web/API/notification).

**Comment by GanZhiXiong** [comment]
**Thank you for solving my problem!**

The sample code of electron Notification I saw is all using new window.Notification. Could you please solve the reason? Thank you very much!

**Comment by nklayman** [comment]
I'm not sure, the examples are probably just wrong. It works either way, but you just aren't supposed to use window.
