### ISSUE TITLE
I need a way to disable or configure Terser for production builds

### ISSUE THREAD

**Issue by njbrown** [nklayman/vue-cli-plugin-electron-builder#530]
**Is your feature request related to a problem? Please describe.**
I need a way to disable Terser or configure it. I am instantiating some classes by name and the plugin wrangles the class names or transforms the classes in such a way that I cant create them from a factory method I have here:

```
 public addNode<T extends DesignerNode>(
    name: string,
    displayName: string,
    type: { new (): T }
  ) {
    var factory = new DesignerNodeFactory();
    factory.name = name;
    factory.displayName = displayName;
    factory.create = (): DesignerNode => {
      return new type();
    };

    this.nodes[name] = factory;
  }
```

When I call the factory method `factory.create()` somewhere else in code I get this error:
![image](https://user-images.githubusercontent.com/1708550/67343605-63cf2800-f4fb-11e9-8ca3-c7ed5eae94bf.png)

I see the Terser plugin being added here but with no way to configure or not add it:
https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/master/index.js#L555

Is there a solution to this that I dont know about?

**Comment by nklayman** [comment]
See the [webpack configuration docs](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#webpack-configuration). You can use the `mainProcessChain` function to configure the main process webpack config. See the [webpack chain](https://github.com/neutrinojs/webpack-chain/tree/v4) docs for instructions on how to modify plugins.

**Comment by njbrown** [comment]
@nklayman Youre suggestion worked and I was able to disable the `uglify` plugin using this:
```
// vue.config.js

module.exports = {
	pluginOptions: {
		electronBuilder: {
			chainWebpackMainProcess: config => {
				config.plugins.delete("uglify");
			},
			chainWebpackRendererProcess: config => {
				config.plugins.delete("uglify");
			}
		}
	}
};

```

But it didn't solve the problem, sadly.

I changed the `target` in the `tsconfg.json` file from `esnext` to `es6` and that fixed things.

Thanks for the help.

**Comment by 1c7** [comment]
Thank!
I was wondering why this doesn't work
```
      chainWebpackMainProcess: config => {
        config.optimization.minimize(false);
        config.plugins.delete("uglify");
        return config
      },
```

This works!
```
config.plugins.delete("uglify");
```

now my src/background.js is not minify anymore
