### ISSUE TITLE
Please support electron 7

### ISSUE THREAD

**Issue by Auxxxxlx** [nklayman/vue-cli-plugin-electron-builder#533]
when I upgraded `electron` to v7.0.0: 
<img width="619" alt="截屏2019-10-2901 01 11" src="https://user-images.githubusercontent.com/55738135/67699808-b458f080-f9e7-11e9-9120-545dd6a0a8d6.png">

**Comment by nklayman** [comment]
That error is thrown by electron because the install failed. The plugin supports electron 7.0.0 just fine.
