### ISSUE TITLE
How do you debug using webstrom?

### ISSUE THREAD

**Issue by GanZhiXiong** [nklayman/vue-cli-plugin-electron-builder#535]
You can find webstrom debugging methods at this link(https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#debugging-with-vscode), but how does webstrom debug?

**Comment by vovchisko** [comment]
@GanZhiXiong I believe it should work the same way for Node & Chrome. https://twitter.com/vovchisko/status/1111972220224618496

Also, Electron has a Chrome DevTools. Isn't enough?

**Comment by camhart** [comment]
Chrome DevTools only works for the renderer process.  I need to debug the main/background process.

**Comment by vovchisko** [comment]
> Chrome DevTools only works for the renderer process. I need to debug the main/background process.

@camhart The main process is just a node process - you can debug it just like I did with WebStrom or like GanZhiXiong says with VS Code.

**Comment by funjobs** [comment]
Same question, how to debug the main process under webstrom?

**Comment by funjobs** [comment]
@GanZhiXiong 老哥你可以debug了嘛

**Comment by anatoly314** [comment]
Struggle with debugging the main process with WebStorm as well. It might be very helpful if somebody will record a short video on how to do it properly.

**Comment by NoahCardoza** [comment]
This might be helpful https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1053.

**Comment by Nisthar** [comment]
@vovchisko do i need to use `electron` command instead of the `vue-cli-service electron:serve` command?

**Comment by nklayman** [comment]
@Nisthar the `electron:serve` command will pass any CLI args to the `electron` command itself, so you shouldn't need to call `electron` directly.

**Comment by nklayman** [comment]
Also, there was a config posted here: https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1053#issuecomment-698816466 that should work. Can some people try it and report back if it works or not?

**Comment by nklayman** [comment]
The issue linked above was closed as a solution was found. Unless someone reports that the solution does not work, this issue will be closed.
