### ISSUE TITLE
build does not include all files.

### ISSUE THREAD

**Issue by travis5491811** [nklayman/vue-cli-plugin-electron-builder#539]
**Describe the bug**
Build was working fine. Then i added a npm module (`pdf-to-printer`) to my project and it included `SumatraPDF.exe` in it's dist folder. When running on Linux in development, everything is fine. After I build and install on windows, i get the following error while trying to use the feature that depends on `pdf-to-printer`

```
electron/js2c/asar.js:126 Uncaught (in promise) Error: ENOENT, SumatraPDF.exe not found in C:\Users\testuser\AppData\Local\Programs\testapp\resources\app.asar
    at createError (electron/js2c/asar.js:126)
    at module.(anonymous function) (electron/js2c/asar.js:194:23)
    at bundle.js:1
    at new Promise (<anonymous>)
    at t.exports (bundle.js:1)
    at Object.t.exports [as print] (bundle.js:1)
    at FileReader.<anonymous> (Main.vue:674)
    at Generator.next (<anonymous>)
    at i (asyncToGenerator.js:3)
    at a (asyncToGenerator.js:25)
```

I tried the following in my `vue.config.js` with no luck and the same error:
```
        extraFiles: {
          from: 'node_modules/pdf-to-printer/dist/SumatraPDF.exe',
          to: './resources/app.asar.unpacked/plugins/',
        },
```

In the above example, if i change "to" to `./resources/`, it adds the .exe to that directory but that doesn't make `pdf-to-printer` look for it there. I'm not sure what to do.

**Expected behavior**
If the app I build and all its features works in development, it should work in production. 

**Environment (please complete the following information):**
 - OS and version: Linux Mint 19.1
 - node version:  13.0.1
 - npm version: 6.12.0
 - vue-cli-plugin-electron-builder version : 1.4.0
 - electron version: 5.0.11
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 

**Additional context**

**Comment by travis5491811** [comment]
The following (from trial and error) worked:
```
...
extraFiles: {
  from: 'node_modules/pdf-to-printer/dist/SumatraPDF.exe',
  to: './resources/app/',
},
win: {
  icon: './src/assets/icons/icon256x256.png',
  asar: false,
  // asar: {
  //   smartUnpack: true,
  // },
  // asarUnpack: ['node_modules/pdf-to-printer/dist/'],
},
```


The above solution results in the following warning:
`asar using is disabled — it is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available`

How do i accomplish what i did, by using asarUnpack? When i tried asarUnpack (see commented out), the program was still trying to find `SumatraPDF.exe` inside `resources\app.asar`

**Comment by nklayman** [comment]
Try this:
```js
// vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
        extraFiles: {
          from: 'node_modules/pdf-to-printer/dist/SumatraPDF.exe',
          to: './resources/app.asar.unpacked/SumatraPDF.exe'
        }
      }
    }
  }
}
```

**Comment by travis5491811** [comment]
> ```js
>         extraFiles: {
>           from: 'node_modules/pdf-to-printer/dist/SumatraPDF.exe',
>           to: './resources/app.asar.unpacked/SumatraPDF.exe'
>         }
> ```

When i tried the above and no `asar` options set, i got the same error message (`electron/js2c/asar.js:126 Uncaught (in promise) Error: ENOENT, SumatraPDF.exe not found in C:\Users\testuser\AppData\Local\Programs\testapp\resources\app.asar`). It seems like whatever i do the app is always looking for the resource in `....resources\app.asar...` unless i set `asar` to false.

**Comment by nklayman** [comment]
I found the issue in pdf-to-printer:
https://github.com/artiebits/pdf-to-printer/blob/265a1c2bf3d916a24c779bea554da1e12ce49b03/src/electron-util.js#L10
It checks to see if the app is using an asar by looking at `process.mainModule.filename`. Due to https://github.com/electron/electron/issues/12163, this is incorrect when using a custom protocol (which is required for vue cli modern mode). Possible solutions:

1. Try fixing `process.mainModule.filename`: https://github.com/electron/electron/issues/12163#issuecomment-372181432
2. Disable the custom protocol (and vue cli modern mode): https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#changing-the-file-loading-protocol (run builds with the `--legacy` argument).

This can't be solved by this plugin, so I will close the issue.
