### ISSUE TITLE
Installing a plugin via Vue CLI UI

### ISSUE THREAD

**Issue by theharshin** [nklayman/vue-cli-plugin-electron-builder#54]
**Describe the bug**
I've installed this plugin via the UI. The plugin installed successfully but I was not able to see the npm scripts added in package.json. 

**To Reproduce**
Install the plugin via vue ui

**Environment (please complete the following information):**
 - OS and version: macOS Mojave
 - Node version: 10.6.0
 - npm version: 6.2.0
 - vue-cli-plugin-electron-builder version : 1.0.0-beta.8

**Comment by nklayman** [comment]
When I installed it via the ui, the scripts showed up fine. Can you elaborate more on your issue? I'm not sure exactly what you mean.
