### ISSUE TITLE
When to support electron 7.x.x?

### ISSUE THREAD

**Issue by xland** [nklayman/vue-cli-plugin-electron-builder#540]
When to support electron 7.x.x?

Thanks!

When I run command
`vue add electron-builder`
It just has electron selection 5.0.0 6.0.0

**Comment by nklayman** [comment]
This will be part of the 2.0.0 release as it requires a breaking change (upgrading spectron). You can try it now by running `yarn add -D vue-cli-plugin-electron-builder@alpha electron@^7.0.0`.

**Comment by xland** [comment]
So when the 2.0.0  will  be published
@nklayman
