### ISSUE TITLE
`electron .` not working -- need a command for `npm run electron:start`

### ISSUE THREAD

**Issue by patarapolw** [nklayman/vue-cli-plugin-electron-builder#541]
**Describe the bug**
`electron .` not working, because `"main": "background.js",`.

Solution is pointing `npm run electron:start` to `"electron dist_electron/bundled/background.js",`

Why? Because `npm run electron:start` should startup faster than `npm run electron:serve`.

**Environment (please complete the following information):**
 - OS and version: macOS Mojave 10.14.6
 - node version: v10.16.0
 - npm version: 6.12.0
 - vue-cli-plugin-electron-builder version : 1.4.0
 - electron version: 6.1.4
 - other vue plugins used: vuetify, pug
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: (pending) <https://github.com/patarapolw/my-notes>

**Additional context**
Also planned to add PouchDB via <https://github.com/nolanlawson/pouchdb-electron>.

**Comment by nklayman** [comment]
To launch using the development version of the main process, run `electron ./dist_electron`. To run the packaged version, run `./dist_electron/mac_unpacked/APPNAME` (without electron).

**Comment by patarapolw** [comment]
Both are not working.

Still, I found my solution -- `"start": "open ./dist_electron/mac/$npm_package_name.app"`. Of course, I don't know what the answer for Windows would be.
