### ISSUE TITLE
import or require doesn't working in worker.js

### ISSUE THREAD

**Issue by marctwen** [nklayman/vue-cli-plugin-electron-builder#545]
**Describe the bug**
Look at the headline.

**To Reproduce**
in `backround.js`:

>webPreferences: {
      nodeIntegration: true,
      nativeWindowOpen: true
 }

in any vue component `mounted()` hook:
> new Worker('/workers/worker.js')

in `worker.js`

> const moduleName= require('module');

or

> import moduleName from 'module';

or

> const moduleName = window.require('module');

**Expected behavior**
Errrors:
`Uncaught ReferenceError: require is not defined at worker.js:1`
or
`worker.js:1 Uncaught SyntaxError: Cannot use import statement outside a module`
or
`Uncaught ReferenceError: window is not defined at worker.js:1`

**Environment (please complete the following information):**
 - OS and version: Windows 10 Build 18362
 - node version: 12.3.1
 - npm version: 6.11.2
 - vue-cli-plugin-electron-builder version : 1.4.0
 - electron version: 7.1.0
 - custom config for vcp-electron-builder:

**Comment by nklayman** [comment]
See https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/486#issuecomment-534968789 for guide on using web workers. I think this may solve your issue as well: https://electronjs.org/docs/tutorial/multithreading#multi-threaded-nodejs.
