### ISSUE TITLE
Electron 5 & 6 errors

### ISSUE THREAD

**Issue by ronssij** [nklayman/vue-cli-plugin-electron-builder#547]
Electron 5 has this error when running `npm run electron:serve`
Electron 6 not launching Electron window but no errors

**To Reproduce**
- vue create my-app
- vue add electron-builder (then choose between electron 5 and 6) which I end choosing v.4

**Expected behavior**
Electron 5 &  6: It will run an electron window with no errors.

**Screenshots**
Electron 5: http://prntscr.com/pvnfqf
Electron 6: http://prntscr.com/pvnhy1 - This does not open an electron window

**Environment (please complete the following information):**
 - OS and version: Windows 10 Pro
 - node version: v12.8.1
 - npm version: 6.9.2
 - yarn version (if used):  N/A
 - vue-cli-plugin-electron-builder version : 
 - electron version: both 5 & 6
 - other vue plugins used: None
 - custom config for vcp-electron-builder:  None
 - (if possible) link to your repo:

**Comment by No3x** [comment]
I don't have much expertise with this tools but were surprised you have such an issue because I just set up project with a similar env but do not have this errors.

- OS and version: Windows 10 Pro
- node version: v11.10.1
- npm version: 6.8.0
- yarn version (if used): N/A
- vue-cli-plugin-electron-builder version: 1.4.1
- electron version: both 6
- other vue plugins used: None
- custom config for vcp-electron-builder: None

I guess the error is already included after `vue create my-app`. Does `npm run serve` work after this step?
Make sure to use vue-cli v3.
```cmd
npm uninstall -g @vue/cli
npm i -g @vue/cli@^3
```

**Comment by nklayman** [comment]
A common issue is electron fails to download correctly. Try removing node_modules and reinstalling. The registerdtandardschemes issue is caused when switching between electron versions with a breaking change. Try reinvoking the generator with `vue invoke electron-builder`.

**Comment by ronssij** [comment]
@No3x on that issue `npm run serve` does not work.
I tried using Electron v 4.x instead seems to be working perfectly fine on my end.
I will try all your suggestion today, Hope I can get the latest version of the electron.
Thanks

**Comment by ronssij** [comment]
I found what causes the electron builder to not work.
what I did was create a two project.

**Project One**
- `vue create project-one` 
- `vue add electron-builder`
- `npm run electron:serve` - **_This is working as expected with electron v6.x_**
- `vue add vuetify`
- `npm run electron:serve` - **_Electron is not working anymore_**

**Project Two**
- `vue create project-two`
- `vue add vuetify`
- `npm run serve` - **_This is working as expected on the browser_**
- `vue add electron-builder`
- `npm run electron:serve` - **_Electron is not working here**

**Comment by nklayman** [comment]
My guess is that your electron cache is corrupted. Try removing `node_modules` and `%LOCALAPPDATA%/electron/Cache` and reinstalling deps.

**Comment by ronssij** [comment]
It works now. I deleted the electron cache folder as what you have said.
and created a new project folder.
