### ISSUE TITLE
electron console error: Not allowed to load local resource: file://./index.html

### ISSUE THREAD

**Issue by bruceauyeung** [nklayman/vue-cli-plugin-electron-builder#550]
**Describe the bug**
https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#changing-the-file-loading-protocol
says we can revert back to file protocol using `customFileProtocol`, so i followed this guide, modified `vue.config.js` and `background.ts` as this guide suggested, but unfortunately that error comes.
i even tried build electron app with `--legacy` flag, but still got no luck.

**Expected behavior**
works well just like `app` protocol.

**Environment (please complete the following information):**
 - OS and version: centos 7 64bit
 - node version: 12.4.0
 - npm version: 6.9.0
 - yarn version (if used):  1.19.0
 - vue-cli-plugin-electron-builder version : 1.4.0
 - electron version: 6.0.12
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
~~~
  pluginOptions: {
    electronBuilder: {
      customFileProtocol: 'file://./',
      externals: ['ffi', 'ref', 'ref-struct', 'ref-array'],
      builderOptions: {
        asar: false,
        //asarUnpack: ['**/static/*'],
        extraFiles: ['webcontents'],
        extraResources: ['workbench.asar', 'preloads'],
        files: ['**/*', 'build/*.node'],
        //nodeGypRebuild: true,
        //buildDependenciesFromSource: true,

      }
    }
  }
~~~
 - (if possible) link to your repo: 

**Additional context**
i am wondering what exactly `customFileProtocol` mean, if `customFileProtocol` used,  the electron application still use ES6 `type="module"` to load scripts?

**Comment by nklayman** [comment]
To use the file protocol, use ``win.loadURL(`file://${__dirname}/index.html`)`` in your `background.js`, and `./` as the `customFileProtocol`. I will update the docs as they are incorrect.
