### ISSUE TITLE
uncaught Error: Could not find module root given file: "app://./js/chunk-vendors.a960702b.js". Do you have a `package.json` file?

### ISSUE THREAD

**Issue by bruceauyeung** [nklayman/vue-cli-plugin-electron-builder#553]
**Describe the bug**
stacktrace:
>Uncaught Error: Could not find module root given file: "app://./js/chunk-vendors.a960702b.js". Do you have a `package.json` file? 
    at Function.getRoot (bindings.js:211)
    at bindings (bindings.js:82)
    at Object.0e66 (ref.js:5)
    at __webpack_require__ (bootstrap:84)
    at Module.cd49 (app.f8c3ff0a.js:1)
    at __webpack_require__ (bootstrap:84)
    at Object.0 (app.f8c3ff0a.js:1)
    at __webpack_require__ (bootstrap:84)
    at checkDeferredModules (bootstrap:45)
    at bootstrap:221

i am using ffi/ref/ref-struct/ref-array modules.

file system structure for app directory( app.asar unpacked)
~~~
|-- omitted...
|-- js
|   |-- omitted...
|   |-- chunk-vendors.a960702b.js
|   `-- chunk-vendors.a960702b.js.map
|-- node_modules
|   |-- bindings
|   |-- omitted...
`-- package.json
~~~
i dived inside `bindings` module's code, and it seems only support regular file system path and `file://` prefixed URIs but lack of supporting this kind of customized  protocol such as `app`.

currently i know a way to get rid of the error: customize `node-bindings` and let it know how to handle `app` protocol, but i don't think it's elegant.

any suggestion?

**Environment (please complete the following information):**
 - OS and version: centos 7 64bit
 - node version: 12.4.0
 - npm version: 6.9.0
 - yarn version (if used):  1.19.0
 - vue-cli-plugin-electron-builder version : 1.4.0
 - electron version: 6.0.12
 - other vue plugins used: 
 - custom config for vcp-electron-builder:

**Comment by nklayman** [comment]
Can you give me a code snippet that throws the error? I'm not sure how to reproduce it.
