### ISSUE TITLE
renderer path.resolve output disk path at windows system

### ISSUE THREAD

**Issue by Liupeng8** [nklayman/vue-cli-plugin-electron-builder#554]
**Describe the bug**
renderer path.resolve output disk path at windows7 system

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: windows 7
 - node version: 12.1.0
 - npm version:6.9.0
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 1.4.1
 - electron version: 6.1.4
 - other vue plugins used: vue.js:2.6.10
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**
![1573894682(1)](https://user-images.githubusercontent.com/23046680/68990788-44c17d00-0892-11ea-832b-02c06e281ff4.jpg)

![1573894736(1)](https://user-images.githubusercontent.com/23046680/68990800-628ee200-0892-11ea-9eca-2488ffbc6086.jpg)

because the path of the path.resolve output has a problem, the route can not be used normally, please help me find the problem, thank you very much.

**Comment by nklayman** [comment]
That is the expected behavior of [path.resolve](https://nodejs.org/api/path.html#path_path_resolve_paths). It is designed to return a file's full path relative to the cwd. You will have to use another technique for router paths.
