### ISSUE TITLE
Support Electron 7

### ISSUE THREAD

**Issue by ethernomad** [nklayman/vue-cli-plugin-electron-builder#555]
Electron 7 has been released:

https://electronjs.org/releases/stable

**Comment by ethernomad** [comment]
Actually - it is supported - it's just not in the wizard.

**Comment by xland** [comment]
No. It is not supported.
See #540  #546

**Comment by nklayman** [comment]
Electron 7 works fine with this plugin (except for https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/546, but that is quite minor). I don't have it available in the wizard because of issues with spectron. Feel free to use it in you apps (as long as you aren't using spectron).

**Comment by xland** [comment]
Thanks

**Comment by pacific202** [comment]
How do you enable Electron v7?  Is it just a matter of installing with v6 then changing the electron entry in package.json and running `npm install`?

**Comment by nklayman** [comment]
Yep, as long as you don't use spectron that works fine.

**Comment by bluelovers** [comment]
is `spectron` mean `vue-cli-service electron:serve` ?

**Comment by nklayman** [comment]
No, spectron is a e2e testing framework for electron.

**Comment by hgt803** [comment]
throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')

https://github.com/electron/electron/issues/20994#issuecomment-566884880

**Comment by AlexSHoffman** [comment]
@nklayman please keep in mind Electron 7.x no longer uses the `electron.asar` file. Perhaps some changes will need to be made in `vue-cli-plugin-electron-builder` to adapt to that change.

Also, do you have a specific date in mind for the release of 2.0.0 (that supports Electron 7.x)?

**Comment by hgt803** [comment]
> @nklayman please keep in mind Electron 7.x no longer uses the `electron.asar` file. Perhaps some changes will need to be made in `vue-cli-plugin-electron-builder` to adapt to that change.
> 
> Also, do you have a specific date in mind for the release that supports Electron 7.x (which is gonna be `2.0.0` I assume) or at least an approximate date?

i fix it use `yarn upgrade`

**Comment by nklayman** [comment]
[v2.0.0 beta](https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-beta.0) supports electron 7.
