### ISSUE TITLE
Could somebody write a document about the win-unpacked files?

### ISSUE THREAD

**Issue by xland** [nklayman/vue-cli-plugin-electron-builder#557]
What are Files in `dist_electron\win-unpacked` folder for?
Can I use them to debug my product?
Could somebody write a document about the `win-unpacked` files?
I don't found docs about them in electron-builder's documents.

Thanks

**Comment by nklayman** [comment]
The win-unpacked folder is all of the electron files and your web code that get packaged into the nsis installer. You can run you application without installing it from `dist_electron/win-unpacked/APP_NAME.exe`.

**Comment by xland** [comment]
Thanks
