### ISSUE TITLE
Failing build exits with code 0

### ISSUE THREAD

**Issue by WalternativE** [nklayman/vue-cli-plugin-electron-builder#558]
**Describe the bug**
When building the electron app and the bundling part fails (because of TS compilations or other errors in this region) the process finishes with a success exit code (0). For a failing build I'd expect the resulting exit code to indicate a failure.

**To Reproduce**
- Install newest vue cli `npm install -g @vue/cli`
- Create a minimal hello world template `vue create hello-word`
- Choose the standard configurations for eslint + prettier, babel, typescript, jest and npm
- Add the electron builder extension `vue add electron-builder`
- Edit the `index.ts` file in a way that forces a TS compile error (like writing 'Mary had a little lamb' somewhere in verbatim)
- Execute a standard bundle build `npm run build` this should finish with exit code 1
- Execute a electron build `npm run electron:build` this will finish with exit code 0

**Expected behavior**
I would expect that both a normal bundle build as well as the electron build exit with a failure exit code.

**Screenshots**
Normal bundle build exiting with code 1
![image](https://user-images.githubusercontent.com/5071748/69142675-943cbe80-0ac7-11ea-9bdd-83b1bbb0a8e2.png)

Electron build exiting with code 0
![image](https://user-images.githubusercontent.com/5071748/69142734-b46c7d80-0ac7-11ea-8cfa-ebdf5cbded5c.png)

**Environment (please complete the following information):**
 - OS and version: Windows 10 (1909) also reproduced on docker image `electronuserland/builder:wine`
 - node version: 12.13.0
 - npm version: 6.11.3
 - vue-cli-plugin-electron-builder version : 1.4.1
 - electron version: 6.0.0 or 5.0.4
 - other vue plugins used: babel, eslint, typescript, jest
 - (if possible) link to your repo: https://github.com/WalternativE/VueElectronBuildRepro

**Comment by nklayman** [comment]
Thanks for the report! Fixed in v1.4.2.

**Comment by WalternativE** [comment]
Works like a charm. Thanks for the fix! 🙇‍♂️
