### ISSUE TITLE
testWithSpectron is not a function

### ISSUE THREAD

**Issue by onekiloparsec** [nklayman/vue-cli-plugin-electron-builder#559]
**Describe the bug**
It is impossible to import `testWithSpectron` in the tests.

It must be something with babel, I am sorry, I can't find where exactly.

**To Reproduce**
Take the exact same code of the test example in the doc, starting with `const { testWithSpectron } = require(...` and running the test with Jest.

**Expected behavior**
The test should start

**Environment (please complete the following information):**
 - OS and version: Ubuntu 16
 - node version: 10.17
 - npm version: 6.11
 - vue-cli-plugin-electron-builder version : 1.4.2
 - electron version: 7.1.2 but also 5.x and 6.x
 - other vue plugins used: @vue/cli-plugin-babel, @vue/cli-plugin-eslint, @vue/cli-plugin-unit-jest, 
 - custom config for vcp-electron-builder: none

**Comment by nklayman** [comment]
Can you please post your jest config?

**Comment by onekiloparsec** [comment]
```
module.exports = {
  moduleFileExtensions: ['js', 'jsx', 'json', 'vue'],
  transform: {
    '^.+\\.vue$': 'vue-jest',
    '.+\\.(css|styl|less|sass|scss|svg|png|jpg|ttf|woff|woff2)$':
      'jest-transform-stub',
    '^.+\\.jsx?$': 'babel-jest'
  },
  transformIgnorePatterns: ['/node_modules/'],
  moduleNameMapper: {
    electron: '<rootDir>/tests/unit/mocks/electronMock.js',
    plotly: '<rootDir>/tests/unit/mocks/plotlyMock.js',
    '^@/analyses/\\${this.analysisComponentName}.vue$':
      '<rootDir>/src/analyses/PeakAnalysis.vue',
    '^@/assets/img/(.*)$': '<rootDir>/tests/unit/mocks/imageFileMock.js',
    '^@/(.*)$': '<rootDir>/src/$1',
    '^#/(.*)$': '<rootDir>/tests/unit/$1'
  },
  snapshotSerializers: ['jest-serializer-vue'],
  testMatch: [
    '**/tests/unit/**/*.spec.(js|jsx|ts|tsx)|**/__tests__/*.(js|jsx|ts|tsx)'
  ],
  testURL: 'http://localhost/',
  watchPlugins: [
    'jest-watch-typeahead/filename',
    'jest-watch-typeahead/testname'
  ],
  collectCoverageFrom: [
    '**/src/**/*.{js,vue}',
    '!**/node_modules/**',
    '!**/src/assets/**',
    '!**/src/directives/*.js',
    '!**/src/*.js',
    '!**/dist_electron/**'
  ],
  coverageReporters: ['lcov', 'text', 'text-summary', 'html'],
  coverageDirectory: 'coverage',
  testResultsProcessor: './node_modules/jest-html-reporter',
  globals: {
    __static: './public'
  }
}
```

**Comment by nklayman** [comment]
Try using `const testWithSpectron = require('vue-cli-plugin-electron-builder/lib/testWithSpectron')`

**Comment by nklayman** [comment]
If that doesn't work, please post your babel config as well.

**Comment by onekiloparsec** [comment]
Thanks for your help. I found the cause of not being able to use `testWithSpectron`. That's the line `   electron: '<rootDir>/tests/unit/mocks/electronMock.js',` in the `moduleNameMapper` of the `jest.config.js` file (as shown above). 

When removed, I get access to the `testWithSpectron` function. It would be interesting to know how to get both working at the same time (i.e. with the mock path, but not for the spectron tests).

But then, somehow, I can't have a browser window. The basic test as per the documentation of your plugin gives:

```
: Timeout - Async callback was not invoked within the 30000ms timeout specified by jest.setTimeout.
Error: Timeout - Async callback was not invoked within the 30000ms timeout specified by jest.setTimeout.
```

When trying with the standard "Window Loads Properly" test in the Spectron documentation I get 

```Error: Client initialization failed after 10 attempts: RuntimeError Client initialization failed after 10 attempts: 
Error: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
```

But that's related to Chromium (I managed to get other error message by providing the remote debug port to the ChromeDriver arguments, but anyway. Maybe that's because I am on a Ubuntu VM sitting on top of a Windows 10 OS?

**Comment by nklayman** [comment]
Try creating a fresh project and adding tests to that. If the fresh project works, you can look for differences between the jest configs of the project. Spectron should work fine on a Ubuntu vm, maybe try `rm`ing `node_modules` and reinstalling deps.
