### ISSUE TITLE
how to use webpack native Modules

### ISSUE THREAD

**Issue by roy2651** [nklayman/vue-cli-plugin-electron-builder#560]
**Describe the bug**

First,great work!
I'm using this project and [zoom-electron-sdk](https://github.com/zoom/zoom-sdk-electron) as a videomeeting project. but when I import zoom-electron-sdk's lib and sdk to new project,
when I npm run dev It's so much warning such as this
in ./src/electron/services/meet/sdk/mac/ZoomSDK/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/bgr_mac.mlmodelc/enc.net

Module parse failed: Unterminated string constant (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

**To Reproduce**
1.copy zoom-electron-sdk to project
2.import ZOOMSDKMOD from './lib/zoom_sdk.js'
3.npm run dev

**Expected behavior**
how to solve this warning I try __non_webpack_require__(zoomnodepath) in lib/zoom_sdk.js
it no work
and I add externals my app path , it no  work

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: macos
 - node version: 10.15.3
 - npm version:6.4.1
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : latest
 - electron version: 5.0.2

**Additional context**

**Comment by nklayman** [comment]
Did you try marking the module as an external?

```js
// vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['zoomnodepath'],
    }
  }
}
```

**Comment by roy2651** [comment]
hi nklay：
this can use ok。
but I have anthoer question about build my app.
electron-zoom-sdk build use  electron-packager and in package.json has a sctrip named packager-mac
it do many steps when build app
in our project ，in package.json just have   "build": "vue-cli-service electron:build --legacy" so I wonder know how to change code like zoom-electron-sdk when build app
hope to your reply
thank you 
sorry for my English it‘s not my native language

**Comment by nklayman** [comment]
You shouldn't need to change the command at all, the default electron:build command should work just fine. The configuration in the extra arguments of the packager-mac is unnecessary with this plugin as it is already set for you.

**Comment by nklayman** [comment]
Does it work in both build and dev now? If so, please close this issue.

**Comment by roy2651** [comment]
thanks
