### ISSUE TITLE
Getting Started Tutorial - How to Access Vue from background.js

### ISSUE THREAD

**Issue by rj-ib-23** [nklayman/vue-cli-plugin-electron-builder#562]
**Getting Started Tutorial - How to Access Vue from background.js**
Hello, I'm new to VueJS
Thanks for the great package and also the tutorial. 
I have a quick question.
* It is not clear weather we can access the Vue instance and it's data from background.js
* it would be great if the tutorial can be updated to state if this is possible and if possible how to achieve it. 
* also it seems the java script in the vue component files do no have access to the Vue instance
* reference: https://codingexplained.com/coding/front-end/vue-js/accessing-vue-instance-outside-declaration
* above reference does not seem to work

**Comment by AssetKid** [comment]
This plugin works with projects created using vue-cli 3.x and higher (See README).

https://cli.vuejs.org/

From the link in your post, it seems like you are using Vue from a CDN (JSDelivr, unpkg etc).
```js
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
```

**Comment by rj-ib-23** [comment]
Hello, maybe the description is unclear... I used vue-cli (vue create myproject) to create my project. So that is not the problem.

Once I create an app  in main.js I have
`var vm=new Vue({
  i18n,
  render: h => h(App),
  data:{
    data_msg:"hello"
  }
}).$mount('#app')`

and I have helloWorld.vue where I want to access vm variable created so that I can access the data.

Once I build the app using npm run electron:build I get an error vm is undefined when I try to use it.

**Comment by AssetKid** [comment]
There are better ways to do that. Use Vuex, an event bus or props.

**Comment by nklayman** [comment]
Since the Vue instance is in a completely separate process than the main process, you will have to use [ipc channels](https://electronjs.org/docs/api/ipc-main). Send a message from the main process (background.js) to the renderer process (your .vue files), and add a listener in the renderer process that does something to the vue instance
