### ISSUE TITLE
Sporadic image popping

### ISSUE THREAD

**Issue by Christilut** [nklayman/vue-cli-plugin-electron-builder#563]
**Describe the bug**
I have a small (4kb) PNG image in my app, but sometimes it has a short delay when loading and you see it pop into the screen slightly after the page is displayed.

I've tried putting this png file in my `public` folder and my `assets` folder but the problem is the same in both cases.

The only workaround I have to completely prevent this image popping is to use the base64 string in the img src tag.

**To Reproduce**
It's a bit hard to reproduce, it seems to happen randomly after using the app for a while. I can't really reproduce it on demand. During development of other features I just notice it sometimes.

**Expected behavior**
I would expect images to be loaded instantly since this is an electron app and no network is required to load the image.

**Environment (please complete the following information):**
 - OS and version: Windows 10
 - node version: 12.x
 - npm version: 6.x
 - vue-cli-plugin-electron-builder version : 1.4.0
 - electron version: 6.0.0

**Comment by nklayman** [comment]
This is expected. Even though it doesn't have to make a network request, it still has to read the file from the filesystem which has a small delay. It also doesn't start loading the image until vue has initialized. You could try waiting for the [ready-to-show](https://electronjs.org/docs/api/browser-window#using-ready-to-show-event) event before making the window visible.

**Comment by Christilut** [comment]
Hmm but what is happening is that this happens when navigating from one page to another. So the window has long ago initialized and so has Vue.

**Comment by nklayman** [comment]
It still takes time to read the image from the filesystem and display it. You can look into ways to preload the image or have an animation while switching between pages that gives the images time to load.

**Comment by Christilut** [comment]
Alright thanks. I thought this wouldn't be such a problem with electron :/

**Comment by Christilut** [comment]
Actually I'm noticing that image popping doesn't happen at all with 6kb SVG files but with 6kb PNG files it does happen. Both are stored in the public folder.
Any idea why? 
Maybe this is a question for the electron repo, not sure how the vue builder ties in here exactly.

**Comment by nklayman** [comment]
Yeah, you should probably open an issue on the electron repo. See if you can reproduce it w/out using vue.
