### ISSUE TITLE
Blank page when I build the app! please help

### ISSUE THREAD

**Issue by ouahibAbdou** [nklayman/vue-cli-plugin-electron-builder#564]
Blank page when I build the app but in the dev mode it's working...

**Comment by nklayman** [comment]
Try [this](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#blank-screen-on-builds-but-works-fine-on-serve). If it doesn't work, please open a new issue that follows the bug report template.
