### ISSUE TITLE
Could not find module electron-v5.0-win32-x64\node_sqlite3.node

### ISSUE THREAD

**Issue by techuila** [nklayman/vue-cli-plugin-electron-builder#565]
I tried building my app on my mac to windows by the command `vue-cli-service electron:build --windows` 
But after running it on a windows environment, it doesn't have sqlite3 on a windows platform, it only has for its own environment which is darwin. How do I solve this?

**Comment by nklayman** [comment]
When I build it, it has the bindings for windows as well. Can you install the `asar` package (`yarn global add asar`) and run `asar extract ./dist_electron/win-unpacked/resources/app.asar ./asar` and then send me the results of `ls asar/node_modules/sqlite3/lib/binding`.

**Comment by techuila** [comment]
@nklayman  Sorry for the late response. I found a workaround, I compiled the app on a windows env and copied the 3 folders. Compiling from my mac would only generate electron-v5.0-darwin-x64 and nodev72-darwin-x64.
![image](https://user-images.githubusercontent.com/15911107/71875042-5de1fe00-315e-11ea-9dc6-5e8bb356747a.png)

So everytime I compile it on my mac, I just copy and paste it on the node_modules/sqlite3/lib/binding.

Someone told me that Sqlite3 is a platform dependent, that I should compile it on a target os. But from what you said, it should build bindings also for windows compiled from a mac?

**Comment by nklayman** [comment]
The module building process is handled by electron-builder, which should build the bindings for all platforms. If it doesn't, you should open an issue on [their repo](https://github.com/electron-userland/electron-builder). Since this problem is not related to the plugin (as far as I can tell), I am going to close this.
