### ISSUE TITLE
Use default app Protocol, Vue axios  http is not working

### ISSUE THREAD

**Issue by Siffre** [nklayman/vue-cli-plugin-electron-builder#567]
** question **

![image](https://user-images.githubusercontent.com/12948798/69728190-fac47b00-115e-11ea-86c5-6893d5977e44.png)

build electron

![image](https://user-images.githubusercontent.com/12948798/69728369-4c6d0580-115f-11ea-9e0a-15aa2d483282.png)

http is not working, please help me, thank you!

**Comment by nklayman** [comment]
Please open a new issue that follows the bug report template.
