### ISSUE TITLE
Use default app Protocol, Vue axios http is not working 

### ISSUE THREAD

**Issue by Siffre** [nklayman/vue-cli-plugin-electron-builder#568]
**Describe the bug**
![image](https://user-images.githubusercontent.com/12948798/69769748-1ceee500-11c1-11ea-88e5-b4c1a11f312c.png)

Development is good, but to build is bad
![image](https://user-images.githubusercontent.com/12948798/69769757-28421080-11c1-11ea-85be-6efc19e308b5.png)

**To Reproduce**

**Expected behavior**
Vue axios http server is good

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: macOS
 - node version:  12.7.0
 - npm version: 6.10.0
 - yarn version (if used):  
 - vue-cli-plugin-electron-builder version :  1.4.2
 - electron version: 6.1.5
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**

**Comment by nklayman** [comment]
Please provide a code snippet of the axios request. I need to know what request is throwing the error.
