### ISSUE TITLE
Cannot find builderOptions key in the project

### ISSUE THREAD

**Issue by omarAbdelhadyok** [nklayman/vue-cli-plugin-electron-builder#569]
Cannot find any builderOptions keys in the project or any configurations to add Electron configs

![Screenshot (6)](https://user-images.githubusercontent.com/50325015/69798872-402a8c00-11e3-11ea-9926-98e0d14cb1f2.png)

 - vue-cli-plugin-electron-builder version : 1.4.1
 - electron version: 6.0.0

This line in the docs is not clear
Electron-builder's config is now taken from the builderOptions key in vue-cli-plugin-electron-builder's plugin options.

**Comment by FawzyZayed** [comment]
try this just create Vue config file in root directory name it : 
vue.config.js

**Comment by omarAbdelhadyok** [comment]
oh was not added in the project by default, after adding it, works correctly

**Comment by nklayman** [comment]
Closing as issue has been resolved, thanks @FawzyZayed.
