### ISSUE TITLE
failed to import module in background.ts

### ISSUE THREAD

**Issue by bruceauyeung** [nklayman/vue-cli-plugin-electron-builder#570]
vue-cli-plugin-electron-builder: 1.4.1
electron-builder: 21.2.0
typescript:3.5.3

**Describe the bug**
error:
> ERROR  Failed to compile with 1 errors                                                                              6:47:38 PM
This dependency was not found:
\* @/components/Workbench/B in ./src/components/Workbench/A.ts
To install it, you can run: npm install --save @/components/Workbench/B

dependency chain:
`background.ts` depends `A.ts`,
`A.ts` depends `B.ts`

`src/background.ts` file content:
~~~
...
import a from './components/Workbench/A';
logger.debug(a.toString());
...
~~~
`src/components/Workbench/A.ts` file content:
~~~
import b from '@/components/Workbench/B';
const a = 0;
export default b;
~~~
`src/components/Workbench/B.ts` file content:
~~~
const b = 0;
export default b;
~~~

but if i change `A.ts`'s contents to the following, it works :
~~~
import b from './B';
const a = 0;
export default b;
~~~

tsconfig.json contents:
~~~
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "webpack-env",
      "jest"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx",
    "preloads/**/*.ts",
    "preloads/**/*.tsx",
  ],
  "exclude": [
    "node_modules"
  ]
}
~~~

**Comment by Molunerfinn** [comment]
Me too. `Webpack alias` && `tsconfig.compilerOptions.paths` seems not working in `background.ts`

**Comment by Molunerfinn** [comment]
OK I have found the solution:

![image](https://user-images.githubusercontent.com/12621342/70110143-f7624f80-1688-11ea-8773-3d4f682217ca.png)

See the docs: https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#webpack-configuration

**Comment by bruceauyeung** [comment]
@Molunerfinn  thanks for your tips and i tried but your solution doesn't work for me, neither in the case of `yarn electron:serve --debug` nor `yarn electron:build`

**Comment by bruceauyeung** [comment]
@nklayman is it a bug or by design ?

**Comment by nklayman** [comment]
As of v1.4.2 `@` is aliased to `src`. If you upgrade to that version it should work.
https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/master/index.js#L587
