### ISSUE TITLE
Windows jumping out continully when testing app with spectron（on Electron 6.1.5）

### ISSUE THREAD

**Issue by xland** [nklayman/vue-cli-plugin-electron-builder#573]
Windows 10
Electron 6.1.5
Test Framework: Mocha

when testing the app with spectron,Windows jumping out continully
```js
const { testWithSpectron } = require('vue-cli-plugin-electron-builder')
const assert = require('assert');

describe('开始加载应用', async function () {
    const { stdout, url, stopServe, app } = await testWithSpectron()
    console.log(`electron:serve returned: ${stdout}`)
    console.log(`the dev server url is: ${url}`)
    it('此方法应该返回一个ul字符串', async () => {
        let count = await app.client.getWindowCount();
        assert.strictEqual(count, 1);
    });
    await stopServe()
})
```
![image](https://user-images.githubusercontent.com/2980915/69840791-bdafd400-1297-11ea-8ba4-0a6a0477aca8.png)

If I set `testWithSpectron({noSpectron: true})`
No window will be opened, and test method is just waiting `app.client.getWindowCount()`

**Comment by xland** [comment]
I don't think this is a issue of  `vue-cli-plugin-electron-builder`
So I close it.

**Comment by nklayman** [comment]
I believe the issue is caused by a spectron/electron version mismatch. Since spectron is a dep of the plugin, I can't change it's version based on the electron version and it is not backwards compatible. You can either downgrade to electron v5 or use [yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) to use spectron v8.

**Comment by bruceauyeung** [comment]
@nklayman  

> I believe the issue is caused by a spectron/electron version mismatch. Since spectron is a dep of the plugin, I can't change it's version based on the electron version and it is not backwards compatible. You can either downgrade to electron v5 or use [yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) to use spectron v8.

i think this should be mentioned at https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/#installation or  https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/testingAndDebugging.html#testing

**Comment by bruceauyeung** [comment]
i am stucked on this issue for serveral hours.
i have rename all unit test files to *.bak except `electron.spec.js` which is untouched and originally generated by `VCP-electron-builder`.
before forcing VCP-electron-builder to use spectron v8 via `yarn selective version resolutions`, i got similar error as the following when running `yarn test:unit`
> Chrome version must be between 70 and 73
>  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.4.0-141-generic x86_64)

so like you said, i put the following lines into `package.json`:
~~~
  "resolutions": {
    "vue-cli-plugin-electron-builder/spectron": "^8.0.0"
  }
~~~
manually install  `spectron` to update `yarn.lock`:
~~~
yarn add spectron@^8.0.0
~~~
then delete the whole `node_module` directory and then `yarn install`

after all of this, `Chrome version must be between 70 and 73` error is gone, but electron windows popped out indefinitely ( before only 10 windows)

@nklayman what can i do ? thanks!
