### ISSUE TITLE
electron-builder config overrides ignored

### ISSUE THREAD

**Issue by clearydude** [nklayman/vue-cli-plugin-electron-builder#575]
**Describe the bug**
As part of our publishing process I need to be able to override values set in `publish`. While the docs state that [additional cli args are passed to electron-builder](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#configuring-electron-builder) I have not found this to be the case. When trying to build with a config override set like `c.publish.package=override-package` the effective config doesn't reflect any of that. When I bypass the vue-cli-service plugin and just straight up use electron-builder the effective config is correct.

**To Reproduce**
Just try to override any electron-builder config via `vue-cli-service electron:build`.
ex: `vue-cli-service electron:build -p never -c.artifactName=butts`. The effective config doesn't pick up any of these config overrides.

**Expected behavior**
The effective config and package is built using whatever config overrides I've passed in.

**Environment (please complete the following information):**
electron-builder  version=21.2.0 os=4.18.0-25-generic
ubuntu 18.10
 - node version: v10.16.0
 - npm version: 6.10.1
 - yarn version (if used): 1.16.0
 - vue-cli-plugin-electron-builder version : 1.4.2
 - electron version: 4.2.12
 
 - custom config for vcp-electron-builder: 
```
    electronBuilder: {
      builderOptions: {
        publish: [
          {
            provider: "bintray",
            repo: "foo",
            owner: "foobed",
            user: "${env.BT_USER}", // Hack for now but would prefer to use cli args
            package: "bar"
          }
        ],
        artifactName: "${productName}-${os}-${version}.${ext}",
        generateUpdatesFilesForAllChannels: true,
        // ...
      }
    }
```

**Comment by nklayman** [comment]
Thanks for the report, fixed in 1.4.2.
