### ISSUE TITLE
auto update

### ISSUE THREAD

**Issue by doyle-mark** [nklayman/vue-cli-plugin-electron-builder#577]
**Describe the bug**
Autoupdate begins downloading before throwing error `[2019-12-03 21:51:57.306] [info] Downloading update from flightdata-0.2.2-mac.zip, flightdata-0.2.2.dmg
[2019-12-03 21:51:57.307] [error] updaterCacheDirName is not specified in app-update.yml Was app build using at least electron-builder 20.34.0?`. 

**To Reproduce**
Add auto update to application as per recipe defined in the docs (https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#auto-update)

**Expected behavior**
Updates will complete download a install.

**Environment (please complete the following information):**
 - OS and version: OSX Catalina
 - node version: v10.16.3
 - npm version: 6.13.1
 - vue-cli-plugin-electron-builder version : ^1.4.2
 - electron version: ^6.1.5
 - other vue plugins used:    ` "@vue/cli-plugin-babel": "^4.0.0",
    "@vue/cli-plugin-unit-jest": "^4.1.1",
    "@vue/cli-service": "^4.0.0",
    "@vue/test-utils": "1.0.0-beta.29",`

 - (if possible) link to your repo:  https://github.com/doyle-mark/flightdata

**Additional context**
Similar issue on electron builder repo https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/323

thanks!

**Comment by nklayman** [comment]
Please share the link to your repo on https://github.com/electron-userland/electron-builder/issues/3485. Hopefully the electron-builder dev can figure it out as I am not sure what is wrong, but I think it is an error with electron-builder. I have not tested the update guide with mac as I don't own one, but it should work fine.

**Comment by doyle-mark** [comment]
I will share it ASAP thanks!

**Comment by nklayman** [comment]
You could also try forking the example repo and trying a Mac update with that
