### ISSUE TITLE
Help Request: Can't get sqlite3 + sequelizer working with VCP-electron-builder on Win10

### ISSUE THREAD

**Issue by adamrdrew** [nklayman/vue-cli-plugin-electron-builder#578]
I am sorry to open an issue here but I've been wrestling with this for a day and don't know what else to do. I cannot get sqlite3 working with sequelizer in a project made with VCP-electron-builder on Windows 10. The exact error I get is:

```
App threw an error during load
Error: Please install sqlite3 package manually
    at new ConnectionManager (webpack:///./node_modules/sequelize/lib/dialects/sqlite/connection-manager.js?:25:13)        at new SqliteDialect (webpack:///./node_modules/sequelize/lib/dialects/sqlite/index.js?:12:28)
    at new Sequelize (webpack:///./node_modules/sequelize/lib/sequelize.js?:233:18)
    at eval (webpack:///./src/background.js?:17:11)
    at Module../src/background.js (C:\Users\adamr\Development\testsql\dist_electron\index.js:5092:1)
    at __webpack_require__ (C:\Users\adamr\Development\testsql\dist_electron\index.js:20:30)
    at eval (webpack:///multi_./src/background.js?:1:18)
    at Object.0 (C:\Users\adamr\Development\testsql\dist_electron\index.js:5103:1)
    at __webpack_require__ (C:\Users\adamr\Development\testsql\dist_electron\index.js:20:30)
    at C:\Users\adamr\Development\testsql\dist_electron\index.js:84:18
    at Object.<anonymous> (C:\Users\adamr\Development\testsql\dist_electron\index.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at loadApplicationPackage (C:\Users\adamr\Development\testsql\node_modules\electron\dist\resources\default_app.asar\main.js:109:16)
```

This happens on a brand new project if you do nothing but add-electron buildering, install sqlite3 and sequelizer, and then just try to connect to a DB. Steps to reproduce:

```
vue create testsql
cd testsql
vue add electron-builder
	selected 6.0.0
npm install --save sqlite3 sequelizer pg-hstore
npm install
npm run postinstall
npm run electron:serve
```
Demo project opens and runs without issue

Added this to the top of background.js:
```
import path from 'path'
import Sequelize from 'sequelize'
const w = new Sequelize({
  dialect: 'sqlite',
  storage: path.join('C:\\', 'test.sqlite')
})
```
Result:
Error: Please install sqlite3 package manually

Try postinstall again and running again. Same thing

I've been searching for hours trying all the things but nothing I've found on Issues in the various projects (sequelizer, sqlite3, electron, this repo, etc) or on SO has actually worked. I don't get build errors - I have the windows dev tools and all of the build stuff set up and working fine. I can see it rebuild the native module, and I can build it from source, but for some reason sequelizer just can't seem to load it.

I am new to electron dev, so I'm sure this is something everyone knows and I just don't, so if anyone could help I would really appreciate it.

**Comment by adamrdrew** [comment]
And it's worth noting I can use sqlite3 directly from my own code without issue. If I switch out the sequelizer code with this it works fine
```
import sqlite3 from 'sqlite3'
const dbPath = electron.app.getPath('userData')
const db = new sqlite3.Database(path.join(dbPath, 'library.db'))
```
So the problem seems to be limited to Sequelizer. I know that this totally isn't yall's problem but I was hoping someone might have hit this before and might know what to do.

Thanks in advance 😊

**Comment by nklayman** [comment]
You need to `npm i sequelize` as it was not installed in your reproduction steps (did you type `sequelizer` instead?). Also, you need to mark sequelize as an [external](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules) by setting your `vue.config.js` to:

```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['sequelize']
    }
  }
}
```

P.S.: Don't hesitate (too much) to ask for help. It takes a lot less time for me to find a solution as I know the code better and have ran into similar issues. There is always a chance that there is a bug in the plugin as well. If you feel like you are taking too up too much of my time, you can always [donate](https://github.com/sponsors/nklayman) to make up for it (you will get priority support as well :) ).

**Comment by adamrdrew** [comment]
Wow, do I feel silly. Thank you very much for your gracious help, and the offer for further help. I will take you up on the offer, but I will try not to wear out my welcome.

It is working now. Thank you again for the second set of eyes :)

**Comment by sharifcse57** [comment]
I am building a electron app with vue cli and vue cli plugin builder.. 
I don't know how to open electron app when some one click from a button link from email.
If someone know this part how to do it please help me.

**Comment by MatthijsBurgh** [comment]
@sharifcse57 This issue has been closed for more than 2 years. You can not just drop an unrelated problem in a closed issue. I am removing you comment.
