### ISSUE TITLE
Error when running tests of vue-components importing ipcRenderer

### ISSUE THREAD

**Issue by davidsoederberg** [nklayman/vue-cli-plugin-electron-builder#582]
**Describe the bug**
When you run `"test:unit": "vue-cli-service test:unit"` and you have a vue component that imports ipcRenderer, `import { ipcRenderer } from 'electron';`, there is an error, screenshot below.

**To Reproduce**
Create a project using the vue-cli and add this plugin to the project. Then add 
`import { ipcRenderer } from 'electron';` to `HelloWorld.vue`. Then run the test script.

**Expected behavior**
I expect to be able to test vue components using the ipcRenderer.

**Screenshots**
![image](https://user-images.githubusercontent.com/31454554/70383712-c036bb80-1972-11ea-822f-e189c438b081.png)

```json
"dependencies": {
    "chai-as-promised": "^7.1.1",
    "core-js": "^3.4.3",
    "vue": "^2.6.10"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.1.0",
    "@vue/cli-plugin-unit-mocha": "^4.1.0",
    "@vue/cli-service": "^4.1.0",
    "@vue/test-utils": "1.0.0-beta.29",
    "chai": "^4.1.2",
    "electron": "^6.0.0",
    "vue-cli-plugin-electron-builder": "^1.4.3",
    "vue-template-compiler": "^2.6.10"
  }
```
```js
import { expect } from 'chai'
import { shallowMount } from '@vue/test-utils'
import HelloWorld from '@/components/HelloWorld.vue'

describe('HelloWorld.vue', () => {
  it('renders props.msg when passed', () => {
    const msg = 'new message'
    const wrapper = shallowMount(HelloWorld, {
      propsData: { msg }
    })
    expect(wrapper.text()).to.include(msg)
  })
})
```

**Environment**
 - OS and version: Ubuntu 18.04
 - node version: 12.13.1
 - npm version: 6.12.1

EDIT: Fixed typo

**Comment by nklayman** [comment]
I don't get the issue when importing `ipcRenderer`. Try `rm -r node_modules && npm i` and then rerunning tests.

**Comment by davidsoederberg** [comment]
I have tried that several times which means there is something else wrong with my system. I have not tried running the tests via CI, I will do that. I guess we can close the issue because the error is on my side and not this package.

**Comment by nklayman** [comment]
Try `rm -r ~/.cache/electron` to clear electron cache, clearing local deps, and reinstall deps.

**Comment by davidsoederberg** [comment]
Did not work for me, I also tried the tests on Github Actions and on my laptop and got the same error. 

I have wasted way too much time on this so I am done for now, thanks for trying to help!

**Comment by yunsinek** [comment]
`ipcRenderer` not `icpRenderer`

**Comment by davidsoederberg** [comment]
@yunsinek Sorry for that typo, in the code however I use the correct spelling. I have no problem running the app normally, it is just when I want to test the code. So I can develop my project fine, it is just that I can not test the vue-files containing imports from electron.

**Comment by nklayman** [comment]
Latest v10.x variant, and I used the latest version of yarn, rather than npm.

**Comment by davidsoederberg** [comment]
Same problem with v10.x and yarn, tried on multiple computers aswell. This is weird.

**Comment by nklayman** [comment]
Since it works fine for me, can you create a sample repository that has the error so that I can try with the exact same code?

**Comment by davidsoederberg** [comment]
I created a simple repo that outputs the error both local and for github actions. The steps taken is described in README.

[Repo](https://github.com/davidsoederberg/vue-electron-error) 
[CI](https://github.com/davidsoederberg/vue-electron-error/commit/e4a230520d44e93b43dfe73fda89b360699b8824/checks?check_suite_id=377635145)

**Comment by AssetKid** [comment]
@davidsoederberg Getting the same error on my PC.

You can try using a `preload` script to workaround this.

```js
// Create a new 'preload.js' file in public folder

const { ipcRenderer } = require('electron')

window.ipcRenderer = ipcRenderer
```

```js
// background.js

// Create the browser window.
win = new BrowserWindow({
  width: 800,
  height: 600,
  webPreferences: {
    nodeIntegration: true,
    preload: path.resolve(__static, 'preload.js')
  }
})
```

`ipcRenderer` should now be available in the `renderer` process. The `import` statement is no longer needed.

### PS: Not tested at all

**Comment by davidsoederberg** [comment]
@AssetKid Your method works! The test is passed both locally and on Github Actions.

I made these [changes](https://github.com/davidsoederberg/vue-electron-error/commit/66f1ff8272bf757951ad01cdbb31fe87bdd83c1a) to the code. Added a button etc. to test that ipcRenderer works fine while running the app.

Thanks for the help both @nklayman and @AssetKid!

**Comment by nklayman** [comment]
@davidsoederberg I was able to reproduce the error with the repo you made, and fix it with @AssetKid's solution. Another option is to mock the electron module with a mocking library such as [sinon js](https://sinonjs.org/). This would prevent you from having to remove the import statements.
