### ISSUE TITLE
I encountered a "regeneratorRuntime" problem after I configured babel to package it into an exe

### ISSUE THREAD

**Issue by luhaoz** [nklayman/vue-cli-plugin-electron-builder#584]
**Describe the bug**

I encountered a "regeneratorRuntime" problem after I configured babel to package it into an exe

**To Reproduce**
I added a framework folder in the src directory to store some of my mian code

But I found that I can no longer use static properties in it

I think this is a problem with babel and then I found

https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/204

After that I modified vue.config.js to become

Solved the problem smoothly afterwards

```
let path = require('path');
module.exports = {
    configureWebpack: {
        resolve: {
            alias: {
                'framework': path.join(__dirname, '../src/framework'),
            },
            extensions: ['.js', '.json', '.node']
        },
    },
    pluginOptions: {
        i18n: {
            locale: 'zh-CN',
            fallbackLocale: 'zh-CN',
            localeDir: 'locales',
            enableInSFC: true
        },
        electronBuilder: {
            chainWebpackMainProcess: config => {
                config.module
                    .rule('babel')
                    .test(/(background\.js$|framework)/)
                    .use('babel')
                    .loader('babel-loader')
                    .options({
                        presets: [['@babel/preset-env', {modules: false}]],
                        plugins: ['@babel/plugin-proposal-class-properties']
                    })
            }
        }
    }
}

```

But it happens when I launch the exe packaged after using  `electron: build`

![a1](https://user-images.githubusercontent.com/8097324/70486482-fd46ad80-1b2c-11ea-8d9d-49d9efd2c592.png)

How should I solve this? This seems to be caused by babel. Should I add more configuration?

Please help me thanks
**Expected behavior**

Run the packaged exe normally

**Environment 

```
 - OS and version: win10 10.0.18362.476
 - node version: 10.17.0
 - npm version: 6.11.3
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version :  1.4.2 
 - electron version: 6.0.0
```

**Comment by nklayman** [comment]
You need to add `targets: { electron: '6' }` alongside `{ modules: false }` to your babel config in `vue.config.js`.
