### ISSUE TITLE
Issue with node-escpos package

### ISSUE THREAD

**Issue by KakarN** [nklayman/vue-cli-plugin-electron-builder#589]
Hi,

I love this plugin! It's so easy and clean. I have used this plugin in many of my projects. 

**Describe the bug**
Recently I had to work with thermal printers, and I wanted to work with this plugin with another npm package ([node-escpos](https://github.com/song940/node-escpos/)) which is as clean as this plugin, but I was unable to integrate these two packages together.

The thing is, I was able to integrate node-escpos with pure electron app, also with [electron-vue](https://github.com/SimulatedGREG/electron-vue) which as you might know is another alternate option to work with electron and vuejs. There were some set backs with electron-vue, but I was able to find solutions for them.

However, when I try to install node-escpos, some of the dependencies does not install.

**To Reproduce**
1. Create a vue project
`vue create test-vue-cli-electron`
2. Verify the project web app
`yarn serve`
3. Install vue-cli-plugin-electron-builder plugin
`vue add electron-builder`
3. Again verify if the desktop app is working
`yarn electron:serve`
4. Finally install node-escpos package, and I get this error:
`npm i escpos --save`
<img width="1440" alt="Screen Shot 2019-12-15 at 3 23 36 PM" src="https://user-images.githubusercontent.com/9060759/70861038-0da4c100-1f4f-11ea-876c-e961318b60a7.png">

However, if I import node-escpos into my background.js:
```
// background.js
import { app, protocol, BrowserWindow } from 'electron'
...
const escpos = require('escpos');
...
```
And after I have imported it, I run the app:
`yarn electron:serve`

I get this error

<img width="604" alt="Screen Shot 2019-12-15 at 3 32 09 PM" src="https://user-images.githubusercontent.com/9060759/70861165-1ba71180-1f50-11ea-8fc4-7ec2e805dc41.png">

**Environment (please complete the following information):**
 - OS and version: macOS High Sierra
 - node version: 13.3.0
 - npm version: 6.13.1
 - vue-cli-plugin-electron-builder version : 1.4.0
 - electron version: 5.0.0
 - yarn version: 1.16.0

**Additional context**
The solution that worked with a pure electron app and electron-vue app was to use [electron-rebuild](https://www.npmjs.com/package/electron-rebuild). To which this [answer](https://stackoverflow.com/questions/46384591/node-was-compiled-against-a-different-node-js-version-using-node-module-versio/52796884#52796884) has a nice explanation.

Additionally for electron-vue, these two steps were required:
- **If HTML `process` not found**: Edit html as described [here](https://github.com/SimulatedGREG/electron-vue/issues/871#issuecomment-529809406) (it also works without editing the webpack.renderer.config.js even though it is described in the reply)
- **If `module` not found**: Set `nodeIntegration` as described [here](https://github.com/SimulatedGREG/electron-vue/issues/871#issuecomment-498220754)

I hope you will help me figure it out! Thank you.

**Comment by KakarN** [comment]
I think, I may have found solution for this. You can verify it in my [medium story](https://medium.com/@nyorikakar/printing-with-vue-electron-and-node-f52a730e63e7). If you are satisfied, I can close this issue.

**Comment by nklayman** [comment]
Marking it as an external is the correct solution. You shouldn't have to use electron-rebuild though, as deps should be rebuilt automatically. However if it doesn't work without it that's fine.
