### ISSUE TITLE
Correctly export your functions from /lib

### ISSUE THREAD

**Issue by TotomInc** [nklayman/vue-cli-plugin-electron-builder#59]
**Is your feature request related to a problem? Please describe.**
You should normalize your exports from `/lib` for `createProtocol` and `installVueDevtools`, actually it looks like:

`import { createProtocol, installVueDevtools } from 'vue-cli-plugin-electron-builder/lib'`

instead of being:

`import { createProtocol, installVueDevtools } from 'vue-cli-plugin-electron-builder`

**Describe the solution you'd like**
Maybe in your `index.js` export the following functions like this:

```javascript
const { createProtocol, installVueDevtools } = require('./lib');

module.exports.createProtocol = createProtocol;
module.exports.installVueDevtools = installVueDevtools;
```

**Comment by nklayman** [comment]
The reason I don't do this as they would be imported whenever a command is run. The `installVueDevtools` has a decent amount of dependencies that would be unnecessarily imported. While this wouldn't really effect performance that much, it is also just 4 letters. What do you think would be the better option?

**Comment by TotomInc** [comment]
Well, the most logical answer is to normalize the exports as all `node_modules` does.

However if the trade-off with dependencies/performance is too big, it's not worth to do it.

**Comment by nklayman** [comment]
While attempting to test the performance, I realized that I use es6 import/export in those two functions to take advantage of better tree-shaking. This result in errors thrown when trying to re-export them in the `index.js` (node does not support import/export). The `testWithSpectron` function was already re-exported (no import/export), and removing it decreased build times by about .3 seconds. So, while performance is barely impacted, I would have to convert to `require()` which would loose tree shaking, which I don't think is worth it.
