### ISSUE TITLE
v2.0.0: Rename "background.js" to "main.js" and "main.js" to "renderer.js"

### ISSUE THREAD

**Issue by AlexSHoffman** [nklayman/vue-cli-plugin-electron-builder#597]
Wouldn't it make more sense to call main process as `main.js` and renderer process as `renderer.js`?
Right now it's kind of backwards.

**Comment by AssetKid** [comment]
I personally think it is fine. With that said, it is easy to achieve this in your project.

```js
// vue.config.js

module.exports = {
  pages: {
    index: {
      entry: 'src/renderer.js' // Previously main.js
    }
  },
  pluginOptions: {
    electronBuilder: {
      mainProcessFile: 'src/main.js' // Previously background.js
    }
  }
}
```

**Comment by AlexSHoffman** [comment]
@AssetKid thanks for the code example. I might actually do that unnecessary monkey-wrenching even though this problem shouldn't exist in the first place.

But I don't know, what's the point calling `renderer` process as `main` and main process as `background` (implying it is **not** main). It's not only confusing but essentially pointless.

**Comment by nklayman** [comment]
The reason I don't change the name is because the renderer process uses `main.js` by default, and I think it would be confusing if I replaced it with a completely different file. You have the option to change it, but the default will remain background.js for now.

**Comment by AlexSHoffman** [comment]
@nklayman what about renaming it to something reasonable, e.g `background.js`  to `electronMain.js`?

I tried renaming it myself by adding the @AssetKid code and renaming `"main" value` in `package.json`, but I'm getting this error:

```
This dependency was not found:

* [path_to_project_dir]\src\background.js in multi ./src/background.js
```

**Comment by nklayman** [comment]
@AlexSHoffman You should only have to update the `vue.config.js`. Can you try following @AssetKid's suggestion with a blank repo? If it doesn't work can you upload it to Github and post a link so I can fix the issue.

**Comment by AssetKid** [comment]
Don't change the `main` value. It will not work.

**Comment by AlexSHoffman** [comment]
Thanks guys, it works now
