### ISSUE TITLE
pluginOptions.electronBuilder.externals doesn't work as expected

### ISSUE THREAD

**Issue by bruceauyeung** [nklayman/vue-cli-plugin-electron-builder#598]
because of module `node-bindings`'s limitation, module `ffi` and `ref` must not be packed ( or must be used as externals ) by webpack, otherwise it will failed with error `Could not load the bindings file` , so i configured as [this comment](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/276#issuecomment-494554077) suggested.
my vue.config.js:
~~~
const { resolve } = require('path');
module.exports = {
  configureWebpack: config => {
    config.devtool = 'source-map';
    config.optimization.minimizer[0].options.terserOptions.keep_classnames = true;
    config.optimization.minimizer[0].options.terserOptions.keep_fnames = true;
    config.optimization.minimizer[0].options.terserOptions.compress.drop_debugger = true;
    config.externals['ffi'] = "require('ffi')";
    config.externals['ref'] = "require('ref')";
  },
  pluginOptions: {
    electronBuilder: {
      chainWebpackMainProcess: config => {
      },
      externals: ['ffi', 'ref', 'shortcut-capture', 'winston', 'winston-daily-rotate-file'],
      builderOptions: {
        extraFiles: ['lib'],
        extraResources: ['workbench-v*.asar', 'preloads'],
      },
    },
  },
};
~~~
but these two lines are mandatory to make `ffi` and `ref` work even when i have already configured pluginOptions.electronBuilder.externals.
~~~
config.externals['ffi'] = "require('ffi')";
config.externals['ref'] = "require('ref')";
~~~
thi is not like what you said in [this comment](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/276#issuecomment-495337273)

**To Reproduce**
none

**Expected behavior**
no need to configure 
~~~
config.externals['ffi'] = "require('ffi')";
config.externals['ref'] = "require('ref')";
~~~
when i have configured pluginOptions.electronBuilder.externals

**Environment (please complete the following information):**
 - OS and version: CentOS 7.4 64bit
 - node version: 12.4.0
 - npm version: not used
 - yarn version (if used):  1.19.0
 - vue-cli-plugin-electron-builder version : 1.4.3
 - electron version: 6.1.4
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo:

**Comment by WingDust** [comment]
i am want  use `win32-api` as same question
`win32-api`  is use `node-bindings` ,I also add 
```
    pluginOptions: {
        webpackBundleAnalyzer: {
            openAnalyzer: false
        }, 
        electronBuilder: {
            externals: ['win32-api','bindings'],
            nodeModulesPath: ['../../node_modules', './node_modules']
        }
    }

```

**Comment by uskithub** [comment]
Try this:

```
    config.externals(['ffi', 'ref']);
```

You should see https://github.com/neutrinojs/webpack-chain .

**Comment by nklayman** [comment]
@bruceauyeung can you try again with the latest version of this plugin (preferably the 2.0 beta)? I tried to reproduce your issue and it worked fine, all I had to do was set the `externals` array. I think I remember being able to reproduce your error a while ago, and I think I may have fixed it accidently.
