### ISSUE TITLE
env variables set in main process are not inherited by renderer process

### ISSUE THREAD

**Issue by bruceauyeung** [nklayman/vue-cli-plugin-electron-builder#599]
**Describe the bug**
first i make sure there is no `process.env.LD_LIBRARY_PATH` in os env variables.
i wanna set env variables programmatically. so i set env variables in `background.ts` before `createWindow()` is called ( if i understand correctly, the renderer process inside which  vuejs codes run is created here )  
`process.env.LD_LIBRARY_PATH` is actually set before `ready` listener being registered on `app` object
my code:
~~~
debugger;
const logger = loggerFactory.get('background');

let libPath = path.join(ElectronUtils.app().getAppPath(), '..', 'lib');
if (ElectronUtils.isLinux32()) {
  libPath = path.join(libPath, 'linux32');
} else {
  libPath = path.join(libPath, 'linux64');
}
logger.debug(`libPath:${libPath}`);
if (process.env.LD_LIBRARY_PATH) {
  process.env.LD_LIBRARY_PATH = `${process.env.LD_LIBRARY_PATH}${path.delimiter}${libPath}`;
} else {
  process.env.LD_LIBRARY_PATH = libPath;
}
logger.debug(`process.env.LD_LIBRARY_PATH:${process.env.LD_LIBRARY_PATH}`);
......  // omitted codes
......  // omitted codes
// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let win: BrowserWindow | null;
// Scheme must be registered before the app is ready
protocol.registerSchemesAsPrivileged([{ scheme: 'app', privileges: { secure: true, standard: true } }]);
...... // omitted codes
......  // omitted codes
~~~
according to the last log line i can confirm `process.env.LD_LIBRARY_PATH` is set successfully.
but when i try to read `process.env.LD_LIBRARY_PATH` in renderer process ( for example vuejs codes ) , it's `undefined`.

**Expected behavior**
`process.env.LD_LIBRARY_PATH` is also set in renderer process.

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: CentOS 7.4 64bit
 - node version: 12.4.0
 - npm version: not used
 - yarn version (if used):  1.19.0
 - vue-cli-plugin-electron-builder version : 1.4.3
 - electron version: 6.1.4
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: none

**Comment by bruceauyeung** [comment]
looks like it's related to webpack's free variable replacement.
if i configure vue.config.js like the following:
~~~
module.exports = {
  chainWebpack: config => {
    config.plugin('define').tap(args => {
      args[0]['process.env'].LD_LIBRARY_PATH = 'process.env.LD_LIBRARY_PATH';
      return args;
    });
  },
}
~~~
then i can write to / read from env variable LD_LIBRARY_PATH  via `process.env.LD_LIBRARY_PATH` directly

then i thought maybe VCP-electron-builder injects all env variables ?
but it seems not:
https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/b87d48984252a31665ddbfa142cd79798cdc35f4/index.js#L564

and why  it acts differently between main and renderer process ?

**Comment by nklayman** [comment]
This is caused because [vue cli uses DefinePlugin](https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-service/lib/util/resolveClientEnv.js) to overwrite `process.env`. This is out of the control of this plugin, so you will have to use your fix in `vue.config.js`.
