### ISSUE TITLE
`npm run serve:electron` results in `TypeError: api.setMode is not a function`

### ISSUE THREAD

**Issue by TAGC** [nklayman/vue-cli-plugin-electron-builder#6]
After creating a new project vue project using this plugin, I'm unable to serve my application as an electron process via `npm run serve:electron`. The command fails with this exception:

```
> vue-experiment@0.1.0 serve:electron /Users/<me>/Documents/VSCode/vue-experiment
> vue-cli-service serve:electron

 ERROR  TypeError: api.setMode is not a function
TypeError: api.setMode is not a function
    at api.registerCommand (/Users/<me>/Documents/VSCode/vue-experiment/node_modules/vue-cli-plugin-electron-builder/index.js:70:11)
    at Service.run (/Users/<me>/Documents/VSCode/vue-experiment/node_modules/@vue/cli-service/lib/Service.js:167:12)
    at Object.<anonymous> (/Users/<me>/Documents/VSCode/vue-experiment/node_modules/@vue/cli-service/bin/vue-cli-service.js:22:9)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-experiment@0.1.0 serve:electron: `vue-cli-service serve:electron`
npm ERR! Exit status 1
npm ERR!
```

This behaviour occurs on both Windows and macOS. Serving normally (via `npm run serve`) works fine.

**Comment by nklayman** [comment]
Try downgrading to vue-cli 3.0.0-beta 9. While this issue would be easy to fix, the bigger issue is that vue-cli beta 10 uses babel@7-beta, which is not supported by electron-webpack (see [#125](https://github.com/electron-userland/electron-webpack/issues/125)). I should be able to fix it by using the suggested temporary workaround soon. Until then, you must use vue-cli 3 beta <=9.

**Comment by TAGC** [comment]
I've downgraded to `@vue/cli@3.0.0-beta.9` and destroyed/recreated my app from scratch but I still get the same error. I'm trying this on Ubuntu 18.04.

**Comment by TAGC** [comment]
Here's the sort of NPM logs I get:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run', 'serve:electron' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose run-script [ 'preserve:electron', 'serve:electron', 'postserve:electron' ]
5 info lifecycle my-electron-app@0.1.0~preserve:electron: my-electron-app@0.1.0
6 info lifecycle my-electron-app@0.1.0~serve:electron: my-electron-app@0.1.0
7 verbose lifecycle my-electron-app@0.1.0~serve:electron: unsafe-perm in lifecycle true
8 verbose lifecycle my-electron-app@0.1.0~serve:electron: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/<me>/Documents/my-electron-app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle my-electron-app@0.1.0~serve:electron: CWD: /home/<me>/Documents/my-electron-app
10 silly lifecycle my-electron-app@0.1.0~serve:electron: Args: [ '-c', 'vue-cli-service serve:electron' ]
11 silly lifecycle my-electron-app@0.1.0~serve:electron: Returned: code: 1  signal: null
12 info lifecycle my-electron-app@0.1.0~serve:electron: Failed to exec serve:electron script
13 verbose stack Error: my-electron-app@0.1.0 serve:electron: `vue-cli-service serve:electron`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid my-electron-app@0.1.0
15 verbose cwd /home/<me>/Documents/my-electron-app
16 verbose Linux 4.15.0-20-generic
17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "serve:electron"
18 verbose node v8.10.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error my-electron-app@0.1.0 serve:electron: `vue-cli-service serve:electron`
22 error Exit status 1
23 error Failed at the my-electron-app@0.1.0 serve:electron script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by TAGC** [comment]
Okay, I managed to resolve this. In case it helps anyone else, I took these steps:

I ran `npm list -g | grep @vue` and nuked all packages that I saw listed. In addition to `@vue/cli`, I also had `@vue/cli-init` installed, so I globally uninstalled both of them. I then reinstalled Vue CLI with `npm i -g @vue/cli@3.0.0-beta.9`.

After that, I recreated my project via `vue create my-electron-app && cd my-electron-app && vue add electron-builder`, using all the default settings and saying "yes" when it asked if I wanted TypeScript support. However, I had to edit the `devDependencies` section of the generated `package.json`:

```diff
-"@vue/cli-plugin-babel": "^3.0.0-beta.10",
-"@vue/cli-plugin-eslint": "^3.0.0-beta.10",
-"@vue/cli-service": "^3.0.0-beta.10",
+"@vue/cli-plugin-babel": "3.0.0-beta.9",
+"@vue/cli-plugin-eslint": "3.0.0-beta.9",
+"@vue/cli-service": "3.0.0-beta.9",
```

After that it was mostly just finishing off the configuration. Cheers for the help, mate.

**Comment by TAGC** [comment]
I still have a problem, actually. `electron-webpack-ts@2.0.2` gets installed with this boilerplate, which depends on `ts-loader@4.3.0`. However, `@vue/cli-service@3.0.0-beta.9` (which I downgraded to) depends on `webpack@3.12.0`, and [ts-loader v4 doesn't support webpack v3](https://github.com/TypeStrong/ts-loader#compatibility). I could try downgrading `electron-webpack-ts` but I'm not sure if that will cause problems of its own.

So I need `@vue/cli-service < 3.0.0-beta.10` to solve one issue and `@vue/cli-service >= 3.0.0-beta.10` to solve another. Setting up JS projects always feel like a game of whackamole haha.

**Comment by nklayman** [comment]
Try switching to electron-webpack-ts@^1.0.0, it worked for me.

**Comment by TAGC** [comment]
I did yeah, cheers, and it hasn't caused any noticeable problems so far. I've worked around the other issue too (though I think you've fixed it now - I'll have to test tomorrow) so I've got a stable running project now.

**Comment by nklayman** [comment]
In v0.2.4, electron-webpack-ts@1.4.0 is installed instead of @2.0.0, and the adding typescript instructions in the readme is updated as well. Thanks for reporting this issue, as well as #7, which I was having problems with as well!
