### ISSUE TITLE
misreport when compiling

### ISSUE THREAD

**Issue by bruceauyeung** [nklayman/vue-cli-plugin-electron-builder#606]
**Describe the bug**
>Starting development server...
>Starting type checking service...
>Using 1 worker with 2048MB memory limit
>98% after emitting CopyPlugin
>
> ERROR  Failed to compile with 1 errors                                                                                     10:23:29
>
> error  in ./src/commons/node/netExtra.ts
>
>Module Error (from D:/Home/icenter-next/node_modules/eslint-loader/index.js):
>error: 'NetExtra' is already defined (no-redeclare) at src\commons\node\netExtra.ts:26:18:
>  24 | }
>  25 |
>> 26 | export namespace NetExtra {
>     |                  ^
>  27 |   export enum IPAddressFamily {
>  28 |     IPV4 = 'IPv4',
>  29 |     IPV6 = 'IPv6',
>
>
>1 error found.
>
> @ ./src/bindings/ussdk/index.ts 11:0-51 124:20-28 124:41-49
> @ ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=ts&
> @ ./src/components/HelloWorld.vue?vue&type=script&lang=ts&
> @ ./src/components/HelloWorld.vue
> @ ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=ts&
> @ ./src/App.vue?vue&type=script&lang=ts&
> @ ./src/App.vue
> @ ./src/main.ts
> @ multi (webpack)-dev-server/client?http://10.4.205.47:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts
>
>No type errors found
>Version: typescript 3.5.3
>Time: 20043ms 

the very last 3 lines : `No type errors found`, 
but actually `eslint-loader` reports: ` 'NetExtra' is already defined (no-redeclare) at src\commons\node\netExtra.ts:26:18:`

this situation may mislead developers , especially there are lots of warnings.

if this is because different tools report them, can we have a summary report ?

**Environment (please complete the following information):**
 - vue-cli-plugin-electron-builder version : 1.4.3

**Comment by nklayman** [comment]
The error is reported during the renderer process build, which is handled by [vue cli](https://github.com/vuejs/vue-cli). You should report this issue there instead.
