### ISSUE TITLE
Build: Cannot Fetch WASM 

### ISSUE THREAD

**Issue by vinceniko** [nklayman/vue-cli-plugin-electron-builder#607]
**Describe the bug**
Using `electron-serve` to serve a wasm file located in a "pkg" subdirectory in project root is fine. However, when running the build executable after using `electron:build`, the following error is thrown: `bootstrap:197 Fetch API cannot load app://./0af963a93f623d39583f.module.wasm. URL scheme "app" is not supported.`

**To Reproduce**
Presumably, import a wasm file into a Vue component and use the plugin to build it.

**Expected behavior**
Expected to run correctly like with the electron:serve command

**Environment (please complete the following information):**
 - OS and version: MacOS Catalina
 - node version:  v12.6.0
 - npm version: 6.13.4
 - yarn version (if used):  1.21.1
 - vue-cli-plugin-electron-builder version : 1.4.4
 - electron version: 6.1.7

**Additional context**
Using Rust and wasm-pack to generate wasm files and the js glue files that gets imported by the Vue code.

**Comment by nklayman** [comment]
You cannot use the fetch api to run wasm in a build, as there is no server. Instead, read the file using fs like so:

```js
const bytes = fs.readFileSync(`/${__static}/simple.wasm`)
WebAssembly.instantiate(bytes, importObject)
    .then(obj => obj.instance.exports.exported_func());
```

**Comment by nklayman** [comment]
Also, if you are a fan of rust and want a bleeding edge alternative to electron that gives you <3mb executables, check out [tauri](https://github.com/tauri-apps/tauri). It is currently pre-alpha, but the alpha release with full docs is coming soon. I made a [vue cli plugin](https://github.com/tauri-apps/vue-cli-plugin-tauri) for it as well. Unfortunately, it doesn't yet support wasm though :(.

**Comment by vinceniko** [comment]
I may not have clarified enough. The error occurs on the last line of the following of index.html:

```
 		// Fetch + compile chunk loading for webassembly

 		var wasmModules = {"chunk-411c2004":["6a5a"]}[chunkId] || [];

 		wasmModules.forEach(function(wasmModuleId) {
 			var installedWasmModuleData = installedWasmModules[wasmModuleId];

 			// a Promise means "currently loading" or "already loaded".
 			if(installedWasmModuleData)
 				promises.push(installedWasmModuleData);
 			else {
 				var importObject = wasmImportObjects[wasmModuleId]();
 				var req = fetch(__webpack_require__.p + "" + {"6a5a":"4944e368558e2d3d4f24"}[wasmModuleId] + ".module.wasm");
```

As I understand it, this is generated by Webpack for chunk loading. Do you know if there is a way to replace the fetch api usage with fs in the Webpack config for this?

**Comment by crossle** [comment]
You can set allow app schema support Fetch API
```
protocol.registerSchemesAsPrivileged([
  { scheme: 'app', privileges: { standard: true, supportFetchAPI: true, secure: true } }
])
```

**Comment by nklayman** [comment]
@vinceniko try @crossle's suggestion, the code snippet to be modified is found in `src/background.js`.

**Comment by vinceniko** [comment]
Awesome, that fixed the issue! Is there a reason why this isn't the default functionality?

**Comment by major-mayer** [comment]
Thanks a lot, I had the same issue and the supportFetchAPI field fixed it for me :) 
I also think this should be enabled by default

**Comment by MGraefe** [comment]
For any electron-serve users that stumble over this issue, you don't need to manually do `protocol.registerSchemeAsPrivileged`. Electron-serve will do that for you **but** only for the last protocol you enable serve for, as there can only be one protocol for which fetch is enabled it seems:

```javascript
const serve = require('electron-serve');

serve({directory: './foo', scheme: 'foo'});
serve({directory: './bar', scheme: 'bar'});
// fetch is only possible for bar://
```

**Comment by RoelRoel** [comment]
I want to use fetch to load local csv files. But when I use crossle's solution I get a blank screen on production build.It works offcoarse with electron:serve.
