### ISSUE TITLE
Check if it's web or not?

### ISSUE THREAD

**Issue by emjimadhu** [nklayman/vue-cli-plugin-electron-builder#611]
I have used `electron-vue` in the past. And i like this plugin. In `electron-vue` they had a method to determine, build the app for web or electron. Based on that check i can disable or enable some of the features in my app like node file system and path. 

For example, i have custom titlebar, that should only show in electron and in web. Because of that, my webapp is not working on the browser!.

So is there any built in method avaible to determine is it web or electron? Or if not, is there a way to determine that manually?

Thanks in advance!

**Comment by yvesh** [comment]
I use a mixin with `process.env.IS_ELECTRON` for that.

**Comment by emjimadhu** [comment]
@yvesh Thank you. That should do it!

**Comment by nklayman** [comment]
Yep, `process.env.IS_ELECTRON` is the best way to tell.
