### ISSUE TITLE
electron__WEBPACK_IMPORTED_MODULE_0___default.a.send is not a function when using ipcRenderer

### ISSUE THREAD

**Issue by AmrBinBashir** [nklayman/vue-cli-plugin-electron-builder#612]
**Describe the bug**
When i use` ipcRenderer` in `App.vue` the console catches this error `electron__WEBPACK_IMPORTED_MODULE_0___default.a.send is not a function at eval`  it actually logs once from `vue.runtime.esm.js` and again from `App.vue`

**To Reproduce**
1- import `ipcRenderer `in `App.vue`
2-use `ipcRenderer.send `in a function inside methods
3-check the devtools for errors

**Expected behavior**
I should be able to receive ipcRenderes message in `background.js` with `ipcMain.on`.

**Screenshots**
![SharedScreenshot](https://user-images.githubusercontent.com/48618675/71647487-5656cb00-2d00-11ea-87bf-792265b63afb.jpg)

**Environment (please complete the following information):**
 - OS and version: Win 10 ver 1909
 - node version:  13.5.0
 - npm version: 6.13.4
 - yarn version (if used): 1.21.1
 - vue-cli-plugin-electron-builder version : 1.4.4
 - electron version: 7.1.7
 - other vue plugins used: vue-router (added to the dependencies but haven't used it yet)
 - custom config for vcp-electron-builder: nope
 - (if possible) link to your repo:  https://github.com/AmrBinBashir/-WIP-Dictionary-App

**Comment by nklayman** [comment]
You need to `import { ipcRenderer } from 'electron'`, not `import ipcRenderer from 'electron'`. The former imports the `ipcRenderer` export of the `electron` module, while the latter imports the whole `electron` module and names the variable it is stored in `ipcRenderer`. See [the MDN docs on import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) for more details.

**Comment by AmrBinBashir** [comment]
@nklayman i don't have any errors now but my logic in background.js still not working, is there is some way to debug the ipc signals in vue devtools , since devtron is dead ?

**Comment by nklayman** [comment]
No, the best option would be to debug `background.js` by following the [debugging instructions](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/testingAndDebugging.html#debugging).
