### ISSUE TITLE
Separate compile for preload script

### ISSUE THREAD

**Issue by cawa-93** [nklayman/vue-cli-plugin-electron-builder#613]
**Describe the solution you'd like**
I want to offer a separate compilation for the preload script.

Similarly, as a background process is compiled, it would be possible to create an appropriate `preload.ts` file and compile it to `preload.js` with the appropriate configuration
 ```json 
{
  "target": "electron-preload"
}
```

**Comment by jsmnbom** [comment]
@nklayman Any chance of this landing in v2? Preload files are very useful, if not almost crucial, with `nodeIntegration: false`.

**Comment by Eidorian** [comment]
Will be very nice yeah!

**Comment by bruceauyeung** [comment]
yeah, absence of such feature forces me to compile my preload scripts using my own Node.js scripts.
expecting so much !

**Comment by nklayman** [comment]
This will be available in v2.0.
