### ISSUE TITLE
AutoUpdate not working

### ISSUE THREAD

**Issue by gabyyro** [nklayman/vue-cli-plugin-electron-builder#614]
`import {
	autoUpdater
} from "electron-updater"

	if (process.env.WEBPACK_DEV_SERVER_URL) {
		// Load the url of the dev server if in development mode
		win.loadURL(process.env.WEBPACK_DEV_SERVER_URL)
		if (!process.env.IS_TEST) win.webContents.openDevTools()
	} else {
		createProtocol('app')
		// Load the index.html when not in development
		win.loadURL('app://./index.html')

		autoUpdater.checkForUpdatesAndNotify()
	}
`
`publish: [{
					provider: "github",
					owner: "git account name",
					repo: "repo url",
					releaseType: "draft",
					channel: "latest",
				}]`

I have this in my background.js. I do all the steps, installed the app, increased versions, used npm run electron:build -- -p always, I publish release on github. I get not update and no notification when I open the app again. I followed all steps from here https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#auto-update

I used electron log to debug and I get:

`Error: Error: Unsupported provider: undefined
    at newError (webpack:///./node_modules/electron-updater/node_modules/builder-util-runtime/out/index.js?:212:17)
    at createClient (webpack:///./node_modules/electron-updater/out/providerFactory.js?:103:48)
    at eval (webpack:///./node_modules/electron-updater/out/AppUpdater.js?:482:99)
    at async NsisUpdater.getUpdateInfoAndProvider (webpack:///./node_modules/electron-updater/out/AppUpdater.js?:485:20)
    at async NsisUpdater.doCheckForUpdates (webpack:///./node_modules/electron-updater/out/AppUpdater.js?:506:20)`

**Comment by gabyyro** [comment]
Managed to make it work...but now I get "method: GET url: https://github.com/ownername/project/releases.atom\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"".

I have set my token in .env GH_TOKEN=token_here

**Comment by gabyyro** [comment]
Manged to find the answer...the github repository has to be public, otherwise it won't work, even though declaring the token in .env file.

**Comment by nklayman** [comment]
This behavior is intended by electron-builder. You can update from private repos, but it is only for very specific use cases. See [the docs](https://www.electron.build/auto-update#private-github-update-repo) for more info.

**Comment by Nisthar** [comment]
@nklayman does private repos currently work with this libraru?

**Comment by Nisthar** [comment]
Should i create a new issue for this?
