### ISSUE TITLE
TypeError: Cannot create proxy with a non-object as target or handler when running 'yarn test:unit'

### ISSUE THREAD

**Issue by bruceauyeung** [nklayman/vue-cli-plugin-electron-builder#615]
i utilize `electron-util: 0.13.0` everywhere within my electron app,for example, to build modules which work both in main and renderer process.

error occurs when i try to unit test my modules via  running `yarn test:unit`

>\# yarn test:unit
>yarn run v1.19.0
>$ vue-cli-service test:unit
> FAIL  tests/unit/refUtils.spec.ts
>  ● Test suite failed to run
>
>    TypeError: Cannot create proxy with a non-object as target or handler
>      1 | import WorkbenchTab from '@/components/Workbench/workbenchTab';
>      2 | import { remote } from 'electron';
>    \> 3 | import { is } from 'electron-util';
>               | ^
>      4 |
>      5 | import { SharedObjectKey } from '@/sharedObjects/sharedObjectKey';
>      6 |
>
>      at Object.<anonymous> (node_modules/electron-util/source/api.js:4:18)
>      at Object.<anonymous> (node_modules/electron-util/index.js:8:13)
>      at Object.<anonymous> (src/sharedObjects/sharedObjects.ts:3:1)
>      at Object.<anonymous> (src/logger/index.ts:3:1)
>      at Object.<anonymous> (src/commons/lang/array.ts:1:1)
>      at Object.<anonymous> (src/bindings/types.ts:3:1)
>      at Object.<anonymous> (tests/unit/refUtils.spec.ts:1:1)

`electron-util/source/api.js` source codes quoted from github repo:
~~~
'use strict';
const electron = require('electron');

module.exports = new Proxy(electron, {
	get: (target, property) => target[property] || (target.remote ? target.remote[property] : undefined)
});
~~~
the error means that `require('electron')` returns `null/undefined`

i have tried to `require` my modules after calling `await testWithSpectron()` but this makes no difference.

it looks like those codes run within normal node process instead of an electron process

**To Reproduce**
add line  `const { is } = require('electron-util'）after `await testWithSpectron()` ` to `electron.spec.js`

**Environment (please complete the following information):**
 - OS and version: CentOS 7.4 64bit
 - node version: 12.4.0
 - npm version: not used
 - yarn version (if used):  1.19.0
 - vue-cli-plugin-electron-builder version : 1.4.3
 - electron version: 6.1.4
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: none

**Comment by nklayman** [comment]
electron-util is designed to be run in the electron process. Since the test code is run in the jest/mocha process, which is effectively a regular node process, it doesn't work. To run code inside of the renderer process, use `app.webContents.executeJavaScript`. You can use `electron.remote` through this to access the main process.

**Comment by bruceauyeung** [comment]
@nklayman can you bring `yarn electron:unittest` to this wonderful VCP ?
 `yarn electron:unittest` mean that jest tests run within real electron process

**Comment by nklayman** [comment]
No, jest does not support running inside the electron process and tests should be run in a separate process anyways. It is best to have separation between your tests and your tested code.
