### ISSUE TITLE
In macOS and when frame is false, -webkit-app-region:drag is useless.

### ISSUE THREAD

**Issue by RilyZhang** [nklayman/vue-cli-plugin-electron-builder#616]
**Describe the bug**
In macOS and when frame is false, -webkit-app-region:drag is useless.

**To Reproduce**
```
// background.js
  win = new BrowserWindow({
    width: 800,
    height: 600,
    frame: false,
    webPreferences: {
      nodeIntegration: true
    }
  })
```

```
// App.vue
<template>
  <div id="app">
    <div style="-webkit-app-region:drag;background-color: red;">drag me!</div>
    <img alt="Vue logo" src="./assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div>
</template>
```

**Expected behavior**
I can drag window.

**Environment (please complete the following information):**
 - OS and version: macOS 10.15.2
 - node version: v12.13.1
 - npm version: 6.13.4
 - vue-cli-plugin-electron-builder version : 1.4.4
 - electron version: 6.0.0
 - other vue plugins used: @vue/cli: 4.1.2
 - custom config for vcp-electron-builder:

**Comment by RilyZhang** [comment]
This issue only exists on macOS, but there is no problem when vue-cli is ok.

**Comment by nklayman** [comment]
Does the same issue occur when using a non-vue electron app? Try reproducing the error with https://github.com/electron/electron-quick-start.

**Comment by RilyZhang** [comment]
> Does the same issue occur when using a non-vue electron app? Try reproducing the error with https://github.com/electron/electron-quick-start.

I tried it and it was fine.

<img width="521" alt="WX20200106-150743@2x" src="https://user-images.githubusercontent.com/26946173/71801687-9d451780-3096-11ea-8d44-4643b4a71c8e.png">

![1578294423714](https://user-images.githubusercontent.com/26946173/71801697-a504bc00-3096-11ea-82ab-bc6a2efcaabe.jpg)

This problem only exists in vue programs on macos, and sometimes effective.

**Comment by nklayman** [comment]
I can't really help as I don't have a mac, and it works fine on linux. However, I did find this issue: https://github.com/electron/electron/issues/3647, which may be the same as your problem. Try closing devtools or running the built app, and see if that works.

**Comment by RilyZhang** [comment]
> I can't really help as I don't have a mac, and it works fine on linux. However, I did find this issue: [electron/electron#3647](https://github.com/electron/electron/issues/3647), which may be the same as your problem. Try closing devtools or running the built app, and see if that works.

OK, the problem has been solved. Thank you.🙏🙏🙏
