### ISSUE TITLE
Support electron-builder 22.2.0

### ISSUE THREAD

**Issue by ziw** [nklayman/vue-cli-plugin-electron-builder#617]
This feature request is to ask for a dependency bump for electron-builder to ^22.2.0. Since mac os Catalina update, electron-builder fails to build targeting windows (--win). This issue is [fixed](https://github.com/electron-userland/electron-builder/issues/4305#issuecomment-559138959) in electron-builder in 22.2.0.

**Comment by nklayman** [comment]
the [2.0.0 beta](https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-beta.0) uses electron builder 22.
