### ISSUE TITLE
electron:build fails with "nodeIntegration: true" config

### ISSUE THREAD

**Issue by Al-Rozhkov** [nklayman/vue-cli-plugin-electron-builder#622]
First of all huge thanks for 2.0.0 version 👍 

**Describe the bug**
I can't figure out what goes wrong with `yarn electron:build` because there is no clear error message in terminal (see screenshot). `yarn electron:serve` and `yarn build` works fine, `yarn lint` don't show any errors.

**To Reproduce**
I have pretty big project and it is hard to find out the actual problem. I want to debug it but I don't know how. It fails with version 1 every time. Right after 2.0.0-beta release I managed to build the project successfully so I thought it was version 1 problem. Now it fails silently again with v2 😄 

**Screenshots**
![2020-01-12_13-42-52](https://user-images.githubusercontent.com/16973264/72217646-dae7eb80-3541-11ea-999d-5917d45c6ede.png)

**Environment:**
 - OS and version: MacOs Catalina and Windows 10
 - node version: 12.14.1
 - yarn version (if used): 1.21.1
 - vue-cli-plugin-electron-builder version : 1.4.0 and 2.0.0-beta
 - electron version: 7.1.8
 - other vue plugins used: ESLint, Typescript, Unit Jest
 - custom config for vcp-electron-builder: 
```
electronBuilder: {
      nodeIntegration: true,
      builderOptions: {
        win: {
          icon: './public/icon.ico'
        }
      }
    }
```

**Additional context**
My main goal is to find out the cause of the problem.  I'm aware that 1.4.0 is not supposed to work with electron 7. And 2.0.0 is still in beta. So please consider this issue as support request (not a bug request). I was looking for some flag or command for verbose error report in `electron-builder` docs, but didn't succeed.

**Comment by Al-Rozhkov** [comment]
I have an important addition. It is impossible to `yarn electron:build` with `nodeIntegration: true`. And if I turn node integration to `false` it is impossible to `electron:serve`. 

vue-cli-plugin-electron-builder version 2.0.0-beta.1

**Comment by AssetKid** [comment]
In your electron file (`background.js`), what is the `nodeIntegration` value set to?

**Comment by Al-Rozhkov** [comment]
> In your electron file (`background.js`), what is the `nodeIntegration` value set to?

```
...
      webPreferences: {
        nodeIntegration: true
      }
```

**Comment by AssetKid** [comment]
I highly doubt this is the issue since the value is already set to `true` in your project but `nodeIntegration` is now controlled from the `vue.config.js` file.

https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/d547da1230b2092e2991e716e6a5e026d9851e36/generator/templates/base/src/background.js#L20-L24

---

Have you changed the name of the `background.js` file or maybe modified or removed the main property in `package.json`?

**Comment by nklayman** [comment]
@Al-Rozhkov Try updating the `nodeIntegration` key as @AssetKid suggested. I added a migration guide to the [release announcement](https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-beta.0) as well.

**Comment by nklayman** [comment]
The error appears to be coming from the vue cli build. For some reason, it didn't print out the errors themselves. Try running `yarn build` and see if there are any errors there. Also, make sure you are using the latest version of all the vue cli plugins.

**Comment by Al-Rozhkov** [comment]
I replaced `nodeIntegration` property in my `background.ts` with
```nodeIntegration: !!process.env.ELECTRON_NODE_INTEGRATION```
and result is still the same.

- If I have `nodeIntegration: true` in my `vue.config.js` then build is broken (see [screenshot](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/622#issue-548556196) from first message).
- If `nodeIntegration: false` `build` is ok but `serve` is broken with message: `Uncaught ReferenceError...`. Obviously because of disabled node integration.

`yarn build` is done without errors. All plugins is up to date.

**Comment by Al-Rozhkov** [comment]
I found a problem. One native module works in `serve` mode but crashes in `build`. Still don't know why and why vue cli doesn't print that error, but it is not related to this awesome project 😄 

@AssetKid and @nklayman thank you for your help.
