### ISSUE TITLE
How to install 32-bit development environment

### ISSUE THREAD

**Issue by Jerryz0312** [nklayman/vue-cli-plugin-electron-builder#624]
**Is your feature request related to a problem? Please describe.**
In my project, I need to call 32-bit DLL file, but now the default installation is 64 bit. Once I call DLL, error: dynamic linking error: Win32 error 193 will be displayed

**Describe the solution you'd like**
I think use 'vue add --arch=ia32 electron-builder',the default installlation is 32-bit .
my english is so poor,I don't know if you understand me.
thx

**Comment by nklayman** [comment]
Can you create a repository that demonstrates the error so that I can reproduce and debug?

**Comment by Jerryz0312** [comment]
sorry！！
I solved it.
When using NPM, you can choose 32-bit or 64-bit  when installing the dependency.
thx!
