### ISSUE TITLE
Database issue under development mode

### ISSUE THREAD

**Issue by wildwind3325** [nklayman/vue-cli-plugin-electron-builder#627]
I have this issue when using sequelize + mysql2/sqlite3 along with vue + electron, database connection alwasy got timeout error ONLY under development mode.
This is my config file:
```
"configureWebpack": {
      "externals": {
        "sequelize": "require('sequelize')"
      }
    },
"pluginOptions": {
      "electronBuilder": {
        "externals": [
          "sequelize",
          "mysql2"
        ],
```
Without config above I will get a "please install mysql2 manually" error or "pg-hstore was not found", and built package(yarn electron:build) works perfectly, so I guess there must be something wrong with the webpack externals, if I append "mysql2": "require('mysql2')" after the sequelize's line, error will be "sequelize is not defined", and nothing will happen for sqlite3's case, no error but also no query result.

**Comment by wildwind3325** [comment]
After hours of debugging, I think I've got the answer, here's my conn.js:
```
import { Sequelize } from 'sequelize';

const sequelize = new Sequelize('sqlite:D:/xx/xx.db');
console.log('12345');
export default sequelize;
```
When I start the dev process by typing yarn electron:serve command, the log info "12345" appears in the os console window(just below - Local:   http://localhost:8080), not in the chrome's console, and calls to the database always fail at this situation, but if I change some code of conn.js, which will force dev server to reload, like commet the sequelize define, some error info will be printed in the chrome console, and then rollback the code to make it okay, guess what? the "12345" log appears in the chrome console, and everything works fine now.
I think it's a loading strategy issue or config miss or a tiny bug, and I can't find a way to fix it.

**Comment by nklayman** [comment]
I don't have any issues with using sqlite. Please create a repo that demonstrates the error and post the link to it here.

**Comment by wildwind3325** [comment]
> 
> 
> I don't have any issues with using sqlite. Please create a repo that demonstrates the error and post the link to it here.

Please refer to this repo:
[VE Demo](https://github.com/wildwind3325/vedemo)
I've only tested em on windows 7 and windows 10, both are x64.

**Comment by nklayman** [comment]
Your repo works fine for me on Arch linux. Can you send me a screenshot of the error you get?

**Comment by MigFerreira** [comment]
Having a similar issue, not sure if the same. 
Using node-sqlite3, works fine with electron:build but not serve.
Database file is created but no sqlite3 commands execute, like run. Also no error is printed.

Everything works fine when I build for production.

Btw, windows 10, using lastest stable version of vue-cli-plugin-electron-builder and latest of node-sqlite3

**Comment by wildwind3325** [comment]
> 
> 
> Having a similar issue, not sure if the same.
> Using node-sqlite3, works fine with electron:build but not serve.
> Database file is created but no sqlite3 commands execute, like run. Also no error is printed.
> 
> Everything works fine when I build for production.
> 
> Btw, windows 10, using lastest stable version of vue-cli-plugin-electron-builder and latest of node-sqlite3
> 
> Edit: im using sqlite3 directly but just tested sequelize and I have the same issue.

Maybe this only occurs on windows not linux, but it really needs to be fixed.

**Comment by nklayman** [comment]
I tried the VE Demo repo on windows 10 and it worked fine. Try removing your `node_modules` folder and reinstalling deps and trying again.

**Comment by MigFerreira** [comment]
@wildwind3325 can you try the workaround mentioned on issue [698](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/698)
