### ISSUE TITLE
Support history❤ & hash mode

### ISSUE THREAD

**Issue by Akimotorakiyu** [nklayman/vue-cli-plugin-electron-builder#628]
**Is your feature request related to a problem? Please describe.**
support vue history mode and hash mode.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/31165554/72697487-12c2e480-3b7b-11ea-91fb-ab6328a9f692.png)

**Describe alternatives you've considered**
[https://router.vuejs.org/guide/essentials/history-mode.html](https://router.vuejs.org/guide/essentials/history-mode.html)

**Additional context**
> Not to worry: To fix the issue, all you need to do is add a simple catch-all fallback route to your server. If the URL doesn't match any static assets, it should serve the same index.html page that your app lives in. Beautiful, again!
> —— [https://router.vuejs.org/guide/essentials/history-mode.html](https://router.vuejs.org/guide/essentials/history-mode.html)

**Comment by Akimotorakiyu** [comment]
https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/27f5b5c058d7b1f8a1eb15301a9a521fd440eedd/lib/createProtocol.js#L13-L16

change: fallback to `index.html`, and 404 error will deal by the vue application.

en... it should be okay!

**Comment by nklayman** [comment]
The error you quoted is different than the one you get from history mode with electron. The error you get is that the initial route doesn't load. I'm not sure why this is caused, but I don't see a need to fix it as you can't even see the address bar in an electron app so there is no difference between history/hash mode. Why do you need to use history mode over hash?

**Comment by Akimotorakiyu** [comment]
Please look at this screenshot again. I've tested it many times. The reason is that it's said in the document.![](https://user-images.githubusercontent.com/31165554/72697487-12c2e480-3b7b-11ea-91fb-ab6328a9f692.png)

**Comment by nklayman** [comment]
The history mode is not designed to work with electron at all, as a different file loading method is used. See [this page](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#blank-screen-on-builds-but-works-fine-on-serve) for instructions on using history mode for non-electron and hash for electron. Using history mode on electron will require modifying Vue router itself. If you can figure out a way to make it work, feel free to submit a pr, but this isn't something I'm willing to fix myself, so I am going to close this issue.

**Comment by Akimotorakiyu** [comment]
Why are you so stubborn at such an age.

**Comment by m4heshd** [comment]
> Why are you so stubborn at such an age.

Weirdest issue response I've seen on GitHub.

**Comment by JuanNitram** [comment]
> The error you quoted is different than the one you get from history mode with electron. The error you get is that the initial route doesn't load. I'm not sure why this is caused, but I don't see a need to fix it as you can't even see the address bar in an electron app so there is no difference between history/hash mode. Why do you need to use history mode over hash?

I spent about 1 day trying to figure out what was wrong with my configuration. Fortunately I found this discussion, you save my Friday, Man!
