### ISSUE TITLE
created window won't show up in dev mode

### ISSUE THREAD

**Issue by march1993** [nklayman/vue-cli-plugin-electron-builder#629]
Calling `win.show()` solves the problem.

**Environment:**
 - OS and version: win10 x64 1909
 - node version: v12.14.1
 - npm version:
 - yarn version (if used): 1.21.1
 - vue-cli-plugin-electron-builder version :  2.0.0 beta
 - electron version: 7.1.9
 - other vue plugins used: -
 - custom config for vcp-electron-builder:  -
 - (if possible) link to your repo:  -

**Comment by nklayman** [comment]
What happens if you use electron 6.x?

**Comment by march1993** [comment]
> What happens if you use electron 6.x?

Same problem. What I have done:
i) using 6.x + builder 1.x, I got nodeIntegration problem, so I decided upgrade to builder 2.0.0beta
ii) electron 6.x + builder 2.0.0beta  no visible window shows up in development mode
iii) electron 7.x + builder 2.0.0beta also no visible window shows up in development mode. But after I build the project, window shows up.

**Comment by nklayman** [comment]
Try creating a new vue cli app and adding electron and see if it works.

**Comment by march1993** [comment]
> Try creating a new vue cli app and adding electron and see if it works.

`Plugin vue-cli-plugin-electron-builder@beta does not have a generator to invoke`
I run `vue add electron-build@beta`. Is it wrong?

**Comment by nklayman** [comment]
Because of an issue with vue cli, you have to `yarn add vue-cli-plugin-electron-builder@beta -D && vue invoke electron-builder`.

**Comment by march1993** [comment]
> Try creating a new vue cli app and adding electron and see if it works.

It won't work

**Comment by nklayman** [comment]
Try deleting the `%LOCALAPPDATA%/electron/Cache` folder and your local `node_modules` folder, reinstalling deps, and see if it works. My guess is that your electron cache got corrupted.

**Comment by march1993** [comment]
> Try deleting the `%LOCALAPPDATA%/electron/Cache` folder and your local `node_modules` folder, reinstalling deps, and see if it works. My guess is that your electron cache got corrupted.

Ssadly, it's not working...

**Comment by nklayman** [comment]
Have you tried using electron v8?

**Comment by march1993** [comment]
@nklayman  I'm closing this issue. I would reopen the issue after I have done sufficient combinations of electron and the plugin to help locate the problem.
