### ISSUE TITLE
How to run an external web app in a new electron window?

### ISSUE THREAD

**Issue by ismet** [nklayman/vue-cli-plugin-electron-builder#63]
Hi,

Here is my scenario:

I have a standard vue-cli app with vue-cli-plugin-electron builder installed. Both web and electron versions work like a charm.

I have a link in a page. This link is supposed to open another web app built with webpack in a new electron window.

Under `/public`, I created a subfolder called `demo` to include that web app.
The demo folder contents:
![image](https://user-images.githubusercontent.com/109025/44793004-e71e1380-abad-11e8-98c1-b5cc585066f7.png)

The Vue component:
```vue
<html>
  <div>
    <a @click="openExternalWebApp()">Open External Demo App In New Electron Window</a>
  </div>
</html>
<script>
import { remote } from 'electron'
export default {
  methods: {
    openExternalWebApp() {
      let demoWindow = new remote.BrowserWindow({ 
        show: false, 
        width: 1440,
        height: 900,
        webPreferences: { plugins: true }
      })

      demoWindow.loadURL(`${__static}\\demo\\index.html`)
        
      demoWindow.once('ready-to-show', () => {
        demoWindow.show()
      })
    }
  }
}
</script>
```

This code opens the new window. However it doesn't load the external web app properly, since that app is not a static web app (cannot be opened by clicking index.html), but a dynamic web app built with webpack. So, we need to have some webserver or something else to open it.

How can I make this electron app load the external web app in a new window? Any suggestions?

**Comment by nklayman** [comment]
Is your other app a vue-cli 3 app? If so, just build that app as if it were it's own electron app. Then, copy the `dist_electron/bundled` folder contents into demo and it should work fine. You may need to use this as the url as well:

```javascript
url.format({
 protocol: 'file',
 slashes: true,
 pathname: path.join(__static, 'demo/index.html')
})
```

**Comment by ismet** [comment]
No, the other app is not a vue-cli 3 app.
What would be my option in this case?

**Comment by traversng** [comment]
@ismet check out the website, perhaps you can upgrade: https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/upgrading.html

**Comment by nklayman** [comment]
Try setting the `config.output.publicPath` to `./` in the demo app's webpack config and loading with the suggested `url.format`.

**Comment by nklayman** [comment]
@ismet Did this work? I'm going to close this issue anyways as it is not specific to vcp-electron-builder, but will continue to help if you haven't found a solution.

**Comment by JTInfinite** [comment]
Hello, 

Sorry for resurrecting this closed issue but after following the above steps to get a child browser window to open a prebuilt VCP Electron Builder app I get the following console errors:

Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME 
app://./css/chunk-vendors..... etc etc

In my demo apps vue.config.js I have the following based on the advice given above (I did not mutate config.output.publicPath as per the warnings in the vue documentation):

```
  module.exports = {
    publicPath: process.env.NODE_ENV === 'production'
      ? './'
      : '/'
  }
```
Any assistance as to where I might be going wrong would be much appreciated.

**Comment by nklayman** [comment]
@JTInfinite to have multiple browser windows with entirely separate apps, use [pages](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#multiple-pages). Instead of having a second Vue CLI app, just create a new page with it's own Vue instance, and then follow the instructions to launch it.

**Comment by JTInfinite** [comment]
@nklayman  thanks for the quick response dude. Had a chance to go over your comment and recipe this afternoon - the instructions were nice and clear. I am very grateful to you for getting my extra page to work! Lovely!
