### ISSUE TITLE
Error running yarn build:electron ->  no such file or directory (css/font)

### ISSUE THREAD

**Issue by mawiza** [nklayman/vue-cli-plugin-electron-builder#64]
**Describe the bug**
Running yarn serve:electron, everything works like a charm, but when I try to build the packache I get the following error:

 **DONE**  Build complete. The dist_electron/bundled directory is ready to be deployed.
 **INFO**  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html

 **ERROR**  Error: ENOENT: no such file or directory, mkdir '/Users/william/Projects/admin/dist_electron/bundled/css/fonts'
Error: ENOENT: no such file or directory, mkdir '/Users/william/Projects/admin/dist_electron/bundled/css/fonts'
    at Object.fs.mkdirSync (fs.js:905:18)
    at api.registerCommand (/Users/william/Projects/admin/node_modules/vue-cli-plugin-electron-builder/index.js:121:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

And in the vue-cli-plugin-electron-builder -> index.js:

`if (fs.existsSync(api.resolve(outputDir + '/bundled/fonts'))) {
        fs.mkdirSync(api.resolve(outputDir + '/bundled/css/fonts'))
        fs.copySync(
                api.resolve(outputDir + '/bundled/fonts'),
                api.resolve(outputDir + '/bundled/css/fonts')
        )
 }
`

It seems that calling mkdir "css/fonts" on a non existing dir "css" fails, but that might be because I missed something. Any ideas?

**To Reproduce**
Run yarn build:electron

**Expected behavior**
Build the electron app

**Environment (please complete the following information):**
 - OS and version: MacOS High Sierra
 - Node version: 9.3.0
 - npm version: 6.3.0
 - yarn version (if used): 1.6.0
 - vue-cli-plugin-electron-builder version : 1.0.0-rc.2
 - other vue plugins used: vue-cli-plugin-apollo
 - custom config for vcp-electron-builder: None

**Comment by nklayman** [comment]
The css folder should always be generated, so I didnt plan for it not existing. I will go ahead and fix this, should have a patch ready in about an hour.

**Comment by mawiza** [comment]
Good stuff! Thanks Noah. And thanks for your plugin!

**Comment by nklayman** [comment]
Alright, fixed by using `fs.ensureDir` instead of `fs.mkDir`. Since this is such a rare issue, I won't create a release just for it. To use is now, set vcp-electron-builder's version to `nklayman/vue-cli-plugin-electron-builder` (in `package.json`) to install from the GitHub repo. When the next release comes out, just use that as the version instead of the github repo.

**Comment by mawiza** [comment]
Excellent. Thanks Noah

**Comment by nklayman** [comment]
1.0.0-rc.3 has been released, along with this feature/fix. You may now use that as vcp-electron-builder's version instead of the github repo (recommended).
