### ISSUE TITLE
main process hot-reload event

### ISSUE THREAD

**Issue by patriciussanctus** [nklayman/vue-cli-plugin-electron-builder#641]
**Is your feature request related to a problem? Please describe.**
can i subscribe to event "main @hot-reload" (stop -> start electron)? i use "usb-detection" package and want .stopMonitoring(), because without it - my app duplicates and freezes.

**Describe the solution you'd like**
- when DEV changes main-files -> process emit @main-process-reload
OR
- electronBuilder config can has handler with name "mainProcessReloadHandler"

**Describe alternatives you've considered**
In theory i can use chokidar on start app and watch my main-files, but my listeners will be ordered and this not will sync operation.

**Comment by nklayman** [comment]
Try using electron's [built in beforeQuit](https://www.electronjs.org/docs/api/app#event-before-quit) event. It will trigger before the hot reload kills electron so you should be able to run `.stopMonitoring()` and fix the duplication/freezing issue.

**Comment by patriciussanctus** [comment]
@nklayman no, i'm trying, event @before-quit must shots, but without stopMonitoring this does not happen =/

**Comment by patriciussanctus** [comment]
@nklayman I got the right behavior after changes 'electron:serve' command in package.
i make function `killElectron` promised, and now launchElectron executes only after killElectron.then().
PR needs?

**Comment by nklayman** [comment]
Thanks for finding a solution, released it in v`2.0.0-beta.2`.
