### ISSUE TITLE
Error: The specified module could not be found. Native Module

### ISSUE THREAD

**Issue by mitchdennett** [nklayman/vue-cli-plugin-electron-builder#642]
**Describe the bug**
When building on windows my app doesn't run because I get this error

`Uncaught Error: The specified module could not be found.
\\?\C:\Users\mdennett\AppData\Local\Programs\GMC\resources\app.asar.unpacked\node_modules\ibm_db\build\Release\odbc_bindings.node`

The module does exist in that location but from researching I'm guessing the node module paths isn't looking in the app.asar.unpacked folder. 

This works fine on MacOS

**To Reproduce**
create a blank project with IBM_DB dependency and try and build for windows

**Expected behavior**
App should run

**Screenshots**

**Environment (please complete the following information):**
```
{
  "name": "xxx",
  "version": "0.1.11",
  "private": true,
  "scripts": {
    "dev": "NODE_ENV=DEV vue-cli-service serve & sleep 5 && NODE_ENV=DEV electron .",
    "dist": "electron-builder",
    "electron:build": "chmod -R +w ./node_modules/ibm_db && vue-cli-service electron:build",
    "electron:build-win": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "pack": "electron-builder --dir",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps",
    "prod": "NODE_ENV=PROD vue-cli-service serve & sleep 5 && NODE_ENV=PROD electron ."
  },
  "repository": {
    "type": "git",
    "url": "xxxxxxx"
  },
  "main": "background.js",
  "dependencies": {
    "@octokit/rest": "^16.35.0",
    "ansi_up": "^4.0.4",
    "async": "^3.1.0",
    "axios": "^0.19.0",
    "bluebird": "^3.7.2",
    "core-js": "^3.4.3",
    "electron-log": "^4.0.2",
    "electron-updater": "^4.2.0",
    "ibm_db": "git+https://github.com/mitchdennett/node-ibm_db.git",
    "install": "^0.13.0",
    "keytar": "^5.0.0",
    "moment": "^2.24.0",
    "nodemailer": "^6.4.2",
    "npm": "^6.13.4",
    "ssh2": "^0.8.7",
    "vue": "^2.6.10",
    "vue-router": "^3.1.3",
    "vue-select": "^3.4.0",
    "vue-virtual-scroller": "^1.0.0-rc.2",
    "vuex": "^3.1.2"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.1.0",
    "@vue/cli-plugin-eslint": "^4.1.0",
    "@vue/cli-service": "^4.1.0",
    "babel-eslint": "^10.0.3",
    "babel-loader": "^8.0.6",
    "electron": "^7.1.2",
    "electron-builder": "^21.2.0",
    "electron-notarize": "^0.2.1",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "node-loader": "^0.6.0",
    "script-loader": "^0.7.2",
    "tailwindcss": "^1.1.4",
    "vue-cli-plugin-electron-builder": "^1.4.3",
    "vue-template-compiler": "^2.6.10"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ]
}
```

**Additional context**
```module.exports = {
  publicPath: process.env.NODE_ENV === 'production'? `${process.cwd()}/dist/` : '/',
  pluginOptions: {
    electronBuilder: {
      chainWebpackMainProcess: config => {
        config.module
          .rule('node')
          .test(/\.node$/)
          .use('node-loader')
          .loader('node-loader');

          config.module
          .rule('js')
          .test(/\.js$/)
          .use('babel-loader')
          .loader('babel-loader');
      },
      externals: ['ibm_db', 'keytar'],
      builderOptions: {
        "productName": "GMC",
        "appId": "com.greatag.gmc",
        publish: [{
          provider:'github',
          host:'xxx',
          protocol:'https',
          private:true,
          owner:'xxx',
          repo:'xxx',
          token:'XXX'

        }],
        "mac": {
          "category": "public.app-category.developer-tools",
          "hardenedRuntime": true,
          "entitlements": "build/entitlements.mac.plist",
          "entitlementsInherit": "build/entitlements.mac.plist",
          "gatekeeperAssess": false
        },
        win: {
          target: {
            target: "nsis",
            arch: [
              "x64"
            ]
          }
        },
        afterSign:'scripts/notarize.js'
      }
    }
  }
}```

**Comment by iamazik** [comment]
Related https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/640

**Comment by mitchdennett** [comment]
As a temporary fix I have been able to get it to work on Windows by adding `asar: false`. I would like to be able to get it to use asar as that is the recommended way.

**Comment by iamazik** [comment]
I tried with both `process.noAsar = true` and `process.noAsar = false` but didn't work on Mac.

**Comment by nklayman** [comment]
I was able to trace the issue to https://github.com/TooTallNate/node-bindings/issues/35. However, this issue was never really resolved. I did some more digging and found out that it is because the .node file is missing a handful of `.dll`s. To see for yourself, point [dependency walker](http://www.dependencywalker.com/) at the `odbc_bindings.node` file. According to https://github.com/justadudewhohacks/opencv4nodejs/issues/440, which seems to be a similar problem, it is because of issues with visual studio build tools. Some other issues that may be similar are https://github.com/justadudewhohacks/opencv4nodejs/issues/106 and https://github.com/oracle/node-oracledb/issues/712. So it seems like there is an issue with the node-gyp/visual studio build tools config. Since I have no experience with this (I use linux as a daily driver), I don't think I will be able to help. I'd suggest opening an issue on the ibm_db repository as I don't believe this has anything to do with vue cli plugin electron builder.

**Comment by mitchdennett** [comment]
@nklayman That helped so much! I have got it working. I had to fork the node-ibmdb repo and make a change. They were setting the process.env.LIB and process.env.PATH variables so it could find that dependency, but since it was getting unpacked the path was pointing inside the asar, so I changed it to point to the app.asar.unpacked and it all worked. Thanks for pointing me in the right direction

**Comment by nklayman** [comment]
Awesome, glad you could figure it out!

**Comment by Yongle-Fu** [comment]
> @nklayman That helped so much! I have got it working. I had to fork the node-ibmdb repo and make a change. They were setting the process.env.LIB and process.env.PATH variables so it could find that dependency, but since it was getting unpacked the path was pointing inside the asar, so I changed it to point to the app.asar.unpacked and it all worked. Thanks for pointing me in the right direction

use electron-builder run on some Windows 10 encountering this issue, i cannot understand well how to figure it out, hope share the related detail  or solution. Thank you very much.
