### ISSUE TITLE
stopServe() in testWithSpectron() throws setTimeout(...).unref is not a function

### ISSUE THREAD

**Issue by thislooksfun** [nklayman/vue-cli-plugin-electron-builder#647]
**Describe the bug**
Calling `stopServe()` throws an exception `setTimeout(...).unref is not a function`.

**To Reproduce**
Minimal example:
```
import spectron from "spectron";
import testWithSpectron from "vue-cli-plugin-electron-builder/lib/testWithSpectron";
import chai from "chai";
import chaiAsPromised from "chai-as-promised";

chai.should();
chai.use(chaiAsPromised);

describe("Application launch", function() {
  let app;
  let stopServe;

  beforeEach(function() {
    return testWithSpectron(spectron).then(instance => {
      app = instance.app;
      stopServe = instance.stopServe;
    });
  }, 30000);

  beforeEach(function() {
    chaiAsPromised.transferPromiseness = app.transferPromiseness;
  });

  afterEach(function() {
    if (app && app.isRunning()) {
      return stopServe();
    }
  });

  it("opens a window", function() {
    return app.client
      .getWindowCount()
      .should.eventually.have.at.least(1)
      .browserWindow.isMinimized()
      .should.eventually.be.false.browserWindow.isVisible()
      .should.eventually.be.true.browserWindow.getBounds()
      .should.eventually.have.property("width")
      .and.be.above(0)
      .browserWindow.getBounds()
      .should.eventually.have.property("height")
      .and.be.above(0);
  });
});
```

**Expected behavior**
Calling `stopServe()` should not throw an error.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS and version: macOS 10.15.2 (19C57)
 - node version: v12.14.1
 - npm version: v6.13.4
 - yarn version (if used): N/A
 - vue-cli-plugin-electron-builder version: v2.0.0-beta.1
 - electron version: v7.1.11
 - other vue plugins used: See [package.json](https://github.com/thislooksfun/earthdawn/blob/master/package.json)
 - custom config for vcp-electron-builder: N/A
 - (if possible) link to your repo: https://github.com/thislooksfun/earthdawn

**Additional context**
This is due to a [bug in execa](https://github.com/sindresorhus/execa/issues/399) that was [fixed in v4.0.0](https://github.com/sindresorhus/execa/issues/399#issuecomment-567421026).

**Comment by nklayman** [comment]
Unfortunately I cannot update to v`4.0.0` as it requires node 10+. Since vue cli supports v8+, I don't want my plugin to be incompatible. Once vue cli requires v10+, I will upgrade execa.

**Comment by thislooksfun** [comment]
This renders `testWithSpectron()` useless as I can't close electron after the tests complete. Do you have any planned mitigation for this?

**Comment by nklayman** [comment]
I don't think there is anything I can really do, other than wait for vue cli to drop node 8 support. This shouldn't take too long as it is already officially deprecated. In the meantime, I will leave this as a beta release and mark this as a known issue. If you are okay with dropping node 8 support, you can use [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) to use execa v4.
