### ISSUE TITLE
Weird icon

### ISSUE THREAD

**Issue by fridzema** [nklayman/vue-cli-plugin-electron-builder#648]
I came across a weird issue. 
I have setup the icon as stated in the docs with this icon:
![icon](https://user-images.githubusercontent.com/8180660/73944358-b984e000-48f2-11ea-9322-db108a258c39.png)

In my dock it shows fine:
![Screenshot 2020-02-06 at 15 10 34](https://user-images.githubusercontent.com/8180660/73944451-e33e0700-48f2-11ea-9492-c3a2b963718f.png)

But the problem is this:
![Screenshot 2020-02-06 at 15 11 35](https://user-images.githubusercontent.com/8180660/73944506-01a40280-48f3-11ea-8dbe-51ae7619a8d2.png)

Anyone has an idea where to look at?

**Comment by nklayman** [comment]
Did you follow the [icon guide](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#icons)? Check out the [example](https://github.com/nklayman/electron-icon-example) as well and see if that works for you.

**Comment by alfonzm** [comment]
I encountered this as well and solved it by making sure the icons are in the `build/` folder and not in `build/icons` which is where `electron-icon-builder` normally saves the generated icons.

See https://www.electron.build/icons

**Comment by nklayman** [comment]
@fridzema can you try @alfonzm and my suggestions and see if they fix the issue?

**Comment by fridzema** [comment]
@alfonzm that seems to do the trick, thanks! 
@nklayman Thanks for your support!
