### ISSUE TITLE
Whoops - Beta version accidentally published under latest tag

### ISSUE THREAD

**Issue by nklayman** [nklayman/vue-cli-plugin-electron-builder#651]
Related: #649.

Just wanted to make everyone aware that v2.0.0-beta.2 was NOT supposed to be published under the latest tag. I published it 20 hours ago (Feb 6th 8:40ish AM Pacific time). It has now been deprecated and new versions have been published so that the latest and beta tags now have the proper releases. Thanks for everyone in #649 for letting me know something was up, and I hope I didn't confuse anyone too much. If you do want to upgrade to the v2.0 beta, see [the release announcement](https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-beta.0) for upgrading details.

**Comment by Rotinx** [comment]
Thank you :)
