### ISSUE TITLE
Can the module block read local and remote files?

### ISSUE THREAD

**Issue by Zummek** [nklayman/vue-cli-plugin-electron-builder#652]
I'm trying to run this module with tesseract.js (OCR engine). Tesseract is trying to download .traineddata - files from remote or load them locally downloaded. 
I suppose it doesn't work with this module, other modules from vue-cli don't seem to be a problem. I'm trying with another electron vue app without vue-cli-service but with electron-builder which was working fine.
So do You have knowledge about similar problems and their solutions?
I was riding about this problem on [stackoverflow](https://stackoverflow.com/questions/60085573/electron-app-with-vue-and-vue-cli-plugin-electron-builder-cant-working-with-tes)

**Comment by nklayman** [comment]
Have you tried marking tesseract.js as an [external](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules):

```js
// vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['tesseract.js']
    }
  }
}
```

**Comment by Zummek** [comment]
Thank You, it works!

**Comment by ColorfulHorse** [comment]
> Thank You, it works!
are you use tesseract.js with offline? I always get error when use local traineddata

**Comment by Zummek** [comment]
> > are you use tesseract.js with offline? I always get error when use local traineddata

Yes, i'm using Tesseract.js offline. I didn't get error. But it took me a long time to be successful.
Mayby not these traineddata or core files/path
```typescript
      corePath: require('@/assets/tesseract/tesseract-core.wasm.js'),
      langPath: 'src/assets/tesseract/tessdata',
```
