### ISSUE TITLE
Artifact Output Name

### ISSUE THREAD

**Issue by mikecbone** [nklayman/vue-cli-plugin-electron-builder#653]
As far as I can tell, there's no `vue-cli-plugin-electron-builder` way of changing the names of the outputs from build / publishing. 

I assumed there would be an option to add in `vue.config.js` unless I am missing something

**Comment by nklayman** [comment]
See the [docs on changing the output dir](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#changing-the-output-directory) if you just want to change the dir where the output is located. If you want to change the names of the installers/executables, you can place [electron-builder config](https://www.electron.build/configuration/configuration) in your `vue.config.js` as [documented here](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#configuring-electron-builder).
