### ISSUE TITLE
App building without changes included

### ISSUE THREAD

**Issue by Simon-Renault** [nklayman/vue-cli-plugin-electron-builder#654]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS and version:
 - node version: 
 - npm version:
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 
 - electron version: 
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**

**Comment by nklayman** [comment]
Please fill out the template in a new issue.
