### ISSUE TITLE
Electron Setting to run file as admin doesnt work with this plugin

### ISSUE THREAD

**Issue by it154582** [nklayman/vue-cli-plugin-electron-builder#655]
Hello. Im having some trouble with implementing elevated priviledges in the final file. According to electron docs, i have to add this snippet in my package.json file:

"build": {
    "win": {
      "requestedExecutionLevel": "requireAdministrator"
    }
  },

But when i put this in my package.json file and i try to npm run electron:build, i get different errors.Any idea how i can bypass this?

**Comment by nklayman** [comment]
Follow [the docs on configuring electron builder](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#configuring-electron-builder). Set your [vue.config.js](https://cli.vuejs.org/config/#vue-config-js) to the following:

```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
        // options placed here will be merged with default configuration and passed to electron-builder
        win: {
          requestedExecutionLevel: 'requireAdministrator'
        }
      }
    }
  }
}
```
