### ISSUE TITLE
Mac install problem: Couldn't find package "7zip-bin@~5.0.3"

### ISSUE THREAD

**Issue by RogerHestad** [nklayman/vue-cli-plugin-electron-builder#657]
**Describe the bug**
Trying to install electron-builder on Mac I get the error message `Couldn't find package '7zip-bin@~5.0.3" required by "builder-util@21.2.0" on the "npm" registry.'`

Tested on a new project created in Vue UI adding SCSS and ESLint + Prettier. No code changes done.

I am using Yarn.

**To Reproduce**
Tried installing via command line:
`vue add electron-builder`
also tried `yarn add -D vue-cli-plugin-electron-builder`

Trying to add via Vue UI it stalls when "Invoking vue-cli-plugin-electron-builder".

**Screenshots**
![image](https://user-images.githubusercontent.com/34653827/74332096-59c88200-4d95-11ea-8cd4-052a38234ba5.png)

**Environment (please complete the following information):**
 - OS and version: MacOS 10.15.3
 - node version: Tried both 11.12.0 and 12.16.0 (installed via nvm)
 - npm version: 6.7.0 and 6.13.4 (depends on node version)
 - yarn version (if used): 1.21.1
 - vue-cli-plugin-electron-builder version : 1.4.5
 - other vue plugins used: 
@vue/cli-service v4.2.2
@vue/cli-plugin-babel v4.2.2
@vue/cli-plugin-eslint v.4.2.2

***package.json:***

```
{
  "name": "electron-test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.6.4",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.2.0",
    "@vue/cli-plugin-eslint": "^4.2.0",
    "@vue/cli-service": "^4.2.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.0.3",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.1.1",
    "eslint-plugin-vue": "^6.1.2",
    "node-sass": "^4.12.0",
    "prettier": "^1.19.1",
    "sass-loader": "^8.0.2",
    "vue-template-compiler": "^2.6.11"
  }
}
```

**Comment by ishulev** [comment]
Hey @RogerHestad ,

I created an app a couple of days ago, following the instructions on this site and all was good. Also using Yarn. Weirdly enough, today I tried cloning said repo and running `yarn install` and got the same error as you.

I got it fixed by using `npm i`. I guess it's a yarn messup?

**Comment by RogerHestad** [comment]
Thanks for the tip @ishulev.

It seems it might be a temporary hiccup with yarn...? First I tried making a new project with npm and electron-builder plugin installed correctly. Just to double check I tried to make a new yarn project and it installed there as well! Then I tried installing in the project where it failed yesterday and that also went well...

Weird, but problem solved, I guess :)
