### ISSUE TITLE
Unable to create websocket connection for mqtt.js

### ISSUE THREAD

**Issue by ysfscream** [nklayman/vue-cli-plugin-electron-builder#658]
My url is `ws://127.0.0.1:8083/mqtt`. No problem in browser and sample electron project, but not in vue-electron, and I don't see any error messages.

![image](https://user-images.githubusercontent.com/21299158/74409610-11cb5d00-4e72-11ea-8af3-33f74cafaf7a.png)

When I open the Developer Tool Console, I use it like this and can also connect
```js
const mqtt = require('mqtt')
mqtt.connect('ws://127.0.0.1:8083/mqtt', opts)
```

![image](https://user-images.githubusercontent.com/21299158/74409710-40e1ce80-4e72-11ea-90cf-e88432b0b5d4.png)

### using:

- electron: 5.0.0
- vue.js: 2.6.10
- vue.js + electron: https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/#installation

Is there something I should do with the proxy config? If you can help me, I will be very grateful!

**Comment by nklayman** [comment]
It may help to mark `mqtt` as an external. This will stop webpack from bundling it. To do so, set your [vue.config.js](https://cli.vuejs.org/config/#vue-config-js) to:
```js

module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['mqtt']
    }
  }
}
```

**Comment by ysfscream** [comment]
@nklayman 👍Thanks!!! It's works for me, I appreciate it.
