### ISSUE TITLE
Failed to register a ServiceWorker

### ISSUE THREAD

**Issue by iamazik** [nklayman/vue-cli-plugin-electron-builder#659]
**Describe the bug**
Seeing the following error in the app build but not in serve for the service worker.

```
app.5305371c.js:1 Error during service worker registration: TypeError: Failed to register a ServiceWorker: The URL protocol of the current origin ('app://.') is not supported.
```

**To Reproduce**

1. Make sure that you create a Vue project by selecting the Progressive Web App
2. Add the Vue CLI Electron Builder Plugin
3. Run `yarn electron:build` to build the app
4. Open the console and that will show you a reference error
5. Enable the `nodeIntegration: true` in the `vue.config.js` to avoid this error
6. Build the app again
7. A blank screen, open the console and that will show the service worker register error

**Expected behavior**
No error for service worker registration after building the app.

**Screenshots**
<img width="912" alt="Screenshot 2020-02-15 at 2 03 21 AM" src="https://user-images.githubusercontent.com/8946603/74563614-5ef51f00-4f97-11ea-9958-a6aea1235458.png">

**Environment (please complete the following information):**
 - OS and version: macOS Catalina v10.15.3
 - node version: 13.8.0
 - npm version: 6.13.7
- @vue/cli 4.2.2
 - yarn version (if used): 1.22.0
 - vue-cli-plugin-electron-builder version : 2.0.0-beta.3
 - electron version: 7.0.0
 - other vue plugins used: N/A
 - custom config for vcp-electron-builder:
```javascript
module.exports = {
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true
    }
  }
};
```

**Additional information**
Commenting out the `import "./registerServiceWorker";` from the `main.js` and building the app seems fixed the error but still doesn't work when we need the service worker.

**Comment by nklayman** [comment]
You will need to disable the pwa plugin in electron mode. Set your vue.config.js to:
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      chainWebpackRendererProcess(config) {
        config.plugins.delete('workbox')
        config.plugins.delete('pwa')
      }
    }
  }
}
```
and update the `if` condition in `registerServiceWorker.js`:
```js
if (process.env.NODE_ENV === 'production' && !process.env.IS_ELECTRON) {
```
This will disable it in electron but it will still work in non-electron builds.
