### ISSUE TITLE
Electron 8.0.0

### ISSUE THREAD

**Issue by mikecbone** [nklayman/vue-cli-plugin-electron-builder#660]
I know Electron 7.0.0 is just being supported on the latest beta version, but [Electron 8.0.0](https://www.electronjs.org/blog/electron-8-0) is now out. Are there plans / ETAs for supporting that through the plugin?

**Comment by nklayman** [comment]
`2.0.0-beta.4`

**Comment by nklayman** [comment]
If you have an existing project, just update the electron version and, if you are using it, update spectron to v10.
