### ISSUE TITLE
[Question] Best practice for testWithSpectron

### ISSUE THREAD

**Issue by baruchiro** [nklayman/vue-cli-plugin-electron-builder#661]
> vue-cli-plugin-electron-builder exports a `testWithSpectron` function. This function will run `electron:serve`, but instead of launching electron, a new Spectron Application will be created and attached to the dev server. This can be used to run e2e tests with Spectron.

If I using `testWithSpectron` in `beforeEach` function to get a clean instance for each test, the suite takes a long time since any test runs `electron:serve`.

Is there another practice to run the suite? Maybe run `testWithSpectron` in `beforeAll` and "clean" the instance in `beforeEach`?

**Comment by nklayman** [comment]
You have a few options to "clean" the instance:
1. Reload the window with `app.browserWindow.reload()`. Note that you may have to wait for the reload to finish before running tests, as I'm not sure that it returns a promise.
2. Restart the entire electron app with `await app.restart()`. This will return a promise that resolves when the app has restarted.
3. Use the `noSpectron` arg with `testWithSpectron`, and only launch the spectron instance between tests. [This code](https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/master/lib/testWithSpectron.js#L42-L60) demonstrates how spectron is launched and with what options. This will remove the overhead of restarting the dev server.
