### ISSUE TITLE
build production env  the flash error

### ISSUE THREAD

**Issue by 82318179** [nklayman/vue-cli-plugin-electron-builder#662]
Reference flash DLL in public folder，the method as 

`let pepFlashPlayer = "";
if (process.platform == "win32") {
  if (process.arch == "x64") {
    pepFlashPlayer = path.join(__static, "pepflashplayer64.dll");
  } else {
    pepFlashPlayer = path.join(__static, "pepflashplayer32.dll");
  }
}
app.commandLine.appendSwitch("ppapi-flash-path", pepFlashPlayer);
app.commandLine.appendSwitch("ppapi-flash-version", "32.0.0.238");`

this  Can operate correctly  in dev env

but can not run in production env(use yarn run  electron:build)
Tips can not find flash 
but the address is right  like 
`C:\Users\King\Desktop\mybrowser\dist_electron\win-unpacked\resources\app.asar\pepflashplayer64.dll`

**Comment by nklayman** [comment]
Electron builder puts all of your files in an asar archive. This may not be compatible with `pepFlashPlayer`. Set your [vue.config.js](https://cli.vuejs.org/config/#vue-config-js) to:
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
        asarUnpack: ['some.dll']
      }
    }
  }
}
```
Then, get the path with:
```
path.join(__static, 'some.dll').replace('app.asar', 'app.asar.unpacked')
```

This will keep `some.dll` outside of the asar.
