### ISSUE TITLE
How to use Electron Release Server for AutoUpdate with VCP electron-builder ?

### ISSUE THREAD

**Issue by Dahkenangnon** [nklayman/vue-cli-plugin-electron-builder#665]
**Is your feature request related to a problem? Please describe.**
I have an electron app built with VCP electron builder and want to use my own (node js) server with 
[Electron Release Server](https://github.com/ArekSredzki/electron-release-server) but when i'd explored [the VCP doc ](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#auto-update), it is described only the use case of Github as backend.

**Describe the solution you'd like**
I aske for link, tips of any advice to use Electron Release Server to AutoUpdate my VCP electron builder.

Thank for your answers

**Comment by nklayman** [comment]
The electron builder [auto update guide](https://www.electron.build/auto-update) and [publish config docs](https://www.electron.build/configuration/publish) have more details on setting up a custom release server.
