### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by Jerryz0312** [nklayman/vue-cli-plugin-electron-builder#668]
**Describe the bug**
my steps：
1. vue create new-project
2. vue add electron-builder
3. yarn electron:serve is ok !
4. yarn electron:build is failed !

**result**
 ERROR  Error: C:\Users\XXY-ZJ\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.3.2\Bin\makensis.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Output:

Output:
Command line defined: "APP_ID=com.electron.electron-vue-ex"
Command line defined: "APP_GUID=1e4c37a8-8e81-5312-b04e-f4639faf16bc"
Command line defined: "UNINSTALL_APP_KEY=1e4c37a8-8e81-5312-b04e-f4639faf16bc"
Command line defined: "PRODUCT_NAME=electron-vue-ex"
Command line defined: "PRODUCT_FILENAME=electron-vue-ex"
Command line defined: "APP_FILENAME=electron-vue-ex"
Command line defined: "APP_DESCRIPTION="
Command line defined: "VERSION=0.1.0"
Command line defined: "PROJECT_DIR=E:\ʾ��\electron-vue-ex"
Command line defined: "BUILD_RESOURCES_DIR=E:\ʾ��\electron-vue-ex\build"
Command line defined: "APP_PACKAGE_NAME=electron-vue-ex"
Command line defined: "APP_64=E:\ʾ��\electron-vue-ex\dist_electron\electron-vue-ex-0.1.0-x64.nsis.7z"
Command line defined: "APP_64_NAME=electron-vue-ex-0.1.0-x64.nsis.7z"
Command line defined: "APP_64_HASH=9005E9D9C0E24F2BA9820E1D905565F1B2419EE6AD698A8FB7667DE3BEEAE3BBA89D1C51B76F8943AD3472ED27805CAA76F037D63C2AA3268561B18FDE3EE814"
Command line defined: "APP_INSTALLER_STORE_FILE=electron-vue-ex-updater\installer.exe"
Command line defined: "COMPRESSION_METHOD=7z"
Command line defined: "ONE_CLICK"
Command line defined: "RUN_AFTER_FINISH"
Command line defined: "SHORTCUT_NAME=electron-vue-ex"
Command line defined: "UNINSTALL_DISPLAY_NAME=electron-vue-ex 0.1.0"
Command line defined: "ESTIMATED_SIZE=145426"
Command line defined: "COMPRESS=auto"
Command line defined: "BUILD_UNINSTALLER"
Command line defined: "UNINSTALLER_OUT_FILE=E:\ʾ��\electron-vue-ex\dist_electron\__uninstaller-nsis-electron-vue-ex.ex
e"
Processing config: C:\Users\XXY-ZJ\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.3.2\nsisconf.nsh
Processing script file: "<stdin>" (ACP)

Error output:

Error output:
!include: could not find: "E:\示例\electron-vue-ex\node_modules\app-builder-lib\templates\nsis\include\StdUtils.nsh"
Error in script "<stdin>" on line 1 -- aborting creation process

    at ChildProcess.<anonymous> (E:\示例\electron-vue-ex\node_modules\builder-util\src\util.ts:239:14)
    at Object.onceWrapper (events.js:300:26)
    at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:476:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
error Command failed with exit code 1.

**Environment (please complete the following information):**
 - window 10:
 - node 12.13.0: 
 - npm 6.13.7:
 - yarn 1.22.0: 
 - vue-cli-plugin-electron-builder ~1.4.5 : 
 - electron ^6.0.0:

**Comment by nklayman** [comment]
Try `rm -r node_modules && yarn`. Looks like a dependency file is missing.
