### ISSUE TITLE
Can't import .mjs modules in the main process

### ISSUE THREAD

**Issue by TotomInc** [nklayman/vue-cli-plugin-electron-builder#67]
**Describe the bug**
Some libraries include Ecmascript Modules as `.mjs` files, it is impossible to import them.

```
./node_modules/node-fetch/lib/index.mjs 496:11-22
Can\'t import the named export \'PassThrough\' from non EcmaScript module (only default export is available) at HarmonyImportSpecifierDependency._getErrors 
(/Users/totominc/Desktop/Git/poe-mapper-assistant/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:90:6)
at HarmonyImportSpecifierDependency.getErrors (/Users/totominc/Desktop/Git/poe-mapper-assistant/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
at Compilation.reportDependencyErrorsAndWarnings (/Users/totominc/Desktop/Git/poe-mapper-assistant/node_modules/webpack/lib/Compilation.js:1334:22)
at Compilation.finish (/Users/totominc/Desktop/Git/poe-mapper-assistant/node_modules/webpack/lib/Compilation.js:1136:9)
at hooks.make.callAsync.err (/Users/totominc/Desktop/Git/poe-mapper-assistant/node_modules/webpack/lib/Compiler.js:545:17)
at _err0 (eval at create (/Users/totominc/Desktop/Git/poe-mapper-assistant/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
at _addModuleChain (/Users/totominc/Desktop/Git/poe-mapper-assistant/node_modules/webpack/lib/Compilation.js:1064:12)
at processModuleDependencies.err (/Users/totominc/Desktop/Git/poe-mapper-assistant/node_modules/webpack/lib/Compilation.js:980:9)
at process._tickCallback (internal/process/next_tick.js:61:11)
@ ./src/background.ts\n @ multi ./src/background.ts
```

**To Reproduce**
1. `yarn add node-fetch && yarn add @types/node-fetch -D`
2.
```typescript
import fetch from 'node-fetch';

fetch('https://google.fr')
	.then(response => console.log(response))
	.then(body => console.log(body));
```
3. `yarn serve:electron`

**Expected behavior**
It should import `node-fetch` successfully, same for all `.ejs` modules.

**Environment (please complete the following information):**
 - OS and version: Mac OS X 10.13.6
 - Node version: 10.8.0
 - npm version: 6.2.0
 - yarn version (if used): 1.9.4
 - vue-cli-plugin-electron-builder version: latest
 - other vue plugins used: typescript
 - custom config for vcp-electron-builder: none
 - (if possible) link to your repo: repo private, sorry

**Comment by TotomInc** [comment]
Apparently you can fix it on webpack ([from this issue comment](https://github.com/bitinn/node-fetch/issues/493#issuecomment-407985160)):

```javascript
{
  type: 'javascript/auto',
  test: /\.mjs$/,
  use: []
}
```

**Comment by nklayman** [comment]
Can you try this in the renderer process as well and see if that works?

**Comment by TotomInc** [comment]
It works fine in the renderer process, here the sample code I used to test:


```javascript
import fetch from 'node-fetch';

fetch('https://google.fr')
	.then(res => console.log(res));
```

I also tried to add a custom loader in the `vue.config.js` (as specified in the issue-comment) but it doesn't work:

```javascript
module.exports = {
	chainWebpack: (config) => {
		config.module.rule('javascript/auto').test(/\.mjs$/).end();
	},
};
```

**Comment by TotomInc** [comment]
The issue seems to be a lot more complex and not anymore related to `.mjs` modules, setting the following config is working fine:

```javascript
// vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
        chainWebpackMainProcess: (config) => {
          config.module.rule('javascript/auto').test(/\.mjs$/);
        },
      }
    }
  }
}
```

The issue I have now is kinda related to `node-fetch` or `webpack`, it is exactly the same problem as [here](https://github.com/bitinn/node-fetch/issues/41).

I'm closing the issue since `.mjs` files are successfully imported, and I will look to use another HTTP fetch module.

**Comment by TotomInc** [comment]
I have also fixed my issue of HTTP module by using [`isomorphic-fetch`](https://github.com/matthew-andrews/isomorphic-fetch). However, there is still a warning (that may be caused by webpack since) when running `serve:electron`:

```
WARNING in ./node_modules/encoding/lib/iconv-loader.js 9:12-34
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/encoding/lib/encoding.js
 @ ./node_modules/node-fetch/lib/body.js
 @ ./node_modules/node-fetch/index.js
 @ ./node_modules/isomorphic-fetch/fetch-npm-node.js
 @ ./src/electron-background/http.ts
 @ ./src/electron-background/index.ts
 @ ./src/background.ts
 @ multi ./src/background.ts
```

For a better understanding, I am using `fetch()` (from `isomorphic-fetch`) in `src/electron-background/http.ts` in a `httpRequest` function which is exported in `src/background.ts`.

When digging into `encoding/lib/iconv-loader.js`, it seems the following lines cause the error:

```javascript
try {
    // this is to fool browserify so it doesn't try (in vain) to install iconv.
    iconv_package = 'iconv';
    Iconv = require(iconv_package).Iconv;
} catch (E) {
    // node-iconv not present
}
```

Anyway, this is related to [andris9/encoding](https://github.com/andris9/encoding).

**Comment by nklayman** [comment]
Add this to `electronBuilder`'s plugin option key:

```
  externals: ['iconv-loader']
```

**Comment by TotomInc** [comment]
I've fixed the issue by adding a postinstall script which edit iconv from the node_modules directory, it may not be the best thing to do but was recommended in the iconv repo until the maintainer take care of the issue.

By adding the externals array, did this means you actually implemented [webpack-node-externals](https://www.npmjs.com/package/webpack-node-externals) in the plugin?

**Comment by nklayman** [comment]
No, I set the externals manually. It is much faster to bundle with webpack so I only externalize native deps. I can't always check  if a dep is native so you may have to list it manually.
