### ISSUE TITLE
Nightmare JS wont work with the vue plugin

### ISSUE THREAD

**Issue by it154582** [nklayman/vue-cli-plugin-electron-builder#675]
Edit 2: Problem is solved by reverting _dirname : false to true in vue.config.js.SOLVED!
Edit : "Apparently,as i search more and more, i found out that it has to do with webpack's __dirname config. Im trying to make it work with this plugin with the help of the site's docs but i still havent managed to make it. According to the docs, i have to put my webpack config into this: 

 module.exports = {
  configureWebpack{
   node: {
   __dirname : false
}
}
} alongside with pluginOptions in vue.config.js but it still doesnt work"

So apparently, even putting nightmare in externals like this : 

![capture1](https://user-images.githubusercontent.com/56912034/75578666-e9944e80-5a6c-11ea-839b-ae8d073daeeb.PNG)

Nightmare wont work with this simple code : 

![captru2](https://user-images.githubusercontent.com/56912034/75578802-3a0bac00-5a6d-11ea-80d6-4e12ad3f15cf.PNG)

Im getting this error : 

![capture3](https://user-images.githubusercontent.com/56912034/75578875-5ad40180-5a6d-11ea-87e0-ec8834cdc755.PNG)

I have also tried setting the electronPath in the nightmare instance manually (as suggested from other github posts) but console still gives me an error. This only happens with this vue plugin-electron :/

**Comment by nklayman** [comment]
So to confirm, settings `__dirname` to true fixed it?

**Comment by it154582** [comment]
Yeah. Just combine my Edit 1 with my Edit 2
