### ISSUE TITLE
Is it possible to serve through https

### ISSUE THREAD

**Issue by ldsenow** [nklayman/vue-cli-plugin-electron-builder#678]
**Is your feature request related to a problem? Please describe.**
As I am wishing to serve through https and it is able to do that in vue-cli-service serve --https
I am wondering the possibility of doing such in this electron plugin

**Describe the solution you'd like**
vue-cli-service electron:serve --https

**Comment by nklayman** [comment]
Included in v1.4.6. You will need to add `app.commandLine.appendSwitch('ignore-certificate-errors', 'true');` to your `background.js` file and then launch electron with the `--https` arg.
