### ISSUE TITLE
Object has been destroyed after closing app

### ISSUE THREAD

**Issue by filipcieminski** [nklayman/vue-cli-plugin-electron-builder#681]
**Describe the bug**
Hello! I dont know if it's a bug, or my missunderstanding of some things works, but I'll give it a try.

I have problem with error after closing my app. I've spend a lot of time searching for fix, but without success. Whenever I'm closing my app I'm getting error "Object has been destroyed" from WebContents.sendToFrame at Object.event.reply. I assume It's reffering to my ipcMain.on(). I'm listening on "get-content" channel which is triggered by my front-end every 1 minute. My ipcMain is fetching data from API, but if there is no internet connection, it's taking the data from already downloaded file. I can see, that the last stack of this error is refering to readFileAfterClose, so it's may be related. How to prevent this error to happen?

Basically, that's how my listener looks like
```js
ipcMain.on("get-content", (event, arg) => {
  getContent()
    .then(response => {
      const downloadedContent = Buffer.from(JSON.stringify(response.data));
      new Promise((resolve, reject) => {
        fs.readFile(path.resolve(`${app.getPath("userData")}/content.json`), (err, data) => {
          if (checksum(downloadedContent) !== checksum(data)) {
            resolve(true);
          }
          if (err) {
            reject(err);
          }
        });
      }).then(() => {
        downloadContent(response.data, event, arg);
      });
    })
    .catch(error => {
      if (error) {
        fs.readFile(
          path.resolve(`${app.getPath("userData")}/content.json`),
          (err, data) => {
            if (err) {
              console.log(err);
            }
            event.reply("get-content", JSON.parse(data));
          }
        );
      }
    });
});
```

The line which is reffered in error message is the last line of this listener.

I have tried to make ` ipcMain.removeAllListeners(['get-content']);` but it's not working.

**Expected behavior**
Close the app without any errors

**Screenshots**
![obraz](https://user-images.githubusercontent.com/51356553/76604855-cad39480-650f-11ea-94d0-29a5a506073a.png)

**Environment (please complete the following information):**
 - OS and version: Win 10
 - node version:  13.3
 - npm version: 6.13
 - vue-cli-plugin-electron-builder version : 
 - electron version: 6.0

**Comment by nklayman** [comment]
It seems like the error may be caused if you are trying to use IPC after the browser window has been closed. Are you using multiple windows in your app? I can't reproduce the error just from your code snippet, if you could create a sample project that demos the error I will be able to help more.

**Comment by filipcieminski** [comment]
Im using only one window, but to be honest, the error is gone. Dunno why. For now I don't need any more assistance :) Thanks!

**Comment by yehtut-indexzero** [comment]
@filipcieminski how u resolved this issue.
