### ISSUE TITLE
nodeIntegration required for ipcRenderer

### ISSUE THREAD

**Issue by iamazik** [nklayman/vue-cli-plugin-electron-builder#683]
**Describe the bug**
When attempting to import `ipcRenderer` from a render process, the following error occurs in the browser console:
```shell
Uncaught ReferenceError: __dirname is not defined
    at eval (index.js?bdb9:4)
    at Object../node_modules/electron/index.js (chunk-vendors.js:1058)
    at __webpack_require__ (app.js:790)
    at fn (app.js:151)
    at eval (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/Home.vue?vue&type=script&lang=js&:3)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/Home.vue?vue&type=script&lang=js& (app.js:955)
    at __webpack_require__ (app.js:790)
    at fn (app.js:151)
    at eval (Home.vue?8a6a:1)
    at Module../src/views/Home.vue?vue&type=script&lang=js& (app.js:1201)
```

**To Reproduce**
Simply just try use the ipcRenderer from a render process. For example:
`Home.vue`
```javascript
import { ipcRenderer } from "electron";

export default {
  name: "Home",
  components: {
    HelloWorld
  },
  created() {
    console.log(ipcRenderer);
  }
};
```

**Expected behavior**
No errors and a working application.

**Screenshots**
<img width="1552" alt="Screenshot 2020-03-17 at 5 18 59 AM" src="https://user-images.githubusercontent.com/8946603/76807520-d1fbea80-680e-11ea-80c5-0ad9d7fce475.png">

**Environment (please complete the following information):**
 - OS and version: macOS Catalina, version: 10.15.3 (19D76)
 - node version: v13.10.1
 - npm version: 6.14.2
 - yarn version (if used): 1.22.4
 - vue-cli-plugin-electron-builder version : 2.0.0-beta.5
 - electron version: 8.0.0 or 8.1.1
 - other vue plugins used: N/A
 - custom config for vcp-electron-builder: N/A
 - (if possible) link to your repo: N/A

**Additional context**
I can confirm the relevant error occurs in a fresh installation of a Vue app with the Vue CLI Plugin Electron Builder project.

**Comment by iamazik** [comment]
I had to enable the `nodeIntegration` from the `vue.config.js` file.

```javascript
module.exports = {
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true
    }
  }
}
```

**Comment by nklayman** [comment]
I am going to reopen this as `nodeIntegration` should not be required for `ipcRenderer`.

**Comment by nklayman** [comment]
Nevermind, `ipcRenderer` requires `nodeIntegration`. If you don't want `nodeIntegration` but do want `ipcRenderer` you can follow these instructions: https://github.com/electron/electron/issues/5113#issuecomment-208713736.

**Comment by viniciusvieir** [comment]
> I had to enable the `nodeIntegration` from the `vue.config.js` file.
> 
> ```js
> module.exports = {
>   pluginOptions: {
>     electronBuilder: {
>       nodeIntegration: true
>     }
>   }
> }
> ```

Even after enabling nodeIntegration on the vue.config.js file I still get the same error
