### ISSUE TITLE
Dynamic import of native addons

### ISSUE THREAD

**Issue by hosnar** [nklayman/vue-cli-plugin-electron-builder#685]
Hi, i'm not sure this is the place to ask this, but i didn't know where else to do it.

I'm trying to require native node module in my Electron main process. This works fine on development where path is static:
> const addon = require('./addon.node')

But when i package production build, my path isn't static anymore, since it differs by OS. So i must use dynamic path like this:
> const addon = require(process.resourcesPath + '/native/addon.node')

When i run this packaged app i keep getting error:
> Error: Cannot find module

Also, i'm using extraResources to move my addon to Resources folder when packaging.

I tried different workarounds, i also tried native-ext-loader and node-loader for webpack but it doesn't seem to help.

Any help would be greatly appreciated. Thank you.

**Comment by nklayman** [comment]
You will want to place your `addon.node` in the `public` folder. Then, you can access it in serve and build with `path.join(__static, 'addon.node')`. See the [docs on static assets](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#handling-static-assets) for more details.

**Comment by hosnar** [comment]
Thank you very much for your answer. But this still doesn't seem to work for me, i get this error:
> Error: Cannot find module '/Applications/MyApp.app/Contents/Resources/app.asar/addon.node'

Path must be incorrect, since app.asar is not a directory.

Code i used:
```
const loadAddon = () => {
  if (!process.env.WEBPACK_DEV_SERVER_URL) {
    return require(path.join(__static, 'addon.node'))
  } else {
    // Dev
  }
}

const proc = loadAddon()
```

For webpack loader i'm using:
```
chainWebpackMainProcess: config => {
  config.module.rule('node').test(/\.node$/).use('node-loader').loader('node-loader')
}
```

And i've put addon.node in public directory.

Do you see anything i could be doing wrong? Thank you

**Comment by nklayman** [comment]
Looks like this is a duplicate of #334. Try the [solution that worked there](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/334#issuecomment-514207626) and see if that helps.

**Comment by hosnar** [comment]
Thank you very much for you help! With the solution you linked, i could make it work like this:
```
const loadAddonFile = () => {
  const path = require('path')
  const filePath = `/addons/addon-${process.platform}.node`
  if (process.env.WEBPACK_DEV_SERVER_URL) {
    // eslint-disable-next-line
    return __non_webpack_require__(path.join(process.cwd(), filePath))
  } else {
    // eslint-disable-next-line
    return __non_webpack_require__(path.join(process.resourcesPath, filePath))
  }
}

const addon = loadAddonFile()
```

I used os.platform since addon is compiled for each OS. And i still ended up using extraResources as mentioned before, without webpack node loader. This probably isn't the best way to go about it but it was the only way i could make it work. So, just posting my solution, as it might help someone else maybe.

Thanks again. Cheers

**Comment by nklayman** [comment]
Just a heads up, `process.cwd()` resolves to the dir you are in when you launch the executable, so I definitely wouldn't use it to get a path to a resource. Try using [app.getPath](https://www.electronjs.org/docs/api/app#appgetpathname) instead.

**Comment by hosnar** [comment]
Oh, ok. Thank you for the heads up, i'll fix it.

**Comment by netcore-jroger** [comment]
I use `__non_webpack_require__` function to dynamic load module.
