### ISSUE TITLE
worker can't import file in main process

### ISSUE THREAD

**Issue by Yuliang-Lee** [nklayman/vue-cli-plugin-electron-builder#687]
**Describe the bug**
main process worker can't import file in production,  there is no problem in development

**To Reproduce**
const {
  Worker
} = require('worker_threads')
```
ipcMain.on('separate:begin-separate', async(event, options) => {
  await beginSeparate(event, options)
})

function beginSeparate(event, options) {
  const worker = new Worker('./src/components/separator/logic.worker.js', {
  })
  // do something
}
```

**Expected behavior**
import file 

**Screenshots**
![image](https://user-images.githubusercontent.com/6936358/77292842-07776b00-6d1c-11ea-8363-b58ad3896696.png)

![企业微信截图_15849485784610](https://user-images.githubusercontent.com/6936358/77292771-e9116f80-6d1b-11ea-9be6-ec38e47eef3c.png)

**Environment (please complete the following information):**
 - OS and version: windows10
 - node version: 12
 - npm version: 6
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 1.3.0
 - electron version:  8.0.0
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**

**Comment by nklayman** [comment]
Here is a solved issue with a guide on using web workers: https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/486#issuecomment-534968789. See if that works for you.
