### ISSUE TITLE
XHR request cancelled with electron 9 beta 9

### ISSUE THREAD

**Issue by Brutia** [nklayman/vue-cli-plugin-electron-builder#689]
**Describe the bug**
Since electron 9 can open pdf (see : https://github.com/electron/electron/issues/12337), I tried to use vue-cli-plugin-electron-builder with electron 9. 

But every xhr requests are canceled in production mode, ie after running `npm run electron:build` and launching the app.

I know electron 9 is not supported by vue-cli-plugin-electron-builder but sending requests with axios without any vue instance is working.

**NB** : it's working with electron 9 beta 5

![image](https://user-images.githubusercontent.com/11478702/77327572-b7000d80-6d1b-11ea-8f6f-411e2ba02db2.png)

Is this bug due to electron 9, vue-cli-plugin-electron-builder or both?

**To Reproduce**

* Create empty vue app : `vue create empty-vue-app`
* Add vue-cli-plugin-electron-builder : `vue add vue-cli-plugin-electron-builder`
* Add vue-resource : `npm i vue-resource`
* Make an XHR request in HelloWorld.vue

or clone this project : https://github.com/Brutia/electron-vue-empty-app (I use google URL, normally you should get a  CORS error, but the request is canceled)

Replace 9.0.0-beta.9 in package.json by 9.0.0-beta.5 and it will work as expected

**Expected behavior**
Request send and response received

**Environment (please complete the following information):**
 - OS and version: Windows 10
 - node version: 12.16.1
 - npm version: 6.13.4
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 1.4.6
 - electron version: 9.0.0-beta.9
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: https://github.com/Brutia/electron-vue-empty-app

**Comment by Brutia** [comment]
Update : same issue with `9.0.0-beta.10`

**Comment by nklayman** [comment]
It worked fine for me on linux:
![image](https://user-images.githubusercontent.com/12448243/77866626-b4ecf180-71e8-11ea-9cb7-652a18ff89d3.png)
I will have to try on windows and see if that causes it. Since it works fine with a different version of electron, my guess is that it is a problem with electron, not this plugin. Try creating an electron app without this plugin and see if you get the same error.

**Comment by Brutia** [comment]
Sorry if I wasn't clear but this only happens in PRODUCTION mode

**Comment by nklayman** [comment]
When I built the app I got the error. This definitely looks like an issue with electron as it only shows up for certain versions and the plugin wouldn't cause this. You should open an issue on their repo instead.

**Comment by Brutia** [comment]
Finally, I used this instead: https://github.com/SimulatedGREG/electron-vue and it's working with any beta of electron.
