### ISSUE TITLE
node-hid

### ISSUE THREAD

**Issue by Wolrab1** [nklayman/vue-cli-plugin-electron-builder#69]
**Describe the bug**
npm run build:electron fails when the package node-hid is installed.

**To Reproduce**
Setup a new project, install node-hid and run build:electron

**Expected behavior**
Successful build

**Environment (please complete the following information):**
 - OS and version: Windows 10
 - Node version: v8.11.3
 - npm version: 5.6.0
 - vue-cli-plugin-electron-builder version : ^1.0.0-rc.2
 - other vue plugins used: node-hid ^0.7.3

**Comment by nklayman** [comment]
It works fine for me, try this:
```
//vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['node-hid']
    }
  }
}
```

**Comment by Wolrab1** [comment]
Thanks for that! I haven't got a vue.config.js file in project?

**Comment by nklayman** [comment]
Re-invoke the generator of vue-cli-plugin-electron-builder and then re-install your deps. This will build all the native deps for you.
