### ISSUE TITLE
Cli-highlight, dependency of typeorm, breaks production build

### ISSUE THREAD

**Issue by cooperfrench95** [nklayman/vue-cli-plugin-electron-builder#690]
**Describe the bug**
Launching app fails after build because of an error with `cli-highlight` node module which is a dependency of typeorm.

**To Reproduce**

1. Create electron project using this
2. `npm i typeorm`
3. `npm run electron:build`
4. `cd` into dist_electron folder and run created app image (or whatever exe or dmg thing it creates on windows/mac)
5. Get the following error

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: chalk_1.default.Instance is not a constructor
    at Object.<anonymous> (/tmp/.mount_molteoj6HNLv/resources/app.asar/node_modules/cli-highlight/dist/theme.js:12:13)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/tmp/.mount_molteoj6HNLv/resources/app.asar/node_modules/cli-highlight/dist/index.js:19:15)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
```

**Expected behavior**
App launches.

**Environment (please complete the following information):**
 - OS and version: Ubuntu 18.04
 - node version: 12.6.0
 - npm version: 6.14.2 
 - vue-cli-plugin-electron-builder version : 1.4.6
 - electron version: 6.1.9
 - other vue plugins used: vuetify, babel, eslint, vuex, router 
 - custom config for vcp-electron-builder: 
```javascript
module.exports = {
  pluginOptions: {
    electronBuilder: {
      customFileProtocol: './',
      externals: [
        'sqlite3',
        'typeorm',
      ],
      builderOptions: {
        extraResources: [
          { from: 'src/worker', to: './worker' }
        ]
      }
    }
  }
}

```

**Additional context**
The problem appears to come from here in cli-highlight's theme.js:
```javascript
"use strict";
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
var chalk_1 = __importStar(require("chalk"));
var chalk = new chalk_1.default.Instance({ level: Math.min(chalk_1.default.level, 1 /* Basic */) });
```

This is a compiled result of the following:

```javascript
import { Chalk, default as _chalk, Level } from 'chalk'

const chalk = new _chalk.Instance({ level: Math.min(_chalk.level, Level.Basic) })
```

What I don't understand is that this error does not occur on `electron:serve` even when I put the same code into background.js, install chalk and console log everything. The constructor works fine.

**Comment by rathboma** [comment]
I came here to post this exact thing.
This is due to Electron 7+ changing how it bundles the code. Do this -- change electron to v6 in your package.json and it will work

**Comment by cooperfrench95** [comment]
I am currently using version 6 actually.

I have migrations disabled in the config, I run them programatically on startup

**Comment by cooperfrench95** [comment]
https://github.com/typeorm/typeorm/issues/5757 - I created this issue as well on the same topic.

**Comment by rathboma** [comment]
Oh, how do you run them programmatically? I haven't figured out how to run them with webpack

**Comment by cooperfrench95** [comment]
Basically have typeorm as an external, compile the entities to a form babel will accept and then place the generated migrations somewhere in the build and set their location in ormconfig.js in production mode.

Then before creating any windows `await connection.runMigrations()`.

Granted I haven't tested this on production yet

**Comment by rathboma** [comment]
Interesting. I gave up and just made an array of sal statements to run, but I'll have to try that

**Comment by nklayman** [comment]
@cooperfrench95 what parts of `typeorm` are you importing? It works fine for me when I imported `Entity, PrimaryGeneratedColumn, Column`. Try removing your `customFileProtocol` config as well.

**Comment by cooperfrench95** [comment]
`createConnection, Entity, PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn, OneToMany, ManyToOne, RelationId, Index, JoinColumn, AfterLoad, JoinTable, OneToOne, ManyToMany`

Removing the `customFileProtocol` did not help.

**Comment by rathboma** [comment]
@cooperfrench95 remove the 'runMigrations()' section of your code then try. I think its when the code tries to scan the fs for the migration files.

**Comment by cooperfrench95** [comment]
@rathboma That did not fix it unfortunately.

**Comment by nklayman** [comment]
@cooperfrench95 I'm not getting the error, even with all the imports you mentioned. Try creating a blank project and importing `typeorm` and see if you get an error.

**Comment by nkprince007** [comment]
I have the same issue when using with `typeorm`

**Comment by nklayman** [comment]
If someone can provide an example repo that demonstrates the problem I will be able to debug the it, but until then I can't do anything as I am unable to reproduce the issue.

**Comment by cooperfrench95** [comment]
@nklayman Reproduction link: https://github.com/cooperfrench95/typeorm-issue

Instructions are in the readme.

**Comment by cooperfrench95** [comment]
I found a solution.

```bash
rm -rf node_modules/
rm -rf dist_electron/
rm package-lock.json
```

Edit your package.json adding the following:
```javascript
"resolutions": {
  "**/cli-highlight": "2.1.4",
  "**/chalk": "3.0.0"
}
```

Then `yarn` and `yarn run electron:build` and it runs.

**Comment by nklayman** [comment]
You shouldn't need to remove the files, just set the resolution and run yarn. That shows that the problem is with the dependency, not this plugin.

**Comment by jayvdb** [comment]
I needed to go a bit further than @cooperfrench95's solution, by elevating `chalk` and `cli-highlight` to top level dependencies, and using older versions consistently instead of newer versions.

This was because I had other dependencies which also used older versions of chalk, and upgrading them caused cascading new problems, and I gave up at `ts-loader` (https://github.com/TypeStrong/ts-loader/issues/1092).

```diff
diff --git a/package.json b/package.json
index ba0b127..ade6360 100644
--- a/package.json
+++ b/package.json
@@ -23,6 +23,8 @@
   "dependencies": {
     "@fortawesome/fontawesome-free": "^5.13.0",
     "bwip-js": "^1.7.1",
+    "chalk": "2.4.2",
+    "cli-highlight": "2.1.2",
     "core-js": "^3.6.4",
     "d3": "^5.7.0",
     "electron": "^6.0.0",
@@ -76,6 +78,10 @@
     "vue-template-compiler": "^2.6.11",
     "vuetify-loader": "^1.3.0"
   },
+  "resolutions": {
+    "cli-highlight": "2.1.2",
+    "**/chalk": "2.4.2"
+  },
   "homepage": "https://github.com/foo/bar",
   "keywords": [
     "electron",
```

Anyone who cant use `yarn`, you may like to try https://github.com/rogeriochaves/npm-force-resolutions .  I had limited success with it before switching to yarn.
