### ISSUE TITLE
ArtifactName mac os build error

### ISSUE THREAD

**Issue by 0x77dev** [nklayman/vue-cli-plugin-electron-builder#691]
**Describe the bug**
https://github.com/electron-userland/electron-builder/issues/3812
electron-builder bug on mac os build with `artifactName`

**To Reproduce**
https://github.com/0x77dev/iQOS-Desktop/runs/533154291

**Expected behavior**
mac os zip build

**Screenshots**
see link in reproduce.

**Environment (please complete the following information):**
 - OS and version: macos-latest
 - node version: 10
 - npm version: latest
 - yarn version (if used): latest 
 - vue-cli-plugin-electron-builder version :  latest
 - electron version: ^6.0.0
 - other vue plugins used: vuetify
 - custom config for vcp-electron-builder: nope
 - (if possible) link to your repo: https://github.com/0x77dev/iQOS-Desktop

**Additional context**
https://github.com/electron-userland/electron-builder/issues/3812

**Comment by 0x77dev** [comment]
https://github.com/SimulatedGREG/electron-vue/issues/266

**Comment by nklayman** [comment]
Unfortunately I do not own a mac and therefore cannot reproduce the issue on my own, so there is very little I can do to help here. Please post your solution if you resolve this issue.

**Comment by 0x77dev** [comment]
You can use GitHub Actions to test it out, example in repo: https://github.com/0x77dev/iQOS-Desktop

**Comment by nklayman** [comment]
@0x77dev can you try using v2.0 of this plugin? It uses a more recent electron-builder version and might solve your issue.

**Comment by 0x77dev** [comment]
Solved.

**Comment by 0x77dev** [comment]
Also do not include `@` in artifact name, 7zip does not work properly with paths that contains `@` symbol.
