### ISSUE TITLE
Duplicate Fonts in Bundle only on electron:build

### ISSUE THREAD

**Issue by Clocktown** [nklayman/vue-cli-plugin-electron-builder#694]
**Describe the bug**
`npm run electron:build` duplicates local fonts, creating a bundle that contains them in `fonts` as well as in `css/fonts`. This also results in a larger asar package.

**To Reproduce**
```
vue create my-project
cd my-project
vue add electron-builder
npm install roboto-fontface
```
And then add `import "roboto-fontface/css/roboto/roboto-fontface.css"` to `src/main.js`

**Expected behavior**
Should produce the same bundle that `npm run build` does, which only contains the fonts in the `fonts` folder.

**Environment:**
 - OS and version: Windows 10
 - node version: v12.16.1
 - npm version: 6.13.4
 - vue-cli-plugin-electron-builder version : vue-cli-plugin-electron-builder@1.4.6
 - electron version: ^6.0.0

**Comment by nklayman** [comment]
I added the duplication a few years ago because I was having font import errors on `electron:build`. Since the error appears to have disappeared now, I have removed the duplication in the 2.0.0 beta as it could possibly be a breaking change.
