### ISSUE TITLE
Unable to expose gc

### ISSUE THREAD

**Issue by mrjackwills** [nklayman/vue-cli-plugin-electron-builder#696]
**Describe the bug**
I am trying to expose the global.gc, so that I can manually invoke the garbage collector.

**To Reproduce**
*As detailed in https://www.electronjs.org/docs/api/command-line-switches*

snippet of vue.config.js (both configs tried):
```pluginOptions: {
  electronBuilder: {
	  mainProcessArgs: ['--js-flags="--expose-gc"'],
    // mainProcessArgs: ['--expose-gc']
    }
}
```

in background.js
```
app.commandLine.appendSwitch('js-flags', '--expose-gc')
```

**Expected behavior**
Repo provided - The main process should now have access to the global.gc method, however inspecting the global object shows that gc is not present. Calling global.gc() results in an error

**Environment (please complete the following information):**
 - OS: Windows 10 pro 1909 - 18363.720
 - node version: v12.16.1
 - npm version: 6.13.4
 - vue-cli-plugin-electron-builder version : 1.4.6
 - electron version: 6.0.0
 - link to your repo: https://github.com/mrjackwills/expose-gc

**Comment by nklayman** [comment]
If you add the `app.commandLine.appendSwitch('js-flags', '--expose-gc')` to `background.js` you will be able to access `window.gc` from the renderer process. I don't think there is a way to access from the main process.
