### ISSUE TITLE
Default app folder name

### ISSUE THREAD

**Issue by hosnar** [nklayman/vue-cli-plugin-electron-builder#697]
Hello,

is there a way to change the app folder name on build? We are working on an app that uses re-branding, so the name of the app is set upon build and i would like to also change it's default app directory upon build. And by default directory i mean these:
MacOS: ~/Library/ApplicationSupport/AppName
Windows: %appdata%/.../AppName

Currently this name is being taken from package.json and i don't think i can dynamically change it there.

Thank you.

**Comment by nklayman** [comment]
The only alternative to changing the `package.json` would be to use a [custom nsis script](https://www.electron.build/configuration/nsis#custom-nsis-script). You can open an issue on [electron-builder](https://github.com/electron-userland/electron-builder) (the tool this plugin uses to build the installer) requesting a way to change the install dir.
