### ISSUE TITLE
SQLite3 not working in windows serve mode

### ISSUE THREAD

**Issue by MigFerreira** [nklayman/vue-cli-plugin-electron-builder#698]
**Describe the bug**
When executing SQLite sample code (switching :memory: to local db) database gets created but no other command runs. This issue only happens on electron:serve mode, if I build it everything works fine.

Tested the same code on my brothers mac and everything works fine in both serve and build. This seems like a windows 10 only problem.

Unfortunately, even with node-sqlite3 in verbose nothing gets printed in console.

**Environment (please complete the following information):**
 - OS and version: Windows 10 x64
 - node version: 12.16.1
 - npm version: 6.13.4
 - vue-cli-plugin-electron-builder version : 1.4.6
 - electron version: 6.0.0
 - other vue plugins used: router; vuex; vuetify
 - custom config for vcp-electron-builder:

**Comment by nklayman** [comment]
Can you please provide a code snippet that throws the error? I'm not sure exactly how to reproduce the issue.

**Comment by MigFerreira** [comment]
Nothing gets printed on console. Even if I place some console.logs in node-sqlite3 callbacks they don't get called at all.
If you have any additional idea on how to debug this I'm all ears

**Comment by nklayman** [comment]
That's fine, I can run it on Windows if necessary.

**Comment by MigFerreira** [comment]
Here it is, tested its not working in serve mode but is in build mode.
[https://github.com/MigFerreira/sqlite-demo](https://github.com/MigFerreira/sqlite-demo)

Code is in HelloWorld component and database is created in project root.

Hope this is helpfull

**Comment by nklayman** [comment]
If I use the sample code from the `sqlite3` readme it works fine:
```js

**Comment by nklayman** [comment]
I take that back, it doesn't work until I reload the page, then the existing code works fine as well.

**Comment by nklayman** [comment]
Since the error only shows up in dev mode, as a (slightly ugly) workaround you can just automatically refresh the page by adding this snippet after line 26 of your `background.js`:
```js
const finishLoadListener = () => {
  win.webContents.reload()
  win.webContents.removeListener('did-finish-load', finishLoadListener)
}
win.webContents.on('did-finish-load', finishLoadListener)
```

**Comment by MigFerreira** [comment]
Workaround no longer functional after updating to electron 9.x.
Refresh leads to blank app with disconnected devtools.

**Comment by nklayman** [comment]
I tested the solution on electron 9 and it worked fine for me. Maybe try creating a fresh project.

**Comment by MigFerreira** [comment]
OK, seems to be issue with sqlite3 and electron9, noithing gets logged so I assumed it was refresh, my bad.
