### ISSUE TITLE
SQLite package has not been found installed! while using with typeorm

### ISSUE THREAD

**Issue by michaelspeed** [nklayman/vue-cli-plugin-electron-builder#699]
**Describe the bug**
I have typeorm , sqlite3 installed
have invoked  `vue invoke electron-builder`
still the browser outputs - 

> `DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
>     at new DriverPackageNotInstalledError (webpack-internal:///./node_modules/typeorm/browser/error/DriverPackageNotInstalledError.js:11:28)
>     at SqliteDriver.loadDependencies (webpack-internal:///./node_modules/typeorm/browser/driver/sqlite/SqliteDriver.js:126:19)
>     at new SqliteDriver (webpack-internal:///./node_modules/typeorm/browser/driver/sqlite/SqliteDriver.js:32:15)
>     at DriverFactory.create (webpack-internal:///./node_modules/typeorm/browser/driver/DriverFactory.js:51:24)
>     at new Connection (webpack-internal:///./node_modules/typeorm/browser/connection/Connection.js:74:98)
>     at ConnectionManager.create (webpack-internal:///./node_modules/typeorm/browser/connection/ConnectionManager.js:59:26)
>     at eval (webpack-internal:///./node_modules/typeorm/browser/index.js:499:66)
>     at step (webpack-internal:///./node_modules/tslib/tslib.es6.js:123:23)
>     at Object.eval [as next] (webpack-internal:///./node_modules/tslib/tslib.es6.js:104:53)
>     at eval (webpack-internal:///./node_modules/tslib/tslib.es6.js:97:71)`

i even added - 

> module.exports = {
    pluginOptions: {
        electronBuilder: {
            // List native deps here if they don't work
            externals: ['sqlite3'],
            // If you are using Yarn Workspaces, you may have multiple node_modules folders
            // List them all here so that VCP Electron Builder can find them
            nodeModulesPath: ['../../node_modules', './node_modules']
        }
    },
    chainWebpack: config => {
        config.merge({
            externals: {
                sqlite3: 'commonjs sqlite3'
            }
        })
    }
};

to the vue.config.js

**Environment (please complete the following information):**
 - OS and version: MacOS
 - node version: 12.14.0
 - npm version: 6.10.3
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : @latest
 - electron version: 6.0.0

**Comment by MigFerreira** [comment]
just to make sure you get this error in electron and not browser right?

**Comment by michaelspeed** [comment]
yup in electron , here are the screen shots
![Screenshot at Apr 04 02-36-20](https://user-images.githubusercontent.com/1447958/78405087-5dea8080-761d-11ea-9a74-a7c58af4c45f.png)

![Screenshot at Apr 04 02-37-27](https://user-images.githubusercontent.com/1447958/78405047-4a3f1a00-761d-11ea-9858-8390468cdf80.png)

**Comment by nklayman** [comment]
@michaelspeed Try keeping the `pluginOptions` config in your `vue.config.js`, but remove the `chainWebpack` config. The `externals` array configures externals for you.

**Comment by michaelspeed** [comment]
even if i remove the chainWebpack it still fails to load the sqlite3 package,
although sequelize with sqlite3 works fine

now the vue.config.js looks like this
but no typeorm

```
 module.exports = {
    configureWebpack: {
        externals: {
            sequelize: "require('sequelize')",
            'sequelize-typescript': "require('sequelize-typescript')",
            sqlite3: "commonjs sqlite3"
        },
    },
    pluginOptions: {
        electronBuilder: {
            externals: ['sequelize', 'sequelize-typescript', 'sqlite3'],
        }
    },
};
```

**Comment by nklayman** [comment]
@michaelspeed can you give me a code snippet that I can use to reproduce the error so I can debug it further?

**Comment by michaelspeed** [comment]
[copy.zip](https://github.com/nklayman/vue-cli-plugin-electron-builder/files/4432215/copy.zip)
Here is a zip with my ongoing setup

**Comment by nklayman** [comment]
Worked fine for me on arch linux, unfortunately I don't have a mac to test on:
![image](https://user-images.githubusercontent.com/12448243/78460454-c6654c00-7675-11ea-8a1c-8ef99280831a.png)

You can try running `rm -rf node_modules && yarn` to reinstall deps and fix any issues that may have been caused by a bad yarn install.

**Comment by michaelspeed** [comment]
Sorry my bad, i gave you the sequelize folder! which works fine with sqlite3
please try this, this is the typeorm which cannot find sqlite3
[copy-typeorm.zip](https://github.com/nklayman/vue-cli-plugin-electron-builder/files/4432419/copy-typeorm.zip)

**Comment by nklayman** [comment]
You need to add `typeorm` as an external. When I set the `vue.config.js` to the following, it worked fine:
```js
module.exports = {
    pluginOptions: {
        electronBuilder: {
            externals: ['typeorm', 'sequelize', 'sequelize-typescript', 'sqlite3'],
        }
    },
};
```

**Comment by michaelspeed** [comment]
thanks a lot it worked
