### ISSUE TITLE
Webpack configuration extensions containing regular expressions are serialized incorrectly

### ISSUE THREAD

**Issue by TAGC** [nklayman/vue-cli-plugin-electron-builder#7]
I'm trying to create a project built on this boilerplate that uses TypeScript and the class-based API for defining Vue components:

```html
<script lang="ts">
import Vue from 'vue'
import Component from 'vue-class-component'

const HelloWorldProps = Vue.extend({
  props: {
    msg: String
  }
})

@Component
export default class HelloWorldComponent extends HelloWorldProps {
  name: String = 'HelloWorld'
}
</script>
```

I want to be able to reference these components in `main.ts`, which is the renderer entry-point:

```typescript
import Vue from 'vue'
import App from './App'

Vue.config.productionTip = false

new Vue({
  render: h => h(App)
}).$mount('#app')
```

However, to do this I need to override the configuration used for `ts-loader` fed to WebPack. According to the docs, I need to do something like:

```js
{
  test: /\.tsx?$/,
  loader: "ts-loader",
  options: {
    appendTsSuffixTo: [/\.vue$/]
  }
}
```

From your README, I've tried to create a `vue.config.js` file in the project root directory with this content:

```js
module.exports = {
  configureWebpack: {
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          loader: 'ts-loader',
          options: {
            appendTsSuffixTo: [/\.vue$/]
          }
        }
      ]
    }
  },
  pluginOptions: {
    electronBuilder: {
      webpackConfig: {
        module: {
          rules: [
            {
              test: /\.tsx?$/,
              loader: 'ts-loader',
              options: {
                appendTsSuffixTo: [/\.vue$/]
              }
            }
          ]
        }
      }
    }
  }
};
```

However, when I run `npm run serve:electron` I get this error during the renderer build:

```
┏ Renderer -------------------

  Error: Excepted condition but got [object Object] in {
    "test": {},
    "include": "undefined",
    "exclude": "undefined"
  }
    at Function.normalizeRule (/home/<me>/Documents/my-electron-app/node_modules/webpack/lib/RuleSet.js:122:11)
```

I'm wondering if you happen to know how I can configure my project so that `electron-builder` merges these with the configurations it provides to `electron-webpack`.

**Comment by TAGC** [comment]
Okay, so it seems if I have this in `vue.config.js`:

```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      webpackConfig: {
        module: {
          rules: [
            {
              test: /\.tsx?$/,
              loader: 'ts-loader',
              options: {
                appendTsSuffixTo: [/\.vue$/]
              }
            }
          ]
        }
      }
    }
  }
};
```
Then `electron-builder` will generate this (incorrect) webpack config which is causing the error I see:

```js
module.exports = {
  module: {
    rules: [
      { test: {}, loader: "ts-loader", options: { appendTsSuffixTo: [{}] } }
    ]
  },
  resolve: {
    alias: {
      "@": "/home/davidfallah/Documents/my-electron-app/src",
      vue$: "vue/dist/vue.runtime.esm.js"
    }
  }
};
```

Assuming this is a bug and not a misunderstanding on my part, I'd imagine it's somewhere here:

https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/cc606da4630278b9041cdc7025bc7a7f7df46b1a/index.js#L94-L123

Not sure why, though. Seems like some sort of issue causing regular expressions to be converted to empty objects. I probably need to tweak some Babel settings.

**Comment by TAGC** [comment]
Tried it out and it's still broken with 0.2.4. Given this `vue.config.js`:

```js
module.exports = {
    pluginOptions: {
      electronBuilder: {
        webpackConfig: {
          module: {
            rules: [
              {
                test: /\.tsx?$/,
                loader: 'ts-loader',
                options: {
                  appendTsSuffixTo: [/\.vue$/]
                }
              }
            ]
          }
        }
      }
    }
  };
```

I end up with this being generated:

```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        loader: "ts-loader",
        options: { appendTsSuffixTo: ["__REGEXP /\\.vue$/"] }
      }
    ]
  },
  resolve: {
    alias: {
      "@": "/home/davidfallah/Documents/atm-prototype/src",
      vue$: "vue/dist/vue.runtime.esm.js"
    }
  }
};
```

The first regular expression got converted fine, but the second one didn't. The issue is that you the [regex you use](https://github.com/nklayman/vue-cli-plugin-electron-builder/commit/1c1e081d09bac7bb46d7d61b7b7ca457c2cc0255#diff-168726dbe96b3ce427e7fedce31bb0bcR124) performs a lookahead assertion for a comma, which will only happen if there's properties appearing afterwards. https://regex101.com/r/Xds6OQ/2/

**Comment by nklayman** [comment]
I added the g (global) tag so that it matches all instances, and made the lookahead for the comma optional. I tested it and it works now.
