### ISSUE TITLE
Add argument to skip bundle

### ISSUE THREAD

**Issue by erguotou520** [nklayman/vue-cli-plugin-electron-builder#70]
**Is your feature request related to a problem? Please describe.**
I need a argument to passed to the npm scripts to skip webpack bundle but just do electron build. As some times the bundle is done before, but the build fails. So I want to skip the bundle step.

**Describe the solution you'd like**
Command like `npm run build:electron --skip`?

**Comment by nklayman** [comment]
This feature will be available in the next release. To use it now, set vcp-electron-builder's version to nklayman/vue-cli-plugin-electron-builder to install from the github repo.

**Comment by nklayman** [comment]
The command is `--skipBundle`.

**Comment by nklayman** [comment]
1.0.0-rc.3 has been released, along with this feature/fix. You may now use that as vcp-electron-builder's version instead of the github repo (recommended).

**Comment by erguotou520** [comment]
ok
