### ISSUE TITLE
auto-updater only uninstalls instead of update

### ISSUE THREAD

**Issue by NoFrosty** [nklayman/vue-cli-plugin-electron-builder#700]
**Describe the bug**
Auto updater is not working. When an update exist, it download it and wait for user to quit.
But after quit, it uninstall everything and install nothing.
This happens only if we install on all user (Program Files)
(I don't know if this is due to electron-builder or vue-cli-electron-builder)

**To Reproduce**
Create app.
Install app on all users (Program Files)
Create patch
Open app
It download the update
Quit application after receiving notification

**Expected behavior**
Download and update correctly the application.

**Environment (please complete the following information):**
 - OS and version: Windows 10 Pro 1903
 - node version: v12.13.0
 - npm version: 6.12.0
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 1.4
 - electron version: 8.2

**Additional context**
Workaround :
Opening the application with administrator permission resolve the problem.

**Comment by nklayman** [comment]
Make sure that you haven't set `allowElevation` to `false` in the [NSIS config](https://www.electron.build/configuration/nsis). Also, try uninstalling the app and removing the updater as it is not removed by default by deleting the `%LOCALAPPDATA%/app-name-updater` folder. The entire update process is handled by electron-builder, so if none of the above solutions work I'd recommend opening an issue on [their repo](https://github.com/electron-userland/electron-builder) instead.
