### ISSUE TITLE
[Question] Call createProtocol at start of background.js

### ISSUE THREAD

**Issue by eschirtz** [nklayman/vue-cli-plugin-electron-builder#701]
Hey,

I noticed in your examples that this pattern is often used when creating windows. 

```
if (!createdAppProtocol) {
      createProtocol('app');
      createdAppProtocol = true;
    }
```
Can also be seen in action [here](https://github.com/nklayman/electron-multipage-example/blob/master/src/background.js)

I was wondering why this is done, and if it's possible for me to just pull out `createProtocol` to be called one time in `background.js` before any windows are created.

How does this call relate to individual window instances? I'm currently refactoring my window logic to be in separate files and it seems a little redundant to have to `createProtocol` for each window. 

Thanks!

**Comment by nklayman** [comment]
As per the [electron docs](https://www.electronjs.org/docs/api/protocol):
> Note: All methods unless specified can only be used after the ready event of the app module gets emitted.

This means that you should be able to move it to the `app.on('ready')` listener instead. Thanks for the suggestion, I'll update the electron-multipage-example repo with this change as it is much simpler.
