### ISSUE TITLE
Uncaught TypeError: Cannot read property 'app' of undefined

### ISSUE THREAD

**Issue by Yuliang-Lee** [nklayman/vue-cli-plugin-electron-builder#703]
**Describe the bug**
I use electron-log tool in the project, the error occurs only for a packaged application but not in development

```
Uncaught TypeError: Cannot read property 'app' of undefined
```

**To Reproduce**
https://github.com/Yuliang-Lee/electron-vue-log-debug

**Expected behavior**
no errors

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: windows 10 & mac
 - node version: v12
 - npm version: 6
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 2.0.0
 - electron version: 8.0.0
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo:  https://github.com/Yuliang-Lee/electron-vue-log-debug

**Additional context**
I filed an issue under electron-log and the feedback is a compilation issue，https://github.com/megahertz/electron-log/issues/187#issuecomment-610176463

**Comment by nklayman** [comment]
If you don't need to use the `process.env.BASE_URL`, you can disable it by adding the following config under the `pluginOptions` of your `vue.config.js`:
```js
electronBuilder: {
      chainWebpackRendererProcess(config) {
        config.plugin('define').tap(args => {
          delete args[0]['process.env'].BASE_URL
          return args
        })
      }
    },
```

You may have to delete your `node_modules` folder and reinstall deps after adding that snippet for some reason, likely related to caching.
