### ISSUE TITLE
electron-builder 22.4.1 is installed in the ^2.0.0-beta.0 version.

### ISSUE THREAD

**Issue by minkkkjoon** [nklayman/vue-cli-plugin-electron-builder#707]
The release said 22.2.0 would be installed, but 22.4.1 was installed.

i need 22.2.0 ;(

**Comment by nklayman** [comment]
The latest minor version will automatically be installed, so `^22.2.0` will resolve to `22.4.1`. If you need a specific version, you can use [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/):

(`package.json`)
```json
{
  "resolutions": {
    "vue-cli-plugin-electron-builder/electron-builder": "22.2.0"
  }
}

**Comment by Aysnine** [comment]
When will use 22x in this repo ?
