### ISSUE TITLE
Error: sha512 checksum mismatch when download completed on windows.

### ISSUE THREAD

**Issue by joenix** [nklayman/vue-cli-plugin-electron-builder#708]
**Describe the bug**
Error: sha512 checksum mismatch when download completed on windows.

### the validation code:

- dependency: electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js
- electron-updater version: `v4.3.0`
- line: 411

```js
if (this._actual !== this.expected) {
  throw (0, _index().newError)(
    `${this.algorithm} checksum mismatch, expected ${this.expected}, got ${this._actual}`,
    "ERR_CHECKSUM_MISMATCH"
  );
}
```

**To Reproduce**

1. checkForUpdates on `ready`
2. downloadUpdate after `update-available`

**Expected behavior**
sha512 validate pass

**Screenshots**

`Error: sha512 checksum mismatch, expected ZTibGDsqQuP835Tpt6Ii3geSSzHD6vWsITC29RTKc+f+5SDag0QZmFRGDuAdNfEpmk/9X70oglYmzEQYqVICew==, got +zFxCWvPfoqy4C231x9olXpflrt4aKsAOFUg3bBVl4jL8urx7dgvwtIrztyUFSgHLFyJwads7eNuj4gxUveAlw== at e.newError (C:\Program Files\resources\app.asar\background.js:2:5792) at E.validate (C:\Program Files\resources\app.asar\background.js:2:132050) at E._flush (C:\Program Files\resources\app.asar\background.js:2:131851) at E.prefinish (_stream_transform.js:140:10) at E.emit (events.js:210:5) at prefinish (_stream_writable.js:645:14) at finishMaybe (_stream_writable.js:653:5) at endWritable (_stream_writable.js:673:3) at E.Writable.end (_stream_writable.js:604:5) at i.onend (_stream_readable.js:691:10)`

**Environment (please complete the following information):**

- OS and version: `Catalina 10.15.4`
- node version: `v13.12.0`
- npm version: `v6.9.0`
- yarn version (if used): `1.22.4`
- vue-cli-plugin-electron-builder version : `v2.0.0-beta.6`
- electron version: `v8.2.1`
- other vue plugins used:
  - vue: `v2.6.11`
  - vue-electron: `v1.0.6`
- custom config for vcp-electron-builder:

```js
productName: "channel-cooperation",
appId: "com.cooperation.mac",
asar: true,
nsis: {
	oneClick: false,
	perMachine: true,
	allowToChangeInstallationDirectory: true,
	createDesktopShortcut: true,
	runAfterFinish: true,
	installerIcon: "public/favicon.ico",
	installerSidebar: "public/favicon.png",
	uninstallerIcon: "public/favicon.ico",
	installerHeaderIcon: "public/favicon.ico",
	createStartMenuShortcut: true,
	shortcutName: "channel-cooperation",
	artifactName: "${name}-${version}-${os}.${ext}"
},
publish: [
	{
		provider: "generic",
		channel: "latest",
		url: "xxx"
	}
],
mac: {
	icon: "public/favicon.png",
	target: ["default"]
},
win: {
	verifyUpdateCodeSignature: false,
	icon: "public/favicon.ico",
	target: [
		{
			target: "nsis"
		}
	]
},

extends: null
```

- (if possible) link to your repo: `confidentiality agreement`

**Additional context**
`extremely anxious`

**Comment by nklayman** [comment]
The update process is handled by electron-builder, you should open an issue on [their repository](https://github.com/electron-userland/electron-builder) instead.
