### ISSUE TITLE
what command to use to build electron app for all three or for selected platform looking forward for you response

### ISSUE THREAD

**Issue by Kamran95** [nklayman/vue-cli-plugin-electron-builder#711]
As electron builder uses electron-builder build -m(for mac) -w(for windows) -l for linux and -mwl(for all three platforms)
similary what command should be used for building for all three platforms

**Comment by nklayman** [comment]
Use `yarn electron:builder --win --mac --linux` or `npm run electron:builder -- --win --mac --linux` (keep the extra `--` for npm). All CLI args passed to `electron:build` get forwarded to electron-builder.

**Comment by Kamran95** [comment]
getting error missing script: electron:builder while using command npm run electron:builder -- --win --mac --linux

**Comment by nklayman** [comment]
My bad, it should be `electron:build`. Updated the comment to reflect this.
