### ISSUE TITLE
Preloaded scripts are not executed on public pages 

### ISSUE THREAD

**Issue by xXanth0s** [nklayman/vue-cli-plugin-electron-builder#717]
Whenever i try to load a public page like [google.com](https://www.google.com/), my preloaded scripts are not executed or even loaded. 

With the local pages, like the default page of the cli, it works perfect. 

Setup:
I am using typescript compiler and added the .ts file to the vue.config. 
Also webpack-dev-server is storing the files in the dist_electron folder. 

The script is preloaded with the following code:
```typescript
 win = new BrowserWindow({
    width: 1200,
    height: 800,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: true,
      nodeIntegrationInSubFrames: false,
      preload: path.resolve(__dirname, 'js', 'content.js'),
    },
  });
```

The only thing the preloaded script contains is 
```typescript
console.log('i am the content script');
```

Edit:
With the latest beta version, it does also not work with the local page. 

Typescript files compiled with custom webpack and ts-loader work fine,
But Typescript files compiled by another vue-cli project without vue-cli-plugin-electron-builder are also not runnable as preloaded script. So its a general problem with vue-cli

**Comment by nklayman** [comment]
In v2.0, there will be a built in feature to bundle preload scripts with webpack, so it should solve your problem.
