### ISSUE TITLE
How to bundle a python dist in build

### ISSUE THREAD

**Issue by mzy2240** [nklayman/vue-cli-plugin-electron-builder#718]
Everything works well on serve, the main process is able to call an executable python program which is packaged using pyinstaller. However, when building, the python program is either not working properly or not being called. How should I config the vue.config.js to include the pydist folder into the build? Thanks!

**Comment by mzy2240** [comment]
The problem is solved! Great package!

**Comment by MahmoudKrema** [comment]
How did you solve it?
