### ISSUE TITLE
npm run serve - no longer working

### ISSUE THREAD

**Issue by focussing** [nklayman/vue-cli-plugin-electron-builder#72]
First of all, thank you for this great plugin!
I followed this [video](https://www.youtube.com/watch?v=Fl7---SEORQ) and all went fine.
`npm run serve:electron` works as expected.
What the video describes is how to generate a Vuejs app which runs in a browser, install this plugin, and create a electron app.

However when I run `npm run serve` in order to show the app in a normal browser I get the following message in the console. I use all latest versions and run on Mac.
```
index.js?bdb9:6 Uncaught TypeError: fs.existsSync is not a function
    at Object.eval (index.js?bdb9:6)
    at eval (index.js:12)
    at Object../node_modules/electron/index.js (app.js:2031)
    at __webpack_require__ (app.js:768)
    at fn (app.js:131)
    at eval (HelloWorld.vue?140d:14)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/index.js?!./src/components/HelloWorld.vue?vue&type=script&lang=js& (app.js:1228)
    at __webpack_require__ (app.js:768)
    at fn (app.js:131)
    at eval (HelloWorld.vue?9697:1)
```

**Comment by nklayman** [comment]
You cant use fs or other native modules (like the built in ones provide by node) in the browser. They only work in node PR electron.

**Comment by focussing** [comment]
Of course, I know; but how nice would it be to adhere to "single source code base" to multiple outputs including the browser :)
That way there is always the possibility to generate a website distribution amongst the Mac, Linux and Windows distributions.

**Comment by focussing** [comment]
Why is "npm run serve" still there if it does not work as expected?

**Comment by nklayman** [comment]
The regular build/serve commands work fine as long as you don't use any native modules or other electron-specific modules or tools.

**Comment by focussing** [comment]
Well I did not add the part which generated the error; is it included via this plugin?

**Comment by nklayman** [comment]
This plugin does not add any fs calls to your app. Try searching your entire project for any part where fs is imported. I just tried with a fresh project and the serve command worked fine.

**Comment by focussing** [comment]
Sorry @nklayman, I searched the project; it is nowhere in my project. The error message is showing where it is caused: `at Object../node_modules/electron/index.js (app.js:2031)`

[This](https://github.com/drehimself/electron-vue-example) is the link to the project, maybe you could try it?
