### ISSUE TITLE
A few questions about the Electron version

### ISSUE THREAD

**Issue by jan-scorl** [nklayman/vue-cli-plugin-electron-builder#720]
Hey Noah, 

First of all: Thank you for providing and maintaining this repo. I gave it a try yesterday and it worked right out of the box.

If I remember correctly, it installed Electron version 6.1.10 during the initialisation. From what I can tell, the latest stable release is 8.2.2. Is there any reason why the plugin uses version 6.1.10 at the moment? I think I read something in the terminal output about a Vue Dev Tools incompatibility with Electron versions higher than 6? Is that the reason?

I saw dependabot mentioning the outdated Electron dependency but couldn't determine if there was a plan to update it or not. If I decided to update the Electron dependency to 8.2.2 myself, would you expect that to create any problems?

**Comment by nklayman** [comment]
You can upgrade to electron 8 without issue. The [2.0 beta](https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-beta.0) supports electron 8 in the invoke prompt. I will be moving 2.0 to RC soon and making it the default.
