### ISSUE TITLE
What are the best practices for managing the codebase of a Vue web-app + Electron-app?

### ISSUE THREAD

**Issue by jan-scorl** [nklayman/vue-cli-plugin-electron-builder#723]
Let's assume that I have created a Vue web-app, which is working fine. Now I want to distribute this app as an Electron app and choose this plugin to get the job done.

In the Electron version, some components need to talk to the Electron main process through the `ipcRenderer` in order to access specific parts of the Electron API to improve the user experience on desktop. However, these calls shall only happen in the Electron version, since they are redundant in the web-app version.

Can I exclude the electron-specific parts during 'yarn serve' and 'yarn build' somehow, so that I can build both versions from the same repo?

The web-app version and Electron-app version shall be based on the same codebase, since they are effectively the same app (excluding the Electron-specific parts).

How would I set up my project structure and build process to achieve that? Are there any examples or tutorials on that?

**Comment by nklayman** [comment]
You can use a `chainWebpack` function like so in your `vue.config.js`:

```js
const { NormalModuleReplacementPlugin } = require('webpack')

module.exports = {
  chainWebpack: config => {
    if (!process.env.IS_ELECTRON) {
      config.plugin('nativeModuleStub').use(NormalModuleReplacementPlugin, [
        /^(electron|othernativemodule)$/,
        resource => {
          // Stub out native modules as they are not used in browser
          resource.request = './src/utils/emptyObject.js'
        }
      ])
    }
  }
}
```
This will replace native module imports with an empty object (make sure to create the `emptyObject.js` file with `export default {}`). Then, wrap all of the calls to `IpcRenderer` with an `if (process.env.IS_ELECTRON)`. Then they will only be called in electron builds when the module is not mocked out.

**Comment by jan-scorl** [comment]
I implemented this the way you described it. However, it throws the error 

```
 ERROR  Failed to compile with 1 errors                                                                                                          20:34:45

This dependency was not found:

* electron in ./src/store/index.js
```

Do you know of an example project where this technique is implemented?

**Comment by nklayman** [comment]
My bad, update the `resource.request` line to:
```js
resource.request = '@/utils/emptyObject.js'
```
