### ISSUE TITLE
Error while building project for multiple operating system on mac

### ISSUE THREAD

**Issue by bahmad143** [nklayman/vue-cli-plugin-electron-builder#724]
Error While using 
npm run electron:build -- --win --mac --linux 
The project is ready but receiving a problem while building it for multiple platforms.  
Looking forward for your response so we can publish this app.
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'electron:build',
1 verbose cli   '--',
1 verbose cli   '--win',
1 verbose cli   '--mac',
1 verbose cli   '--linux'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.0
4 verbose run-script [ 'preelectron:build', 'electron:build', 'postelectron:build' ]
5 info lifecycle timetrackerapp@1.0.0~preelectron:build: timetrackerapp@1.0.0
6 info lifecycle timetrackerapp@1.0.0~electron:build: timetrackerapp@1.0.0
7 verbose lifecycle timetrackerapp@1.0.0~electron:build: unsafe-perm in lifecycle true
8 verbose lifecycle timetrackerapp@1.0.0~electron:build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/bilalahmad/Desktop/timetrackerfiles/testtttt/Timetracker 3/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle timetrackerapp@1.0.0~electron:build: CWD: /Users/bilalahmad/Desktop/timetrackerfiles/testtttt/Timetracker 3
10 silly lifecycle timetrackerapp@1.0.0~electron:build: Args: [ '-c', 'vue-cli-service electron:build "--win" "--mac" "--linux"' ]
11 silly lifecycle timetrackerapp@1.0.0~electron:build: Returned: code: 1  signal: null
12 info lifecycle timetrackerapp@1.0.0~electron:build: Failed to exec electron:build script
13 verbose stack Error: timetrackerapp@1.0.0 electron:build: `vue-cli-service electron:build "--win" "--mac" "--linux"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid timetrackerapp@1.0.0
15 verbose cwd /Users/bilalahmad/Desktop/timetrackerfiles/testtttt/Timetracker 3
16 verbose Darwin 19.4.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "electron:build" "--" "--win" "--mac" "--linux"
18 verbose node v12.14.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error timetrackerapp@1.0.0 electron:build: `vue-cli-service electron:build "--win" "--mac" "--linux"`
22 error Exit status 1
23 error Failed at the timetrackerapp@1.0.0 electron:build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by adnan8044** [comment]
Getting same problem. Couldn't solve it. Anyone who can resolve this error kindly leave a response

**Comment by UsmanGul** [comment]
Same issue :(

**Comment by onekiloparsec** [comment]
I have the same issue, with different error message. There is one thing related to Windows builds on macOS though that would benefit from a version bump of `electron-builder` (`v22.2`): https://github.com/electron-userland/electron-builder/issues/4305#issuecomment-559138959

**Comment by nklayman** [comment]
I think electron-builder v22 fixes this problem. The [2.0.0 beta](https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-beta.0) of this plugin uses electron builder v22. You can also use [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) with the 1.x version:

(`package.json`)
```json
{
  "resolutions": {
    "vue-cli-plugin-electron-builder/electron-builder": "^22.2.0"
  }
}
