### ISSUE TITLE
Error: Cannot find module 'C:\Users\usr\Documents\GitHub\Vue-recreate\clinician-rnd-2\node_modules\vue-cli-plugin-electron\index.js'

### ISSUE THREAD

**Issue by uforiginal** [nklayman/vue-cli-plugin-electron-builder#727]
Getting the following error while after running `npm run electron:serve` : 
`Error: Cannot find module 'C:\Users\usr\Documents\GitHub\Vue-recreate\clinician-rnd-2\node_modules\vue-cli-plugin-electron\index.js'. Please verify that the package.json has a valid "main" entry`

My package.josn "main" is "main":"main.js" and my file tree looks like this:
![image](https://user-images.githubusercontent.com/29385897/80141728-a12a7600-856f-11ea-8ec9-7c1e520ed596.png)

**Comment by nklayman** [comment]
It's looking for `vue-cli-plugin-electron/index.js`, not `vue-cli-plugin-electron-builder/index.js`. Check your `package.json` to make sure the proper package is installed and then try again.
