### ISSUE TITLE
Unable to build window NSIS on MacOS

### ISSUE THREAD

**Issue by LeiZeng** [nklayman/vue-cli-plugin-electron-builder#728]
**Describe the bug**
 ERROR  Error: Exit code: ENOENT. spawn prlctl ENOENT

**To Reproduce**
Try to build windows NSIS on MacOS.

**Expected behavior**
Please upgrade electron-builder to 22.2.0, as in below solution.
https://github.com/electron-userland/electron-builder/issues/4305#issuecomment-559138959

**Comment by nklayman** [comment]
This is a duplicate of #724.
