### ISSUE TITLE
Failed to register app protocol

### ISSUE THREAD

**Issue by 0x77dev** [nklayman/vue-cli-plugin-electron-builder#736]
**Describe the bug**
```log
Failed to register app protocol Error: Invalid package /Users/0x77/Projects/@kubecraft/launcher/dist_electron/mac/Kubecraft Launcher.app/Contents/Resources/app.asar/Users/0x77/Projects/@kubecraft/launcher/dist_electron/mac/Kubecraft Launcher.app/Contents/Resources/electron.asar
```
**To Reproduce**
buid application and open

**Expected behavior**
Rendered page

**Screenshots**
![Снимок экрана 2020-05-02 в 13 44 23](https://user-images.githubusercontent.com/46429701/80862073-0a4e6f80-8c7b-11ea-8c7f-2cafb16e01ea.png)
![Снимок экрана 2020-05-02 в 13 44 09](https://user-images.githubusercontent.com/46429701/80862065-015d9e00-8c7b-11ea-95cf-e514132e4646.png)

**Environment (please complete the following information):**
 - OS and version: `Darwin 0x77imac.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64`
 - node version: `v14.1.0`
 - npm version: `6.14.4`
 - yarn version (if used): `1.22.4` 
 - vue-cli-plugin-electron-builder version : `~1.4.6`
 - electron version: `^6.0.0`
 - other vue plugins used: `nothing special`
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: https://github.com/KubecraftServer/launcher/tree/v0.0.2+1

**Additional context**

**Comment by 0x77dev** [comment]
@nklayman

**Comment by nklayman** [comment]
Not sure why, but your app works just fine for me on Arch Linux. Try `rm -rf node_modules && yarn` and then rebuild and run.

**Comment by 0x77dev** [comment]
Yeah, thanks!

**Comment by 0x77dev** [comment]
I've fixed this, this is was a rendering problem

**Comment by Lockseed** [comment]
> I've fixed this, this is was a rendering problem

Hi, 0x77dev. Could you tell me some details about how you fix this issue? I seem to have the same problem as you.

**Comment by martin-braun** [comment]
@0x77dev I'm facing the same issue like you and @Lockseed. Do you have some advice to us?
