### ISSUE TITLE
Incorrect "app.getPath('userData')" in "serve:electron" task.

### ISSUE THREAD

**Issue by fenixphp** [nklayman/vue-cli-plugin-electron-builder#74]
**Describe the bug**
on start a "serve:electron" task.
```javascript
console.log(app.getPath('userData'));
```
```
C:\Users\Fenixphp\AppData\Roaming\Electron
```

**Expected behavior**

```javascript
console.log(app.getPath('userData'));
```
```
C:\Users\Fenixphp\AppData\Roaming\{AppName}
```

**Environment (please complete the following information):**
 - OS and version: Windows 10
 - Node version: v8.11.2
 - npm version: v5.7.1
 - vue-cli-plugin-electron-builder version :  v1.0.0-rc.2

"build:electron" task works correctly

---

As if use the function "app.getVersion()" in "serve: electron" is derived version of the Electron, and "build: electron" displays the current version of the application.

**Comment by nklayman** [comment]
For now, just copy the `package.json` file to the `dist_electron` folder. I think this will work. Tomorrow I will test it and automate it through the plugin.

**Comment by nklayman** [comment]
Tested, it doesn't work :sob: . However, I should have a fix by tomorrow morning :+1: so hang on till then.

**Comment by nklayman** [comment]
This fix will be available in the next release. To use it now, set vcp-electron-builder's version to `nklayman/vue-cli-plugin-electron-builder` to install from the github repo.

**Comment by fenixphp** [comment]
It seems to work) Thank you.

**Comment by nklayman** [comment]
1.0.0-rc.3 has been released, along with this feature/fix. You may now use that as vcp-electron-builder's version instead of the github repo (recommended).
