### ISSUE TITLE
express server not working properly

### ISSUE THREAD

**Issue by lokingwei** [nklayman/vue-cli-plugin-electron-builder#740]
**Describe the bug**
I need to serve an express server(localhost:3000/) and express-pouchdb (localhost:3000/db) as the backend of electron.
I already added both dependencies into externals like below:
```
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['pouchdb', 'express-pouchdb', 'express']
    }
  }
}
```
It work properly when I serve the electron, but the path for express-pouchdb not working after build.

**To Reproduce**
https://github.com/lokingwei/vue-cli-plugin-electron-builder-test

It has no error at all, the request just stays at pending, I can't debug what really happen.
It's the same behavior for http://localhost:3000 if I remove express from externals

**Comment by nklayman** [comment]
I think the issue issue may be caused when pouchdb creates a handful of files in the directory from which the app is launched:
![image](https://user-images.githubusercontent.com/12448243/81245469-e4ea9a00-8fc9-11ea-8126-bb6f5a8d0193.png)
In production, that location is unwritable as it is inside of an asar archive. You will need to find a way to have those files stored somewhere else, such as the path returned by `app.getPath('userData')`.

**Comment by lokingwei** [comment]
Thanks for the response, I had added the DB path selection after build and pushed to update. Unfortunately still no luck on this.

Currently, I'm trying to debug the source for pouchdb express, it seems one stream.pipe() did not resolve. I'm wondering will it possible the `require("stream")` statement are actually require the stream from browser API instead of nodejs, and there's a difference between these 2.

**Comment by lokingwei** [comment]
Below is my finding (updated the reproduce repo)
the `allDocs()` in the `main.ts` resolved properly, but the `allDocs()` in the pouchdb-express (first call was inside `pouchdb-replicator`) was never resolved, which lead to server hangs and visiting `localhost:3000/db` will never resolve.

After my debugging, the depth I can reach is pouchdb line 5711. For the `allDocs()` in main.ts, it has the `unpipe` event emitted but no for pouchdb-express.
```
}).on('unpipe', function () {
  throughStream.end();
});
```

So I suspect this has something to due with the webpack, which causes the external module to use different native module eg:`require('stream')`. Or is there any other different direction?

**Comment by lokingwei** [comment]
Fixed this by downgrade the pouchdb version. I guess I'll file an issue in pouchdb to understand more about this behaviour...

Thanks for helping
