### ISSUE TITLE
Hot-Reload not working in background.js dependencies

### ISSUE THREAD

**Issue by ZhangZisu** [nklayman/vue-cli-plugin-electron-builder#741]
**Describe the bug**
Hot-Reload wont work when despondencies of background.js changed.

**To Reproduce**
```ts
// src/background.ts
'use strict'

import path from 'path'
import { app, protocol, BrowserWindow, Tray, Menu, Notification } from 'electron'
import { createProtocol, installVueDevtools } from 'vue-cli-plugin-electron-builder/lib'
import { getConfig } from './common/config'

const isDevelopment = process.env.NODE_ENV !== 'production'

protocol.registerSchemesAsPrivileged([{ scheme: 'app', privileges: { secure: true, standard: true } }])

let win: BrowserWindow | null

function createWindow () {
  ...
}

if (app.requestSingleInstanceLock()) {
  app.on('ready', async () => {
    ... // Install Vue Devtools
    const config = getConfig()
    if (!config.hideOnStart) {
      createWindow()
    }
  })
  ...
} else {
  app.quit()
}

```
```ts
// src/common/config.ts

export function getConfig(){
  ...
}
```

Edit `src/common/config.ts`, but the background process wont be reloaded
**Expected behavior**
background process should be reloaded after its dependencies updated

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: `Microsoft Windows [Version 10.0.18363.778]`
 - node version: `v14.2.0`
 - npm version: `6.14.4`
 - yarn version (if used): `1.22.4`
 - vue-cli-plugin-electron-builder version : `^1.4.6`
 - electron version: 8.2.5 (but the bug happens on all electron versions!)
 - other vue plugins used: babel, eslint, router, typescript, vuetify
 - custom config for vcp-electron-builder: https://github.com/ZhangZisu/classroom-helper/blob/master/vue.config.js
 - (if possible) link to your repo: https://github.com/ZhangZisu/classroom-helper

**Comment by nklayman** [comment]
You need to add the file to the `mainProcessWatch` array in `vue.config.js`:
```js
// vue.config.js

module.exports = {
  pluginOptions: {
    electronBuilder: {
      // Provide an array of files that, when changed, will recompile the main process and restart Electron
      // Your main process file will be added by default
      mainProcessWatch: ['src/myFile1', 'src/myFile2'],
    }
  }
}

**Comment by getflourish** [comment]
Does this work with folders, e.g. "some/folder/*"?

**Comment by BroJenuel** [comment]
can I do something like this 
![image](https://user-images.githubusercontent.com/31676163/133961845-241a6be9-9f37-4043-9f1c-e8a38943db50.png)

**Comment by nklayman** [comment]
@BroJenuel no, glob files are not supported for mainProcessWatch. However, you can add directories to that list and all contents will be watched.

**Comment by BroJenuel** [comment]
> @BroJenuel no, glob files are not supported for mainProcessWatch. However, you can add directories to that list and all contents will be watched.

awesome, thanks a lot <3 more power

**Comment by g8up** [comment]
delete `dist_electron` generated by `electron:build`, and run `electron:server`, it would reload well when change background.js.
