### ISSUE TITLE
Debugging With Vscode (help wanted)

### ISSUE THREAD

**Issue by ajmasia** [nklayman/vue-cli-plugin-electron-builder#745]
Hu guys, I'm trying to config my Vscode to debug a new project. I'm using the config described [here](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#debugging-with-vscode) but don't work. 

When I run the Vscode debugger the project is built and get this messages:

```bash
 INFO  Not launching electron as debug argument was passed. You must launch electron though your debugger.
 INFO  If you are using Spectron, make sure to set the IS_TEST env variable to true.
 INFO  Learn more about debugging the main process at https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/testingAndDebugging.html#debugging.
```
After that
```bash
Cannot connect to runtime process, timeout after 30000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9223).
```

I've tried this [example](https://github.com/nklayman/electron-vscode-debug-example) and it doesn't work either.

My config: 
Vscode: 1.44.2
Node: 12.16.1
Electron: 5.0.0
Vue: 2.6.11
Vue-cli-plugin-electron-builder: 1.4.6

Thanks!

**Comment by nklayman** [comment]
Make sure that you are launching the `Electron: All` config and not the `Electron: Main`.
