### ISSUE TITLE
How to debug production build?

### ISSUE THREAD

**Issue by BotellaA** [nklayman/vue-cli-plugin-electron-builder#750]
I have an error only while executing the production app.
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
```
The stack trace is not helpful because it refer to an asar package.
I would like to disable `asar` and `uglify` to see what code produces this error.

I understand how to disable `asar`
```
module.exports = {
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
        asar: false,
    },
  },
};
```
and I read about disabling `uglify`
```
module.exports = {
  pluginOptions: {
    electronBuilder: {
	chainWebpackMainProcess: config => {
		config.plugins.delete("uglify");
	},
	chainWebpackRendererProcess: config => {
		config.plugins.delete("uglify");
	},
    },
  },
};
```

How change the `vue.config.js` have both behaviors?
Thanks for your help

**Comment by nklayman** [comment]
You can use `yarn electron:build --mode development` to disable minification for both the main and renderer process.

**Comment by BotellaA** [comment]
Thanks @nklayman for the help. Indeed it does not minify.
However, I do not have my error with the unminified build.

What could cause this different behavior?

**Comment by nklayman** [comment]
Use this:
```js
module.exports = {
  configureWebpack: {
    optimization: {
      minimize: false,
    },
  },
  pluginOptions: {
    electronBuilder: {
      chainWebpackMainProcess: (config) => {
        config.plugins.delete('uglify')
      }
    },
  }
}
```

**Comment by BotellaA** [comment]
Thanks
