### ISSUE TITLE
Video playback performance not equivalent to chromium-browser

### ISSUE THREAD

**Issue by turbopasi** [nklayman/vue-cli-plugin-electron-builder#754]
**Describe the bug**
I am using electron from this vue-cli-plugin-electron-builder to play some local video files on a Raspberry Pi 3 b+. I set webSecurity to false, so playing local files is not a problem. I am trying to play the video file (mp4, 720p) via html video tag. It works. 

Now something is odd about the video performance, when playing in fullscreen. Via the electron app the video slightly lags/stutters. However, playing the same file directly via the chromium-browser it runs fluent and smooth. I wonder why this could be, I thought they both use the same engine somehow ? 

Are they any special settings in electron, electron-builder to enable a missing feature ? 

**To Reproduce**
Playing a local video file on a Raspberry Pi 3b+ via Electron, vs playing in Chromium-Browser .

**Expected behavior**
Same video performance as in chromium-browser

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: Raspbian Buster
 - node version: 10.15.2
 - npm version: 6.14.2
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 1.4.6
 - electron version: 6.0.0
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**
I built the app vie `npm run electron:build -- --linux deb --armv7l`

**Comment by nklayman** [comment]
I don't know of any settings that could affect video playback performance. Try using the latest version of electron as that will use a more recent version of chromium which could be faster. Also, try playing the video in a [vanilla electron app](https://github.com/electron/electron-quick-start) and see if it is still slow there.

**Comment by turbopasi** [comment]
Thanks for suggestions @nklayman . 
About using a more recent version of electron  : Is it enough to just update the electron version in the package.json and hit `npm install` again ? I never altered an existing project like that before I am afraid :) 

About using the vanilla electron app : Yes, I will try that. Will come back with the results 👍

**Comment by nklayman** [comment]
All you need to do is change the electron version and run npm install. Just beware of [electron breaking changes](https://www.electronjs.org/releases/stable).

**Comment by turbopasi** [comment]
Sadly upgrading the electron to latest or beta version did not do any changes in performance. Same as with using electron vanilla. 

I 'll probably bundle my vue app for direct use in browser and use `chromium-browser --kiosk file://`

**Comment by nklayman** [comment]
If the vanilla electron has the same performance as a vue app, then I'd suggest opening an issue on electron's repo instead, as it isn't a problem with this plugin.
