### ISSUE TITLE
Native module `dns` cannot be resolved

### ISSUE THREAD

**Issue by Meowzz95** [nklayman/vue-cli-plugin-electron-builder#755]
**Describe the bug**
Native module `dns` cannot be resolved despite adding it into `pluginOptions.electronBuilder.externals`.

**To Reproduce**
Init an empty project following the doc, and `import dns from "dns"`

**Expected behavior**
`dns` module should be loaded without issue

**Screenshots**
![image](https://user-images.githubusercontent.com/22430379/82116826-ec1a6080-979e-11ea-9988-50ca7b9bfb61.png)

**Environment (please complete the following information):**
 - OS and version: MacOS 10.15.4
 - node version: v12.13.1
 - npm version: 6.14.4
 - yarn version (if used): 1.22.0
 - vue-cli-plugin-electron-builder version : v2.0.0-beta.0
 - electron version: 8.3.0
 - other vue plugins used: vuetify
 - custom config for vcp-electron-builder: `pluginOptions.electronBuilder.externals = ['dns']`
 - (if possible) link to your repo: not yet

**Additional context**

**Comment by nklayman** [comment]
Works fine for me when I follow the reproduction steps. Try `rm -rf node_modules && yarn` and see if that helps. Also make sure dns is installed as a `dependency`, not a `devDependency`.

**Comment by shudingbo** [comment]
dns is node.js 's native module

**Comment by jardenliu** [comment]
@shudingbo  `pluginOptions.electronBuilder.nodeIntegration` to `true`, and it work for me
