### ISSUE TITLE
extraResource when using electron:serve not copying

### ISSUE THREAD

**Issue by werkflo** [nklayman/vue-cli-plugin-electron-builder#757]
**Describe the bug**
I have a file (a compiled dotnet application) that I need to copy into the Resources folder of my application. Using a builderOptions.extraResources setting successfully copies this file into the Resources folder when using electron:build.  However, the file does _not_ copy when using electron:serve.  Is there any way to apply these options to electron:serve?

**To Reproduce**
I use the following options in my vue.config.js:
`				
extraResources:[
	{
		from:"FMComparison_DotNet/bin/Debug/netcoreapp3.1/osx-x64/publish/FMComparison_DotNet",
		to:"FMComparison_DotNet"
	}
]
`
These settings do not appear to be considered by the electron:serve script.  Is there a way to make this happen?

**Comment by nklayman** [comment]
Since `electron:serve` does not use electron-builder, `extraResources` is ignored. You will have to reference the source path in development builds. You can use a ternary statement to choose the proper path like so: 
```js
const pathToResource = process.env.NODE_ENV === 'production' ? extraResourcesPath : sourcePath
```
