### ISSUE TITLE
Will This project support vite(vue 3.0)?

### ISSUE THREAD

**Issue by xland** [nklayman/vue-cli-plugin-electron-builder#758]
Will This project support vite(vue 3.0)?
[https://github.com/vuejs/vite](https://github.com/vuejs/vite)
When? and How?

Thanks

**Comment by nklayman** [comment]
This plugin already supports vue 3, just use the [vue-next](https://github.com/vuejs/vue-cli-plugin-vue-next) plugin in your vue cli 4 project. As for Vite, it cannot support it until vue cli uses vite.
