### ISSUE TITLE
How to use a local database (SQLite or NeDB) after build?

### ISSUE THREAD

**Issue by renatomattos2912** [nklayman/vue-cli-plugin-electron-builder#76]
I'm trying to use a local database in my electron app, it works in development but when i bundled the app (I only tested in mac os bundle), the database is not connecting anymore, so maybe the bundle is not moving my database to a folder with the right permissions, but i dont know in what folder i can put my database file, i don't find nothing in the docs too, can someone help me with this?

**Comment by nklayman** [comment]
The reason it doesn't work is because all of your files get packed into an `asar` archive. This archive is read only, preventing a database from working. To fix this, you need to have the database file/folder not packed into the archive:

**Note: change `src/database.txt` to the path of your database file/folder**

```javascript
// vue.config.js

module.exports = {
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
        extraResources: ['src/database.txt']
      }
    }
  }
}
```

```javascript
// Wherever you use the database
import path from 'path'

const pathToDbFile = path.join(
  (isBuild ? __dirname : __static),
  (isBuild ? '../../' : ''),
  '../src/database.txt'
)
```

`pathToDbFile` is equal to `PROJECT_ROOT/src/database.txt`.

**Comment by nklayman** [comment]
@piascikj have you tried placing the script in the public folder and running it inside the archive? Also, try just reading the contents of the file, or the parent directory. In addition, can you tell me where the worker file ends up in your built app? Thanks!

**Comment by piascikj** [comment]
Thanks a bunch @nklayman! Moving `imdone-repo-worker.js` to `public/` and using `path.join(__static,'imdone-repo-worker.js')` did the trick.

**Comment by nathansalwen** [comment]
Thank you for this note! Is there any way this information could be made more visible or linked to in, for example the following page? 

https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules

Thanks!

**Comment by nklayman** [comment]
@nathansalwen Added a link to the above comment in that section, the updated docs should be live now.

**Comment by nathansalwen** [comment]
I see the comment. I think that is an improvement. In my case, the "extraResources" configuration was necessary for ffi-napi to find external libraries. 

"If files need to be present in an unpacked form, such as library files for ffin-napi or database files for MySQL or MongoDB, additional configuration is needed. See Issue #76 (comment) for usage of builderOptions->ExtraResources in vue.config.js.

    for more info.

#

**Comment by douglast2t** [comment]
hi @nklayman, i'm having problems on building, can you be more specific about the configuration to use mysql? 
thank for this awesome project by the way!

**Comment by nklayman** [comment]
@douglast2t use mysql as if you are creating a regular nodejs script, but follow the instructions in https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/76#issuecomment-420060179 for determining the location of your database file/folder. The mysql code should go in `src/background.js`.

**Comment by MedoAngel** [comment]
this worked for me 

**in vue.config.js**

` module.exports = { chainWebpack: config => { config.externals({ "nedb":"commonjs nedb" }) } } `

these could also be helpful for you

[https://stackoverflow.com/questions/40650701/nedb-not-loading-or-storing-to-file](https://stackoverflow.com/questions/40650701/nedb-not-loading-or-storing-to-file)

[https://github.com/louischatriot/nedb/issues/329](https://github.com/louischatriot/nedb/issues/329)
