### ISSUE TITLE
Problems with fileAssociations.

### ISSUE THREAD

**Issue by sampalest** [nklayman/vue-cli-plugin-electron-builder#760]
**Bug:**
fileAssociations not working... (macOS Catalina)

**Expected behavior**
Hi, I have a problem when I want to associate file types to my app. 
I tried to do it like it is specified in [electron-builder documentation](https://www.electron.build/configuration/configuration) but nothing works, there's no file association.

This is my configuration:

```json
      fileAssociations: {
        ext: "ctx",
        name: "CTX",
        role: "Editor",
        description: "Cryptox file encrypted"
      },
```
Icons:
![icons](https://user-images.githubusercontent.com/16646954/82264247-d22a7a80-9964-11ea-86b4-359dcb8a8a9e.png)

Info.plist when I built it without vue-plugin (only electron-builder):
![wo-vueplugin](https://user-images.githubusercontent.com/16646954/82263877-1ff2b300-9964-11ea-986a-494d97cc2f67.png)
This attribute does not exist when run build with vue plugin.

Dependencies:

```json
  "dependencies": {
    "animate.css": "^3.7.2",
    "archiver": "^4.0.1",
    "core-js": "^3.6.4",
    "electron-log": "^4.1.2",
    "electron-notarize": "^0.3.0",
    "file-system": "^2.2.2",
    "file-type": "^14.3.0",
    "jquery": "^3.5.1",
    "materialize-css": "^1.0.0",
    "unzipper": "^0.10.11",
    "vue": "^2.6.11",
    "vue-router": "^3.1.6",
    "vuex": "^3.1.3"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.3.0",
    "@vue/cli-plugin-e2e-nightwatch": "^4.3.0",
    "@vue/cli-plugin-eslint": "^4.3.0",
    "@vue/cli-plugin-router": "^4.3.0",
    "@vue/cli-plugin-unit-jest": "^4.3.0",
    "@vue/cli-plugin-vuex": "^4.3.0",
    "@vue/cli-service": "^4.3.0",
    "@vue/test-utils": "1.0.0-beta.31",
    "babel-eslint": "^10.1.0",
    "chromedriver": "81",
    "electron": "8.2.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "geckodriver": "^1.19.1",
    "node-sass": "^4.12.0",
    "sass-loader": "^8.0.2",
    "vue-cli-plugin-electron-builder": "^1.4.0",
    "vue-template-compiler": "^2.6.11",
    "webpack": "~4.42.1"
  }
```
Even if I manage to solve this problem, the "on-open" events don't work either, this might be because of the same bug?

Thank you very much, and thank you for your work.

Sam

**Comment by nklayman** [comment]
Did you place the electron-builder config [in the proper file](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#configuring-electron-builder)?

**Comment by sampalest** [comment]
At the end the problem wasn't related to the project, I've already solved it.
Thank you so much for your help!
