### ISSUE TITLE
process.env truncated

### ISSUE THREAD

**Issue by Wikiki** [nklayman/vue-cli-plugin-electron-builder#764]
Hi,

I'm trying to access to `process.env.PATH` but the variable is `undefined`. It seems variables are truncated when acessing to `process.env`.
If I log `process` I can see all variables (including `env.PATH` in the console) but when I log `process.env` I only get these variables `BASE_URL`, `IS_ELECTRON` and `NODE_ENV`.

`console.log(process)`:
<img width="774" alt="Screenshot 2020-05-20 at 21 08 17" src="https://user-images.githubusercontent.com/24766179/82487198-58b69780-9ade-11ea-8880-d04d53b4856b.png">

`console.log(process.env)`:
<img width="533" alt="Screenshot 2020-05-20 at 21 08 55" src="https://user-images.githubusercontent.com/24766179/82487207-5ce2b500-9ade-11ea-9594-a07ab4a5da81.png">

Why can't I access to all env variables instead of it seems they are all present in the process object ?

**Comment by Wikiki** [comment]
I forgot to mention that I'm doing this in the rendering process.

Some tests show that I can get the real `process.env` value with the following code:
```javascript
Object.keys(process).forEach((key, index) => {
    if (key === 'env') {
        console.log(Object.values(process)[index]);
    }
});
```

Why `process.env` overrides the real `env` property ?

**Comment by nklayman** [comment]
This is because Vue CLI uses [webpack's DefinePlugin](https://webpack.js.org/plugins/define-plugin/) to fill `process.env` with useful values since `process` is not available in the browser. A simple solution to get the real `process.env` is to use `eval('process.env')`, which will return the actual `process.env` object like in nodejs.

**Comment by rzfzr** [comment]
@nklayman Is there a way to replace process.env for its own eval? Because I'm using a module that references process.env.path which is null.
Thanks

**Comment by nklayman** [comment]
You could [externalize](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules) the module which will have it skip webpack processing, that should fix the error.
