### ISSUE TITLE
Is there a way to create a custom protocol to navigate to a specific page?

### ISSUE THREAD

**Issue by austtn** [nklayman/vue-cli-plugin-electron-builder#765]
I need to use oAuth2 with a project and the redirect URI needs to be inside of my electron app. Anyone know my best possible approach to this?

**Comment by nklayman** [comment]
Try https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/686#issuecomment-602362111

**Comment by austtn** [comment]
Yeah i got it anyways, thanks though.
