### ISSUE TITLE
Cannot use “import” inside a module that is set to “external” in electron-builder config

### ISSUE THREAD

**Issue by coinshot** [nklayman/vue-cli-plugin-electron-builder#769]
I set a module as external in the electron-builder config as below:
`module.exports = { electronBuilder: { externals: ['my-module'] } }`

Now I cannot use "import" in my module, for example, if I import something inside that external module like `import {func} from 'some-module'` then I receive the following error:

>  SyntaxError: Cannot use import statement outside a module

- I added `type = "module"` to the module's package.json file — **Did not fix it**
- I added the following to the babel config through chainWebpackRendererProcess ` { "presets": ["@babel/preset-env"] }` — **Did not fix it**

**Comment by nklayman** [comment]
You will have to use commonjs `require/module.exports` because es6 import/export isn't supported. Since the module is externalized, webpack doesn't change es6 modules to commonjs like it normally would.
