### ISSUE TITLE
Router-view Issue When npm run electron:build Is Built

### ISSUE THREAD

**Issue by sderbidge** [nklayman/vue-cli-plugin-electron-builder#772]
**Describe the bug**
After I use npm run electron: build, it builds the app but doesn't go to the correct router view. It shows the menu "Home | About" but neither are selected. Ideally I'd like Home to be selected.

**To Reproduce**
1. Use npm run electron:build on a vue app, 
2. install the desktop app using the installer inside the newly built app,
3. open up the app

**Expected behavior**
I expect it to be the same functionality as npm run electron:serve that is when you launch the app it starts on the same page

**Comment by nklayman** [comment]
This is likely caused if Vue router is operating in history mode. Try https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#blank-screen-on-builds-but-works-fine-on-serve.

**Comment by MrEduar** [comment]
Hi, I had this same white screen problem while compiling a build. I read the documentation and changed the mode to hash, but when I compile again the white screen still comes up. Any idea what it could be?

```
//src\router\index.js
const router = new VueRouter({
  mode: 'hash',
  base: process.env.BASE_URL,
  routes
})
```

**Comment by nklayman** [comment]
@MrEduar open a new issue that follows the bug report template (preferably with a repo that demonstrates the error). I need more information to help you.
