### ISSUE TITLE
How to install Apollo Dev Tools?

### ISSUE THREAD

**Issue by Al-Rozhkov** [nklayman/vue-cli-plugin-electron-builder#777]
**Is your feature request related to a problem? Please describe.**
Is it possible to install another Chrome extension just as simple as Vue Devtools?

**Comment by nklayman** [comment]
You can use [electron-devtools-installer](https://www.npmjs.com/package/electron-devtools-installer). I only provide easy install for vue devtools as I don't want to try and support all the other possible devtools someone could want.
