### ISSUE TITLE
Electron 7/8/9 ，how to install Vue Devtools?

### ISSUE THREAD

**Issue by wuxiaobin1995** [nklayman/vue-cli-plugin-electron-builder#783]
**Describe the bug**
how to install Vue Devtools

**Screenshots**

**Environment (please complete the following information):**
 - node version: 12.16.3
 - npm version: 6.14.4
 - vue-cli-plugin-electron-builder version :  2.0-rc1
 - electron version:  7 8 9

**Additional context**
`Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools`

**Comment by wuxiaobin1995** [comment]
![image](https://user-images.githubusercontent.com/36044379/83476098-5e3eb500-a4c2-11ea-8db8-3e2910730479.png)

**Comment by wuxiaobin1995** [comment]
![image](https://user-images.githubusercontent.com/36044379/83476929-83ccbe00-a4c4-11ea-8b4d-3077b411cfc2.png)

**Comment by nklayman** [comment]
Vue devtools are still broken on windows 10 dark mode for 7/8/9, but all you need to do to enable them is uncomment lines 73-76 and line 6 I think in `background.js`

**Comment by wuxiaobin1995** [comment]
ok,i solve it
