### ISSUE TITLE
vue multiple pages project with filename like admin/index.html

### ISSUE THREAD

**Issue by ginkosen** [nklayman/vue-cli-plugin-electron-builder#786]
**Is your feature request related to a problem? Please describe.**

_**vue multiple pages project with filename like admin/index.html**_ Does not compile correctly。
with error
`
 Error: ENOENT: no such file or directory, open 'dist_electron/bundled/legacy-assets-admin/index.html.json'
`
**Describe the solution you'd like**
this filename will compile correctly
**Describe alternatives you've considered**

change the code and create **dist_electron/bundled/legacy-assets-admin/** directory

**Additional context**
none

**Comment by nklayman** [comment]
Thanks for the report! Fix will be available in v2.0.0-rc.2.

**Comment by ginkosen** [comment]
Thanks!!
