### ISSUE TITLE
Uncught ReferenceError: require in not defined

### ISSUE THREAD

**Issue by amaury-tobias** [nklayman/vue-cli-plugin-electron-builder#789]
**Describe the bug**
When I build using vue-router, the console logs error
```
Uncaught ReferenceError: require is not defined > app.hash.js
```
on `app.hash.js`
```
x = new c["a"]({
mode: "hash",
base: require("electron").remote.app.getAppPath(),
routes: w
})
```
source `router/index.ts`
```
const router = new VueRouter({
  mode: process.env.IS_ELECTRON ? 'hash' : 'history',
  base: process.env.BASE_URL,
  routes,
})
```

**To Reproduce**
$ vue create app
> select typescript, vue-router
$ vue add electron-builder
$ yarn electron:build
open app > open devtools console

**Expected behavior**
Application works normally

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: MacOs 10.15.4
 - node version: 14.2.0
 - npm version: 6.14.5
 - yarn version (if used): 1.22.4
 - vue-cli-plugin-electron-builder version : 2.0.0-rc.1
 - electron version: 9.0.2
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**
If i enable `nodeIntegration` on `background.ts` all works,

**Comment by amaury-tobias** [comment]
Update, I change the `base` on Router from `process.env.BASE_URL` to `'/'` with `nodeIntegration = false` and works.

**Comment by nklayman** [comment]
You shouldn't need to set the base for electron builds, just leave it undefined or `/`.
