### ISSUE TITLE
What happen with “await installVueDevtools()” ?

### ISSUE THREAD

**Issue by Ken-twenty** [nklayman/vue-cli-plugin-electron-builder#79]
Only when I remove the line `await installVueDevtools()` in `background.js`, Electron can launch successfully.How can I fixed it if I want VueDevtools?

**To Reproduce**
`vue create my-project`
`vue add electron-builder`
`npm serve:electron`

**Environment (please complete the following information):**
 - OS and version: Windows 10
 - Node version: v8.11.4
 - npm version:v5.6.0
 - vue-cli-plugin-electron-builder version : ^1.0.0-rc.3

Thanks a lot!

**Comment by TotomInc** [comment]
This is what happens when you call [`await installVueDevtools()`](https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/5d7dc390e31735e5cd0e1462f09c6908f25e7522/lib/installVueDevtools/index.js#L22-L52).

IIRC, it first try to find the vue-devtools extension installed locally (like in your chrome) then if it can't find it, it will try to download it from the chrome web store.

**Comment by Ken-twenty** [comment]
@TotomInc Thanks for ur kind help! According to your tips, I find a way to solve this problem.

**Comment by TotomInc** [comment]
Do you have any errors when you keep the `await installVueDevtools()` in `background.js`?

**Comment by TotomInc** [comment]
There are no error on Mac OS (10.13.6). I will try to reproduce it on Windows 10 tonight.

**Comment by Ken-twenty** [comment]
node_modules\vue-cli-plugin-electron-builder\lib\installVueDevtools\util.js
![image](https://user-images.githubusercontent.com/21240591/45355737-bef1d400-b5f3-11e8-8248-b7796d701569.png)
node_modules\vue-cli-plugin-electron-builder\lib\installVueDevtools\index.js
![image](https://user-images.githubusercontent.com/21240591/45355862-27d94c00-b5f4-11e8-863e-744c7d41dd3f.png)

This is how I solve the problem, apparently ugly ==!

To a wrong Path, downloading from the chrome web store should be invalid. So I suppose it is a bug?

**Comment by Ken-twenty** [comment]
@TotomInc any errors with my ugly solution...

**Comment by nklayman** [comment]
It works fine for both linux and windows in the CI tests. I don't have any issues either, so I can't debug it myself. The `getPath()` function is cross-platform, as described [here](https://electronjs.org/docs/api/app#appgetpathname). It might be related to [this PR](https://github.com/MarshallOfSound/electron-devtools-installer/pull/88), and I will look into incorporating those changes tomorrow.

**Comment by nklayman** [comment]
I incorporated the changes of the PR, but they don't relate to this issue (as far as I can tell). Still have no idea why this doesn't work.

**Comment by Ken-twenty** [comment]
Emm...embarrassed，I might found the reason. There is Internet Censorship in some country (dont know how u call this), my mirror site sets probably cause this error. With a VPN set, the downloading and `getPath()` work. Sorry for bother~  Awesome builder, thank you Klayman!
