### ISSUE TITLE
Vue Devtools failed to install: ReferenceError: installVueDevtools is not defined

### ISSUE THREAD

**Issue by 396784797** [nklayman/vue-cli-plugin-electron-builder#790]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS and version:window
 - node version: 12.17.0
 - npm version:6.14.4
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 2.0.0-cr.1
 - electron version: 9.0.0
 - other vue plugins used:  "@vue/cli-plugin-babel": "~4.4.0",
    "@vue/cli-plugin-eslint": "~4.4.0",
    "@vue/cli-service": "~4.4.0",
    "babel-eslint": "^10.1.0",
    "electron": "^9.0.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "vue-cli-plugin-electron-builder": "~2.0.0-rc.1",
    "vue-template-compiler": "^2.6.11"
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 396784797@qq.com

**Additional context**

**Comment by azeranex** [comment]
Don't forget to import it first.
```
import {
  createProtocol,
  installVueDevtools // <---- here
} from 'vue-cli-plugin-electron-builder/lib'
```

**Comment by nklayman** [comment]
Thanks for the help @azeranex! @396784797 try their answer, it should fix it.
