### ISSUE TITLE
Video doesn't work on production build

### ISSUE THREAD

**Issue by azeranex** [nklayman/vue-cli-plugin-electron-builder#792]
**Describe the bug**
Video won't working on production build app but working fine during development. I doesn't load but href link to video file is working.

**To Reproduce**
1. Create vue app with vue cli (with router, vuex)
2. Add this vue-cli-plugin-electron-builder
3. Use video tag
```
<video
      ref="video"
      src="/videos/my-video.mp4"
      autoplay
      loop
      class="object-cover w-screen h-screen"
    />
```
4. Run npm run electron:build
5. Open .exe from win-unpacked folder

**Expected behavior**
Video is playing on production build.

**Environment (please complete the following information):**
 - OS and version: Windows 10 2004
 - node version: 12.16.3
 - npm version: 6.14.5
 - vue-cli-plugin-electron-builder version : 2.0.0-rc1
 - electron version: 9.0.2 (also 8.3.6)
 - other vue plugins used: eslint
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**

**Comment by nklayman** [comment]
Did you follow the [handling static assets guide](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#handling-static-assets) (just below the section on native modules)? The video should be placed in the public dir and accessed with `path.join(process.env.BASE_URL, 'video.mp4')`.

**Comment by azeranex** [comment]
I tried but I'm facing "Not allowed to load local resource" or CORS issue (when use webSecurity: false). Video files are in /public folder.

**Comment by azeranex** [comment]
I change protocol to file protocol to solve the problem. I will close to issue for now. But I still don't know why I can't use video with default protocol (app://).

**Comment by nklayman** [comment]
Try checking the [loading local images/resources](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#loading-local-images-resources) section of the docs.

**Comment by BusyHe** [comment]
youtube Video doesn't work on production build @nklayman 
dmg url：https://www.youtube.com/embed/5sF8WWteUCs?autoplay=1&cc_load_policy=0&controls=0&disablekb=0&enablejsapi=1&fs=0&iv_load_policy=3&modestbranding=1&playsinline=1&rel=0&wmode=opaque&origin=app%3A%2F%2F.&widgetid=1
in electron:serve is work

**Comment by starhu521** [comment]
> I change protocol to file protocol to solve the problem. I will close to issue for now. But I still don't know why I can't use video with default protocol (app://).

sorry to bother you. I have the same problem. I put the vide(mp4) in assets folder. and after i build. run app just show the 
request canceled in devtool.
![image](https://user-images.githubusercontent.com/23275495/86072538-591a5900-bab4-11ea-9cb1-de6eb63f6730.png)
Do you have any idea?

**Comment by azeranex** [comment]
@starhu521 I put my video files in static folder. Please make sure that you use file protocol. See [Changing the File Loading Protocol](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#changing-the-file-loading-protocol) for more info.

**Comment by starhu521** [comment]
> @starhu521 I put my video files in static folder. Please make sure that you use file protocol. See [Changing the File Loading Protocol](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#changing-the-file-loading-protocol) for more info.

yes,it works switch to file protocol. But i'm carious about why can't use custome protocol like app://

**Comment by azeranex** [comment]
I think it has something to do with streaming. I You may take a look at 
https://github.com/electron/electron/pull/22955

**Comment by starhu521** [comment]
> I think it has something to do with streaming. I You may take a look at
> [electron/electron#22955](https://github.com/electron/electron/pull/22955)

thanks a lot.

**Comment by andypotato** [comment]
@nklayman there seems to be a breaking change somewhere between Electron 5 and Electron 7 (or vue-cli-plugin-electron-builder 1.4.x and vue-cli-plugin-electron-builder 2.x)

Playing a video from the public folder works as expected with the older version but results in the issue described by the OP in later versions.
