### ISSUE TITLE
How to call background.js functions in Vue components？

### ISSUE THREAD

**Issue by medivhliu** [nklayman/vue-cli-plugin-electron-builder#798]

**Comment by nklayman** [comment]
Use [IPC Main](https://www.electronjs.org/docs/api/ipc-main) and [IPC Renderer](https://www.electronjs.org/docs/api/ipc-renderer).

**Comment by medivhliu** [comment]
Can this be done by using "remote" module?
I write "const mainProcess = window.require('electron').remote.require('./background.js');" in main.js but got "Uncaught Error: Cannot find module './background.js'"

**Comment by medivhliu** [comment]
> Use [IPC Main](https://www.electronjs.org/docs/api/ipc-main) and [IPC Renderer](https://www.electronjs.org/docs/api/ipc-renderer).

Can this be done by using "remote" module?
I write "const mainProcess = window.require('electron').remote.require('./background.js');" in main.js but got "Uncaught Error: Cannot find module './background.js'"

**Comment by nklayman** [comment]
No, you can't require main process files from the renderer process.
