### ISSUE TITLE
Plugin changes _gitignore too much :)

### ISSUE THREAD

**Issue by laSinteZ** [nklayman/vue-cli-plugin-electron-builder#8]
I've created a new vue-cli 3 project with e2e option as selenium. Plugin removes lines
```
/tests/e2e/reports/
selenium-debug.log
``` 
from gitignore after installation. I guess it is because it extends default _gitignore, which lacks those options for some reason.

<img width="839" alt="screen shot 2018-05-18 at 13 13 38" src="https://user-images.githubusercontent.com/10958990/40230423-19296820-5aa0-11e8-9e28-cae9dd2fcbc2.png">

**Comment by nklayman** [comment]
I believe the only way to change the gitignore file is by extending the default one, according to the vue-cli docs. This I feel is better than not changing it at all, as most people add this plugin right after they create their app. It can also be easily reversed if needed. I am going to close this for now but if you find a way to extend the current gitignore I will re-open and use that method.
