### ISSUE TITLE
TypeScript Boolean Check for nodeIntegration

### ISSUE THREAD

**Issue by esquivias** [nklayman/vue-cli-plugin-electron-builder#801]
**Describe the bug**
Type `string | undefined` is not assignable to type `boolean | undefined` in _background.js_; error reported by TypeScript.

**Actual:**
```nodeIntegration: process.env.ELECTRON_NODE_INTEGRATION```

**Expected**
```nodeIntegration: typeof process.env.ELECTRON_NODE_INTEGRATION == "boolean" ? process.env.ELECTRON_NODE_INTEGRATION : false```

**Environment (please complete the following information):**
 - OS and version: **MacOS 10.15.4 (Catalina)**
 - node version: **12.13.1**
 - npm version: **6.14.4**
 - typescript version: **3.9.5**
 - vue-cli-plugin-electron-builder version: **2.0.0-rc.1**
 - electron version: **9.0.0**

**Comment by nklayman** [comment]
Fixed with 81fa4fde72b77e5bcec4dda1e4c31b2b8f65302a.

**Comment by esquivias** [comment]
You beat me to it!

Thanks again for your review and effort on this, very much appreciated.

**Comment by nklayman** [comment]
Your welcome, thanks for helping! Even though your fix didn't get merged, it gave me a good starting point for my solution which I just thought was a little cleaner. Opening up a PR in addition to the issue showed me that it was an easy fix so I was able to get to it quicker.

**Comment by thoni56** [comment]
Maybe you'd want to update the [upgrade instructions in the release information](https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0) to include this fix. Just figured this out...

**Comment by nklayman** [comment]
V3 will be released soon so it doesn't seem necessary to go back and update that.
