### ISSUE TITLE
Both __static and process.env.BASE_URL crash when building without nodeIntegration

### ISSUE THREAD

**Issue by eulertour** [nklayman/vue-cli-plugin-electron-builder#803]
**Describe the bug**
Attempting to use either variable after building results in `Uncaught ReferenceError: require is not defined`. However, no warning or error is generating when running with `electron:serve`.

Enabling nodeIntegration results in `Electron Deprecation Warning The 'remote' module is deprecated and will be disabled by default in a future version of Electron`.

**To Reproduce**
Attempt to use either variable in a new project using electron 9.0.0.

**Expected behavior**
For at least one of the variables to return the path to `public/`.

**Environment (please complete the following information):**
 - OS and version: Arch Linux
 - node version: 14.3.0
 - npm version: 6.14.5
 - yarn version (if used): 1.22.4
 - vue-cli-plugin-electron-builder version : 2.0.0-rc.1
 - electron version: 9.0.0

**Additional context**
The docs are somewhat vague on how `__static` should work. On one hand they say it provides a path to your public directory in both development and production, but on the other they say it is not available in regular build/serve. Can you clarify what this means?

The warning that appears after enabling nodeIntegration is rather ominous. Are these variables dangerous, or will they be removed in a future release?

**Comment by nklayman** [comment]
`__static` only works in electron build/serve, not just `vue-cli-service build/serve`, and is expected to only work with `nodeIntegration` enabled. However, `process.env.BASE_URL` should work regardless so I need to update how that is determined so that it doesn't depend on electron remote. Thanks for reporting the issue!

**Comment by nklayman** [comment]
Fix released in v2.0.0-rc.2.
