### ISSUE TITLE
App icon is not getting loaded in GNU/Linux GNOME 3

### ISSUE THREAD

**Issue by RealGoodProgrammer** [nklayman/vue-cli-plugin-electron-builder#81]
**Describe the bug**
I tried the solution from issue #49, but it does not work.
And how can I achieve the same effect through vue.config.js file? Thanks.

**To Reproduce**
My logo is 64x64 png-file called **logo.png**. I put it in directly in **/public**, and in my **background.js** I wrote:
` const window = new BrowserWindow({
    ...
    icon: path.join(__static, 'logo.png')
  })`

**Expected behavior**
I want to see my logo :)
Also I have 
/public/img/icons/mac
/public/img/icons/png
/public/img/icons/win
Do I need to specify an icon for each platform separately in Travis?

**Environment (please complete the following information):**
 - OS and version: SMP Debian 4.17.17-1kali1 (2018-08-21) x86_64 GNU/Linux
 - Node version: v10.9.0
 - npm version: 6.2.0
 - yarn version (if used): 1.9.4
 - vue-cli-plugin-electron-builder version : #1.0.0-rc.3
 - other vue plugins used: { 
      "vue-cli-plugin-i18n": "^0.5.0",
      "@vue/cli-plugin-babel": "^3.0.1",
      "@vue/cli-plugin-e2e-cypress": "^3.0.1",
      "@vue/cli-plugin-eslint": "^3.0.1",
      "@vue/cli-plugin-pwa": "^3.0.1",
      "@vue/cli-plugin-unit-jest": "^3.0.1"
    }
 - custom config for vcp-electron-builder: -
 - (if possible) link to your repo:

**Comment by nklayman** [comment]
I'm going to close this as it works for me and it related to [electron-builder](https://electron.build), not this plugin. See [electron-builder's instructions](https://www.electron.build/icons) for more info. Continue to use `path.join(__static, 'logo.png')` for the logo path, and follow [this tutorial](https://www.christianengvall.se/electron-app-icons/). Also check out the [official electron docs](https://electronjs.org/docs/api/browser-window#class-browserwindow). If this doesn't work, let me know and I will look into it more.

**Comment by Voxelot** [comment]
I'm also having this issue. Feels like I've tried nearly everything, from configuring mac icns icons only, to linux png directory. Still just getting a red circle icon on ubuntu (icons work on windows and linux though)

```
"electron": "^3.1.10",
"vue-cli-plugin-electron-builder": "^1.3.4",
```
```
  win = new BrowserWindow({ width: 800, height: 600, webPreferences: {
		nodeIntegration: true,
		webSecurity: false,
		icon: path.join(__static, "icon.png")
  } })
```
The icon is located in `/public/icon.png`

**Comment by nklayman** [comment]
I'm not having any issues on Ubuntu. Try cloning the [electron-icon-example repo](https://github.com/nklayman/electron-icon-example) and see if the icon is customized. Make sure you followed [the guide](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#icons) properly as well.

**Comment by Voxelot** [comment]
Oh nice one, I didn't see this example repo before. Mega-helpful, all good now :+1:
