### ISSUE TITLE
Cant build for Windows / Linux

### ISSUE THREAD

**Issue by do-web** [nklayman/vue-cli-plugin-electron-builder#82]
if i run build, only the mac version is build but not for Windows or Linux.

**Comment by nklayman** [comment]
You need to specify your targets. See [here](https://www.electron.build/cli) for more info. Use `build:electron` instead of `electron-builder`.

**Comment by riksnelders** [comment]
How is this closed. Build:electron does not work if i append --mac for example?

**Comment by nklayman** [comment]
You can only build for Mac on a Mac.
