### ISSUE TITLE
Main Process build does not seem to behave the same way as Web build for webpack 'external' config

### ISSUE THREAD

**Issue by Meowzz95** [nklayman/vue-cli-plugin-electron-builder#820]
**Describe the bug**
I'm using sequelize package and it has problem with webpack, webpack tries to load package that we're not using, the issue is tracked [here](https://github.com/sequelize/sequelize/issues/7509#issuecomment-302913466).

A workaround by adding not used packages in webpack's config(detail can be found in the issue).

I put the same set of sequlize code in both Vue code and main process, and after applying the workaround, the first phase of build seems to be successful but second fails with the following error message.

```
 ERROR  Failed to compile with 1 errors                               5:04:07 PM

This dependency was not found:

* pg-hstore in ./node_modules/sequelize/lib/dialects/postgres/hstore.js

To install it, you can run: npm install --save pg-hstore
 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The code I use in main process and Vue,
```
// test sequlize
      const { Sequelize, Model, DataTypes } = require('sequelize');
      const sequelize = new Sequelize('sqlite::memory:');

      class User extends Model {}
      User.init({
        username: DataTypes.STRING,
        birthday: DataTypes.DATE
      }, { sequelize, modelName: 'user' });

      (async () => {
        await sequelize.sync();
        const jane = await User.create({
          username: 'janedoe',
          birthday: new Date(1980, 6, 20)
        });
        console.log(jane.toJSON());
      })();
      // test sequlize end
```

My web pack config added in vue.config.js

```
module.exports = {
  "transpileDependencies": [
    "vuetify"
  ],
  configureWebpack:{
    externals:  [
      'pg',
      'pg-hstore',
      'sqlite3',
      'mysql2'
    ],
  },
  pluginOptions: {
    electronBuilder: {
      // List native deps here if they don't work
      externals: ['dns'],
      // If you are using Yarn Workspaces, you may have multiple node_modules folders
      // List them all here so that VCP Electron Builder can find them
      nodeModulesPath: [
          // '../../node_modules',
        './node_modules'
      ]
    }
  }
}

```

**To Reproduce**
The above code snippets should be enough.

**Expected behavior**
Build success.

**Screenshots**
NA

**Environment (please complete the following information):**
 - OS and version: macOS 10.15.5
 - node version: v12.13.1
 - npm version:
 - yarn version (if used): 1.22.0
 - vue-cli-plugin-electron-builder version : 2.0.0 rc1
 - electron version: 9.0.0
 - other vue plugins used: vuetify
 - custom config for vcp-electron-builder: none
 - (if possible) link to your repo: none

**Comment by nklayman** [comment]
Try moving the `configureWebpack.externals` array to `pluginOptions.electronBuilder.externals`. `configureWebpack` only effects the renderer process, while the `electronBuilder.externals` array is set for both processes (and sets other required configuration).

**Comment by followbin** [comment]
> Try moving the `configureWebpack.externals` array to `pluginOptions.electronBuilder.externals`. `configureWebpack` only effects the renderer process, while the `electronBuilder.externals` array is set for both processes (and sets other required configuration).

can i set diffrent 'electronBuilder.externals' between both processes? what should i do ? .have a look: [ issues ](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1214)

**Comment by nklayman** [comment]
Why would you need separate externals? I can't think of a scenario where that would be beneficial.
