### ISSUE TITLE
Changing default name

### ISSUE THREAD

**Issue by Timibadass** [nklayman/vue-cli-plugin-electron-builder#821]
How can I rename my app from 'Electron' to anything I want?.

I have tried this solution https://github.com/electron/electron/issues/2543#issuecomment-133201841 but it only changes the 'title' from what I named my app(when creating the app with the Vue CLI), the 'Electron' still persists.

**Comment by nklayman** [comment]
The electron window title matches whatever your document title is, which is set in `index.html` The binary name is sourced from your `package.json`'s name field. If you are trying to rename something other than those two let me know and I can tell you how to configure that.

**Comment by Timibadass** [comment]
Hi, @nklayman This name is what I'm trying to change. I have searched for the string 'Electron' in my file and there's nothing like that present there.
<img width="244" alt="Screenshot 2020-06-15 at 11 28 14 AM" src="https://user-images.githubusercontent.com/25494586/84647480-69023c80-aefb-11ea-9e5f-0cb81c880771.png">

**Comment by nklayman** [comment]
That should be the `productName` property. Try setting your `vue.config.js` to:
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
        productName: 'my-app-name'
      }
    }
  }
}
```

**Comment by Timibadass** [comment]
Thanks! this works.

It might be worth adding that the name doesn't get updated in development mode, it only changes after running `yarn electron:build`.

**Comment by yogarasu** [comment]
With this plugin, when in development mode,
Does that mean you can't change the title?

The app created with the vue2 series
Even if you set the title in vue.config.js or background.js
I'm wondering what to do because the title is still "Vue App"

**Comment by nklayman** [comment]
The productName is for naming shortcuts for after your app is installed. Change the document title in `public/index.html` to change the window title.
