### ISSUE TITLE
How do I upgrade v2.0.0-rc.1 to v2.0.0-rc.2

### ISSUE THREAD

**Issue by wuxiaobin1995** [nklayman/vue-cli-plugin-electron-builder#822]
![image](https://user-images.githubusercontent.com/36044379/84607683-35b2b400-aee1-11ea-9575-b4938218cd05.png)

**Comment by nklayman** [comment]
All you need to do is change the version to `2.0.0-rc.2`, there are no other changes necessary.

**Comment by wuxiaobin1995** [comment]
should i delete the node_modules , and `npm i` again?

**Comment by nklayman** [comment]
No, just run `npm i` after changing the version.

**Comment by wuxiaobin1995** [comment]
ok，thanks
