### ISSUE TITLE
After running the exe, it is blank

### ISSUE THREAD

**Issue by funjobs** [nklayman/vue-cli-plugin-electron-builder#824]
Excuse me, I used "yarn run electron:build" to package and produce the exe used by the window. After installing the exe, the opening is blank. May I ask what is the cause?

**Comment by nklayman** [comment]
Try the first option on the [common issues section of the docs](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#blank-screen-on-builds-but-works-fine-on-serve).

**Comment by funjobs** [comment]
Thanks, I tried this method, it should not be a routing problem.

**Comment by funjobs** [comment]
I am using "vue-cli-plugin-electron-builder": "~2.0.0-rc.2".

**Comment by ihewro** [comment]
Hi, In the end, how to solve the problem?
