### ISSUE TITLE
createProtocol support VueRouter history mode

### ISSUE THREAD

**Issue by czastack** [nklayman/vue-cli-plugin-electron-builder#826]
**Is your feature request related to a problem? Please describe.**
Yes. When you use VueRouter with history mode and home page is / in the production mode, home page didn't show.
Because ```win.loadURL('app://./index.html')```, the pathname is '/index.html' rather than '/'

**Describe the solution you'd like**
file: vue-cli-plugin-electron-builder/lib/createProtocol.js
```javascript
export default scheme => {
  protocol.registerBufferProtocol(
    scheme,
    (request, respond) => {
      let pathName = new URL(request.url).pathname
      pathName = decodeURI(pathName) // Needed in case URL contains spaces

      // add here
      // import { readFile, existsSync } from 'fs'
      if (!existsSync(path.join(__dirname, pathName))) {
        pathName = 'index.html'
      }
      ...
```

file: src/background.js
```javascript
// win.loadURL('app://./index.html')
win.loadURL('app://.')
```

Then it work well.

**Comment by nklayman** [comment]
Is there a reason you need history mode instead of hash? It's really easy to use history in web builds and hash in electron automatically, [just follow these docs](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#blank-screen-on-builds-but-works-fine-on-serve).

**Comment by czastack** [comment]
@nklayman For example, when I use autofocus attribute such as `<input autofocus />`,
then the browser console this:
>**Autofocus processing was blocked because a document's URL has a fragment '#/'.**

Althought I can use 
```javascript
Vue.directive('focus', {
  inserted: function (el) {
    el.focus()
  }
})
```

```html
<input v-focus>
```

So, I will use hash in electron, thank you.
