### ISSUE TITLE
`.env` config not work in main process for build bundle

### ISSUE THREAD

**Issue by ovo4096** [nklayman/vue-cli-plugin-electron-builder#83]
**Describe the bug**
`.env` config not work in main process for build bundle

**To Reproduce**
1. create `.env` in project root
2. create and set a env, example `VUE_APP_TITLE=test`
3. build and run, try output `process.env.VUE_APP_TITLE`

**Expected behavior**
Can output `test` of  `process.env.VUE_APP_TITLE`

**Environment (please complete the following information):**
 - OS and version: windows 10
 - Node version: v10.8.0
 - npm version: 6.2.0
 - vue-cli-plugin-electron-builder version : ^1.0.0-beta.6

**Additional context**
I think this bug may happen in not config webpack, I try https://webpack.electron.build/environment-variables but still can't work

**Comment by nklayman** [comment]
If I were to make it automatic, should the prefix be `VUE_APP`, `ELECTRON_APP`, or something else?

**Comment by ovo4096** [comment]
> If I were to make it automatic, should the prefix be `VUE_APP`, `ELECTRON_APP`, or something else?

If it is `VUE_APP`, it can be consistent in the main process and the rendering process.

I choose `VUE_APP`.
