### ISSUE TITLE
使用命令yarn 安装依赖一直卡在building fresh packages 

### ISSUE THREAD

**Issue by jiumengs** [nklayman/vue-cli-plugin-electron-builder#833]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS and version:
 - node version: 
 - npm version:
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 
 - electron version: 
 - other vue plugins used: 
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**

**Comment by nklayman** [comment]
Please fill out all the information asked for in the big report template.
