### ISSUE TITLE
Render process import { ipcRenderer } from 'electron' Report an error.

### ISSUE THREAD

**Issue by xuehonghao** [nklayman/vue-cli-plugin-electron-builder#835]
vue components script  import { ipcRenderer } from 'electron' 
![image](https://user-images.githubusercontent.com/46518758/85200412-b03c6300-b329-11ea-9f72-f1cbc8f6c623.png)

then npm run electron:serve

![image](https://user-images.githubusercontent.com/46518758/85200392-8d11b380-b329-11ea-9e99-3dcdd08c57e8.png)

I don't know what went wrong

**Comment by nklayman** [comment]
Have you enabled [nodeIntegration](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration)?

**Comment by xuehonghao** [comment]
> Have you enabled [nodeIntegration](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration)?

Thank you very much! Using your method successfully solved this problem

**Comment by DeadlySurgeon** [comment]
Can there be a note of this on the main README or documented somewhere? I ran into this issue too and it took me longer than I'd like to admit to find this page..
