### ISSUE TITLE
File protocol not supported

### ISSUE THREAD

**Issue by hosnar** [nklayman/vue-cli-plugin-electron-builder#846]
Hello,

I am trying to use electron-updater with local path to update package (like described [here](https://github.com/electron/electron/issues/5020#issuecomment-477636990)).

But I keep getting an error "_Error: Error: Protocol "file:" not supported_". I also tried using customFileProtocol as "_./_" and "win.loadURL(`file://${__dirname}/index.html`)" and I still get this error. Is there a way I could use file protocol and can you help me figure out what I am doing wrong here? Because I have been at this for days and I can't find a solution.

Thank you

**Comment by nklayman** [comment]
Please open a new issue that follows the bug report template. I need more information about your project and environment to help you.
