### ISSUE TITLE
An error occurred: require('fs-extra') 

### ISSUE THREAD

**Issue by DougFlands** [nklayman/vue-cli-plugin-electron-builder#849]
**Describe the bug**
if `require('fs-extra') `
tell me 
```
Uncaught TypeError: Cannot read property 'match' of undefined
    at patch (polyfills.js?a0a3:31)
    at patch (graceful-fs.js?0da7:104)
    at Object.eval (graceful-fs.js?0da7:96)
    at eval (graceful-fs.js:356)
    at Object../node_modules/graceful-fs/graceful-fs.js (chunk-vendors.js:1476)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at eval (index.js?ec2f:5)
    at Object../node_modules/fs-extra/lib/fs/index.js (chunk-vendors.js:1249)
    at __webpack_require__ (app.js:854)
```

**To Reproduce**
1. vue-cli 4.0 create Vue Project
2. vue add electron-builder
3. `main.js`  add
```
if (process.env.IS_ELECTRON) {
  console.log(process)
  console.log(process.env)
  const fs = require('fs-extra');
  console.log(fs)
}
```
4. `background.js` add
`nodeIntegration: true`

**Expected behavior**
no error

**Screenshots**
if i use electron 6.0, the` process` out put this.
![1](https://user-images.githubusercontent.com/15337471/85513824-f9dcc480-b62d-11ea-9d5c-57f08808f7a7.png)

electron 9.0, the` process` out put this.
![2](https://user-images.githubusercontent.com/15337471/85514238-6b1c7780-b62e-11ea-9e07-c97798a066fe.png)

**Environment (please complete the following information):**

 - OS and version: windows 10 1809
 - node version: v12.16.2
 - npm version: 6.14.4
 - vue-cli-plugin-electron-builder version :  ~2.0.0-rc.2
 - electron version: ^9.0.0

**Additional context**
Did I forget what to configure?

**Comment by DougFlands** [comment]
module.exports = {
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true
    }
  }
}

**Comment by MehJv** [comment]
大佬 我报这个错了请问你解决了吗

**Comment by MehJv** [comment]
![image](https://user-images.githubusercontent.com/48472208/210049103-4696269d-f60e-426b-9e80-5755ac5191ad.png)
页面内容都不出来  我是import引进来的
