### ISSUE TITLE
安装vue-cli-plugin-electron-builder插件后点击导航都指向404

### ISSUE THREAD

**Issue by haliuhei** [nklayman/vue-cli-plugin-electron-builder#851]
项目运行起来后，通过vue ui安装vue-cli-plugin-electron-builder 插件，版本2.0.0-rc.2，根据electron（地址：https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration）
要求在vue.config.js下添加：

`publicPath: '/',
  outputDir: 'dist',
  assetsDir: 'static',
  lintOnSave: process.env.NODE_ENV === 'development',

  **pluginOptions: {
    electronBuilder: {
      nodeIntegration: true
    }
  },**

  productionSourceMap: false,`

加粗为在vue.config.js增加的内容。
然后项目跑起来，登录后，点击左侧导航，跳转的路径都是404。
不添加vue.config.js里面加粗内容的话，运行electron，可以正常跳转，
但是在页面引入模块的时候报错，比如guide页面引入
`import { ipcRenderer } from 'electron'`
提示：
`vue-router.esm.js?8c4f:1897 ReferenceError: __dirname is not defined
    at eval (index.js?bdb9:4)
    at Object../node_modules/electron/index.js (chunk-vendors.js:8757)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at eval (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/guide/index.vue?vue&type=script&lang=js&:7)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/guide/index.vue?vue&type=script&lang=js& (app.js:2042)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at eval (index.vue?cc91:1)
    at Module../src/views/guide/index.vue?vue&type=script&lang=js& (app.js:11017)`

**Comment by haliuhei** [comment]
字体加粗

**Comment by nklayman** [comment]
Please post your `src/background.js` as well. I think you may be missing some configuration.

**Comment by haliuhei** [comment]
'use strict'

import { app, protocol, BrowserWindow } from 'electron'
import {
  createProtocol,
  installVueDevtools
} from 'vue-cli-plugin-electron-builder/lib'
const isDevelopment = process.env.NODE_ENV !== 'production'

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let win

// Scheme must be registered before the app is ready
protocol.registerSchemesAsPrivileged([
  { scheme: 'app', privileges: { secure: true, standard: true } }
])

function createWindow() {
  // Create the browser window.
  win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      // Use pluginOptions.nodeIntegration, leave this alone
      // See nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration for more info
      nodeIntegration: process.env.ELECTRON_NODE_INTEGRATION
    }
  })

  if (process.env.WEBPACK_DEV_SERVER_URL) {
    // Load the url of the dev server if in development mode
    win.loadURL(process.env.WEBPACK_DEV_SERVER_URL)
    if (!process.env.IS_TEST) win.webContents.openDevTools()
  } else {
    createProtocol('app')
    // Load the index.html when not in development
    win.loadURL('app://./index.html')
  }

  win.on('closed', () => {
    win = null
  })
}

// Quit when all windows are closed.
app.on('window-all-closed', () => {
  // On macOS it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  // On macOS it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (win === null) {
    createWindow()
  }
})

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
  if (isDevelopment && !process.env.IS_TEST) {
    // Install Vue Devtools
    try {
      await installVueDevtools()
    } catch (e) {
      console.error('Vue Devtools failed to install:', e.toString())
    }
  }
  createWindow()
})

// Exit cleanly on request from parent process in development mode.
if (isDevelopment) {
  if (process.platform === 'win32') {
    process.on('message', (data) => {
      if (data === 'graceful-exit') {
        app.quit()
      }
    })
  } else {
    process.on('SIGTERM', () => {
      app.quit()
    })
  }
}

以上，安装后的默认配置，更改nodeIntegration:true,依然出错。
运行electron打开窗口会出现登录页面，登录后有首屏信息（即可以显示Dashboard 的appmain信息，一些图表），再点击左侧的任意一个侧边栏时跳转到404页面

**Comment by nklayman** [comment]
Please share the repo that has this issue or create a new one. I can't get this issue to happen for me so I can't debug it.

**Comment by haliuhei** [comment]
> Please share the repo that has this issue or create a new one. I can't get this issue to happen for me so I can't debug it.

我提交了个错误的问题，原本是留言给vue-element-admin这个项目作者的，抱歉，刚发现，疏忽了.这个插件运行初始化项目没有问题的，sorry
