### ISSUE TITLE
Accessing `webFrame`

### ISSUE THREAD

**Issue by elcontraption** [nklayman/vue-cli-plugin-electron-builder#86]
I'm trying to disable pinch/zoom using [`setVisualZoomLevelLimits` on `webFrame`](https://github.com/electron/electron/blob/451b1782acfef01dd0758e7b9ddb329700626b98/docs/api/web-frame.md#webframesetvisualzoomlevellimitsminimumlevel-maximumlevel). I think this needs to happen on the render process–but where would I be able to access `webFrame`? 

Thank you for any assistance.

**Comment by nklayman** [comment]
Just `import {webFrame} from 'electron'`.

**Comment by elcontraption** [comment]
For anyone else who might find this useful... I was attempting to access `webFrame` in `background.js` which did not work for me, but I was able to get it working within a view component:

```js
import isElectron from 'is-electron'

let electron = isElectron()
  ? window.require('electron')
  : false
```
And inside a method:

```js
electron.webFrame.setVisualZoomLevelLimits(1, 1)
```
