### ISSUE TITLE
Try the new native dependency checker (Help Wanted)

### ISSUE THREAD

**Issue by nklayman** [nklayman/vue-cli-plugin-electron-builder#861]
If your app uses native dependencies, chances are you have had to configure the `externals` array in `vue.config.js`. Included in `v2.0.0-rc.3` is a new way of checking for native deps that should allow you to completely remove your `externals` array. It is currently disabled by default, but I would like to replace the old version by `v2.0.0`.

To test it, simply upgrade to `v2.0.0-rc.3` and update your `vue.config.js` like so:
```diff
module.exports = {
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true,
-       externals: ['native-dep', ...]
+       experimentalNativeDepCheck: true
    }
  }
}
```

Now, run `electron:serve` and it should automatically detect native deps and compilation should succeed. If this works for you, please :+1: this issue. If not, please leave a comment with the native deps you are using.

**Comment by iamazik** [comment]
While the native dependencies are now working, I am seeing the following warnings on terminal whenever using native dependency like https://github.com/svg/svgo.

```shell
Launching Electron...
(electron) 'BrowserWindow.addDevToolsExtension' is deprecated and will be removed. Please use 'session.loadExtension' instead.
(node:5653) ExtensionLoadWarning: Warnings loading extension at /Library/Application Support/dd/extensions/nhdogjmejiglipccpnnnanhbledajbpd: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'update_url'. Permission 'contextMenus' is unknown or URL pattern is malformed. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
```

Whenever I remove the native dependency reference from the code, the warnings disappear. I tried with the `experimentalNativeDepCheck: true` check in `vue.config.js`.

**Comment by nklayman** [comment]
@iamazik It's odd that those warnings only appear with native deps as they are related to devtools extensions. See https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-rc.4 for instructions on upgrading to `electron-devtools-installer` which will fix those warnings.

**Comment by iamazik** [comment]
I don't know why but the `v2.0.0-rc.4` is now showing the following warning in the terminal when even without having a native dependency at all. It's just a fresh project:

```shell
ExtensionLoadWarning: Warnings loading extension at /Library/Application Support/project/extensions/nhdogjmejiglipccpnnnanhbledajbpd: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'update_url'. Permission 'contextMenus' is unknown or URL pattern is malformed. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
```

**Comment by nklayman** [comment]
@iamazik I think that is a bug with VueJS Devtools not supporting some electron 9 changes, but I'm not sure. Try clearing the app's config (`rm -r ~/.config/APP_NAME`).

**Comment by romansp** [comment]
With `experimentalNativeDepCheck: true` I see the following warning during bundling:

```
 WARNING  Compiled with 1 warnings                                                                          10:34:02 PM
 warning  in ./node_modules/express/lib/view.js

Critical dependency: the request of a dependency is an expression
```

We have a direct dependency on express and use it inside our app but it still starts and works correctly. All other native dependencies look fine when in development. Haven't tried published app yet.

**Comment by claudioluciano** [comment]
It's not working for me.
```
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to 
process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

I'm using [neon-binding](https://neon-bindings.com/) to create the native module.

**Comment by nklayman** [comment]
@claudioluciano is the native module in `node_modules` or in a sperate folder? If it's in `node_modules`, can you post the list of files in it (`ls node_modules/module-name`)?

**Comment by claudioluciano** [comment]
@nklayman I tried to put it in `node_modules`, in a separate folder at the root of the project, it didn't work.
When I placed the module in node_modules, I placed only the `.node` file

**Comment by nklayman** [comment]
The new checker won't work for `.node` files as it looks for a `bindings.gyp` file, which is the same technique electron-builder uses to find native modules that need to be built. You will have to keep that in your `externals` array.

**Comment by nklayman** [comment]
@romansp the old checker reports `express` as an external, while the new one doesn't. Even though express doesn't have any native code, it seems people recommend [adding it as an external regardless](https://github.com/webpack/webpack/issues/1576), so you may want to add it to your externals array.

**Comment by iamazik** [comment]
> @iamazik I think that is a bug with VueJS Devtools not supporting some electron 9 changes, but I'm not sure. Try clearing the app's config (`rm -r ~/.config/APP_NAME`).

@nklayman I am afraid to say that I don't have anything located in the `rm -r ~/.config/APP_NAME` that I could delete. I only have the following under the `~/.config` location:
```
~/.config/
├── configstore/
    ├── nodemon.json
    ├── update-notifier-npm.json
    ├── update-notifier-electron-builder.json
├── yarn/
    ├── global/
```

### Separate issue
I found something else now. The new `experimentalNativeDepCheck: true` in the `vue.config.js` doesn't work when a non-native dependency has a native peer dependency. However, the old `externals: ['']` still works though.

For example, the [@iconify/tools](https://github.com/iconify/tools) is a non-native dependency whereas, it has the [svg/svgo](https://github.com/svg/svgo) as a peer dependency which is a native dependency. When I use the `experimentalNativeDepCheck: true` in the `vue.config.js` file, it doesn't work and shows the following error:
```shell
Error: ENOENT: no such file or directory, open '/Users/mazik/Desktop/icon-suite/dist_electron/../../.svgo.yml'
```
This error is related to the native dependency issue that was described [here](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/640) before.

### Steps to reproduce
`vue.config.js`
```javascript
module.exports = {
  pluginOptions: {
    electronBuilder: {
      preload: 'src/preload.js',
      experimentalNativeDepCheck: true
    }
  }
}
```
`App.vue`
```javascript
export default {
  name: 'App',
  mounted() {
    window.ipcRenderer.send('home');
};
```
`background.js`
```javascript
import tools from '@iconify/tools';
import { ipcMain } from 'electron';

let collection;

ipcMain.on('home', event => {
  tools
  .ImportDir('./source')
  .then(result => {
    collection = result;
    
    return collection.promiseAll(svg => tools.SVGO(svg));
  })
  .catch(error => console.error(error));
});
```
Where `./source` directory includes a `.svg` file/icon. When running the above example, you'll see the error. However, if you use the following, there won't be an error:

`vue.config.js`
```javascript
module.exports = {
  pluginOptions: {
    electronBuilder: {
      preload: 'src/preload.js',
      externals: ['@iconify/tools'],
    }
  }
}
```
I hope that it helps you to find the root cause of the issue ✌️

**Comment by nklayman** [comment]
`svgo` isn't a native dependency as it doesn't need to build native bindings. It just  [reads a config file](https://github.com/svg/svgo/blob/27cdeb7c1ca550466fc4e4637a6ebd255d948f2a/lib/svgo/config.js#L30) at runtime, which means it has to be externalized. There isn't a good way of detecting this automatically so I can't really do anything about it.

**Comment by iamazik** [comment]
Aah, thanks @nklayman 😀  It's completely fine as I can still use it but I just wanted to report it to make sure that you are aware of it ✌️

**Comment by nancologist** [comment]
I should still use the array, it does not work with **lighthouse**
https://www.npmjs.com/package/lighthouse

**Comment by sabifa** [comment]
Interestingly enabling `experimentalNativeDepCheck` works for me when I start the app via `electron:serve` but after I build my app it does not work anymore. 
Error after starting my production built app: 
![image](https://user-images.githubusercontent.com/25851344/94956245-238a6f00-04ec-11eb-9505-25994df3e945.png)

I'm using [serialport](https://github.com/serialport/node-serialport) and [node-irsdk](https://github.com/apihlaja/node-irsdk)

**Comment by ejohnso49** [comment]
Unfortunately I did not have luck using this option. My one native dependency is just `serialport`.

I am running v2.0.0-rc.5 of the plugin.

**Comment by Nisthar** [comment]
A quick question i can load a native module in development using `externals:['moduleName']`. how do i load this module when building?

**Comment by gianlucamazzeo** [comment]
Please can you help me
I'm trying to make two native modules that work with:
ffi-napi, ref-napi,

I've also added in vue.config.js : externals: ['ffi-napi', 'ref-napi']
but the error persist and  returns:
 
INFO Launching Electron ...
App threw an error during load
Error: No native build was found for platform = darwin arch = x64 runtime = electron abi = 87 uv = 1 libc = glibc node = 14.16.0 electron = 12.0.16 webpack = true
    loaded from: / testcerta
    at Function.load.path (webpack: ///./node_modules/node-gyp-build/index.js?: 59: 9)
    at load (webpack: ///./node_modules/node-gyp-build/index.js?: 21: 30)
    at eval (webpack: ///./node_modules/ref-napi/lib/ref.js?: 8: 111)
    at Object ../ node_modules / ref-napi / lib / ref.js (/testcerta/dist_electron/index.js:2365:1)
    at __webpack_require__ (/testcerta/dist_electron/index.js:20:30)
    at eval (webpack: ///./node_modules/ffi-napi/lib/ffi.js?: 7: 13)
    at Object ../ node_modules / ffi-napi / lib / ffi.js (/testcerta/dist_electron/index.js:1171:1)
    at __webpack_require__ (/testcerta/dist_electron/index.js:20:30)
    at eval (webpack: ///./node_modules/sign-sdk/lib/SignSDK.js?: 2: 13)
    at Object ../ node_modules / sign-sdk / lib / SignSDK.js (/testcerta/dist_electron/index.js:2472:1)

**Comment by nklayman** [comment]
Closing as the new native dep checker is enabled by default in v3 alpha. While there are some issues with it, it's still much better than the old one and I don't know of any ways to improve it as of now.
