### ISSUE TITLE
Can't change the icon for Linux

### ISSUE THREAD

**Issue by ClementDreptin** [nklayman/vue-cli-plugin-electron-builder#864]
Hi,

I can't seem to change to app icon when I build for Linux (I didn't try for any other OS). The default icon (the purple square with the gears) is always there no matter what I do.

My vue.config.js:
```
module.exports = {
    pluginOptions: {
        electronBuilder: {
            builderOptions: {
                linux: {
                    category: 'Chat',
                    target: 'deb'
                }
            }
        }
    }
}
```

My folders:
```
app/
----build/
--------icons/
------------16x16.png
------------...
------------1024x1024.png
------------icon.icns
------------icon.ico
----public/
--------icon.png
```

I tried to manually set the icon in the builderOptions and the result is still the same. I even tried to include all the files from the `build/icons/` folder by adding `files: ["**/*", "build/icons/*"]` to the config as mentioned [here](https://www.electron.build/configuration/configuration#MetadataDirectories-buildResources).

There must me something I'm missing or not understand. Any help would be much appreciated.

Thanks in advance.

**Comment by nklayman** [comment]
Try [the official guide for app icons](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#icons).

**Comment by ClementDreptin** [comment]
Thanks for your response.

I already did, that's how I generated the `build` folder from my icon. I also changed my `background.js` like mentioned in the guide.

The `win` object from my `background.js`:
```
    // Create the browser window.
    win = new BrowserWindow({
        icon: path.join(__static, 'icon.png'),
        webPreferences: {
            // Use pluginOptions.nodeIntegration, leave this alone
            // See nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration for more info
            nodeIntegration: process.env.ELECTRON_NODE_INTEGRATION
        }
    });
```

I tried to log `path.join(__static, 'icon.png')` in the console and it looks right. It's something like `/root/of/my/project/public/icon.png`.

**Comment by nklayman** [comment]
What happens if you run the [example](https://github.com/nklayman/electron-icon-example)? Does the icon work for you there?

**Comment by ClementDreptin** [comment]
I managed to fix my issue by removing all the generated images except for the .icns and .ico ones and putting them directly under `build/`.

Thanks for your time and also for this awesome builder that saved me so much time :)

**Comment by nklayman** [comment]
Glad that you figured it out!
