### ISSUE TITLE
Remove Menu Bar

### ISSUE THREAD

**Issue by LaravDev** [nklayman/vue-cli-plugin-electron-builder#867]
Hi!, is it there a way to remove the top nav-menu bar? 

![image](https://user-images.githubusercontent.com/35145882/85924784-9e8b1c00-b851-11ea-9a50-3c5ed027ba87.png)

Thanks in advance

**Comment by nklayman** [comment]
Add `win.setMenu(null)` under `createProtocol('app')` (line 39ish).

**Comment by patarapolw** [comment]
How about removing only some dangerous menus, like Toggle DevTools?

**Comment by nklayman** [comment]
@patarapolw [This post](https://discuss.atom.io/t/a-way-to-prevent-developer-tools/29746/9) should work for disabling devtools only.
