### ISSUE TITLE
File protocol not supported

### ISSUE THREAD

**Issue by hosnar** [nklayman/vue-cli-plugin-electron-builder#868]
Hello, this is a follow up of [this](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/846#issuecomment-648410080).

**Describe the bug**
I am trying to use electron-updater with local path to update package (like described [here](https://github.com/electron/electron/issues/5020#issuecomment-477636990)).

But I keep getting an error "_Error: Error: Protocol "file:" not supported_". I also tried using customFileProtocol as "_./_" and "_win.loadURL(file://${__dirname}/index.html)_" and I still get this error. 

**To Reproduce**
```javascript
import { autoUpdater } from 'electron-updater';

app.on('ready', async () => {
  const fs = require('fs');
  // Set global temporary directory for things like auto update downloads, creating it if it doesn't exist already.
  global.tempPath = path.join(app.getPath('temp'), 'NTWRK');
  if (!fs.existsSync(global.tempPath)) fs.mkdirSync(global.tempPath);

  // We need to manually create a feed.json file with a `url` key that points to our local `.zip` update file.
  // For test purpose, install-package.zip is manually copied into this directory (later it will be downloaded upon app start)
  const json = { url: `file://${ global.tempPath }/install-package.zip` };

  fs.writeFileSync(global.tempPath + '/feed.json', JSON.stringify(json));

  const feedURL = `file://${global.tempPath}/feed.json`;

  autoUpdater.setFeedURL(feedURL);

  autoUpdater.checkForUpdates(); // or checkForUpdatesAndNotify()

  createWindow();
})
```

**Expected behavior**
This code should check if update package is available by using file protocol path (shouldn't result in error). For test purpose I copied .zip package to source path, but later app will download package from server upon app start. I also tested autoupdate with package being uploaded on server and using http protocol instead of file protocol and that worked fine. But I am required to do it with file protocol, if possible.

**Screenshots**
Console error:
![Screenshot 2020-06-29 at 07 27 44](https://user-images.githubusercontent.com/11992843/85976212-45022900-b9da-11ea-9379-8c09316d8e0e.png)

**Environment (please complete the following information):**
 - terminal output from running `vue info`:
```Environment Info:

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz
  Binaries:
    Node: 12.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.13.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 72.0.2
    Safari: 13.1.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.2.2
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.2.2
    @vue/cli-plugin-babel: ^4.2.0 => 4.2.2
    @vue/cli-plugin-eslint: ^4.2.0 => 4.2.2
    @vue/cli-plugin-router:  4.2.2
    @vue/cli-plugin-vuex:  4.2.2
    @vue/cli-service: ^4.2.0 => 4.2.2
    @vue/cli-shared-utils:  4.2.2
    @vue/component-compiler-utils:  3.1.1
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^6.1.2 => 6.2.1
    vue: ^2.6.11 => 2.6.11
    vue-cli-plugin-electron-builder: ^2.0.0-rc.2 => 2.0.0-rc.2
    vue-clickaway:  2.2.2
    vue-context: ^5.1.0 => 5.1.0
    vue-eslint-parser:  7.0.0
    vue-hot-reload-api:  2.3.4
    vue-i18n: ^8.15.3 => 8.15.3
    vue-loader:  15.9.0
    vue-router: ^3.1.5 => 3.1.5
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.1.2 => 3.1.2
  npmGlobalPackages:
    @vue/cli: 3.3.0
```

If you need anything else, please let me know. Thank you.

**Comment by nklayman** [comment]
The update process is handled by [electron-builder](https://github.com/electron-userland/electron-builder), this plugin shouldn't have any impact on it. You should open an issue there instead as that is what is throwing the error. I think it is intentional that the updater only supports a `http(s)` url, so you may have to make a custom patch.
