### ISSUE TITLE
How to use my own App Icon .ico

### ISSUE THREAD

**Issue by mrin9** [nklayman/vue-cli-plugin-electron-builder#87]
**Is your feature request related to a problem? Please describe.**
A way to provide .ico file to be used as the App Icon. Currently the App uses the default electron icon

**Describe the solution you'd like**
After building, The new app uses the default electron icon 

**Describe alternatives you've considered**
I have tried to place the .ico files in different location, but the plugin failed to pick it up to be used as an App Icon

**Comment by mrin9** [comment]
thanks !!! 
Are these, [electron-builder](https://www.electron.build/configuration/configuration) configurations ?

**Comment by ovo4096** [comment]
> thanks !!!
> Are these, [electron-builder](https://www.electron.build/configuration/configuration) configurations ?

yes

**Comment by ibalaji777** [comment]
> @mrin9 Just copy your icon to project root, then add `vue.config.js`:
> 
> ```
> module.exports = {
>   pluginOptions: {
>     electronBuilder: {
>       builderOptions: {
>         win: {
>           icon: './icon.ico'
>         }
>       }
>     }
>   }
> }
> ```

not working for me

**Comment by nklayman** [comment]
@ibalaji777 see the [icon guide](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/recipes.html#icons) (check toc for link).

**Comment by piyunior** [comment]
Thanks @nklayman...

**Comment by Mikeonii** [comment]
> pluginOptions: {
>     electronBuilder: {
>       builderOptions: {
>         win: {
>           icon: './icon.ico'
>         }
>       }
>     }
>   }

this doesn't work on my project. I don't know why.

**Comment by piyunior** [comment]
Hi @Mikeonii...  check your version of electronjs?

**Comment by IrvingRamirez1710** [comment]
para que funcione el icono, tiene que ser de 256px x 256px, sin no va mandar este error ERR_ICON_TOO_SMALL

- probe con formato .ico y .png y funciona bien
