### ISSUE TITLE
App does not work when built, the screen remains empty

### ISSUE THREAD

**Issue by mxswat** [nklayman/vue-cli-plugin-electron-builder#871]
**Describe the bug**
I followed this [tutorial ](https://codesource.io/build-a-desktop-application-with-vuejs-and-electronjs/) to make an electron vue app but when 

**Screenshots**
![image](https://user-images.githubusercontent.com/17874432/86042848-0dca6100-ba48-11ea-87af-43828ef024ea.png)

**Environment**
-     "core-js": "^3.6.5",
-     "rxjs": "^6.5.5",
-     "vue": "^2.6.11",
-     "vue-class-component": "^7.2.3",
-     "vue-property-decorator": "^8.4.2",
-     "vue-router": "^3.2.0",
-     "vuex": "^3.4.0"
-     "@vue/cli-plugin-babel": "~4.4.0",
-     "@vue/cli-plugin-router": "~4.4.0",
-     "@vue/cli-plugin-typescript": "^4.4.6",
-     "@vue/cli-plugin-vuex": "~4.4.0",
-     "@vue/cli-service": "~4.4.0",
-     "electron": "^9.0.0",
-     "electron-cgi": "^1.0.5",
-     "node-sass": "^4.12.0",
-     "sass-loader": "^8.0.2",
-     "typescript": "~3.9.3",
-     "vue-cli-plugin-electron-builder": "~2.0.0-rc.3",
-     "vue-template-compiler": "^2.6.11"
- terminal output from running `vue info`:
  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmGlobalPackages:
    @vue/cli: Not Found

vue --version: @vue/cli 4.4.6

**Additional context**
I'm working on a simple app that works great during the "serve" but when built I have an empty screen
It's the first time I have an issue like this when using electron
Also, I have no error in console on the production version and no errors during the serve.

This entire app is based on https://github.com/Wisdom132/Electronjs-Vuejs-Sweeeet where I opened an issue there too.
https://github.com/Wisdom132/Electronjs-Vuejs-Sweeeet/issues/2

**Comment by mxswat** [comment]
I just realized that I wasn't using the router in hash mod but in history mode

Now it works

Is this a know issue?

**Comment by nklayman** [comment]
[It is a known issue](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#blank-screen-on-builds-but-works-fine-on-serve), and a warning should be printed when you add this plugin.
