### ISSUE TITLE
production can not play local video

### ISSUE THREAD

**Issue by starhu521** [nklayman/vue-cli-plugin-electron-builder#872]
**Describe the bug**
I'm using Vue cli 4 to build the project.I can not load and play the local video in production but development is fine.
And the video is mp4, I put it in assets folder.
Devtools shows like:
![image](https://user-images.githubusercontent.com/23275495/86075369-7520f900-baba-11ea-877c-1cb6e71c7f30.png)
![image](https://user-images.githubusercontent.com/23275495/86075408-80742480-baba-11ea-8c7a-9ac69a65c0ff.png)

OR like this:
![image](https://user-images.githubusercontent.com/23275495/86075461-9f72b680-baba-11ea-836e-f1e0880a5725.png)
![image](https://user-images.githubusercontent.com/23275495/86075474-a699c480-baba-11ea-8f52-c85d27ffcdde.png)
 version:
electron: 9.0.5
vue-cli-plugin-electron-builder: 2.0.0-rc.2

**Expected behavior**
I hope to play video normal like image.

**Comment by andypotato** [comment]
I'm having the same issue with Electron 8 I had to downgrade to Electron 5 to get videos to work again.

**Comment by starhu521** [comment]
> I'm having the same issue with Electron 8 I had to downgrade to Electron 5 to get videos to work again.
> 
> _Edit_ It made no difference putting the videos in the "public" or "assets" folder.

Yes, and you also can use node stream pipe or change the protocol to file://. Just the custome protocol has the issue.

**Comment by nklayman** [comment]
I was able to play a video just by putting it in the `public` folder and then referencing it like so:
```html
<video width="320" height="240" controls>
  <source src="vid.mp4" type="video/mp4" />
</video>
```
This was on electron v9. Can someone try this method and report if it works?

**Comment by azeranex** [comment]
@nklayman I tried it with electron 9.1.0 but it didn't work.

**Comment by nklayman** [comment]
@azeranex what version of this plugin did you use?

**Comment by azeranex** [comment]
@nklayman I'm using version 2.0.0-rc4.

**Comment by nklayman** [comment]
Hmm, could you create a demo repo and post a link here so that I can try it myself?

**Comment by azeranex** [comment]
Here it is https://github.com/azeranex/vue-cli-electron-video-demo

**Comment by andypotato** [comment]
I can reproduce the error with Electron 7, 8 and 9. Using Electron 6 or below it works just fine.

The version of the plugin does not matter, the error happens with both 1.4.6 and current 2.0.0-rc4.

**Comment by nklayman** [comment]
@azeranex thanks for the repo, I realized I was testing it on a project that used the file protocol enabled instead of `app://` :facepalm:. I did find a solution though that works for `app://` protocol:

```js
// in background.js
app.on('ready', async () => {
  // Add this here:
  registerLocalVideoProtocol()

// And this anywhere:
function registerLocalVideoProtocol () {
  protocol.registerFileProtocol('local-video', (request, callback) => {
    const url = request.url.replace(/^local-video:\/\//, '')
    // Decode URL to prevent errors when loading filenames with UTF-8 chars or chars like "#"
    const decodedUrl = decodeURI(url) // Needed in case URL contains spaces
    try {
      // eslint-disable-next-line no-undef
      return callback(path.join(__static, decodedUrl))
    } catch (error) {
      console.error(
        'ERROR: registerLocalVideoProtocol: Could not get file path:',
        error
      )
    }
  })
}
```

Then, use `src="local-video://vid.mp4"`. This works in both build and serve.

**Comment by azeranex** [comment]
Thanks, I confirm it's working. It can also replace `createProtocol('app')` and create "app" protocol with this method instead. So you don't need to create separated protocol anymore.

**Comment by starhu521** [comment]
@nklayman thanks a lot. But can we make the function of the custom app protocol the same as the file protocol?

**Comment by AMDZEN3** [comment]
I'm glad I found this, I was going crazy trying to figure out why videos wouldn't play from my public folder.  Is this still the only solution though?  This means I have to have special code to set the src for the video based on whether its electron or web.  Its doable but not ideal.

**Comment by pat-flew** [comment]
I ran into a similar sounding issue where videos would not play over the app protocol in a distribution build. 

Serving over a file protocol, or adding `stream: true` to the app protocol scheme privileges appears to have fixed it.

**Comment by eladcandroid** [comment]
@azeranex 
Did you find any solution? I tried the local-video://  solution but still get an error like this:

![WhatsApp Image 2021-03-03 at 3 30 05 PM](https://user-images.githubusercontent.com/13297000/109812963-63898580-7c35-11eb-8296-c0e1549fb9ed.jpeg)

**Comment by azeranex** [comment]
@eladcandroid You can use file protocol instead. Take a look ar here for more info: https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#changing-the-file-loading-protocol

You can also enable stream support in default protocol.
https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#handling-static-assets

Please note that you might find it's really slow compared to file protocol. (Especially when you seeking)

**Comment by eladcandroid** [comment]
@azeranex 
I tried it also with no luck.. Can you please update your repo https://github.com/azeranex/vue-cli-electron-video-demo with a working fix?

**Comment by azeranex** [comment]
@eladcandroid Done

**Comment by eladcandroid** [comment]
@azeranex Works on my Mac M1. Thanks! 👍

**Comment by anderssonq** [comment]
> @azeranex thanks for the repo, I realized I was testing it on a project that used the file protocol enabled instead of `app://` . I did find a solution though that works for `app://` protocol:
> 
> ```js
> // in background.js
> app.on('ready', async () => {
>   // Add this here:
>   registerLocalVideoProtocol()
> 
> // And this anywhere:
> function registerLocalVideoProtocol () {
>   protocol.registerFileProtocol('local-video', (request, callback) => {
>     const url = request.url.replace(/^local-video:\/\//, '')
>     // Decode URL to prevent errors when loading filenames with UTF-8 chars or chars like "#"
>     const decodedUrl = decodeURI(url) // Needed in case URL contains spaces
>     try {
>       // eslint-disable-next-line no-undef
>       return callback(path.join(__static, decodedUrl))
>     } catch (error) {
>       console.error(
>         'ERROR: registerLocalVideoProtocol: Could not get file path:',
>         error
>       )
>     }
>   })
> }
> ```
> 
> Then, use `src="local-video://vid.mp4"`. This works in both build and serve.

Works on Linux ! thanks

**Comment by martinsnajdr** [comment]
I have a problem when trying to seek the video on Windows. It just jumps to the start to video.

**Comment by JavaScriptam** [comment]
> @azeranex thanks for the repo, I realized I was testing it on a project that used the file protocol enabled instead of `app://` 🤦. I did find a solution though that works for `app://` protocol:
> 
> ```js
> // in background.js
> app.on('ready', async () => {
>   // Add this here:
>   registerLocalVideoProtocol()
> 
> // And this anywhere:
> function registerLocalVideoProtocol () {
>   protocol.registerFileProtocol('local-video', (request, callback) => {
>     const url = request.url.replace(/^local-video:\/\//, '')
>     // Decode URL to prevent errors when loading filenames with UTF-8 chars or chars like "#"
>     const decodedUrl = decodeURI(url) // Needed in case URL contains spaces
>     try {
>       // eslint-disable-next-line no-undef
>       return callback(path.join(__static, decodedUrl))
>     } catch (error) {
>       console.error(
>         'ERROR: registerLocalVideoProtocol: Could not get file path:',
>         error
>       )
>     }
>   })
> }
> ```
> 
> Then, use `src="local-video://vid.mp4"`. This works in both build and serve.

works on windows 11 and 10!!!  thanks

**Comment by alexeiidonetskiy** [comment]
@azeranex Thanks mate, I was struggling 2 hours before I found this solution in issues.
MacOS M1, Windows emulator — works 🎉
