### ISSUE TITLE
Uncaught ReferenceError: __dirname is not defined

### ISSUE THREAD

**Issue by swifterchong** [nklayman/vue-cli-plugin-electron-builder#874]
Describe:

1.  I create a vue project with following commands:
```
vue create electron-app
vue add vuetify
vue add electron-builder
```

2. Then I added 'console.log(__dirname)' into <script></script> of App.vue.

3. I run the project with command `npm run electron:serve`.  But I got an error bellow:

![image](https://user-images.githubusercontent.com/43359786/86114322-f305f400-bafc-11ea-9dbf-471114fa156c.png)

I had try to resolve this problem for several hours, but nothing goes well.

Who can help me?

**Comment by iamazik** [comment]
Related: https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/891
>The error you are getting is related to `nodeIntegration`, see the [docs](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration) for instructions on how to use IPC without `nodeIntegration`.
