### ISSUE TITLE
Make `spectron` optional

### ISSUE THREAD

**Issue by 2xAA** [nklayman/vue-cli-plugin-electron-builder#876]
**Is your feature request related to a problem? Please describe.**
`spectron` requires `electron-chromedriver` which adds huge build-time bloat to any project using `vue-cli-plugin-electron-builder`.
Some projects may not need Spectron.

**Describe the solution you'd like**
Make `spectron` optional.

**Describe alternatives you've considered**
~~1. I could stay on Electron 7 forever.~~
2. I might be consuming this package incorrectly, is there a way to use `vue-cli-plugin-electron-builder` 2.X without `electron-chromedriver` being built?

**Additional context**
N/A.

**Comment by nklayman** [comment]
Spectron is only a `devDependency` on this plugin, and shouldn't be installed. The only reason spectron would be installed is if you answered yes to the spectron question when invoking the generator. If this is the case, you can remove it from your `package.json`.
