### ISSUE TITLE
IFrame production electron

### ISSUE THREAD

**Issue by Alexel37** [nklayman/vue-cli-plugin-electron-builder#880]
Good day,
We are using iframe to have authorization inside our window (requested by customer).
In "npm run electron:serve" everything works fine we successfully receive callback from another server after entering credentials
and proceed with standard flow.
Unfortunately in "npm run electron:build" after entering credentials we have blank part of iframe and any redirection url to our electron application.

**Comment by nklayman** [comment]
Try using [webview](https://www.electronjs.org/docs/api/webview-tag) instead of `iframe`. It offers better security and control of the external content. See https://www.electronjs.org/docs/tutorial/web-embeds for more details.

**Comment by Alexel37** [comment]
We figured out that in development we start localhost server and we receive callback url to localhost while in production we actually registering it as app protocol and still receiving callback to localhost)

**Comment by nklayman** [comment]
I'm not sure what you mean. Can you elaborate on what you figured out and maybe include some code snippets as well?

**Comment by Alexel37** [comment]
To summarize
1. On development we have app running on localhost
2. On production we are not running on localhost, thats why we don't receive callback
