### ISSUE TITLE
I can not use the native module ffi-napi, please help!

### ISSUE THREAD

**Issue by fflrichard** [nklayman/vue-cli-plugin-electron-builder#884]
**Describe the bug**
I have read those issues about native module and tried many ways, but still can not work.

<pre>
Error: No native build was found for platform=win32 arch=ia32 runtime=electron abi=80 uv=1 libc=glibc
    at Function.load.path (webpack:///./node_modules/node-gyp-build/index.js?:56:9)
    at load (webpack:///./node_modules/node-gyp-build/index.js?:21:30)
    at eval (webpack:///./node_modules/ref-napi/lib/ref.js?:8:111)
    at Object../node_modules/ref-napi/lib/ref.js (C:\Users\xxx\Desktop\workspace\abc\dist_electron\index.js:1637:1)
    at __webpack_require__ (C:\Users\xxx\Desktop\workspace\abc\dist_electron\index.js:20:30)
    at eval (webpack:///./src/background.js?:14:13)
    at Module../src/background.js (C:\Users\xxx\Desktop\workspace\abc\dist_electron\index.js:1823:1)
    at __webpack_require__ (C:\Users\xxx\Desktop\workspace\abc\dist_electron\index.js:20:30)
    at eval (webpack:///multi_./src/background.js?:1:18)
    at Object.0 (C:\Users\xxx\Desktop\workspace\abc\dist_electron\index.js:1834:1)
Done in 41.66s.
</pre>

**To Reproduce**
install the latest vue-cli
<pre>
vue create abc
vue add electron-builder
yarn add ffi-napi
</pre>
then add the code to top of background.js
<pre>
const ffi = require('ffi-napi');
const ref = require('ref-napi');
</pre>

add the code to vue.config.js
<pre>
module.exports = {
    pluginOptions: {
        electronBuilder: {
            externals: ['ffi-napi', 'ref-napi'],
        }
    }
};
</pre>
run `yarn electron:serve` and will have error

**Expected behavior**
Expected no error

**Screenshots**

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 
 - terminal output from running `vue info`:
<pre>
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) ia32 Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz
  Binaries:
    Node: 12.18.1 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files (x86)\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.4.6
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.4.6
    @vue/cli-plugin-babel: ~4.4.0 => 4.4.6
    @vue/cli-plugin-router: ~4.4.0 => 4.4.6
    @vue/cli-plugin-vuex: ~4.4.0 => 4.4.6
    @vue/cli-service: ~4.4.0 => 4.4.6
    @vue/cli-shared-utils:  4.4.6
    @vue/component-compiler-utils:  3.1.2
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    vue: ^2.6.11 => 2.6.11
    vue-cli-plugin-electron-builder: ~2.0.0-rc.4 => 2.0.0-rc.4
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.3
    vue-router: ^3.2.0 => 3.3.4
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.4.0 => 3.5.1
  npmGlobalPackages:
    @vue/cli: Not Found
</pre>

**Additional context**
I have successfully used serialport, sequelize, mysql2 this way. but the ffi module always went wrong
I have tried to edit the vue.config.js , for example add externals to configureWebpack, but it did not work.
also i've tried to run the code with x64 nodejs, and it did not work.
please help!

**Comment by DaZhaoLis** [comment]
i got same issue.

**Comment by DaZhaoLis** [comment]
dyld: lazy symbol binding failed: Symbol not found: _napi_set_instance_data
  Referenced from: /Users/xx/Documents/xx/node_modules/ffi-napi/prebuilds/darwin-x64/node.napi.uv1.node
  Expected in: flat namespace
dyld: Symbol not found: _napi_set_instance_data
  Referenced from: /Users/xx/Documents/xx/node_modules/ffi-napi/prebuilds/darwin-x64/node.napi.uv1.node
  Expected in: flat namespace

node version:v14.5.0 and i use n to change node version

**Comment by nklayman** [comment]
Try running `yarn electron-builder install-app-deps` and then post the output here.

**Comment by fflrichard** [comment]
> Try running `yarn electron-builder install-app-deps` and then post the output here.

nothing changed, show the same error

**Comment by nklayman** [comment]
When that command runs, does it find and build `ffi-napi` and `ref-napi`? The command output should show both those modules being built.

**Comment by fflrichard** [comment]
> When that command runs, does it find and build `ffi-napi` and `ref-napi`? The command output should show both those modules being built.

yes, build successfully.
<pre>
yarn electron-builder install-app-deps
yarn run v1.21.1
$ C:\Users\xxx\Desktop\workspace\abc\node_modules\.bin\electron-builder install-app-deps
  • electron-builder  version=22.7.0
  • rebuilding native dependencies  dependencies=ffi-napi@3.0.1, ref-napi@2.0.3 platform=win32 arch=ia32
  • rebuilding native dependency  name=ffi-napi version=3.0.1
  • rebuilding native dependency  name=ref-napi version=2.0.3
Done in 30.58s.
</pre>

would you please take a moment to try it, I have tried on MacBook and it shows the same error.

**Comment by nklayman** [comment]
You need to install `ref-napi` as a dependency if you are importing it. I got the same error as you and then fixed it by running `yarn add ref-napi`.
