### ISSUE TITLE
Set URL from API in background.js

### ISSUE THREAD

**Issue by yehtut-indexzero** [nklayman/vue-cli-plugin-electron-builder#886]
Hi Everyone,
Is there a way to load dynamic URL in background.js. I have API which will expose URL. In the following example, I hard coded URL. I want to get URL value from API. Thank you 

```
if (process.env.WEBPACK_DEV_SERVER_URL) {
    // Load the url of the dev server if in development mode
    win.loadURL('https://google.com')    
    // if (!process.env.IS_TEST) win.webContents.openDevTools()
  } else {
    createProtocol('app')
    // Load the index.html when not in development
    win.loadURL('app://./index.html')
  }  
```

**Comment by nklayman** [comment]
You can just query the api from the main process (`background.js`) and then pass in the url to `win.loadUrl`. You could also change from the renderer process (`App.vue`) with `window.location.replace`. If this doesn't help, please explain your problem a little more, I don't understand it completely.
