### ISSUE TITLE
Use the electron command in the VUE file

### ISSUE THREAD

**Issue by jahnli** [nklayman/vue-cli-plugin-electron-builder#887]
In addition to requiring electron in each VUE file, is the electron command provided to use globally in the VUE

such as  this.$electron.ipcRenderer.send('')     

It will be more convenient

**Comment by nklayman** [comment]
You can create your own [mixin](https://vuejs.org/v2/guide/mixins.html) for this if you want. Also check out [vue-electron](https://github.com/SimulatedGREG/vue-electron). I'm not going to add this feature to this plugin as I think it is out-of-scope.
