### ISSUE TITLE
How set preload

### ISSUE THREAD

**Issue by wuyuedefeng** [nklayman/vue-cli-plugin-electron-builder#89]
```
function createMainWindow () {
  const window = new BrowserWindow({
     webPreferences: {
	plugins: true,
	nodeIntegration: true,
	nativeWindowOpen: false,
	preload: __dirname + '/preload.js'
     }
  })
}
```
not work

if I put `preload.js` in `dist_electron`, dev is OK. but not work when i generate dmg file.

**Comment by nklayman** [comment]
Try putting it in public and using `__static` instead of `__dirname`. Should work for both dev and serve.

**Comment by nklayman** [comment]
see the [docs on vue cli](https://cli.vuejs.org/guide/html-and-static-assets.html#preload).

**Comment by Neko911** [comment]
how about preload with typescript?
