### ISSUE TITLE
Auto Reload doesn't always work when using babel for background.js

### ISSUE THREAD

**Issue by rathboma** [nklayman/vue-cli-plugin-electron-builder#890]
**Describe the bug**

I have code I need to share between the `main` and `background` processes, and I use modern imports - `import { foo } from './bar', so I needed to add babel for all js files.

So I added the following to my vue.config.js under `electronBuilder: {`
```js
      chainWebpackMainProcess: config => {
        config.module
          .rule('babel')
          .test(/\.js$/)
          .use('babel')
          .loader('babel-loader')
          .options({
            presets: [['@babel/preset-env', { modules: false }]],
            plugins: [
              ['@babel/plugin-proposal-decorators', {legacy: true}],
              ['@babel/plugin-proposal-class-properties', {loose: true}]
            ]
          })
      },


```

Now I have two problems:
1. live builds (using `electron:serve` are much slower
2. Changing my `common` code isn't detected and the app doesn't restart (most of the time?)

Any thoughts? Is this the best way to support babel for `background.js`?

**Comment by nklayman** [comment]
The slow builds is due to babel having to do lots of work transpiling the js, there isn't much you could do about it, but you could try an alternative like [swc](https://github.com/swc-project/swc).

As for the restarting not working, what do you mean by "`common` code"?

**Comment by rathboma** [comment]
@nklayman So I basically have three directories: `background`, `app`, and `common`, stuff in `common` is used by both js targets.

I'm not sure it's anything to do with it being shared code, but I do find that since enabling Babel for background it doesn't always pick up changes.

QQ -- is my vue.config.js code above the right way to do this?

**Comment by nklayman** [comment]
If you have code in files other than `background.js`, you will have to configure `mainProcessWatch` so that electron is restarted when they change:

```js
// vue.config.js

module.exports = {
  pluginOptions: {
    electronBuilder: {
      // Your main process file will be added by default
      mainProcessWatch: ['src/myFile1', 'src/myFile2']
    }
  }
}
```

**Comment by rathboma** [comment]
These are just the entry files? Or any file that can change?

**Comment by nklayman** [comment]
Any file that can change, it doesn't traverse imports to find more files to watch.
