### ISSUE TITLE
[Help] Confusion regarding main and background processes when using events

### ISSUE THREAD

**Issue by ajthinking** [nklayman/vue-cli-plugin-electron-builder#891]
When researching the IPC pattern I see there should be a `Main` process and a `Renderer` process.
In my project created with this repo I see `main.js` and `background.js`. In the terminology I seen, does the `main.js` correspond to the `Renderer` process and `background.js` to the `Main` process?

Context - Im failing to bind events as documented here: https://www.electronjs.org/docs/api/ipc-main. In my Vue component:
```js
myMethod() {
    const { ipcRenderer } = require('electron')
    console.log(ipcRenderer.sendSync('synchronous-message', 'ping')) // prints "pong"
    ipcRenderer.on('asynchronous-reply', (event, arg) => {
        console.log(arg) // prints "pong"
    })
    ipcRenderer.send('asynchronous-message', 'ping')
}
```

In `background.js`
```js
const { ipcMain } = require('electron')
ipcMain.on('asynchronous-message', (event, arg) => {
  console.log(arg) // prints "ping"
  event.reply('asynchronous-reply', 'pong')
})

ipcMain.on('synchronous-message', (event, arg) => {
  console.log(arg) // prints "ping"
  event.returnValue = 'pong'
})
})
```

This compiles fine but gives me an error as soon as the app loads:
```
index.js?bdb9:4 Uncaught ReferenceError: __dirname is not defined
    at eval (index.js?bdb9:4)
    at Object../node_modules/electron/index.js (chunk-vendors.js:1035)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at eval (Splash.vue?7ed9:22)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/Splash.vue?vue&type=script&lang=js& (app.js:986)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at eval (Splash.vue?9c8e:1)
    at Module../src/components/Splash.vue?vue&type=script&lang=js& (app.js:1271)
```

Did I misunderstood the processes or where to emit/listen for events?

**Comment by nklayman** [comment]
Unfortunately, Vue CLI uses `main.js` for the Vue app, which is the renderer process. This means I had to use another name for the main process, so I went with `background.js`. The error you are getting is related to `nodeIntegration`, see [the docs](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration) for instructions on how to use IPC without `nodeIntegration`. Other than that, your code looks fine.
