### ISSUE TITLE
web pack electron fork-child process

### ISSUE THREAD

**Issue by arsh09** [nklayman/vue-cli-plugin-electron-builder#898]
Hello, 

I am using 2 different JavaScript files as child processes in electron side (main process). I forked these processed in main process of Electron. 

This works quite well. I can also include them in the electron builder options' extraResources. However, they are copied as it is in the resources folder after built and install. 

I was wondering if there is a way to make an extra web-pack bundled for them so that after built, they are minified etc. 

Looking forward for suggestions

Thank you

**Comment by nklayman** [comment]
Maybe try using web workers? See [the guide](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#web-workers) for instructions.

**Comment by nklayman** [comment]
I haven't tested it in the main process though, you could also use webpack entries and child_process if web workers don't work.

**Comment by arsh09** [comment]
Thank you for the suggestion. 

I tried web workers a month ago. They worked in renderer process but I could not use node native libraries (such as ffi or ref) in them. 

Could you please eloborate on your second suggestion about web pack entries and child processes?

**Comment by nklayman** [comment]
Sure, to spawn the process:
```js
import { fork } from 'child_process'
import path from 'path'
fork(path.join(__dirname, 'child.js'))
```

And in `vue.config.js`:
```js
const path = require('path')

module.exports = {
  pluginOptions: {
    electronBuilder: {
      chainWebpackMainProcess(config) {
        config.entry('child').add(path.join(__dirname, 'src/child.js'))
      }
    }
  }
}
```

**Comment by arsh09** [comment]
@nklayman  Thank you.

I will try it today. 

Have a good day :)
