### ISSUE TITLE
Strict MIME type checking error

### ISSUE THREAD

**Issue by jadams2305** [nklayman/vue-cli-plugin-electron-builder#90]
**Describe the bug**

I'm able to run my application with `npm run serve:electron` with no issue.  but when I build it with `npm run build:electron`, the package builds,  I can run the EXE file but nothing loads in the electron window. In the chrome developer console I got the following message
```
Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.

chunk-vendors.13c5b05b.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**To Reproduce**
 `npm run build:electron`

**Expected behavior**
The application runs

**Environment (please complete the following information):**
 - OS and version: Winddows 10+
 - Node version: v8.9.4
 - npm version: 5.6.0
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 1.0.0-rc.1
 - other vue plugins used: "vue-template-compiler": "^2.5.17"
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**

**Comment by nklayman** [comment]
Have you made any changes to your `background.js`? If so, save them. Try deleting the file and running `vue invoke electron-builder`. This will re-create your background file with the latest updates I have made. It should work then.

**Comment by jadams2305** [comment]
It worked! Thanks a lot!
