### ISSUE TITLE
Window edges not rounded

### ISSUE THREAD

**Issue by XENOTpro** [nklayman/vue-cli-plugin-electron-builder#907]
**Describe the bug**
None of the four corners of the electron window are rounded like any other electron application.

**To Reproduce**
vue create my-app
vue add electron-builder
npm run electron:serve

**Expected behavior**
I would expect rounded corners.

**Screenshots**
<img width="336" alt="Screenshot 2020-07-19 at 22 28 35" src="https://user-images.githubusercontent.com/53019576/87884555-38885380-ca0f-11ea-9268-35d7a0392c47.png">

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: no
 - (if possible) link to your repo: no
 - terminal output from running `vue info`:
  System:
    OS: macOS 10.16
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 12.9.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.89
    Edge: Not Found
    Firefox: 78.0.1
    Safari: 14.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.4.6 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.4.6 
    @vue/cli-plugin-babel: ~4.4.0 => 4.4.6 
    @vue/cli-plugin-eslint: ~4.4.0 => 4.4.6 
    @vue/cli-plugin-router:  4.4.6 
    @vue/cli-plugin-vuex:  4.4.6 
    @vue/cli-service: ~4.4.0 => 4.4.6 
    @vue/cli-shared-utils:  4.4.6 
    @vue/component-compiler-utils:  3.1.2 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.11 
    vue-cli-plugin-electron-builder: ~2.0.0-rc.4 => 2.0.0-rc.4 
    vue-cli-plugin-vuetify: ~2.0.6 => 2.0.6 
    vue-eslint-parser:  7.1.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.3 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
    vuetify: ^2.2.11 => 2.3.4 
    vuetify-loader: ^1.3.0 => 1.6.0 
  npmGlobalPackages:
    @vue/cli: 4.4.6

**Additional context**
no

**Comment by nklayman** [comment]
If you run the [electron-quick-start](https://github.com/electron/electron-quick-start) repo with the same version of electron, does that have rounded corners? Also, are the corners rounded in production (`npm run electron:build && dist_electron/mac-unpacked/[APP NAME]`)?

**Comment by XENOTpro** [comment]
Thank you, for your reply. Indeed, this also occurs with the electron-quick-start repo, so I assume this is an error is a result macOS Big Sur's UI update and is part of Electron itself.
