### ISSUE TITLE
After I built it, the Tray icon didn't show and the functionality wasn't available

### ISSUE THREAD

**Issue by jahnli** [nklayman/vue-cli-plugin-electron-builder#908]
![image](https://user-images.githubusercontent.com/20943608/87908999-ff48f580-ca99-11ea-8478-d268d8e85bb2.png)

**Comment by nklayman** [comment]
Please open a new issue that follows the bug report template. I need more information to debug this.

**Comment by bruceauyeung** [comment]
@jahnli i even can not get it work in dev mode. did this work for you ?
