### ISSUE TITLE
[Question] Multiple preload files

### ISSUE THREAD

**Issue by steelersd** [nklayman/vue-cli-plugin-electron-builder#912]
Hello,

I'm following the multiple [preload-files](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#preload-files) example.

```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      // Or, for multiple preload files:
      preload: { preload: 'src/preload.js', otherPreload: 'src/preload2.js' }
    }
  }
}
```

This will generate two files in `dist_electron`, `preload.js` and `otherPreload.js`

I can't seem to figure out how to references both of these files in the BrowserWindow's `preload` config. 
```js
win = new BrowserWindow({
  width: 800,
  height: 600,
  webPreferences: {
    // Use pluginOptions.nodeIntegration, leave this alone
    // See nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#node-integration for more info
    // nodeIntegration: process.env.ELECTRON_NODE_INTEGRATION,
+   preload: path.join(__dirname, 'preload.js')
  }
})
```

I was hoping I could pass an array to `preload`, but that doesn't seem to be valid. 

Any help is appreciated. Thanks!

**Comment by nklayman** [comment]
Electron doesn't support multiple preload files (https://github.com/electron/electron/issues/2406). The reason you can specify multiple preload files in the config is if you need to have a different preload file for another `BrowserWindow` instance. What you can do instead is `import 'preload2.js'` in `preload.js`, which should have the same effect.
