### ISSUE TITLE
SQLite package has not been found installed - TypeORM use in background.js when built with webpack. Deployed Mac app only

### ISSUE THREAD

**Issue by rathboma** [nklayman/vue-cli-plugin-electron-builder#914]
**Describe the bug**
Ok, this is a weird one.

I'm getting this familiar error again, but only in a specific situation:
1. I've moved to using webpack for both `background.js` and `main.js`
2. Works fine in development mode
3. Works fine on Linux and Windows builds
4. Production builds don't work on MacOS.

When I added TypeORM months ago I followed [your suggestion](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/699#issuecomment-609523589) on making it external to get it working in the renderer.

Now I'm [also using webpack for background.js](https://github.com/beekeeper-studio/beekeeper-studio/blob/master/vue.config.js) I am seeing [the issue again](https://github.com/beekeeper-studio/beekeeper-studio/issues/249).

It's NOT happening in dev mode `electron:serve`, but only when I deploy a notarized mac build.

Update: It also doesn't happen on ALL macs.... although it does happen on my test macbook, and the test macbook of my collaborator, just not a mac instance I rent through an online remote desktop system.

I know this is almost certainly nothing to do with your Vue plugin, but you seem to be a wizard of native dependency issues, so hoping you might have some thoughts?

**Comment by rathboma** [comment]
Here's the DMG file with the issue: https://github.com/beekeeper-studio/beekeeper-studio/releases/download/v1.6.4/Beekeeper-Studio-1.6.4.dmg

You can run it from the terminal to see the problem:

`/Applications/Beekeeper\ Studio.app/Content/MacOS/Beekeeper\ Studio`

**Comment by nklayman** [comment]
I don't have a mac to test it, but I'm working on setting up a hackintosh and I can give it a shot once it is ready.

**Comment by rathboma** [comment]
Thanks! It's totally blocking our release, so it's totally bumming us out :-(

**Comment by rathboma** [comment]
Figured it out (sort of). It was something to do with Mac notarization. I'm not sure entirely what I did, but here is my two line change that fixed it:

https://github.com/beekeeper-studio/beekeeper-studio/commit/691357bda09121b01efe72419244821f468fe551

Hopefully if someone has this in the future they can stumble across this
