### ISSUE TITLE
Change Menu Bar

### ISSUE THREAD

**Issue by thesmartrenovation** [nklayman/vue-cli-plugin-electron-builder#916]
Hello, 

Is there a way to edit the menu bar you see in the picture? I've searched but can't find a way to edit it to show relevant information. 

![image](https://user-images.githubusercontent.com/57076657/88245810-1e908000-cc5e-11ea-8a95-0ac1139051f9.png)

As well as changing the name "Electron" in the menu.

**Comment by nklayman** [comment]
See the [Electron Menu docs](https://www.electronjs.org/docs/api/menu). The window name should be taken from your `package.json`, but it may only show in builds (`yarn electron:build`).
