### ISSUE TITLE
ERROR Vue CLI build failed

### ISSUE THREAD

**Issue by sderbidge** [nklayman/vue-cli-plugin-electron-builder#923]
**NEVERMIND**
I found a solution to the problem, all I had to do was delete vue.config.js file

**Describe the bug**
When I run npm run electron:build I get this error:

 ERROR  Vue CLI build failed. Please resolve any issues with your build and try again.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! one-key@0.1.0 electron:build: `vue-cli-service electron:build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the one-key@0.1.0 electron:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**To Reproduce**
I'm not sure how to reproduce the behavior

**Expected behavior**
I expected to have the command build and package the electron app into a disc_electron folder

**Screenshots**
![error](https://user-images.githubusercontent.com/55034668/88597435-6fb8bf00-d024-11ea-94c8-4f1d29822b2d.PNG)

**Comment by nklayman** [comment]
Closing as you fixed it.
