### ISSUE TITLE
wrong build ouput main name

### ISSUE THREAD

**Issue by godtoy** [nklayman/vue-cli-plugin-electron-builder#925]
i  change the vue.config.js mainProcessFile to ```xxx/main/index.js```
![image](https://user-images.githubusercontent.com/13638996/88658505-217bec80-d106-11ea-97de-f3a4ed1e786c.png)

i got this error
```
(node:13820) UnhandledPromiseRejectionWarning: Error: Application entry file "index.js" in the "E:\workspaces\dragon\electron-update-demo\dist_electron\win-unpacked\resources\app.asar" does not exi
st. Seems like a wrong configuration.

```

**Comment by godtoy** [comment]
it fixed when i change package.json main entry

**Comment by RoamIn** [comment]
me too , so i keep it....but stiill feel strange
