### ISSUE TITLE
configureWebpack vue.config.js, Won't npm run electron:build

### ISSUE THREAD

**Issue by sderbidge** [nklayman/vue-cli-plugin-electron-builder#928]
**Nevermind, I commented out the if statement and the build works**

**Describe the bug**
Build fails when vue.config.js contains the following code:
```
module.exports = {
    configureWebpack: config => {
        if (process.env.NODE_ENV === 'production') {
            config.output.publicPath = `${process.cwd()}/dist/`
        }
        config.target = 'electron-renderer'
    }
}
```
I'd like to use this code if possible to be able to require("electron") in the renderer process so I can use the ipcRenderer to communicate between the main and renderer process.

**To Reproduce**
Place the code from above into a vue.config.js file in the project with the plugin

**Expected behavior**
Be able to run `npm run electron:build` without any errors

**Environment (please complete the following information):**
Electron: 9.0.0
Node:  12.18.2
npm: 6.14.5

**Additional context**
npm run electron:serve works just fine, it's only when the app gets packaged that the error shows up, here's the screenshot of the error.

![error](https://user-images.githubusercontent.com/55034668/88705833-4b64ed00-d0cd-11ea-9d8e-681ffe6f1158.PNG)

**Comment by nklayman** [comment]
The target is already set to `electron-renderer` automatically, so no need to do that manually. You will either have to [enable nodeIntegration or use a preload script](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration) if you want to use `ipc` though.

**Comment by Nisthar** [comment]
@nklayman I was getting errors like `fs.existsSync is not a function` 

I had to set `electron-renderer` manually to fix it.
