### ISSUE TITLE
Cannot access remote resources on Mac

### ISSUE THREAD

**Issue by wststone** [nklayman/vue-cli-plugin-electron-builder#932]
**Describe the bug**
I am trying to add a "fake" navigation bar to my web application, and I wanted to use BrowserView to embed my actual web application. However, the BrowserView was always blank when I tried to serve it in local development. First, I thought it might be an issue with Vue or Vue Router, but a colleague of mine served it on his window machine and it worked. Then it occurred to me that it wasn't just the BrowserView, so I set the loadURL of the BroswerWindow to a remote URL such as (https://github.com) it also did not display.

**To Reproduce**
example: 
` win = new BrowserWindow({
    width: 800,
    height: 600,
    preload: path.join(__dirname, 'preload.js'),
    webPreferences: {
      nodeIntegration: true,
      webSecurity: false,
      nodeIntegrationInSubFrames: false,
      allowRunningInsecureContent: true,
      devTools: true
    }
  })
`
`win.loadURL("https://www.electronjs.org/") `

**Expected behavior**
Remote URL webcontent displays

**Screenshots**
repo: https://github.com/wststone/desktop-app

**Environment (please complete the following information):**
```
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.105
    Edge: Not Found
    Firefox: 70.0.1
    Safari: 13.1.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.4.6 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.4.6 
    @vue/cli-plugin-babel: ~4.4.0 => 4.4.6 
    @vue/cli-plugin-eslint: ~4.4.0 => 4.4.6 
    @vue/cli-plugin-router: ~4.4.0 => 4.4.6 
    @vue/cli-plugin-vuex: ~4.4.0 => 4.4.6 
    @vue/cli-service: ~4.4.0 => 4.4.6 
    @vue/cli-shared-utils:  4.4.6 
    @vue/component-compiler-utils:  3.2.0 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.11 
    vue-cli-plugin-electron-builder: ~2.0.0-rc.4 => 2.0.0-rc.4 
    vue-cli-plugin-vuetify: ~2.0.7 => 2.0.7 
    vue-eslint-parser:  7.1.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.3 
    vue-router: ^3.2.0 => 3.3.4 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
    vuetify: ^2.2.11 => 2.3.6 
    vuetify-loader: ^1.3.0 => 1.6.0 
    vuex: ^3.4.0 => 3.5.1 
  npmGlobalPackages:
    @vue/cli: 4.4.1
```

**Additional context**
I've tried changing the configurations around webPrefereces in both the BrowserWindow and BrowserView, and had no success, also worth noting that I tried to load URLs in a native electron app without Vue on Mac and it worked, also on Windows machine it can work. Thank anyone who is able to help in advance!

**Comment by wststone** [comment]
It seems that this is more of unable to access remote resources as I tried putting couple images with src of remote location such as imgur and it also didn't work, hence the change of title.

**Comment by nklayman** [comment]
It worked fine for me on linux, but I don't have a mac to test it on. I will hopefully be getting one soon (within a month or so), but until then I can't try and fix it. It seems like it may be a problem with electron since it works on windows/linux, just not mac. Try using electron v8 and see if that helps.

**Comment by wststone** [comment]
> It worked fine for me on linux, but I don't have a mac to test it on. I will hopefully be getting one soon (within a month or so), but until then I can't try and fix it. It seems like it may be a problem with electron since it works on windows/linux, just not mac. Try using electron v8 and see if that helps.

It worked on electron v8! Thank you very much for the reply and suggestion, it helped me a lot with development! You can close the issue now!

**Comment by nklayman** [comment]
You're welcome! You should open an issue on the Electron github repo (if there isn't one already), as this seems like a significant bug.
