### ISSUE TITLE
Unable to resolve fluent-ffmpeg

### ISSUE THREAD

**Issue by Lutetium-Vanadium** [nklayman/vue-cli-plugin-electron-builder#938]
**Describe the bug**
Fails to run when importing `fluent-ffmpeg`. There was another issue #139 which gave a solution, but that isn't working for me.

**To Reproduce**
- `yarn add fluent-ffmpeg`
- `yarn serve:electron`

**Screenshots**
![image](https://user-images.githubusercontent.com/52347010/89126782-2aa1fa80-d506-11ea-9e05-874670e8442a.png)

**Environment (please complete the following information):**
vue.config.js:
```javascript
module.exports = {
  pluginOptions: {
    electronBuilder: {
      chainWebpackRendererProcess: config => {
        config.plugin('define').tap(args => {
          args[0]['process.env.FLUENTFFMPEG_COV'] = false;
          return args;
        });
      },
      nodeIntegration: true,
      customFileProtocol: './',
      builderOptions: {
        // ...
      },
    },
  },
};
```

**Versions**
`fluent-ffmpeg`: `^2.1.2`
`vue-cli-plugin-electron-builder`: `~2.0.0-rc.4`
[Link to repo](https://github.com/Lutetium-Vanadium/Music-Vue)

It is not being imported by any code thats a part of the render process.

Is there anything that I got wrong in the config, or maybe a version problem?

**Comment by nklayman** [comment]
You can also try marking `fluent-ffmpeg` as an external, see [these docs](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules). The webpack config fixed it for me though.

**Comment by Lutetium-Vanadium** [comment]
@nklayman that worked, thanks!
