### ISSUE TITLE
[poll] Change command names?

### ISSUE THREAD

**Issue by nklayman** [nklayman/vue-cli-plugin-electron-builder#94]
It seems that, for node scripts, the format `platform:command` is more popular than `command:platform`. To better match this format, I could change the commands to `electron:build/serve`. The old commands would still work, but would log a deprication message. React with a thumbs up if it should be changed, thumbs down if I should leave it. If you want, explain your reasoning in the comments.

Thanks for all your input!

**Comment by pksunkara** [comment]
I don't get it. You changed the commands names to `electron:*` in code but kept them as `*:electron` in README. Shouldn't you change them in README too?

**Comment by nklayman** [comment]
Closing as they are renamed as part of 1.0.0-rc.4.
