### ISSUE TITLE
Code signing error

### ISSUE THREAD

**Issue by jaythegeek** [nklayman/vue-cli-plugin-electron-builder#941]
I am getting a failure when running a build on Mac os for Mac os. It is failing at the code signing stage. 

**Failed to parse entitlements**

I'm at a loss as to what it may be. Cannot find any reference to it elsewhere.

Is this because of electron-builder needing to be updated to the latest version? I'm currently using 22.2.0 as per the beta channel of this repo. 

Any help would be much appreciated.

**Comment by nklayman** [comment]
I'd suggest opening an issue on the [electron builder repository](https://github.com/electron-userland/electron-builder) instead as it handles the code signing and is throwing the error. You could also try deleting `package-lock.json` or `yarn.lock`, then reinstalling dependencies to update to the latest electron-builder version, which may fix it.
