### ISSUE TITLE
(node:19656) ExtensionLoadWarning: Warnings loading extension at

### ISSUE THREAD

**Issue by yayxs** [nklayman/vue-cli-plugin-electron-builder#943]
## 描述
完整的控制台信息如下： 
---

App running at:
  - Local:   http://localhost:8081/
  - Network: http://192.168.13.233:8081/
  Note that the development build is not optimized.
  To create a production build, run yarn build.

\  Bundling main process...

 DONE  Compiled successfully in 1526ms                                                                                      18:09:11  File                      Size                     Gzipped

  dist_electron\index.js    744.94 KiB               165.80 KiB

  Images and other types of assets omitted.

 INFO  Launching Electron...
(node:19656) ExtensionLoadWarning: Warnings loading extension at C:\Users\1\AppData\Roaming\electron-vue-desktop\extensions\nhdogjmejiglipccpnnnanhbledajbpd: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'update_url'. Permission 'contextMenus' is unknown or URL pattern is malformed. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
>
-----
## 执行步骤
1. vue add proName
2. vue add electron-builder
3. yarn electron:serve
**之后在控制台信息如上所示**

### vue info

 System:
    OS: Windows 10 10.0.16299
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.105
    Edge: Spartan (41.16299.1480.0)
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.4.6
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.4.6
    @vue/cli-plugin-babel: ~4.4.0 => 4.4.6
    @vue/cli-plugin-eslint: ~4.4.0 => 4.4.6
    @vue/cli-plugin-router: ~4.4.0 => 4.4.6
    @vue/cli-plugin-vuex: ~4.4.0 => 4.4.6
    @vue/cli-service: ~4.4.0 => 4.4.6
    @vue/cli-shared-utils:  4.4.6
    @vue/component-compiler-utils:  3.2.0
    @vue/eslint-config-airbnb: ^5.0.2 => 5.1.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    vue: ^2.6.11 => 2.6.11
    vue-cli-plugin-electron-builder: ~2.0.0-rc.4 => 2.0.0-rc.4
    vue-eslint-parser:  7.1.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.3
    vue-router: ^3.2.0 => 3.3.4
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.4.0 => 3.5.1
  npmGlobalPackages:
    @vue/cli: Not Found

## 其他
项目也是可以正常运行，只是控制台有`ExtensionLoadWarning ` 信息

**Comment by RowinRuizendaal** [comment]
I am having the same issue, while launching Electron:

```js
Launching Electron...
(node:20136) ExtensionLoadWarning: Warnings loading extension at C:\Users\AppData\Roaming\electron\extensions\nhdogjmejiglipccpnnnanhbledajbpd: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'update_url'. Permission 'contextMenus' is unknown or URL pattern is malformed. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the 
system.

Force killing Electron (process #27392)

```

**Comment by nklayman** [comment]
This is an issue with electron/vue devtools, not this plugin. See https://github.com/electron/electron/issues/23662 for details.

One thing that seems to have helped some people is to add `await` on [this line](https://github.com/yayxs/electron-vue-desktop/blob/master/src/background.js#L29) of your `background.js`.

**Comment by denyncrawford** [comment]
Same here.
```sh
ExtensionLoadWarning: Warnings loading extension at C:\Users\denyncrawford\AppData\Roaming\mainframe\extensions\nhdogjmejiglipccpnnnanhbledajbpd: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'update_url'. 
Permission 'contextMenus' is unknown or URL pattern is malformed. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
```
I've already tryed [this](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/943#issuecomment-668744393)
😞

**Comment by m4heshd** [comment]
Still having this issue. And the extension isn't working even though it's installed.

**Comment by andgeno** [comment]
Also having the same issue and the suggested fix does not work for me as well.

**Comment by m4heshd** [comment]
@andgeno Are you happen to be using Vue 3?

**Comment by andgeno** [comment]
> 
> 
> @andgeno Are you happen to be using Vue 3?

Yes, Vue 3.0.0

**Comment by m4heshd** [comment]
Use this instead of the predefined VueJS Devtools. It's the beta that supports Vue 3.

```
try {
  await installExtension({
    id: 'ljjemllljcmogpfapbkkighbhhppjdbg', //Vue Devtools beta
    electron: '>=1.2.1'
  })
} catch (e) {
  console.error('Vue Devtools failed to install:', e.toString())
}
```

**Comment by andgeno** [comment]
> 
> 
> Use this instead of the predefined VueJS Devtools. It's the beta that supports Vue 3.
> 
> ```
> try {
>   await installExtension({
>     id: 'ljjemllljcmogpfapbkkighbhhppjdbg', //Vue Devtools beta
>     electron: '>=1.2.1'
>   })
> } catch (e) {
>   console.error('Vue Devtools failed to install:', e.toString())
> }
> ```

Works. Thanks! 👍🏼

**Comment by leifcr** [comment]
@nklayman Please consider changing to the beta devtools that support vue 3.

**Comment by nklayman** [comment]
You can change it yourself in `background.js`. By default, I'm going to use the stable version for, well, stability.

**Comment by jeremyong** [comment]
Is this still accurate? vue 3 has had a stable release for some time

**Comment by loriswave** [comment]
> ```js
> Vue Devtools beta
> ```

Can you explain a little bit how to use this? only replace  of
```
   try {
      await installExtension(VUEJS3_DEVTOOLS)
    } catch (e) {
      console.error('Vue Devtools failed to install:', e.toString())
    }
```

**Comment by nklayman** [comment]
Yeah, replacing those lines should be all you need to do.

**Comment by hrsndb1n** [comment]
still getting this warning.
Vue-cli 4, Vue 2, Electron 13, macOS

**Comment by fsk** [comment]
```
app.on("ready", async () => {
  if (isDevelopment && !process.env.IS_TEST) {
    // Install Vue Devtools
    try {
      await installExtension({
        id: "ljjemllljcmogpfapbkkighbhhppjdbg", //Vue Devtools beta
        electron: ">=1.2.1",
      });
    } catch (e) {
      console.error("Vue Devtools failed to install:", e.toString());
    }
  }
  createWindow();
});
```

This is code blog in my background.js file. But still i have same issue.

Error is;

```
[(node:12040) ExtensionLoadWarning: Warnings loading extension at C:\Users\Dell\AppData\Roaming\meetoz-dsk\extensions\ljjemllljcmogpfapbkkighbhhppjdbg:
  Unrecognized manifest key 'browser_action'.
  Unrecognized manifest key 'update_url'.
  Permission 'contextMenus' is unknown or URL pattern is malformed.
  Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.](url)
```


How can i fix.?

**Comment by abe1272001** [comment]
Same issue show up!

**Comment by kevinmnm** [comment]
Any solution..? I have same problem.

**Comment by krishnaguragain** [comment]
```
await installExtension({
        id: 'fjjopahebfkmlmkekebhacaklbhiefbn', //Vue Devtools beta
        electron: '>=1.2.1'
      })
```
      
      
This is working for me till now.
