### ISSUE TITLE
Why vue-cli-plugin-electron-builder changes package-lock.json semver so much?

### ISSUE THREAD

**Issue by oopsplus** [nklayman/vue-cli-plugin-electron-builder#95]
After creating a fresh vue project with "vue create ***" command, then run "vue add electron-builder", I find that there are quite lots of diff in the package-lock.json file. Many of them are changing to the semver of the dependency packages, like this:
```
-        "jsesc": "2.5.1",
-        "lodash": "4.17.11",
-        "source-map": "0.5.7",
-        "trim-right": "1.0.1"
+        "jsesc": "^2.5.1",
+        "lodash": "^4.17.5",
+        "source-map": "^0.5.0",
+        "trim-right": "^1.0.1"
```

The strangest thing is that the version are either being "downgraded"(like 4.17.11-->^4.17.5) or "widen"(like 1.0.1 --> ^1.0.1). 
Why the vue-cli-plugin-electron-builder plugin do this?

Hope to hear from you, nklayman~

**Comment by oopsplus** [comment]
Sorry for the bad layout in the previous post. Here is the new one:

After creating a fresh vue project with "vue create ***" command, then run "vue add electron-builder", I find that there are quite lots of diff in the package-lock.json file. Many of them are changing to the semver of the dependency packages, like this:

```
-        "jsesc": "2.5.1",
-        "lodash": "4.17.11",
-        "source-map": "0.5.7",
-        "trim-right": "1.0.1"
+        "jsesc": "^2.5.1",
+        "lodash": "^4.17.5",
+        "source-map": "^0.5.0",
+        "trim-right": "^1.0.1"
```

The strangest thing is that the version are either being "downgraded"(like 4.17.11-->^4.17.5) or "widen"(like 1.0.1 --> ^1.0.1).
Why the vue-cli-plugin-electron-builder plugin do this?

Hope to hear from you, nklayman~

**Comment by nklayman** [comment]
I think this is just from installing electron and other deps. Try installing without invoking:
```
npm i -D vue-cli-plugin-electron-builder electron
```
And see if the `package-lock.json` has changed. If it is, it is out of my control, as it is not caused by the plugin's generator. If not, re-open this issue, and I will look into it further. Thanks.
