### ISSUE TITLE
mac build .exe,uninstall error

### ISSUE THREAD

**Issue by simple-YoungBadBoy** [nklayman/vue-cli-plugin-electron-builder#953]
When the program is in use, everything is normal. After packaged and installed on windows, I think the second installation will directly overwrite the previous version, but no, the installation progress will be stuck in half.

Then I delete it, it will report an error:
![image](https://user-images.githubusercontent.com/20324269/89712341-d0e87700-d9c2-11ea-9209-788c5150fb9b.png)

command:
"electron:build-win64": "vue-cli-service electron:build --windows --x64"

**Comment by nklayman** [comment]
[Electron Builder](https://github.com/electron-userland/electron-builder) is used to build the executables and handles the update process, you should open an issue on their repository instead. I'd also suggest rebuilding both versions, fully uninstalling the app, and then trying the install/update process again as one build may be corrupted.
