### ISSUE TITLE
Open PDF from <a href="assets/abc.pdf"></a> in Electron app not working

### ISSUE THREAD

**Issue by KamalArora1** [nklayman/vue-cli-plugin-electron-builder#963]
I want to open PDF from static path 'assets' or 'static' but Blank black screen is coming while opening pdf. 

I have used: <a href="#" onclick="window.open('static/abc.pdf', '_blank'); return false;">open pdf</a> or 
<a href="static/abc.pdf" target="_blank">open pdf</a>. But black screen is coming.

I have used vuejs 2+ version and electron 9.1.0 version for the same. Can someone help me out?

**Comment by nklayman** [comment]
Please open a new issue that follows the bug report template.
