### ISSUE TITLE
missing node_modules

### ISSUE THREAD

**Issue by xiaosu95** [nklayman/vue-cli-plugin-electron-builder#964]
**Describe the bug**
The dependencies option cannot be packaged into node_modules

**To Reproduce**
```
"dependencies": {
    "axios": "^0.19.2",
    "core-js": "^3.6.5",
    "crypto-js": "^4.0.0",
    "electron-log": "^4.2.2",
    "electron-store": "^5.2.0",
    "find-process": "^1.4.3",
    "vue": "^2.6.11",
    "vue-router": "^3.2.0",
    "vue2-animate": "^2.1.3",
    "vuex": "^3.4.0"
  }
```
npm run electron:build

**Expected behavior**
the dependencies option cannot be packaged into node_modules

**Screenshots**
![image](https://user-images.githubusercontent.com/22880707/89891504-c5d25880-dc07-11ea-85a9-51539fe055a6.png)
no electron-log

**Environment (please complete the following information):**
"vue-cli-plugin-electron-builder": "~2.0.0-rc.1",
vue-cli:~4.4.0

**Comment by xiaosu95** [comment]
Has been resolved, has externals attributes

**Comment by Nisthar** [comment]
@xiaosu95 how do you resolve it? i have the same issue.

**Comment by nklayman** [comment]
Probably by [marking those deps as externals](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules).

**Comment by Nisthar** [comment]
externals assume the module is installed in users pc. Right? how does it work on production build then?

**Comment by nklayman** [comment]
No, it still includes the module with the installer. The difference is that it is kept as a separate file whereas non-externals are inlined into your build with webpack.
