### ISSUE TITLE
Change electron-builder to peer dep please.

### ISSUE THREAD

**Issue by erguotou520** [nklayman/vue-cli-plugin-electron-builder#97]
**Is your feature request related to a problem? Please describe.**
As this issue said, `electron-builder > 20.6.0` has a windows pack issue.

**Describe the solution you'd like**
Change `electron-builder` to peerDependencies.

**Comment by nklayman** [comment]
I don't think I can do this as I `require` electron-builder directly to use the programmatic API. What is the specific issue # with electron-builder? I can look into fixing it or locking electron-builder to an earlier version in this plugin.

**Comment by erguotou520** [comment]
Emmm~. The api changed in some version, so you are right. Maybe waiting for `electron-builder` to fix it.
