### ISSUE TITLE
electron Bytenode

### ISSUE THREAD

**Issue by simple-YoungBadBoy** [nklayman/vue-cli-plugin-electron-builder#973]
Hello, do you have any idea to add bytenode to the current cli to ensure the security of the source code? Google has little information on this aspect
I'm looking forward to your reply. Have a nice day

**Comment by nklayman** [comment]
I do not plan to add bytenode support to this plugin unless paid to do so. If a company's code is so important that it has to be protected by bytenode, then they can afford to add it themselves or pay me to add it. I don't think it's fair for me to freely expend my time to do something that will only benefit proprietary products.

**Comment by jiumengs** [comment]
@simple-YoungBadBoy  我搞定了

**Comment by huiXinYiJi** [comment]
> @simple-YoungBadBoy 我搞定了

how to get it?
