### ISSUE TITLE
fs.readdir error :ENOENT: no such file or directory

### ISSUE THREAD

**Issue by yexiaodong** [nklayman/vue-cli-plugin-electron-builder#976]
**Describe the bug**
electron:build is ok, but electron:serve error（no such file or directory, scandir ）

**To Reproduce**
preload.js
window.fsReaddir = async function(dir) {
    return new Promise((resolve,rejects)=>{
        fs.readdir(dir, (err, files) =>{
            if (err) {
                console.error(err);
                rejects([])
            }
            resolve(files)
        });
    })
};
xxx.vue
 async getFiles() {
      this.list = await window.fsReaddir('public/workplace')
 },

**Screenshots**
![image](https://user-images.githubusercontent.com/13914749/90349283-e10bf080-e06b-11ea-8787-5d5a4688a092.png)

**Environment (please complete the following information):**
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.3 - D:\soft\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - D:\soft\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.12.1
    @vue/babel-preset-jsx:  1.1.1
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.1.1
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  3.12.1
    @vue/cli-plugin-babel: ^3.12.1 => 3.12.1
    @vue/cli-plugin-eslint: ^3.12.1 => 3.12.1
    @vue/cli-service: ^3.12.1 => 3.12.1
    @vue/cli-shared-utils:  3.12.1
    @vue/component-compiler-utils:  3.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.2.3 => 5.2.3 (4.7.1)
    vue: ^2.6.11 => 2.6.11
    vue-cli-plugin-electron-builder: ~2.0.0-rc.4 => 2.0.0-rc.4
    vue-eslint-parser:  5.0.0 (2.0.3)
    vue-hot-reload-api:  2.3.4
    vue-json-component: ^0.4.1 => 0.4.1
    vue-lazyload:  1.2.3
    vue-loader:  15.7.1
    vue-markdown: ^2.2.4 => 2.2.4
    vue-router: ^3.1.6 => 3.1.6
    vue-style-loader:  4.1.2
    vue-tabs-chrome: ^0.5.1 => 0.5.1
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.2.0 => 3.2.0
  npmGlobalPackages:
    @vue/cli: Not Found

**Comment by nklayman** [comment]
It looks like the directory you are trying to read does not exist. Try reading a path you know exists, like `C:\Users` and see if that works.

**Comment by yexiaodong** [comment]
that is ok. But i want to read project path, like public/workplace 
![image](https://user-images.githubusercontent.com/13914749/90457476-38729500-e12e-11ea-9d04-2b384fe6b368.png)

**Comment by nklayman** [comment]
Are you sure that it works in build and not dev? It looks like it should only work in development, that folder is not available in build as the cwd is different.

**Comment by yexiaodong** [comment]
sorry, I write it wrongly. it work in development,not work in build

**Comment by nklayman** [comment]
The code is fine, the issue is that the `public` directory has a different path in build. The `__static` variable is auto injected to your code and resolved to the `public` dir in both build and dev. Try this code instead:
```js
// At the top of <script>
import path from 'path'

// In place of your existing call
this.list = await window.fsReaddir(path.join(__static, 'workplace'))
```
