### ISSUE TITLE
Skip webpack bundling for main process

### ISSUE THREAD

**Issue by pksunkara** [nklayman/vue-cli-plugin-electron-builder#98]
**Is your feature request related to a problem? Please describe.**
Using webpack to bundle the main process has a few issues that is preventing my app from working. The main thing I would like to use is `require`'ing a plugin from the `appData` directory which can be installed by the user. But since, webpack rewrites `require`, it is currently impossible to do this.

**Describe the solution you'd like**
An option skip bundling of main process

**Comment by nklayman** [comment]
Try marking that plugin as an external:
```javascript
// vue.config.js

module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['your-plugin-name']
    }
  }
}
```
If that doesn't work, re-open this issue.

**Comment by pksunkara** [comment]
Unfortunately, it didn't solve the problem since I am using `remote.require.resolve` in https://github.com/pksunkara/electron-plugin-manager. This is the error I get (in renderer),

```
"TypeError: requireFn.resolve is not a function"
```

where `requireFn = electron.remote.require`

And the plugins I load are going to be named differently and are based on path. So, yes, I can provide a path regex, but it still didn't solve the above issue I am facing.

**Comment by nklayman** [comment]
I added this, but keep in mind you will have to do the following things to make it work:

first, run `yarn add --dev nklayman/vue-cli-plugin-electron-builder && vue invoke electron-builder`

1. replace any `import` statements with `require` in `background.js`
2. remove any imports from `vue-cli-plugin-electron-builder/lib`, and remove `await installVueDevtools()` and `createProtocol('app')`, as they both use es6 import/export
3. remove `<base href="app://./ />` and `require('module').globalPaths...` from `public/index.html`
[electron-test.zip](https://github.com/nklayman/vue-cli-plugin-electron-builder/files/2439077/electron-test.zip)

4. replace `process.env.WEBPACK_DEV_SERVER_URL` with `http://localhost:8080` in background.js
5. remove `require('module').globalPaths...` from `background.js`
6. replace `const isDevelopment...` with `const isDevelopment = path.extname(__dirname) !== '.asar'`
7. Make sure to always run `electron:build` with the `--legacy` arg.

Note that

- Vue devtools will not work
- native modules will not work
- if the dev server is anything other then `localhost:8080`, it will not work
- If `--legacy` is not passed to build, it will not work

I attached a blank project that works without bundling the main process, use this as a reference.

**Comment by pksunkara** [comment]
> remove any imports from vue-cli-plugin-electron-builder/lib, and remove await installVueDevtools() and createProtocol('app'), as they both use es6 import/export

I think you should probably change your `lib` code away from es6 as that will support both webpack and non-webpack.

> replace const isDevelopment... with const isDevelopment = path.extname(__dirname) !== '.asar'

What about finding if the environment is test? I am doing it like this for now which probably wont work, right?

```js
const isOnlyDevelopment = isDevelopment && !process.env.IS_TEST;
```

**Comment by nklayman** [comment]
Process.env.IS_TEST would be undefined as it is only set when testing with spectron. As for making the built in helpers use commonjs, that would eliminate tree shaking for people using webpack (99.99% of users). If you really need them, just copy them into your project and convert them yourself. I don't want to focus on using without webpack, as there are too many things you have to change/won't work, and it is an extremely edge case scenario.

**Comment by pksunkara** [comment]
Got it, thanks. Could you do a release?

**Comment by pksunkara** [comment]
So, I tried what you said, but it's not working. I took you example and tried, but it's not working too.

1. Extract your example and install deps
2. Add the following to `src/main.js`
```js
import { remote } from 'electron';

remote.require.resolve('test');
```
3. Run `electron:serve`
4. I see the following error
```
electron__WEBPACK_IMPORTED_MODULE_5__.remote.require.resolve is not a function
```

**Comment by nklayman** [comment]
if you look at [the docs](https://github.com/electron/electron/blob/master/docs/api/remote.md#remoterequiremodule), there is no `remote.require.resolve`. This issue is related to electron, rather than this plugin. Try opening an issue (or better yet, submit a PR), to add this feature.

**Comment by divrse** [comment]
@nklayman I followed your instructions and got it working but have the following issue:
It doesn't  work on linux.
My mac OS machine can run it fine with no bundled main process but when I use my linux machine, only the vueJS app runs and electron never starts.
I use your test code as well with the same result.
I run via
```bash
npm run electron:serve
```
works fine on mac, and electron never starts on linux, but the vue app runs (on 8080)

**Comment by nklayman** [comment]
Try deleting your node_modules folder and reinstalling deps. That often fixes the issue for me. Disabling webpack shouldn't affect the launching of electron whatsoever.

**Comment by pksunkara** [comment]
I don't know if you have changed the main process bundling now, but the default ES6 background.js is now working with my `remote.require` used from https://github.com/pksunkara/electron-plugin-manager

**Comment by divrse** [comment]
@nklayman Hey, been building a VueJS app with this and ran into one issue now.
I am fixing code errors and for some reason runtime errors (ones that start after app launches)
give me no details where the issue is, bug only the issue.
For example see this screenshot.
<img width="475" alt="screen shot 2019-03-08 at 1 05 15 am" src="https://user-images.githubusercontent.com/18077440/54019065-173b0600-413f-11e9-9bf5-c8fca300d311.png">


I have an unexpected token error, but do not know where.
My console doesn't show me this error, just the alert.
Have any idea how to get more detailed errors in this popup?

**Comment by pksunkara** [comment]
Why did you reply in this issue instead of creating a new one? @nklayman Please lock this.

**Comment by nklayman** [comment]
See [debugging the main process](https://electronjs.org/docs/tutorial/debugging-main-process). Also see the [plugin docs](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/testingAndDebugging.html#main-process-background-file).
