### ISSUE TITLE
why use vue-cli-plugin-electron-builder to build the program, it is display whiteboard after starting the program

### ISSUE THREAD

**Issue by dx01259** [nklayman/vue-cli-plugin-electron-builder#995]
hello, who knows when i use vue-cli-plugin-electron-builder to build the program, it is display whiteboard after starting the program.  as shown in the following figure.
<img width="788" alt="image" src="https://user-images.githubusercontent.com/13490100/90875599-fe2a2180-e3d3-11ea-9d85-c11dd75dbeab.png">
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true,
      externals: ['sqlite3'],
      mainProcessFile: './src/background.js',
      nodeModulesPath: ['../../node_modules', './node_modules'],
      builderOptions: {
        appId: 'com.janeim.app',
        productName: 'JaneIM',
        copyright: 'Copyright @2020 by 追逐',
        mac: {
          icon: './public/favicon.png',
        },
        win: {
          icon: './public/favicon.ico',
          target: ['zip', 'nsis']
        },
        nsis: {
          oneClick: false, 
          allowElevation: true, 
          allowToChangeInstallationDirectory: true, 
          installerIcon: './public/favicon.ico',
          uninstallerIcon: './public/favicon.ico', 
          installerHeaderIcon: './public/favicon.ico', 
          createDesktopShortcut: true, 
          createStartMenuShortcut: true, 
          shortcutName: 'JaneIm' 
        }
      }
    }
  }
}
```

**Comment by nklayman** [comment]
@dx01259 The app loads fine if you remove the `partion: 'persist:tmp'` from the `new BroserWindow` call. Why do you need the partition setting?

**Comment by dx01259** [comment]
@nklayman thanks very much, when i remove the partion: 'persist:tmp' that program is solved. this is the first time i've used electron to create desktop program. please forgive me do not know much for the 'persist: tmp' effection.  Thanks again!

**Comment by nklayman** [comment]
Glad that helped!

**Comment by svebaa** [comment]
Hello, I have the same problem as @dx01259, but I need to use it and I am wondering why does that have to be removed?

**Comment by lokhmanov-m** [comment]
when you run in electron, check router mode. 
check when you start electron, router mode should be hash `mode: process.env.IS_ELECTRON ? 'hash' : 'history',`
